<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State7TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of Connecticut.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 7, 'city' => 'Botsford'],
                ['state_id' => 7, 'city' => 'Hawleyville'],
                ['state_id' => 7, 'city' => 'Monroe'],
                ['state_id' => 7, 'city' => 'Newtown'],
                ['state_id' => 7, 'city' => 'Sandy Hook'],
                ['state_id' => 7, 'city' => 'Shelton'],
                ['state_id' => 7, 'city' => 'Stevenson'],
                ['state_id' => 7, 'city' => 'Bridgeport'],
                ['state_id' => 7, 'city' => 'Trumbull'],
                ['state_id' => 7, 'city' => 'Easton'],
                ['state_id' => 7, 'city' => 'Stratford'],
                ['state_id' => 7, 'city' => 'Sherman'],
                ['state_id' => 7, 'city' => 'Bethel'],
                ['state_id' => 7, 'city' => 'Brookfield'],
                ['state_id' => 7, 'city' => 'Cos Cob'],
                ['state_id' => 7, 'city' => 'Danbury'],
                ['state_id' => 7, 'city' => 'New Fairfield'],
                ['state_id' => 7, 'city' => 'Darien'],
                ['state_id' => 7, 'city' => 'Fairfield'],
                ['state_id' => 7, 'city' => 'Georgetown'],
                ['state_id' => 7, 'city' => 'Greenwich'],
                ['state_id' => 7, 'city' => 'Greens Farms'],
                ['state_id' => 7, 'city' => 'New Canaan'],
                ['state_id' => 7, 'city' => 'Norwalk'],
                ['state_id' => 7, 'city' => 'Old Greenwich'],
                ['state_id' => 7, 'city' => 'Redding Center'],
                ['state_id' => 7, 'city' => 'Redding Ridge'],
                ['state_id' => 7, 'city' => 'Ridgefield'],
                ['state_id' => 7, 'city' => 'Riverside'],
                ['state_id' => 7, 'city' => 'Westport'],
                ['state_id' => 7, 'city' => 'Weston'],
                ['state_id' => 7, 'city' => 'Southport'],
                ['state_id' => 7, 'city' => 'Redding'],
                ['state_id' => 7, 'city' => 'Wilton'],
                ['state_id' => 7, 'city' => 'Stamford'],
                ['state_id' => 7, 'city' => 'Avon'],
                ['state_id' => 7, 'city' => 'Bloomfield'],
                ['state_id' => 7, 'city' => 'Windsor'],
                ['state_id' => 7, 'city' => 'Bristol'],
                ['state_id' => 7, 'city' => 'Burlington'],
                ['state_id' => 7, 'city' => 'Broad Brook'],
                ['state_id' => 7, 'city' => 'Canton'],
                ['state_id' => 7, 'city' => 'Canton Center'],
                ['state_id' => 7, 'city' => 'Collinsville'],
                ['state_id' => 7, 'city' => 'East Berlin'],
                ['state_id' => 7, 'city' => 'East Glastonbury'],
                ['state_id' => 7, 'city' => 'East Granby'],
                ['state_id' => 7, 'city' => 'East Hartland'],
                ['state_id' => 7, 'city' => 'East Windsor Hill'],
                ['state_id' => 7, 'city' => 'Farmington'],
                ['state_id' => 7, 'city' => 'Glastonbury'],
                ['state_id' => 7, 'city' => 'Granby'],
                ['state_id' => 7, 'city' => 'Berlin'],
                ['state_id' => 7, 'city' => 'Manchester'],
                ['state_id' => 7, 'city' => 'New Britain'],
                ['state_id' => 7, 'city' => 'North Canton'],
                ['state_id' => 7, 'city' => 'North Granby'],
                ['state_id' => 7, 'city' => 'Plainville'],
                ['state_id' => 7, 'city' => 'Poquonock'],
                ['state_id' => 7, 'city' => 'Rocky Hill'],
                ['state_id' => 7, 'city' => 'Simsbury'],
                ['state_id' => 7, 'city' => 'South Glastonbury'],
                ['state_id' => 7, 'city' => 'South Windsor'],
                ['state_id' => 7, 'city' => 'Suffield'],
                ['state_id' => 7, 'city' => 'Tariffville'],
                ['state_id' => 7, 'city' => 'Enfield'],
                ['state_id' => 7, 'city' => 'Unionville'],
                ['state_id' => 7, 'city' => 'East Windsor'],
                ['state_id' => 7, 'city' => 'Weatogue'],
                ['state_id' => 7, 'city' => 'West Granby'],
                ['state_id' => 7, 'city' => 'West Hartland'],
                ['state_id' => 7, 'city' => 'West Simsbury'],
                ['state_id' => 7, 'city' => 'West Suffield'],
                ['state_id' => 7, 'city' => 'Windsor Locks'],
                ['state_id' => 7, 'city' => 'Hartford'],
                ['state_id' => 7, 'city' => 'West Hartford'],
                ['state_id' => 7, 'city' => 'East Hartford'],
                ['state_id' => 7, 'city' => 'Wethersfield'],
                ['state_id' => 7, 'city' => 'Newington'],
                ['state_id' => 7, 'city' => 'Marion'],
                ['state_id' => 7, 'city' => 'Marlborough'],
                ['state_id' => 7, 'city' => 'Milldale'],
                ['state_id' => 7, 'city' => 'Plantsville'],
                ['state_id' => 7, 'city' => 'Southington'],
                ['state_id' => 7, 'city' => 'Canaan'],
                ['state_id' => 7, 'city' => 'Colebrook'],
                ['state_id' => 7, 'city' => 'East Canaan'],
                ['state_id' => 7, 'city' => 'Falls Village'],
                ['state_id' => 7, 'city' => 'Lakeville'],
                ['state_id' => 7, 'city' => 'New Hartford'],
                ['state_id' => 7, 'city' => 'Norfolk'],
                ['state_id' => 7, 'city' => 'Pine Meadow'],
                ['state_id' => 7, 'city' => 'Barkhamsted'],
                ['state_id' => 7, 'city' => 'Riverton'],
                ['state_id' => 7, 'city' => 'Salisbury'],
                ['state_id' => 7, 'city' => 'Sharon'],
                ['state_id' => 7, 'city' => 'Taconic'],
                ['state_id' => 7, 'city' => 'Winchester Center'],
                ['state_id' => 7, 'city' => 'Winsted'],
                ['state_id' => 7, 'city' => 'Bantam'],
                ['state_id' => 7, 'city' => 'Bethlehem'],
                ['state_id' => 7, 'city' => 'Bridgewater'],
                ['state_id' => 7, 'city' => 'Cornwall'],
                ['state_id' => 7, 'city' => 'Cornwall Bridge'],
                ['state_id' => 7, 'city' => 'Gaylordsville'],
                ['state_id' => 7, 'city' => 'Goshen'],
                ['state_id' => 7, 'city' => 'Kent'],
                ['state_id' => 7, 'city' => 'Lakeside'],
                ['state_id' => 7, 'city' => 'Litchfield'],
                ['state_id' => 7, 'city' => 'Morris'],
                ['state_id' => 7, 'city' => 'New Milford'],
                ['state_id' => 7, 'city' => 'New Preston Marble Dale'],
                ['state_id' => 7, 'city' => 'Northfield'],
                ['state_id' => 7, 'city' => 'Oakville'],
                ['state_id' => 7, 'city' => 'Pequabuck'],
                ['state_id' => 7, 'city' => 'Plymouth'],
                ['state_id' => 7, 'city' => 'Roxbury'],
                ['state_id' => 7, 'city' => 'South Kent'],
                ['state_id' => 7, 'city' => 'Terryville'],
                ['state_id' => 7, 'city' => 'Thomaston'],
                ['state_id' => 7, 'city' => 'Torrington'],
                ['state_id' => 7, 'city' => 'Harwinton'],
                ['state_id' => 7, 'city' => 'Washington'],
                ['state_id' => 7, 'city' => 'Washington Depot'],
                ['state_id' => 7, 'city' => 'Watertown'],
                ['state_id' => 7, 'city' => 'West Cornwall'],
                ['state_id' => 7, 'city' => 'Woodbury'],
                ['state_id' => 7, 'city' => 'Centerbrook'],
                ['state_id' => 7, 'city' => 'Chester'],
                ['state_id' => 7, 'city' => 'Clinton'],
                ['state_id' => 7, 'city' => 'Cobalt'],
                ['state_id' => 7, 'city' => 'Cromwell'],
                ['state_id' => 7, 'city' => 'Deep River'],
                ['state_id' => 7, 'city' => 'Killingworth'],
                ['state_id' => 7, 'city' => 'Durham'],
                ['state_id' => 7, 'city' => 'East Haddam'],
                ['state_id' => 7, 'city' => 'East Hampton'],
                ['state_id' => 7, 'city' => 'Essex'],
                ['state_id' => 7, 'city' => 'Haddam'],
                ['state_id' => 7, 'city' => 'Higganum'],
                ['state_id' => 7, 'city' => 'Ivoryton'],
                ['state_id' => 7, 'city' => 'Middlefield'],
                ['state_id' => 7, 'city' => 'Middle Haddam'],
                ['state_id' => 7, 'city' => 'Middletown'],
                ['state_id' => 7, 'city' => 'Moodus'],
                ['state_id' => 7, 'city' => 'Old Saybrook'],
                ['state_id' => 7, 'city' => 'Portland'],
                ['state_id' => 7, 'city' => 'Rockfall'],
                ['state_id' => 7, 'city' => 'Westbrook'],
                ['state_id' => 7, 'city' => 'Ansonia'],
                ['state_id' => 7, 'city' => 'Beacon Falls'],
                ['state_id' => 7, 'city' => 'Branford'],
                ['state_id' => 7, 'city' => 'Cheshire'],
                ['state_id' => 7, 'city' => 'Derby'],
                ['state_id' => 7, 'city' => 'Guilford'],
                ['state_id' => 7, 'city' => 'Madison'],
                ['state_id' => 7, 'city' => 'Meriden'],
                ['state_id' => 7, 'city' => 'Milford'],
                ['state_id' => 7, 'city' => 'North Branford'],
                ['state_id' => 7, 'city' => 'Northford'],
                ['state_id' => 7, 'city' => 'North Haven'],
                ['state_id' => 7, 'city' => 'Orange'],
                ['state_id' => 7, 'city' => 'Oxford'],
                ['state_id' => 7, 'city' => 'Seymour'],
                ['state_id' => 7, 'city' => 'South Britain'],
                ['state_id' => 7, 'city' => 'Southbury'],
                ['state_id' => 7, 'city' => 'Wallingford'],
                ['state_id' => 7, 'city' => 'New Haven'],
                ['state_id' => 7, 'city' => 'Hamden'],
                ['state_id' => 7, 'city' => 'West Haven'],
                ['state_id' => 7, 'city' => 'Bethany'],
                ['state_id' => 7, 'city' => 'Waterbury'],
                ['state_id' => 7, 'city' => 'Prospect'],
                ['state_id' => 7, 'city' => 'Wolcott'],
                ['state_id' => 7, 'city' => 'Middlebury'],
                ['state_id' => 7, 'city' => 'Naugatuck'],
                ['state_id' => 7, 'city' => 'Lebanon'],
                ['state_id' => 7, 'city' => 'North Franklin'],
                ['state_id' => 7, 'city' => 'New London'],
                ['state_id' => 7, 'city' => 'Baltic'],
                ['state_id' => 7, 'city' => 'East Lyme'],
                ['state_id' => 7, 'city' => 'Bozrah'],
                ['state_id' => 7, 'city' => 'Gales Ferry'],
                ['state_id' => 7, 'city' => 'Gilman'],
                ['state_id' => 7, 'city' => 'Mashantucket'],
                ['state_id' => 7, 'city' => 'Ledyard'],
                ['state_id' => 7, 'city' => 'Groton'],
                ['state_id' => 7, 'city' => 'Hanover'],
                ['state_id' => 7, 'city' => 'Jewett City'],
                ['state_id' => 7, 'city' => 'Montville'],
                ['state_id' => 7, 'city' => 'Mystic'],
                ['state_id' => 7, 'city' => 'Niantic'],
                ['state_id' => 7, 'city' => 'North Stonington'],
                ['state_id' => 7, 'city' => 'Norwich'],
                ['state_id' => 7, 'city' => 'Preston'],
                ['state_id' => 7, 'city' => 'Oakdale'],
                ['state_id' => 7, 'city' => 'Old Lyme'],
                ['state_id' => 7, 'city' => 'Old Mystic'],
                ['state_id' => 7, 'city' => 'Quaker Hill'],
                ['state_id' => 7, 'city' => 'South Lyme'],
                ['state_id' => 7, 'city' => 'Stonington'],
                ['state_id' => 7, 'city' => 'Pawcatuck'],
                ['state_id' => 7, 'city' => 'Taftville'],
                ['state_id' => 7, 'city' => 'Uncasville'],
                ['state_id' => 7, 'city' => 'Versailles'],
                ['state_id' => 7, 'city' => 'Voluntown'],
                ['state_id' => 7, 'city' => 'Waterford'],
                ['state_id' => 7, 'city' => 'West Mystic'],
                ['state_id' => 7, 'city' => 'Yantic'],
                ['state_id' => 7, 'city' => 'Colchester'],
                ['state_id' => 7, 'city' => 'Salem'],
                ['state_id' => 7, 'city' => 'Hadlyme'],
                ['state_id' => 7, 'city' => 'North Westchester'],
                ['state_id' => 7, 'city' => 'Ellington'],
                ['state_id' => 7, 'city' => 'Bolton'],
                ['state_id' => 7, 'city' => 'Vernon Rockville'],
                ['state_id' => 7, 'city' => 'Somers'],
                ['state_id' => 7, 'city' => 'Somersville'],
                ['state_id' => 7, 'city' => 'Stafford'],
                ['state_id' => 7, 'city' => 'Stafford Springs'],
                ['state_id' => 7, 'city' => 'Staffordville'],
                ['state_id' => 7, 'city' => 'Tolland'],
                ['state_id' => 7, 'city' => 'Amston'],
                ['state_id' => 7, 'city' => 'Andover'],
                ['state_id' => 7, 'city' => 'Columbia'],
                ['state_id' => 7, 'city' => 'Coventry'],
                ['state_id' => 7, 'city' => 'Hebron'],
                ['state_id' => 7, 'city' => 'Mansfield Center'],
                ['state_id' => 7, 'city' => 'Mansfield Depot'],
                ['state_id' => 7, 'city' => 'South Willington'],
                ['state_id' => 7, 'city' => 'Storrs Mansfield'],
                ['state_id' => 7, 'city' => 'Willington'],
                ['state_id' => 7, 'city' => 'Willimantic'],
                ['state_id' => 7, 'city' => 'Abington'],
                ['state_id' => 7, 'city' => 'Ballouville'],
                ['state_id' => 7, 'city' => 'Brooklyn'],
                ['state_id' => 7, 'city' => 'Chaplin'],
                ['state_id' => 7, 'city' => 'Danielson'],
                ['state_id' => 7, 'city' => 'Dayville'],
                ['state_id' => 7, 'city' => 'Eastford'],
                ['state_id' => 7, 'city' => 'East Killingly'],
                ['state_id' => 7, 'city' => 'East Woodstock'],
                ['state_id' => 7, 'city' => 'Fabyan'],
                ['state_id' => 7, 'city' => 'Grosvenor Dale'],
                ['state_id' => 7, 'city' => 'Hampton'],
                ['state_id' => 7, 'city' => 'North Grosvenordale'],
                ['state_id' => 7, 'city' => 'North Windham'],
                ['state_id' => 7, 'city' => 'Pomfret'],
                ['state_id' => 7, 'city' => 'Pomfret Center'],
                ['state_id' => 7, 'city' => 'Putnam'],
                ['state_id' => 7, 'city' => 'Quinebaug'],
                ['state_id' => 7, 'city' => 'Rogers'],
                ['state_id' => 7, 'city' => 'Scotland'],
                ['state_id' => 7, 'city' => 'South Windham'],
                ['state_id' => 7, 'city' => 'South Woodstock'],
                ['state_id' => 7, 'city' => 'Thompson'],
                ['state_id' => 7, 'city' => 'Ashford'],
                ['state_id' => 7, 'city' => 'Windham'],
                ['state_id' => 7, 'city' => 'Woodstock'],
                ['state_id' => 7, 'city' => 'Woodstock Valley'],
                ['state_id' => 7, 'city' => 'Canterbury'],
                ['state_id' => 7, 'city' => 'Central Village'],
                ['state_id' => 7, 'city' => 'Moosup'],
                ['state_id' => 7, 'city' => 'Oneco'],
                ['state_id' => 7, 'city' => 'Plainfield'],
                ['state_id' => 7, 'city' => 'Sterling'],
                ['state_id' => 7, 'city' => 'Wauregan']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
