<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State3TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of AZ - Arizona.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 3, 'city' => 'Alpine'],
                ['state_id' => 3, 'city' => 'Concho'],
                ['state_id' => 3, 'city' => 'Eagar'],
                ['state_id' => 3, 'city' => 'Greer'],
                ['state_id' => 3, 'city' => 'Mcnary'],
                ['state_id' => 3, 'city' => 'Nutrioso'],
                ['state_id' => 3, 'city' => 'Saint Johns'],
                ['state_id' => 3, 'city' => 'Springerville'],
                ['state_id' => 3, 'city' => 'Vernon'],
                ['state_id' => 3, 'city' => 'Petrified Forest Natl Pk'],
                ['state_id' => 3, 'city' => 'Chambers'],
                ['state_id' => 3, 'city' => 'Chinle'],
                ['state_id' => 3, 'city' => 'Fort Defiance'],
                ['state_id' => 3, 'city' => 'Ganado'],
                ['state_id' => 3, 'city' => 'Houck'],
                ['state_id' => 3, 'city' => 'Lukachukai'],
                ['state_id' => 3, 'city' => 'Lupton'],
                ['state_id' => 3, 'city' => 'Saint Michaels'],
                ['state_id' => 3, 'city' => 'Sanders'],
                ['state_id' => 3, 'city' => 'Teec Nos Pos'],
                ['state_id' => 3, 'city' => 'Window Rock'],
                ['state_id' => 3, 'city' => 'Dennehotso'],
                ['state_id' => 3, 'city' => 'Many Farms'],
                ['state_id' => 3, 'city' => 'Nazlini'],
                ['state_id' => 3, 'city' => 'Red Valley'],
                ['state_id' => 3, 'city' => 'Rock Point'],
                ['state_id' => 3, 'city' => 'Round Rock'],
                ['state_id' => 3, 'city' => 'Tsaile'],
                ['state_id' => 3, 'city' => 'Benson'],
                ['state_id' => 3, 'city' => 'Bisbee'],
                ['state_id' => 3, 'city' => 'Bowie'],
                ['state_id' => 3, 'city' => 'Cochise'],
                ['state_id' => 3, 'city' => 'Douglas'],
                ['state_id' => 3, 'city' => 'Dragoon'],
                ['state_id' => 3, 'city' => 'Elfrida'],
                ['state_id' => 3, 'city' => 'Fort Huachuca'],
                ['state_id' => 3, 'city' => 'Hereford'],
                ['state_id' => 3, 'city' => 'Huachuca City'],
                ['state_id' => 3, 'city' => 'Mc Neal'],
                ['state_id' => 3, 'city' => 'Naco'],
                ['state_id' => 3, 'city' => 'Pearce'],
                ['state_id' => 3, 'city' => 'Pirtleville'],
                ['state_id' => 3, 'city' => 'Pomerene'],
                ['state_id' => 3, 'city' => 'Saint David'],
                ['state_id' => 3, 'city' => 'San Simon'],
                ['state_id' => 3, 'city' => 'Sierra Vista'],
                ['state_id' => 3, 'city' => 'Tombstone'],
                ['state_id' => 3, 'city' => 'Willcox'],
                ['state_id' => 3, 'city' => 'Forest Lakes'],
                ['state_id' => 3, 'city' => 'Flagstaff'],
                ['state_id' => 3, 'city' => 'Bellemont'],
                ['state_id' => 3, 'city' => 'Gray Mountain'],
                ['state_id' => 3, 'city' => 'Munds Park'],
                ['state_id' => 3, 'city' => 'Parks'],
                ['state_id' => 3, 'city' => 'Cameron'],
                ['state_id' => 3, 'city' => 'Fredonia'],
                ['state_id' => 3, 'city' => 'Grand Canyon'],
                ['state_id' => 3, 'city' => 'Happy Jack'],
                ['state_id' => 3, 'city' => 'Leupp'],
                ['state_id' => 3, 'city' => 'Marble Canyon'],
                ['state_id' => 3, 'city' => 'Mormon Lake'],
                ['state_id' => 3, 'city' => 'Page'],
                ['state_id' => 3, 'city' => 'Tonalea'],
                ['state_id' => 3, 'city' => 'Tuba City'],
                ['state_id' => 3, 'city' => 'Williams'],
                ['state_id' => 3, 'city' => 'North Rim'],
                ['state_id' => 3, 'city' => 'Kaibeto'],
                ['state_id' => 3, 'city' => 'Sedona'],
                ['state_id' => 3, 'city' => 'Supai'],
                ['state_id' => 3, 'city' => 'Hayden'],
                ['state_id' => 3, 'city' => 'Winkelman'],
                ['state_id' => 3, 'city' => 'Globe'],
                ['state_id' => 3, 'city' => 'Claypool'],
                ['state_id' => 3, 'city' => 'Miami'],
                ['state_id' => 3, 'city' => 'Payson'],
                ['state_id' => 3, 'city' => 'Peridot'],
                ['state_id' => 3, 'city' => 'Pine'],
                ['state_id' => 3, 'city' => 'Roosevelt'],
                ['state_id' => 3, 'city' => 'San Carlos'],
                ['state_id' => 3, 'city' => 'Tonto Basin'],
                ['state_id' => 3, 'city' => 'Young'],
                ['state_id' => 3, 'city' => 'Bylas'],
                ['state_id' => 3, 'city' => 'Central'],
                ['state_id' => 3, 'city' => 'Eden'],
                ['state_id' => 3, 'city' => 'Fort Thomas'],
                ['state_id' => 3, 'city' => 'Pima'],
                ['state_id' => 3, 'city' => 'Safford'],
                ['state_id' => 3, 'city' => 'Solomon'],
                ['state_id' => 3, 'city' => 'Thatcher'],
                ['state_id' => 3, 'city' => 'Clifton'],
                ['state_id' => 3, 'city' => 'Duncan'],
                ['state_id' => 3, 'city' => 'Morenci'],
                ['state_id' => 3, 'city' => 'Blue'],
                ['state_id' => 3, 'city' => 'Bouse'],
                ['state_id' => 3, 'city' => 'Cibola'],
                ['state_id' => 3, 'city' => 'Ehrenberg'],
                ['state_id' => 3, 'city' => 'Parker'],
                ['state_id' => 3, 'city' => 'Quartzsite'],
                ['state_id' => 3, 'city' => 'Salome'],
                ['state_id' => 3, 'city' => 'Wenden'],
                ['state_id' => 3, 'city' => 'Poston'],
                ['state_id' => 3, 'city' => 'Phoenix'],
                ['state_id' => 3, 'city' => 'New River'],
                ['state_id' => 3, 'city' => 'Chandler Heights'],
                ['state_id' => 3, 'city' => 'Queen Creek'],
                ['state_id' => 3, 'city' => 'Tortilla Flat'],
                ['state_id' => 3, 'city' => 'Mesa'],
                ['state_id' => 3, 'city' => 'Chandler'],
                ['state_id' => 3, 'city' => 'Gilbert'],
                ['state_id' => 3, 'city' => 'Higley'],
                ['state_id' => 3, 'city' => 'Scottsdale'],
                ['state_id' => 3, 'city' => 'Paradise Valley'],
                ['state_id' => 3, 'city' => 'Rio Verde'],
                ['state_id' => 3, 'city' => 'Fort Mcdowell'],
                ['state_id' => 3, 'city' => 'Fountain Hills'],
                ['state_id' => 3, 'city' => 'Tempe'],
                ['state_id' => 3, 'city' => 'Glendale'],
                ['state_id' => 3, 'city' => 'Luke Air Force Base'],
                ['state_id' => 3, 'city' => 'Aguila'],
                ['state_id' => 3, 'city' => 'Arlington'],
                ['state_id' => 3, 'city' => 'Avondale'],
                ['state_id' => 3, 'city' => 'Buckeye'],
                ['state_id' => 3, 'city' => 'Cave Creek'],
                ['state_id' => 3, 'city' => 'Cashion'],
                ['state_id' => 3, 'city' => 'El Mirage'],
                ['state_id' => 3, 'city' => 'Gila Bend'],
                ['state_id' => 3, 'city' => 'Goodyear'],
                ['state_id' => 3, 'city' => 'Laveen'],
                ['state_id' => 3, 'city' => 'Litchfield Park'],
                ['state_id' => 3, 'city' => 'Morristown'],
                ['state_id' => 3, 'city' => 'Palo Verde'],
                ['state_id' => 3, 'city' => 'Peoria'],
                ['state_id' => 3, 'city' => 'Sun City'],
                ['state_id' => 3, 'city' => 'Tolleson'],
                ['state_id' => 3, 'city' => 'Tonopah'],
                ['state_id' => 3, 'city' => 'Waddell'],
                ['state_id' => 3, 'city' => 'Wickenburg'],
                ['state_id' => 3, 'city' => 'Wittmann'],
                ['state_id' => 3, 'city' => 'Youngtown'],
                ['state_id' => 3, 'city' => 'Surprise'],
                ['state_id' => 3, 'city' => 'Sun City West'],
                ['state_id' => 3, 'city' => 'Carefree'],
                ['state_id' => 3, 'city' => 'Wikieup'],
                ['state_id' => 3, 'city' => 'Colorado City'],
                ['state_id' => 3, 'city' => 'Kingman'],
                ['state_id' => 3, 'city' => 'Lake Havasu City'],
                ['state_id' => 3, 'city' => 'Hackberry'],
                ['state_id' => 3, 'city' => 'Hualapai'],
                ['state_id' => 3, 'city' => 'Golden Valley'],
                ['state_id' => 3, 'city' => 'Fort Mohave'],
                ['state_id' => 3, 'city' => 'Bullhead City'],
                ['state_id' => 3, 'city' => 'Chloride'],
                ['state_id' => 3, 'city' => 'Littlefield'],
                ['state_id' => 3, 'city' => 'Oatman'],
                ['state_id' => 3, 'city' => 'Peach Springs'],
                ['state_id' => 3, 'city' => 'Topock'],
                ['state_id' => 3, 'city' => 'Valentine'],
                ['state_id' => 3, 'city' => 'Yucca'],
                ['state_id' => 3, 'city' => 'Mohave Valley'],
                ['state_id' => 3, 'city' => 'Dolan Springs'],
                ['state_id' => 3, 'city' => 'Temple Bar Marina'],
                ['state_id' => 3, 'city' => 'Meadview'],
                ['state_id' => 3, 'city' => 'Willow Beach'],
                ['state_id' => 3, 'city' => 'Show Low'],
                ['state_id' => 3, 'city' => 'Cibecue'],
                ['state_id' => 3, 'city' => 'White Mountain Lake'],
                ['state_id' => 3, 'city' => 'Clay Springs'],
                ['state_id' => 3, 'city' => 'Fort Apache'],
                ['state_id' => 3, 'city' => 'Heber'],
                ['state_id' => 3, 'city' => 'Lakeside'],
                ['state_id' => 3, 'city' => 'Overgaard'],
                ['state_id' => 3, 'city' => 'Pinedale'],
                ['state_id' => 3, 'city' => 'Pinetop'],
                ['state_id' => 3, 'city' => 'Snowflake'],
                ['state_id' => 3, 'city' => 'Taylor'],
                ['state_id' => 3, 'city' => 'Whiteriver'],
                ['state_id' => 3, 'city' => 'Woodruff'],
                ['state_id' => 3, 'city' => 'Holbrook'],
                ['state_id' => 3, 'city' => 'Sun Valley'],
                ['state_id' => 3, 'city' => 'Hotevilla'],
                ['state_id' => 3, 'city' => 'Indian Wells'],
                ['state_id' => 3, 'city' => 'Joseph City'],
                ['state_id' => 3, 'city' => 'Kayenta'],
                ['state_id' => 3, 'city' => 'Keams Canyon'],
                ['state_id' => 3, 'city' => 'Kykotsmovi Village'],
                ['state_id' => 3, 'city' => 'Polacca'],
                ['state_id' => 3, 'city' => 'Second Mesa'],
                ['state_id' => 3, 'city' => 'Winslow'],
                ['state_id' => 3, 'city' => 'Shonto'],
                ['state_id' => 3, 'city' => 'Pinon'],
                ['state_id' => 3, 'city' => 'Blue Gap'],
                ['state_id' => 3, 'city' => 'Ajo'],
                ['state_id' => 3, 'city' => 'Lukeville'],
                ['state_id' => 3, 'city' => 'Arivaca'],
                ['state_id' => 3, 'city' => 'Green Valley'],
                ['state_id' => 3, 'city' => 'Mount Lemmon'],
                ['state_id' => 3, 'city' => 'Sahuarita'],
                ['state_id' => 3, 'city' => 'Sasabe'],
                ['state_id' => 3, 'city' => 'Sells'],
                ['state_id' => 3, 'city' => 'Topawa'],
                ['state_id' => 3, 'city' => 'Vail'],
                ['state_id' => 3, 'city' => 'Cortaro'],
                ['state_id' => 3, 'city' => 'Marana'],
                ['state_id' => 3, 'city' => 'Rillito'],
                ['state_id' => 3, 'city' => 'Tucson'],
                ['state_id' => 3, 'city' => 'Catalina'],
                ['state_id' => 3, 'city' => 'Apache Junction'],
                ['state_id' => 3, 'city' => 'Gold Canyon'],
                ['state_id' => 3, 'city' => 'Bapchule'],
                ['state_id' => 3, 'city' => 'Casa Grande'],
                ['state_id' => 3, 'city' => 'Arizona City'],
                ['state_id' => 3, 'city' => 'Coolidge'],
                ['state_id' => 3, 'city' => 'Eloy'],
                ['state_id' => 3, 'city' => 'Florence'],
                ['state_id' => 3, 'city' => 'Kearny'],
                ['state_id' => 3, 'city' => 'Maricopa'],
                ['state_id' => 3, 'city' => 'San Tan Valley'],
                ['state_id' => 3, 'city' => 'Picacho'],
                ['state_id' => 3, 'city' => 'Red Rock'],
                ['state_id' => 3, 'city' => 'Sacaton'],
                ['state_id' => 3, 'city' => 'Stanfield'],
                ['state_id' => 3, 'city' => 'Superior'],
                ['state_id' => 3, 'city' => 'Valley Farms'],
                ['state_id' => 3, 'city' => 'Mammoth'],
                ['state_id' => 3, 'city' => 'Oracle'],
                ['state_id' => 3, 'city' => 'San Manuel'],
                ['state_id' => 3, 'city' => 'Elgin'],
                ['state_id' => 3, 'city' => 'Nogales'],
                ['state_id' => 3, 'city' => 'Patagonia'],
                ['state_id' => 3, 'city' => 'Sonoita'],
                ['state_id' => 3, 'city' => 'Tumacacori'],
                ['state_id' => 3, 'city' => 'Amado'],
                ['state_id' => 3, 'city' => 'Tubac'],
                ['state_id' => 3, 'city' => 'Rio Rico'],
                ['state_id' => 3, 'city' => 'Black Canyon City'],
                ['state_id' => 3, 'city' => 'Congress'],
                ['state_id' => 3, 'city' => 'Yarnell'],
                ['state_id' => 3, 'city' => 'Prescott'],
                ['state_id' => 3, 'city' => 'Prescott Valley'],
                ['state_id' => 3, 'city' => 'Ash Fork'],
                ['state_id' => 3, 'city' => 'Bagdad'],
                ['state_id' => 3, 'city' => 'Camp Verde'],
                ['state_id' => 3, 'city' => 'Chino Valley'],
                ['state_id' => 3, 'city' => 'Clarkdale'],
                ['state_id' => 3, 'city' => 'Cornville'],
                ['state_id' => 3, 'city' => 'Cottonwood'],
                ['state_id' => 3, 'city' => 'Dewey'],
                ['state_id' => 3, 'city' => 'Humboldt'],
                ['state_id' => 3, 'city' => 'Jerome'],
                ['state_id' => 3, 'city' => 'Kirkland'],
                ['state_id' => 3, 'city' => 'Mayer'],
                ['state_id' => 3, 'city' => 'Paulden'],
                ['state_id' => 3, 'city' => 'Rimrock'],
                ['state_id' => 3, 'city' => 'Seligman'],
                ['state_id' => 3, 'city' => 'Skull Valley'],
                ['state_id' => 3, 'city' => 'Lake Montezuma'],
                ['state_id' => 3, 'city' => 'Crown King'],
                ['state_id' => 3, 'city' => 'Dateland'],
                ['state_id' => 3, 'city' => 'Gadsden'],
                ['state_id' => 3, 'city' => 'Roll'],
                ['state_id' => 3, 'city' => 'San Luis'],
                ['state_id' => 3, 'city' => 'Somerton'],
                ['state_id' => 3, 'city' => 'Tacna'],
                ['state_id' => 3, 'city' => 'Wellton'],
                ['state_id' => 3, 'city' => 'Yuma']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
