<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State33TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NY - New York.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 33, 'city' => 'Alcove'],
                ['state_id' => 33, 'city' => 'Altamont'],
                ['state_id' => 33, 'city' => 'Berne'],
                ['state_id' => 33, 'city' => 'Clarksville'],
                ['state_id' => 33, 'city' => 'Coeymans'],
                ['state_id' => 33, 'city' => 'Coeymans Hollow'],
                ['state_id' => 33, 'city' => 'Cohoes'],
                ['state_id' => 33, 'city' => 'Delmar'],
                ['state_id' => 33, 'city' => 'Dormansville'],
                ['state_id' => 33, 'city' => 'East Berne'],
                ['state_id' => 33, 'city' => 'Feura Bush'],
                ['state_id' => 33, 'city' => 'Glenmont'],
                ['state_id' => 33, 'city' => 'Guilderland'],
                ['state_id' => 33, 'city' => 'Guilderland Center'],
                ['state_id' => 33, 'city' => 'Knox'],
                ['state_id' => 33, 'city' => 'Latham'],
                ['state_id' => 33, 'city' => 'Medusa'],
                ['state_id' => 33, 'city' => 'Newtonville'],
                ['state_id' => 33, 'city' => 'Ravena'],
                ['state_id' => 33, 'city' => 'Rensselaerville'],
                ['state_id' => 33, 'city' => 'Selkirk'],
                ['state_id' => 33, 'city' => 'Slingerlands'],
                ['state_id' => 33, 'city' => 'South Bethlehem'],
                ['state_id' => 33, 'city' => 'Troy'],
                ['state_id' => 33, 'city' => 'Voorheesville'],
                ['state_id' => 33, 'city' => 'Watervliet'],
                ['state_id' => 33, 'city' => 'Westerlo'],
                ['state_id' => 33, 'city' => 'Albany'],
                ['state_id' => 33, 'city' => 'Preston Hollow'],
                ['state_id' => 33, 'city' => 'Centerville'],
                ['state_id' => 33, 'city' => 'Allentown'],
                ['state_id' => 33, 'city' => 'Alma'],
                ['state_id' => 33, 'city' => 'Angelica'],
                ['state_id' => 33, 'city' => 'Belfast'],
                ['state_id' => 33, 'city' => 'Black Creek'],
                ['state_id' => 33, 'city' => 'Bolivar'],
                ['state_id' => 33, 'city' => 'Caneadea'],
                ['state_id' => 33, 'city' => 'Ceres'],
                ['state_id' => 33, 'city' => 'Cuba'],
                ['state_id' => 33, 'city' => 'Fillmore'],
                ['state_id' => 33, 'city' => 'Friendship'],
                ['state_id' => 33, 'city' => 'Houghton'],
                ['state_id' => 33, 'city' => 'Hume'],
                ['state_id' => 33, 'city' => 'Little Genesee'],
                ['state_id' => 33, 'city' => 'Richburg'],
                ['state_id' => 33, 'city' => 'Rushford'],
                ['state_id' => 33, 'city' => 'West Clarksville'],
                ['state_id' => 33, 'city' => 'Alfred'],
                ['state_id' => 33, 'city' => 'Alfred Station'],
                ['state_id' => 33, 'city' => 'Almond'],
                ['state_id' => 33, 'city' => 'Andover'],
                ['state_id' => 33, 'city' => 'Belmont'],
                ['state_id' => 33, 'city' => 'Canaseraga'],
                ['state_id' => 33, 'city' => 'Scio'],
                ['state_id' => 33, 'city' => 'Swain'],
                ['state_id' => 33, 'city' => 'Wellsville'],
                ['state_id' => 33, 'city' => 'Whitesville'],
                ['state_id' => 33, 'city' => 'Bronx'],
                ['state_id' => 33, 'city' => 'Bible School Park'],
                ['state_id' => 33, 'city' => 'Castle Creek'],
                ['state_id' => 33, 'city' => 'Chenango Bridge'],
                ['state_id' => 33, 'city' => 'Chenango Forks'],
                ['state_id' => 33, 'city' => 'Conklin'],
                ['state_id' => 33, 'city' => 'Corbettsville'],
                ['state_id' => 33, 'city' => 'Deposit'],
                ['state_id' => 33, 'city' => 'Endicott'],
                ['state_id' => 33, 'city' => 'Endwell'],
                ['state_id' => 33, 'city' => 'Glen Aubrey'],
                ['state_id' => 33, 'city' => 'Harpursville'],
                ['state_id' => 33, 'city' => 'Johnson City'],
                ['state_id' => 33, 'city' => 'Killawog'],
                ['state_id' => 33, 'city' => 'Kirkwood'],
                ['state_id' => 33, 'city' => 'Lisle'],
                ['state_id' => 33, 'city' => 'Maine'],
                ['state_id' => 33, 'city' => 'Nineveh'],
                ['state_id' => 33, 'city' => 'Ouaquaga'],
                ['state_id' => 33, 'city' => 'Port Crane'],
                ['state_id' => 33, 'city' => 'Tunnel'],
                ['state_id' => 33, 'city' => 'Vestal'],
                ['state_id' => 33, 'city' => 'Whitney Point'],
                ['state_id' => 33, 'city' => 'Windsor'],
                ['state_id' => 33, 'city' => 'Binghamton'],
                ['state_id' => 33, 'city' => 'Dayton'],
                ['state_id' => 33, 'city' => 'Delevan'],
                ['state_id' => 33, 'city' => 'Farmersville Station'],
                ['state_id' => 33, 'city' => 'Freedom'],
                ['state_id' => 33, 'city' => 'Gowanda'],
                ['state_id' => 33, 'city' => 'Machias'],
                ['state_id' => 33, 'city' => 'Perrysburg'],
                ['state_id' => 33, 'city' => 'Sandusky'],
                ['state_id' => 33, 'city' => 'South Dayton'],
                ['state_id' => 33, 'city' => 'Versailles'],
                ['state_id' => 33, 'city' => 'West Valley'],
                ['state_id' => 33, 'city' => 'Yorkshire'],
                ['state_id' => 33, 'city' => 'Allegany'],
                ['state_id' => 33, 'city' => 'Cattaraugus'],
                ['state_id' => 33, 'city' => 'Conewango Valley'],
                ['state_id' => 33, 'city' => 'East Otto'],
                ['state_id' => 33, 'city' => 'East Randolph'],
                ['state_id' => 33, 'city' => 'Ellicottville'],
                ['state_id' => 33, 'city' => 'Franklinville'],
                ['state_id' => 33, 'city' => 'Great Valley'],
                ['state_id' => 33, 'city' => 'Hinsdale'],
                ['state_id' => 33, 'city' => 'Kill Buck'],
                ['state_id' => 33, 'city' => 'Leon'],
                ['state_id' => 33, 'city' => 'Limestone'],
                ['state_id' => 33, 'city' => 'Little Valley'],
                ['state_id' => 33, 'city' => 'Olean'],
                ['state_id' => 33, 'city' => 'Otto'],
                ['state_id' => 33, 'city' => 'Portville'],
                ['state_id' => 33, 'city' => 'Randolph'],
                ['state_id' => 33, 'city' => 'Saint Bonaventure'],
                ['state_id' => 33, 'city' => 'Salamanca'],
                ['state_id' => 33, 'city' => 'Steamburg'],
                ['state_id' => 33, 'city' => 'Westons Mills'],
                ['state_id' => 33, 'city' => 'Auburn'],
                ['state_id' => 33, 'city' => 'Aurora'],
                ['state_id' => 33, 'city' => 'Cato'],
                ['state_id' => 33, 'city' => 'Cayuga'],
                ['state_id' => 33, 'city' => 'Genoa'],
                ['state_id' => 33, 'city' => 'King Ferry'],
                ['state_id' => 33, 'city' => 'Locke'],
                ['state_id' => 33, 'city' => 'Martville'],
                ['state_id' => 33, 'city' => 'Meridian'],
                ['state_id' => 33, 'city' => 'Montezuma'],
                ['state_id' => 33, 'city' => 'Moravia'],
                ['state_id' => 33, 'city' => 'Poplar Ridge'],
                ['state_id' => 33, 'city' => 'Port Byron'],
                ['state_id' => 33, 'city' => 'Scipio Center'],
                ['state_id' => 33, 'city' => 'Sterling'],
                ['state_id' => 33, 'city' => 'Union Springs'],
                ['state_id' => 33, 'city' => 'Weedsport'],
                ['state_id' => 33, 'city' => 'Dunkirk'],
                ['state_id' => 33, 'city' => 'Forestville'],
                ['state_id' => 33, 'city' => 'Fredonia'],
                ['state_id' => 33, 'city' => 'Irving'],
                ['state_id' => 33, 'city' => 'Sheridan'],
                ['state_id' => 33, 'city' => 'Silver Creek'],
                ['state_id' => 33, 'city' => 'Van Buren Point'],
                ['state_id' => 33, 'city' => 'Jamestown'],
                ['state_id' => 33, 'city' => 'Ashville'],
                ['state_id' => 33, 'city' => 'Bemus Point'],
                ['state_id' => 33, 'city' => 'Brocton'],
                ['state_id' => 33, 'city' => 'Cassadaga'],
                ['state_id' => 33, 'city' => 'Celoron'],
                ['state_id' => 33, 'city' => 'Chautauqua'],
                ['state_id' => 33, 'city' => 'Cherry Creek'],
                ['state_id' => 33, 'city' => 'Clymer'],
                ['state_id' => 33, 'city' => 'Dewittville'],
                ['state_id' => 33, 'city' => 'Ellington'],
                ['state_id' => 33, 'city' => 'Falconer'],
                ['state_id' => 33, 'city' => 'Findley Lake'],
                ['state_id' => 33, 'city' => 'Frewsburg'],
                ['state_id' => 33, 'city' => 'Gerry'],
                ['state_id' => 33, 'city' => 'Greenhurst'],
                ['state_id' => 33, 'city' => 'Kennedy'],
                ['state_id' => 33, 'city' => 'Lakewood'],
                ['state_id' => 33, 'city' => 'Lily Dale'],
                ['state_id' => 33, 'city' => 'Maple Springs'],
                ['state_id' => 33, 'city' => 'Mayville'],
                ['state_id' => 33, 'city' => 'Niobe'],
                ['state_id' => 33, 'city' => 'Panama'],
                ['state_id' => 33, 'city' => 'Portland'],
                ['state_id' => 33, 'city' => 'Ripley'],
                ['state_id' => 33, 'city' => 'Sherman'],
                ['state_id' => 33, 'city' => 'Sinclairville'],
                ['state_id' => 33, 'city' => 'Stockton'],
                ['state_id' => 33, 'city' => 'Stow'],
                ['state_id' => 33, 'city' => 'Westfield'],
                ['state_id' => 33, 'city' => 'Big Flats'],
                ['state_id' => 33, 'city' => 'Breesport'],
                ['state_id' => 33, 'city' => 'Chemung'],
                ['state_id' => 33, 'city' => 'Erin'],
                ['state_id' => 33, 'city' => 'Horseheads'],
                ['state_id' => 33, 'city' => 'Lowman'],
                ['state_id' => 33, 'city' => 'Millport'],
                ['state_id' => 33, 'city' => 'Pine City'],
                ['state_id' => 33, 'city' => 'Pine Valley'],
                ['state_id' => 33, 'city' => 'Van Etten'],
                ['state_id' => 33, 'city' => 'Wellsburg'],
                ['state_id' => 33, 'city' => 'Elmira'],
                ['state_id' => 33, 'city' => 'North Pitcher'],
                ['state_id' => 33, 'city' => 'Pitcher'],
                ['state_id' => 33, 'city' => 'South Otselic'],
                ['state_id' => 33, 'city' => 'Earlville'],
                ['state_id' => 33, 'city' => 'New Berlin'],
                ['state_id' => 33, 'city' => 'Sherburne'],
                ['state_id' => 33, 'city' => 'Smyrna'],
                ['state_id' => 33, 'city' => 'Afton'],
                ['state_id' => 33, 'city' => 'Bainbridge'],
                ['state_id' => 33, 'city' => 'East Pharsalia'],
                ['state_id' => 33, 'city' => 'Greene'],
                ['state_id' => 33, 'city' => 'Guilford'],
                ['state_id' => 33, 'city' => 'Mc Donough'],
                ['state_id' => 33, 'city' => 'Mount Upton'],
                ['state_id' => 33, 'city' => 'North Norwich'],
                ['state_id' => 33, 'city' => 'Norwich'],
                ['state_id' => 33, 'city' => 'Oxford'],
                ['state_id' => 33, 'city' => 'Plymouth'],
                ['state_id' => 33, 'city' => 'Smithville Flats'],
                ['state_id' => 33, 'city' => 'South New Berlin'],
                ['state_id' => 33, 'city' => 'South Plymouth'],
                ['state_id' => 33, 'city' => 'Plattsburgh'],
                ['state_id' => 33, 'city' => 'Altona'],
                ['state_id' => 33, 'city' => 'Keeseville'],
                ['state_id' => 33, 'city' => 'Au Sable Forks'],
                ['state_id' => 33, 'city' => 'Cadyville'],
                ['state_id' => 33, 'city' => 'Champlain'],
                ['state_id' => 33, 'city' => 'Chazy'],
                ['state_id' => 33, 'city' => 'Churubusco'],
                ['state_id' => 33, 'city' => 'Dannemora'],
                ['state_id' => 33, 'city' => 'Ellenburg'],
                ['state_id' => 33, 'city' => 'Ellenburg Center'],
                ['state_id' => 33, 'city' => 'Ellenburg Depot'],
                ['state_id' => 33, 'city' => 'Lyon Mountain'],
                ['state_id' => 33, 'city' => 'Mooers'],
                ['state_id' => 33, 'city' => 'Mooers Forks'],
                ['state_id' => 33, 'city' => 'Morrisonville'],
                ['state_id' => 33, 'city' => 'Peru'],
                ['state_id' => 33, 'city' => 'Redford'],
                ['state_id' => 33, 'city' => 'Rouses Point'],
                ['state_id' => 33, 'city' => 'Saranac'],
                ['state_id' => 33, 'city' => 'Schuyler Falls'],
                ['state_id' => 33, 'city' => 'West Chazy'],
                ['state_id' => 33, 'city' => 'Austerlitz'],
                ['state_id' => 33, 'city' => 'Canaan'],
                ['state_id' => 33, 'city' => 'Chatham'],
                ['state_id' => 33, 'city' => 'Columbiaville'],
                ['state_id' => 33, 'city' => 'East Chatham'],
                ['state_id' => 33, 'city' => 'Ghent'],
                ['state_id' => 33, 'city' => 'Kinderhook'],
                ['state_id' => 33, 'city' => 'Malden Bridge'],
                ['state_id' => 33, 'city' => 'New Lebanon'],
                ['state_id' => 33, 'city' => 'Niverville'],
                ['state_id' => 33, 'city' => 'North Chatham'],
                ['state_id' => 33, 'city' => 'Old Chatham'],
                ['state_id' => 33, 'city' => 'Spencertown'],
                ['state_id' => 33, 'city' => 'Stottville'],
                ['state_id' => 33, 'city' => 'Stuyvesant'],
                ['state_id' => 33, 'city' => 'Stuyvesant Falls'],
                ['state_id' => 33, 'city' => 'Valatie'],
                ['state_id' => 33, 'city' => 'West Lebanon'],
                ['state_id' => 33, 'city' => 'Ancram'],
                ['state_id' => 33, 'city' => 'Ancramdale'],
                ['state_id' => 33, 'city' => 'Claverack'],
                ['state_id' => 33, 'city' => 'Copake'],
                ['state_id' => 33, 'city' => 'Copake Falls'],
                ['state_id' => 33, 'city' => 'Craryville'],
                ['state_id' => 33, 'city' => 'Elizaville'],
                ['state_id' => 33, 'city' => 'Germantown'],
                ['state_id' => 33, 'city' => 'Hillsdale'],
                ['state_id' => 33, 'city' => 'Hollowville'],
                ['state_id' => 33, 'city' => 'Hudson'],
                ['state_id' => 33, 'city' => 'Livingston'],
                ['state_id' => 33, 'city' => 'Mellenville'],
                ['state_id' => 33, 'city' => 'Philmont'],
                ['state_id' => 33, 'city' => 'Cincinnatus'],
                ['state_id' => 33, 'city' => 'Cortland'],
                ['state_id' => 33, 'city' => 'East Homer'],
                ['state_id' => 33, 'city' => 'Homer'],
                ['state_id' => 33, 'city' => 'Little York'],
                ['state_id' => 33, 'city' => 'Mc Graw'],
                ['state_id' => 33, 'city' => 'Preble'],
                ['state_id' => 33, 'city' => 'Truxton'],
                ['state_id' => 33, 'city' => 'Blodgett Mills'],
                ['state_id' => 33, 'city' => 'Harford'],
                ['state_id' => 33, 'city' => 'Marathon'],
                ['state_id' => 33, 'city' => 'Willet'],
                ['state_id' => 33, 'city' => 'Stamford'],
                ['state_id' => 33, 'city' => 'Arkville'],
                ['state_id' => 33, 'city' => 'Denver'],
                ['state_id' => 33, 'city' => 'Fleischmanns'],
                ['state_id' => 33, 'city' => 'Grand Gorge'],
                ['state_id' => 33, 'city' => 'Halcottsville'],
                ['state_id' => 33, 'city' => 'Margaretville'],
                ['state_id' => 33, 'city' => 'New Kingston'],
                ['state_id' => 33, 'city' => 'Roxbury'],
                ['state_id' => 33, 'city' => 'Andes'],
                ['state_id' => 33, 'city' => 'Bloomville'],
                ['state_id' => 33, 'city' => 'Bovina Center'],
                ['state_id' => 33, 'city' => 'Davenport'],
                ['state_id' => 33, 'city' => 'Davenport Center'],
                ['state_id' => 33, 'city' => 'Delancey'],
                ['state_id' => 33, 'city' => 'Delhi'],
                ['state_id' => 33, 'city' => 'Downsville'],
                ['state_id' => 33, 'city' => 'East Branch'],
                ['state_id' => 33, 'city' => 'East Meredith'],
                ['state_id' => 33, 'city' => 'Fishs Eddy'],
                ['state_id' => 33, 'city' => 'Franklin'],
                ['state_id' => 33, 'city' => 'Hamden'],
                ['state_id' => 33, 'city' => 'Hancock'],
                ['state_id' => 33, 'city' => 'Harpersfield'],
                ['state_id' => 33, 'city' => 'Hobart'],
                ['state_id' => 33, 'city' => 'Masonville'],
                ['state_id' => 33, 'city' => 'Meridale'],
                ['state_id' => 33, 'city' => 'Sidney'],
                ['state_id' => 33, 'city' => 'Sidney Center'],
                ['state_id' => 33, 'city' => 'South Kortright'],
                ['state_id' => 33, 'city' => 'Treadwell'],
                ['state_id' => 33, 'city' => 'Trout Creek'],
                ['state_id' => 33, 'city' => 'Walton'],
                ['state_id' => 33, 'city' => 'West Davenport'],
                ['state_id' => 33, 'city' => 'Amenia'],
                ['state_id' => 33, 'city' => 'Annandale On Hudson'],
                ['state_id' => 33, 'city' => 'Bangall'],
                ['state_id' => 33, 'city' => 'Barrytown'],
                ['state_id' => 33, 'city' => 'Beacon'],
                ['state_id' => 33, 'city' => 'Billings'],
                ['state_id' => 33, 'city' => 'Castle Point'],
                ['state_id' => 33, 'city' => 'Chelsea'],
                ['state_id' => 33, 'city' => 'Clinton Corners'],
                ['state_id' => 33, 'city' => 'Dover Plains'],
                ['state_id' => 33, 'city' => 'Fishkill'],
                ['state_id' => 33, 'city' => 'Glenham'],
                ['state_id' => 33, 'city' => 'Holmes'],
                ['state_id' => 33, 'city' => 'Hopewell Junction'],
                ['state_id' => 33, 'city' => 'Hughsonville'],
                ['state_id' => 33, 'city' => 'Hyde Park'],
                ['state_id' => 33, 'city' => 'Lagrangeville'],
                ['state_id' => 33, 'city' => 'Millbrook'],
                ['state_id' => 33, 'city' => 'Millerton'],
                ['state_id' => 33, 'city' => 'Pawling'],
                ['state_id' => 33, 'city' => 'Pine Plains'],
                ['state_id' => 33, 'city' => 'Pleasant Valley'],
                ['state_id' => 33, 'city' => 'Poughquag'],
                ['state_id' => 33, 'city' => 'Red Hook'],
                ['state_id' => 33, 'city' => 'Rhinebeck'],
                ['state_id' => 33, 'city' => 'Rhinecliff'],
                ['state_id' => 33, 'city' => 'Salt Point'],
                ['state_id' => 33, 'city' => 'Staatsburg'],
                ['state_id' => 33, 'city' => 'Stanfordville'],
                ['state_id' => 33, 'city' => 'Stormville'],
                ['state_id' => 33, 'city' => 'Tivoli'],
                ['state_id' => 33, 'city' => 'Verbank'],
                ['state_id' => 33, 'city' => 'Wappingers Falls'],
                ['state_id' => 33, 'city' => 'Wassaic'],
                ['state_id' => 33, 'city' => 'Wingdale'],
                ['state_id' => 33, 'city' => 'Poughkeepsie'],
                ['state_id' => 33, 'city' => 'Akron'],
                ['state_id' => 33, 'city' => 'Alden'],
                ['state_id' => 33, 'city' => 'Angola'],
                ['state_id' => 33, 'city' => 'Athol Springs'],
                ['state_id' => 33, 'city' => 'Boston'],
                ['state_id' => 33, 'city' => 'Bowmansville'],
                ['state_id' => 33, 'city' => 'Brant'],
                ['state_id' => 33, 'city' => 'Chaffee'],
                ['state_id' => 33, 'city' => 'Clarence'],
                ['state_id' => 33, 'city' => 'Clarence Center'],
                ['state_id' => 33, 'city' => 'Colden'],
                ['state_id' => 33, 'city' => 'Collins'],
                ['state_id' => 33, 'city' => 'Collins Center'],
                ['state_id' => 33, 'city' => 'Crittenden'],
                ['state_id' => 33, 'city' => 'Depew'],
                ['state_id' => 33, 'city' => 'Derby'],
                ['state_id' => 33, 'city' => 'East Amherst'],
                ['state_id' => 33, 'city' => 'East Aurora'],
                ['state_id' => 33, 'city' => 'East Concord'],
                ['state_id' => 33, 'city' => 'Eden'],
                ['state_id' => 33, 'city' => 'Elma'],
                ['state_id' => 33, 'city' => 'Farnham'],
                ['state_id' => 33, 'city' => 'Getzville'],
                ['state_id' => 33, 'city' => 'Glenwood'],
                ['state_id' => 33, 'city' => 'Grand Island'],
                ['state_id' => 33, 'city' => 'Hamburg'],
                ['state_id' => 33, 'city' => 'Holland'],
                ['state_id' => 33, 'city' => 'Lake View'],
                ['state_id' => 33, 'city' => 'Lancaster'],
                ['state_id' => 33, 'city' => 'Lawtons'],
                ['state_id' => 33, 'city' => 'Marilla'],
                ['state_id' => 33, 'city' => 'North Boston'],
                ['state_id' => 33, 'city' => 'North Collins'],
                ['state_id' => 33, 'city' => 'North Evans'],
                ['state_id' => 33, 'city' => 'Orchard Park'],
                ['state_id' => 33, 'city' => 'Sardinia'],
                ['state_id' => 33, 'city' => 'South Wales'],
                ['state_id' => 33, 'city' => 'Spring Brook'],
                ['state_id' => 33, 'city' => 'Springville'],
                ['state_id' => 33, 'city' => 'Tonawanda'],
                ['state_id' => 33, 'city' => 'Wales Center'],
                ['state_id' => 33, 'city' => 'West Falls'],
                ['state_id' => 33, 'city' => 'Buffalo'],
                ['state_id' => 33, 'city' => 'Minerva'],
                ['state_id' => 33, 'city' => 'Newcomb'],
                ['state_id' => 33, 'city' => 'North Hudson'],
                ['state_id' => 33, 'city' => 'Olmstedville'],
                ['state_id' => 33, 'city' => 'Paradox'],
                ['state_id' => 33, 'city' => 'Schroon Lake'],
                ['state_id' => 33, 'city' => 'Severance'],
                ['state_id' => 33, 'city' => 'Ticonderoga'],
                ['state_id' => 33, 'city' => 'Bloomingdale'],
                ['state_id' => 33, 'city' => 'Crown Point'],
                ['state_id' => 33, 'city' => 'Elizabethtown'],
                ['state_id' => 33, 'city' => 'Essex'],
                ['state_id' => 33, 'city' => 'Jay'],
                ['state_id' => 33, 'city' => 'Keene'],
                ['state_id' => 33, 'city' => 'Keene Valley'],
                ['state_id' => 33, 'city' => 'Lake Placid'],
                ['state_id' => 33, 'city' => 'Lewis'],
                ['state_id' => 33, 'city' => 'Mineville'],
                ['state_id' => 33, 'city' => 'Moriah'],
                ['state_id' => 33, 'city' => 'Moriah Center'],
                ['state_id' => 33, 'city' => 'New Russia'],
                ['state_id' => 33, 'city' => 'Port Henry'],
                ['state_id' => 33, 'city' => 'Port Kent'],
                ['state_id' => 33, 'city' => 'Ray Brook'],
                ['state_id' => 33, 'city' => 'Upper Jay'],
                ['state_id' => 33, 'city' => 'Westport'],
                ['state_id' => 33, 'city' => 'Willsboro'],
                ['state_id' => 33, 'city' => 'Wilmington'],
                ['state_id' => 33, 'city' => 'Witherbee'],
                ['state_id' => 33, 'city' => 'Bombay'],
                ['state_id' => 33, 'city' => 'Brainardsville'],
                ['state_id' => 33, 'city' => 'Brushton'],
                ['state_id' => 33, 'city' => 'Burke'],
                ['state_id' => 33, 'city' => 'Chateaugay'],
                ['state_id' => 33, 'city' => 'Constable'],
                ['state_id' => 33, 'city' => 'Dickinson Center'],
                ['state_id' => 33, 'city' => 'Fort Covington'],
                ['state_id' => 33, 'city' => 'Gabriels'],
                ['state_id' => 33, 'city' => 'Lake Clear'],
                ['state_id' => 33, 'city' => 'Malone'],
                ['state_id' => 33, 'city' => 'Moira'],
                ['state_id' => 33, 'city' => 'North Bangor'],
                ['state_id' => 33, 'city' => 'Owls Head'],
                ['state_id' => 33, 'city' => 'Paul Smiths'],
                ['state_id' => 33, 'city' => 'Rainbow Lake'],
                ['state_id' => 33, 'city' => 'Saint Regis Falls'],
                ['state_id' => 33, 'city' => 'Saranac Lake'],
                ['state_id' => 33, 'city' => 'Tupper Lake'],
                ['state_id' => 33, 'city' => 'Vermontville'],
                ['state_id' => 33, 'city' => 'Whippleville'],
                ['state_id' => 33, 'city' => 'Hogansburg'],
                ['state_id' => 33, 'city' => 'Broadalbin'],
                ['state_id' => 33, 'city' => 'Caroga Lake'],
                ['state_id' => 33, 'city' => 'Gloversville'],
                ['state_id' => 33, 'city' => 'Johnstown'],
                ['state_id' => 33, 'city' => 'Mayfield'],
                ['state_id' => 33, 'city' => 'Northville'],
                ['state_id' => 33, 'city' => 'Stratford'],
                ['state_id' => 33, 'city' => 'Alexander'],
                ['state_id' => 33, 'city' => 'Basom'],
                ['state_id' => 33, 'city' => 'Batavia'],
                ['state_id' => 33, 'city' => 'Corfu'],
                ['state_id' => 33, 'city' => 'Darien Center'],
                ['state_id' => 33, 'city' => 'East Bethany'],
                ['state_id' => 33, 'city' => 'East Pembroke'],
                ['state_id' => 33, 'city' => 'Elba'],
                ['state_id' => 33, 'city' => 'Oakfield'],
                ['state_id' => 33, 'city' => 'Stafford'],
                ['state_id' => 33, 'city' => 'Bergen'],
                ['state_id' => 33, 'city' => 'Byron'],
                ['state_id' => 33, 'city' => 'Le Roy'],
                ['state_id' => 33, 'city' => 'Linwood'],
                ['state_id' => 33, 'city' => 'Pavilion'],
                ['state_id' => 33, 'city' => 'South Byron'],
                ['state_id' => 33, 'city' => 'Athens'],
                ['state_id' => 33, 'city' => 'Climax'],
                ['state_id' => 33, 'city' => 'Coxsackie'],
                ['state_id' => 33, 'city' => 'Earlton'],
                ['state_id' => 33, 'city' => 'Greenville'],
                ['state_id' => 33, 'city' => 'Hannacroix'],
                ['state_id' => 33, 'city' => 'New Baltimore'],
                ['state_id' => 33, 'city' => 'Surprise'],
                ['state_id' => 33, 'city' => 'West Coxsackie'],
                ['state_id' => 33, 'city' => 'Acra'],
                ['state_id' => 33, 'city' => 'Ashland'],
                ['state_id' => 33, 'city' => 'Cairo'],
                ['state_id' => 33, 'city' => 'Catskill'],
                ['state_id' => 33, 'city' => 'Cornwallville'],
                ['state_id' => 33, 'city' => 'Durham'],
                ['state_id' => 33, 'city' => 'East Durham'],
                ['state_id' => 33, 'city' => 'East Jewett'],
                ['state_id' => 33, 'city' => 'Elka Park'],
                ['state_id' => 33, 'city' => 'Freehold'],
                ['state_id' => 33, 'city' => 'Haines Falls'],
                ['state_id' => 33, 'city' => 'Hensonville'],
                ['state_id' => 33, 'city' => 'Hunter'],
                ['state_id' => 33, 'city' => 'Jewett'],
                ['state_id' => 33, 'city' => 'Lanesville'],
                ['state_id' => 33, 'city' => 'Leeds'],
                ['state_id' => 33, 'city' => 'Lexington'],
                ['state_id' => 33, 'city' => 'Maplecrest'],
                ['state_id' => 33, 'city' => 'Oak Hill'],
                ['state_id' => 33, 'city' => 'Palenville'],
                ['state_id' => 33, 'city' => 'Prattsville'],
                ['state_id' => 33, 'city' => 'Purling'],
                ['state_id' => 33, 'city' => 'Round Top'],
                ['state_id' => 33, 'city' => 'South Cairo'],
                ['state_id' => 33, 'city' => 'Tannersville'],
                ['state_id' => 33, 'city' => 'West Kill'],
                ['state_id' => 33, 'city' => 'Windham'],
                ['state_id' => 33, 'city' => 'Lake Pleasant'],
                ['state_id' => 33, 'city' => 'Piseco'],
                ['state_id' => 33, 'city' => 'Speculator'],
                ['state_id' => 33, 'city' => 'Wells'],
                ['state_id' => 33, 'city' => 'Blue Mountain Lake'],
                ['state_id' => 33, 'city' => 'Indian Lake'],
                ['state_id' => 33, 'city' => 'Long Lake'],
                ['state_id' => 33, 'city' => 'Sabael'],
                ['state_id' => 33, 'city' => 'Hoffmeister'],
                ['state_id' => 33, 'city' => 'Inlet'],
                ['state_id' => 33, 'city' => 'Raquette Lake'],
                ['state_id' => 33, 'city' => 'Cold Brook'],
                ['state_id' => 33, 'city' => 'Dolgeville'],
                ['state_id' => 33, 'city' => 'Eagle Bay'],
                ['state_id' => 33, 'city' => 'Frankfort'],
                ['state_id' => 33, 'city' => 'Herkimer'],
                ['state_id' => 33, 'city' => 'Ilion'],
                ['state_id' => 33, 'city' => 'Jordanville'],
                ['state_id' => 33, 'city' => 'Little Falls'],
                ['state_id' => 33, 'city' => 'Middleville'],
                ['state_id' => 33, 'city' => 'Mohawk'],
                ['state_id' => 33, 'city' => 'Newport'],
                ['state_id' => 33, 'city' => 'Old Forge'],
                ['state_id' => 33, 'city' => 'Poland'],
                ['state_id' => 33, 'city' => 'Salisbury Center'],
                ['state_id' => 33, 'city' => 'Thendara'],
                ['state_id' => 33, 'city' => 'Van Hornesville'],
                ['state_id' => 33, 'city' => 'West Winfield'],
                ['state_id' => 33, 'city' => 'Watertown'],
                ['state_id' => 33, 'city' => 'Fort Drum'],
                ['state_id' => 33, 'city' => 'Adams'],
                ['state_id' => 33, 'city' => 'Adams Center'],
                ['state_id' => 33, 'city' => 'Alexandria Bay'],
                ['state_id' => 33, 'city' => 'Antwerp'],
                ['state_id' => 33, 'city' => 'Belleville'],
                ['state_id' => 33, 'city' => 'Black River'],
                ['state_id' => 33, 'city' => 'Brownville'],
                ['state_id' => 33, 'city' => 'Calcium'],
                ['state_id' => 33, 'city' => 'Cape Vincent'],
                ['state_id' => 33, 'city' => 'Carthage'],
                ['state_id' => 33, 'city' => 'Chaumont'],
                ['state_id' => 33, 'city' => 'Clayton'],
                ['state_id' => 33, 'city' => 'Deferiet'],
                ['state_id' => 33, 'city' => 'Depauville'],
                ['state_id' => 33, 'city' => 'Dexter'],
                ['state_id' => 33, 'city' => 'Ellisburg'],
                ['state_id' => 33, 'city' => 'Evans Mills'],
                ['state_id' => 33, 'city' => 'Felts Mills'],
                ['state_id' => 33, 'city' => 'Wellesley Island'],
                ['state_id' => 33, 'city' => 'Fishers Landing'],
                ['state_id' => 33, 'city' => 'Great Bend'],
                ['state_id' => 33, 'city' => 'Henderson'],
                ['state_id' => 33, 'city' => 'Henderson Harbor'],
                ['state_id' => 33, 'city' => 'La Fargeville'],
                ['state_id' => 33, 'city' => 'Limerick'],
                ['state_id' => 33, 'city' => 'Lorraine'],
                ['state_id' => 33, 'city' => 'Mannsville'],
                ['state_id' => 33, 'city' => 'Natural Bridge'],
                ['state_id' => 33, 'city' => 'Oxbow'],
                ['state_id' => 33, 'city' => 'Philadelphia'],
                ['state_id' => 33, 'city' => 'Pierrepont Manor'],
                ['state_id' => 33, 'city' => 'Plessis'],
                ['state_id' => 33, 'city' => 'Redwood'],
                ['state_id' => 33, 'city' => 'Rodman'],
                ['state_id' => 33, 'city' => 'Sackets Harbor'],
                ['state_id' => 33, 'city' => 'Theresa'],
                ['state_id' => 33, 'city' => 'Thousand Island Park'],
                ['state_id' => 33, 'city' => 'Three Mile Bay'],
                ['state_id' => 33, 'city' => 'Brooklyn'],
                ['state_id' => 33, 'city' => 'Beaver Falls'],
                ['state_id' => 33, 'city' => 'Brantingham'],
                ['state_id' => 33, 'city' => 'Constableville'],
                ['state_id' => 33, 'city' => 'Croghan'],
                ['state_id' => 33, 'city' => 'Glenfield'],
                ['state_id' => 33, 'city' => 'Greig'],
                ['state_id' => 33, 'city' => 'Lowville'],
                ['state_id' => 33, 'city' => 'Lyons Falls'],
                ['state_id' => 33, 'city' => 'Martinsburg'],
                ['state_id' => 33, 'city' => 'Port Leyden'],
                ['state_id' => 33, 'city' => 'Turin'],
                ['state_id' => 33, 'city' => 'West Leyden'],
                ['state_id' => 33, 'city' => 'Castorland'],
                ['state_id' => 33, 'city' => 'Copenhagen'],
                ['state_id' => 33, 'city' => 'Deer River'],
                ['state_id' => 33, 'city' => 'Denmark'],
                ['state_id' => 33, 'city' => 'Harrisville'],
                ['state_id' => 33, 'city' => 'Avon'],
                ['state_id' => 33, 'city' => 'Caledonia'],
                ['state_id' => 33, 'city' => 'Conesus'],
                ['state_id' => 33, 'city' => 'Dansville'],
                ['state_id' => 33, 'city' => 'Geneseo'],
                ['state_id' => 33, 'city' => 'Groveland'],
                ['state_id' => 33, 'city' => 'Hemlock'],
                ['state_id' => 33, 'city' => 'Lakeville'],
                ['state_id' => 33, 'city' => 'Leicester'],
                ['state_id' => 33, 'city' => 'Lima'],
                ['state_id' => 33, 'city' => 'Livonia'],
                ['state_id' => 33, 'city' => 'Livonia Center'],
                ['state_id' => 33, 'city' => 'Mount Morris'],
                ['state_id' => 33, 'city' => 'Nunda'],
                ['state_id' => 33, 'city' => 'Piffard'],
                ['state_id' => 33, 'city' => 'Retsof'],
                ['state_id' => 33, 'city' => 'Scottsburg'],
                ['state_id' => 33, 'city' => 'Sonyea'],
                ['state_id' => 33, 'city' => 'South Lima'],
                ['state_id' => 33, 'city' => 'Springwater'],
                ['state_id' => 33, 'city' => 'York'],
                ['state_id' => 33, 'city' => 'Dalton'],
                ['state_id' => 33, 'city' => 'Hunt'],
                ['state_id' => 33, 'city' => 'Canastota'],
                ['state_id' => 33, 'city' => 'Cazenovia'],
                ['state_id' => 33, 'city' => 'Chittenango'],
                ['state_id' => 33, 'city' => 'Clockville'],
                ['state_id' => 33, 'city' => 'De Ruyter'],
                ['state_id' => 33, 'city' => 'Erieville'],
                ['state_id' => 33, 'city' => 'Georgetown'],
                ['state_id' => 33, 'city' => 'New Woodstock'],
                ['state_id' => 33, 'city' => 'Peterboro'],
                ['state_id' => 33, 'city' => 'Wampsville'],
                ['state_id' => 33, 'city' => 'Bouckville'],
                ['state_id' => 33, 'city' => 'Brookfield'],
                ['state_id' => 33, 'city' => 'Eaton'],
                ['state_id' => 33, 'city' => 'Hamilton'],
                ['state_id' => 33, 'city' => 'Hubbardsville'],
                ['state_id' => 33, 'city' => 'Leonardsville'],
                ['state_id' => 33, 'city' => 'Madison'],
                ['state_id' => 33, 'city' => 'Morrisville'],
                ['state_id' => 33, 'city' => 'Munnsville'],
                ['state_id' => 33, 'city' => 'North Brookfield'],
                ['state_id' => 33, 'city' => 'Oneida'],
                ['state_id' => 33, 'city' => 'Solsville'],
                ['state_id' => 33, 'city' => 'West Eaton'],
                ['state_id' => 33, 'city' => 'Adams Basin'],
                ['state_id' => 33, 'city' => 'Brockport'],
                ['state_id' => 33, 'city' => 'Churchville'],
                ['state_id' => 33, 'city' => 'Clarkson'],
                ['state_id' => 33, 'city' => 'East Rochester'],
                ['state_id' => 33, 'city' => 'Fairport'],
                ['state_id' => 33, 'city' => 'Hamlin'],
                ['state_id' => 33, 'city' => 'Henrietta'],
                ['state_id' => 33, 'city' => 'Hilton'],
                ['state_id' => 33, 'city' => 'Honeoye Falls'],
                ['state_id' => 33, 'city' => 'Mendon'],
                ['state_id' => 33, 'city' => 'Mumford'],
                ['state_id' => 33, 'city' => 'North Chili'],
                ['state_id' => 33, 'city' => 'North Greece'],
                ['state_id' => 33, 'city' => 'Penfield'],
                ['state_id' => 33, 'city' => 'Pittsford'],
                ['state_id' => 33, 'city' => 'Rush'],
                ['state_id' => 33, 'city' => 'Scottsville'],
                ['state_id' => 33, 'city' => 'Spencerport'],
                ['state_id' => 33, 'city' => 'Webster'],
                ['state_id' => 33, 'city' => 'West Henrietta'],
                ['state_id' => 33, 'city' => 'Rochester'],
                ['state_id' => 33, 'city' => 'Amsterdam'],
                ['state_id' => 33, 'city' => 'Auriesville'],
                ['state_id' => 33, 'city' => 'Esperance'],
                ['state_id' => 33, 'city' => 'Fonda'],
                ['state_id' => 33, 'city' => 'Fort Hunter'],
                ['state_id' => 33, 'city' => 'Fort Johnson'],
                ['state_id' => 33, 'city' => 'Fultonville'],
                ['state_id' => 33, 'city' => 'Hagaman'],
                ['state_id' => 33, 'city' => 'Sprakers'],
                ['state_id' => 33, 'city' => 'Tribes Hill'],
                ['state_id' => 33, 'city' => 'Canajoharie'],
                ['state_id' => 33, 'city' => 'Fort Plain'],
                ['state_id' => 33, 'city' => 'Nelliston'],
                ['state_id' => 33, 'city' => 'Palatine Bridge'],
                ['state_id' => 33, 'city' => 'Saint Johnsville'],
                ['state_id' => 33, 'city' => 'Floral Park'],
                ['state_id' => 33, 'city' => 'Elmont'],
                ['state_id' => 33, 'city' => 'Franklin Square'],
                ['state_id' => 33, 'city' => 'Great Neck'],
                ['state_id' => 33, 'city' => 'Manhasset'],
                ['state_id' => 33, 'city' => 'New Hyde Park'],
                ['state_id' => 33, 'city' => 'Port Washington'],
                ['state_id' => 33, 'city' => 'Inwood'],
                ['state_id' => 33, 'city' => 'Mineola'],
                ['state_id' => 33, 'city' => 'Albertson'],
                ['state_id' => 33, 'city' => 'Atlantic Beach'],
                ['state_id' => 33, 'city' => 'Baldwin'],
                ['state_id' => 33, 'city' => 'Carle Place'],
                ['state_id' => 33, 'city' => 'Cedarhurst'],
                ['state_id' => 33, 'city' => 'East Rockaway'],
                ['state_id' => 33, 'city' => 'Freeport'],
                ['state_id' => 33, 'city' => 'Garden City'],
                ['state_id' => 33, 'city' => 'Glen Cove'],
                ['state_id' => 33, 'city' => 'Glen Head'],
                ['state_id' => 33, 'city' => 'Glenwood Landing'],
                ['state_id' => 33, 'city' => 'Greenvale'],
                ['state_id' => 33, 'city' => 'Hempstead'],
                ['state_id' => 33, 'city' => 'West Hempstead'],
                ['state_id' => 33, 'city' => 'Uniondale'],
                ['state_id' => 33, 'city' => 'East Meadow'],
                ['state_id' => 33, 'city' => 'Hewlett'],
                ['state_id' => 33, 'city' => 'Island Park'],
                ['state_id' => 33, 'city' => 'Lawrence'],
                ['state_id' => 33, 'city' => 'Locust Valley'],
                ['state_id' => 33, 'city' => 'Long Beach'],
                ['state_id' => 33, 'city' => 'Lynbrook'],
                ['state_id' => 33, 'city' => 'Malverne'],
                ['state_id' => 33, 'city' => 'Merrick'],
                ['state_id' => 33, 'city' => 'Old Westbury'],
                ['state_id' => 33, 'city' => 'Point Lookout'],
                ['state_id' => 33, 'city' => 'Rockville Centre'],
                ['state_id' => 33, 'city' => 'Oceanside'],
                ['state_id' => 33, 'city' => 'Roosevelt'],
                ['state_id' => 33, 'city' => 'Roslyn'],
                ['state_id' => 33, 'city' => 'Roslyn Heights'],
                ['state_id' => 33, 'city' => 'Sea Cliff'],
                ['state_id' => 33, 'city' => 'Valley Stream'],
                ['state_id' => 33, 'city' => 'Westbury'],
                ['state_id' => 33, 'city' => 'Williston Park'],
                ['state_id' => 33, 'city' => 'Woodmere'],
                ['state_id' => 33, 'city' => 'Bayville'],
                ['state_id' => 33, 'city' => 'Bellmore'],
                ['state_id' => 33, 'city' => 'Bethpage'],
                ['state_id' => 33, 'city' => 'East Norwich'],
                ['state_id' => 33, 'city' => 'Farmingdale'],
                ['state_id' => 33, 'city' => 'Jericho'],
                ['state_id' => 33, 'city' => 'Levittown'],
                ['state_id' => 33, 'city' => 'Massapequa'],
                ['state_id' => 33, 'city' => 'Massapequa Park'],
                ['state_id' => 33, 'city' => 'Mill Neck'],
                ['state_id' => 33, 'city' => 'Oyster Bay'],
                ['state_id' => 33, 'city' => 'Syosset'],
                ['state_id' => 33, 'city' => 'Seaford'],
                ['state_id' => 33, 'city' => 'Wantagh'],
                ['state_id' => 33, 'city' => 'Woodbury'],
                ['state_id' => 33, 'city' => 'Hicksville'],
                ['state_id' => 33, 'city' => 'Plainview'],
                ['state_id' => 33, 'city' => 'Old Bethpage'],
                ['state_id' => 33, 'city' => 'New York'],
                ['state_id' => 33, 'city' => 'Appleton'],
                ['state_id' => 33, 'city' => 'Barker'],
                ['state_id' => 33, 'city' => 'Burt'],
                ['state_id' => 33, 'city' => 'Gasport'],
                ['state_id' => 33, 'city' => 'Lewiston'],
                ['state_id' => 33, 'city' => 'Lockport'],
                ['state_id' => 33, 'city' => 'Middleport'],
                ['state_id' => 33, 'city' => 'Model City'],
                ['state_id' => 33, 'city' => 'Newfane'],
                ['state_id' => 33, 'city' => 'Niagara University'],
                ['state_id' => 33, 'city' => 'North Tonawanda'],
                ['state_id' => 33, 'city' => 'Olcott'],
                ['state_id' => 33, 'city' => 'Ransomville'],
                ['state_id' => 33, 'city' => 'Sanborn'],
                ['state_id' => 33, 'city' => 'Stella Niagara'],
                ['state_id' => 33, 'city' => 'Wilson'],
                ['state_id' => 33, 'city' => 'Youngstown'],
                ['state_id' => 33, 'city' => 'Niagara Falls'],
                ['state_id' => 33, 'city' => 'Durhamville'],
                ['state_id' => 33, 'city' => 'North Bay'],
                ['state_id' => 33, 'city' => 'Sylvan Beach'],
                ['state_id' => 33, 'city' => 'Verona Beach'],
                ['state_id' => 33, 'city' => 'Alder Creek'],
                ['state_id' => 33, 'city' => 'Ava'],
                ['state_id' => 33, 'city' => 'Barneveld'],
                ['state_id' => 33, 'city' => 'Blossvale'],
                ['state_id' => 33, 'city' => 'Boonville'],
                ['state_id' => 33, 'city' => 'Bridgewater'],
                ['state_id' => 33, 'city' => 'Camden'],
                ['state_id' => 33, 'city' => 'Cassville'],
                ['state_id' => 33, 'city' => 'Chadwicks'],
                ['state_id' => 33, 'city' => 'Clark Mills'],
                ['state_id' => 33, 'city' => 'Clayville'],
                ['state_id' => 33, 'city' => 'Clinton'],
                ['state_id' => 33, 'city' => 'Deansboro'],
                ['state_id' => 33, 'city' => 'Forestport'],
                ['state_id' => 33, 'city' => 'Franklin Springs'],
                ['state_id' => 33, 'city' => 'Hinckley'],
                ['state_id' => 33, 'city' => 'Holland Patent'],
                ['state_id' => 33, 'city' => 'Knoxboro'],
                ['state_id' => 33, 'city' => 'Lee Center'],
                ['state_id' => 33, 'city' => 'Mc Connellsville'],
                ['state_id' => 33, 'city' => 'Marcy'],
                ['state_id' => 33, 'city' => 'New Hartford'],
                ['state_id' => 33, 'city' => 'New York Mills'],
                ['state_id' => 33, 'city' => 'Oriskany'],
                ['state_id' => 33, 'city' => 'Oriskany Falls'],
                ['state_id' => 33, 'city' => 'Prospect'],
                ['state_id' => 33, 'city' => 'Remsen'],
                ['state_id' => 33, 'city' => 'Rome'],
                ['state_id' => 33, 'city' => 'Sangerfield'],
                ['state_id' => 33, 'city' => 'Sauquoit'],
                ['state_id' => 33, 'city' => 'Sherrill'],
                ['state_id' => 33, 'city' => 'Stittville'],
                ['state_id' => 33, 'city' => 'Taberg'],
                ['state_id' => 33, 'city' => 'Vernon'],
                ['state_id' => 33, 'city' => 'Vernon Center'],
                ['state_id' => 33, 'city' => 'Verona'],
                ['state_id' => 33, 'city' => 'Washington Mills'],
                ['state_id' => 33, 'city' => 'Waterville'],
                ['state_id' => 33, 'city' => 'Westdale'],
                ['state_id' => 33, 'city' => 'Westernville'],
                ['state_id' => 33, 'city' => 'Westmoreland'],
                ['state_id' => 33, 'city' => 'Whitesboro'],
                ['state_id' => 33, 'city' => 'Woodgate'],
                ['state_id' => 33, 'city' => 'Yorkville'],
                ['state_id' => 33, 'city' => 'Utica'],
                ['state_id' => 33, 'city' => 'Apulia Station'],
                ['state_id' => 33, 'city' => 'Baldwinsville'],
                ['state_id' => 33, 'city' => 'Brewerton'],
                ['state_id' => 33, 'city' => 'Bridgeport'],
                ['state_id' => 33, 'city' => 'Camillus'],
                ['state_id' => 33, 'city' => 'Cicero'],
                ['state_id' => 33, 'city' => 'Clay'],
                ['state_id' => 33, 'city' => 'Delphi Falls'],
                ['state_id' => 33, 'city' => 'East Syracuse'],
                ['state_id' => 33, 'city' => 'Elbridge'],
                ['state_id' => 33, 'city' => 'Fabius'],
                ['state_id' => 33, 'city' => 'Fayetteville'],
                ['state_id' => 33, 'city' => 'Jamesville'],
                ['state_id' => 33, 'city' => 'Jordan'],
                ['state_id' => 33, 'city' => 'Kirkville'],
                ['state_id' => 33, 'city' => 'La Fayette'],
                ['state_id' => 33, 'city' => 'Liverpool'],
                ['state_id' => 33, 'city' => 'Manlius'],
                ['state_id' => 33, 'city' => 'Marcellus'],
                ['state_id' => 33, 'city' => 'Marietta'],
                ['state_id' => 33, 'city' => 'Memphis'],
                ['state_id' => 33, 'city' => 'Minoa'],
                ['state_id' => 33, 'city' => 'Mottville'],
                ['state_id' => 33, 'city' => 'Nedrow'],
                ['state_id' => 33, 'city' => 'Plainville'],
                ['state_id' => 33, 'city' => 'Pompey'],
                ['state_id' => 33, 'city' => 'Skaneateles'],
                ['state_id' => 33, 'city' => 'Skaneateles Falls'],
                ['state_id' => 33, 'city' => 'Tully'],
                ['state_id' => 33, 'city' => 'Warners'],
                ['state_id' => 33, 'city' => 'Syracuse'],
                ['state_id' => 33, 'city' => 'Canandaigua'],
                ['state_id' => 33, 'city' => 'Farmington'],
                ['state_id' => 33, 'city' => 'Clifton Springs'],
                ['state_id' => 33, 'city' => 'East Bloomfield'],
                ['state_id' => 33, 'city' => 'Fishers'],
                ['state_id' => 33, 'city' => 'Geneva'],
                ['state_id' => 33, 'city' => 'Gorham'],
                ['state_id' => 33, 'city' => 'Hall'],
                ['state_id' => 33, 'city' => 'Bloomfield'],
                ['state_id' => 33, 'city' => 'Honeoye'],
                ['state_id' => 33, 'city' => 'Ionia'],
                ['state_id' => 33, 'city' => 'Manchester'],
                ['state_id' => 33, 'city' => 'Naples'],
                ['state_id' => 33, 'city' => 'Oaks Corners'],
                ['state_id' => 33, 'city' => 'Phelps'],
                ['state_id' => 33, 'city' => 'Port Gibson'],
                ['state_id' => 33, 'city' => 'Seneca Castle'],
                ['state_id' => 33, 'city' => 'Shortsville'],
                ['state_id' => 33, 'city' => 'Stanley'],
                ['state_id' => 33, 'city' => 'Victor'],
                ['state_id' => 33, 'city' => 'West Bloomfield'],
                ['state_id' => 33, 'city' => 'Arden'],
                ['state_id' => 33, 'city' => 'Bellvale'],
                ['state_id' => 33, 'city' => 'Blooming Grove'],
                ['state_id' => 33, 'city' => 'Bullville'],
                ['state_id' => 33, 'city' => 'Campbell Hall'],
                ['state_id' => 33, 'city' => 'Central Valley'],
                ['state_id' => 33, 'city' => 'Chester'],
                ['state_id' => 33, 'city' => 'Circleville'],
                ['state_id' => 33, 'city' => 'Florida'],
                ['state_id' => 33, 'city' => 'Fort Montgomery'],
                ['state_id' => 33, 'city' => 'Goshen'],
                ['state_id' => 33, 'city' => 'Greenwood Lake'],
                ['state_id' => 33, 'city' => 'Harriman'],
                ['state_id' => 33, 'city' => 'Highland Falls'],
                ['state_id' => 33, 'city' => 'Highland Mills'],
                ['state_id' => 33, 'city' => 'Howells'],
                ['state_id' => 33, 'city' => 'Johnson'],
                ['state_id' => 33, 'city' => 'Middletown'],
                ['state_id' => 33, 'city' => 'Monroe'],
                ['state_id' => 33, 'city' => 'Mountainville'],
                ['state_id' => 33, 'city' => 'New Hampton'],
                ['state_id' => 33, 'city' => 'New Milford'],
                ['state_id' => 33, 'city' => 'Otisville'],
                ['state_id' => 33, 'city' => 'Pine Island'],
                ['state_id' => 33, 'city' => 'Slate Hill'],
                ['state_id' => 33, 'city' => 'Southfields'],
                ['state_id' => 33, 'city' => 'Sterling Forest'],
                ['state_id' => 33, 'city' => 'Sugar Loaf'],
                ['state_id' => 33, 'city' => 'Thompson Ridge'],
                ['state_id' => 33, 'city' => 'Tuxedo Park'],
                ['state_id' => 33, 'city' => 'Unionville'],
                ['state_id' => 33, 'city' => 'Warwick'],
                ['state_id' => 33, 'city' => 'Washingtonville'],
                ['state_id' => 33, 'city' => 'West Point'],
                ['state_id' => 33, 'city' => 'Westtown'],
                ['state_id' => 33, 'city' => 'Cornwall'],
                ['state_id' => 33, 'city' => 'Cornwall On Hudson'],
                ['state_id' => 33, 'city' => 'Maybrook'],
                ['state_id' => 33, 'city' => 'Montgomery'],
                ['state_id' => 33, 'city' => 'Newburgh'],
                ['state_id' => 33, 'city' => 'New Windsor'],
                ['state_id' => 33, 'city' => 'Pine Bush'],
                ['state_id' => 33, 'city' => 'Rock Tavern'],
                ['state_id' => 33, 'city' => 'Salisbury Mills'],
                ['state_id' => 33, 'city' => 'Vails Gate'],
                ['state_id' => 33, 'city' => 'Walden'],
                ['state_id' => 33, 'city' => 'Cuddebackville'],
                ['state_id' => 33, 'city' => 'Huguenot'],
                ['state_id' => 33, 'city' => 'Port Jervis'],
                ['state_id' => 33, 'city' => 'Sparrow Bush'],
                ['state_id' => 33, 'city' => 'Lyndonville'],
                ['state_id' => 33, 'city' => 'Medina'],
                ['state_id' => 33, 'city' => 'Albion'],
                ['state_id' => 33, 'city' => 'Clarendon'],
                ['state_id' => 33, 'city' => 'Fancher'],
                ['state_id' => 33, 'city' => 'Holley'],
                ['state_id' => 33, 'city' => 'Kendall'],
                ['state_id' => 33, 'city' => 'Kent'],
                ['state_id' => 33, 'city' => 'Knowlesville'],
                ['state_id' => 33, 'city' => 'Morton'],
                ['state_id' => 33, 'city' => 'Waterport'],
                ['state_id' => 33, 'city' => 'Bernhards Bay'],
                ['state_id' => 33, 'city' => 'Central Square'],
                ['state_id' => 33, 'city' => 'Cleveland'],
                ['state_id' => 33, 'city' => 'Constantia'],
                ['state_id' => 33, 'city' => 'Fair Haven'],
                ['state_id' => 33, 'city' => 'Fulton'],
                ['state_id' => 33, 'city' => 'Hannibal'],
                ['state_id' => 33, 'city' => 'Hastings'],
                ['state_id' => 33, 'city' => 'Lacona'],
                ['state_id' => 33, 'city' => 'Lycoming'],
                ['state_id' => 33, 'city' => 'Mallory'],
                ['state_id' => 33, 'city' => 'Maple View'],
                ['state_id' => 33, 'city' => 'Mexico'],
                ['state_id' => 33, 'city' => 'Minetto'],
                ['state_id' => 33, 'city' => 'New Haven'],
                ['state_id' => 33, 'city' => 'Oswego'],
                ['state_id' => 33, 'city' => 'Parish'],
                ['state_id' => 33, 'city' => 'Pennellville'],
                ['state_id' => 33, 'city' => 'Phoenix'],
                ['state_id' => 33, 'city' => 'Pulaski'],
                ['state_id' => 33, 'city' => 'Richland'],
                ['state_id' => 33, 'city' => 'Sandy Creek'],
                ['state_id' => 33, 'city' => 'West Monroe'],
                ['state_id' => 33, 'city' => 'Altmar'],
                ['state_id' => 33, 'city' => 'Orwell'],
                ['state_id' => 33, 'city' => 'Redfield'],
                ['state_id' => 33, 'city' => 'Williamstown'],
                ['state_id' => 33, 'city' => 'East Worcester'],
                ['state_id' => 33, 'city' => 'Maryland'],
                ['state_id' => 33, 'city' => 'Schenevus'],
                ['state_id' => 33, 'city' => 'Worcester'],
                ['state_id' => 33, 'city' => 'Burlington Flats'],
                ['state_id' => 33, 'city' => 'Cherry Valley'],
                ['state_id' => 33, 'city' => 'Cooperstown'],
                ['state_id' => 33, 'city' => 'East Springfield'],
                ['state_id' => 33, 'city' => 'Edmeston'],
                ['state_id' => 33, 'city' => 'Fly Creek'],
                ['state_id' => 33, 'city' => 'Garrattsville'],
                ['state_id' => 33, 'city' => 'Hartwick'],
                ['state_id' => 33, 'city' => 'New Lisbon'],
                ['state_id' => 33, 'city' => 'Richfield Springs'],
                ['state_id' => 33, 'city' => 'Roseboom'],
                ['state_id' => 33, 'city' => 'Schuyler Lake'],
                ['state_id' => 33, 'city' => 'Springfield Center'],
                ['state_id' => 33, 'city' => 'West Burlington'],
                ['state_id' => 33, 'city' => 'West Edmeston'],
                ['state_id' => 33, 'city' => 'Westford'],
                ['state_id' => 33, 'city' => 'Colliersville'],
                ['state_id' => 33, 'city' => 'Gilbertsville'],
                ['state_id' => 33, 'city' => 'Laurens'],
                ['state_id' => 33, 'city' => 'Milford'],
                ['state_id' => 33, 'city' => 'Morris'],
                ['state_id' => 33, 'city' => 'Mount Vision'],
                ['state_id' => 33, 'city' => 'Oneonta'],
                ['state_id' => 33, 'city' => 'Otego'],
                ['state_id' => 33, 'city' => 'Portlandville'],
                ['state_id' => 33, 'city' => 'Unadilla'],
                ['state_id' => 33, 'city' => 'Wells Bridge'],
                ['state_id' => 33, 'city' => 'West Oneonta'],
                ['state_id' => 33, 'city' => 'Brewster'],
                ['state_id' => 33, 'city' => 'Carmel'],
                ['state_id' => 33, 'city' => 'Cold Spring'],
                ['state_id' => 33, 'city' => 'Garrison'],
                ['state_id' => 33, 'city' => 'Lake Peekskill'],
                ['state_id' => 33, 'city' => 'Mahopac'],
                ['state_id' => 33, 'city' => 'Mahopac Falls'],
                ['state_id' => 33, 'city' => 'Putnam Valley'],
                ['state_id' => 33, 'city' => 'Patterson'],
                ['state_id' => 33, 'city' => 'Glen Oaks'],
                ['state_id' => 33, 'city' => 'Long Island City'],
                ['state_id' => 33, 'city' => 'Astoria'],
                ['state_id' => 33, 'city' => 'Sunnyside'],
                ['state_id' => 33, 'city' => 'Flushing'],
                ['state_id' => 33, 'city' => 'College Point'],
                ['state_id' => 33, 'city' => 'Whitestone'],
                ['state_id' => 33, 'city' => 'Bayside'],
                ['state_id' => 33, 'city' => 'Little Neck'],
                ['state_id' => 33, 'city' => 'Oakland Gardens'],
                ['state_id' => 33, 'city' => 'Fresh Meadows'],
                ['state_id' => 33, 'city' => 'Corona'],
                ['state_id' => 33, 'city' => 'East Elmhurst'],
                ['state_id' => 33, 'city' => 'Jackson Heights'],
                ['state_id' => 33, 'city' => 'Elmhurst'],
                ['state_id' => 33, 'city' => 'Rego Park'],
                ['state_id' => 33, 'city' => 'Forest Hills'],
                ['state_id' => 33, 'city' => 'Woodside'],
                ['state_id' => 33, 'city' => 'Maspeth'],
                ['state_id' => 33, 'city' => 'Middle Village'],
                ['state_id' => 33, 'city' => 'Ridgewood'],
                ['state_id' => 33, 'city' => 'Jamaica'],
                ['state_id' => 33, 'city' => 'Cambria Heights'],
                ['state_id' => 33, 'city' => 'Saint Albans'],
                ['state_id' => 33, 'city' => 'Springfield Gardens'],
                ['state_id' => 33, 'city' => 'Howard Beach'],
                ['state_id' => 33, 'city' => 'Kew Gardens'],
                ['state_id' => 33, 'city' => 'Ozone Park'],
                ['state_id' => 33, 'city' => 'Richmond Hill'],
                ['state_id' => 33, 'city' => 'South Richmond Hill'],
                ['state_id' => 33, 'city' => 'South Ozone Park'],
                ['state_id' => 33, 'city' => 'Woodhaven'],
                ['state_id' => 33, 'city' => 'Rosedale'],
                ['state_id' => 33, 'city' => 'Hollis'],
                ['state_id' => 33, 'city' => 'Bellerose'],
                ['state_id' => 33, 'city' => 'Queens Village'],
                ['state_id' => 33, 'city' => 'Far Rockaway'],
                ['state_id' => 33, 'city' => 'Arverne'],
                ['state_id' => 33, 'city' => 'Rockaway Park'],
                ['state_id' => 33, 'city' => 'Breezy Point'],
                ['state_id' => 33, 'city' => 'Averill Park'],
                ['state_id' => 33, 'city' => 'Berlin'],
                ['state_id' => 33, 'city' => 'Brainard'],
                ['state_id' => 33, 'city' => 'Buskirk'],
                ['state_id' => 33, 'city' => 'Castleton On Hudson'],
                ['state_id' => 33, 'city' => 'Cherry Plain'],
                ['state_id' => 33, 'city' => 'Cropseyville'],
                ['state_id' => 33, 'city' => 'East Greenbush'],
                ['state_id' => 33, 'city' => 'East Nassau'],
                ['state_id' => 33, 'city' => 'East Schodack'],
                ['state_id' => 33, 'city' => 'Grafton'],
                ['state_id' => 33, 'city' => 'Hoosick'],
                ['state_id' => 33, 'city' => 'Hoosick Falls'],
                ['state_id' => 33, 'city' => 'Johnsonville'],
                ['state_id' => 33, 'city' => 'Melrose'],
                ['state_id' => 33, 'city' => 'Nassau'],
                ['state_id' => 33, 'city' => 'North Hoosick'],
                ['state_id' => 33, 'city' => 'Petersburg'],
                ['state_id' => 33, 'city' => 'Poestenkill'],
                ['state_id' => 33, 'city' => 'Rensselaer'],
                ['state_id' => 33, 'city' => 'Sand Lake'],
                ['state_id' => 33, 'city' => 'Schaghticoke'],
                ['state_id' => 33, 'city' => 'Schodack Landing'],
                ['state_id' => 33, 'city' => 'Stephentown'],
                ['state_id' => 33, 'city' => 'Valley Falls'],
                ['state_id' => 33, 'city' => 'West Sand Lake'],
                ['state_id' => 33, 'city' => 'Wynantskill'],
                ['state_id' => 33, 'city' => 'Staten Island'],
                ['state_id' => 33, 'city' => 'Suffern'],
                ['state_id' => 33, 'city' => 'Bear Mountain'],
                ['state_id' => 33, 'city' => 'Blauvelt'],
                ['state_id' => 33, 'city' => 'Congers'],
                ['state_id' => 33, 'city' => 'Garnerville'],
                ['state_id' => 33, 'city' => 'Haverstraw'],
                ['state_id' => 33, 'city' => 'Hillburn'],
                ['state_id' => 33, 'city' => 'Monsey'],
                ['state_id' => 33, 'city' => 'Nanuet'],
                ['state_id' => 33, 'city' => 'New City'],
                ['state_id' => 33, 'city' => 'Nyack'],
                ['state_id' => 33, 'city' => 'Orangeburg'],
                ['state_id' => 33, 'city' => 'Palisades'],
                ['state_id' => 33, 'city' => 'Pearl River'],
                ['state_id' => 33, 'city' => 'Piermont'],
                ['state_id' => 33, 'city' => 'Pomona'],
                ['state_id' => 33, 'city' => 'Sloatsburg'],
                ['state_id' => 33, 'city' => 'Sparkill'],
                ['state_id' => 33, 'city' => 'Spring Valley'],
                ['state_id' => 33, 'city' => 'Stony Point'],
                ['state_id' => 33, 'city' => 'Tallman'],
                ['state_id' => 33, 'city' => 'Tappan'],
                ['state_id' => 33, 'city' => 'Thiells'],
                ['state_id' => 33, 'city' => 'Tomkins Cove'],
                ['state_id' => 33, 'city' => 'Valley Cottage'],
                ['state_id' => 33, 'city' => 'West Haverstraw'],
                ['state_id' => 33, 'city' => 'West Nyack'],
                ['state_id' => 33, 'city' => 'Childwold'],
                ['state_id' => 33, 'city' => 'Cranberry Lake'],
                ['state_id' => 33, 'city' => 'Lawrenceville'],
                ['state_id' => 33, 'city' => 'Nicholville'],
                ['state_id' => 33, 'city' => 'North Lawrence'],
                ['state_id' => 33, 'city' => 'Piercefield'],
                ['state_id' => 33, 'city' => 'Brasher Falls'],
                ['state_id' => 33, 'city' => 'Brier Hill'],
                ['state_id' => 33, 'city' => 'Canton'],
                ['state_id' => 33, 'city' => 'Chase Mills'],
                ['state_id' => 33, 'city' => 'Chippewa Bay'],
                ['state_id' => 33, 'city' => 'Colton'],
                ['state_id' => 33, 'city' => 'De Kalb Junction'],
                ['state_id' => 33, 'city' => 'De Peyster'],
                ['state_id' => 33, 'city' => 'Edwards'],
                ['state_id' => 33, 'city' => 'Fine'],
                ['state_id' => 33, 'city' => 'Gouverneur'],
                ['state_id' => 33, 'city' => 'Hailesboro'],
                ['state_id' => 33, 'city' => 'Hammond'],
                ['state_id' => 33, 'city' => 'Hannawa Falls'],
                ['state_id' => 33, 'city' => 'Helena'],
                ['state_id' => 33, 'city' => 'Hermon'],
                ['state_id' => 33, 'city' => 'Heuvelton'],
                ['state_id' => 33, 'city' => 'Lisbon'],
                ['state_id' => 33, 'city' => 'Madrid'],
                ['state_id' => 33, 'city' => 'Massena'],
                ['state_id' => 33, 'city' => 'Morristown'],
                ['state_id' => 33, 'city' => 'Newton Falls'],
                ['state_id' => 33, 'city' => 'Norfolk'],
                ['state_id' => 33, 'city' => 'Norwood'],
                ['state_id' => 33, 'city' => 'Ogdensburg'],
                ['state_id' => 33, 'city' => 'Oswegatchie'],
                ['state_id' => 33, 'city' => 'Parishville'],
                ['state_id' => 33, 'city' => 'Potsdam'],
                ['state_id' => 33, 'city' => 'Pyrites'],
                ['state_id' => 33, 'city' => 'Raymondville'],
                ['state_id' => 33, 'city' => 'Rensselaer Falls'],
                ['state_id' => 33, 'city' => 'Richville'],
                ['state_id' => 33, 'city' => 'Rooseveltown'],
                ['state_id' => 33, 'city' => 'Russell'],
                ['state_id' => 33, 'city' => 'South Colton'],
                ['state_id' => 33, 'city' => 'Star Lake'],
                ['state_id' => 33, 'city' => 'Waddington'],
                ['state_id' => 33, 'city' => 'Wanakena'],
                ['state_id' => 33, 'city' => 'West Stockholm'],
                ['state_id' => 33, 'city' => 'Winthrop'],
                ['state_id' => 33, 'city' => 'Ballston Lake'],
                ['state_id' => 33, 'city' => 'Ballston Spa'],
                ['state_id' => 33, 'city' => 'Burnt Hills'],
                ['state_id' => 33, 'city' => 'Clifton Park'],
                ['state_id' => 33, 'city' => 'Galway'],
                ['state_id' => 33, 'city' => 'Mechanicville'],
                ['state_id' => 33, 'city' => 'Rexford'],
                ['state_id' => 33, 'city' => 'Round Lake'],
                ['state_id' => 33, 'city' => 'Stillwater'],
                ['state_id' => 33, 'city' => 'Waterford'],
                ['state_id' => 33, 'city' => 'South Glens Falls'],
                ['state_id' => 33, 'city' => 'Corinth'],
                ['state_id' => 33, 'city' => 'Gansevoort'],
                ['state_id' => 33, 'city' => 'Greenfield Center'],
                ['state_id' => 33, 'city' => 'Hadley'],
                ['state_id' => 33, 'city' => 'Middle Grove'],
                ['state_id' => 33, 'city' => 'Porter Corners'],
                ['state_id' => 33, 'city' => 'Rock City Falls'],
                ['state_id' => 33, 'city' => 'Saratoga Springs'],
                ['state_id' => 33, 'city' => 'Schuylerville'],
                ['state_id' => 33, 'city' => 'Victory Mills'],
                ['state_id' => 33, 'city' => 'Alplaus'],
                ['state_id' => 33, 'city' => 'Delanson'],
                ['state_id' => 33, 'city' => 'Duanesburg'],
                ['state_id' => 33, 'city' => 'Pattersonville'],
                ['state_id' => 33, 'city' => 'Quaker Street'],
                ['state_id' => 33, 'city' => 'Rotterdam Junction'],
                ['state_id' => 33, 'city' => 'Schenectady'],
                ['state_id' => 33, 'city' => 'Carlisle'],
                ['state_id' => 33, 'city' => 'Central Bridge'],
                ['state_id' => 33, 'city' => 'Charlotteville'],
                ['state_id' => 33, 'city' => 'Cobleskill'],
                ['state_id' => 33, 'city' => 'Fultonham'],
                ['state_id' => 33, 'city' => 'Gallupville'],
                ['state_id' => 33, 'city' => 'Gilboa'],
                ['state_id' => 33, 'city' => 'Howes Cave'],
                ['state_id' => 33, 'city' => 'Jefferson'],
                ['state_id' => 33, 'city' => 'Middleburgh'],
                ['state_id' => 33, 'city' => 'North Blenheim'],
                ['state_id' => 33, 'city' => 'Richmondville'],
                ['state_id' => 33, 'city' => 'Schoharie'],
                ['state_id' => 33, 'city' => 'Sloansville'],
                ['state_id' => 33, 'city' => 'Summit'],
                ['state_id' => 33, 'city' => 'Warnerville'],
                ['state_id' => 33, 'city' => 'West Fulton'],
                ['state_id' => 33, 'city' => 'Sharon Springs'],
                ['state_id' => 33, 'city' => 'Alpine'],
                ['state_id' => 33, 'city' => 'Beaver Dams'],
                ['state_id' => 33, 'city' => 'Burdett'],
                ['state_id' => 33, 'city' => 'Cayuta'],
                ['state_id' => 33, 'city' => 'Hector'],
                ['state_id' => 33, 'city' => 'Mecklenburg'],
                ['state_id' => 33, 'city' => 'Montour Falls'],
                ['state_id' => 33, 'city' => 'Odessa'],
                ['state_id' => 33, 'city' => 'Reading Center'],
                ['state_id' => 33, 'city' => 'Tyrone'],
                ['state_id' => 33, 'city' => 'Watkins Glen'],
                ['state_id' => 33, 'city' => 'Wayne'],
                ['state_id' => 33, 'city' => 'Fayette'],
                ['state_id' => 33, 'city' => 'Seneca Falls'],
                ['state_id' => 33, 'city' => 'Waterloo'],
                ['state_id' => 33, 'city' => 'Ovid'],
                ['state_id' => 33, 'city' => 'Romulus'],
                ['state_id' => 33, 'city' => 'Willard'],
                ['state_id' => 33, 'city' => 'Interlaken'],
                ['state_id' => 33, 'city' => 'Lodi'],
                ['state_id' => 33, 'city' => 'Perkinsville'],
                ['state_id' => 33, 'city' => 'Wayland'],
                ['state_id' => 33, 'city' => 'Addison'],
                ['state_id' => 33, 'city' => 'Arkport'],
                ['state_id' => 33, 'city' => 'Atlanta'],
                ['state_id' => 33, 'city' => 'Avoca'],
                ['state_id' => 33, 'city' => 'Bath'],
                ['state_id' => 33, 'city' => 'Bradford'],
                ['state_id' => 33, 'city' => 'Cameron'],
                ['state_id' => 33, 'city' => 'Cameron Mills'],
                ['state_id' => 33, 'city' => 'Campbell'],
                ['state_id' => 33, 'city' => 'Canisteo'],
                ['state_id' => 33, 'city' => 'Cohocton'],
                ['state_id' => 33, 'city' => 'Coopers Plains'],
                ['state_id' => 33, 'city' => 'Corning'],
                ['state_id' => 33, 'city' => 'Greenwood'],
                ['state_id' => 33, 'city' => 'Hammondsport'],
                ['state_id' => 33, 'city' => 'Hornell'],
                ['state_id' => 33, 'city' => 'Jasper'],
                ['state_id' => 33, 'city' => 'Kanona'],
                ['state_id' => 33, 'city' => 'Lindley'],
                ['state_id' => 33, 'city' => 'Painted Post'],
                ['state_id' => 33, 'city' => 'Prattsburgh'],
                ['state_id' => 33, 'city' => 'Pulteney'],
                ['state_id' => 33, 'city' => 'Rexville'],
                ['state_id' => 33, 'city' => 'Savona'],
                ['state_id' => 33, 'city' => 'Troupsburg'],
                ['state_id' => 33, 'city' => 'Woodhull'],
                ['state_id' => 33, 'city' => 'Holtsville'],
                ['state_id' => 33, 'city' => 'Fishers Island'],
                ['state_id' => 33, 'city' => 'Amityville'],
                ['state_id' => 33, 'city' => 'Babylon'],
                ['state_id' => 33, 'city' => 'North Babylon'],
                ['state_id' => 33, 'city' => 'West Babylon'],
                ['state_id' => 33, 'city' => 'Bayport'],
                ['state_id' => 33, 'city' => 'Bay Shore'],
                ['state_id' => 33, 'city' => 'Bellport'],
                ['state_id' => 33, 'city' => 'Blue Point'],
                ['state_id' => 33, 'city' => 'Bohemia'],
                ['state_id' => 33, 'city' => 'Brentwood'],
                ['state_id' => 33, 'city' => 'Brightwaters'],
                ['state_id' => 33, 'city' => 'Brookhaven'],
                ['state_id' => 33, 'city' => 'Centereach'],
                ['state_id' => 33, 'city' => 'Centerport'],
                ['state_id' => 33, 'city' => 'Central Islip'],
                ['state_id' => 33, 'city' => 'Cold Spring Harbor'],
                ['state_id' => 33, 'city' => 'Commack'],
                ['state_id' => 33, 'city' => 'Copiague'],
                ['state_id' => 33, 'city' => 'Coram'],
                ['state_id' => 33, 'city' => 'Deer Park'],
                ['state_id' => 33, 'city' => 'East Islip'],
                ['state_id' => 33, 'city' => 'East Northport'],
                ['state_id' => 33, 'city' => 'East Setauket'],
                ['state_id' => 33, 'city' => 'Farmingville'],
                ['state_id' => 33, 'city' => 'Great River'],
                ['state_id' => 33, 'city' => 'Greenlawn'],
                ['state_id' => 33, 'city' => 'Holbrook'],
                ['state_id' => 33, 'city' => 'Huntington'],
                ['state_id' => 33, 'city' => 'Huntington Station'],
                ['state_id' => 33, 'city' => 'Melville'],
                ['state_id' => 33, 'city' => 'Islandia'],
                ['state_id' => 33, 'city' => 'Islip'],
                ['state_id' => 33, 'city' => 'Islip Terrace'],
                ['state_id' => 33, 'city' => 'Kings Park'],
                ['state_id' => 33, 'city' => 'Lake Grove'],
                ['state_id' => 33, 'city' => 'Lindenhurst'],
                ['state_id' => 33, 'city' => 'Medford'],
                ['state_id' => 33, 'city' => 'Miller Place'],
                ['state_id' => 33, 'city' => 'Mount Sinai'],
                ['state_id' => 33, 'city' => 'Nesconset'],
                ['state_id' => 33, 'city' => 'Northport'],
                ['state_id' => 33, 'city' => 'Oakdale'],
                ['state_id' => 33, 'city' => 'Ocean Beach'],
                ['state_id' => 33, 'city' => 'Patchogue'],
                ['state_id' => 33, 'city' => 'Port Jefferson Station'],
                ['state_id' => 33, 'city' => 'Port Jefferson'],
                ['state_id' => 33, 'city' => 'Rocky Point'],
                ['state_id' => 33, 'city' => 'Ronkonkoma'],
                ['state_id' => 33, 'city' => 'Saint James'],
                ['state_id' => 33, 'city' => 'Sayville'],
                ['state_id' => 33, 'city' => 'Selden'],
                ['state_id' => 33, 'city' => 'Shoreham'],
                ['state_id' => 33, 'city' => 'Smithtown'],
                ['state_id' => 33, 'city' => 'Hauppauge'],
                ['state_id' => 33, 'city' => 'Sound Beach'],
                ['state_id' => 33, 'city' => 'Stony Brook'],
                ['state_id' => 33, 'city' => 'Wading River'],
                ['state_id' => 33, 'city' => 'West Islip'],
                ['state_id' => 33, 'city' => 'West Sayville'],
                ['state_id' => 33, 'city' => 'Wyandanch'],
                ['state_id' => 33, 'city' => 'Riverhead'],
                ['state_id' => 33, 'city' => 'Amagansett'],
                ['state_id' => 33, 'city' => 'Aquebogue'],
                ['state_id' => 33, 'city' => 'Bridgehampton'],
                ['state_id' => 33, 'city' => 'Calverton'],
                ['state_id' => 33, 'city' => 'Center Moriches'],
                ['state_id' => 33, 'city' => 'Cutchogue'],
                ['state_id' => 33, 'city' => 'East Hampton'],
                ['state_id' => 33, 'city' => 'East Marion'],
                ['state_id' => 33, 'city' => 'East Moriches'],
                ['state_id' => 33, 'city' => 'Eastport'],
                ['state_id' => 33, 'city' => 'East Quogue'],
                ['state_id' => 33, 'city' => 'Greenport'],
                ['state_id' => 33, 'city' => 'Hampton Bays'],
                ['state_id' => 33, 'city' => 'Jamesport'],
                ['state_id' => 33, 'city' => 'Laurel'],
                ['state_id' => 33, 'city' => 'Manorville'],
                ['state_id' => 33, 'city' => 'Mastic'],
                ['state_id' => 33, 'city' => 'Mastic Beach'],
                ['state_id' => 33, 'city' => 'Mattituck'],
                ['state_id' => 33, 'city' => 'Middle Island'],
                ['state_id' => 33, 'city' => 'Montauk'],
                ['state_id' => 33, 'city' => 'Moriches'],
                ['state_id' => 33, 'city' => 'New Suffolk'],
                ['state_id' => 33, 'city' => 'Orient'],
                ['state_id' => 33, 'city' => 'Peconic'],
                ['state_id' => 33, 'city' => 'Quogue'],
                ['state_id' => 33, 'city' => 'Remsenburg'],
                ['state_id' => 33, 'city' => 'Ridge'],
                ['state_id' => 33, 'city' => 'Sagaponack'],
                ['state_id' => 33, 'city' => 'Sag Harbor'],
                ['state_id' => 33, 'city' => 'Shelter Island'],
                ['state_id' => 33, 'city' => 'Shelter Island Heights'],
                ['state_id' => 33, 'city' => 'Shirley'],
                ['state_id' => 33, 'city' => 'Southampton'],
                ['state_id' => 33, 'city' => 'South Jamesport'],
                ['state_id' => 33, 'city' => 'Southold'],
                ['state_id' => 33, 'city' => 'Speonk'],
                ['state_id' => 33, 'city' => 'Upton'],
                ['state_id' => 33, 'city' => 'Wainscott'],
                ['state_id' => 33, 'city' => 'Water Mill'],
                ['state_id' => 33, 'city' => 'Westhampton'],
                ['state_id' => 33, 'city' => 'Westhampton Beach'],
                ['state_id' => 33, 'city' => 'Yaphank'],
                ['state_id' => 33, 'city' => 'Monticello'],
                ['state_id' => 33, 'city' => 'Barryville'],
                ['state_id' => 33, 'city' => 'Bethel'],
                ['state_id' => 33, 'city' => 'Bloomingburg'],
                ['state_id' => 33, 'city' => 'Burlingham'],
                ['state_id' => 33, 'city' => 'Callicoon'],
                ['state_id' => 33, 'city' => 'Callicoon Center'],
                ['state_id' => 33, 'city' => 'Claryville'],
                ['state_id' => 33, 'city' => 'Cochecton'],
                ['state_id' => 33, 'city' => 'Cochecton Center'],
                ['state_id' => 33, 'city' => 'Eldred'],
                ['state_id' => 33, 'city' => 'Fallsburg'],
                ['state_id' => 33, 'city' => 'Ferndale'],
                ['state_id' => 33, 'city' => 'Fremont Center'],
                ['state_id' => 33, 'city' => 'Glen Spey'],
                ['state_id' => 33, 'city' => 'Glen Wild'],
                ['state_id' => 33, 'city' => 'Grahamsville'],
                ['state_id' => 33, 'city' => 'Hankins'],
                ['state_id' => 33, 'city' => 'Harris'],
                ['state_id' => 33, 'city' => 'Highland Lake'],
                ['state_id' => 33, 'city' => 'Hortonville'],
                ['state_id' => 33, 'city' => 'Hurleyville'],
                ['state_id' => 33, 'city' => 'Jeffersonville'],
                ['state_id' => 33, 'city' => 'Kauneonga Lake'],
                ['state_id' => 33, 'city' => 'Kenoza Lake'],
                ['state_id' => 33, 'city' => 'Kiamesha Lake'],
                ['state_id' => 33, 'city' => 'Lake Huntington'],
                ['state_id' => 33, 'city' => 'Liberty'],
                ['state_id' => 33, 'city' => 'Livingston Manor'],
                ['state_id' => 33, 'city' => 'Loch Sheldrake'],
                ['state_id' => 33, 'city' => 'Long Eddy'],
                ['state_id' => 33, 'city' => 'Mongaup Valley'],
                ['state_id' => 33, 'city' => 'Mountain Dale'],
                ['state_id' => 33, 'city' => 'Narrowsburg'],
                ['state_id' => 33, 'city' => 'Neversink'],
                ['state_id' => 33, 'city' => 'North Branch'],
                ['state_id' => 33, 'city' => 'Obernburg'],
                ['state_id' => 33, 'city' => 'Parksville'],
                ['state_id' => 33, 'city' => 'Phillipsport'],
                ['state_id' => 33, 'city' => 'Pond Eddy'],
                ['state_id' => 33, 'city' => 'Rock Hill'],
                ['state_id' => 33, 'city' => 'Roscoe'],
                ['state_id' => 33, 'city' => 'Forestburgh'],
                ['state_id' => 33, 'city' => 'Smallwood'],
                ['state_id' => 33, 'city' => 'South Fallsburg'],
                ['state_id' => 33, 'city' => 'Summitville'],
                ['state_id' => 33, 'city' => 'Swan Lake'],
                ['state_id' => 33, 'city' => 'Thompsonville'],
                ['state_id' => 33, 'city' => 'Westbrookville'],
                ['state_id' => 33, 'city' => 'White Lake'],
                ['state_id' => 33, 'city' => 'White Sulphur Springs'],
                ['state_id' => 33, 'city' => 'Woodbourne'],
                ['state_id' => 33, 'city' => 'Woodridge'],
                ['state_id' => 33, 'city' => 'Wurtsboro'],
                ['state_id' => 33, 'city' => 'Youngsville'],
                ['state_id' => 33, 'city' => 'Yulan'],
                ['state_id' => 33, 'city' => 'Apalachin'],
                ['state_id' => 33, 'city' => 'Barton'],
                ['state_id' => 33, 'city' => 'Berkshire'],
                ['state_id' => 33, 'city' => 'Candor'],
                ['state_id' => 33, 'city' => 'Newark Valley'],
                ['state_id' => 33, 'city' => 'Nichols'],
                ['state_id' => 33, 'city' => 'Owego'],
                ['state_id' => 33, 'city' => 'Richford'],
                ['state_id' => 33, 'city' => 'Smithboro'],
                ['state_id' => 33, 'city' => 'Tioga Center'],
                ['state_id' => 33, 'city' => 'Willseyville'],
                ['state_id' => 33, 'city' => 'Lockwood'],
                ['state_id' => 33, 'city' => 'Spencer'],
                ['state_id' => 33, 'city' => 'Waverly'],
                ['state_id' => 33, 'city' => 'Dryden'],
                ['state_id' => 33, 'city' => 'Etna'],
                ['state_id' => 33, 'city' => 'Freeville'],
                ['state_id' => 33, 'city' => 'Groton'],
                ['state_id' => 33, 'city' => 'Mc Lean'],
                ['state_id' => 33, 'city' => 'Brooktondale'],
                ['state_id' => 33, 'city' => 'Ithaca'],
                ['state_id' => 33, 'city' => 'Jacksonville'],
                ['state_id' => 33, 'city' => 'Newfield'],
                ['state_id' => 33, 'city' => 'Slaterville Springs'],
                ['state_id' => 33, 'city' => 'Lansing'],
                ['state_id' => 33, 'city' => 'Trumansburg'],
                ['state_id' => 33, 'city' => 'Kingston'],
                ['state_id' => 33, 'city' => 'Accord'],
                ['state_id' => 33, 'city' => 'Bearsville'],
                ['state_id' => 33, 'city' => 'Big Indian'],
                ['state_id' => 33, 'city' => 'Bloomington'],
                ['state_id' => 33, 'city' => 'Boiceville'],
                ['state_id' => 33, 'city' => 'Chichester'],
                ['state_id' => 33, 'city' => 'Connelly'],
                ['state_id' => 33, 'city' => 'Cottekill'],
                ['state_id' => 33, 'city' => 'Cragsmoor'],
                ['state_id' => 33, 'city' => 'Ellenville'],
                ['state_id' => 33, 'city' => 'Esopus'],
                ['state_id' => 33, 'city' => 'Glasco'],
                ['state_id' => 33, 'city' => 'Glenford'],
                ['state_id' => 33, 'city' => 'Greenfield Park'],
                ['state_id' => 33, 'city' => 'High Falls'],
                ['state_id' => 33, 'city' => 'Highmount'],
                ['state_id' => 33, 'city' => 'Hurley'],
                ['state_id' => 33, 'city' => 'Kerhonkson'],
                ['state_id' => 33, 'city' => 'Lake Hill'],
                ['state_id' => 33, 'city' => 'Lake Katrine'],
                ['state_id' => 33, 'city' => 'Malden On Hudson'],
                ['state_id' => 33, 'city' => 'Mount Marion'],
                ['state_id' => 33, 'city' => 'Mount Tremper'],
                ['state_id' => 33, 'city' => 'Napanoch'],
                ['state_id' => 33, 'city' => 'Olivebridge'],
                ['state_id' => 33, 'city' => 'Phoenicia'],
                ['state_id' => 33, 'city' => 'Pine Hill'],
                ['state_id' => 33, 'city' => 'Port Ewen'],
                ['state_id' => 33, 'city' => 'Rifton'],
                ['state_id' => 33, 'city' => 'Rosendale'],
                ['state_id' => 33, 'city' => 'Ruby'],
                ['state_id' => 33, 'city' => 'Saugerties'],
                ['state_id' => 33, 'city' => 'Shandaken'],
                ['state_id' => 33, 'city' => 'Shokan'],
                ['state_id' => 33, 'city' => 'Spring Glen'],
                ['state_id' => 33, 'city' => 'Stone Ridge'],
                ['state_id' => 33, 'city' => 'Tillson'],
                ['state_id' => 33, 'city' => 'Ulster Park'],
                ['state_id' => 33, 'city' => 'Wawarsing'],
                ['state_id' => 33, 'city' => 'West Camp'],
                ['state_id' => 33, 'city' => 'West Hurley'],
                ['state_id' => 33, 'city' => 'West Park'],
                ['state_id' => 33, 'city' => 'West Shokan'],
                ['state_id' => 33, 'city' => 'Willow'],
                ['state_id' => 33, 'city' => 'Woodstock'],
                ['state_id' => 33, 'city' => 'Clintondale'],
                ['state_id' => 33, 'city' => 'Gardiner'],
                ['state_id' => 33, 'city' => 'Highland'],
                ['state_id' => 33, 'city' => 'Marlboro'],
                ['state_id' => 33, 'city' => 'Milton'],
                ['state_id' => 33, 'city' => 'Modena'],
                ['state_id' => 33, 'city' => 'New Paltz'],
                ['state_id' => 33, 'city' => 'Plattekill'],
                ['state_id' => 33, 'city' => 'Walker Valley'],
                ['state_id' => 33, 'city' => 'Wallkill'],
                ['state_id' => 33, 'city' => 'Glens Falls'],
                ['state_id' => 33, 'city' => 'Queensbury'],
                ['state_id' => 33, 'city' => 'Adirondack'],
                ['state_id' => 33, 'city' => 'Athol'],
                ['state_id' => 33, 'city' => 'Bakers Mills'],
                ['state_id' => 33, 'city' => 'Bolton Landing'],
                ['state_id' => 33, 'city' => 'Brant Lake'],
                ['state_id' => 33, 'city' => 'Chestertown'],
                ['state_id' => 33, 'city' => 'Cleverdale'],
                ['state_id' => 33, 'city' => 'Diamond Point'],
                ['state_id' => 33, 'city' => 'Hague'],
                ['state_id' => 33, 'city' => 'Johnsburg'],
                ['state_id' => 33, 'city' => 'Kattskill Bay'],
                ['state_id' => 33, 'city' => 'Lake George'],
                ['state_id' => 33, 'city' => 'Lake Luzerne'],
                ['state_id' => 33, 'city' => 'North Creek'],
                ['state_id' => 33, 'city' => 'North River'],
                ['state_id' => 33, 'city' => 'Pottersville'],
                ['state_id' => 33, 'city' => 'Riparius'],
                ['state_id' => 33, 'city' => 'Silver Bay'],
                ['state_id' => 33, 'city' => 'Stony Creek'],
                ['state_id' => 33, 'city' => 'Warrensburg'],
                ['state_id' => 33, 'city' => 'Wevertown'],
                ['state_id' => 33, 'city' => 'Eagle Bridge'],
                ['state_id' => 33, 'city' => 'Argyle'],
                ['state_id' => 33, 'city' => 'Cambridge'],
                ['state_id' => 33, 'city' => 'Clemons'],
                ['state_id' => 33, 'city' => 'Comstock'],
                ['state_id' => 33, 'city' => 'Cossayuna'],
                ['state_id' => 33, 'city' => 'Fort Ann'],
                ['state_id' => 33, 'city' => 'Fort Edward'],
                ['state_id' => 33, 'city' => 'Granville'],
                ['state_id' => 33, 'city' => 'Greenwich'],
                ['state_id' => 33, 'city' => 'Hampton'],
                ['state_id' => 33, 'city' => 'Hartford'],
                ['state_id' => 33, 'city' => 'Hudson Falls'],
                ['state_id' => 33, 'city' => 'Huletts Landing'],
                ['state_id' => 33, 'city' => 'Middle Falls'],
                ['state_id' => 33, 'city' => 'Middle Granville'],
                ['state_id' => 33, 'city' => 'North Granville'],
                ['state_id' => 33, 'city' => 'Putnam Station'],
                ['state_id' => 33, 'city' => 'Salem'],
                ['state_id' => 33, 'city' => 'Shushan'],
                ['state_id' => 33, 'city' => 'Whitehall'],
                ['state_id' => 33, 'city' => 'Red Creek'],
                ['state_id' => 33, 'city' => 'Savannah'],
                ['state_id' => 33, 'city' => 'South Butler'],
                ['state_id' => 33, 'city' => 'Alton'],
                ['state_id' => 33, 'city' => 'Clyde'],
                ['state_id' => 33, 'city' => 'East Williamson'],
                ['state_id' => 33, 'city' => 'Lyons'],
                ['state_id' => 33, 'city' => 'Macedon'],
                ['state_id' => 33, 'city' => 'Marion'],
                ['state_id' => 33, 'city' => 'Newark'],
                ['state_id' => 33, 'city' => 'North Rose'],
                ['state_id' => 33, 'city' => 'Ontario'],
                ['state_id' => 33, 'city' => 'Ontario Center'],
                ['state_id' => 33, 'city' => 'Palmyra'],
                ['state_id' => 33, 'city' => 'Pultneyville'],
                ['state_id' => 33, 'city' => 'Rose'],
                ['state_id' => 33, 'city' => 'Sodus'],
                ['state_id' => 33, 'city' => 'Sodus Point'],
                ['state_id' => 33, 'city' => 'Union Hill'],
                ['state_id' => 33, 'city' => 'Walworth'],
                ['state_id' => 33, 'city' => 'Williamson'],
                ['state_id' => 33, 'city' => 'Wolcott'],
                ['state_id' => 33, 'city' => 'Amawalk'],
                ['state_id' => 33, 'city' => 'Ardsley'],
                ['state_id' => 33, 'city' => 'Ardsley On Hudson'],
                ['state_id' => 33, 'city' => 'Armonk'],
                ['state_id' => 33, 'city' => 'Baldwin Place'],
                ['state_id' => 33, 'city' => 'Bedford'],
                ['state_id' => 33, 'city' => 'Bedford Hills'],
                ['state_id' => 33, 'city' => 'Briarcliff Manor'],
                ['state_id' => 33, 'city' => 'Buchanan'],
                ['state_id' => 33, 'city' => 'Chappaqua'],
                ['state_id' => 33, 'city' => 'Crompond'],
                ['state_id' => 33, 'city' => 'Cross River'],
                ['state_id' => 33, 'city' => 'Croton Falls'],
                ['state_id' => 33, 'city' => 'Croton On Hudson'],
                ['state_id' => 33, 'city' => 'Dobbs Ferry'],
                ['state_id' => 33, 'city' => 'Elmsford'],
                ['state_id' => 33, 'city' => 'Goldens Bridge'],
                ['state_id' => 33, 'city' => 'Granite Springs'],
                ['state_id' => 33, 'city' => 'Harrison'],
                ['state_id' => 33, 'city' => 'Hartsdale'],
                ['state_id' => 33, 'city' => 'Hawthorne'],
                ['state_id' => 33, 'city' => 'Irvington'],
                ['state_id' => 33, 'city' => 'Jefferson Valley'],
                ['state_id' => 33, 'city' => 'Katonah'],
                ['state_id' => 33, 'city' => 'Larchmont'],
                ['state_id' => 33, 'city' => 'Lincolndale'],
                ['state_id' => 33, 'city' => 'Mamaroneck'],
                ['state_id' => 33, 'city' => 'Maryknoll'],
                ['state_id' => 33, 'city' => 'Millwood'],
                ['state_id' => 33, 'city' => 'Mohegan Lake'],
                ['state_id' => 33, 'city' => 'Montrose'],
                ['state_id' => 33, 'city' => 'Mount Kisco'],
                ['state_id' => 33, 'city' => 'Mount Vernon'],
                ['state_id' => 33, 'city' => 'North Salem'],
                ['state_id' => 33, 'city' => 'Ossining'],
                ['state_id' => 33, 'city' => 'Peekskill'],
                ['state_id' => 33, 'city' => 'Cortlandt Manor'],
                ['state_id' => 33, 'city' => 'Pleasantville'],
                ['state_id' => 33, 'city' => 'Port Chester'],
                ['state_id' => 33, 'city' => 'Pound Ridge'],
                ['state_id' => 33, 'city' => 'Purchase'],
                ['state_id' => 33, 'city' => 'Purdys'],
                ['state_id' => 33, 'city' => 'Rye'],
                ['state_id' => 33, 'city' => 'Scarsdale'],
                ['state_id' => 33, 'city' => 'Shenorock'],
                ['state_id' => 33, 'city' => 'Shrub Oak'],
                ['state_id' => 33, 'city' => 'Somers'],
                ['state_id' => 33, 'city' => 'South Salem'],
                ['state_id' => 33, 'city' => 'Tarrytown'],
                ['state_id' => 33, 'city' => 'Thornwood'],
                ['state_id' => 33, 'city' => 'Valhalla'],
                ['state_id' => 33, 'city' => 'Verplanck'],
                ['state_id' => 33, 'city' => 'Waccabuc'],
                ['state_id' => 33, 'city' => 'Yorktown Heights'],
                ['state_id' => 33, 'city' => 'White Plains'],
                ['state_id' => 33, 'city' => 'West Harrison'],
                ['state_id' => 33, 'city' => 'Yonkers'],
                ['state_id' => 33, 'city' => 'Hastings On Hudson'],
                ['state_id' => 33, 'city' => 'Tuckahoe'],
                ['state_id' => 33, 'city' => 'Bronxville'],
                ['state_id' => 33, 'city' => 'Eastchester'],
                ['state_id' => 33, 'city' => 'New Rochelle'],
                ['state_id' => 33, 'city' => 'Pelham'],
                ['state_id' => 33, 'city' => 'Arcade'],
                ['state_id' => 33, 'city' => 'Attica'],
                ['state_id' => 33, 'city' => 'Bliss'],
                ['state_id' => 33, 'city' => 'Cowlesville'],
                ['state_id' => 33, 'city' => 'Dale'],
                ['state_id' => 33, 'city' => 'Gainesville'],
                ['state_id' => 33, 'city' => 'Java Center'],
                ['state_id' => 33, 'city' => 'Java Village'],
                ['state_id' => 33, 'city' => 'North Java'],
                ['state_id' => 33, 'city' => 'Pike'],
                ['state_id' => 33, 'city' => 'Strykersville'],
                ['state_id' => 33, 'city' => 'Varysburg'],
                ['state_id' => 33, 'city' => 'Castile'],
                ['state_id' => 33, 'city' => 'Perry'],
                ['state_id' => 33, 'city' => 'Portageville'],
                ['state_id' => 33, 'city' => 'Silver Lake'],
                ['state_id' => 33, 'city' => 'Silver Springs'],
                ['state_id' => 33, 'city' => 'Warsaw'],
                ['state_id' => 33, 'city' => 'Wyoming'],
                ['state_id' => 33, 'city' => 'Bellona'],
                ['state_id' => 33, 'city' => 'Branchport'],
                ['state_id' => 33, 'city' => 'Dresden'],
                ['state_id' => 33, 'city' => 'Keuka Park'],
                ['state_id' => 33, 'city' => 'Middlesex'],
                ['state_id' => 33, 'city' => 'Penn Yan'],
                ['state_id' => 33, 'city' => 'Rushville'],
                ['state_id' => 33, 'city' => 'Dundee'],
                ['state_id' => 33, 'city' => 'Himrod'],
                ['state_id' => 33, 'city' => 'Lakemont'],
                ['state_id' => 33, 'city' => 'Rock Stream', 'state_id' => 35]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
