<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State28TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NE - Nebraska.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 28, 'city' => 'Hastings'],
                ['state_id' => 28, 'city' => 'Ayr'],
                ['state_id' => 28, 'city' => 'Holstein'],
                ['state_id' => 28, 'city' => 'Juniata'],
                ['state_id' => 28, 'city' => 'Kenesaw'],
                ['state_id' => 28, 'city' => 'Roseland'],
                ['state_id' => 28, 'city' => 'Elgin'],
                ['state_id' => 28, 'city' => 'Brunswick'],
                ['state_id' => 28, 'city' => 'Clearwater'],
                ['state_id' => 28, 'city' => 'Neligh'],
                ['state_id' => 28, 'city' => 'Oakdale'],
                ['state_id' => 28, 'city' => 'Orchard'],
                ['state_id' => 28, 'city' => 'Royal'],
                ['state_id' => 28, 'city' => 'Arthur'],
                ['state_id' => 28, 'city' => 'Harrisburg'],
                ['state_id' => 28, 'city' => 'Brewster'],
                ['state_id' => 28, 'city' => 'Dunning'],
                ['state_id' => 28, 'city' => 'Purdum'],
                ['state_id' => 28, 'city' => 'Albion'],
                ['state_id' => 28, 'city' => 'Cedar Rapids'],
                ['state_id' => 28, 'city' => 'Petersburg'],
                ['state_id' => 28, 'city' => 'Primrose'],
                ['state_id' => 28, 'city' => 'Saint Edward'],
                ['state_id' => 28, 'city' => 'Alliance'],
                ['state_id' => 28, 'city' => 'Hemingford'],
                ['state_id' => 28, 'city' => 'Bristow'],
                ['state_id' => 28, 'city' => 'Butte'],
                ['state_id' => 28, 'city' => 'Lynch'],
                ['state_id' => 28, 'city' => 'Naper'],
                ['state_id' => 28, 'city' => 'Spencer'],
                ['state_id' => 28, 'city' => 'Ainsworth'],
                ['state_id' => 28, 'city' => 'Johnstown'],
                ['state_id' => 28, 'city' => 'Long Pine'],
                ['state_id' => 28, 'city' => 'Amherst'],
                ['state_id' => 28, 'city' => 'Elm Creek'],
                ['state_id' => 28, 'city' => 'Gibbon'],
                ['state_id' => 28, 'city' => 'Kearney'],
                ['state_id' => 28, 'city' => 'Miller'],
                ['state_id' => 28, 'city' => 'Odessa'],
                ['state_id' => 28, 'city' => 'Pleasanton'],
                ['state_id' => 28, 'city' => 'Ravenna'],
                ['state_id' => 28, 'city' => 'Riverdale'],
                ['state_id' => 28, 'city' => 'Shelton'],
                ['state_id' => 28, 'city' => 'Craig'],
                ['state_id' => 28, 'city' => 'Decatur'],
                ['state_id' => 28, 'city' => 'Lyons'],
                ['state_id' => 28, 'city' => 'Oakland'],
                ['state_id' => 28, 'city' => 'Tekamah'],
                ['state_id' => 28, 'city' => 'Abie'],
                ['state_id' => 28, 'city' => 'Bruno'],
                ['state_id' => 28, 'city' => 'Linwood'],
                ['state_id' => 28, 'city' => 'Bellwood'],
                ['state_id' => 28, 'city' => 'Brainard'],
                ['state_id' => 28, 'city' => 'David City'],
                ['state_id' => 28, 'city' => 'Dwight'],
                ['state_id' => 28, 'city' => 'Rising City'],
                ['state_id' => 28, 'city' => 'Surprise'],
                ['state_id' => 28, 'city' => 'Ulysses'],
                ['state_id' => 28, 'city' => 'Cedar Creek'],
                ['state_id' => 28, 'city' => 'Louisville'],
                ['state_id' => 28, 'city' => 'Plattsmouth'],
                ['state_id' => 28, 'city' => 'South Bend'],
                ['state_id' => 28, 'city' => 'Alvo'],
                ['state_id' => 28, 'city' => 'Avoca'],
                ['state_id' => 28, 'city' => 'Eagle'],
                ['state_id' => 28, 'city' => 'Elmwood'],
                ['state_id' => 28, 'city' => 'Greenwood'],
                ['state_id' => 28, 'city' => 'Manley'],
                ['state_id' => 28, 'city' => 'Murdock'],
                ['state_id' => 28, 'city' => 'Murray'],
                ['state_id' => 28, 'city' => 'Nehawka'],
                ['state_id' => 28, 'city' => 'Union'],
                ['state_id' => 28, 'city' => 'Weeping Water'],
                ['state_id' => 28, 'city' => 'Belden'],
                ['state_id' => 28, 'city' => 'Coleridge'],
                ['state_id' => 28, 'city' => 'Fordyce'],
                ['state_id' => 28, 'city' => 'Hartington'],
                ['state_id' => 28, 'city' => 'Laurel'],
                ['state_id' => 28, 'city' => 'Magnet'],
                ['state_id' => 28, 'city' => 'Randolph'],
                ['state_id' => 28, 'city' => 'Saint Helena'],
                ['state_id' => 28, 'city' => 'Wynot'],
                ['state_id' => 28, 'city' => 'Champion'],
                ['state_id' => 28, 'city' => 'Enders'],
                ['state_id' => 28, 'city' => 'Imperial'],
                ['state_id' => 28, 'city' => 'Wauneta'],
                ['state_id' => 28, 'city' => 'Elsmere'],
                ['state_id' => 28, 'city' => 'Valentine'],
                ['state_id' => 28, 'city' => 'Cody'],
                ['state_id' => 28, 'city' => 'Crookston'],
                ['state_id' => 28, 'city' => 'Kilgore'],
                ['state_id' => 28, 'city' => 'Merriman'],
                ['state_id' => 28, 'city' => 'Nenzel'],
                ['state_id' => 28, 'city' => 'Sparks'],
                ['state_id' => 28, 'city' => 'Wood Lake'],
                ['state_id' => 28, 'city' => 'Dalton'],
                ['state_id' => 28, 'city' => 'Gurley'],
                ['state_id' => 28, 'city' => 'Lodgepole'],
                ['state_id' => 28, 'city' => 'Potter'],
                ['state_id' => 28, 'city' => 'Sidney'],
                ['state_id' => 28, 'city' => 'Ong'],
                ['state_id' => 28, 'city' => 'Clay Center'],
                ['state_id' => 28, 'city' => 'Deweese'],
                ['state_id' => 28, 'city' => 'Edgar'],
                ['state_id' => 28, 'city' => 'Fairfield'],
                ['state_id' => 28, 'city' => 'Glenvil'],
                ['state_id' => 28, 'city' => 'Harvard'],
                ['state_id' => 28, 'city' => 'Inland'],
                ['state_id' => 28, 'city' => 'Saronville'],
                ['state_id' => 28, 'city' => 'Sutton'],
                ['state_id' => 28, 'city' => 'Trumbull'],
                ['state_id' => 28, 'city' => 'Clarkson'],
                ['state_id' => 28, 'city' => 'Howells'],
                ['state_id' => 28, 'city' => 'Leigh'],
                ['state_id' => 28, 'city' => 'Rogers'],
                ['state_id' => 28, 'city' => 'Schuyler'],
                ['state_id' => 28, 'city' => 'Bancroft'],
                ['state_id' => 28, 'city' => 'Beemer'],
                ['state_id' => 28, 'city' => 'West Point'],
                ['state_id' => 28, 'city' => 'Wisner'],
                ['state_id' => 28, 'city' => 'Anselmo'],
                ['state_id' => 28, 'city' => 'Ansley'],
                ['state_id' => 28, 'city' => 'Broken Bow'],
                ['state_id' => 28, 'city' => 'Callaway'],
                ['state_id' => 28, 'city' => 'Comstock'],
                ['state_id' => 28, 'city' => 'Mason City'],
                ['state_id' => 28, 'city' => 'Merna'],
                ['state_id' => 28, 'city' => 'Oconto'],
                ['state_id' => 28, 'city' => 'Sargent'],
                ['state_id' => 28, 'city' => 'Westerville'],
                ['state_id' => 28, 'city' => 'Arnold'],
                ['state_id' => 28, 'city' => 'Homer'],
                ['state_id' => 28, 'city' => 'Dakota City'],
                ['state_id' => 28, 'city' => 'Emerson'],
                ['state_id' => 28, 'city' => 'Hubbard'],
                ['state_id' => 28, 'city' => 'Jackson'],
                ['state_id' => 28, 'city' => 'South Sioux City'],
                ['state_id' => 28, 'city' => 'Chadron'],
                ['state_id' => 28, 'city' => 'Crawford'],
                ['state_id' => 28, 'city' => 'Marsland'],
                ['state_id' => 28, 'city' => 'Whitney'],
                ['state_id' => 28, 'city' => 'Eddyville'],
                ['state_id' => 28, 'city' => 'Lexington'],
                ['state_id' => 28, 'city' => 'Overton'],
                ['state_id' => 28, 'city' => 'Sumner'],
                ['state_id' => 28, 'city' => 'Farnam'],
                ['state_id' => 28, 'city' => 'Cozad'],
                ['state_id' => 28, 'city' => 'Gothenburg'],
                ['state_id' => 28, 'city' => 'Willow Island'],
                ['state_id' => 28, 'city' => 'Big Springs'],
                ['state_id' => 28, 'city' => 'Chappell'],
                ['state_id' => 28, 'city' => 'Allen'],
                ['state_id' => 28, 'city' => 'Concord'],
                ['state_id' => 28, 'city' => 'Dixon'],
                ['state_id' => 28, 'city' => 'Maskell'],
                ['state_id' => 28, 'city' => 'Newcastle'],
                ['state_id' => 28, 'city' => 'Ponca'],
                ['state_id' => 28, 'city' => 'Wakefield'],
                ['state_id' => 28, 'city' => 'Waterbury'],
                ['state_id' => 28, 'city' => 'Fremont'],
                ['state_id' => 28, 'city' => 'Hooper'],
                ['state_id' => 28, 'city' => 'Nickerson'],
                ['state_id' => 28, 'city' => 'Scribner'],
                ['state_id' => 28, 'city' => 'Uehling'],
                ['state_id' => 28, 'city' => 'Winslow'],
                ['state_id' => 28, 'city' => 'Ames'],
                ['state_id' => 28, 'city' => 'Dodge'],
                ['state_id' => 28, 'city' => 'North Bend'],
                ['state_id' => 28, 'city' => 'Snyder'],
                ['state_id' => 28, 'city' => 'Bennington'],
                ['state_id' => 28, 'city' => 'Boys Town'],
                ['state_id' => 28, 'city' => 'Elkhorn'],
                ['state_id' => 28, 'city' => 'Valley'],
                ['state_id' => 28, 'city' => 'Waterloo'],
                ['state_id' => 28, 'city' => 'Omaha'],
                ['state_id' => 28, 'city' => 'Benkelman'],
                ['state_id' => 28, 'city' => 'Haigler'],
                ['state_id' => 28, 'city' => 'Max'],
                ['state_id' => 28, 'city' => 'Parks'],
                ['state_id' => 28, 'city' => 'Exeter'],
                ['state_id' => 28, 'city' => 'Fairmont'],
                ['state_id' => 28, 'city' => 'Geneva'],
                ['state_id' => 28, 'city' => 'Grafton'],
                ['state_id' => 28, 'city' => 'Milligan'],
                ['state_id' => 28, 'city' => 'Ohiowa'],
                ['state_id' => 28, 'city' => 'Shickley'],
                ['state_id' => 28, 'city' => 'Strang'],
                ['state_id' => 28, 'city' => 'Bloomington'],
                ['state_id' => 28, 'city' => 'Campbell'],
                ['state_id' => 28, 'city' => 'Franklin'],
                ['state_id' => 28, 'city' => 'Hildreth'],
                ['state_id' => 28, 'city' => 'Naponee'],
                ['state_id' => 28, 'city' => 'Riverton'],
                ['state_id' => 28, 'city' => 'Upland'],
                ['state_id' => 28, 'city' => 'Curtis'],
                ['state_id' => 28, 'city' => 'Eustis'],
                ['state_id' => 28, 'city' => 'Maywood'],
                ['state_id' => 28, 'city' => 'Moorefield'],
                ['state_id' => 28, 'city' => 'Stockville'],
                ['state_id' => 28, 'city' => 'Arapahoe'],
                ['state_id' => 28, 'city' => 'Beaver City'],
                ['state_id' => 28, 'city' => 'Edison'],
                ['state_id' => 28, 'city' => 'Hendley'],
                ['state_id' => 28, 'city' => 'Holbrook'],
                ['state_id' => 28, 'city' => 'Oxford'],
                ['state_id' => 28, 'city' => 'Cambridge'],
                ['state_id' => 28, 'city' => 'Wilsonville'],
                ['state_id' => 28, 'city' => 'Adams'],
                ['state_id' => 28, 'city' => 'Barneston'],
                ['state_id' => 28, 'city' => 'Beatrice'],
                ['state_id' => 28, 'city' => 'Blue Springs'],
                ['state_id' => 28, 'city' => 'Clatonia'],
                ['state_id' => 28, 'city' => 'Cortland'],
                ['state_id' => 28, 'city' => 'Filley'],
                ['state_id' => 28, 'city' => 'Liberty'],
                ['state_id' => 28, 'city' => 'Odell'],
                ['state_id' => 28, 'city' => 'Pickrell'],
                ['state_id' => 28, 'city' => 'Virginia'],
                ['state_id' => 28, 'city' => 'Wymore'],
                ['state_id' => 28, 'city' => 'Lewellen'],
                ['state_id' => 28, 'city' => 'Lisco'],
                ['state_id' => 28, 'city' => 'Oshkosh'],
                ['state_id' => 28, 'city' => 'Burwell'],
                ['state_id' => 28, 'city' => 'Elwood'],
                ['state_id' => 28, 'city' => 'Smithfield'],
                ['state_id' => 28, 'city' => 'Ashby'],
                ['state_id' => 28, 'city' => 'Hyannis'],
                ['state_id' => 28, 'city' => 'Whitman'],
                ['state_id' => 28, 'city' => 'Spalding'],
                ['state_id' => 28, 'city' => 'Greeley'],
                ['state_id' => 28, 'city' => 'Scotia'],
                ['state_id' => 28, 'city' => 'Wolbach'],
                ['state_id' => 28, 'city' => 'Grand Island'],
                ['state_id' => 28, 'city' => 'Alda'],
                ['state_id' => 28, 'city' => 'Cairo'],
                ['state_id' => 28, 'city' => 'Doniphan'],
                ['state_id' => 28, 'city' => 'Wood River'],
                ['state_id' => 28, 'city' => 'Aurora'],
                ['state_id' => 28, 'city' => 'Giltner'],
                ['state_id' => 28, 'city' => 'Hampton'],
                ['state_id' => 28, 'city' => 'Hordville'],
                ['state_id' => 28, 'city' => 'Marquette'],
                ['state_id' => 28, 'city' => 'Phillips'],
                ['state_id' => 28, 'city' => 'Alma'],
                ['state_id' => 28, 'city' => 'Orleans'],
                ['state_id' => 28, 'city' => 'Ragan'],
                ['state_id' => 28, 'city' => 'Republican City'],
                ['state_id' => 28, 'city' => 'Stamford'],
                ['state_id' => 28, 'city' => 'Hayes Center'],
                ['state_id' => 28, 'city' => 'Culbertson'],
                ['state_id' => 28, 'city' => 'Palisade'],
                ['state_id' => 28, 'city' => 'Stratton'],
                ['state_id' => 28, 'city' => 'Trenton'],
                ['state_id' => 28, 'city' => 'Amelia'],
                ['state_id' => 28, 'city' => 'Atkinson'],
                ['state_id' => 28, 'city' => 'Chambers'],
                ['state_id' => 28, 'city' => 'Emmet'],
                ['state_id' => 28, 'city' => 'Ewing'],
                ['state_id' => 28, 'city' => 'Inman'],
                ['state_id' => 28, 'city' => 'Oneill'],
                ['state_id' => 28, 'city' => 'Page'],
                ['state_id' => 28, 'city' => 'Stuart'],
                ['state_id' => 28, 'city' => 'Mullen'],
                ['state_id' => 28, 'city' => 'Boelus'],
                ['state_id' => 28, 'city' => 'Dannebrog'],
                ['state_id' => 28, 'city' => 'Elba'],
                ['state_id' => 28, 'city' => 'Farwell'],
                ['state_id' => 28, 'city' => 'Saint Libory'],
                ['state_id' => 28, 'city' => 'Saint Paul'],
                ['state_id' => 28, 'city' => 'Daykin'],
                ['state_id' => 28, 'city' => 'Diller'],
                ['state_id' => 28, 'city' => 'Endicott'],
                ['state_id' => 28, 'city' => 'Fairbury'],
                ['state_id' => 28, 'city' => 'Jansen'],
                ['state_id' => 28, 'city' => 'Plymouth'],
                ['state_id' => 28, 'city' => 'Steele City'],
                ['state_id' => 28, 'city' => 'Cook'],
                ['state_id' => 28, 'city' => 'Crab Orchard'],
                ['state_id' => 28, 'city' => 'Elk Creek'],
                ['state_id' => 28, 'city' => 'Sterling'],
                ['state_id' => 28, 'city' => 'Tecumseh'],
                ['state_id' => 28, 'city' => 'Axtell'],
                ['state_id' => 28, 'city' => 'Heartwell'],
                ['state_id' => 28, 'city' => 'Minden'],
                ['state_id' => 28, 'city' => 'Wilcox'],
                ['state_id' => 28, 'city' => 'Brule'],
                ['state_id' => 28, 'city' => 'Keystone'],
                ['state_id' => 28, 'city' => 'Lemoyne'],
                ['state_id' => 28, 'city' => 'Ogallala'],
                ['state_id' => 28, 'city' => 'Paxton'],
                ['state_id' => 28, 'city' => 'Mills'],
                ['state_id' => 28, 'city' => 'Newport'],
                ['state_id' => 28, 'city' => 'Springview'],
                ['state_id' => 28, 'city' => 'Bushnell'],
                ['state_id' => 28, 'city' => 'Dix'],
                ['state_id' => 28, 'city' => 'Kimball'],
                ['state_id' => 28, 'city' => 'Bloomfield'],
                ['state_id' => 28, 'city' => 'Center'],
                ['state_id' => 28, 'city' => 'Creighton'],
                ['state_id' => 28, 'city' => 'Crofton'],
                ['state_id' => 28, 'city' => 'Niobrara'],
                ['state_id' => 28, 'city' => 'Verdigre'],
                ['state_id' => 28, 'city' => 'Wausa'],
                ['state_id' => 28, 'city' => 'Winnetoon'],
                ['state_id' => 28, 'city' => 'Bennet'],
                ['state_id' => 28, 'city' => 'Davey'],
                ['state_id' => 28, 'city' => 'Denton'],
                ['state_id' => 28, 'city' => 'Firth'],
                ['state_id' => 28, 'city' => 'Hallam'],
                ['state_id' => 28, 'city' => 'Hickman'],
                ['state_id' => 28, 'city' => 'Malcolm'],
                ['state_id' => 28, 'city' => 'Martell'],
                ['state_id' => 28, 'city' => 'Panama'],
                ['state_id' => 28, 'city' => 'Raymond'],
                ['state_id' => 28, 'city' => 'Roca'],
                ['state_id' => 28, 'city' => 'Sprague'],
                ['state_id' => 28, 'city' => 'Walton'],
                ['state_id' => 28, 'city' => 'Waverly'],
                ['state_id' => 28, 'city' => 'Lincoln'],
                ['state_id' => 28, 'city' => 'North Platte'],
                ['state_id' => 28, 'city' => 'Brady'],
                ['state_id' => 28, 'city' => 'Dickens'],
                ['state_id' => 28, 'city' => 'Hershey'],
                ['state_id' => 28, 'city' => 'Maxwell'],
                ['state_id' => 28, 'city' => 'Sutherland'],
                ['state_id' => 28, 'city' => 'Wallace'],
                ['state_id' => 28, 'city' => 'Wellfleet'],
                ['state_id' => 28, 'city' => 'Stapleton'],
                ['state_id' => 28, 'city' => 'Taylor'],
                ['state_id' => 28, 'city' => 'Tryon'],
                ['state_id' => 28, 'city' => 'Norfolk'],
                ['state_id' => 28, 'city' => 'Battle Creek'],
                ['state_id' => 28, 'city' => 'Madison'],
                ['state_id' => 28, 'city' => 'Meadow Grove'],
                ['state_id' => 28, 'city' => 'Newman Grove'],
                ['state_id' => 28, 'city' => 'Tilden'],
                ['state_id' => 28, 'city' => 'Clarks'],
                ['state_id' => 28, 'city' => 'Silver Creek'],
                ['state_id' => 28, 'city' => 'Archer'],
                ['state_id' => 28, 'city' => 'Central City'],
                ['state_id' => 28, 'city' => 'Chapman'],
                ['state_id' => 28, 'city' => 'Palmer'],
                ['state_id' => 28, 'city' => 'Broadwater'],
                ['state_id' => 28, 'city' => 'Angora'],
                ['state_id' => 28, 'city' => 'Bayard'],
                ['state_id' => 28, 'city' => 'Bridgeport'],
                ['state_id' => 28, 'city' => 'Belgrade'],
                ['state_id' => 28, 'city' => 'Fullerton'],
                ['state_id' => 28, 'city' => 'Genoa'],
                ['state_id' => 28, 'city' => 'Auburn'],
                ['state_id' => 28, 'city' => 'Brock'],
                ['state_id' => 28, 'city' => 'Brownville'],
                ['state_id' => 28, 'city' => 'Johnson'],
                ['state_id' => 28, 'city' => 'Julian'],
                ['state_id' => 28, 'city' => 'Nemaha'],
                ['state_id' => 28, 'city' => 'Peru'],
                ['state_id' => 28, 'city' => 'Hardy'],
                ['state_id' => 28, 'city' => 'Lawrence'],
                ['state_id' => 28, 'city' => 'Nelson'],
                ['state_id' => 28, 'city' => 'Oak'],
                ['state_id' => 28, 'city' => 'Ruskin'],
                ['state_id' => 28, 'city' => 'Superior'],
                ['state_id' => 28, 'city' => 'Burr'],
                ['state_id' => 28, 'city' => 'Douglas'],
                ['state_id' => 28, 'city' => 'Dunbar'],
                ['state_id' => 28, 'city' => 'Lorton'],
                ['state_id' => 28, 'city' => 'Nebraska City'],
                ['state_id' => 28, 'city' => 'Otoe'],
                ['state_id' => 28, 'city' => 'Palmyra'],
                ['state_id' => 28, 'city' => 'Syracuse'],
                ['state_id' => 28, 'city' => 'Talmage'],
                ['state_id' => 28, 'city' => 'Unadilla'],
                ['state_id' => 28, 'city' => 'Burchard'],
                ['state_id' => 28, 'city' => 'Du Bois'],
                ['state_id' => 28, 'city' => 'Lewiston'],
                ['state_id' => 28, 'city' => 'Pawnee City'],
                ['state_id' => 28, 'city' => 'Steinauer'],
                ['state_id' => 28, 'city' => 'Table Rock'],
                ['state_id' => 28, 'city' => 'Elsie'],
                ['state_id' => 28, 'city' => 'Grant'],
                ['state_id' => 28, 'city' => 'Madrid'],
                ['state_id' => 28, 'city' => 'Venango'],
                ['state_id' => 28, 'city' => 'Atlanta'],
                ['state_id' => 28, 'city' => 'Bertrand'],
                ['state_id' => 28, 'city' => 'Funk'],
                ['state_id' => 28, 'city' => 'Holdrege'],
                ['state_id' => 28, 'city' => 'Loomis'],
                ['state_id' => 28, 'city' => 'Hadar'],
                ['state_id' => 28, 'city' => 'Mclean'],
                ['state_id' => 28, 'city' => 'Osmond'],
                ['state_id' => 28, 'city' => 'Pierce'],
                ['state_id' => 28, 'city' => 'Plainview'],
                ['state_id' => 28, 'city' => 'Columbus'],
                ['state_id' => 28, 'city' => 'Creston'],
                ['state_id' => 28, 'city' => 'Duncan'],
                ['state_id' => 28, 'city' => 'Humphrey'],
                ['state_id' => 28, 'city' => 'Lindsay'],
                ['state_id' => 28, 'city' => 'Monroe'],
                ['state_id' => 28, 'city' => 'Platte Center'],
                ['state_id' => 28, 'city' => 'Osceola'],
                ['state_id' => 28, 'city' => 'Polk'],
                ['state_id' => 28, 'city' => 'Shelby'],
                ['state_id' => 28, 'city' => 'Stromsburg'],
                ['state_id' => 28, 'city' => 'Mc Cook'],
                ['state_id' => 28, 'city' => 'Bartley'],
                ['state_id' => 28, 'city' => 'Danbury'],
                ['state_id' => 28, 'city' => 'Indianola'],
                ['state_id' => 28, 'city' => 'Lebanon'],
                ['state_id' => 28, 'city' => 'Dawson'],
                ['state_id' => 28, 'city' => 'Falls City'],
                ['state_id' => 28, 'city' => 'Humboldt'],
                ['state_id' => 28, 'city' => 'Rulo'],
                ['state_id' => 28, 'city' => 'Salem'],
                ['state_id' => 28, 'city' => 'Shubert'],
                ['state_id' => 28, 'city' => 'Stella'],
                ['state_id' => 28, 'city' => 'Verdon'],
                ['state_id' => 28, 'city' => 'Bassett'],
                ['state_id' => 28, 'city' => 'Crete'],
                ['state_id' => 28, 'city' => 'De Witt'],
                ['state_id' => 28, 'city' => 'Dorchester'],
                ['state_id' => 28, 'city' => 'Friend'],
                ['state_id' => 28, 'city' => 'Swanton'],
                ['state_id' => 28, 'city' => 'Tobias'],
                ['state_id' => 28, 'city' => 'Western'],
                ['state_id' => 28, 'city' => 'Wilber'],
                ['state_id' => 28, 'city' => 'Bellevue'],
                ['state_id' => 28, 'city' => 'Gretna'],
                ['state_id' => 28, 'city' => 'Papillion'],
                ['state_id' => 28, 'city' => 'St Columbans'],
                ['state_id' => 28, 'city' => 'Springfield'],
                ['state_id' => 28, 'city' => 'Offutt Afb'],
                ['state_id' => 28, 'city' => 'La Vista'],
                ['state_id' => 28, 'city' => 'Ashland'],
                ['state_id' => 28, 'city' => 'Cedar Bluffs'],
                ['state_id' => 28, 'city' => 'Ceresco'],
                ['state_id' => 28, 'city' => 'Colon'],
                ['state_id' => 28, 'city' => 'Ithaca'],
                ['state_id' => 28, 'city' => 'Malmo'],
                ['state_id' => 28, 'city' => 'Mead'],
                ['state_id' => 28, 'city' => 'Memphis'],
                ['state_id' => 28, 'city' => 'Prague'],
                ['state_id' => 28, 'city' => 'Valparaiso'],
                ['state_id' => 28, 'city' => 'Wahoo'],
                ['state_id' => 28, 'city' => 'Weston'],
                ['state_id' => 28, 'city' => 'Yutan'],
                ['state_id' => 28, 'city' => 'Morse Bluff'],
                ['state_id' => 28, 'city' => 'Gering'],
                ['state_id' => 28, 'city' => 'Lyman'],
                ['state_id' => 28, 'city' => 'Mcgrew'],
                ['state_id' => 28, 'city' => 'Melbeta'],
                ['state_id' => 28, 'city' => 'Minatare'],
                ['state_id' => 28, 'city' => 'Mitchell'],
                ['state_id' => 28, 'city' => 'Morrill'],
                ['state_id' => 28, 'city' => 'Scottsbluff'],
                ['state_id' => 28, 'city' => 'Beaver Crossing'],
                ['state_id' => 28, 'city' => 'Bee'],
                ['state_id' => 28, 'city' => 'Cordova'],
                ['state_id' => 28, 'city' => 'Garland'],
                ['state_id' => 28, 'city' => 'Goehner'],
                ['state_id' => 28, 'city' => 'Milford'],
                ['state_id' => 28, 'city' => 'Pleasant Dale'],
                ['state_id' => 28, 'city' => 'Seward'],
                ['state_id' => 28, 'city' => 'Staplehurst'],
                ['state_id' => 28, 'city' => 'Utica'],
                ['state_id' => 28, 'city' => 'Bingham'],
                ['state_id' => 28, 'city' => 'Ellsworth'],
                ['state_id' => 28, 'city' => 'Gordon'],
                ['state_id' => 28, 'city' => 'Hay Springs'],
                ['state_id' => 28, 'city' => 'Lakeside'],
                ['state_id' => 28, 'city' => 'Rushville'],
                ['state_id' => 28, 'city' => 'Whiteclay'],
                ['state_id' => 28, 'city' => 'Ashton'],
                ['state_id' => 28, 'city' => 'Hazard'],
                ['state_id' => 28, 'city' => 'Litchfield'],
                ['state_id' => 28, 'city' => 'Loup City'],
                ['state_id' => 28, 'city' => 'Rockville'],
                ['state_id' => 28, 'city' => 'Harrison'],
                ['state_id' => 28, 'city' => 'Pilger'],
                ['state_id' => 28, 'city' => 'Stanton'],
                ['state_id' => 28, 'city' => 'Alexandria'],
                ['state_id' => 28, 'city' => 'Belvidere'],
                ['state_id' => 28, 'city' => 'Bruning'],
                ['state_id' => 28, 'city' => 'Byron'],
                ['state_id' => 28, 'city' => 'Carleton'],
                ['state_id' => 28, 'city' => 'Chester'],
                ['state_id' => 28, 'city' => 'Davenport'],
                ['state_id' => 28, 'city' => 'Deshler'],
                ['state_id' => 28, 'city' => 'Gilead'],
                ['state_id' => 28, 'city' => 'Hebron'],
                ['state_id' => 28, 'city' => 'Hubbell'],
                ['state_id' => 28, 'city' => 'Reynolds'],
                ['state_id' => 28, 'city' => 'Halsey'],
                ['state_id' => 28, 'city' => 'Seneca'],
                ['state_id' => 28, 'city' => 'Thedford'],
                ['state_id' => 28, 'city' => 'Macy'],
                ['state_id' => 28, 'city' => 'Pender'],
                ['state_id' => 28, 'city' => 'Rosalie'],
                ['state_id' => 28, 'city' => 'Thurston'],
                ['state_id' => 28, 'city' => 'Walthill'],
                ['state_id' => 28, 'city' => 'Winnebago'],
                ['state_id' => 28, 'city' => 'Arcadia'],
                ['state_id' => 28, 'city' => 'Elyria'],
                ['state_id' => 28, 'city' => 'North Loup'],
                ['state_id' => 28, 'city' => 'Ord'],
                ['state_id' => 28, 'city' => 'Arlington'],
                ['state_id' => 28, 'city' => 'Blair'],
                ['state_id' => 28, 'city' => 'Fort Calhoun'],
                ['state_id' => 28, 'city' => 'Herman'],
                ['state_id' => 28, 'city' => 'Kennard'],
                ['state_id' => 28, 'city' => 'Washington'],
                ['state_id' => 28, 'city' => 'Carroll'],
                ['state_id' => 28, 'city' => 'Hoskins'],
                ['state_id' => 28, 'city' => 'Wayne'],
                ['state_id' => 28, 'city' => 'Winside'],
                ['state_id' => 28, 'city' => 'Bladen'],
                ['state_id' => 28, 'city' => 'Blue Hill'],
                ['state_id' => 28, 'city' => 'Guide Rock'],
                ['state_id' => 28, 'city' => 'Inavale'],
                ['state_id' => 28, 'city' => 'Red Cloud'],
                ['state_id' => 28, 'city' => 'Bartlett'],
                ['state_id' => 28, 'city' => 'Ericson'],
                ['state_id' => 28, 'city' => 'Benedict'],
                ['state_id' => 28, 'city' => 'Bradshaw'],
                ['state_id' => 28, 'city' => 'Gresham'],
                ['state_id' => 28, 'city' => 'Henderson'],
                ['state_id' => 28, 'city' => 'Mc Cool Junction'],
                ['state_id' => 28, 'city' => 'Waco'],
                ['state_id' => 28, 'city' => 'York']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
