<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State48TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of WA - Washington.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 48, 'city' => 'Benge'],
                ['state_id' => 48, 'city' => 'Ritzville'],
                ['state_id' => 48, 'city' => 'Lind'],
                ['state_id' => 48, 'city' => 'Othello'],
                ['state_id' => 48, 'city' => 'Washtucna'],
                ['state_id' => 48, 'city' => 'Anatone'],
                ['state_id' => 48, 'city' => 'Asotin'],
                ['state_id' => 48, 'city' => 'Clarkston'],
                ['state_id' => 48, 'city' => 'Benton City'],
                ['state_id' => 48, 'city' => 'Kennewick'],
                ['state_id' => 48, 'city' => 'Paterson'],
                ['state_id' => 48, 'city' => 'Plymouth'],
                ['state_id' => 48, 'city' => 'Prosser'],
                ['state_id' => 48, 'city' => 'Richland'],
                ['state_id' => 48, 'city' => 'West Richland'],
                ['state_id' => 48, 'city' => 'Wenatchee'],
                ['state_id' => 48, 'city' => 'Ardenvoir'],
                ['state_id' => 48, 'city' => 'Cashmere'],
                ['state_id' => 48, 'city' => 'Chelan'],
                ['state_id' => 48, 'city' => 'Chelan Falls'],
                ['state_id' => 48, 'city' => 'Dryden'],
                ['state_id' => 48, 'city' => 'Entiat'],
                ['state_id' => 48, 'city' => 'Leavenworth'],
                ['state_id' => 48, 'city' => 'Malaga'],
                ['state_id' => 48, 'city' => 'Manson'],
                ['state_id' => 48, 'city' => 'Monitor'],
                ['state_id' => 48, 'city' => 'Peshastin'],
                ['state_id' => 48, 'city' => 'Stehekin'],
                ['state_id' => 48, 'city' => 'Beaver'],
                ['state_id' => 48, 'city' => 'Carlsborg'],
                ['state_id' => 48, 'city' => 'Clallam Bay'],
                ['state_id' => 48, 'city' => 'Forks'],
                ['state_id' => 48, 'city' => 'Joyce'],
                ['state_id' => 48, 'city' => 'La Push'],
                ['state_id' => 48, 'city' => 'Neah Bay'],
                ['state_id' => 48, 'city' => 'Port Angeles'],
                ['state_id' => 48, 'city' => 'Sekiu'],
                ['state_id' => 48, 'city' => 'Sequim'],
                ['state_id' => 48, 'city' => 'Amboy'],
                ['state_id' => 48, 'city' => 'Battle Ground'],
                ['state_id' => 48, 'city' => 'Brush Prairie'],
                ['state_id' => 48, 'city' => 'Camas'],
                ['state_id' => 48, 'city' => 'Heisson'],
                ['state_id' => 48, 'city' => 'La Center'],
                ['state_id' => 48, 'city' => 'Ridgefield'],
                ['state_id' => 48, 'city' => 'Vancouver'],
                ['state_id' => 48, 'city' => 'Washougal'],
                ['state_id' => 48, 'city' => 'Yacolt'],
                ['state_id' => 48, 'city' => 'Dayton'],
                ['state_id' => 48, 'city' => 'Starbuck'],
                ['state_id' => 48, 'city' => 'Ryderwood'],
                ['state_id' => 48, 'city' => 'Ariel'],
                ['state_id' => 48, 'city' => 'Carrolls'],
                ['state_id' => 48, 'city' => 'Castle Rock'],
                ['state_id' => 48, 'city' => 'Cougar'],
                ['state_id' => 48, 'city' => 'Kalama'],
                ['state_id' => 48, 'city' => 'Kelso'],
                ['state_id' => 48, 'city' => 'Longview'],
                ['state_id' => 48, 'city' => 'Silverlake'],
                ['state_id' => 48, 'city' => 'Toutle'],
                ['state_id' => 48, 'city' => 'Woodland'],
                ['state_id' => 48, 'city' => 'East Wenatchee'],
                ['state_id' => 48, 'city' => 'Bridgeport'],
                ['state_id' => 48, 'city' => 'Mansfield'],
                ['state_id' => 48, 'city' => 'Orondo'],
                ['state_id' => 48, 'city' => 'Palisades'],
                ['state_id' => 48, 'city' => 'Rock Island'],
                ['state_id' => 48, 'city' => 'Waterville'],
                ['state_id' => 48, 'city' => 'Boyds'],
                ['state_id' => 48, 'city' => 'Curlew'],
                ['state_id' => 48, 'city' => 'Danville'],
                ['state_id' => 48, 'city' => 'Inchelium'],
                ['state_id' => 48, 'city' => 'Keller'],
                ['state_id' => 48, 'city' => 'Laurier'],
                ['state_id' => 48, 'city' => 'Malo'],
                ['state_id' => 48, 'city' => 'Orient'],
                ['state_id' => 48, 'city' => 'Republic'],
                ['state_id' => 48, 'city' => 'Pasco'],
                ['state_id' => 48, 'city' => 'Connell'],
                ['state_id' => 48, 'city' => 'Eltopia'],
                ['state_id' => 48, 'city' => 'Kahlotus'],
                ['state_id' => 48, 'city' => 'Mesa'],
                ['state_id' => 48, 'city' => 'Pomeroy'],
                ['state_id' => 48, 'city' => 'Ephrata'],
                ['state_id' => 48, 'city' => 'George'],
                ['state_id' => 48, 'city' => 'Marlin'],
                ['state_id' => 48, 'city' => 'Moses Lake'],
                ['state_id' => 48, 'city' => 'Quincy'],
                ['state_id' => 48, 'city' => 'Soap Lake'],
                ['state_id' => 48, 'city' => 'Stratford'],
                ['state_id' => 48, 'city' => 'Warden'],
                ['state_id' => 48, 'city' => 'Wilson Creek'],
                ['state_id' => 48, 'city' => 'Coulee City'],
                ['state_id' => 48, 'city' => 'Electric City'],
                ['state_id' => 48, 'city' => 'Grand Coulee'],
                ['state_id' => 48, 'city' => 'Hartline'],
                ['state_id' => 48, 'city' => 'Beverly'],
                ['state_id' => 48, 'city' => 'Mattawa'],
                ['state_id' => 48, 'city' => 'Royal City'],
                ['state_id' => 48, 'city' => 'Aberdeen'],
                ['state_id' => 48, 'city' => 'Amanda Park'],
                ['state_id' => 48, 'city' => 'Copalis Beach'],
                ['state_id' => 48, 'city' => 'Copalis Crossing'],
                ['state_id' => 48, 'city' => 'Cosmopolis'],
                ['state_id' => 48, 'city' => 'Elma'],
                ['state_id' => 48, 'city' => 'Grayland'],
                ['state_id' => 48, 'city' => 'Hoquiam'],
                ['state_id' => 48, 'city' => 'Humptulips'],
                ['state_id' => 48, 'city' => 'Mccleary'],
                ['state_id' => 48, 'city' => 'Malone'],
                ['state_id' => 48, 'city' => 'Moclips'],
                ['state_id' => 48, 'city' => 'Montesano'],
                ['state_id' => 48, 'city' => 'Neilton'],
                ['state_id' => 48, 'city' => 'Oakville'],
                ['state_id' => 48, 'city' => 'Ocean Shores'],
                ['state_id' => 48, 'city' => 'Pacific Beach'],
                ['state_id' => 48, 'city' => 'Quinault'],
                ['state_id' => 48, 'city' => 'Satsop'],
                ['state_id' => 48, 'city' => 'Taholah'],
                ['state_id' => 48, 'city' => 'Westport'],
                ['state_id' => 48, 'city' => 'Clinton'],
                ['state_id' => 48, 'city' => 'Coupeville'],
                ['state_id' => 48, 'city' => 'Freeland'],
                ['state_id' => 48, 'city' => 'Greenbank'],
                ['state_id' => 48, 'city' => 'Langley'],
                ['state_id' => 48, 'city' => 'Oak Harbor'],
                ['state_id' => 48, 'city' => 'Brinnon'],
                ['state_id' => 48, 'city' => 'Chimacum'],
                ['state_id' => 48, 'city' => 'Port Hadlock'],
                ['state_id' => 48, 'city' => 'Nordland'],
                ['state_id' => 48, 'city' => 'Port Ludlow'],
                ['state_id' => 48, 'city' => 'Port Townsend'],
                ['state_id' => 48, 'city' => 'Quilcene'],
                ['state_id' => 48, 'city' => 'Auburn'],
                ['state_id' => 48, 'city' => 'Federal Way'],
                ['state_id' => 48, 'city' => 'Bellevue'],
                ['state_id' => 48, 'city' => 'Black Diamond'],
                ['state_id' => 48, 'city' => 'Bothell'],
                ['state_id' => 48, 'city' => 'Burton'],
                ['state_id' => 48, 'city' => 'Carnation'],
                ['state_id' => 48, 'city' => 'Duvall'],
                ['state_id' => 48, 'city' => 'Enumclaw'],
                ['state_id' => 48, 'city' => 'Fall City'],
                ['state_id' => 48, 'city' => 'Hobart'],
                ['state_id' => 48, 'city' => 'Issaquah'],
                ['state_id' => 48, 'city' => 'Kenmore'],
                ['state_id' => 48, 'city' => 'Kent'],
                ['state_id' => 48, 'city' => 'Kirkland'],
                ['state_id' => 48, 'city' => 'Maple Valley'],
                ['state_id' => 48, 'city' => 'Medina'],
                ['state_id' => 48, 'city' => 'Mercer Island'],
                ['state_id' => 48, 'city' => 'North Bend'],
                ['state_id' => 48, 'city' => 'Pacific'],
                ['state_id' => 48, 'city' => 'Preston'],
                ['state_id' => 48, 'city' => 'Ravensdale'],
                ['state_id' => 48, 'city' => 'Redmond'],
                ['state_id' => 48, 'city' => 'Renton'],
                ['state_id' => 48, 'city' => 'Seahurst'],
                ['state_id' => 48, 'city' => 'Snoqualmie'],
                ['state_id' => 48, 'city' => 'Snoqualmie Pass'],
                ['state_id' => 48, 'city' => 'Vashon'],
                ['state_id' => 48, 'city' => 'Woodinville'],
                ['state_id' => 48, 'city' => 'Sammamish'],
                ['state_id' => 48, 'city' => 'Seattle'],
                ['state_id' => 48, 'city' => 'Baring'],
                ['state_id' => 48, 'city' => 'Skykomish'],
                ['state_id' => 48, 'city' => 'Rollingbay'],
                ['state_id' => 48, 'city' => 'Bainbridge Island'],
                ['state_id' => 48, 'city' => 'Bremerton'],
                ['state_id' => 48, 'city' => 'Silverdale'],
                ['state_id' => 48, 'city' => 'Burley'],
                ['state_id' => 48, 'city' => 'Hansville'],
                ['state_id' => 48, 'city' => 'Indianola'],
                ['state_id' => 48, 'city' => 'Keyport'],
                ['state_id' => 48, 'city' => 'Kingston'],
                ['state_id' => 48, 'city' => 'Manchester'],
                ['state_id' => 48, 'city' => 'Olalla'],
                ['state_id' => 48, 'city' => 'Port Gamble'],
                ['state_id' => 48, 'city' => 'Port Orchard'],
                ['state_id' => 48, 'city' => 'Poulsbo'],
                ['state_id' => 48, 'city' => 'Retsil'],
                ['state_id' => 48, 'city' => 'Seabeck'],
                ['state_id' => 48, 'city' => 'South Colby'],
                ['state_id' => 48, 'city' => 'Southworth'],
                ['state_id' => 48, 'city' => 'Suquamish'],
                ['state_id' => 48, 'city' => 'Tracyton'],
                ['state_id' => 48, 'city' => 'Cle Elum'],
                ['state_id' => 48, 'city' => 'Easton'],
                ['state_id' => 48, 'city' => 'Ellensburg'],
                ['state_id' => 48, 'city' => 'Kittitas'],
                ['state_id' => 48, 'city' => 'Ronald'],
                ['state_id' => 48, 'city' => 'Roslyn'],
                ['state_id' => 48, 'city' => 'South Cle Elum'],
                ['state_id' => 48, 'city' => 'Thorp'],
                ['state_id' => 48, 'city' => 'Vantage'],
                ['state_id' => 48, 'city' => 'Appleton'],
                ['state_id' => 48, 'city' => 'Bingen'],
                ['state_id' => 48, 'city' => 'Centerville'],
                ['state_id' => 48, 'city' => 'Dallesport'],
                ['state_id' => 48, 'city' => 'Glenwood'],
                ['state_id' => 48, 'city' => 'Goldendale'],
                ['state_id' => 48, 'city' => 'Husum'],
                ['state_id' => 48, 'city' => 'Klickitat'],
                ['state_id' => 48, 'city' => 'Lyle'],
                ['state_id' => 48, 'city' => 'Trout Lake'],
                ['state_id' => 48, 'city' => 'Wahkiacus'],
                ['state_id' => 48, 'city' => 'White Salmon'],
                ['state_id' => 48, 'city' => 'Wishram'],
                ['state_id' => 48, 'city' => 'Bickleton'],
                ['state_id' => 48, 'city' => 'Roosevelt'],
                ['state_id' => 48, 'city' => 'Glenoma'],
                ['state_id' => 48, 'city' => 'Mineral'],
                ['state_id' => 48, 'city' => 'Morton'],
                ['state_id' => 48, 'city' => 'Packwood'],
                ['state_id' => 48, 'city' => 'Randle'],
                ['state_id' => 48, 'city' => 'Adna'],
                ['state_id' => 48, 'city' => 'Centralia'],
                ['state_id' => 48, 'city' => 'Chehalis'],
                ['state_id' => 48, 'city' => 'Cinebar'],
                ['state_id' => 48, 'city' => 'Curtis'],
                ['state_id' => 48, 'city' => 'Doty'],
                ['state_id' => 48, 'city' => 'Ethel'],
                ['state_id' => 48, 'city' => 'Galvin'],
                ['state_id' => 48, 'city' => 'Mossyrock'],
                ['state_id' => 48, 'city' => 'Napavine'],
                ['state_id' => 48, 'city' => 'Onalaska'],
                ['state_id' => 48, 'city' => 'Pe Ell'],
                ['state_id' => 48, 'city' => 'Salkum'],
                ['state_id' => 48, 'city' => 'Silver Creek'],
                ['state_id' => 48, 'city' => 'Toledo'],
                ['state_id' => 48, 'city' => 'Vader'],
                ['state_id' => 48, 'city' => 'Winlock'],
                ['state_id' => 48, 'city' => 'Edwall'],
                ['state_id' => 48, 'city' => 'Sprague'],
                ['state_id' => 48, 'city' => 'Almira'],
                ['state_id' => 48, 'city' => 'Creston'],
                ['state_id' => 48, 'city' => 'Davenport'],
                ['state_id' => 48, 'city' => 'Harrington'],
                ['state_id' => 48, 'city' => 'Lamona'],
                ['state_id' => 48, 'city' => 'Lincoln'],
                ['state_id' => 48, 'city' => 'Mohler'],
                ['state_id' => 48, 'city' => 'Odessa'],
                ['state_id' => 48, 'city' => 'Wilbur'],
                ['state_id' => 48, 'city' => 'Allyn'],
                ['state_id' => 48, 'city' => 'Belfair'],
                ['state_id' => 48, 'city' => 'Grapeview'],
                ['state_id' => 48, 'city' => 'Hoodsport'],
                ['state_id' => 48, 'city' => 'Lilliwaup'],
                ['state_id' => 48, 'city' => 'Matlock'],
                ['state_id' => 48, 'city' => 'Shelton'],
                ['state_id' => 48, 'city' => 'Tahuya'],
                ['state_id' => 48, 'city' => 'Union'],
                ['state_id' => 48, 'city' => 'Brewster'],
                ['state_id' => 48, 'city' => 'Carlton'],
                ['state_id' => 48, 'city' => 'Conconully'],
                ['state_id' => 48, 'city' => 'Loomis'],
                ['state_id' => 48, 'city' => 'Malott'],
                ['state_id' => 48, 'city' => 'Mazama'],
                ['state_id' => 48, 'city' => 'Methow'],
                ['state_id' => 48, 'city' => 'Okanogan'],
                ['state_id' => 48, 'city' => 'Omak'],
                ['state_id' => 48, 'city' => 'Oroville'],
                ['state_id' => 48, 'city' => 'Pateros'],
                ['state_id' => 48, 'city' => 'Riverside'],
                ['state_id' => 48, 'city' => 'Tonasket'],
                ['state_id' => 48, 'city' => 'Twisp'],
                ['state_id' => 48, 'city' => 'Wauconda'],
                ['state_id' => 48, 'city' => 'Winthrop'],
                ['state_id' => 48, 'city' => 'Coulee Dam'],
                ['state_id' => 48, 'city' => 'Elmer City'],
                ['state_id' => 48, 'city' => 'Nespelem'],
                ['state_id' => 48, 'city' => 'Bay Center'],
                ['state_id' => 48, 'city' => 'Lebam'],
                ['state_id' => 48, 'city' => 'Menlo'],
                ['state_id' => 48, 'city' => 'Raymond'],
                ['state_id' => 48, 'city' => 'South Bend'],
                ['state_id' => 48, 'city' => 'Tokeland'],
                ['state_id' => 48, 'city' => 'Chinook'],
                ['state_id' => 48, 'city' => 'Ilwaco'],
                ['state_id' => 48, 'city' => 'Long Beach'],
                ['state_id' => 48, 'city' => 'Nahcotta'],
                ['state_id' => 48, 'city' => 'Naselle'],
                ['state_id' => 48, 'city' => 'Ocean Park'],
                ['state_id' => 48, 'city' => 'Oysterville'],
                ['state_id' => 48, 'city' => 'Seaview'],
                ['state_id' => 48, 'city' => 'Cusick'],
                ['state_id' => 48, 'city' => 'Ione'],
                ['state_id' => 48, 'city' => 'Metaline'],
                ['state_id' => 48, 'city' => 'Metaline Falls'],
                ['state_id' => 48, 'city' => 'Newport'],
                ['state_id' => 48, 'city' => 'Usk'],
                ['state_id' => 48, 'city' => 'Anderson Island'],
                ['state_id' => 48, 'city' => 'Ashford'],
                ['state_id' => 48, 'city' => 'Buckley'],
                ['state_id' => 48, 'city' => 'Carbonado'],
                ['state_id' => 48, 'city' => 'Dupont'],
                ['state_id' => 48, 'city' => 'Eatonville'],
                ['state_id' => 48, 'city' => 'Gig Harbor'],
                ['state_id' => 48, 'city' => 'Elbe'],
                ['state_id' => 48, 'city' => 'Fox Island'],
                ['state_id' => 48, 'city' => 'Graham'],
                ['state_id' => 48, 'city' => 'Kapowsin'],
                ['state_id' => 48, 'city' => 'La Grande'],
                ['state_id' => 48, 'city' => 'Lakebay'],
                ['state_id' => 48, 'city' => 'Longbranch'],
                ['state_id' => 48, 'city' => 'Sumner'],
                ['state_id' => 48, 'city' => 'Milton'],
                ['state_id' => 48, 'city' => 'Orting'],
                ['state_id' => 48, 'city' => 'Puyallup'],
                ['state_id' => 48, 'city' => 'South Prairie'],
                ['state_id' => 48, 'city' => 'Spanaway'],
                ['state_id' => 48, 'city' => 'Steilacoom'],
                ['state_id' => 48, 'city' => 'Bonney Lake'],
                ['state_id' => 48, 'city' => 'Vaughn'],
                ['state_id' => 48, 'city' => 'Wauna'],
                ['state_id' => 48, 'city' => 'Wilkeson'],
                ['state_id' => 48, 'city' => 'Longmire'],
                ['state_id' => 48, 'city' => 'Paradise Inn'],
                ['state_id' => 48, 'city' => 'Tacoma'],
                ['state_id' => 48, 'city' => 'Camp Murray'],
                ['state_id' => 48, 'city' => 'Mcchord Afb'],
                ['state_id' => 48, 'city' => 'Lakewood'],
                ['state_id' => 48, 'city' => 'University Place'],
                ['state_id' => 48, 'city' => 'Mckenna'],
                ['state_id' => 48, 'city' => 'Roy'],
                ['state_id' => 48, 'city' => 'Blakely Island'],
                ['state_id' => 48, 'city' => 'Deer Harbor'],
                ['state_id' => 48, 'city' => 'Eastsound'],
                ['state_id' => 48, 'city' => 'Friday Harbor'],
                ['state_id' => 48, 'city' => 'Lopez Island'],
                ['state_id' => 48, 'city' => 'Olga'],
                ['state_id' => 48, 'city' => 'Orcas'],
                ['state_id' => 48, 'city' => 'Shaw Island'],
                ['state_id' => 48, 'city' => 'Waldron'],
                ['state_id' => 48, 'city' => 'Anacortes'],
                ['state_id' => 48, 'city' => 'Bow'],
                ['state_id' => 48, 'city' => 'Burlington'],
                ['state_id' => 48, 'city' => 'Clearlake'],
                ['state_id' => 48, 'city' => 'Concrete'],
                ['state_id' => 48, 'city' => 'Conway'],
                ['state_id' => 48, 'city' => 'Hamilton'],
                ['state_id' => 48, 'city' => 'La Conner'],
                ['state_id' => 48, 'city' => 'Lyman'],
                ['state_id' => 48, 'city' => 'Marblemount'],
                ['state_id' => 48, 'city' => 'Mount Vernon'],
                ['state_id' => 48, 'city' => 'Rockport'],
                ['state_id' => 48, 'city' => 'Sedro Woolley'],
                ['state_id' => 48, 'city' => 'Carson'],
                ['state_id' => 48, 'city' => 'North Bonneville'],
                ['state_id' => 48, 'city' => 'Stevenson'],
                ['state_id' => 48, 'city' => 'Underwood'],
                ['state_id' => 48, 'city' => 'Edmonds'],
                ['state_id' => 48, 'city' => 'Lynnwood'],
                ['state_id' => 48, 'city' => 'Mountlake Terrace'],
                ['state_id' => 48, 'city' => 'Mill Creek'],
                ['state_id' => 48, 'city' => 'Everett'],
                ['state_id' => 48, 'city' => 'Arlington'],
                ['state_id' => 48, 'city' => 'Darrington'],
                ['state_id' => 48, 'city' => 'Gold Bar'],
                ['state_id' => 48, 'city' => 'Granite Falls'],
                ['state_id' => 48, 'city' => 'Index'],
                ['state_id' => 48, 'city' => 'Lake Stevens'],
                ['state_id' => 48, 'city' => 'North Lakewood'],
                ['state_id' => 48, 'city' => 'Marysville'],
                ['state_id' => 48, 'city' => 'Monroe'],
                ['state_id' => 48, 'city' => 'Mukilteo'],
                ['state_id' => 48, 'city' => 'Camano Island'],
                ['state_id' => 48, 'city' => 'Silvana'],
                ['state_id' => 48, 'city' => 'Snohomish'],
                ['state_id' => 48, 'city' => 'Stanwood'],
                ['state_id' => 48, 'city' => 'Startup'],
                ['state_id' => 48, 'city' => 'Sultan'],
                ['state_id' => 48, 'city' => 'Airway Heights'],
                ['state_id' => 48, 'city' => 'Chattaroy'],
                ['state_id' => 48, 'city' => 'Cheney'],
                ['state_id' => 48, 'city' => 'Colbert'],
                ['state_id' => 48, 'city' => 'Deer Park'],
                ['state_id' => 48, 'city' => 'Elk'],
                ['state_id' => 48, 'city' => 'Fairchild Air Force Base'],
                ['state_id' => 48, 'city' => 'Fairfield'],
                ['state_id' => 48, 'city' => 'Four Lakes'],
                ['state_id' => 48, 'city' => 'Greenacres'],
                ['state_id' => 48, 'city' => 'Latah'],
                ['state_id' => 48, 'city' => 'Liberty Lake'],
                ['state_id' => 48, 'city' => 'Marshall'],
                ['state_id' => 48, 'city' => 'Mead'],
                ['state_id' => 48, 'city' => 'Medical Lake'],
                ['state_id' => 48, 'city' => 'Mica'],
                ['state_id' => 48, 'city' => 'Newman Lake'],
                ['state_id' => 48, 'city' => 'Nine Mile Falls'],
                ['state_id' => 48, 'city' => 'Otis Orchards'],
                ['state_id' => 48, 'city' => 'Reardan'],
                ['state_id' => 48, 'city' => 'Rockford'],
                ['state_id' => 48, 'city' => 'Spangle'],
                ['state_id' => 48, 'city' => 'Valleyford'],
                ['state_id' => 48, 'city' => 'Veradale'],
                ['state_id' => 48, 'city' => 'Waverly'],
                ['state_id' => 48, 'city' => 'Spokane'],
                ['state_id' => 48, 'city' => 'Ford'],
                ['state_id' => 48, 'city' => 'Tumtum'],
                ['state_id' => 48, 'city' => 'Wellpinit'],
                ['state_id' => 48, 'city' => 'Addy'],
                ['state_id' => 48, 'city' => 'Chewelah'],
                ['state_id' => 48, 'city' => 'Clayton'],
                ['state_id' => 48, 'city' => 'Colville'],
                ['state_id' => 48, 'city' => 'Evans'],
                ['state_id' => 48, 'city' => 'Fruitland'],
                ['state_id' => 48, 'city' => 'Gifford'],
                ['state_id' => 48, 'city' => 'Hunters'],
                ['state_id' => 48, 'city' => 'Kettle Falls'],
                ['state_id' => 48, 'city' => 'Loon Lake'],
                ['state_id' => 48, 'city' => 'Marcus'],
                ['state_id' => 48, 'city' => 'Northport'],
                ['state_id' => 48, 'city' => 'Rice'],
                ['state_id' => 48, 'city' => 'Springdale'],
                ['state_id' => 48, 'city' => 'Valley'],
                ['state_id' => 48, 'city' => 'Olympia'],
                ['state_id' => 48, 'city' => 'Lacey'],
                ['state_id' => 48, 'city' => 'Tumwater'],
                ['state_id' => 48, 'city' => 'Bucoda'],
                ['state_id' => 48, 'city' => 'East Olympia'],
                ['state_id' => 48, 'city' => 'Littlerock'],
                ['state_id' => 48, 'city' => 'Rainier'],
                ['state_id' => 48, 'city' => 'Rochester'],
                ['state_id' => 48, 'city' => 'Tenino'],
                ['state_id' => 48, 'city' => 'Yelm'],
                ['state_id' => 48, 'city' => 'Cathlamet'],
                ['state_id' => 48, 'city' => 'Grays River'],
                ['state_id' => 48, 'city' => 'Rosburg'],
                ['state_id' => 48, 'city' => 'Skamokawa'],
                ['state_id' => 48, 'city' => 'Burbank'],
                ['state_id' => 48, 'city' => 'College Place'],
                ['state_id' => 48, 'city' => 'Dixie'],
                ['state_id' => 48, 'city' => 'Prescott'],
                ['state_id' => 48, 'city' => 'Touchet'],
                ['state_id' => 48, 'city' => 'Waitsburg'],
                ['state_id' => 48, 'city' => 'Walla Walla'],
                ['state_id' => 48, 'city' => 'Wallula'],
                ['state_id' => 48, 'city' => 'Acme'],
                ['state_id' => 48, 'city' => 'Bellingham'],
                ['state_id' => 48, 'city' => 'Blaine'],
                ['state_id' => 48, 'city' => 'Custer'],
                ['state_id' => 48, 'city' => 'Deming'],
                ['state_id' => 48, 'city' => 'Everson'],
                ['state_id' => 48, 'city' => 'Ferndale'],
                ['state_id' => 48, 'city' => 'Lummi Island'],
                ['state_id' => 48, 'city' => 'Lynden'],
                ['state_id' => 48, 'city' => 'Maple Falls'],
                ['state_id' => 48, 'city' => 'Nooksack'],
                ['state_id' => 48, 'city' => 'Point Roberts'],
                ['state_id' => 48, 'city' => 'Sumas'],
                ['state_id' => 48, 'city' => 'Lamont'],
                ['state_id' => 48, 'city' => 'Tekoa'],
                ['state_id' => 48, 'city' => 'Albion'],
                ['state_id' => 48, 'city' => 'Belmont'],
                ['state_id' => 48, 'city' => 'Colfax'],
                ['state_id' => 48, 'city' => 'Colton'],
                ['state_id' => 48, 'city' => 'Endicott'],
                ['state_id' => 48, 'city' => 'Farmington'],
                ['state_id' => 48, 'city' => 'Garfield'],
                ['state_id' => 48, 'city' => 'Hay'],
                ['state_id' => 48, 'city' => 'Lacrosse'],
                ['state_id' => 48, 'city' => 'Malden'],
                ['state_id' => 48, 'city' => 'Oakesdale'],
                ['state_id' => 48, 'city' => 'Palouse'],
                ['state_id' => 48, 'city' => 'Pullman'],
                ['state_id' => 48, 'city' => 'Rosalia'],
                ['state_id' => 48, 'city' => 'Saint John'],
                ['state_id' => 48, 'city' => 'Steptoe'],
                ['state_id' => 48, 'city' => 'Thornton'],
                ['state_id' => 48, 'city' => 'Uniontown'],
                ['state_id' => 48, 'city' => 'Hooper'],
                ['state_id' => 48, 'city' => 'Yakima'],
                ['state_id' => 48, 'city' => 'Brownstown'],
                ['state_id' => 48, 'city' => 'Buena'],
                ['state_id' => 48, 'city' => 'Cowiche'],
                ['state_id' => 48, 'city' => 'Grandview'],
                ['state_id' => 48, 'city' => 'Granger'],
                ['state_id' => 48, 'city' => 'Harrah'],
                ['state_id' => 48, 'city' => 'Mabton'],
                ['state_id' => 48, 'city' => 'Moxee'],
                ['state_id' => 48, 'city' => 'Naches'],
                ['state_id' => 48, 'city' => 'Outlook'],
                ['state_id' => 48, 'city' => 'Parker'],
                ['state_id' => 48, 'city' => 'Selah'],
                ['state_id' => 48, 'city' => 'Sunnyside'],
                ['state_id' => 48, 'city' => 'Tieton'],
                ['state_id' => 48, 'city' => 'Toppenish'],
                ['state_id' => 48, 'city' => 'Wapato'],
                ['state_id' => 48, 'city' => 'White Swan'],
                ['state_id' => 48, 'city' => 'Zillah', 'state_id' => 48]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
