<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State17TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of KS - Kansas.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 17, 'city' => 'Elsmore'],
                ['state_id' => 17, 'city' => 'Gas'],
                ['state_id' => 17, 'city' => 'Humboldt'],
                ['state_id' => 17, 'city' => 'Iola'],
                ['state_id' => 17, 'city' => 'La Harpe'],
                ['state_id' => 17, 'city' => 'Moran'],
                ['state_id' => 17, 'city' => 'Savonburg'],
                ['state_id' => 17, 'city' => 'Colony'],
                ['state_id' => 17, 'city' => 'Garnett'],
                ['state_id' => 17, 'city' => 'Greeley'],
                ['state_id' => 17, 'city' => 'Kincaid'],
                ['state_id' => 17, 'city' => 'Welda'],
                ['state_id' => 17, 'city' => 'Westphalia'],
                ['state_id' => 17, 'city' => 'Atchison'],
                ['state_id' => 17, 'city' => 'Cummings'],
                ['state_id' => 17, 'city' => 'Effingham'],
                ['state_id' => 17, 'city' => 'Lancaster'],
                ['state_id' => 17, 'city' => 'Muscotah'],
                ['state_id' => 17, 'city' => 'Hardtner'],
                ['state_id' => 17, 'city' => 'Hazelton'],
                ['state_id' => 17, 'city' => 'Isabel'],
                ['state_id' => 17, 'city' => 'Kiowa'],
                ['state_id' => 17, 'city' => 'Lake City'],
                ['state_id' => 17, 'city' => 'Medicine Lodge'],
                ['state_id' => 17, 'city' => 'Sharon'],
                ['state_id' => 17, 'city' => 'Sun City'],
                ['state_id' => 17, 'city' => 'Albert'],
                ['state_id' => 17, 'city' => 'Claflin'],
                ['state_id' => 17, 'city' => 'Ellinwood'],
                ['state_id' => 17, 'city' => 'Great Bend'],
                ['state_id' => 17, 'city' => 'Hoisington'],
                ['state_id' => 17, 'city' => 'Olmitz'],
                ['state_id' => 17, 'city' => 'Pawnee Rock'],
                ['state_id' => 17, 'city' => 'Fort Scott'],
                ['state_id' => 17, 'city' => 'Bronson'],
                ['state_id' => 17, 'city' => 'Fulton'],
                ['state_id' => 17, 'city' => 'Garland'],
                ['state_id' => 17, 'city' => 'Mapleton'],
                ['state_id' => 17, 'city' => 'Redfield'],
                ['state_id' => 17, 'city' => 'Uniontown'],
                ['state_id' => 17, 'city' => 'Everest'],
                ['state_id' => 17, 'city' => 'Fairview'],
                ['state_id' => 17, 'city' => 'Hiawatha'],
                ['state_id' => 17, 'city' => 'Horton'],
                ['state_id' => 17, 'city' => 'Morrill'],
                ['state_id' => 17, 'city' => 'Powhattan'],
                ['state_id' => 17, 'city' => 'Robinson'],
                ['state_id' => 17, 'city' => 'Cassoday'],
                ['state_id' => 17, 'city' => 'Andover'],
                ['state_id' => 17, 'city' => 'Augusta'],
                ['state_id' => 17, 'city' => 'Beaumont'],
                ['state_id' => 17, 'city' => 'Benton'],
                ['state_id' => 17, 'city' => 'Douglass'],
                ['state_id' => 17, 'city' => 'Elbing'],
                ['state_id' => 17, 'city' => 'El Dorado'],
                ['state_id' => 17, 'city' => 'Latham'],
                ['state_id' => 17, 'city' => 'Leon'],
                ['state_id' => 17, 'city' => 'Potwin'],
                ['state_id' => 17, 'city' => 'Rosalia'],
                ['state_id' => 17, 'city' => 'Rose Hill'],
                ['state_id' => 17, 'city' => 'Towanda'],
                ['state_id' => 17, 'city' => 'Whitewater'],
                ['state_id' => 17, 'city' => 'Cedar Point'],
                ['state_id' => 17, 'city' => 'Cottonwood Falls'],
                ['state_id' => 17, 'city' => 'Elmdale'],
                ['state_id' => 17, 'city' => 'Matfield Green'],
                ['state_id' => 17, 'city' => 'Strong City'],
                ['state_id' => 17, 'city' => 'Cedar Vale'],
                ['state_id' => 17, 'city' => 'Chautauqua'],
                ['state_id' => 17, 'city' => 'Niotaze'],
                ['state_id' => 17, 'city' => 'Peru'],
                ['state_id' => 17, 'city' => 'Sedan'],
                ['state_id' => 17, 'city' => 'Baxter Springs'],
                ['state_id' => 17, 'city' => 'Columbus'],
                ['state_id' => 17, 'city' => 'Crestline'],
                ['state_id' => 17, 'city' => 'Galena'],
                ['state_id' => 17, 'city' => 'Riverton'],
                ['state_id' => 17, 'city' => 'Scammon'],
                ['state_id' => 17, 'city' => 'Treece'],
                ['state_id' => 17, 'city' => 'Weir'],
                ['state_id' => 17, 'city' => 'West Mineral'],
                ['state_id' => 17, 'city' => 'Bird City'],
                ['state_id' => 17, 'city' => 'Saint Francis'],
                ['state_id' => 17, 'city' => 'Ashland'],
                ['state_id' => 17, 'city' => 'Englewood'],
                ['state_id' => 17, 'city' => 'Minneola'],
                ['state_id' => 17, 'city' => 'Clay Center'],
                ['state_id' => 17, 'city' => 'Green'],
                ['state_id' => 17, 'city' => 'Longford'],
                ['state_id' => 17, 'city' => 'Morganville'],
                ['state_id' => 17, 'city' => 'Wakefield'],
                ['state_id' => 17, 'city' => 'Concordia'],
                ['state_id' => 17, 'city' => 'Clyde'],
                ['state_id' => 17, 'city' => 'Jamestown'],
                ['state_id' => 17, 'city' => 'Aurora'],
                ['state_id' => 17, 'city' => 'Glasco'],
                ['state_id' => 17, 'city' => 'Miltonvale'],
                ['state_id' => 17, 'city' => 'Burlington'],
                ['state_id' => 17, 'city' => 'Gridley'],
                ['state_id' => 17, 'city' => 'Lebo'],
                ['state_id' => 17, 'city' => 'Le Roy'],
                ['state_id' => 17, 'city' => 'Waverly'],
                ['state_id' => 17, 'city' => 'Coldwater'],
                ['state_id' => 17, 'city' => 'Protection'],
                ['state_id' => 17, 'city' => 'Wilmore'],
                ['state_id' => 17, 'city' => 'Arkansas City'],
                ['state_id' => 17, 'city' => 'Atlanta'],
                ['state_id' => 17, 'city' => 'Burden'],
                ['state_id' => 17, 'city' => 'Cambridge'],
                ['state_id' => 17, 'city' => 'Dexter'],
                ['state_id' => 17, 'city' => 'Maple City'],
                ['state_id' => 17, 'city' => 'Rock'],
                ['state_id' => 17, 'city' => 'Udall'],
                ['state_id' => 17, 'city' => 'Winfield'],
                ['state_id' => 17, 'city' => 'Arcadia'],
                ['state_id' => 17, 'city' => 'Arma'],
                ['state_id' => 17, 'city' => 'Cherokee'],
                ['state_id' => 17, 'city' => 'Farlington'],
                ['state_id' => 17, 'city' => 'Franklin'],
                ['state_id' => 17, 'city' => 'Girard'],
                ['state_id' => 17, 'city' => 'Hepler'],
                ['state_id' => 17, 'city' => 'Mc Cune'],
                ['state_id' => 17, 'city' => 'Mulberry'],
                ['state_id' => 17, 'city' => 'Opolis'],
                ['state_id' => 17, 'city' => 'Pittsburg'],
                ['state_id' => 17, 'city' => 'Frontenac'],
                ['state_id' => 17, 'city' => 'Walnut'],
                ['state_id' => 17, 'city' => 'Dresden'],
                ['state_id' => 17, 'city' => 'Jennings'],
                ['state_id' => 17, 'city' => 'Norcatur'],
                ['state_id' => 17, 'city' => 'Oberlin'],
                ['state_id' => 17, 'city' => 'Abilene'],
                ['state_id' => 17, 'city' => 'Chapman'],
                ['state_id' => 17, 'city' => 'Enterprise'],
                ['state_id' => 17, 'city' => 'Herington'],
                ['state_id' => 17, 'city' => 'Hope'],
                ['state_id' => 17, 'city' => 'Solomon'],
                ['state_id' => 17, 'city' => 'Talmage'],
                ['state_id' => 17, 'city' => 'Woodbine'],
                ['state_id' => 17, 'city' => 'Bendena'],
                ['state_id' => 17, 'city' => 'Denton'],
                ['state_id' => 17, 'city' => 'Elwood'],
                ['state_id' => 17, 'city' => 'Highland'],
                ['state_id' => 17, 'city' => 'Troy'],
                ['state_id' => 17, 'city' => 'Wathena'],
                ['state_id' => 17, 'city' => 'White Cloud'],
                ['state_id' => 17, 'city' => 'Baldwin City'],
                ['state_id' => 17, 'city' => 'Eudora'],
                ['state_id' => 17, 'city' => 'Lawrence'],
                ['state_id' => 17, 'city' => 'Lecompton'],
                ['state_id' => 17, 'city' => 'Belpre'],
                ['state_id' => 17, 'city' => 'Kinsley'],
                ['state_id' => 17, 'city' => 'Lewis'],
                ['state_id' => 17, 'city' => 'Offerle'],
                ['state_id' => 17, 'city' => 'Elk Falls'],
                ['state_id' => 17, 'city' => 'Grenola'],
                ['state_id' => 17, 'city' => 'Howard'],
                ['state_id' => 17, 'city' => 'Longton'],
                ['state_id' => 17, 'city' => 'Moline'],
                ['state_id' => 17, 'city' => 'Hays'],
                ['state_id' => 17, 'city' => 'Catharine'],
                ['state_id' => 17, 'city' => 'Ellis'],
                ['state_id' => 17, 'city' => 'Pfeifer'],
                ['state_id' => 17, 'city' => 'Schoenchen'],
                ['state_id' => 17, 'city' => 'Victoria'],
                ['state_id' => 17, 'city' => 'Walker'],
                ['state_id' => 17, 'city' => 'Ellsworth'],
                ['state_id' => 17, 'city' => 'Holyrood'],
                ['state_id' => 17, 'city' => 'Kanopolis'],
                ['state_id' => 17, 'city' => 'Lorraine'],
                ['state_id' => 17, 'city' => 'Wilson'],
                ['state_id' => 17, 'city' => 'Garden City'],
                ['state_id' => 17, 'city' => 'Holcomb'],
                ['state_id' => 17, 'city' => 'Pierceville'],
                ['state_id' => 17, 'city' => 'Dodge City'],
                ['state_id' => 17, 'city' => 'Bucklin'],
                ['state_id' => 17, 'city' => 'Ford'],
                ['state_id' => 17, 'city' => 'Fort Dodge'],
                ['state_id' => 17, 'city' => 'Spearville'],
                ['state_id' => 17, 'city' => 'Wright'],
                ['state_id' => 17, 'city' => 'Lane'],
                ['state_id' => 17, 'city' => 'Ottawa'],
                ['state_id' => 17, 'city' => 'Pomona'],
                ['state_id' => 17, 'city' => 'Princeton'],
                ['state_id' => 17, 'city' => 'Rantoul'],
                ['state_id' => 17, 'city' => 'Richmond'],
                ['state_id' => 17, 'city' => 'Wellsville'],
                ['state_id' => 17, 'city' => 'Williamsburg'],
                ['state_id' => 17, 'city' => 'Junction City'],
                ['state_id' => 17, 'city' => 'Fort Riley'],
                ['state_id' => 17, 'city' => 'Milford'],
                ['state_id' => 17, 'city' => 'Gove'],
                ['state_id' => 17, 'city' => 'Grainfield'],
                ['state_id' => 17, 'city' => 'Grinnell'],
                ['state_id' => 17, 'city' => 'Park'],
                ['state_id' => 17, 'city' => 'Quinter'],
                ['state_id' => 17, 'city' => 'Bogue'],
                ['state_id' => 17, 'city' => 'Hill City'],
                ['state_id' => 17, 'city' => 'Morland'],
                ['state_id' => 17, 'city' => 'Penokee'],
                ['state_id' => 17, 'city' => 'Ulysses'],
                ['state_id' => 17, 'city' => 'Cimarron'],
                ['state_id' => 17, 'city' => 'Copeland'],
                ['state_id' => 17, 'city' => 'Ensign'],
                ['state_id' => 17, 'city' => 'Ingalls'],
                ['state_id' => 17, 'city' => 'Montezuma'],
                ['state_id' => 17, 'city' => 'Tribune'],
                ['state_id' => 17, 'city' => 'Hamilton'],
                ['state_id' => 17, 'city' => 'Lamont'],
                ['state_id' => 17, 'city' => 'Madison'],
                ['state_id' => 17, 'city' => 'Neal'],
                ['state_id' => 17, 'city' => 'Virgil'],
                ['state_id' => 17, 'city' => 'Eureka'],
                ['state_id' => 17, 'city' => 'Fall River'],
                ['state_id' => 17, 'city' => 'Piedmont'],
                ['state_id' => 17, 'city' => 'Severy'],
                ['state_id' => 17, 'city' => 'Coolidge'],
                ['state_id' => 17, 'city' => 'Kendall'],
                ['state_id' => 17, 'city' => 'Syracuse'],
                ['state_id' => 17, 'city' => 'Anthony'],
                ['state_id' => 17, 'city' => 'Attica'],
                ['state_id' => 17, 'city' => 'Bluff City'],
                ['state_id' => 17, 'city' => 'Danville'],
                ['state_id' => 17, 'city' => 'Freeport'],
                ['state_id' => 17, 'city' => 'Harper'],
                ['state_id' => 17, 'city' => 'Waldron'],
                ['state_id' => 17, 'city' => 'Burrton'],
                ['state_id' => 17, 'city' => 'Halstead'],
                ['state_id' => 17, 'city' => 'Hesston'],
                ['state_id' => 17, 'city' => 'Newton'],
                ['state_id' => 17, 'city' => 'North Newton'],
                ['state_id' => 17, 'city' => 'Sedgwick'],
                ['state_id' => 17, 'city' => 'Walton'],
                ['state_id' => 17, 'city' => 'Satanta'],
                ['state_id' => 17, 'city' => 'Sublette'],
                ['state_id' => 17, 'city' => 'Hanston'],
                ['state_id' => 17, 'city' => 'Jetmore'],
                ['state_id' => 17, 'city' => 'Circleville'],
                ['state_id' => 17, 'city' => 'Delia'],
                ['state_id' => 17, 'city' => 'Denison'],
                ['state_id' => 17, 'city' => 'Holton'],
                ['state_id' => 17, 'city' => 'Hoyt'],
                ['state_id' => 17, 'city' => 'Mayetta'],
                ['state_id' => 17, 'city' => 'Netawaka'],
                ['state_id' => 17, 'city' => 'Soldier'],
                ['state_id' => 17, 'city' => 'Whiting'],
                ['state_id' => 17, 'city' => 'Mc Louth'],
                ['state_id' => 17, 'city' => 'Nortonville'],
                ['state_id' => 17, 'city' => 'Oskaloosa'],
                ['state_id' => 17, 'city' => 'Ozawkie'],
                ['state_id' => 17, 'city' => 'Perry'],
                ['state_id' => 17, 'city' => 'Valley Falls'],
                ['state_id' => 17, 'city' => 'Winchester'],
                ['state_id' => 17, 'city' => 'Grantville'],
                ['state_id' => 17, 'city' => 'Meriden'],
                ['state_id' => 17, 'city' => 'Burr Oak'],
                ['state_id' => 17, 'city' => 'Esbon'],
                ['state_id' => 17, 'city' => 'Formoso'],
                ['state_id' => 17, 'city' => 'Jewell'],
                ['state_id' => 17, 'city' => 'Mankato'],
                ['state_id' => 17, 'city' => 'Randall'],
                ['state_id' => 17, 'city' => 'Webber'],
                ['state_id' => 17, 'city' => 'De Soto'],
                ['state_id' => 17, 'city' => 'Edgerton'],
                ['state_id' => 17, 'city' => 'Gardner'],
                ['state_id' => 17, 'city' => 'New Century'],
                ['state_id' => 17, 'city' => 'Olathe'],
                ['state_id' => 17, 'city' => 'Spring Hill'],
                ['state_id' => 17, 'city' => 'Stilwell'],
                ['state_id' => 17, 'city' => 'Mission'],
                ['state_id' => 17, 'city' => 'Shawnee'],
                ['state_id' => 17, 'city' => 'Overland Park'],
                ['state_id' => 17, 'city' => 'Leawood'],
                ['state_id' => 17, 'city' => 'Prairie Village'],
                ['state_id' => 17, 'city' => 'Lenexa'],
                ['state_id' => 17, 'city' => 'Shawnee Mission'],
                ['state_id' => 17, 'city' => 'Deerfield'],
                ['state_id' => 17, 'city' => 'Lakin'],
                ['state_id' => 17, 'city' => 'Cunningham'],
                ['state_id' => 17, 'city' => 'Kingman'],
                ['state_id' => 17, 'city' => 'Murdock'],
                ['state_id' => 17, 'city' => 'Nashville'],
                ['state_id' => 17, 'city' => 'Norwich'],
                ['state_id' => 17, 'city' => 'Spivey'],
                ['state_id' => 17, 'city' => 'Zenda'],
                ['state_id' => 17, 'city' => 'Greensburg'],
                ['state_id' => 17, 'city' => 'Haviland'],
                ['state_id' => 17, 'city' => 'Mullinville'],
                ['state_id' => 17, 'city' => 'Altamont'],
                ['state_id' => 17, 'city' => 'Bartlett'],
                ['state_id' => 17, 'city' => 'Chetopa'],
                ['state_id' => 17, 'city' => 'Dennis'],
                ['state_id' => 17, 'city' => 'Edna'],
                ['state_id' => 17, 'city' => 'Mound Valley'],
                ['state_id' => 17, 'city' => 'Oswego'],
                ['state_id' => 17, 'city' => 'Parsons'],
                ['state_id' => 17, 'city' => 'Dighton'],
                ['state_id' => 17, 'city' => 'Healy'],
                ['state_id' => 17, 'city' => 'Basehor'],
                ['state_id' => 17, 'city' => 'Easton'],
                ['state_id' => 17, 'city' => 'Fort Leavenworth'],
                ['state_id' => 17, 'city' => 'Lansing'],
                ['state_id' => 17, 'city' => 'Leavenworth'],
                ['state_id' => 17, 'city' => 'Linwood'],
                ['state_id' => 17, 'city' => 'Tonganoxie'],
                ['state_id' => 17, 'city' => 'Barnard'],
                ['state_id' => 17, 'city' => 'Beverly'],
                ['state_id' => 17, 'city' => 'Lincoln'],
                ['state_id' => 17, 'city' => 'Sylvan Grove'],
                ['state_id' => 17, 'city' => 'Blue Mound'],
                ['state_id' => 17, 'city' => 'Centerville'],
                ['state_id' => 17, 'city' => 'Lacygne'],
                ['state_id' => 17, 'city' => 'Mound City'],
                ['state_id' => 17, 'city' => 'Parker'],
                ['state_id' => 17, 'city' => 'Pleasanton'],
                ['state_id' => 17, 'city' => 'Prescott'],
                ['state_id' => 17, 'city' => 'Monument'],
                ['state_id' => 17, 'city' => 'Oakley'],
                ['state_id' => 17, 'city' => 'Winona'],
                ['state_id' => 17, 'city' => 'Emporia'],
                ['state_id' => 17, 'city' => 'Admire'],
                ['state_id' => 17, 'city' => 'Allen'],
                ['state_id' => 17, 'city' => 'Americus'],
                ['state_id' => 17, 'city' => 'Hartford'],
                ['state_id' => 17, 'city' => 'Neosho Rapids'],
                ['state_id' => 17, 'city' => 'Olpe'],
                ['state_id' => 17, 'city' => 'Reading'],
                ['state_id' => 17, 'city' => 'Moundridge'],
                ['state_id' => 17, 'city' => 'Canton'],
                ['state_id' => 17, 'city' => 'Galva'],
                ['state_id' => 17, 'city' => 'Lindsborg'],
                ['state_id' => 17, 'city' => 'Mcpherson'],
                ['state_id' => 17, 'city' => 'Marquette'],
                ['state_id' => 17, 'city' => 'Roxbury'],
                ['state_id' => 17, 'city' => 'Windom'],
                ['state_id' => 17, 'city' => 'Inman'],
                ['state_id' => 17, 'city' => 'Burns'],
                ['state_id' => 17, 'city' => 'Florence'],
                ['state_id' => 17, 'city' => 'Lincolnville'],
                ['state_id' => 17, 'city' => 'Lost Springs'],
                ['state_id' => 17, 'city' => 'Marion'],
                ['state_id' => 17, 'city' => 'Peabody'],
                ['state_id' => 17, 'city' => 'Goessel'],
                ['state_id' => 17, 'city' => 'Hillsboro'],
                ['state_id' => 17, 'city' => 'Lehigh'],
                ['state_id' => 17, 'city' => 'Durham'],
                ['state_id' => 17, 'city' => 'Ramona'],
                ['state_id' => 17, 'city' => 'Tampa'],
                ['state_id' => 17, 'city' => 'Axtell'],
                ['state_id' => 17, 'city' => 'Beattie'],
                ['state_id' => 17, 'city' => 'Blue Rapids'],
                ['state_id' => 17, 'city' => 'Bremen'],
                ['state_id' => 17, 'city' => 'Frankfort'],
                ['state_id' => 17, 'city' => 'Home'],
                ['state_id' => 17, 'city' => 'Marysville'],
                ['state_id' => 17, 'city' => 'Oketo'],
                ['state_id' => 17, 'city' => 'Summerfield'],
                ['state_id' => 17, 'city' => 'Vermillion'],
                ['state_id' => 17, 'city' => 'Waterville'],
                ['state_id' => 17, 'city' => 'Fowler'],
                ['state_id' => 17, 'city' => 'Meade'],
                ['state_id' => 17, 'city' => 'Plains'],
                ['state_id' => 17, 'city' => 'Bucyrus'],
                ['state_id' => 17, 'city' => 'Fontana'],
                ['state_id' => 17, 'city' => 'Hillsdale'],
                ['state_id' => 17, 'city' => 'Louisburg'],
                ['state_id' => 17, 'city' => 'Osawatomie'],
                ['state_id' => 17, 'city' => 'Paola'],
                ['state_id' => 17, 'city' => 'Beloit'],
                ['state_id' => 17, 'city' => 'Cawker City'],
                ['state_id' => 17, 'city' => 'Glen Elder'],
                ['state_id' => 17, 'city' => 'Hunter'],
                ['state_id' => 17, 'city' => 'Simpson'],
                ['state_id' => 17, 'city' => 'Tipton'],
                ['state_id' => 17, 'city' => 'Independence'],
                ['state_id' => 17, 'city' => 'Caney'],
                ['state_id' => 17, 'city' => 'Cherryvale'],
                ['state_id' => 17, 'city' => 'Coffeyville'],
                ['state_id' => 17, 'city' => 'Dearing'],
                ['state_id' => 17, 'city' => 'Elk City'],
                ['state_id' => 17, 'city' => 'Havana'],
                ['state_id' => 17, 'city' => 'Liberty'],
                ['state_id' => 17, 'city' => 'Sycamore'],
                ['state_id' => 17, 'city' => 'Tyro'],
                ['state_id' => 17, 'city' => 'Burdick'],
                ['state_id' => 17, 'city' => 'Council Grove'],
                ['state_id' => 17, 'city' => 'Dwight'],
                ['state_id' => 17, 'city' => 'White City'],
                ['state_id' => 17, 'city' => 'Wilsey'],
                ['state_id' => 17, 'city' => 'Elkhart'],
                ['state_id' => 17, 'city' => 'Richfield'],
                ['state_id' => 17, 'city' => 'Rolla'],
                ['state_id' => 17, 'city' => 'Baileyville'],
                ['state_id' => 17, 'city' => 'Bern'],
                ['state_id' => 17, 'city' => 'Centralia'],
                ['state_id' => 17, 'city' => 'Corning'],
                ['state_id' => 17, 'city' => 'Goff'],
                ['state_id' => 17, 'city' => 'Oneida'],
                ['state_id' => 17, 'city' => 'Sabetha'],
                ['state_id' => 17, 'city' => 'Seneca'],
                ['state_id' => 17, 'city' => 'Wetmore'],
                ['state_id' => 17, 'city' => 'Chanute'],
                ['state_id' => 17, 'city' => 'Erie'],
                ['state_id' => 17, 'city' => 'Galesburg'],
                ['state_id' => 17, 'city' => 'Saint Paul'],
                ['state_id' => 17, 'city' => 'Stark'],
                ['state_id' => 17, 'city' => 'Thayer'],
                ['state_id' => 17, 'city' => 'Arnold'],
                ['state_id' => 17, 'city' => 'Bazine'],
                ['state_id' => 17, 'city' => 'Beeler'],
                ['state_id' => 17, 'city' => 'Brownell'],
                ['state_id' => 17, 'city' => 'Ness City'],
                ['state_id' => 17, 'city' => 'Ransom'],
                ['state_id' => 17, 'city' => 'Utica'],
                ['state_id' => 17, 'city' => 'Almena'],
                ['state_id' => 17, 'city' => 'Clayton'],
                ['state_id' => 17, 'city' => 'Lenora'],
                ['state_id' => 17, 'city' => 'Norton'],
                ['state_id' => 17, 'city' => 'Burlingame'],
                ['state_id' => 17, 'city' => 'Carbondale'],
                ['state_id' => 17, 'city' => 'Lyndon'],
                ['state_id' => 17, 'city' => 'Melvern'],
                ['state_id' => 17, 'city' => 'Osage City'],
                ['state_id' => 17, 'city' => 'Overbrook'],
                ['state_id' => 17, 'city' => 'Quenemo'],
                ['state_id' => 17, 'city' => 'Scranton'],
                ['state_id' => 17, 'city' => 'Vassar'],
                ['state_id' => 17, 'city' => 'Downs'],
                ['state_id' => 17, 'city' => 'Osborne'],
                ['state_id' => 17, 'city' => 'Portis'],
                ['state_id' => 17, 'city' => 'Alton'],
                ['state_id' => 17, 'city' => 'Natoma'],
                ['state_id' => 17, 'city' => 'Bennington'],
                ['state_id' => 17, 'city' => 'Delphos'],
                ['state_id' => 17, 'city' => 'Minneapolis'],
                ['state_id' => 17, 'city' => 'Tescott'],
                ['state_id' => 17, 'city' => 'Burdett'],
                ['state_id' => 17, 'city' => 'Garfield'],
                ['state_id' => 17, 'city' => 'Larned'],
                ['state_id' => 17, 'city' => 'Rozel'],
                ['state_id' => 17, 'city' => 'Agra'],
                ['state_id' => 17, 'city' => 'Glade'],
                ['state_id' => 17, 'city' => 'Kirwin'],
                ['state_id' => 17, 'city' => 'Logan'],
                ['state_id' => 17, 'city' => 'Long Island'],
                ['state_id' => 17, 'city' => 'Phillipsburg'],
                ['state_id' => 17, 'city' => 'Prairie View'],
                ['state_id' => 17, 'city' => 'Belvue'],
                ['state_id' => 17, 'city' => 'Emmett'],
                ['state_id' => 17, 'city' => 'Fostoria'],
                ['state_id' => 17, 'city' => 'Havensville'],
                ['state_id' => 17, 'city' => 'Olsburg'],
                ['state_id' => 17, 'city' => 'Onaga'],
                ['state_id' => 17, 'city' => 'Saint George'],
                ['state_id' => 17, 'city' => 'Saint Marys'],
                ['state_id' => 17, 'city' => 'Wamego'],
                ['state_id' => 17, 'city' => 'Westmoreland'],
                ['state_id' => 17, 'city' => 'Byers'],
                ['state_id' => 17, 'city' => 'Coats'],
                ['state_id' => 17, 'city' => 'Iuka'],
                ['state_id' => 17, 'city' => 'Pratt'],
                ['state_id' => 17, 'city' => 'Sawyer'],
                ['state_id' => 17, 'city' => 'Atwood'],
                ['state_id' => 17, 'city' => 'Herndon'],
                ['state_id' => 17, 'city' => 'Ludell'],
                ['state_id' => 17, 'city' => 'Mc Donald'],
                ['state_id' => 17, 'city' => 'Hutchinson'],
                ['state_id' => 17, 'city' => 'South Hutchinson'],
                ['state_id' => 17, 'city' => 'Abbyville'],
                ['state_id' => 17, 'city' => 'Arlington'],
                ['state_id' => 17, 'city' => 'Buhler'],
                ['state_id' => 17, 'city' => 'Haven'],
                ['state_id' => 17, 'city' => 'Nickerson'],
                ['state_id' => 17, 'city' => 'Partridge'],
                ['state_id' => 17, 'city' => 'Plevna'],
                ['state_id' => 17, 'city' => 'Pretty Prairie'],
                ['state_id' => 17, 'city' => 'Sylvia'],
                ['state_id' => 17, 'city' => 'Turon'],
                ['state_id' => 17, 'city' => 'Yoder'],
                ['state_id' => 17, 'city' => 'Agenda'],
                ['state_id' => 17, 'city' => 'Belleville'],
                ['state_id' => 17, 'city' => 'Courtland'],
                ['state_id' => 17, 'city' => 'Cuba'],
                ['state_id' => 17, 'city' => 'Munden'],
                ['state_id' => 17, 'city' => 'Narka'],
                ['state_id' => 17, 'city' => 'Norway'],
                ['state_id' => 17, 'city' => 'Republic'],
                ['state_id' => 17, 'city' => 'Scandia'],
                ['state_id' => 17, 'city' => 'Bushton'],
                ['state_id' => 17, 'city' => 'Geneseo'],
                ['state_id' => 17, 'city' => 'Little River'],
                ['state_id' => 17, 'city' => 'Alden'],
                ['state_id' => 17, 'city' => 'Chase'],
                ['state_id' => 17, 'city' => 'Lyons'],
                ['state_id' => 17, 'city' => 'Raymond'],
                ['state_id' => 17, 'city' => 'Sterling'],
                ['state_id' => 17, 'city' => 'Leonardville'],
                ['state_id' => 17, 'city' => 'Manhattan'],
                ['state_id' => 17, 'city' => 'Ogden'],
                ['state_id' => 17, 'city' => 'Riley'],
                ['state_id' => 17, 'city' => 'Randolph'],
                ['state_id' => 17, 'city' => 'Damar'],
                ['state_id' => 17, 'city' => 'Palco'],
                ['state_id' => 17, 'city' => 'Plainville'],
                ['state_id' => 17, 'city' => 'Stockton'],
                ['state_id' => 17, 'city' => 'Woodston'],
                ['state_id' => 17, 'city' => 'Alexander'],
                ['state_id' => 17, 'city' => 'Bison'],
                ['state_id' => 17, 'city' => 'La Crosse'],
                ['state_id' => 17, 'city' => 'Liebenthal'],
                ['state_id' => 17, 'city' => 'Mc Cracken'],
                ['state_id' => 17, 'city' => 'Nekoma'],
                ['state_id' => 17, 'city' => 'Otis'],
                ['state_id' => 17, 'city' => 'Rush Center'],
                ['state_id' => 17, 'city' => 'Bunker Hill'],
                ['state_id' => 17, 'city' => 'Dorrance'],
                ['state_id' => 17, 'city' => 'Gorham'],
                ['state_id' => 17, 'city' => 'Lucas'],
                ['state_id' => 17, 'city' => 'Luray'],
                ['state_id' => 17, 'city' => 'Paradise'],
                ['state_id' => 17, 'city' => 'Russell'],
                ['state_id' => 17, 'city' => 'Waldo'],
                ['state_id' => 17, 'city' => 'Salina'],
                ['state_id' => 17, 'city' => 'Assaria'],
                ['state_id' => 17, 'city' => 'Brookville'],
                ['state_id' => 17, 'city' => 'Falun'],
                ['state_id' => 17, 'city' => 'Gypsum'],
                ['state_id' => 17, 'city' => 'New Cambria'],
                ['state_id' => 17, 'city' => 'Scott City'],
                ['state_id' => 17, 'city' => 'Andale'],
                ['state_id' => 17, 'city' => 'Bentley'],
                ['state_id' => 17, 'city' => 'Cheney'],
                ['state_id' => 17, 'city' => 'Clearwater'],
                ['state_id' => 17, 'city' => 'Colwich'],
                ['state_id' => 17, 'city' => 'Derby'],
                ['state_id' => 17, 'city' => 'Garden Plain'],
                ['state_id' => 17, 'city' => 'Goddard'],
                ['state_id' => 17, 'city' => 'Greenwich'],
                ['state_id' => 17, 'city' => 'Haysville'],
                ['state_id' => 17, 'city' => 'Kechi'],
                ['state_id' => 17, 'city' => 'Maize'],
                ['state_id' => 17, 'city' => 'Mount Hope'],
                ['state_id' => 17, 'city' => 'Peck'],
                ['state_id' => 17, 'city' => 'Valley Center'],
                ['state_id' => 17, 'city' => 'Viola'],
                ['state_id' => 17, 'city' => 'Wichita'],
                ['state_id' => 17, 'city' => 'Mcconnell Afb'],
                ['state_id' => 17, 'city' => 'Kismet'],
                ['state_id' => 17, 'city' => 'Liberal'],
                ['state_id' => 17, 'city' => 'Auburn'],
                ['state_id' => 17, 'city' => 'Berryton'],
                ['state_id' => 17, 'city' => 'Dover'],
                ['state_id' => 17, 'city' => 'Rossville'],
                ['state_id' => 17, 'city' => 'Silver Lake'],
                ['state_id' => 17, 'city' => 'Tecumseh'],
                ['state_id' => 17, 'city' => 'Wakarusa'],
                ['state_id' => 17, 'city' => 'Topeka'],
                ['state_id' => 17, 'city' => 'Hoxie'],
                ['state_id' => 17, 'city' => 'Selden'],
                ['state_id' => 17, 'city' => 'Edson'],
                ['state_id' => 17, 'city' => 'Goodland'],
                ['state_id' => 17, 'city' => 'Kanorado'],
                ['state_id' => 17, 'city' => 'Athol'],
                ['state_id' => 17, 'city' => 'Kensington'],
                ['state_id' => 17, 'city' => 'Lebanon'],
                ['state_id' => 17, 'city' => 'Smith Center'],
                ['state_id' => 17, 'city' => 'Cedar'],
                ['state_id' => 17, 'city' => 'Gaylord'],
                ['state_id' => 17, 'city' => 'Hudson'],
                ['state_id' => 17, 'city' => 'Macksville'],
                ['state_id' => 17, 'city' => 'St John'],
                ['state_id' => 17, 'city' => 'Stafford'],
                ['state_id' => 17, 'city' => 'Johnson'],
                ['state_id' => 17, 'city' => 'Manter'],
                ['state_id' => 17, 'city' => 'Hugoton'],
                ['state_id' => 17, 'city' => 'Moscow'],
                ['state_id' => 17, 'city' => 'Argonia'],
                ['state_id' => 17, 'city' => 'Belle Plaine'],
                ['state_id' => 17, 'city' => 'Caldwell'],
                ['state_id' => 17, 'city' => 'Conway Springs'],
                ['state_id' => 17, 'city' => 'Geuda Springs'],
                ['state_id' => 17, 'city' => 'Mayfield'],
                ['state_id' => 17, 'city' => 'Milan'],
                ['state_id' => 17, 'city' => 'Milton'],
                ['state_id' => 17, 'city' => 'Mulvane'],
                ['state_id' => 17, 'city' => 'Oxford'],
                ['state_id' => 17, 'city' => 'South Haven'],
                ['state_id' => 17, 'city' => 'Wellington'],
                ['state_id' => 17, 'city' => 'Colby'],
                ['state_id' => 17, 'city' => 'Brewster'],
                ['state_id' => 17, 'city' => 'Gem'],
                ['state_id' => 17, 'city' => 'Levant'],
                ['state_id' => 17, 'city' => 'Rexford'],
                ['state_id' => 17, 'city' => 'Collyer'],
                ['state_id' => 17, 'city' => 'Ogallah'],
                ['state_id' => 17, 'city' => 'Wakeeney'],
                ['state_id' => 17, 'city' => 'Alma'],
                ['state_id' => 17, 'city' => 'Eskridge'],
                ['state_id' => 17, 'city' => 'Harveyville'],
                ['state_id' => 17, 'city' => 'Mc Farland'],
                ['state_id' => 17, 'city' => 'Maple Hill'],
                ['state_id' => 17, 'city' => 'Paxico'],
                ['state_id' => 17, 'city' => 'Alta Vista'],
                ['state_id' => 17, 'city' => 'Sharon Springs'],
                ['state_id' => 17, 'city' => 'Wallace'],
                ['state_id' => 17, 'city' => 'Weskan'],
                ['state_id' => 17, 'city' => 'Barnes'],
                ['state_id' => 17, 'city' => 'Clifton'],
                ['state_id' => 17, 'city' => 'Greenleaf'],
                ['state_id' => 17, 'city' => 'Haddam'],
                ['state_id' => 17, 'city' => 'Hanover'],
                ['state_id' => 17, 'city' => 'Hollenberg'],
                ['state_id' => 17, 'city' => 'Linn'],
                ['state_id' => 17, 'city' => 'Mahaska'],
                ['state_id' => 17, 'city' => 'Morrowville'],
                ['state_id' => 17, 'city' => 'Palmer'],
                ['state_id' => 17, 'city' => 'Washington'],
                ['state_id' => 17, 'city' => 'Leoti'],
                ['state_id' => 17, 'city' => 'Marienthal'],
                ['state_id' => 17, 'city' => 'Altoona'],
                ['state_id' => 17, 'city' => 'Benedict'],
                ['state_id' => 17, 'city' => 'Buffalo'],
                ['state_id' => 17, 'city' => 'Fredonia'],
                ['state_id' => 17, 'city' => 'Neodesha'],
                ['state_id' => 17, 'city' => 'New Albany'],
                ['state_id' => 17, 'city' => 'Neosho Falls'],
                ['state_id' => 17, 'city' => 'Piqua'],
                ['state_id' => 17, 'city' => 'Toronto'],
                ['state_id' => 17, 'city' => 'Yates Center'],
                ['state_id' => 17, 'city' => 'Bonner Springs'],
                ['state_id' => 17, 'city' => 'Kansas City'],
                ['state_id' => 17, 'city' => 'Edwardsville']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
