<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State23TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MI - Michigan.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 23, 'city' => 'Barton City'],
                ['state_id' => 23, 'city' => 'Black River'],
                ['state_id' => 23, 'city' => 'Curran'],
                ['state_id' => 23, 'city' => 'Glennie'],
                ['state_id' => 23, 'city' => 'Greenbush'],
                ['state_id' => 23, 'city' => 'Harrisville'],
                ['state_id' => 23, 'city' => 'Lincoln'],
                ['state_id' => 23, 'city' => 'Mikado'],
                ['state_id' => 23, 'city' => 'Spruce'],
                ['state_id' => 23, 'city' => 'Au Train'],
                ['state_id' => 23, 'city' => 'Chatham'],
                ['state_id' => 23, 'city' => 'Deerton'],
                ['state_id' => 23, 'city' => 'Eben Junction'],
                ['state_id' => 23, 'city' => 'Rumely'],
                ['state_id' => 23, 'city' => 'Grand Marais'],
                ['state_id' => 23, 'city' => 'Munising'],
                ['state_id' => 23, 'city' => 'Shingleton'],
                ['state_id' => 23, 'city' => 'Trenary'],
                ['state_id' => 23, 'city' => 'Wetmore'],
                ['state_id' => 23, 'city' => 'Allegan'],
                ['state_id' => 23, 'city' => 'Martin'],
                ['state_id' => 23, 'city' => 'Otsego'],
                ['state_id' => 23, 'city' => 'Plainwell'],
                ['state_id' => 23, 'city' => 'Bradley'],
                ['state_id' => 23, 'city' => 'Burnips'],
                ['state_id' => 23, 'city' => 'Dorr'],
                ['state_id' => 23, 'city' => 'Hopkins'],
                ['state_id' => 23, 'city' => 'Moline'],
                ['state_id' => 23, 'city' => 'Shelbyville'],
                ['state_id' => 23, 'city' => 'Wayland'],
                ['state_id' => 23, 'city' => 'Douglas'],
                ['state_id' => 23, 'city' => 'Fennville'],
                ['state_id' => 23, 'city' => 'Glenn'],
                ['state_id' => 23, 'city' => 'Hamilton'],
                ['state_id' => 23, 'city' => 'Pullman'],
                ['state_id' => 23, 'city' => 'Saugatuck'],
                ['state_id' => 23, 'city' => 'Alpena'],
                ['state_id' => 23, 'city' => 'Herron'],
                ['state_id' => 23, 'city' => 'Hubbard Lake'],
                ['state_id' => 23, 'city' => 'Lachine'],
                ['state_id' => 23, 'city' => 'Ossineke'],
                ['state_id' => 23, 'city' => 'Alba'],
                ['state_id' => 23, 'city' => 'Alden'],
                ['state_id' => 23, 'city' => 'Bellaire'],
                ['state_id' => 23, 'city' => 'Central Lake'],
                ['state_id' => 23, 'city' => 'Eastport'],
                ['state_id' => 23, 'city' => 'Elk Rapids'],
                ['state_id' => 23, 'city' => 'Kewadin'],
                ['state_id' => 23, 'city' => 'Mancelona'],
                ['state_id' => 23, 'city' => 'Ellsworth'],
                ['state_id' => 23, 'city' => 'Standish'],
                ['state_id' => 23, 'city' => 'Sterling'],
                ['state_id' => 23, 'city' => 'Au Gres'],
                ['state_id' => 23, 'city' => 'Omer'],
                ['state_id' => 23, 'city' => 'Turner'],
                ['state_id' => 23, 'city' => 'Twining'],
                ['state_id' => 23, 'city' => 'Baraga'],
                ['state_id' => 23, 'city' => 'Covington'],
                ['state_id' => 23, 'city' => 'Lanse'],
                ['state_id' => 23, 'city' => 'Skanee'],
                ['state_id' => 23, 'city' => 'Watton'],
                ['state_id' => 23, 'city' => 'Woodland'],
                ['state_id' => 23, 'city' => 'Cloverdale'],
                ['state_id' => 23, 'city' => 'Delton'],
                ['state_id' => 23, 'city' => 'Dowling'],
                ['state_id' => 23, 'city' => 'Hastings'],
                ['state_id' => 23, 'city' => 'Hickory Corners'],
                ['state_id' => 23, 'city' => 'Nashville'],
                ['state_id' => 23, 'city' => 'Freeport'],
                ['state_id' => 23, 'city' => 'Middleville'],
                ['state_id' => 23, 'city' => 'Auburn'],
                ['state_id' => 23, 'city' => 'Bentley'],
                ['state_id' => 23, 'city' => 'Kawkawlin'],
                ['state_id' => 23, 'city' => 'Linwood'],
                ['state_id' => 23, 'city' => 'Pinconning'],
                ['state_id' => 23, 'city' => 'Bay City'],
                ['state_id' => 23, 'city' => 'University Center'],
                ['state_id' => 23, 'city' => 'Essexville'],
                ['state_id' => 23, 'city' => 'Munger'],
                ['state_id' => 23, 'city' => 'Benzonia'],
                ['state_id' => 23, 'city' => 'Beulah'],
                ['state_id' => 23, 'city' => 'Elberta'],
                ['state_id' => 23, 'city' => 'Frankfort'],
                ['state_id' => 23, 'city' => 'Honor'],
                ['state_id' => 23, 'city' => 'Lake Ann'],
                ['state_id' => 23, 'city' => 'Thompsonville'],
                ['state_id' => 23, 'city' => 'Benton Harbor'],
                ['state_id' => 23, 'city' => 'Coloma'],
                ['state_id' => 23, 'city' => 'Hagar Shores'],
                ['state_id' => 23, 'city' => 'Riverside'],
                ['state_id' => 23, 'city' => 'Saint Joseph'],
                ['state_id' => 23, 'city' => 'Watervliet'],
                ['state_id' => 23, 'city' => 'Baroda'],
                ['state_id' => 23, 'city' => 'Berrien Center'],
                ['state_id' => 23, 'city' => 'Berrien Springs'],
                ['state_id' => 23, 'city' => 'Bridgman'],
                ['state_id' => 23, 'city' => 'Buchanan'],
                ['state_id' => 23, 'city' => 'Eau Claire'],
                ['state_id' => 23, 'city' => 'Galien'],
                ['state_id' => 23, 'city' => 'Harbert'],
                ['state_id' => 23, 'city' => 'Lakeside'],
                ['state_id' => 23, 'city' => 'New Buffalo'],
                ['state_id' => 23, 'city' => 'New Troy'],
                ['state_id' => 23, 'city' => 'Niles'],
                ['state_id' => 23, 'city' => 'Sawyer'],
                ['state_id' => 23, 'city' => 'Sodus'],
                ['state_id' => 23, 'city' => 'Stevensville'],
                ['state_id' => 23, 'city' => 'Three Oaks'],
                ['state_id' => 23, 'city' => 'Union Pier'],
                ['state_id' => 23, 'city' => 'Bronson'],
                ['state_id' => 23, 'city' => 'Coldwater'],
                ['state_id' => 23, 'city' => 'Quincy'],
                ['state_id' => 23, 'city' => 'Sherwood'],
                ['state_id' => 23, 'city' => 'Union City'],
                ['state_id' => 23, 'city' => 'Montgomery'],
                ['state_id' => 23, 'city' => 'Athens'],
                ['state_id' => 23, 'city' => 'Battle Creek'],
                ['state_id' => 23, 'city' => 'Bedford'],
                ['state_id' => 23, 'city' => 'Burlington'],
                ['state_id' => 23, 'city' => 'Ceresco'],
                ['state_id' => 23, 'city' => 'East Leroy'],
                ['state_id' => 23, 'city' => 'Marshall'],
                ['state_id' => 23, 'city' => 'Tekonsha'],
                ['state_id' => 23, 'city' => 'Albion'],
                ['state_id' => 23, 'city' => 'Homer'],
                ['state_id' => 23, 'city' => 'Cassopolis'],
                ['state_id' => 23, 'city' => 'Dowagiac'],
                ['state_id' => 23, 'city' => 'Jones'],
                ['state_id' => 23, 'city' => 'Marcellus'],
                ['state_id' => 23, 'city' => 'Vandalia'],
                ['state_id' => 23, 'city' => 'Edwardsburg'],
                ['state_id' => 23, 'city' => 'Union'],
                ['state_id' => 23, 'city' => 'Bay Shore'],
                ['state_id' => 23, 'city' => 'Boyne City'],
                ['state_id' => 23, 'city' => 'Boyne Falls'],
                ['state_id' => 23, 'city' => 'Charlevoix'],
                ['state_id' => 23, 'city' => 'East Jordan'],
                ['state_id' => 23, 'city' => 'Beaver Island'],
                ['state_id' => 23, 'city' => 'Walloon Lake'],
                ['state_id' => 23, 'city' => 'Mackinaw City'],
                ['state_id' => 23, 'city' => 'Afton'],
                ['state_id' => 23, 'city' => 'Brutus'],
                ['state_id' => 23, 'city' => 'Burt Lake'],
                ['state_id' => 23, 'city' => 'Cheboygan'],
                ['state_id' => 23, 'city' => 'Indian River'],
                ['state_id' => 23, 'city' => 'Mullett Lake'],
                ['state_id' => 23, 'city' => 'Topinabee'],
                ['state_id' => 23, 'city' => 'Tower'],
                ['state_id' => 23, 'city' => 'Wolverine'],
                ['state_id' => 23, 'city' => 'Barbeau'],
                ['state_id' => 23, 'city' => 'Brimley'],
                ['state_id' => 23, 'city' => 'Dafter'],
                ['state_id' => 23, 'city' => 'De Tour Village'],
                ['state_id' => 23, 'city' => 'Drummond Island'],
                ['state_id' => 23, 'city' => 'Eckerman'],
                ['state_id' => 23, 'city' => 'Goetzville'],
                ['state_id' => 23, 'city' => 'Hulbert'],
                ['state_id' => 23, 'city' => 'Kinross'],
                ['state_id' => 23, 'city' => 'Paradise'],
                ['state_id' => 23, 'city' => 'Pickford'],
                ['state_id' => 23, 'city' => 'Rudyard'],
                ['state_id' => 23, 'city' => 'Sault Sainte Marie'],
                ['state_id' => 23, 'city' => 'Kincheloe'],
                ['state_id' => 23, 'city' => 'Trout Lake'],
                ['state_id' => 23, 'city' => 'Clare'],
                ['state_id' => 23, 'city' => 'Farwell'],
                ['state_id' => 23, 'city' => 'Harrison'],
                ['state_id' => 23, 'city' => 'Lake'],
                ['state_id' => 23, 'city' => 'Lake George'],
                ['state_id' => 23, 'city' => 'Bath'],
                ['state_id' => 23, 'city' => 'Dewitt'],
                ['state_id' => 23, 'city' => 'Eagle'],
                ['state_id' => 23, 'city' => 'Elsie'],
                ['state_id' => 23, 'city' => 'Eureka'],
                ['state_id' => 23, 'city' => 'Fowler'],
                ['state_id' => 23, 'city' => 'Maple Rapids'],
                ['state_id' => 23, 'city' => 'Ovid'],
                ['state_id' => 23, 'city' => 'Saint Johns'],
                ['state_id' => 23, 'city' => 'Westphalia'],
                ['state_id' => 23, 'city' => 'Frederic'],
                ['state_id' => 23, 'city' => 'Grayling'],
                ['state_id' => 23, 'city' => 'Bark River'],
                ['state_id' => 23, 'city' => 'Cornell'],
                ['state_id' => 23, 'city' => 'Escanaba'],
                ['state_id' => 23, 'city' => 'Garden'],
                ['state_id' => 23, 'city' => 'Gladstone'],
                ['state_id' => 23, 'city' => 'Nahma'],
                ['state_id' => 23, 'city' => 'Perkins'],
                ['state_id' => 23, 'city' => 'Rapid River'],
                ['state_id' => 23, 'city' => 'Rock'],
                ['state_id' => 23, 'city' => 'Wells'],
                ['state_id' => 23, 'city' => 'Iron Mountain'],
                ['state_id' => 23, 'city' => 'Kingsford'],
                ['state_id' => 23, 'city' => 'Channing'],
                ['state_id' => 23, 'city' => 'Felch'],
                ['state_id' => 23, 'city' => 'Foster City'],
                ['state_id' => 23, 'city' => 'Loretto'],
                ['state_id' => 23, 'city' => 'Norway'],
                ['state_id' => 23, 'city' => 'Quinnesec'],
                ['state_id' => 23, 'city' => 'Ralph'],
                ['state_id' => 23, 'city' => 'Sagola'],
                ['state_id' => 23, 'city' => 'Vulcan'],
                ['state_id' => 23, 'city' => 'Charlotte'],
                ['state_id' => 23, 'city' => 'Dimondale'],
                ['state_id' => 23, 'city' => 'Eaton Rapids'],
                ['state_id' => 23, 'city' => 'Grand Ledge'],
                ['state_id' => 23, 'city' => 'Mulliken'],
                ['state_id' => 23, 'city' => 'Potterville'],
                ['state_id' => 23, 'city' => 'Sunfield'],
                ['state_id' => 23, 'city' => 'Lansing'],
                ['state_id' => 23, 'city' => 'Bellevue'],
                ['state_id' => 23, 'city' => 'Olivet'],
                ['state_id' => 23, 'city' => 'Vermontville'],
                ['state_id' => 23, 'city' => 'Alanson'],
                ['state_id' => 23, 'city' => 'Carp Lake'],
                ['state_id' => 23, 'city' => 'Conway'],
                ['state_id' => 23, 'city' => 'Cross Village'],
                ['state_id' => 23, 'city' => 'Good Hart'],
                ['state_id' => 23, 'city' => 'Harbor Springs'],
                ['state_id' => 23, 'city' => 'Levering'],
                ['state_id' => 23, 'city' => 'Oden'],
                ['state_id' => 23, 'city' => 'Pellston'],
                ['state_id' => 23, 'city' => 'Petoskey'],
                ['state_id' => 23, 'city' => 'Atlas'],
                ['state_id' => 23, 'city' => 'Clio'],
                ['state_id' => 23, 'city' => 'Davison'],
                ['state_id' => 23, 'city' => 'Fenton'],
                ['state_id' => 23, 'city' => 'Flushing'],
                ['state_id' => 23, 'city' => 'Gaines'],
                ['state_id' => 23, 'city' => 'Genesee'],
                ['state_id' => 23, 'city' => 'Goodrich'],
                ['state_id' => 23, 'city' => 'Grand Blanc'],
                ['state_id' => 23, 'city' => 'Lennon'],
                ['state_id' => 23, 'city' => 'Linden'],
                ['state_id' => 23, 'city' => 'Montrose'],
                ['state_id' => 23, 'city' => 'Mount Morris'],
                ['state_id' => 23, 'city' => 'Otisville'],
                ['state_id' => 23, 'city' => 'Swartz Creek'],
                ['state_id' => 23, 'city' => 'Flint'],
                ['state_id' => 23, 'city' => 'Burton'],
                ['state_id' => 23, 'city' => 'Beaverton'],
                ['state_id' => 23, 'city' => 'Gladwin'],
                ['state_id' => 23, 'city' => 'Saginaw'],
                ['state_id' => 23, 'city' => 'Rhodes'],
                ['state_id' => 23, 'city' => 'Bessemer'],
                ['state_id' => 23, 'city' => 'Ironwood'],
                ['state_id' => 23, 'city' => 'Marenisco'],
                ['state_id' => 23, 'city' => 'Ramsay'],
                ['state_id' => 23, 'city' => 'Wakefield'],
                ['state_id' => 23, 'city' => 'Watersmeet'],
                ['state_id' => 23, 'city' => 'Acme'],
                ['state_id' => 23, 'city' => 'Fife Lake'],
                ['state_id' => 23, 'city' => 'Grawn'],
                ['state_id' => 23, 'city' => 'Interlochen'],
                ['state_id' => 23, 'city' => 'Kingsley'],
                ['state_id' => 23, 'city' => 'Mayfield'],
                ['state_id' => 23, 'city' => 'Old Mission'],
                ['state_id' => 23, 'city' => 'Traverse City'],
                ['state_id' => 23, 'city' => 'Williamsburg'],
                ['state_id' => 23, 'city' => 'Breckenridge'],
                ['state_id' => 23, 'city' => 'Wheeler'],
                ['state_id' => 23, 'city' => 'Alma'],
                ['state_id' => 23, 'city' => 'Ashley'],
                ['state_id' => 23, 'city' => 'Bannister'],
                ['state_id' => 23, 'city' => 'Elm Hall'],
                ['state_id' => 23, 'city' => 'Elwell'],
                ['state_id' => 23, 'city' => 'Ithaca'],
                ['state_id' => 23, 'city' => 'Middleton'],
                ['state_id' => 23, 'city' => 'North Star'],
                ['state_id' => 23, 'city' => 'Perrinton'],
                ['state_id' => 23, 'city' => 'Pompeii'],
                ['state_id' => 23, 'city' => 'Riverdale'],
                ['state_id' => 23, 'city' => 'Saint Louis'],
                ['state_id' => 23, 'city' => 'Sumner'],
                ['state_id' => 23, 'city' => 'Allen'],
                ['state_id' => 23, 'city' => 'Camden'],
                ['state_id' => 23, 'city' => 'Frontier'],
                ['state_id' => 23, 'city' => 'Hillsdale'],
                ['state_id' => 23, 'city' => 'Jerome'],
                ['state_id' => 23, 'city' => 'Jonesville'],
                ['state_id' => 23, 'city' => 'Litchfield'],
                ['state_id' => 23, 'city' => 'Moscow'],
                ['state_id' => 23, 'city' => 'Mosherville'],
                ['state_id' => 23, 'city' => 'North Adams'],
                ['state_id' => 23, 'city' => 'Osseo'],
                ['state_id' => 23, 'city' => 'Pittsford'],
                ['state_id' => 23, 'city' => 'Reading'],
                ['state_id' => 23, 'city' => 'Somerset'],
                ['state_id' => 23, 'city' => 'Somerset Center'],
                ['state_id' => 23, 'city' => 'Waldron'],
                ['state_id' => 23, 'city' => 'Atlantic Mine'],
                ['state_id' => 23, 'city' => 'Calumet'],
                ['state_id' => 23, 'city' => 'Chassell'],
                ['state_id' => 23, 'city' => 'Copper City'],
                ['state_id' => 23, 'city' => 'Dodgeville'],
                ['state_id' => 23, 'city' => 'Dollar Bay'],
                ['state_id' => 23, 'city' => 'Hancock'],
                ['state_id' => 23, 'city' => 'Houghton'],
                ['state_id' => 23, 'city' => 'Hubbell'],
                ['state_id' => 23, 'city' => 'Kearsarge'],
                ['state_id' => 23, 'city' => 'Lake Linden'],
                ['state_id' => 23, 'city' => 'Nisula'],
                ['state_id' => 23, 'city' => 'Painesdale'],
                ['state_id' => 23, 'city' => 'Pelkie'],
                ['state_id' => 23, 'city' => 'Sidnaw'],
                ['state_id' => 23, 'city' => 'South Range'],
                ['state_id' => 23, 'city' => 'Toivola'],
                ['state_id' => 23, 'city' => 'Bad Axe'],
                ['state_id' => 23, 'city' => 'Filion'],
                ['state_id' => 23, 'city' => 'Harbor Beach'],
                ['state_id' => 23, 'city' => 'Kinde'],
                ['state_id' => 23, 'city' => 'Port Austin'],
                ['state_id' => 23, 'city' => 'Port Hope'],
                ['state_id' => 23, 'city' => 'Ruth'],
                ['state_id' => 23, 'city' => 'Ubly'],
                ['state_id' => 23, 'city' => 'Bay Port'],
                ['state_id' => 23, 'city' => 'Caseville'],
                ['state_id' => 23, 'city' => 'Elkton'],
                ['state_id' => 23, 'city' => 'Owendale'],
                ['state_id' => 23, 'city' => 'Pigeon'],
                ['state_id' => 23, 'city' => 'Sebewaing'],
                ['state_id' => 23, 'city' => 'Okemos'],
                ['state_id' => 23, 'city' => 'Dansville'],
                ['state_id' => 23, 'city' => 'East Lansing'],
                ['state_id' => 23, 'city' => 'Haslett'],
                ['state_id' => 23, 'city' => 'Holt'],
                ['state_id' => 23, 'city' => 'Mason'],
                ['state_id' => 23, 'city' => 'Webberville'],
                ['state_id' => 23, 'city' => 'Williamston'],
                ['state_id' => 23, 'city' => 'Leslie'],
                ['state_id' => 23, 'city' => 'Onondaga'],
                ['state_id' => 23, 'city' => 'Stockbridge'],
                ['state_id' => 23, 'city' => 'Belding'],
                ['state_id' => 23, 'city' => 'Clarksville'],
                ['state_id' => 23, 'city' => 'Hubbardston'],
                ['state_id' => 23, 'city' => 'Ionia'],
                ['state_id' => 23, 'city' => 'Lake Odessa'],
                ['state_id' => 23, 'city' => 'Lyons'],
                ['state_id' => 23, 'city' => 'Muir'],
                ['state_id' => 23, 'city' => 'Orleans'],
                ['state_id' => 23, 'city' => 'Palo'],
                ['state_id' => 23, 'city' => 'Pewamo'],
                ['state_id' => 23, 'city' => 'Portland'],
                ['state_id' => 23, 'city' => 'Saranac'],
                ['state_id' => 23, 'city' => 'Smyrna'],
                ['state_id' => 23, 'city' => 'East Tawas'],
                ['state_id' => 23, 'city' => 'Hale'],
                ['state_id' => 23, 'city' => 'Long Lake'],
                ['state_id' => 23, 'city' => 'National City'],
                ['state_id' => 23, 'city' => 'Oscoda'],
                ['state_id' => 23, 'city' => 'Tawas City'],
                ['state_id' => 23, 'city' => 'Whittemore'],
                ['state_id' => 23, 'city' => 'Alpha'],
                ['state_id' => 23, 'city' => 'Amasa'],
                ['state_id' => 23, 'city' => 'Caspian'],
                ['state_id' => 23, 'city' => 'Crystal Falls'],
                ['state_id' => 23, 'city' => 'Gaastra'],
                ['state_id' => 23, 'city' => 'Iron River'],
                ['state_id' => 23, 'city' => 'Stambaugh'],
                ['state_id' => 23, 'city' => 'Mount Pleasant'],
                ['state_id' => 23, 'city' => 'Rosebush'],
                ['state_id' => 23, 'city' => 'Shepherd'],
                ['state_id' => 23, 'city' => 'Weidman'],
                ['state_id' => 23, 'city' => 'Winn'],
                ['state_id' => 23, 'city' => 'Blanchard'],
                ['state_id' => 23, 'city' => 'Jackson'],
                ['state_id' => 23, 'city' => 'Brooklyn'],
                ['state_id' => 23, 'city' => 'Clarklake'],
                ['state_id' => 23, 'city' => 'Concord'],
                ['state_id' => 23, 'city' => 'Grass Lake'],
                ['state_id' => 23, 'city' => 'Hanover'],
                ['state_id' => 23, 'city' => 'Horton'],
                ['state_id' => 23, 'city' => 'Michigan Center'],
                ['state_id' => 23, 'city' => 'Munith'],
                ['state_id' => 23, 'city' => 'Napoleon'],
                ['state_id' => 23, 'city' => 'Norvell'],
                ['state_id' => 23, 'city' => 'Parma'],
                ['state_id' => 23, 'city' => 'Pleasant Lake'],
                ['state_id' => 23, 'city' => 'Rives Junction'],
                ['state_id' => 23, 'city' => 'Spring Arbor'],
                ['state_id' => 23, 'city' => 'Springport'],
                ['state_id' => 23, 'city' => 'Kalamazoo'],
                ['state_id' => 23, 'city' => 'Portage'],
                ['state_id' => 23, 'city' => 'Augusta'],
                ['state_id' => 23, 'city' => 'Climax'],
                ['state_id' => 23, 'city' => 'Comstock'],
                ['state_id' => 23, 'city' => 'Fulton'],
                ['state_id' => 23, 'city' => 'Galesburg'],
                ['state_id' => 23, 'city' => 'Nazareth'],
                ['state_id' => 23, 'city' => 'Oshtemo'],
                ['state_id' => 23, 'city' => 'Richland'],
                ['state_id' => 23, 'city' => 'Schoolcraft'],
                ['state_id' => 23, 'city' => 'Scotts'],
                ['state_id' => 23, 'city' => 'Vicksburg'],
                ['state_id' => 23, 'city' => 'Kalkaska'],
                ['state_id' => 23, 'city' => 'Rapid City'],
                ['state_id' => 23, 'city' => 'South Boardman'],
                ['state_id' => 23, 'city' => 'Ada'],
                ['state_id' => 23, 'city' => 'Alto'],
                ['state_id' => 23, 'city' => 'Belmont'],
                ['state_id' => 23, 'city' => 'Byron Center'],
                ['state_id' => 23, 'city' => 'Caledonia'],
                ['state_id' => 23, 'city' => 'Cannonsburg'],
                ['state_id' => 23, 'city' => 'Cedar Springs'],
                ['state_id' => 23, 'city' => 'Comstock Park'],
                ['state_id' => 23, 'city' => 'Kent City'],
                ['state_id' => 23, 'city' => 'Lowell'],
                ['state_id' => 23, 'city' => 'Rockford'],
                ['state_id' => 23, 'city' => 'Sand Lake'],
                ['state_id' => 23, 'city' => 'Sparta'],
                ['state_id' => 23, 'city' => 'Grandville'],
                ['state_id' => 23, 'city' => 'Grand Rapids'],
                ['state_id' => 23, 'city' => 'Wyoming'],
                ['state_id' => 23, 'city' => 'Allouez'],
                ['state_id' => 23, 'city' => 'Ahmeek'],
                ['state_id' => 23, 'city' => 'Copper Harbor'],
                ['state_id' => 23, 'city' => 'Mohawk'],
                ['state_id' => 23, 'city' => 'Baldwin'],
                ['state_id' => 23, 'city' => 'Branch'],
                ['state_id' => 23, 'city' => 'Chase'],
                ['state_id' => 23, 'city' => 'Idlewild'],
                ['state_id' => 23, 'city' => 'Irons'],
                ['state_id' => 23, 'city' => 'Luther'],
                ['state_id' => 23, 'city' => 'Almont'],
                ['state_id' => 23, 'city' => 'Attica'],
                ['state_id' => 23, 'city' => 'Columbiaville'],
                ['state_id' => 23, 'city' => 'Dryden'],
                ['state_id' => 23, 'city' => 'Hadley'],
                ['state_id' => 23, 'city' => 'Imlay City'],
                ['state_id' => 23, 'city' => 'Lapeer'],
                ['state_id' => 23, 'city' => 'Metamora'],
                ['state_id' => 23, 'city' => 'North Branch'],
                ['state_id' => 23, 'city' => 'Otter Lake'],
                ['state_id' => 23, 'city' => 'Clifford'],
                ['state_id' => 23, 'city' => 'Silverwood'],
                ['state_id' => 23, 'city' => 'Cedar'],
                ['state_id' => 23, 'city' => 'Empire'],
                ['state_id' => 23, 'city' => 'Glen Arbor'],
                ['state_id' => 23, 'city' => 'Lake Leelanau'],
                ['state_id' => 23, 'city' => 'Leland'],
                ['state_id' => 23, 'city' => 'Maple City'],
                ['state_id' => 23, 'city' => 'Northport'],
                ['state_id' => 23, 'city' => 'Omena'],
                ['state_id' => 23, 'city' => 'Suttons Bay'],
                ['state_id' => 23, 'city' => 'Addison'],
                ['state_id' => 23, 'city' => 'Adrian'],
                ['state_id' => 23, 'city' => 'Blissfield'],
                ['state_id' => 23, 'city' => 'Britton'],
                ['state_id' => 23, 'city' => 'Cement City'],
                ['state_id' => 23, 'city' => 'Clayton'],
                ['state_id' => 23, 'city' => 'Clinton'],
                ['state_id' => 23, 'city' => 'Deerfield'],
                ['state_id' => 23, 'city' => 'Hudson'],
                ['state_id' => 23, 'city' => 'Jasper'],
                ['state_id' => 23, 'city' => 'Manitou Beach'],
                ['state_id' => 23, 'city' => 'Morenci'],
                ['state_id' => 23, 'city' => 'Onsted'],
                ['state_id' => 23, 'city' => 'Palmyra'],
                ['state_id' => 23, 'city' => 'Riga'],
                ['state_id' => 23, 'city' => 'Sand Creek'],
                ['state_id' => 23, 'city' => 'Tecumseh'],
                ['state_id' => 23, 'city' => 'Tipton'],
                ['state_id' => 23, 'city' => 'Weston'],
                ['state_id' => 23, 'city' => 'Brighton'],
                ['state_id' => 23, 'city' => 'Gregory'],
                ['state_id' => 23, 'city' => 'Hamburg'],
                ['state_id' => 23, 'city' => 'Lakeland'],
                ['state_id' => 23, 'city' => 'Pinckney'],
                ['state_id' => 23, 'city' => 'Hartland'],
                ['state_id' => 23, 'city' => 'Cohoctah'],
                ['state_id' => 23, 'city' => 'Fowlerville'],
                ['state_id' => 23, 'city' => 'Howell'],
                ['state_id' => 23, 'city' => 'Mc Millan'],
                ['state_id' => 23, 'city' => 'Newberry'],
                ['state_id' => 23, 'city' => 'Cedarville'],
                ['state_id' => 23, 'city' => 'Hessel'],
                ['state_id' => 23, 'city' => 'Mackinac Island'],
                ['state_id' => 23, 'city' => 'Moran'],
                ['state_id' => 23, 'city' => 'Naubinway'],
                ['state_id' => 23, 'city' => 'Pointe Aux Pins'],
                ['state_id' => 23, 'city' => 'Saint Ignace'],
                ['state_id' => 23, 'city' => 'Curtis'],
                ['state_id' => 23, 'city' => 'Engadine'],
                ['state_id' => 23, 'city' => 'Gould City'],
                ['state_id' => 23, 'city' => 'Armada'],
                ['state_id' => 23, 'city' => 'Center Line'],
                ['state_id' => 23, 'city' => 'Eastpointe'],
                ['state_id' => 23, 'city' => 'Fraser'],
                ['state_id' => 23, 'city' => 'Clinton Township'],
                ['state_id' => 23, 'city' => 'Macomb'],
                ['state_id' => 23, 'city' => 'Mount Clemens'],
                ['state_id' => 23, 'city' => 'Harrison Township'],
                ['state_id' => 23, 'city' => 'New Baltimore'],
                ['state_id' => 23, 'city' => 'New Haven'],
                ['state_id' => 23, 'city' => 'Richmond'],
                ['state_id' => 23, 'city' => 'Romeo'],
                ['state_id' => 23, 'city' => 'Roseville'],
                ['state_id' => 23, 'city' => 'Saint Clair Shores'],
                ['state_id' => 23, 'city' => 'Warren'],
                ['state_id' => 23, 'city' => 'Washington'],
                ['state_id' => 23, 'city' => 'Ray'],
                ['state_id' => 23, 'city' => 'Sterling Heights'],
                ['state_id' => 23, 'city' => 'Utica'],
                ['state_id' => 23, 'city' => 'Arcadia'],
                ['state_id' => 23, 'city' => 'Bear Lake'],
                ['state_id' => 23, 'city' => 'Brethren'],
                ['state_id' => 23, 'city' => 'Copemish'],
                ['state_id' => 23, 'city' => 'Eastlake'],
                ['state_id' => 23, 'city' => 'Filer City'],
                ['state_id' => 23, 'city' => 'Kaleva'],
                ['state_id' => 23, 'city' => 'Manistee'],
                ['state_id' => 23, 'city' => 'Onekama'],
                ['state_id' => 23, 'city' => 'Wellston'],
                ['state_id' => 23, 'city' => 'Big Bay'],
                ['state_id' => 23, 'city' => 'Champion'],
                ['state_id' => 23, 'city' => 'Arnold'],
                ['state_id' => 23, 'city' => 'Little Lake'],
                ['state_id' => 23, 'city' => 'Gwinn'],
                ['state_id' => 23, 'city' => 'Ishpeming'],
                ['state_id' => 23, 'city' => 'Marquette'],
                ['state_id' => 23, 'city' => 'Michigamme'],
                ['state_id' => 23, 'city' => 'National Mine'],
                ['state_id' => 23, 'city' => 'Negaunee'],
                ['state_id' => 23, 'city' => 'Palmer'],
                ['state_id' => 23, 'city' => 'Republic'],
                ['state_id' => 23, 'city' => 'Skandia'],
                ['state_id' => 23, 'city' => 'Custer'],
                ['state_id' => 23, 'city' => 'Fountain'],
                ['state_id' => 23, 'city' => 'Free Soil'],
                ['state_id' => 23, 'city' => 'Ludington'],
                ['state_id' => 23, 'city' => 'Scottville'],
                ['state_id' => 23, 'city' => 'Walhalla'],
                ['state_id' => 23, 'city' => 'Barryton'],
                ['state_id' => 23, 'city' => 'Big Rapids'],
                ['state_id' => 23, 'city' => 'Chippewa Lake'],
                ['state_id' => 23, 'city' => 'Mecosta'],
                ['state_id' => 23, 'city' => 'Morley'],
                ['state_id' => 23, 'city' => 'Paris'],
                ['state_id' => 23, 'city' => 'Remus'],
                ['state_id' => 23, 'city' => 'Rodney'],
                ['state_id' => 23, 'city' => 'Stanwood'],
                ['state_id' => 23, 'city' => 'Carney'],
                ['state_id' => 23, 'city' => 'Daggett'],
                ['state_id' => 23, 'city' => 'Harris'],
                ['state_id' => 23, 'city' => 'Hermansville'],
                ['state_id' => 23, 'city' => 'Ingalls'],
                ['state_id' => 23, 'city' => 'Menominee'],
                ['state_id' => 23, 'city' => 'Nadeau'],
                ['state_id' => 23, 'city' => 'Perronville'],
                ['state_id' => 23, 'city' => 'Powers'],
                ['state_id' => 23, 'city' => 'Spalding'],
                ['state_id' => 23, 'city' => 'Stephenson'],
                ['state_id' => 23, 'city' => 'Wallace'],
                ['state_id' => 23, 'city' => 'Wilson'],
                ['state_id' => 23, 'city' => 'Coleman'],
                ['state_id' => 23, 'city' => 'Edenville'],
                ['state_id' => 23, 'city' => 'Hope'],
                ['state_id' => 23, 'city' => 'Midland'],
                ['state_id' => 23, 'city' => 'Sanford'],
                ['state_id' => 23, 'city' => 'Falmouth'],
                ['state_id' => 23, 'city' => 'Lake City'],
                ['state_id' => 23, 'city' => 'Mc Bain'],
                ['state_id' => 23, 'city' => 'Merritt'],
                ['state_id' => 23, 'city' => 'Azalia'],
                ['state_id' => 23, 'city' => 'Carleton'],
                ['state_id' => 23, 'city' => 'Dundee'],
                ['state_id' => 23, 'city' => 'Erie'],
                ['state_id' => 23, 'city' => 'Ida'],
                ['state_id' => 23, 'city' => 'Lambertville'],
                ['state_id' => 23, 'city' => 'La Salle'],
                ['state_id' => 23, 'city' => 'Luna Pier'],
                ['state_id' => 23, 'city' => 'Maybee'],
                ['state_id' => 23, 'city' => 'Milan'],
                ['state_id' => 23, 'city' => 'Monroe'],
                ['state_id' => 23, 'city' => 'Newport'],
                ['state_id' => 23, 'city' => 'Samaria'],
                ['state_id' => 23, 'city' => 'South Rockwood'],
                ['state_id' => 23, 'city' => 'Temperance'],
                ['state_id' => 23, 'city' => 'Ottawa Lake'],
                ['state_id' => 23, 'city' => 'Petersburg'],
                ['state_id' => 23, 'city' => 'Carson City'],
                ['state_id' => 23, 'city' => 'Cedar Lake'],
                ['state_id' => 23, 'city' => 'Crystal'],
                ['state_id' => 23, 'city' => 'Edmore'],
                ['state_id' => 23, 'city' => 'Fenwick'],
                ['state_id' => 23, 'city' => 'Greenville'],
                ['state_id' => 23, 'city' => 'Lakeview'],
                ['state_id' => 23, 'city' => 'Mcbrides'],
                ['state_id' => 23, 'city' => 'Sheridan'],
                ['state_id' => 23, 'city' => 'Sidney'],
                ['state_id' => 23, 'city' => 'Six Lakes'],
                ['state_id' => 23, 'city' => 'Stanton'],
                ['state_id' => 23, 'city' => 'Vestaburg'],
                ['state_id' => 23, 'city' => 'Coral'],
                ['state_id' => 23, 'city' => 'Gowen'],
                ['state_id' => 23, 'city' => 'Howard City'],
                ['state_id' => 23, 'city' => 'Pierson'],
                ['state_id' => 23, 'city' => 'Trufant'],
                ['state_id' => 23, 'city' => 'Atlanta'],
                ['state_id' => 23, 'city' => 'Hillman'],
                ['state_id' => 23, 'city' => 'Lewiston'],
                ['state_id' => 23, 'city' => 'Bailey'],
                ['state_id' => 23, 'city' => 'Casnovia'],
                ['state_id' => 23, 'city' => 'Fruitport'],
                ['state_id' => 23, 'city' => 'Holton'],
                ['state_id' => 23, 'city' => 'Montague'],
                ['state_id' => 23, 'city' => 'Muskegon'],
                ['state_id' => 23, 'city' => 'Ravenna'],
                ['state_id' => 23, 'city' => 'Twin Lake'],
                ['state_id' => 23, 'city' => 'Whitehall'],
                ['state_id' => 23, 'city' => 'Sylvan Beach'],
                ['state_id' => 23, 'city' => 'Bitely'],
                ['state_id' => 23, 'city' => 'Brohman'],
                ['state_id' => 23, 'city' => 'Grant'],
                ['state_id' => 23, 'city' => 'Newaygo'],
                ['state_id' => 23, 'city' => 'White Cloud'],
                ['state_id' => 23, 'city' => 'Fremont'],
                ['state_id' => 23, 'city' => 'Troy'],
                ['state_id' => 23, 'city' => 'Birmingham'],
                ['state_id' => 23, 'city' => 'Clawson'],
                ['state_id' => 23, 'city' => 'Franklin'],
                ['state_id' => 23, 'city' => 'Hazel Park'],
                ['state_id' => 23, 'city' => 'Southfield'],
                ['state_id' => 23, 'city' => 'Royal Oak'],
                ['state_id' => 23, 'city' => 'Pleasant Ridge'],
                ['state_id' => 23, 'city' => 'Huntington Woods'],
                ['state_id' => 23, 'city' => 'Madison Heights'],
                ['state_id' => 23, 'city' => 'Berkley'],
                ['state_id' => 23, 'city' => 'New Hudson'],
                ['state_id' => 23, 'city' => 'South Lyon'],
                ['state_id' => 23, 'city' => 'Ferndale'],
                ['state_id' => 23, 'city' => 'Oak Park'],
                ['state_id' => 23, 'city' => 'Bloomfield Hills'],
                ['state_id' => 23, 'city' => 'Rochester'],
                ['state_id' => 23, 'city' => 'Keego Harbor'],
                ['state_id' => 23, 'city' => 'Auburn Hills'],
                ['state_id' => 23, 'city' => 'West Bloomfield'],
                ['state_id' => 23, 'city' => 'Waterford'],
                ['state_id' => 23, 'city' => 'Drayton Plains'],
                ['state_id' => 23, 'city' => 'Farmington'],
                ['state_id' => 23, 'city' => 'Pontiac'],
                ['state_id' => 23, 'city' => 'Clarkston'],
                ['state_id' => 23, 'city' => 'Davisburg'],
                ['state_id' => 23, 'city' => 'Highland'],
                ['state_id' => 23, 'city' => 'Lake Orion'],
                ['state_id' => 23, 'city' => 'Oakland'],
                ['state_id' => 23, 'city' => 'Lakeville'],
                ['state_id' => 23, 'city' => 'Leonard'],
                ['state_id' => 23, 'city' => 'Oxford'],
                ['state_id' => 23, 'city' => 'Novi'],
                ['state_id' => 23, 'city' => 'Milford'],
                ['state_id' => 23, 'city' => 'Commerce Township'],
                ['state_id' => 23, 'city' => 'White Lake'],
                ['state_id' => 23, 'city' => 'Union Lake'],
                ['state_id' => 23, 'city' => 'Walled Lake'],
                ['state_id' => 23, 'city' => 'Wixom'],
                ['state_id' => 23, 'city' => 'Holly'],
                ['state_id' => 23, 'city' => 'Ortonville'],
                ['state_id' => 23, 'city' => 'Hart'],
                ['state_id' => 23, 'city' => 'Hesperia'],
                ['state_id' => 23, 'city' => 'Mears'],
                ['state_id' => 23, 'city' => 'New Era'],
                ['state_id' => 23, 'city' => 'Pentwater'],
                ['state_id' => 23, 'city' => 'Rothbury'],
                ['state_id' => 23, 'city' => 'Shelby'],
                ['state_id' => 23, 'city' => 'Walkerville'],
                ['state_id' => 23, 'city' => 'Alger'],
                ['state_id' => 23, 'city' => 'Lupton'],
                ['state_id' => 23, 'city' => 'Rose City'],
                ['state_id' => 23, 'city' => 'West Branch'],
                ['state_id' => 23, 'city' => 'Prescott'],
                ['state_id' => 23, 'city' => 'South Branch'],
                ['state_id' => 23, 'city' => 'Bergland'],
                ['state_id' => 23, 'city' => 'Bruce Crossing'],
                ['state_id' => 23, 'city' => 'Ewen'],
                ['state_id' => 23, 'city' => 'Greenland'],
                ['state_id' => 23, 'city' => 'Mass City'],
                ['state_id' => 23, 'city' => 'Ontonagon'],
                ['state_id' => 23, 'city' => 'Rockland'],
                ['state_id' => 23, 'city' => 'Trout Creek'],
                ['state_id' => 23, 'city' => 'White Pine'],
                ['state_id' => 23, 'city' => 'Evart'],
                ['state_id' => 23, 'city' => 'Hersey'],
                ['state_id' => 23, 'city' => 'Leroy'],
                ['state_id' => 23, 'city' => 'Marion'],
                ['state_id' => 23, 'city' => 'Reed City'],
                ['state_id' => 23, 'city' => 'Sears'],
                ['state_id' => 23, 'city' => 'Tustin'],
                ['state_id' => 23, 'city' => 'Comins'],
                ['state_id' => 23, 'city' => 'Fairview'],
                ['state_id' => 23, 'city' => 'Luzerne'],
                ['state_id' => 23, 'city' => 'Mio'],
                ['state_id' => 23, 'city' => 'Elmira'],
                ['state_id' => 23, 'city' => 'Gaylord'],
                ['state_id' => 23, 'city' => 'Johannesburg'],
                ['state_id' => 23, 'city' => 'Vanderbilt'],
                ['state_id' => 23, 'city' => 'Waters'],
                ['state_id' => 23, 'city' => 'Allendale'],
                ['state_id' => 23, 'city' => 'Conklin'],
                ['state_id' => 23, 'city' => 'Coopersville'],
                ['state_id' => 23, 'city' => 'Ferrysburg'],
                ['state_id' => 23, 'city' => 'Grand Haven'],
                ['state_id' => 23, 'city' => 'Holland'],
                ['state_id' => 23, 'city' => 'Hudsonville'],
                ['state_id' => 23, 'city' => 'Jamestown'],
                ['state_id' => 23, 'city' => 'Jenison'],
                ['state_id' => 23, 'city' => 'Lamont'],
                ['state_id' => 23, 'city' => 'Macatawa'],
                ['state_id' => 23, 'city' => 'Marne'],
                ['state_id' => 23, 'city' => 'Nunica'],
                ['state_id' => 23, 'city' => 'Spring Lake'],
                ['state_id' => 23, 'city' => 'West Olive'],
                ['state_id' => 23, 'city' => 'Zeeland'],
                ['state_id' => 23, 'city' => 'Hawks'],
                ['state_id' => 23, 'city' => 'Millersburg'],
                ['state_id' => 23, 'city' => 'Onaway'],
                ['state_id' => 23, 'city' => 'Posen'],
                ['state_id' => 23, 'city' => 'Presque Isle'],
                ['state_id' => 23, 'city' => 'Rogers City'],
                ['state_id' => 23, 'city' => 'Higgins Lake'],
                ['state_id' => 23, 'city' => 'Houghton Lake'],
                ['state_id' => 23, 'city' => 'Houghton Lake Heights'],
                ['state_id' => 23, 'city' => 'Prudenville'],
                ['state_id' => 23, 'city' => 'Roscommon'],
                ['state_id' => 23, 'city' => 'Saint Helen'],
                ['state_id' => 23, 'city' => 'Birch Run'],
                ['state_id' => 23, 'city' => 'Burt'],
                ['state_id' => 23, 'city' => 'Brant'],
                ['state_id' => 23, 'city' => 'Chesaning'],
                ['state_id' => 23, 'city' => 'Freeland'],
                ['state_id' => 23, 'city' => 'Hemlock'],
                ['state_id' => 23, 'city' => 'Merrill'],
                ['state_id' => 23, 'city' => 'Oakley'],
                ['state_id' => 23, 'city' => 'Saint Charles'],
                ['state_id' => 23, 'city' => 'Bridgeport'],
                ['state_id' => 23, 'city' => 'Carrollton'],
                ['state_id' => 23, 'city' => 'Frankenmuth'],
                ['state_id' => 23, 'city' => 'Algonac'],
                ['state_id' => 23, 'city' => 'Allenton'],
                ['state_id' => 23, 'city' => 'Anchorville'],
                ['state_id' => 23, 'city' => 'Avoca'],
                ['state_id' => 23, 'city' => 'Capac'],
                ['state_id' => 23, 'city' => 'Emmett'],
                ['state_id' => 23, 'city' => 'Fair Haven'],
                ['state_id' => 23, 'city' => 'Goodells'],
                ['state_id' => 23, 'city' => 'Harsens Island'],
                ['state_id' => 23, 'city' => 'Jeddo'],
                ['state_id' => 23, 'city' => 'Marine City'],
                ['state_id' => 23, 'city' => 'Marysville'],
                ['state_id' => 23, 'city' => 'Memphis'],
                ['state_id' => 23, 'city' => 'North Street'],
                ['state_id' => 23, 'city' => 'East China'],
                ['state_id' => 23, 'city' => 'Fort Gratiot'],
                ['state_id' => 23, 'city' => 'Port Huron'],
                ['state_id' => 23, 'city' => 'Columbus'],
                ['state_id' => 23, 'city' => 'Casco'],
                ['state_id' => 23, 'city' => 'Smiths Creek'],
                ['state_id' => 23, 'city' => 'Saint Clair'],
                ['state_id' => 23, 'city' => 'Yale'],
                ['state_id' => 23, 'city' => 'Burr Oak'],
                ['state_id' => 23, 'city' => 'Centreville'],
                ['state_id' => 23, 'city' => 'Colon'],
                ['state_id' => 23, 'city' => 'Constantine'],
                ['state_id' => 23, 'city' => 'Leonidas'],
                ['state_id' => 23, 'city' => 'Mendon'],
                ['state_id' => 23, 'city' => 'Nottawa'],
                ['state_id' => 23, 'city' => 'Sturgis'],
                ['state_id' => 23, 'city' => 'Three Rivers'],
                ['state_id' => 23, 'city' => 'White Pigeon'],
                ['state_id' => 23, 'city' => 'Applegate'],
                ['state_id' => 23, 'city' => 'Argyle'],
                ['state_id' => 23, 'city' => 'Brown City'],
                ['state_id' => 23, 'city' => 'Carsonville'],
                ['state_id' => 23, 'city' => 'Croswell'],
                ['state_id' => 23, 'city' => 'Decker'],
                ['state_id' => 23, 'city' => 'Deckerville'],
                ['state_id' => 23, 'city' => 'Forestville'],
                ['state_id' => 23, 'city' => 'Lexington'],
                ['state_id' => 23, 'city' => 'Marlette'],
                ['state_id' => 23, 'city' => 'Melvin'],
                ['state_id' => 23, 'city' => 'Minden City'],
                ['state_id' => 23, 'city' => 'Palms'],
                ['state_id' => 23, 'city' => 'Peck'],
                ['state_id' => 23, 'city' => 'Port Sanilac'],
                ['state_id' => 23, 'city' => 'Sandusky'],
                ['state_id' => 23, 'city' => 'Snover'],
                ['state_id' => 23, 'city' => 'Cooks'],
                ['state_id' => 23, 'city' => 'Germfask'],
                ['state_id' => 23, 'city' => 'Gulliver'],
                ['state_id' => 23, 'city' => 'Manistique'],
                ['state_id' => 23, 'city' => 'Seney'],
                ['state_id' => 23, 'city' => 'Bancroft'],
                ['state_id' => 23, 'city' => 'Byron'],
                ['state_id' => 23, 'city' => 'Durand'],
                ['state_id' => 23, 'city' => 'New Lothrop'],
                ['state_id' => 23, 'city' => 'Vernon'],
                ['state_id' => 23, 'city' => 'Corunna'],
                ['state_id' => 23, 'city' => 'Henderson'],
                ['state_id' => 23, 'city' => 'Laingsburg'],
                ['state_id' => 23, 'city' => 'Morrice'],
                ['state_id' => 23, 'city' => 'Owosso'],
                ['state_id' => 23, 'city' => 'Perry'],
                ['state_id' => 23, 'city' => 'Shaftsburg'],
                ['state_id' => 23, 'city' => 'Fostoria'],
                ['state_id' => 23, 'city' => 'Akron'],
                ['state_id' => 23, 'city' => 'Caro'],
                ['state_id' => 23, 'city' => 'Cass City'],
                ['state_id' => 23, 'city' => 'Deford'],
                ['state_id' => 23, 'city' => 'Fairgrove'],
                ['state_id' => 23, 'city' => 'Gagetown'],
                ['state_id' => 23, 'city' => 'Kingston'],
                ['state_id' => 23, 'city' => 'Mayville'],
                ['state_id' => 23, 'city' => 'Millington'],
                ['state_id' => 23, 'city' => 'Reese'],
                ['state_id' => 23, 'city' => 'Richville'],
                ['state_id' => 23, 'city' => 'Unionville'],
                ['state_id' => 23, 'city' => 'Vassar'],
                ['state_id' => 23, 'city' => 'Bangor'],
                ['state_id' => 23, 'city' => 'Bloomingdale'],
                ['state_id' => 23, 'city' => 'Breedsville'],
                ['state_id' => 23, 'city' => 'Covert'],
                ['state_id' => 23, 'city' => 'Decatur'],
                ['state_id' => 23, 'city' => 'Gobles'],
                ['state_id' => 23, 'city' => 'Grand Junction'],
                ['state_id' => 23, 'city' => 'Hartford'],
                ['state_id' => 23, 'city' => 'Kendall'],
                ['state_id' => 23, 'city' => 'Lacota'],
                ['state_id' => 23, 'city' => 'Lawrence'],
                ['state_id' => 23, 'city' => 'Lawton'],
                ['state_id' => 23, 'city' => 'Mattawan'],
                ['state_id' => 23, 'city' => 'Paw Paw'],
                ['state_id' => 23, 'city' => 'South Haven'],
                ['state_id' => 23, 'city' => 'Ann Arbor'],
                ['state_id' => 23, 'city' => 'Bridgewater'],
                ['state_id' => 23, 'city' => 'Chelsea'],
                ['state_id' => 23, 'city' => 'Dexter'],
                ['state_id' => 23, 'city' => 'Manchester'],
                ['state_id' => 23, 'city' => 'Salem'],
                ['state_id' => 23, 'city' => 'Saline'],
                ['state_id' => 23, 'city' => 'Whitmore Lake'],
                ['state_id' => 23, 'city' => 'Whittaker'],
                ['state_id' => 23, 'city' => 'Willis'],
                ['state_id' => 23, 'city' => 'Ypsilanti'],
                ['state_id' => 23, 'city' => 'Allen Park'],
                ['state_id' => 23, 'city' => 'Belleville'],
                ['state_id' => 23, 'city' => 'Dearborn'],
                ['state_id' => 23, 'city' => 'Melvindale'],
                ['state_id' => 23, 'city' => 'Dearborn Heights'],
                ['state_id' => 23, 'city' => 'Flat Rock'],
                ['state_id' => 23, 'city' => 'Garden City'],
                ['state_id' => 23, 'city' => 'Grosse Ile'],
                ['state_id' => 23, 'city' => 'Inkster'],
                ['state_id' => 23, 'city' => 'Lincoln Park'],
                ['state_id' => 23, 'city' => 'Livonia'],
                ['state_id' => 23, 'city' => 'New Boston'],
                ['state_id' => 23, 'city' => 'Northville'],
                ['state_id' => 23, 'city' => 'Plymouth'],
                ['state_id' => 23, 'city' => 'Rockwood'],
                ['state_id' => 23, 'city' => 'Romulus'],
                ['state_id' => 23, 'city' => 'Taylor'],
                ['state_id' => 23, 'city' => 'Trenton'],
                ['state_id' => 23, 'city' => 'Wayne'],
                ['state_id' => 23, 'city' => 'Westland'],
                ['state_id' => 23, 'city' => 'Canton'],
                ['state_id' => 23, 'city' => 'Wyandotte'],
                ['state_id' => 23, 'city' => 'Riverview'],
                ['state_id' => 23, 'city' => 'Southgate'],
                ['state_id' => 23, 'city' => 'Detroit'],
                ['state_id' => 23, 'city' => 'Highland Park'],
                ['state_id' => 23, 'city' => 'Hamtramck'],
                ['state_id' => 23, 'city' => 'River Rouge'],
                ['state_id' => 23, 'city' => 'Harper Woods'],
                ['state_id' => 23, 'city' => 'Ecorse'],
                ['state_id' => 23, 'city' => 'Grosse Pointe'],
                ['state_id' => 23, 'city' => 'Redford'],
                ['state_id' => 23, 'city' => 'Cadillac'],
                ['state_id' => 23, 'city' => 'Boon'],
                ['state_id' => 23, 'city' => 'Buckley'],
                ['state_id' => 23, 'city' => 'Harrietta'],
                ['state_id' => 23, 'city' => 'Manton'],
                ['state_id' => 23, 'city' => 'Mesick']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
