<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State44TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of TX - Texas.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 44, 'city' => 'Frankston'],
                ['state_id' => 44, 'city' => 'Neches'],
                ['state_id' => 44, 'city' => 'Palestine'],
                ['state_id' => 44, 'city' => 'Cayuga'],
                ['state_id' => 44, 'city' => 'Elkhart'],
                ['state_id' => 44, 'city' => 'Montalba'],
                ['state_id' => 44, 'city' => 'Tennessee Colony'],
                ['state_id' => 44, 'city' => 'Andrews'],
                ['state_id' => 44, 'city' => 'Lufkin'],
                ['state_id' => 44, 'city' => 'Diboll'],
                ['state_id' => 44, 'city' => 'Huntington'],
                ['state_id' => 44, 'city' => 'Pollok'],
                ['state_id' => 44, 'city' => 'Zavalla'],
                ['state_id' => 44, 'city' => 'Fulton'],
                ['state_id' => 44, 'city' => 'Rockport'],
                ['state_id' => 44, 'city' => 'Archer City'],
                ['state_id' => 44, 'city' => 'Holliday'],
                ['state_id' => 44, 'city' => 'Megargel'],
                ['state_id' => 44, 'city' => 'Scotland'],
                ['state_id' => 44, 'city' => 'Windthorst'],
                ['state_id' => 44, 'city' => 'Claude'],
                ['state_id' => 44, 'city' => 'Wayside'],
                ['state_id' => 44, 'city' => 'Campbellton'],
                ['state_id' => 44, 'city' => 'Charlotte'],
                ['state_id' => 44, 'city' => 'Christine'],
                ['state_id' => 44, 'city' => 'Jourdanton'],
                ['state_id' => 44, 'city' => 'Leming'],
                ['state_id' => 44, 'city' => 'Lytle'],
                ['state_id' => 44, 'city' => 'Peggy'],
                ['state_id' => 44, 'city' => 'Pleasanton'],
                ['state_id' => 44, 'city' => 'Poteet'],
                ['state_id' => 44, 'city' => 'Bellville'],
                ['state_id' => 44, 'city' => 'Kenney'],
                ['state_id' => 44, 'city' => 'San Felipe'],
                ['state_id' => 44, 'city' => 'Sealy'],
                ['state_id' => 44, 'city' => 'Wallis'],
                ['state_id' => 44, 'city' => 'Bleiblerville'],
                ['state_id' => 44, 'city' => 'Cat Spring'],
                ['state_id' => 44, 'city' => 'Industry'],
                ['state_id' => 44, 'city' => 'New Ulm'],
                ['state_id' => 44, 'city' => 'Enochs'],
                ['state_id' => 44, 'city' => 'Maple'],
                ['state_id' => 44, 'city' => 'Muleshoe'],
                ['state_id' => 44, 'city' => 'Bandera'],
                ['state_id' => 44, 'city' => 'Medina'],
                ['state_id' => 44, 'city' => 'Pipe Creek'],
                ['state_id' => 44, 'city' => 'Tarpley'],
                ['state_id' => 44, 'city' => 'Vanderpool'],
                ['state_id' => 44, 'city' => 'Bastrop'],
                ['state_id' => 44, 'city' => 'Cedar Creek'],
                ['state_id' => 44, 'city' => 'Elgin'],
                ['state_id' => 44, 'city' => 'Mc Dade'],
                ['state_id' => 44, 'city' => 'Paige'],
                ['state_id' => 44, 'city' => 'Red Rock'],
                ['state_id' => 44, 'city' => 'Rosanky'],
                ['state_id' => 44, 'city' => 'Smithville'],
                ['state_id' => 44, 'city' => 'Seymour'],
                ['state_id' => 44, 'city' => 'Beeville'],
                ['state_id' => 44, 'city' => 'Mineral'],
                ['state_id' => 44, 'city' => 'Normanna'],
                ['state_id' => 44, 'city' => 'Pawnee'],
                ['state_id' => 44, 'city' => 'Pettus'],
                ['state_id' => 44, 'city' => 'Tuleta'],
                ['state_id' => 44, 'city' => 'Skidmore'],
                ['state_id' => 44, 'city' => 'Tynan'],
                ['state_id' => 44, 'city' => 'Temple'],
                ['state_id' => 44, 'city' => 'Bartlett'],
                ['state_id' => 44, 'city' => 'Belton'],
                ['state_id' => 44, 'city' => 'Heidenheimer'],
                ['state_id' => 44, 'city' => 'Holland'],
                ['state_id' => 44, 'city' => 'Killeen'],
                ['state_id' => 44, 'city' => 'Fort Hood'],
                ['state_id' => 44, 'city' => 'Harker Heights'],
                ['state_id' => 44, 'city' => 'Little River Academy'],
                ['state_id' => 44, 'city' => 'Nolanville'],
                ['state_id' => 44, 'city' => 'Pendleton'],
                ['state_id' => 44, 'city' => 'Rogers'],
                ['state_id' => 44, 'city' => 'Salado'],
                ['state_id' => 44, 'city' => 'Troy'],
                ['state_id' => 44, 'city' => 'Atascosa'],
                ['state_id' => 44, 'city' => 'Boerne'],
                ['state_id' => 44, 'city' => 'Helotes'],
                ['state_id' => 44, 'city' => 'Macdona'],
                ['state_id' => 44, 'city' => 'Somerset'],
                ['state_id' => 44, 'city' => 'Von Ormy'],
                ['state_id' => 44, 'city' => 'Adkins'],
                ['state_id' => 44, 'city' => 'Converse'],
                ['state_id' => 44, 'city' => 'Elmendorf'],
                ['state_id' => 44, 'city' => 'Universal City'],
                ['state_id' => 44, 'city' => 'Jbsa Randolph'],
                ['state_id' => 44, 'city' => 'Saint Hedwig'],
                ['state_id' => 44, 'city' => 'San Antonio'],
                ['state_id' => 44, 'city' => 'Jbsa Ft Sam Houston'],
                ['state_id' => 44, 'city' => 'Jbsa Lackland'],
                ['state_id' => 44, 'city' => 'Blanco'],
                ['state_id' => 44, 'city' => 'Hye'],
                ['state_id' => 44, 'city' => 'Johnson City'],
                ['state_id' => 44, 'city' => 'Round Mountain'],
                ['state_id' => 44, 'city' => 'Gail'],
                ['state_id' => 44, 'city' => 'Clifton'],
                ['state_id' => 44, 'city' => 'Cranfills Gap'],
                ['state_id' => 44, 'city' => 'Laguna Park'],
                ['state_id' => 44, 'city' => 'Iredell'],
                ['state_id' => 44, 'city' => 'Kopperl'],
                ['state_id' => 44, 'city' => 'Meridian'],
                ['state_id' => 44, 'city' => 'Morgan'],
                ['state_id' => 44, 'city' => 'Valley Mills'],
                ['state_id' => 44, 'city' => 'Walnut Springs'],
                ['state_id' => 44, 'city' => 'Texarkana'],
                ['state_id' => 44, 'city' => 'De Kalb'],
                ['state_id' => 44, 'city' => 'Hooks'],
                ['state_id' => 44, 'city' => 'Maud'],
                ['state_id' => 44, 'city' => 'Nash'],
                ['state_id' => 44, 'city' => 'New Boston'],
                ['state_id' => 44, 'city' => 'Redwater'],
                ['state_id' => 44, 'city' => 'Simms'],
                ['state_id' => 44, 'city' => 'Brazoria'],
                ['state_id' => 44, 'city' => 'Damon'],
                ['state_id' => 44, 'city' => 'Danciger'],
                ['state_id' => 44, 'city' => 'Old Ocean'],
                ['state_id' => 44, 'city' => 'Sweeny'],
                ['state_id' => 44, 'city' => 'West Columbia'],
                ['state_id' => 44, 'city' => 'Alvin'],
                ['state_id' => 44, 'city' => 'Angleton'],
                ['state_id' => 44, 'city' => 'Clute'],
                ['state_id' => 44, 'city' => 'Danbury'],
                ['state_id' => 44, 'city' => 'Freeport'],
                ['state_id' => 44, 'city' => 'Lake Jackson'],
                ['state_id' => 44, 'city' => 'Liverpool'],
                ['state_id' => 44, 'city' => 'Manvel'],
                ['state_id' => 44, 'city' => 'Pearland'],
                ['state_id' => 44, 'city' => 'Rosharon'],
                ['state_id' => 44, 'city' => 'Bryan'],
                ['state_id' => 44, 'city' => 'College Station'],
                ['state_id' => 44, 'city' => 'Kurten'],
                ['state_id' => 44, 'city' => 'Millican'],
                ['state_id' => 44, 'city' => 'Wellborn'],
                ['state_id' => 44, 'city' => 'Alpine'],
                ['state_id' => 44, 'city' => 'Big Bend National Park'],
                ['state_id' => 44, 'city' => 'Marathon'],
                ['state_id' => 44, 'city' => 'Terlingua'],
                ['state_id' => 44, 'city' => 'Quitaque'],
                ['state_id' => 44, 'city' => 'Silverton'],
                ['state_id' => 44, 'city' => 'Encino'],
                ['state_id' => 44, 'city' => 'Falfurrias'],
                ['state_id' => 44, 'city' => 'Blanket'],
                ['state_id' => 44, 'city' => 'Brownwood'],
                ['state_id' => 44, 'city' => 'Early'],
                ['state_id' => 44, 'city' => 'Bangs'],
                ['state_id' => 44, 'city' => 'Brookesmith'],
                ['state_id' => 44, 'city' => 'May'],
                ['state_id' => 44, 'city' => 'Zephyr'],
                ['state_id' => 44, 'city' => 'Caldwell'],
                ['state_id' => 44, 'city' => 'Chriesman'],
                ['state_id' => 44, 'city' => 'Deanville'],
                ['state_id' => 44, 'city' => 'Lyons'],
                ['state_id' => 44, 'city' => 'Snook'],
                ['state_id' => 44, 'city' => 'Somerville'],
                ['state_id' => 44, 'city' => 'Bertram'],
                ['state_id' => 44, 'city' => 'Briggs'],
                ['state_id' => 44, 'city' => 'Burnet'],
                ['state_id' => 44, 'city' => 'Marble Falls'],
                ['state_id' => 44, 'city' => 'Dale'],
                ['state_id' => 44, 'city' => 'Fentress'],
                ['state_id' => 44, 'city' => 'Lockhart'],
                ['state_id' => 44, 'city' => 'Luling'],
                ['state_id' => 44, 'city' => 'Martindale'],
                ['state_id' => 44, 'city' => 'Maxwell'],
                ['state_id' => 44, 'city' => 'Prairie Lea'],
                ['state_id' => 44, 'city' => 'Point Comfort'],
                ['state_id' => 44, 'city' => 'Port Lavaca'],
                ['state_id' => 44, 'city' => 'Port O Connor'],
                ['state_id' => 44, 'city' => 'Seadrift'],
                ['state_id' => 44, 'city' => 'Cross Plains'],
                ['state_id' => 44, 'city' => 'Putnam'],
                ['state_id' => 44, 'city' => 'Baird'],
                ['state_id' => 44, 'city' => 'Clyde'],
                ['state_id' => 44, 'city' => 'Brownsville'],
                ['state_id' => 44, 'city' => 'Combes'],
                ['state_id' => 44, 'city' => 'Harlingen'],
                ['state_id' => 44, 'city' => 'La Feria'],
                ['state_id' => 44, 'city' => 'Los Fresnos'],
                ['state_id' => 44, 'city' => 'Los Indios'],
                ['state_id' => 44, 'city' => 'Lozano'],
                ['state_id' => 44, 'city' => 'Olmito'],
                ['state_id' => 44, 'city' => 'Port Isabel'],
                ['state_id' => 44, 'city' => 'Rio Hondo'],
                ['state_id' => 44, 'city' => 'San Benito'],
                ['state_id' => 44, 'city' => 'Santa Maria'],
                ['state_id' => 44, 'city' => 'Santa Rosa'],
                ['state_id' => 44, 'city' => 'South Padre Island'],
                ['state_id' => 44, 'city' => 'Leesburg'],
                ['state_id' => 44, 'city' => 'Pittsburg'],
                ['state_id' => 44, 'city' => 'Groom'],
                ['state_id' => 44, 'city' => 'Panhandle'],
                ['state_id' => 44, 'city' => 'Skellytown'],
                ['state_id' => 44, 'city' => 'White Deer'],
                ['state_id' => 44, 'city' => 'Atlanta'],
                ['state_id' => 44, 'city' => 'Bivins'],
                ['state_id' => 44, 'city' => 'Bloomburg'],
                ['state_id' => 44, 'city' => 'Douglassville'],
                ['state_id' => 44, 'city' => 'Kildare'],
                ['state_id' => 44, 'city' => 'Linden'],
                ['state_id' => 44, 'city' => 'Mc Leod'],
                ['state_id' => 44, 'city' => 'Marietta'],
                ['state_id' => 44, 'city' => 'Queen City'],
                ['state_id' => 44, 'city' => 'Avinger'],
                ['state_id' => 44, 'city' => 'Hughes Springs'],
                ['state_id' => 44, 'city' => 'Dimmitt'],
                ['state_id' => 44, 'city' => 'Hart'],
                ['state_id' => 44, 'city' => 'Nazareth'],
                ['state_id' => 44, 'city' => 'Summerfield'],
                ['state_id' => 44, 'city' => 'Anahuac'],
                ['state_id' => 44, 'city' => 'Baytown'],
                ['state_id' => 44, 'city' => 'Hankamer'],
                ['state_id' => 44, 'city' => 'Mont Belvieu'],
                ['state_id' => 44, 'city' => 'Wallisville'],
                ['state_id' => 44, 'city' => 'Stowell'],
                ['state_id' => 44, 'city' => 'Winnie'],
                ['state_id' => 44, 'city' => 'Cuney'],
                ['state_id' => 44, 'city' => 'Gallatin'],
                ['state_id' => 44, 'city' => 'Jacksonville'],
                ['state_id' => 44, 'city' => 'Maydelle'],
                ['state_id' => 44, 'city' => 'New Summerfield'],
                ['state_id' => 44, 'city' => 'Reklaw'],
                ['state_id' => 44, 'city' => 'Rusk'],
                ['state_id' => 44, 'city' => 'Alto'],
                ['state_id' => 44, 'city' => 'Wells'],
                ['state_id' => 44, 'city' => 'Childress'],
                ['state_id' => 44, 'city' => 'Tell'],
                ['state_id' => 44, 'city' => 'Bellevue'],
                ['state_id' => 44, 'city' => 'Bluegrove'],
                ['state_id' => 44, 'city' => 'Byers'],
                ['state_id' => 44, 'city' => 'Henrietta'],
                ['state_id' => 44, 'city' => 'Petrolia'],
                ['state_id' => 44, 'city' => 'Bledsoe'],
                ['state_id' => 44, 'city' => 'Morton'],
                ['state_id' => 44, 'city' => 'Whiteface'],
                ['state_id' => 44, 'city' => 'Bronte'],
                ['state_id' => 44, 'city' => 'Robert Lee'],
                ['state_id' => 44, 'city' => 'Silver'],
                ['state_id' => 44, 'city' => 'Tennyson'],
                ['state_id' => 44, 'city' => 'Burkett'],
                ['state_id' => 44, 'city' => 'Coleman'],
                ['state_id' => 44, 'city' => 'Gouldbusk'],
                ['state_id' => 44, 'city' => 'Rockwood'],
                ['state_id' => 44, 'city' => 'Santa Anna'],
                ['state_id' => 44, 'city' => 'Talpa'],
                ['state_id' => 44, 'city' => 'Valera'],
                ['state_id' => 44, 'city' => 'Voss'],
                ['state_id' => 44, 'city' => 'Goldsboro'],
                ['state_id' => 44, 'city' => 'Novice'],
                ['state_id' => 44, 'city' => 'Allen'],
                ['state_id' => 44, 'city' => 'Celina'],
                ['state_id' => 44, 'city' => 'Plano'],
                ['state_id' => 44, 'city' => 'Frisco'],
                ['state_id' => 44, 'city' => 'Mckinney'],
                ['state_id' => 44, 'city' => 'Prosper'],
                ['state_id' => 44, 'city' => 'Weston'],
                ['state_id' => 44, 'city' => 'Copeville'],
                ['state_id' => 44, 'city' => 'Josephine'],
                ['state_id' => 44, 'city' => 'Lavon'],
                ['state_id' => 44, 'city' => 'Nevada'],
                ['state_id' => 44, 'city' => 'Princeton'],
                ['state_id' => 44, 'city' => 'Anna'],
                ['state_id' => 44, 'city' => 'Blue Ridge'],
                ['state_id' => 44, 'city' => 'Farmersville'],
                ['state_id' => 44, 'city' => 'Melissa'],
                ['state_id' => 44, 'city' => 'Westminster'],
                ['state_id' => 44, 'city' => 'Samnorwood'],
                ['state_id' => 44, 'city' => 'Wellington'],
                ['state_id' => 44, 'city' => 'Dodson'],
                ['state_id' => 44, 'city' => 'Quail'],
                ['state_id' => 44, 'city' => 'Altair'],
                ['state_id' => 44, 'city' => 'Eagle Lake'],
                ['state_id' => 44, 'city' => 'Garwood'],
                ['state_id' => 44, 'city' => 'Nada'],
                ['state_id' => 44, 'city' => 'Rock Island'],
                ['state_id' => 44, 'city' => 'Sheridan'],
                ['state_id' => 44, 'city' => 'Columbus'],
                ['state_id' => 44, 'city' => 'Alleyton'],
                ['state_id' => 44, 'city' => 'Glidden'],
                ['state_id' => 44, 'city' => 'Oakland'],
                ['state_id' => 44, 'city' => 'Weimar'],
                ['state_id' => 44, 'city' => 'Spring Branch'],
                ['state_id' => 44, 'city' => 'New Braunfels'],
                ['state_id' => 44, 'city' => 'Canyon Lake'],
                ['state_id' => 44, 'city' => 'Bulverde'],
                ['state_id' => 44, 'city' => 'Fischer'],
                ['state_id' => 44, 'city' => 'Comanche'],
                ['state_id' => 44, 'city' => 'De Leon'],
                ['state_id' => 44, 'city' => 'Energy'],
                ['state_id' => 44, 'city' => 'Gustine'],
                ['state_id' => 44, 'city' => 'Proctor'],
                ['state_id' => 44, 'city' => 'Sidney'],
                ['state_id' => 44, 'city' => 'Eden'],
                ['state_id' => 44, 'city' => 'Lowake'],
                ['state_id' => 44, 'city' => 'Millersview'],
                ['state_id' => 44, 'city' => 'Paint Rock'],
                ['state_id' => 44, 'city' => 'Eola'],
                ['state_id' => 44, 'city' => 'Era'],
                ['state_id' => 44, 'city' => 'Gainesville'],
                ['state_id' => 44, 'city' => 'Lindsay'],
                ['state_id' => 44, 'city' => 'Muenster'],
                ['state_id' => 44, 'city' => 'Myra'],
                ['state_id' => 44, 'city' => 'Rosston'],
                ['state_id' => 44, 'city' => 'Valley View'],
                ['state_id' => 44, 'city' => 'Copperas Cove'],
                ['state_id' => 44, 'city' => 'Evant'],
                ['state_id' => 44, 'city' => 'Flat'],
                ['state_id' => 44, 'city' => 'Gatesville'],
                ['state_id' => 44, 'city' => 'Jonesboro'],
                ['state_id' => 44, 'city' => 'Mound'],
                ['state_id' => 44, 'city' => 'Oglesby'],
                ['state_id' => 44, 'city' => 'Purmela'],
                ['state_id' => 44, 'city' => 'Cee Vee'],
                ['state_id' => 44, 'city' => 'Paducah'],
                ['state_id' => 44, 'city' => 'Crane'],
                ['state_id' => 44, 'city' => 'Ozona'],
                ['state_id' => 44, 'city' => 'Crosbyton'],
                ['state_id' => 44, 'city' => 'Lorenzo'],
                ['state_id' => 44, 'city' => 'Ralls'],
                ['state_id' => 44, 'city' => 'Van Horn'],
                ['state_id' => 44, 'city' => 'Dalhart'],
                ['state_id' => 44, 'city' => 'Kerrick'],
                ['state_id' => 44, 'city' => 'Texline'],
                ['state_id' => 44, 'city' => 'Addison'],
                ['state_id' => 44, 'city' => 'Carrollton'],
                ['state_id' => 44, 'city' => 'Irving'],
                ['state_id' => 44, 'city' => 'Coppell'],
                ['state_id' => 44, 'city' => 'Rowlett'],
                ['state_id' => 44, 'city' => 'Garland'],
                ['state_id' => 44, 'city' => 'Sachse'],
                ['state_id' => 44, 'city' => 'Grand Prairie'],
                ['state_id' => 44, 'city' => 'Richardson'],
                ['state_id' => 44, 'city' => 'Wylie'],
                ['state_id' => 44, 'city' => 'Cedar Hill'],
                ['state_id' => 44, 'city' => 'Desoto'],
                ['state_id' => 44, 'city' => 'Duncanville'],
                ['state_id' => 44, 'city' => 'Lancaster'],
                ['state_id' => 44, 'city' => 'Hutchins'],
                ['state_id' => 44, 'city' => 'Mesquite'],
                ['state_id' => 44, 'city' => 'Seagoville'],
                ['state_id' => 44, 'city' => 'Wilmer'],
                ['state_id' => 44, 'city' => 'Balch Springs'],
                ['state_id' => 44, 'city' => 'Sunnyvale'],
                ['state_id' => 44, 'city' => 'Dallas'],
                ['state_id' => 44, 'city' => 'Lamesa'],
                ['state_id' => 44, 'city' => 'Welch'],
                ['state_id' => 44, 'city' => 'Ackerly'],
                ['state_id' => 44, 'city' => 'Dawn'],
                ['state_id' => 44, 'city' => 'Hereford'],
                ['state_id' => 44, 'city' => 'Ben Franklin'],
                ['state_id' => 44, 'city' => 'Cooper'],
                ['state_id' => 44, 'city' => 'Enloe'],
                ['state_id' => 44, 'city' => 'Klondike'],
                ['state_id' => 44, 'city' => 'Lake Creek'],
                ['state_id' => 44, 'city' => 'Pecan Gap'],
                ['state_id' => 44, 'city' => 'Flower Mound'],
                ['state_id' => 44, 'city' => 'Lewisville'],
                ['state_id' => 44, 'city' => 'The Colony'],
                ['state_id' => 44, 'city' => 'Lake Dallas'],
                ['state_id' => 44, 'city' => 'Little Elm'],
                ['state_id' => 44, 'city' => 'Denton'],
                ['state_id' => 44, 'city' => 'Argyle'],
                ['state_id' => 44, 'city' => 'Aubrey'],
                ['state_id' => 44, 'city' => 'Justin'],
                ['state_id' => 44, 'city' => 'Krum'],
                ['state_id' => 44, 'city' => 'Pilot Point'],
                ['state_id' => 44, 'city' => 'Ponder'],
                ['state_id' => 44, 'city' => 'Roanoke'],
                ['state_id' => 44, 'city' => 'Sanger'],
                ['state_id' => 44, 'city' => 'Cuero'],
                ['state_id' => 44, 'city' => 'Hochheim'],
                ['state_id' => 44, 'city' => 'Meyersville'],
                ['state_id' => 44, 'city' => 'Thomaston'],
                ['state_id' => 44, 'city' => 'Westhoff'],
                ['state_id' => 44, 'city' => 'Nordheim'],
                ['state_id' => 44, 'city' => 'Yorktown'],
                ['state_id' => 44, 'city' => 'Afton'],
                ['state_id' => 44, 'city' => 'Dickens'],
                ['state_id' => 44, 'city' => 'Mcadoo'],
                ['state_id' => 44, 'city' => 'Spur'],
                ['state_id' => 44, 'city' => 'Asherton'],
                ['state_id' => 44, 'city' => 'Big Wells'],
                ['state_id' => 44, 'city' => 'Carrizo Springs'],
                ['state_id' => 44, 'city' => 'Catarina'],
                ['state_id' => 44, 'city' => 'Clarendon'],
                ['state_id' => 44, 'city' => 'Hedley'],
                ['state_id' => 44, 'city' => 'Lelia Lake'],
                ['state_id' => 44, 'city' => 'Benavides'],
                ['state_id' => 44, 'city' => 'Concepcion'],
                ['state_id' => 44, 'city' => 'Freer'],
                ['state_id' => 44, 'city' => 'Realitos'],
                ['state_id' => 44, 'city' => 'San Diego'],
                ['state_id' => 44, 'city' => 'Carbon'],
                ['state_id' => 44, 'city' => 'Cisco'],
                ['state_id' => 44, 'city' => 'Desdemona'],
                ['state_id' => 44, 'city' => 'Eastland'],
                ['state_id' => 44, 'city' => 'Gorman'],
                ['state_id' => 44, 'city' => 'Olden'],
                ['state_id' => 44, 'city' => 'Ranger'],
                ['state_id' => 44, 'city' => 'Rising Star'],
                ['state_id' => 44, 'city' => 'Goldsmith'],
                ['state_id' => 44, 'city' => 'Gardendale'],
                ['state_id' => 44, 'city' => 'Notrees'],
                ['state_id' => 44, 'city' => 'Odessa'],
                ['state_id' => 44, 'city' => 'Penwell'],
                ['state_id' => 44, 'city' => 'Telegraph'],
                ['state_id' => 44, 'city' => 'Barksdale'],
                ['state_id' => 44, 'city' => 'Rocksprings'],
                ['state_id' => 44, 'city' => 'Bardwell'],
                ['state_id' => 44, 'city' => 'Ennis'],
                ['state_id' => 44, 'city' => 'Ferris'],
                ['state_id' => 44, 'city' => 'Palmer'],
                ['state_id' => 44, 'city' => 'Red Oak'],
                ['state_id' => 44, 'city' => 'Rice'],
                ['state_id' => 44, 'city' => 'Waxahachie'],
                ['state_id' => 44, 'city' => 'Forreston'],
                ['state_id' => 44, 'city' => 'Maypearl'],
                ['state_id' => 44, 'city' => 'Midlothian'],
                ['state_id' => 44, 'city' => 'Avalon'],
                ['state_id' => 44, 'city' => 'Italy'],
                ['state_id' => 44, 'city' => 'Milford'],
                ['state_id' => 44, 'city' => 'Anthony'],
                ['state_id' => 44, 'city' => 'Canutillo'],
                ['state_id' => 44, 'city' => 'Clint'],
                ['state_id' => 44, 'city' => 'Fabens'],
                ['state_id' => 44, 'city' => 'San Elizario'],
                ['state_id' => 44, 'city' => 'Tornillo'],
                ['state_id' => 44, 'city' => 'El Paso'],
                ['state_id' => 44, 'city' => 'Fort Bliss'],
                ['state_id' => 44, 'city' => 'Stephenville'],
                ['state_id' => 44, 'city' => 'Bluff Dale'],
                ['state_id' => 44, 'city' => 'Dublin'],
                ['state_id' => 44, 'city' => 'Lingleville'],
                ['state_id' => 44, 'city' => 'Morgan Mill'],
                ['state_id' => 44, 'city' => 'Rosebud'],
                ['state_id' => 44, 'city' => 'Chilton'],
                ['state_id' => 44, 'city' => 'Lott'],
                ['state_id' => 44, 'city' => 'Marlin'],
                ['state_id' => 44, 'city' => 'Reagan'],
                ['state_id' => 44, 'city' => 'Satin'],
                ['state_id' => 44, 'city' => 'Bailey'],
                ['state_id' => 44, 'city' => 'Bonham'],
                ['state_id' => 44, 'city' => 'Dodd City'],
                ['state_id' => 44, 'city' => 'Ector'],
                ['state_id' => 44, 'city' => 'Gober'],
                ['state_id' => 44, 'city' => 'Honey Grove'],
                ['state_id' => 44, 'city' => 'Ivanhoe'],
                ['state_id' => 44, 'city' => 'Ladonia'],
                ['state_id' => 44, 'city' => 'Leonard'],
                ['state_id' => 44, 'city' => 'Randolph'],
                ['state_id' => 44, 'city' => 'Ravenna'],
                ['state_id' => 44, 'city' => 'Savoy'],
                ['state_id' => 44, 'city' => 'Telephone'],
                ['state_id' => 44, 'city' => 'Trenton'],
                ['state_id' => 44, 'city' => 'Windom'],
                ['state_id' => 44, 'city' => 'Carmine'],
                ['state_id' => 44, 'city' => 'Ellinger'],
                ['state_id' => 44, 'city' => 'Fayetteville'],
                ['state_id' => 44, 'city' => 'Flatonia'],
                ['state_id' => 44, 'city' => 'La Grange'],
                ['state_id' => 44, 'city' => 'Ledbetter'],
                ['state_id' => 44, 'city' => 'Muldoon'],
                ['state_id' => 44, 'city' => 'Plum'],
                ['state_id' => 44, 'city' => 'Round Top'],
                ['state_id' => 44, 'city' => 'Schulenburg'],
                ['state_id' => 44, 'city' => 'Warda'],
                ['state_id' => 44, 'city' => 'West Point'],
                ['state_id' => 44, 'city' => 'Mc Caulley'],
                ['state_id' => 44, 'city' => 'Roby'],
                ['state_id' => 44, 'city' => 'Rotan'],
                ['state_id' => 44, 'city' => 'Sylvester'],
                ['state_id' => 44, 'city' => 'Aiken'],
                ['state_id' => 44, 'city' => 'Dougherty'],
                ['state_id' => 44, 'city' => 'Floydada'],
                ['state_id' => 44, 'city' => 'Lockney'],
                ['state_id' => 44, 'city' => 'South Plains'],
                ['state_id' => 44, 'city' => 'Crowell'],
                ['state_id' => 44, 'city' => 'Richmond'],
                ['state_id' => 44, 'city' => 'Beasley'],
                ['state_id' => 44, 'city' => 'Fulshear'],
                ['state_id' => 44, 'city' => 'Guy'],
                ['state_id' => 44, 'city' => 'Kendleton'],
                ['state_id' => 44, 'city' => 'Missouri City'],
                ['state_id' => 44, 'city' => 'Needville'],
                ['state_id' => 44, 'city' => 'Orchard'],
                ['state_id' => 44, 'city' => 'Rosenberg'],
                ['state_id' => 44, 'city' => 'Simonton'],
                ['state_id' => 44, 'city' => 'Stafford'],
                ['state_id' => 44, 'city' => 'Sugar Land'],
                ['state_id' => 44, 'city' => 'Thompsons'],
                ['state_id' => 44, 'city' => 'Fresno'],
                ['state_id' => 44, 'city' => 'Mount Vernon'],
                ['state_id' => 44, 'city' => 'Scroggins'],
                ['state_id' => 44, 'city' => 'Talco'],
                ['state_id' => 44, 'city' => 'Donie'],
                ['state_id' => 44, 'city' => 'Fairfield'],
                ['state_id' => 44, 'city' => 'Kirvin'],
                ['state_id' => 44, 'city' => 'Streetman'],
                ['state_id' => 44, 'city' => 'Teague'],
                ['state_id' => 44, 'city' => 'Wortham'],
                ['state_id' => 44, 'city' => 'Bigfoot'],
                ['state_id' => 44, 'city' => 'Dilley'],
                ['state_id' => 44, 'city' => 'Moore'],
                ['state_id' => 44, 'city' => 'Pearsall'],
                ['state_id' => 44, 'city' => 'Loop'],
                ['state_id' => 44, 'city' => 'Seagraves'],
                ['state_id' => 44, 'city' => 'Seminole'],
                ['state_id' => 44, 'city' => 'Santa Fe'],
                ['state_id' => 44, 'city' => 'Bacliff'],
                ['state_id' => 44, 'city' => 'Dickinson'],
                ['state_id' => 44, 'city' => 'Friendswood'],
                ['state_id' => 44, 'city' => 'Galveston'],
                ['state_id' => 44, 'city' => 'Hitchcock'],
                ['state_id' => 44, 'city' => 'Kemah'],
                ['state_id' => 44, 'city' => 'La Marque'],
                ['state_id' => 44, 'city' => 'League City'],
                ['state_id' => 44, 'city' => 'Texas City'],
                ['state_id' => 44, 'city' => 'Gilchrist'],
                ['state_id' => 44, 'city' => 'High Island'],
                ['state_id' => 44, 'city' => 'Port Bolivar'],
                ['state_id' => 44, 'city' => 'Justiceburg'],
                ['state_id' => 44, 'city' => 'Post'],
                ['state_id' => 44, 'city' => 'Doss'],
                ['state_id' => 44, 'city' => 'Fredericksburg'],
                ['state_id' => 44, 'city' => 'Harper'],
                ['state_id' => 44, 'city' => 'Stonewall'],
                ['state_id' => 44, 'city' => 'Willow City'],
                ['state_id' => 44, 'city' => 'Garden City'],
                ['state_id' => 44, 'city' => 'Fannin'],
                ['state_id' => 44, 'city' => 'Goliad'],
                ['state_id' => 44, 'city' => 'Weesatche'],
                ['state_id' => 44, 'city' => 'Berclair'],
                ['state_id' => 44, 'city' => 'Leesville'],
                ['state_id' => 44, 'city' => 'Nixon'],
                ['state_id' => 44, 'city' => 'Smiley'],
                ['state_id' => 44, 'city' => 'Belmont'],
                ['state_id' => 44, 'city' => 'Cost'],
                ['state_id' => 44, 'city' => 'Gonzales'],
                ['state_id' => 44, 'city' => 'Harwood'],
                ['state_id' => 44, 'city' => 'Ottine'],
                ['state_id' => 44, 'city' => 'Wrightsboro'],
                ['state_id' => 44, 'city' => 'Waelder'],
                ['state_id' => 44, 'city' => 'Alanreed'],
                ['state_id' => 44, 'city' => 'Lefors'],
                ['state_id' => 44, 'city' => 'Mclean'],
                ['state_id' => 44, 'city' => 'Pampa'],
                ['state_id' => 44, 'city' => 'Denison'],
                ['state_id' => 44, 'city' => 'Gunter'],
                ['state_id' => 44, 'city' => 'Pottsboro'],
                ['state_id' => 44, 'city' => 'Sherman'],
                ['state_id' => 44, 'city' => 'Bells'],
                ['state_id' => 44, 'city' => 'Howe'],
                ['state_id' => 44, 'city' => 'Tom Bean'],
                ['state_id' => 44, 'city' => 'Whitewright'],
                ['state_id' => 44, 'city' => 'Van Alstyne'],
                ['state_id' => 44, 'city' => 'Collinsville'],
                ['state_id' => 44, 'city' => 'Gordonville'],
                ['state_id' => 44, 'city' => 'Sadler'],
                ['state_id' => 44, 'city' => 'Southmayd'],
                ['state_id' => 44, 'city' => 'Tioga'],
                ['state_id' => 44, 'city' => 'Whitesboro'],
                ['state_id' => 44, 'city' => 'Longview'],
                ['state_id' => 44, 'city' => 'Easton'],
                ['state_id' => 44, 'city' => 'Gladewater'],
                ['state_id' => 44, 'city' => 'Judson'],
                ['state_id' => 44, 'city' => 'Kilgore'],
                ['state_id' => 44, 'city' => 'White Oak'],
                ['state_id' => 44, 'city' => 'Plantersville'],
                ['state_id' => 44, 'city' => 'Anderson'],
                ['state_id' => 44, 'city' => 'Bedias'],
                ['state_id' => 44, 'city' => 'Iola'],
                ['state_id' => 44, 'city' => 'Navasota'],
                ['state_id' => 44, 'city' => 'Richards'],
                ['state_id' => 44, 'city' => 'Roans Prairie'],
                ['state_id' => 44, 'city' => 'Shiro'],
                ['state_id' => 44, 'city' => 'Cibolo'],
                ['state_id' => 44, 'city' => 'Geronimo'],
                ['state_id' => 44, 'city' => 'Mc Queeney'],
                ['state_id' => 44, 'city' => 'Marion'],
                ['state_id' => 44, 'city' => 'Schertz'],
                ['state_id' => 44, 'city' => 'Seguin'],
                ['state_id' => 44, 'city' => 'Kingsbury'],
                ['state_id' => 44, 'city' => 'Staples'],
                ['state_id' => 44, 'city' => 'Cotton Center'],
                ['state_id' => 44, 'city' => 'Edmonson'],
                ['state_id' => 44, 'city' => 'Hale Center'],
                ['state_id' => 44, 'city' => 'Plainview'],
                ['state_id' => 44, 'city' => 'Petersburg'],
                ['state_id' => 44, 'city' => 'Abernathy'],
                ['state_id' => 44, 'city' => 'Estelline'],
                ['state_id' => 44, 'city' => 'Lakeview'],
                ['state_id' => 44, 'city' => 'Memphis'],
                ['state_id' => 44, 'city' => 'Turkey'],
                ['state_id' => 44, 'city' => 'Carlton'],
                ['state_id' => 44, 'city' => 'Hico'],
                ['state_id' => 44, 'city' => 'Hamilton'],
                ['state_id' => 44, 'city' => 'Pottsville'],
                ['state_id' => 44, 'city' => 'Gruver'],
                ['state_id' => 44, 'city' => 'Morse'],
                ['state_id' => 44, 'city' => 'Spearman'],
                ['state_id' => 44, 'city' => 'Chillicothe'],
                ['state_id' => 44, 'city' => 'Quanah'],
                ['state_id' => 44, 'city' => 'Thicket'],
                ['state_id' => 44, 'city' => 'Votaw'],
                ['state_id' => 44, 'city' => 'Batson'],
                ['state_id' => 44, 'city' => 'Saratoga'],
                ['state_id' => 44, 'city' => 'Kountze'],
                ['state_id' => 44, 'city' => 'Silsbee'],
                ['state_id' => 44, 'city' => 'Lumberton'],
                ['state_id' => 44, 'city' => 'Sour Lake'],
                ['state_id' => 44, 'city' => 'Village Mills'],
                ['state_id' => 44, 'city' => 'Houston'],
                ['state_id' => 44, 'city' => 'North Houston'],
                ['state_id' => 44, 'city' => 'Kingwood'],
                ['state_id' => 44, 'city' => 'Huffman'],
                ['state_id' => 44, 'city' => 'Hufsmith'],
                ['state_id' => 44, 'city' => 'Humble'],
                ['state_id' => 44, 'city' => 'Spring'],
                ['state_id' => 44, 'city' => 'Tomball'],
                ['state_id' => 44, 'city' => 'Bellaire'],
                ['state_id' => 44, 'city' => 'Cypress'],
                ['state_id' => 44, 'city' => 'Alief'],
                ['state_id' => 44, 'city' => 'Barker'],
                ['state_id' => 44, 'city' => 'Hockley'],
                ['state_id' => 44, 'city' => 'Katy'],
                ['state_id' => 44, 'city' => 'Pasadena'],
                ['state_id' => 44, 'city' => 'Channelview'],
                ['state_id' => 44, 'city' => 'Crosby'],
                ['state_id' => 44, 'city' => 'Deer Park'],
                ['state_id' => 44, 'city' => 'Galena Park'],
                ['state_id' => 44, 'city' => 'Highlands'],
                ['state_id' => 44, 'city' => 'La Porte'],
                ['state_id' => 44, 'city' => 'Seabrook'],
                ['state_id' => 44, 'city' => 'South Houston'],
                ['state_id' => 44, 'city' => 'Webster'],
                ['state_id' => 44, 'city' => 'Elysian Fields'],
                ['state_id' => 44, 'city' => 'Hallsville'],
                ['state_id' => 44, 'city' => 'Harleton'],
                ['state_id' => 44, 'city' => 'Jonesville'],
                ['state_id' => 44, 'city' => 'Karnack'],
                ['state_id' => 44, 'city' => 'Marshall'],
                ['state_id' => 44, 'city' => 'Scottsville'],
                ['state_id' => 44, 'city' => 'Waskom'],
                ['state_id' => 44, 'city' => 'Woodlawn'],
                ['state_id' => 44, 'city' => 'Channing'],
                ['state_id' => 44, 'city' => 'Hartley'],
                ['state_id' => 44, 'city' => 'Weinert'],
                ['state_id' => 44, 'city' => 'Haskell'],
                ['state_id' => 44, 'city' => 'O Brien'],
                ['state_id' => 44, 'city' => 'Rochester'],
                ['state_id' => 44, 'city' => 'Rule'],
                ['state_id' => 44, 'city' => 'Buda'],
                ['state_id' => 44, 'city' => 'Driftwood'],
                ['state_id' => 44, 'city' => 'Dripping Springs'],
                ['state_id' => 44, 'city' => 'Kyle'],
                ['state_id' => 44, 'city' => 'San Marcos'],
                ['state_id' => 44, 'city' => 'Wimberley'],
                ['state_id' => 44, 'city' => 'Canadian'],
                ['state_id' => 44, 'city' => 'Eustace'],
                ['state_id' => 44, 'city' => 'Kemp'],
                ['state_id' => 44, 'city' => 'Malakoff'],
                ['state_id' => 44, 'city' => 'Trinidad'],
                ['state_id' => 44, 'city' => 'Athens'],
                ['state_id' => 44, 'city' => 'Brownsboro'],
                ['state_id' => 44, 'city' => 'Chandler'],
                ['state_id' => 44, 'city' => 'Larue'],
                ['state_id' => 44, 'city' => 'Murchison'],
                ['state_id' => 44, 'city' => 'Poynor'],
                ['state_id' => 44, 'city' => 'Mcallen'],
                ['state_id' => 44, 'city' => 'Alamo'],
                ['state_id' => 44, 'city' => 'Donna'],
                ['state_id' => 44, 'city' => 'Edcouch'],
                ['state_id' => 44, 'city' => 'Edinburg'],
                ['state_id' => 44, 'city' => 'Elsa'],
                ['state_id' => 44, 'city' => 'Hargill'],
                ['state_id' => 44, 'city' => 'Hidalgo'],
                ['state_id' => 44, 'city' => 'La Blanca'],
                ['state_id' => 44, 'city' => 'La Joya'],
                ['state_id' => 44, 'city' => 'La Villa'],
                ['state_id' => 44, 'city' => 'Linn'],
                ['state_id' => 44, 'city' => 'Los Ebanos'],
                ['state_id' => 44, 'city' => 'Mercedes'],
                ['state_id' => 44, 'city' => 'Mission'],
                ['state_id' => 44, 'city' => 'Penitas'],
                ['state_id' => 44, 'city' => 'Pharr'],
                ['state_id' => 44, 'city' => 'Progreso'],
                ['state_id' => 44, 'city' => 'San Juan'],
                ['state_id' => 44, 'city' => 'Sullivan City'],
                ['state_id' => 44, 'city' => 'Weslaco'],
                ['state_id' => 44, 'city' => 'Itasca'],
                ['state_id' => 44, 'city' => 'Abbott'],
                ['state_id' => 44, 'city' => 'Aquilla'],
                ['state_id' => 44, 'city' => 'Blum'],
                ['state_id' => 44, 'city' => 'Brandon'],
                ['state_id' => 44, 'city' => 'Bynum'],
                ['state_id' => 44, 'city' => 'Covington'],
                ['state_id' => 44, 'city' => 'Hillsboro'],
                ['state_id' => 44, 'city' => 'Hubbard'],
                ['state_id' => 44, 'city' => 'Irene'],
                ['state_id' => 44, 'city' => 'Malone'],
                ['state_id' => 44, 'city' => 'Mertens'],
                ['state_id' => 44, 'city' => 'Mount Calm'],
                ['state_id' => 44, 'city' => 'Penelope'],
                ['state_id' => 44, 'city' => 'Whitney'],
                ['state_id' => 44, 'city' => 'Anton'],
                ['state_id' => 44, 'city' => 'Levelland'],
                ['state_id' => 44, 'city' => 'Pep'],
                ['state_id' => 44, 'city' => 'Ropesville'],
                ['state_id' => 44, 'city' => 'Smyer'],
                ['state_id' => 44, 'city' => 'Sundown'],
                ['state_id' => 44, 'city' => 'Whitharral'],
                ['state_id' => 44, 'city' => 'Cresson'],
                ['state_id' => 44, 'city' => 'Granbury'],
                ['state_id' => 44, 'city' => 'Lipan'],
                ['state_id' => 44, 'city' => 'Paluxy'],
                ['state_id' => 44, 'city' => 'Tolar'],
                ['state_id' => 44, 'city' => 'Brashear'],
                ['state_id' => 44, 'city' => 'Como'],
                ['state_id' => 44, 'city' => 'Cumby'],
                ['state_id' => 44, 'city' => 'Dike'],
                ['state_id' => 44, 'city' => 'Pickton'],
                ['state_id' => 44, 'city' => 'Saltillo'],
                ['state_id' => 44, 'city' => 'Sulphur Bluff'],
                ['state_id' => 44, 'city' => 'Sulphur Springs'],
                ['state_id' => 44, 'city' => 'Crockett'],
                ['state_id' => 44, 'city' => 'Grapeland'],
                ['state_id' => 44, 'city' => 'Kennard'],
                ['state_id' => 44, 'city' => 'Latexo'],
                ['state_id' => 44, 'city' => 'Lovelady'],
                ['state_id' => 44, 'city' => 'Ratcliff'],
                ['state_id' => 44, 'city' => 'Coahoma'],
                ['state_id' => 44, 'city' => 'Big Spring'],
                ['state_id' => 44, 'city' => 'Forsan'],
                ['state_id' => 44, 'city' => 'Knott'],
                ['state_id' => 44, 'city' => 'Dell City'],
                ['state_id' => 44, 'city' => 'Fort Hancock'],
                ['state_id' => 44, 'city' => 'Salt Flat'],
                ['state_id' => 44, 'city' => 'Sierra Blanca'],
                ['state_id' => 44, 'city' => 'Caddo Mills'],
                ['state_id' => 44, 'city' => 'Greenville'],
                ['state_id' => 44, 'city' => 'Campbell'],
                ['state_id' => 44, 'city' => 'Celeste'],
                ['state_id' => 44, 'city' => 'Commerce'],
                ['state_id' => 44, 'city' => 'Lone Oak'],
                ['state_id' => 44, 'city' => 'Merit'],
                ['state_id' => 44, 'city' => 'Quinlan'],
                ['state_id' => 44, 'city' => 'Wolfe City'],
                ['state_id' => 44, 'city' => 'Borger'],
                ['state_id' => 44, 'city' => 'Fritch'],
                ['state_id' => 44, 'city' => 'Sanford'],
                ['state_id' => 44, 'city' => 'Stinnett'],
                ['state_id' => 44, 'city' => 'Barnhart'],
                ['state_id' => 44, 'city' => 'Mertzon'],
                ['state_id' => 44, 'city' => 'Bryson'],
                ['state_id' => 44, 'city' => 'Jacksboro'],
                ['state_id' => 44, 'city' => 'Jermyn'],
                ['state_id' => 44, 'city' => 'Perrin'],
                ['state_id' => 44, 'city' => 'Edna'],
                ['state_id' => 44, 'city' => 'Francitas'],
                ['state_id' => 44, 'city' => 'Ganado'],
                ['state_id' => 44, 'city' => 'La Salle'],
                ['state_id' => 44, 'city' => 'La Ward'],
                ['state_id' => 44, 'city' => 'Lolita'],
                ['state_id' => 44, 'city' => 'Vanderbilt'],
                ['state_id' => 44, 'city' => 'Jasper'],
                ['state_id' => 44, 'city' => 'Kirbyville'],
                ['state_id' => 44, 'city' => 'Buna'],
                ['state_id' => 44, 'city' => 'Evadale'],
                ['state_id' => 44, 'city' => 'Fort Davis'],
                ['state_id' => 44, 'city' => 'Valentine'],
                ['state_id' => 44, 'city' => 'China'],
                ['state_id' => 44, 'city' => 'Groves'],
                ['state_id' => 44, 'city' => 'Hamshire'],
                ['state_id' => 44, 'city' => 'Nederland'],
                ['state_id' => 44, 'city' => 'Nome'],
                ['state_id' => 44, 'city' => 'Port Arthur'],
                ['state_id' => 44, 'city' => 'Port Neches'],
                ['state_id' => 44, 'city' => 'Sabine Pass'],
                ['state_id' => 44, 'city' => 'Beaumont'],
                ['state_id' => 44, 'city' => 'Guerra'],
                ['state_id' => 44, 'city' => 'Hebbronville'],
                ['state_id' => 44, 'city' => 'Alice'],
                ['state_id' => 44, 'city' => 'Ben Bolt'],
                ['state_id' => 44, 'city' => 'Orange Grove'],
                ['state_id' => 44, 'city' => 'Premont'],
                ['state_id' => 44, 'city' => 'Sandia'],
                ['state_id' => 44, 'city' => 'Alvarado'],
                ['state_id' => 44, 'city' => 'Burleson'],
                ['state_id' => 44, 'city' => 'Cleburne'],
                ['state_id' => 44, 'city' => 'Godley'],
                ['state_id' => 44, 'city' => 'Grandview'],
                ['state_id' => 44, 'city' => 'Joshua'],
                ['state_id' => 44, 'city' => 'Keene'],
                ['state_id' => 44, 'city' => 'Lillian'],
                ['state_id' => 44, 'city' => 'Venus'],
                ['state_id' => 44, 'city' => 'Rio Vista'],
                ['state_id' => 44, 'city' => 'Anson'],
                ['state_id' => 44, 'city' => 'Avoca'],
                ['state_id' => 44, 'city' => 'Hamlin'],
                ['state_id' => 44, 'city' => 'Hawley'],
                ['state_id' => 44, 'city' => 'Lueders'],
                ['state_id' => 44, 'city' => 'Stamford'],
                ['state_id' => 44, 'city' => 'Ecleto'],
                ['state_id' => 44, 'city' => 'Falls City'],
                ['state_id' => 44, 'city' => 'Gillett'],
                ['state_id' => 44, 'city' => 'Hobson'],
                ['state_id' => 44, 'city' => 'Karnes City'],
                ['state_id' => 44, 'city' => 'Kenedy'],
                ['state_id' => 44, 'city' => 'Panna Maria'],
                ['state_id' => 44, 'city' => 'Runge'],
                ['state_id' => 44, 'city' => 'Crandall'],
                ['state_id' => 44, 'city' => 'Elmo'],
                ['state_id' => 44, 'city' => 'Forney'],
                ['state_id' => 44, 'city' => 'Kaufman'],
                ['state_id' => 44, 'city' => 'Mabank'],
                ['state_id' => 44, 'city' => 'Rosser'],
                ['state_id' => 44, 'city' => 'Scurry'],
                ['state_id' => 44, 'city' => 'Terrell'],
                ['state_id' => 44, 'city' => 'Bergheim'],
                ['state_id' => 44, 'city' => 'Comfort'],
                ['state_id' => 44, 'city' => 'Kendalia'],
                ['state_id' => 44, 'city' => 'Waring'],
                ['state_id' => 44, 'city' => 'Armstrong'],
                ['state_id' => 44, 'city' => 'Sarita'],
                ['state_id' => 44, 'city' => 'Girard'],
                ['state_id' => 44, 'city' => 'Jayton'],
                ['state_id' => 44, 'city' => 'Center Point'],
                ['state_id' => 44, 'city' => 'Hunt'],
                ['state_id' => 44, 'city' => 'Ingram'],
                ['state_id' => 44, 'city' => 'Kerrville'],
                ['state_id' => 44, 'city' => 'Mountain Home'],
                ['state_id' => 44, 'city' => 'Junction'],
                ['state_id' => 44, 'city' => 'London'],
                ['state_id' => 44, 'city' => 'Roosevelt'],
                ['state_id' => 44, 'city' => 'Guthrie'],
                ['state_id' => 44, 'city' => 'Brackettville'],
                ['state_id' => 44, 'city' => 'Kingsville'],
                ['state_id' => 44, 'city' => 'Riviera'],
                ['state_id' => 44, 'city' => 'Goree'],
                ['state_id' => 44, 'city' => 'Munday'],
                ['state_id' => 44, 'city' => 'Benjamin'],
                ['state_id' => 44, 'city' => 'Knox City'],
                ['state_id' => 44, 'city' => 'Arthur City'],
                ['state_id' => 44, 'city' => 'Blossom'],
                ['state_id' => 44, 'city' => 'Brookston'],
                ['state_id' => 44, 'city' => 'Chicota'],
                ['state_id' => 44, 'city' => 'Cunningham'],
                ['state_id' => 44, 'city' => 'Deport'],
                ['state_id' => 44, 'city' => 'Paris'],
                ['state_id' => 44, 'city' => 'Pattonville'],
                ['state_id' => 44, 'city' => 'Petty'],
                ['state_id' => 44, 'city' => 'Powderly'],
                ['state_id' => 44, 'city' => 'Roxton'],
                ['state_id' => 44, 'city' => 'Sumner'],
                ['state_id' => 44, 'city' => 'Earth'],
                ['state_id' => 44, 'city' => 'Olton'],
                ['state_id' => 44, 'city' => 'Springlake'],
                ['state_id' => 44, 'city' => 'Amherst'],
                ['state_id' => 44, 'city' => 'Fieldton'],
                ['state_id' => 44, 'city' => 'Littlefield'],
                ['state_id' => 44, 'city' => 'Spade'],
                ['state_id' => 44, 'city' => 'Sudan'],
                ['state_id' => 44, 'city' => 'Kempner'],
                ['state_id' => 44, 'city' => 'Lampasas'],
                ['state_id' => 44, 'city' => 'Bend'],
                ['state_id' => 44, 'city' => 'Lometa'],
                ['state_id' => 44, 'city' => 'Artesia Wells'],
                ['state_id' => 44, 'city' => 'Cotulla'],
                ['state_id' => 44, 'city' => 'Encinal'],
                ['state_id' => 44, 'city' => 'Fowlerton'],
                ['state_id' => 44, 'city' => 'Hallettsville'],
                ['state_id' => 44, 'city' => 'Moulton'],
                ['state_id' => 44, 'city' => 'Shiner'],
                ['state_id' => 44, 'city' => 'Sublime'],
                ['state_id' => 44, 'city' => 'Sweet Home'],
                ['state_id' => 44, 'city' => 'Yoakum'],
                ['state_id' => 44, 'city' => 'Dime Box'],
                ['state_id' => 44, 'city' => 'Giddings'],
                ['state_id' => 44, 'city' => 'Lexington'],
                ['state_id' => 44, 'city' => 'Lincoln'],
                ['state_id' => 44, 'city' => 'Buffalo'],
                ['state_id' => 44, 'city' => 'Centerville'],
                ['state_id' => 44, 'city' => 'Jewett'],
                ['state_id' => 44, 'city' => 'Leona'],
                ['state_id' => 44, 'city' => 'Oakwood'],
                ['state_id' => 44, 'city' => 'Concord'],
                ['state_id' => 44, 'city' => 'Flynn'],
                ['state_id' => 44, 'city' => 'Marquez'],
                ['state_id' => 44, 'city' => 'Normangee'],
                ['state_id' => 44, 'city' => 'Cleveland'],
                ['state_id' => 44, 'city' => 'Romayor'],
                ['state_id' => 44, 'city' => 'Rye'],
                ['state_id' => 44, 'city' => 'Daisetta'],
                ['state_id' => 44, 'city' => 'Dayton'],
                ['state_id' => 44, 'city' => 'Devers'],
                ['state_id' => 44, 'city' => 'Hardin'],
                ['state_id' => 44, 'city' => 'Hull'],
                ['state_id' => 44, 'city' => 'Liberty'],
                ['state_id' => 44, 'city' => 'Raywood'],
                ['state_id' => 44, 'city' => 'Coolidge'],
                ['state_id' => 44, 'city' => 'Groesbeck'],
                ['state_id' => 44, 'city' => 'Kosse'],
                ['state_id' => 44, 'city' => 'Mexia'],
                ['state_id' => 44, 'city' => 'Prairie Hill'],
                ['state_id' => 44, 'city' => 'Tehuacana'],
                ['state_id' => 44, 'city' => 'Thornton'],
                ['state_id' => 44, 'city' => 'Booker'],
                ['state_id' => 44, 'city' => 'Darrouzett'],
                ['state_id' => 44, 'city' => 'Follett'],
                ['state_id' => 44, 'city' => 'Higgins'],
                ['state_id' => 44, 'city' => 'Lipscomb'],
                ['state_id' => 44, 'city' => 'George West'],
                ['state_id' => 44, 'city' => 'Oakville'],
                ['state_id' => 44, 'city' => 'Three Rivers'],
                ['state_id' => 44, 'city' => 'Whitsett'],
                ['state_id' => 44, 'city' => 'Dinero'],
                ['state_id' => 44, 'city' => 'Castell'],
                ['state_id' => 44, 'city' => 'Valley Spring'],
                ['state_id' => 44, 'city' => 'Bluffton'],
                ['state_id' => 44, 'city' => 'Buchanan Dam'],
                ['state_id' => 44, 'city' => 'Kingsland'],
                ['state_id' => 44, 'city' => 'Llano'],
                ['state_id' => 44, 'city' => 'Horseshoe Bay'],
                ['state_id' => 44, 'city' => 'Tow'],
                ['state_id' => 44, 'city' => 'Mentone'],
                ['state_id' => 44, 'city' => 'Idalou'],
                ['state_id' => 44, 'city' => 'New Deal'],
                ['state_id' => 44, 'city' => 'Shallowater'],
                ['state_id' => 44, 'city' => 'Slaton'],
                ['state_id' => 44, 'city' => 'Ransom Canyon'],
                ['state_id' => 44, 'city' => 'Wolfforth'],
                ['state_id' => 44, 'city' => 'Lubbock'],
                ['state_id' => 44, 'city' => 'Odonnell'],
                ['state_id' => 44, 'city' => 'Tahoka'],
                ['state_id' => 44, 'city' => 'Wilson'],
                ['state_id' => 44, 'city' => 'New Home'],
                ['state_id' => 44, 'city' => 'Brady'],
                ['state_id' => 44, 'city' => 'Doole'],
                ['state_id' => 44, 'city' => 'Lohn'],
                ['state_id' => 44, 'city' => 'Melvin'],
                ['state_id' => 44, 'city' => 'Rochelle'],
                ['state_id' => 44, 'city' => 'Voca'],
                ['state_id' => 44, 'city' => 'Eddy'],
                ['state_id' => 44, 'city' => 'Moody'],
                ['state_id' => 44, 'city' => 'Axtell'],
                ['state_id' => 44, 'city' => 'Bruceville'],
                ['state_id' => 44, 'city' => 'China Spring'],
                ['state_id' => 44, 'city' => 'Crawford'],
                ['state_id' => 44, 'city' => 'Elm Mott'],
                ['state_id' => 44, 'city' => 'Hewitt'],
                ['state_id' => 44, 'city' => 'Leroy'],
                ['state_id' => 44, 'city' => 'Lorena'],
                ['state_id' => 44, 'city' => 'Mc Gregor'],
                ['state_id' => 44, 'city' => 'Mart'],
                ['state_id' => 44, 'city' => 'Riesel'],
                ['state_id' => 44, 'city' => 'Ross'],
                ['state_id' => 44, 'city' => 'West'],
                ['state_id' => 44, 'city' => 'Waco'],
                ['state_id' => 44, 'city' => 'Woodway'],
                ['state_id' => 44, 'city' => 'Calliham'],
                ['state_id' => 44, 'city' => 'Tilden'],
                ['state_id' => 44, 'city' => 'Midway'],
                ['state_id' => 44, 'city' => 'Madisonville'],
                ['state_id' => 44, 'city' => 'North Zulch'],
                ['state_id' => 44, 'city' => 'Lodi'],
                ['state_id' => 44, 'city' => 'Jefferson'],
                ['state_id' => 44, 'city' => 'Lenorah'],
                ['state_id' => 44, 'city' => 'Stanton'],
                ['state_id' => 44, 'city' => 'Tarzan'],
                ['state_id' => 44, 'city' => 'Art'],
                ['state_id' => 44, 'city' => 'Fredonia'],
                ['state_id' => 44, 'city' => 'Mason'],
                ['state_id' => 44, 'city' => 'Pontotoc'],
                ['state_id' => 44, 'city' => 'Bay City'],
                ['state_id' => 44, 'city' => 'Cedar Lane'],
                ['state_id' => 44, 'city' => 'Blessing'],
                ['state_id' => 44, 'city' => 'Collegeport'],
                ['state_id' => 44, 'city' => 'Elmaton'],
                ['state_id' => 44, 'city' => 'Markham'],
                ['state_id' => 44, 'city' => 'Matagorda'],
                ['state_id' => 44, 'city' => 'Midfield'],
                ['state_id' => 44, 'city' => 'Palacios'],
                ['state_id' => 44, 'city' => 'Pledger'],
                ['state_id' => 44, 'city' => 'Van Vleck'],
                ['state_id' => 44, 'city' => 'Wadsworth'],
                ['state_id' => 44, 'city' => 'Eagle Pass'],
                ['state_id' => 44, 'city' => 'El Indio'],
                ['state_id' => 44, 'city' => 'Quemado'],
                ['state_id' => 44, 'city' => 'Castroville'],
                ['state_id' => 44, 'city' => 'Devine'],
                ['state_id' => 44, 'city' => 'La Coste'],
                ['state_id' => 44, 'city' => 'Mico'],
                ['state_id' => 44, 'city' => 'Natalia'],
                ['state_id' => 44, 'city' => 'Rio Medina'],
                ['state_id' => 44, 'city' => 'D Hanis'],
                ['state_id' => 44, 'city' => 'Hondo'],
                ['state_id' => 44, 'city' => 'Yancey'],
                ['state_id' => 44, 'city' => 'Fort Mc Kavett'],
                ['state_id' => 44, 'city' => 'Hext'],
                ['state_id' => 44, 'city' => 'Menard'],
                ['state_id' => 44, 'city' => 'Midland'],
                ['state_id' => 44, 'city' => 'Buckholts'],
                ['state_id' => 44, 'city' => 'Burlington'],
                ['state_id' => 44, 'city' => 'Cameron'],
                ['state_id' => 44, 'city' => 'Davilla'],
                ['state_id' => 44, 'city' => 'Milano'],
                ['state_id' => 44, 'city' => 'Rockdale'],
                ['state_id' => 44, 'city' => 'Thorndale'],
                ['state_id' => 44, 'city' => 'Gause'],
                ['state_id' => 44, 'city' => 'Goldthwaite'],
                ['state_id' => 44, 'city' => 'Mullin'],
                ['state_id' => 44, 'city' => 'Priddy'],
                ['state_id' => 44, 'city' => 'Star'],
                ['state_id' => 44, 'city' => 'Colorado City'],
                ['state_id' => 44, 'city' => 'Loraine'],
                ['state_id' => 44, 'city' => 'Westbrook'],
                ['state_id' => 44, 'city' => 'Bowie'],
                ['state_id' => 44, 'city' => 'Forestburg'],
                ['state_id' => 44, 'city' => 'Montague'],
                ['state_id' => 44, 'city' => 'Nocona'],
                ['state_id' => 44, 'city' => 'Ringgold'],
                ['state_id' => 44, 'city' => 'Saint Jo'],
                ['state_id' => 44, 'city' => 'Sunset'],
                ['state_id' => 44, 'city' => 'Conroe'],
                ['state_id' => 44, 'city' => 'Montgomery'],
                ['state_id' => 44, 'city' => 'Willis'],
                ['state_id' => 44, 'city' => 'Dobbin'],
                ['state_id' => 44, 'city' => 'Magnolia'],
                ['state_id' => 44, 'city' => 'New Caney'],
                ['state_id' => 44, 'city' => 'Pinehurst'],
                ['state_id' => 44, 'city' => 'Porter'],
                ['state_id' => 44, 'city' => 'Splendora'],
                ['state_id' => 44, 'city' => 'Cactus'],
                ['state_id' => 44, 'city' => 'Dumas'],
                ['state_id' => 44, 'city' => 'Masterson'],
                ['state_id' => 44, 'city' => 'Sunray'],
                ['state_id' => 44, 'city' => 'Naples'],
                ['state_id' => 44, 'city' => 'Omaha'],
                ['state_id' => 44, 'city' => 'Cason'],
                ['state_id' => 44, 'city' => 'Daingerfield'],
                ['state_id' => 44, 'city' => 'Lone Star'],
                ['state_id' => 44, 'city' => 'Flomot'],
                ['state_id' => 44, 'city' => 'Matador'],
                ['state_id' => 44, 'city' => 'Roaring Springs'],
                ['state_id' => 44, 'city' => 'Cushing'],
                ['state_id' => 44, 'city' => 'Sacul'],
                ['state_id' => 44, 'city' => 'Chireno'],
                ['state_id' => 44, 'city' => 'Douglass'],
                ['state_id' => 44, 'city' => 'Etoile'],
                ['state_id' => 44, 'city' => 'Garrison'],
                ['state_id' => 44, 'city' => 'Martinsville'],
                ['state_id' => 44, 'city' => 'Nacogdoches'],
                ['state_id' => 44, 'city' => 'Woden'],
                ['state_id' => 44, 'city' => 'Barry'],
                ['state_id' => 44, 'city' => 'Chatfield'],
                ['state_id' => 44, 'city' => 'Corsicana'],
                ['state_id' => 44, 'city' => 'Kerens'],
                ['state_id' => 44, 'city' => 'Powell'],
                ['state_id' => 44, 'city' => 'Blooming Grove'],
                ['state_id' => 44, 'city' => 'Dawson'],
                ['state_id' => 44, 'city' => 'Frost'],
                ['state_id' => 44, 'city' => 'Purdon'],
                ['state_id' => 44, 'city' => 'Richland'],
                ['state_id' => 44, 'city' => 'Bon Wier'],
                ['state_id' => 44, 'city' => 'Burkeville'],
                ['state_id' => 44, 'city' => 'Call'],
                ['state_id' => 44, 'city' => 'Newton'],
                ['state_id' => 44, 'city' => 'Wiergate'],
                ['state_id' => 44, 'city' => 'Deweyville'],
                ['state_id' => 44, 'city' => 'Blackwell'],
                ['state_id' => 44, 'city' => 'Maryneal'],
                ['state_id' => 44, 'city' => 'Nolan'],
                ['state_id' => 44, 'city' => 'Roscoe'],
                ['state_id' => 44, 'city' => 'Sweetwater'],
                ['state_id' => 44, 'city' => 'Agua Dulce'],
                ['state_id' => 44, 'city' => 'Banquete'],
                ['state_id' => 44, 'city' => 'Bishop'],
                ['state_id' => 44, 'city' => 'Chapman Ranch'],
                ['state_id' => 44, 'city' => 'Driscoll'],
                ['state_id' => 44, 'city' => 'Port Aransas'],
                ['state_id' => 44, 'city' => 'Robstown'],
                ['state_id' => 44, 'city' => 'Corpus Christi'],
                ['state_id' => 44, 'city' => 'Farnsworth'],
                ['state_id' => 44, 'city' => 'Perryton'],
                ['state_id' => 44, 'city' => 'Waka'],
                ['state_id' => 44, 'city' => 'Adrian'],
                ['state_id' => 44, 'city' => 'Boys Ranch'],
                ['state_id' => 44, 'city' => 'Vega'],
                ['state_id' => 44, 'city' => 'Wildorado'],
                ['state_id' => 44, 'city' => 'Bridge City'],
                ['state_id' => 44, 'city' => 'Mauriceville'],
                ['state_id' => 44, 'city' => 'Orange'],
                ['state_id' => 44, 'city' => 'Orangefield'],
                ['state_id' => 44, 'city' => 'Vidor'],
                ['state_id' => 44, 'city' => 'Mineral Wells'],
                ['state_id' => 44, 'city' => 'Graford'],
                ['state_id' => 44, 'city' => 'Gordon'],
                ['state_id' => 44, 'city' => 'Mingus'],
                ['state_id' => 44, 'city' => 'Santo'],
                ['state_id' => 44, 'city' => 'Strawn'],
                ['state_id' => 44, 'city' => 'Palo Pinto'],
                ['state_id' => 44, 'city' => 'Beckville'],
                ['state_id' => 44, 'city' => 'Carthage'],
                ['state_id' => 44, 'city' => 'Clayton'],
                ['state_id' => 44, 'city' => 'De Berry'],
                ['state_id' => 44, 'city' => 'Gary'],
                ['state_id' => 44, 'city' => 'Long Branch'],
                ['state_id' => 44, 'city' => 'Panola'],
                ['state_id' => 44, 'city' => 'Aledo'],
                ['state_id' => 44, 'city' => 'Millsap'],
                ['state_id' => 44, 'city' => 'Springtown'],
                ['state_id' => 44, 'city' => 'Weatherford'],
                ['state_id' => 44, 'city' => 'Azle'],
                ['state_id' => 44, 'city' => 'Dennis'],
                ['state_id' => 44, 'city' => 'Peaster'],
                ['state_id' => 44, 'city' => 'Poolville'],
                ['state_id' => 44, 'city' => 'Whitt'],
                ['state_id' => 44, 'city' => 'Bovina'],
                ['state_id' => 44, 'city' => 'Friona'],
                ['state_id' => 44, 'city' => 'Lazbuddie'],
                ['state_id' => 44, 'city' => 'Farwell'],
                ['state_id' => 44, 'city' => 'Coyanosa'],
                ['state_id' => 44, 'city' => 'Fort Stockton'],
                ['state_id' => 44, 'city' => 'Girvin'],
                ['state_id' => 44, 'city' => 'Imperial'],
                ['state_id' => 44, 'city' => 'Iraan'],
                ['state_id' => 44, 'city' => 'Sheffield'],
                ['state_id' => 44, 'city' => 'Camden'],
                ['state_id' => 44, 'city' => 'Corrigan'],
                ['state_id' => 44, 'city' => 'Moscow'],
                ['state_id' => 44, 'city' => 'Ace'],
                ['state_id' => 44, 'city' => 'Dallardsville'],
                ['state_id' => 44, 'city' => 'Goodrich'],
                ['state_id' => 44, 'city' => 'Leggett'],
                ['state_id' => 44, 'city' => 'Livingston'],
                ['state_id' => 44, 'city' => 'Onalaska'],
                ['state_id' => 44, 'city' => 'Bushland'],
                ['state_id' => 44, 'city' => 'Amarillo'],
                ['state_id' => 44, 'city' => 'Marfa'],
                ['state_id' => 44, 'city' => 'Presidio'],
                ['state_id' => 44, 'city' => 'Redford'],
                ['state_id' => 44, 'city' => 'Alba'],
                ['state_id' => 44, 'city' => 'Emory'],
                ['state_id' => 44, 'city' => 'Point'],
                ['state_id' => 44, 'city' => 'Canyon'],
                ['state_id' => 44, 'city' => 'Umbarger'],
                ['state_id' => 44, 'city' => 'Big Lake'],
                ['state_id' => 44, 'city' => 'Camp Wood'],
                ['state_id' => 44, 'city' => 'Leakey'],
                ['state_id' => 44, 'city' => 'Rio Frio'],
                ['state_id' => 44, 'city' => 'Bagwell'],
                ['state_id' => 44, 'city' => 'Bogata'],
                ['state_id' => 44, 'city' => 'Clarksville'],
                ['state_id' => 44, 'city' => 'Detroit'],
                ['state_id' => 44, 'city' => 'Annona'],
                ['state_id' => 44, 'city' => 'Avery'],
                ['state_id' => 44, 'city' => 'Balmorhea'],
                ['state_id' => 44, 'city' => 'Orla'],
                ['state_id' => 44, 'city' => 'Pecos'],
                ['state_id' => 44, 'city' => 'Saragosa'],
                ['state_id' => 44, 'city' => 'Toyah'],
                ['state_id' => 44, 'city' => 'Toyahvale'],
                ['state_id' => 44, 'city' => 'Austwell'],
                ['state_id' => 44, 'city' => 'Tivoli'],
                ['state_id' => 44, 'city' => 'Bayside'],
                ['state_id' => 44, 'city' => 'Refugio'],
                ['state_id' => 44, 'city' => 'Woodsboro'],
                ['state_id' => 44, 'city' => 'Miami'],
                ['state_id' => 44, 'city' => 'Bremond'],
                ['state_id' => 44, 'city' => 'Calvert'],
                ['state_id' => 44, 'city' => 'Franklin'],
                ['state_id' => 44, 'city' => 'Hearne'],
                ['state_id' => 44, 'city' => 'Mumford'],
                ['state_id' => 44, 'city' => 'New Baden'],
                ['state_id' => 44, 'city' => 'Wheelock'],
                ['state_id' => 44, 'city' => 'Rockwall'],
                ['state_id' => 44, 'city' => 'Fate'],
                ['state_id' => 44, 'city' => 'Royse City'],
                ['state_id' => 44, 'city' => 'Ballinger'],
                ['state_id' => 44, 'city' => 'Miles'],
                ['state_id' => 44, 'city' => 'Norton'],
                ['state_id' => 44, 'city' => 'Rowena'],
                ['state_id' => 44, 'city' => 'Wingate'],
                ['state_id' => 44, 'city' => 'Winters'],
                ['state_id' => 44, 'city' => 'Henderson'],
                ['state_id' => 44, 'city' => 'Joinerville'],
                ['state_id' => 44, 'city' => 'Laird Hill'],
                ['state_id' => 44, 'city' => 'Laneville'],
                ['state_id' => 44, 'city' => 'Minden'],
                ['state_id' => 44, 'city' => 'Mount Enterprise'],
                ['state_id' => 44, 'city' => 'New London'],
                ['state_id' => 44, 'city' => 'Overton'],
                ['state_id' => 44, 'city' => 'Price'],
                ['state_id' => 44, 'city' => 'Selman City'],
                ['state_id' => 44, 'city' => 'Tatum'],
                ['state_id' => 44, 'city' => 'Bronson'],
                ['state_id' => 44, 'city' => 'Brookeland'],
                ['state_id' => 44, 'city' => 'Hemphill'],
                ['state_id' => 44, 'city' => 'Milam'],
                ['state_id' => 44, 'city' => 'Pineland'],
                ['state_id' => 44, 'city' => 'Broaddus'],
                ['state_id' => 44, 'city' => 'San Augustine'],
                ['state_id' => 44, 'city' => 'Coldspring'],
                ['state_id' => 44, 'city' => 'Oakhurst'],
                ['state_id' => 44, 'city' => 'Pointblank'],
                ['state_id' => 44, 'city' => 'Shepherd'],
                ['state_id' => 44, 'city' => 'Aransas Pass'],
                ['state_id' => 44, 'city' => 'Edroy'],
                ['state_id' => 44, 'city' => 'Gregory'],
                ['state_id' => 44, 'city' => 'Ingleside'],
                ['state_id' => 44, 'city' => 'Mathis'],
                ['state_id' => 44, 'city' => 'Odem'],
                ['state_id' => 44, 'city' => 'Portland'],
                ['state_id' => 44, 'city' => 'Sinton'],
                ['state_id' => 44, 'city' => 'Taft'],
                ['state_id' => 44, 'city' => 'Cherokee'],
                ['state_id' => 44, 'city' => 'Richland Springs'],
                ['state_id' => 44, 'city' => 'San Saba'],
                ['state_id' => 44, 'city' => 'Eldorado'],
                ['state_id' => 44, 'city' => 'Dunn'],
                ['state_id' => 44, 'city' => 'Fluvanna'],
                ['state_id' => 44, 'city' => 'Hermleigh'],
                ['state_id' => 44, 'city' => 'Ira'],
                ['state_id' => 44, 'city' => 'Snyder'],
                ['state_id' => 44, 'city' => 'Albany'],
                ['state_id' => 44, 'city' => 'Moran'],
                ['state_id' => 44, 'city' => 'Center'],
                ['state_id' => 44, 'city' => 'Joaquin'],
                ['state_id' => 44, 'city' => 'Shelbyville'],
                ['state_id' => 44, 'city' => 'Tenaha'],
                ['state_id' => 44, 'city' => 'Timpson'],
                ['state_id' => 44, 'city' => 'Texhoma'],
                ['state_id' => 44, 'city' => 'Stratford'],
                ['state_id' => 44, 'city' => 'Tyler'],
                ['state_id' => 44, 'city' => 'Arp'],
                ['state_id' => 44, 'city' => 'Bullard'],
                ['state_id' => 44, 'city' => 'Flint'],
                ['state_id' => 44, 'city' => 'Lindale'],
                ['state_id' => 44, 'city' => 'Troup'],
                ['state_id' => 44, 'city' => 'Whitehouse'],
                ['state_id' => 44, 'city' => 'Winona'],
                ['state_id' => 44, 'city' => 'Glen Rose'],
                ['state_id' => 44, 'city' => 'Nemo'],
                ['state_id' => 44, 'city' => 'Rainbow'],
                ['state_id' => 44, 'city' => 'Delmita'],
                ['state_id' => 44, 'city' => 'Falcon Heights'],
                ['state_id' => 44, 'city' => 'Garciasville'],
                ['state_id' => 44, 'city' => 'Grulla'],
                ['state_id' => 44, 'city' => 'Rio Grande City'],
                ['state_id' => 44, 'city' => 'Roma'],
                ['state_id' => 44, 'city' => 'Salineno'],
                ['state_id' => 44, 'city' => 'San Isidro'],
                ['state_id' => 44, 'city' => 'Santa Elena'],
                ['state_id' => 44, 'city' => 'Breckenridge'],
                ['state_id' => 44, 'city' => 'Caddo'],
                ['state_id' => 44, 'city' => 'Sterling City'],
                ['state_id' => 44, 'city' => 'Aspermont'],
                ['state_id' => 44, 'city' => 'Old Glory'],
                ['state_id' => 44, 'city' => 'Sonora'],
                ['state_id' => 44, 'city' => 'Happy'],
                ['state_id' => 44, 'city' => 'Kress'],
                ['state_id' => 44, 'city' => 'Tulia'],
                ['state_id' => 44, 'city' => 'Arlington'],
                ['state_id' => 44, 'city' => 'Bedford'],
                ['state_id' => 44, 'city' => 'Colleyville'],
                ['state_id' => 44, 'city' => 'Crowley'],
                ['state_id' => 44, 'city' => 'Euless'],
                ['state_id' => 44, 'city' => 'Grapevine'],
                ['state_id' => 44, 'city' => 'Haslet'],
                ['state_id' => 44, 'city' => 'Hurst'],
                ['state_id' => 44, 'city' => 'Kennedale'],
                ['state_id' => 44, 'city' => 'Mansfield'],
                ['state_id' => 44, 'city' => 'Southlake'],
                ['state_id' => 44, 'city' => 'Fort Worth'],
                ['state_id' => 44, 'city' => 'Haltom City'],
                ['state_id' => 44, 'city' => 'Naval Air Station Jrb'],
                ['state_id' => 44, 'city' => 'North Richland Hills'],
                ['state_id' => 44, 'city' => 'Keller'],
                ['state_id' => 44, 'city' => 'Buffalo Gap'],
                ['state_id' => 44, 'city' => 'Lawn'],
                ['state_id' => 44, 'city' => 'Merkel'],
                ['state_id' => 44, 'city' => 'Ovalo'],
                ['state_id' => 44, 'city' => 'Trent'],
                ['state_id' => 44, 'city' => 'Tuscola'],
                ['state_id' => 44, 'city' => 'Tye'],
                ['state_id' => 44, 'city' => 'Abilene'],
                ['state_id' => 44, 'city' => 'Dyess Afb'],
                ['state_id' => 44, 'city' => 'Dryden'],
                ['state_id' => 44, 'city' => 'Sanderson'],
                ['state_id' => 44, 'city' => 'Brownfield'],
                ['state_id' => 44, 'city' => 'Meadow'],
                ['state_id' => 44, 'city' => 'Wellman'],
                ['state_id' => 44, 'city' => 'Throckmorton'],
                ['state_id' => 44, 'city' => 'Woodson'],
                ['state_id' => 44, 'city' => 'Mount Pleasant'],
                ['state_id' => 44, 'city' => 'Winfield'],
                ['state_id' => 44, 'city' => 'Cookville'],
                ['state_id' => 44, 'city' => 'Veribest'],
                ['state_id' => 44, 'city' => 'San Angelo'],
                ['state_id' => 44, 'city' => 'Goodfellow Afb'],
                ['state_id' => 44, 'city' => 'Carlsbad'],
                ['state_id' => 44, 'city' => 'Christoval'],
                ['state_id' => 44, 'city' => 'Knickerbocker'],
                ['state_id' => 44, 'city' => 'Mereta'],
                ['state_id' => 44, 'city' => 'Vancourt'],
                ['state_id' => 44, 'city' => 'Wall'],
                ['state_id' => 44, 'city' => 'Water Valley'],
                ['state_id' => 44, 'city' => 'Austin'],
                ['state_id' => 44, 'city' => 'Del Valle'],
                ['state_id' => 44, 'city' => 'Leander'],
                ['state_id' => 44, 'city' => 'Mc Neil'],
                ['state_id' => 44, 'city' => 'Manchaca'],
                ['state_id' => 44, 'city' => 'Manor'],
                ['state_id' => 44, 'city' => 'Pflugerville'],
                ['state_id' => 44, 'city' => 'Spicewood'],
                ['state_id' => 44, 'city' => 'Centralia'],
                ['state_id' => 44, 'city' => 'Groveton'],
                ['state_id' => 44, 'city' => 'Pennington'],
                ['state_id' => 44, 'city' => 'Trinity'],
                ['state_id' => 44, 'city' => 'Woodlake'],
                ['state_id' => 44, 'city' => 'Apple Springs'],
                ['state_id' => 44, 'city' => 'Chester'],
                ['state_id' => 44, 'city' => 'Colmesneil'],
                ['state_id' => 44, 'city' => 'Doucette'],
                ['state_id' => 44, 'city' => 'Woodville'],
                ['state_id' => 44, 'city' => 'Fred'],
                ['state_id' => 44, 'city' => 'Hillister'],
                ['state_id' => 44, 'city' => 'Spurger'],
                ['state_id' => 44, 'city' => 'Warren'],
                ['state_id' => 44, 'city' => 'Diana'],
                ['state_id' => 44, 'city' => 'Gilmer'],
                ['state_id' => 44, 'city' => 'Ore City'],
                ['state_id' => 44, 'city' => 'Big Sandy'],
                ['state_id' => 44, 'city' => 'Mc Camey'],
                ['state_id' => 44, 'city' => 'Midkiff'],
                ['state_id' => 44, 'city' => 'Rankin'],
                ['state_id' => 44, 'city' => 'Uvalde'],
                ['state_id' => 44, 'city' => 'Concan'],
                ['state_id' => 44, 'city' => 'Knippa'],
                ['state_id' => 44, 'city' => 'Sabinal'],
                ['state_id' => 44, 'city' => 'Utopia'],
                ['state_id' => 44, 'city' => 'Comstock'],
                ['state_id' => 44, 'city' => 'Del Rio'],
                ['state_id' => 44, 'city' => 'Laughlin Afb'],
                ['state_id' => 44, 'city' => 'Langtry'],
                ['state_id' => 44, 'city' => 'Canton'],
                ['state_id' => 44, 'city' => 'Edgewood'],
                ['state_id' => 44, 'city' => 'Fruitvale'],
                ['state_id' => 44, 'city' => 'Grand Saline'],
                ['state_id' => 44, 'city' => 'Wills Point'],
                ['state_id' => 44, 'city' => 'Ben Wheeler'],
                ['state_id' => 44, 'city' => 'Van'],
                ['state_id' => 44, 'city' => 'Victoria'],
                ['state_id' => 44, 'city' => 'Bloomington'],
                ['state_id' => 44, 'city' => 'Inez'],
                ['state_id' => 44, 'city' => 'Mcfaddin'],
                ['state_id' => 44, 'city' => 'Nursery'],
                ['state_id' => 44, 'city' => 'Placedo'],
                ['state_id' => 44, 'city' => 'Telferner'],
                ['state_id' => 44, 'city' => 'Huntsville'],
                ['state_id' => 44, 'city' => 'Dodge'],
                ['state_id' => 44, 'city' => 'New Waverly'],
                ['state_id' => 44, 'city' => 'Riverside'],
                ['state_id' => 44, 'city' => 'Brookshire'],
                ['state_id' => 44, 'city' => 'Hempstead'],
                ['state_id' => 44, 'city' => 'Prairie View'],
                ['state_id' => 44, 'city' => 'Pattison'],
                ['state_id' => 44, 'city' => 'Waller'],
                ['state_id' => 44, 'city' => 'Barstow'],
                ['state_id' => 44, 'city' => 'Grandfalls'],
                ['state_id' => 44, 'city' => 'Monahans'],
                ['state_id' => 44, 'city' => 'Pyote'],
                ['state_id' => 44, 'city' => 'Wickett'],
                ['state_id' => 44, 'city' => 'Chappell Hill'],
                ['state_id' => 44, 'city' => 'Brenham'],
                ['state_id' => 44, 'city' => 'Burton'],
                ['state_id' => 44, 'city' => 'Washington'],
                ['state_id' => 44, 'city' => 'Laredo'],
                ['state_id' => 44, 'city' => 'Bruni'],
                ['state_id' => 44, 'city' => 'Mirando City'],
                ['state_id' => 44, 'city' => 'Oilton'],
                ['state_id' => 44, 'city' => 'Boling'],
                ['state_id' => 44, 'city' => 'Danevang'],
                ['state_id' => 44, 'city' => 'East Bernard'],
                ['state_id' => 44, 'city' => 'Egypt'],
                ['state_id' => 44, 'city' => 'El Campo'],
                ['state_id' => 44, 'city' => 'Glen Flora'],
                ['state_id' => 44, 'city' => 'Hungerford'],
                ['state_id' => 44, 'city' => 'Lane City'],
                ['state_id' => 44, 'city' => 'Lissie'],
                ['state_id' => 44, 'city' => 'Louise'],
                ['state_id' => 44, 'city' => 'Pierce'],
                ['state_id' => 44, 'city' => 'Wharton'],
                ['state_id' => 44, 'city' => 'Allison'],
                ['state_id' => 44, 'city' => 'Briscoe'],
                ['state_id' => 44, 'city' => 'Mobeetie'],
                ['state_id' => 44, 'city' => 'Shamrock'],
                ['state_id' => 44, 'city' => 'Wheeler'],
                ['state_id' => 44, 'city' => 'Wichita Falls'],
                ['state_id' => 44, 'city' => 'Sheppard Afb'],
                ['state_id' => 44, 'city' => 'Burkburnett'],
                ['state_id' => 44, 'city' => 'Electra'],
                ['state_id' => 44, 'city' => 'Iowa Park'],
                ['state_id' => 44, 'city' => 'Kamay'],
                ['state_id' => 44, 'city' => 'Harrold'],
                ['state_id' => 44, 'city' => 'Oklaunion'],
                ['state_id' => 44, 'city' => 'Vernon'],
                ['state_id' => 44, 'city' => 'Odell'],
                ['state_id' => 44, 'city' => 'Lasara'],
                ['state_id' => 44, 'city' => 'Lyford'],
                ['state_id' => 44, 'city' => 'Raymondville'],
                ['state_id' => 44, 'city' => 'San Perlita'],
                ['state_id' => 44, 'city' => 'Sebastian'],
                ['state_id' => 44, 'city' => 'Port Mansfield'],
                ['state_id' => 44, 'city' => 'Florence'],
                ['state_id' => 44, 'city' => 'Granger'],
                ['state_id' => 44, 'city' => 'Jarrell'],
                ['state_id' => 44, 'city' => 'Schwertner'],
                ['state_id' => 44, 'city' => 'Taylor'],
                ['state_id' => 44, 'city' => 'Thrall'],
                ['state_id' => 44, 'city' => 'Cedar Park'],
                ['state_id' => 44, 'city' => 'Coupland'],
                ['state_id' => 44, 'city' => 'Georgetown'],
                ['state_id' => 44, 'city' => 'Hutto'],
                ['state_id' => 44, 'city' => 'Liberty Hill'],
                ['state_id' => 44, 'city' => 'Round Rock'],
                ['state_id' => 44, 'city' => 'Walburg'],
                ['state_id' => 44, 'city' => 'Weir'],
                ['state_id' => 44, 'city' => 'Floresville'],
                ['state_id' => 44, 'city' => 'La Vernia'],
                ['state_id' => 44, 'city' => 'Pandora'],
                ['state_id' => 44, 'city' => 'Poth'],
                ['state_id' => 44, 'city' => 'Stockdale'],
                ['state_id' => 44, 'city' => 'Sutherland Springs'],
                ['state_id' => 44, 'city' => 'Kermit'],
                ['state_id' => 44, 'city' => 'Wink'],
                ['state_id' => 44, 'city' => 'Boyd'],
                ['state_id' => 44, 'city' => 'Newark'],
                ['state_id' => 44, 'city' => 'Paradise'],
                ['state_id' => 44, 'city' => 'Rhome'],
                ['state_id' => 44, 'city' => 'Alvord'],
                ['state_id' => 44, 'city' => 'Decatur'],
                ['state_id' => 44, 'city' => 'Greenwood'],
                ['state_id' => 44, 'city' => 'Slidell'],
                ['state_id' => 44, 'city' => 'Bridgeport'],
                ['state_id' => 44, 'city' => 'Chico'],
                ['state_id' => 44, 'city' => 'Golden'],
                ['state_id' => 44, 'city' => 'Winnsboro'],
                ['state_id' => 44, 'city' => 'Yantis'],
                ['state_id' => 44, 'city' => 'Hawkins'],
                ['state_id' => 44, 'city' => 'Mineola'],
                ['state_id' => 44, 'city' => 'Quitman'],
                ['state_id' => 44, 'city' => 'Denver City'],
                ['state_id' => 44, 'city' => 'Plains'],
                ['state_id' => 44, 'city' => 'Tokio'],
                ['state_id' => 44, 'city' => 'Newcastle'],
                ['state_id' => 44, 'city' => 'Olney'],
                ['state_id' => 44, 'city' => 'Graham'],
                ['state_id' => 44, 'city' => 'Loving'],
                ['state_id' => 44, 'city' => 'South Bend'],
                ['state_id' => 44, 'city' => 'San Ygnacio'],
                ['state_id' => 44, 'city' => 'Zapata'],
                ['state_id' => 44, 'city' => 'Lopeno'],
                ['state_id' => 44, 'city' => 'Batesville'],
                ['state_id' => 44, 'city' => 'Crystal City'],
                ['state_id' => 44, 'city' => 'La Pryor', 'state_id' => 44]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
