<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State15TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of IN - Indiana.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 15, 'city' => 'Berne'],
                ['state_id' => 15, 'city' => 'Decatur'],
                ['state_id' => 15, 'city' => 'Geneva'],
                ['state_id' => 15, 'city' => 'Linn Grove'],
                ['state_id' => 15, 'city' => 'Monroe'],
                ['state_id' => 15, 'city' => 'Pleasant Mills'],
                ['state_id' => 15, 'city' => 'Preble'],
                ['state_id' => 15, 'city' => 'Arcola'],
                ['state_id' => 15, 'city' => 'Grabill'],
                ['state_id' => 15, 'city' => 'Harlan'],
                ['state_id' => 15, 'city' => 'Hoagland'],
                ['state_id' => 15, 'city' => 'Huntertown'],
                ['state_id' => 15, 'city' => 'Leo'],
                ['state_id' => 15, 'city' => 'Monroeville'],
                ['state_id' => 15, 'city' => 'New Haven'],
                ['state_id' => 15, 'city' => 'Woodburn'],
                ['state_id' => 15, 'city' => 'Yoder'],
                ['state_id' => 15, 'city' => 'Zanesville'],
                ['state_id' => 15, 'city' => 'Fort Wayne'],
                ['state_id' => 15, 'city' => 'Columbus'],
                ['state_id' => 15, 'city' => 'Clifford'],
                ['state_id' => 15, 'city' => 'Elizabethtown'],
                ['state_id' => 15, 'city' => 'Grammer'],
                ['state_id' => 15, 'city' => 'Hartsville'],
                ['state_id' => 15, 'city' => 'Hope'],
                ['state_id' => 15, 'city' => 'Jonesville'],
                ['state_id' => 15, 'city' => 'Taylorsville'],
                ['state_id' => 15, 'city' => 'Ambia'],
                ['state_id' => 15, 'city' => 'Boswell'],
                ['state_id' => 15, 'city' => 'Earl Park'],
                ['state_id' => 15, 'city' => 'Fowler'],
                ['state_id' => 15, 'city' => 'Otterbein'],
                ['state_id' => 15, 'city' => 'Oxford'],
                ['state_id' => 15, 'city' => 'Talbot'],
                ['state_id' => 15, 'city' => 'Templeton'],
                ['state_id' => 15, 'city' => 'Hartford City'],
                ['state_id' => 15, 'city' => 'Montpelier'],
                ['state_id' => 15, 'city' => 'Lebanon'],
                ['state_id' => 15, 'city' => 'Thorntown'],
                ['state_id' => 15, 'city' => 'Whitestown'],
                ['state_id' => 15, 'city' => 'Zionsville'],
                ['state_id' => 15, 'city' => 'Advance'],
                ['state_id' => 15, 'city' => 'Jamestown'],
                ['state_id' => 15, 'city' => 'Morgantown'],
                ['state_id' => 15, 'city' => 'Helmsburg'],
                ['state_id' => 15, 'city' => 'Nashville'],
                ['state_id' => 15, 'city' => 'Bringhurst'],
                ['state_id' => 15, 'city' => 'Burlington'],
                ['state_id' => 15, 'city' => 'Burrows'],
                ['state_id' => 15, 'city' => 'Camden'],
                ['state_id' => 15, 'city' => 'Cutler'],
                ['state_id' => 15, 'city' => 'Delphi'],
                ['state_id' => 15, 'city' => 'Flora'],
                ['state_id' => 15, 'city' => 'Rockfield'],
                ['state_id' => 15, 'city' => 'Yeoman'],
                ['state_id' => 15, 'city' => 'Galveston'],
                ['state_id' => 15, 'city' => 'Lake Cicott'],
                ['state_id' => 15, 'city' => 'Logansport'],
                ['state_id' => 15, 'city' => 'Lucerne'],
                ['state_id' => 15, 'city' => 'New Waverly'],
                ['state_id' => 15, 'city' => 'Onward'],
                ['state_id' => 15, 'city' => 'Royal Center'],
                ['state_id' => 15, 'city' => 'Twelve Mile'],
                ['state_id' => 15, 'city' => 'Walton'],
                ['state_id' => 15, 'city' => 'Young America'],
                ['state_id' => 15, 'city' => 'Bethlehem'],
                ['state_id' => 15, 'city' => 'Borden'],
                ['state_id' => 15, 'city' => 'Charlestown'],
                ['state_id' => 15, 'city' => 'Henryville'],
                ['state_id' => 15, 'city' => 'Clarksville'],
                ['state_id' => 15, 'city' => 'Jeffersonville'],
                ['state_id' => 15, 'city' => 'Marysville'],
                ['state_id' => 15, 'city' => 'Memphis'],
                ['state_id' => 15, 'city' => 'Nabb'],
                ['state_id' => 15, 'city' => 'New Washington'],
                ['state_id' => 15, 'city' => 'Otisco'],
                ['state_id' => 15, 'city' => 'Sellersburg'],
                ['state_id' => 15, 'city' => 'Underwood'],
                ['state_id' => 15, 'city' => 'Bowling Green'],
                ['state_id' => 15, 'city' => 'Brazil'],
                ['state_id' => 15, 'city' => 'Carbon'],
                ['state_id' => 15, 'city' => 'Centerpoint'],
                ['state_id' => 15, 'city' => 'Clay City'],
                ['state_id' => 15, 'city' => 'Coalmont'],
                ['state_id' => 15, 'city' => 'Cory'],
                ['state_id' => 15, 'city' => 'Harmony'],
                ['state_id' => 15, 'city' => 'Knightsville'],
                ['state_id' => 15, 'city' => 'Poland'],
                ['state_id' => 15, 'city' => 'Staunton'],
                ['state_id' => 15, 'city' => 'Colfax'],
                ['state_id' => 15, 'city' => 'Forest'],
                ['state_id' => 15, 'city' => 'Frankfort'],
                ['state_id' => 15, 'city' => 'Kirklin'],
                ['state_id' => 15, 'city' => 'Michigantown'],
                ['state_id' => 15, 'city' => 'Mulberry'],
                ['state_id' => 15, 'city' => 'Rossville'],
                ['state_id' => 15, 'city' => 'Sedalia'],
                ['state_id' => 15, 'city' => 'Eckerty'],
                ['state_id' => 15, 'city' => 'English'],
                ['state_id' => 15, 'city' => 'Grantsburg'],
                ['state_id' => 15, 'city' => 'Leavenworth'],
                ['state_id' => 15, 'city' => 'Marengo'],
                ['state_id' => 15, 'city' => 'Milltown'],
                ['state_id' => 15, 'city' => 'Sulphur'],
                ['state_id' => 15, 'city' => 'Taswell'],
                ['state_id' => 15, 'city' => 'Washington'],
                ['state_id' => 15, 'city' => 'Cannelburg'],
                ['state_id' => 15, 'city' => 'Elnora'],
                ['state_id' => 15, 'city' => 'Montgomery'],
                ['state_id' => 15, 'city' => 'Odon'],
                ['state_id' => 15, 'city' => 'Plainville'],
                ['state_id' => 15, 'city' => 'Aurora'],
                ['state_id' => 15, 'city' => 'Dillsboro'],
                ['state_id' => 15, 'city' => 'Guilford'],
                ['state_id' => 15, 'city' => 'Lawrenceburg'],
                ['state_id' => 15, 'city' => 'Moores Hill'],
                ['state_id' => 15, 'city' => 'West Harrison'],
                ['state_id' => 15, 'city' => 'Clarksburg'],
                ['state_id' => 15, 'city' => 'Greensburg'],
                ['state_id' => 15, 'city' => 'Millhousen'],
                ['state_id' => 15, 'city' => 'New Point'],
                ['state_id' => 15, 'city' => 'Saint Paul'],
                ['state_id' => 15, 'city' => 'Westport'],
                ['state_id' => 15, 'city' => 'Ashley'],
                ['state_id' => 15, 'city' => 'Auburn'],
                ['state_id' => 15, 'city' => 'Butler'],
                ['state_id' => 15, 'city' => 'Corunna'],
                ['state_id' => 15, 'city' => 'Garrett'],
                ['state_id' => 15, 'city' => 'Saint Joe'],
                ['state_id' => 15, 'city' => 'Spencerville'],
                ['state_id' => 15, 'city' => 'Waterloo'],
                ['state_id' => 15, 'city' => 'Muncie'],
                ['state_id' => 15, 'city' => 'Albany'],
                ['state_id' => 15, 'city' => 'Daleville'],
                ['state_id' => 15, 'city' => 'Eaton'],
                ['state_id' => 15, 'city' => 'Gaston'],
                ['state_id' => 15, 'city' => 'Oakville'],
                ['state_id' => 15, 'city' => 'Selma'],
                ['state_id' => 15, 'city' => 'Yorktown'],
                ['state_id' => 15, 'city' => 'Birdseye'],
                ['state_id' => 15, 'city' => 'Celestine'],
                ['state_id' => 15, 'city' => 'Dubois'],
                ['state_id' => 15, 'city' => 'Ferdinand'],
                ['state_id' => 15, 'city' => 'Holland'],
                ['state_id' => 15, 'city' => 'Huntingburg'],
                ['state_id' => 15, 'city' => 'Ireland'],
                ['state_id' => 15, 'city' => 'Jasper'],
                ['state_id' => 15, 'city' => 'Saint Anthony'],
                ['state_id' => 15, 'city' => 'Schnellville'],
                ['state_id' => 15, 'city' => 'Bristol'],
                ['state_id' => 15, 'city' => 'Elkhart'],
                ['state_id' => 15, 'city' => 'Goshen'],
                ['state_id' => 15, 'city' => 'Middlebury'],
                ['state_id' => 15, 'city' => 'Millersburg'],
                ['state_id' => 15, 'city' => 'Nappanee'],
                ['state_id' => 15, 'city' => 'New Paris'],
                ['state_id' => 15, 'city' => 'Wakarusa'],
                ['state_id' => 15, 'city' => 'Glenwood'],
                ['state_id' => 15, 'city' => 'Bentonville'],
                ['state_id' => 15, 'city' => 'Connersville'],
                ['state_id' => 15, 'city' => 'Floyds Knobs'],
                ['state_id' => 15, 'city' => 'Georgetown'],
                ['state_id' => 15, 'city' => 'Greenville'],
                ['state_id' => 15, 'city' => 'Mount Saint Francis'],
                ['state_id' => 15, 'city' => 'New Albany'],
                ['state_id' => 15, 'city' => 'Attica'],
                ['state_id' => 15, 'city' => 'Covington'],
                ['state_id' => 15, 'city' => 'Hillsboro'],
                ['state_id' => 15, 'city' => 'Kingman'],
                ['state_id' => 15, 'city' => 'Mellott'],
                ['state_id' => 15, 'city' => 'Newtown'],
                ['state_id' => 15, 'city' => 'Veedersburg'],
                ['state_id' => 15, 'city' => 'Wallace'],
                ['state_id' => 15, 'city' => 'West College Corner'],
                ['state_id' => 15, 'city' => 'Bath'],
                ['state_id' => 15, 'city' => 'Brookville'],
                ['state_id' => 15, 'city' => 'Cedar Grove'],
                ['state_id' => 15, 'city' => 'Laurel'],
                ['state_id' => 15, 'city' => 'Metamora'],
                ['state_id' => 15, 'city' => 'New Trenton'],
                ['state_id' => 15, 'city' => 'Oldenburg'],
                ['state_id' => 15, 'city' => 'Akron'],
                ['state_id' => 15, 'city' => 'Athens'],
                ['state_id' => 15, 'city' => 'Delong'],
                ['state_id' => 15, 'city' => 'Fulton'],
                ['state_id' => 15, 'city' => 'Grass Creek'],
                ['state_id' => 15, 'city' => 'Kewanna'],
                ['state_id' => 15, 'city' => 'Leiters Ford'],
                ['state_id' => 15, 'city' => 'Rochester'],
                ['state_id' => 15, 'city' => 'Haubstadt'],
                ['state_id' => 15, 'city' => 'Hazleton'],
                ['state_id' => 15, 'city' => 'Buckskin'],
                ['state_id' => 15, 'city' => 'Fort Branch'],
                ['state_id' => 15, 'city' => 'Francisco'],
                ['state_id' => 15, 'city' => 'Mackey'],
                ['state_id' => 15, 'city' => 'Oakland City'],
                ['state_id' => 15, 'city' => 'Owensville'],
                ['state_id' => 15, 'city' => 'Patoka'],
                ['state_id' => 15, 'city' => 'Princeton'],
                ['state_id' => 15, 'city' => 'Somerville'],
                ['state_id' => 15, 'city' => 'Fairmount'],
                ['state_id' => 15, 'city' => 'Fowlerton'],
                ['state_id' => 15, 'city' => 'Gas City'],
                ['state_id' => 15, 'city' => 'Jonesboro'],
                ['state_id' => 15, 'city' => 'Marion'],
                ['state_id' => 15, 'city' => 'Matthews'],
                ['state_id' => 15, 'city' => 'Swayzee'],
                ['state_id' => 15, 'city' => 'Sweetser'],
                ['state_id' => 15, 'city' => 'Upland'],
                ['state_id' => 15, 'city' => 'Van Buren'],
                ['state_id' => 15, 'city' => 'Bloomfield'],
                ['state_id' => 15, 'city' => 'Jasonville'],
                ['state_id' => 15, 'city' => 'Koleen'],
                ['state_id' => 15, 'city' => 'Linton'],
                ['state_id' => 15, 'city' => 'Lyons'],
                ['state_id' => 15, 'city' => 'Midland'],
                ['state_id' => 15, 'city' => 'Newberry'],
                ['state_id' => 15, 'city' => 'Owensburg'],
                ['state_id' => 15, 'city' => 'Scotland'],
                ['state_id' => 15, 'city' => 'Solsberry'],
                ['state_id' => 15, 'city' => 'Switz City'],
                ['state_id' => 15, 'city' => 'Worthington'],
                ['state_id' => 15, 'city' => 'Arcadia'],
                ['state_id' => 15, 'city' => 'Atlanta'],
                ['state_id' => 15, 'city' => 'Carmel'],
                ['state_id' => 15, 'city' => 'Cicero'],
                ['state_id' => 15, 'city' => 'Fishers'],
                ['state_id' => 15, 'city' => 'Noblesville'],
                ['state_id' => 15, 'city' => 'Sheridan'],
                ['state_id' => 15, 'city' => 'Westfield'],
                ['state_id' => 15, 'city' => 'Indianapolis'],
                ['state_id' => 15, 'city' => 'Fortville'],
                ['state_id' => 15, 'city' => 'Mccordsville'],
                ['state_id' => 15, 'city' => 'Charlottesville'],
                ['state_id' => 15, 'city' => 'Finly'],
                ['state_id' => 15, 'city' => 'Greenfield'],
                ['state_id' => 15, 'city' => 'Maxwell'],
                ['state_id' => 15, 'city' => 'New Palestine'],
                ['state_id' => 15, 'city' => 'Wilkinson'],
                ['state_id' => 15, 'city' => 'Bradford'],
                ['state_id' => 15, 'city' => 'Central'],
                ['state_id' => 15, 'city' => 'Corydon'],
                ['state_id' => 15, 'city' => 'Crandall'],
                ['state_id' => 15, 'city' => 'Depauw'],
                ['state_id' => 15, 'city' => 'Elizabeth'],
                ['state_id' => 15, 'city' => 'Laconia'],
                ['state_id' => 15, 'city' => 'Lanesville'],
                ['state_id' => 15, 'city' => 'Mauckport'],
                ['state_id' => 15, 'city' => 'New Middletown'],
                ['state_id' => 15, 'city' => 'New Salisbury'],
                ['state_id' => 15, 'city' => 'Palmyra'],
                ['state_id' => 15, 'city' => 'Ramsey'],
                ['state_id' => 15, 'city' => 'Amo'],
                ['state_id' => 15, 'city' => 'Brownsburg'],
                ['state_id' => 15, 'city' => 'Clayton'],
                ['state_id' => 15, 'city' => 'Coatesville'],
                ['state_id' => 15, 'city' => 'Danville'],
                ['state_id' => 15, 'city' => 'Avon'],
                ['state_id' => 15, 'city' => 'Lizton'],
                ['state_id' => 15, 'city' => 'North Salem'],
                ['state_id' => 15, 'city' => 'Pittsboro'],
                ['state_id' => 15, 'city' => 'Plainfield'],
                ['state_id' => 15, 'city' => 'Stilesville'],
                ['state_id' => 15, 'city' => 'Knightstown'],
                ['state_id' => 15, 'city' => 'Dunreith'],
                ['state_id' => 15, 'city' => 'Greensboro'],
                ['state_id' => 15, 'city' => 'Kennard'],
                ['state_id' => 15, 'city' => 'Lewisville'],
                ['state_id' => 15, 'city' => 'Middletown'],
                ['state_id' => 15, 'city' => 'Mooreland'],
                ['state_id' => 15, 'city' => 'Mount Summit'],
                ['state_id' => 15, 'city' => 'New Castle'],
                ['state_id' => 15, 'city' => 'New Lisbon'],
                ['state_id' => 15, 'city' => 'Shirley'],
                ['state_id' => 15, 'city' => 'Spiceland'],
                ['state_id' => 15, 'city' => 'Springport'],
                ['state_id' => 15, 'city' => 'Straughn'],
                ['state_id' => 15, 'city' => 'Sulphur Springs'],
                ['state_id' => 15, 'city' => 'Kokomo'],
                ['state_id' => 15, 'city' => 'Greentown'],
                ['state_id' => 15, 'city' => 'Hemlock'],
                ['state_id' => 15, 'city' => 'Oakford'],
                ['state_id' => 15, 'city' => 'Russiaville'],
                ['state_id' => 15, 'city' => 'West Middleton'],
                ['state_id' => 15, 'city' => 'Andrews'],
                ['state_id' => 15, 'city' => 'Bippus'],
                ['state_id' => 15, 'city' => 'Huntington'],
                ['state_id' => 15, 'city' => 'Markle'],
                ['state_id' => 15, 'city' => 'Roanoke'],
                ['state_id' => 15, 'city' => 'Warren'],
                ['state_id' => 15, 'city' => 'Brownstown'],
                ['state_id' => 15, 'city' => 'Cortland'],
                ['state_id' => 15, 'city' => 'Crothersville'],
                ['state_id' => 15, 'city' => 'Freetown'],
                ['state_id' => 15, 'city' => 'Kurtz'],
                ['state_id' => 15, 'city' => 'Medora'],
                ['state_id' => 15, 'city' => 'Norman'],
                ['state_id' => 15, 'city' => 'Seymour'],
                ['state_id' => 15, 'city' => 'Vallonia'],
                ['state_id' => 15, 'city' => 'Demotte'],
                ['state_id' => 15, 'city' => 'Tefft'],
                ['state_id' => 15, 'city' => 'Wheatfield'],
                ['state_id' => 15, 'city' => 'Fair Oaks'],
                ['state_id' => 15, 'city' => 'Remington'],
                ['state_id' => 15, 'city' => 'Rensselaer'],
                ['state_id' => 15, 'city' => 'Bryant'],
                ['state_id' => 15, 'city' => 'Dunkirk'],
                ['state_id' => 15, 'city' => 'Pennville'],
                ['state_id' => 15, 'city' => 'Portland'],
                ['state_id' => 15, 'city' => 'Redkey'],
                ['state_id' => 15, 'city' => 'Salamonia'],
                ['state_id' => 15, 'city' => 'Canaan'],
                ['state_id' => 15, 'city' => 'Deputy'],
                ['state_id' => 15, 'city' => 'Dupont'],
                ['state_id' => 15, 'city' => 'Hanover'],
                ['state_id' => 15, 'city' => 'Madison'],
                ['state_id' => 15, 'city' => 'Butlerville'],
                ['state_id' => 15, 'city' => 'Commiskey'],
                ['state_id' => 15, 'city' => 'Hayden'],
                ['state_id' => 15, 'city' => 'North Vernon'],
                ['state_id' => 15, 'city' => 'Paris Crossing'],
                ['state_id' => 15, 'city' => 'Scipio'],
                ['state_id' => 15, 'city' => 'Vernon'],
                ['state_id' => 15, 'city' => 'Bargersville'],
                ['state_id' => 15, 'city' => 'Edinburgh'],
                ['state_id' => 15, 'city' => 'Franklin'],
                ['state_id' => 15, 'city' => 'Greenwood'],
                ['state_id' => 15, 'city' => 'Needham'],
                ['state_id' => 15, 'city' => 'Nineveh'],
                ['state_id' => 15, 'city' => 'Trafalgar'],
                ['state_id' => 15, 'city' => 'Whiteland'],
                ['state_id' => 15, 'city' => 'Bicknell'],
                ['state_id' => 15, 'city' => 'Bruceville'],
                ['state_id' => 15, 'city' => 'Decker'],
                ['state_id' => 15, 'city' => 'Edwardsport'],
                ['state_id' => 15, 'city' => 'Freelandville'],
                ['state_id' => 15, 'city' => 'Monroe City'],
                ['state_id' => 15, 'city' => 'Oaktown'],
                ['state_id' => 15, 'city' => 'Ragsdale'],
                ['state_id' => 15, 'city' => 'Sandborn'],
                ['state_id' => 15, 'city' => 'Vincennes'],
                ['state_id' => 15, 'city' => 'Westphalia'],
                ['state_id' => 15, 'city' => 'Wheatland'],
                ['state_id' => 15, 'city' => 'Atwood'],
                ['state_id' => 15, 'city' => 'Burket'],
                ['state_id' => 15, 'city' => 'Claypool'],
                ['state_id' => 15, 'city' => 'Etna Green'],
                ['state_id' => 15, 'city' => 'Leesburg'],
                ['state_id' => 15, 'city' => 'Mentone'],
                ['state_id' => 15, 'city' => 'Milford'],
                ['state_id' => 15, 'city' => 'North Webster'],
                ['state_id' => 15, 'city' => 'Pierceton'],
                ['state_id' => 15, 'city' => 'Syracuse'],
                ['state_id' => 15, 'city' => 'Warsaw'],
                ['state_id' => 15, 'city' => 'Winona Lake'],
                ['state_id' => 15, 'city' => 'Silver Lake'],
                ['state_id' => 15, 'city' => 'Shipshewana'],
                ['state_id' => 15, 'city' => 'Topeka'],
                ['state_id' => 15, 'city' => 'Howe'],
                ['state_id' => 15, 'city' => 'Lagrange'],
                ['state_id' => 15, 'city' => 'Mongo'],
                ['state_id' => 15, 'city' => 'South Milford'],
                ['state_id' => 15, 'city' => 'Stroh'],
                ['state_id' => 15, 'city' => 'Wolcottville'],
                ['state_id' => 15, 'city' => 'Cedar Lake'],
                ['state_id' => 15, 'city' => 'Crown Point'],
                ['state_id' => 15, 'city' => 'Dyer'],
                ['state_id' => 15, 'city' => 'East Chicago'],
                ['state_id' => 15, 'city' => 'Griffith'],
                ['state_id' => 15, 'city' => 'Hammond'],
                ['state_id' => 15, 'city' => 'Munster'],
                ['state_id' => 15, 'city' => 'Highland'],
                ['state_id' => 15, 'city' => 'Hobart'],
                ['state_id' => 15, 'city' => 'Leroy'],
                ['state_id' => 15, 'city' => 'Lowell'],
                ['state_id' => 15, 'city' => 'Saint John'],
                ['state_id' => 15, 'city' => 'Schererville'],
                ['state_id' => 15, 'city' => 'Schneider'],
                ['state_id' => 15, 'city' => 'Shelby'],
                ['state_id' => 15, 'city' => 'Whiting'],
                ['state_id' => 15, 'city' => 'Gary'],
                ['state_id' => 15, 'city' => 'Lake Station'],
                ['state_id' => 15, 'city' => 'Merrillville'],
                ['state_id' => 15, 'city' => 'Hanna'],
                ['state_id' => 15, 'city' => 'Kingsbury'],
                ['state_id' => 15, 'city' => 'Kingsford Heights'],
                ['state_id' => 15, 'city' => 'La Crosse'],
                ['state_id' => 15, 'city' => 'La Porte'],
                ['state_id' => 15, 'city' => 'Michigan City'],
                ['state_id' => 15, 'city' => 'Mill Creek'],
                ['state_id' => 15, 'city' => 'Rolling Prairie'],
                ['state_id' => 15, 'city' => 'Union Mills'],
                ['state_id' => 15, 'city' => 'Wanatah'],
                ['state_id' => 15, 'city' => 'Westville'],
                ['state_id' => 15, 'city' => 'Avoca'],
                ['state_id' => 15, 'city' => 'Bedford'],
                ['state_id' => 15, 'city' => 'Heltonville'],
                ['state_id' => 15, 'city' => 'Huron'],
                ['state_id' => 15, 'city' => 'Mitchell'],
                ['state_id' => 15, 'city' => 'Oolitic'],
                ['state_id' => 15, 'city' => 'Springville'],
                ['state_id' => 15, 'city' => 'Tunnelton'],
                ['state_id' => 15, 'city' => 'Williams'],
                ['state_id' => 15, 'city' => 'Alexandria'],
                ['state_id' => 15, 'city' => 'Anderson'],
                ['state_id' => 15, 'city' => 'Elwood'],
                ['state_id' => 15, 'city' => 'Frankton'],
                ['state_id' => 15, 'city' => 'Ingalls'],
                ['state_id' => 15, 'city' => 'Lapel'],
                ['state_id' => 15, 'city' => 'Markleville'],
                ['state_id' => 15, 'city' => 'Orestes'],
                ['state_id' => 15, 'city' => 'Pendleton'],
                ['state_id' => 15, 'city' => 'Summitville'],
                ['state_id' => 15, 'city' => 'Beech Grove'],
                ['state_id' => 15, 'city' => 'Camby'],
                ['state_id' => 15, 'city' => 'West Newton'],
                ['state_id' => 15, 'city' => 'Argos'],
                ['state_id' => 15, 'city' => 'Bourbon'],
                ['state_id' => 15, 'city' => 'Bremen'],
                ['state_id' => 15, 'city' => 'Culver'],
                ['state_id' => 15, 'city' => 'Donaldson'],
                ['state_id' => 15, 'city' => 'Lapaz'],
                ['state_id' => 15, 'city' => 'Plymouth'],
                ['state_id' => 15, 'city' => 'Tippecanoe'],
                ['state_id' => 15, 'city' => 'Tyner'],
                ['state_id' => 15, 'city' => 'Crane'],
                ['state_id' => 15, 'city' => 'Loogootee'],
                ['state_id' => 15, 'city' => 'Shoals'],
                ['state_id' => 15, 'city' => 'Amboy'],
                ['state_id' => 15, 'city' => 'Bunker Hill'],
                ['state_id' => 15, 'city' => 'Converse'],
                ['state_id' => 15, 'city' => 'Deedsville'],
                ['state_id' => 15, 'city' => 'Denver'],
                ['state_id' => 15, 'city' => 'Macy'],
                ['state_id' => 15, 'city' => 'Mexico'],
                ['state_id' => 15, 'city' => 'Miami'],
                ['state_id' => 15, 'city' => 'Peru'],
                ['state_id' => 15, 'city' => 'Grissom Arb'],
                ['state_id' => 15, 'city' => 'Bloomington'],
                ['state_id' => 15, 'city' => 'Clear Creek'],
                ['state_id' => 15, 'city' => 'Ellettsville'],
                ['state_id' => 15, 'city' => 'Harrodsburg'],
                ['state_id' => 15, 'city' => 'Smithville'],
                ['state_id' => 15, 'city' => 'Stanford'],
                ['state_id' => 15, 'city' => 'Stinesville'],
                ['state_id' => 15, 'city' => 'Unionville'],
                ['state_id' => 15, 'city' => 'Alamo'],
                ['state_id' => 15, 'city' => 'Crawfordsville'],
                ['state_id' => 15, 'city' => 'Darlington'],
                ['state_id' => 15, 'city' => 'Ladoga'],
                ['state_id' => 15, 'city' => 'Linden'],
                ['state_id' => 15, 'city' => 'New Market'],
                ['state_id' => 15, 'city' => 'New Richmond'],
                ['state_id' => 15, 'city' => 'New Ross'],
                ['state_id' => 15, 'city' => 'Waveland'],
                ['state_id' => 15, 'city' => 'Waynetown'],
                ['state_id' => 15, 'city' => 'Wingate'],
                ['state_id' => 15, 'city' => 'Brooklyn'],
                ['state_id' => 15, 'city' => 'Eminence'],
                ['state_id' => 15, 'city' => 'Martinsville'],
                ['state_id' => 15, 'city' => 'Monrovia'],
                ['state_id' => 15, 'city' => 'Mooresville'],
                ['state_id' => 15, 'city' => 'Paragon'],
                ['state_id' => 15, 'city' => 'Lake Village'],
                ['state_id' => 15, 'city' => 'Roselawn'],
                ['state_id' => 15, 'city' => 'Sumava Resorts'],
                ['state_id' => 15, 'city' => 'Thayer'],
                ['state_id' => 15, 'city' => 'Brook'],
                ['state_id' => 15, 'city' => 'Goodland'],
                ['state_id' => 15, 'city' => 'Kentland'],
                ['state_id' => 15, 'city' => 'Morocco'],
                ['state_id' => 15, 'city' => 'Mount Ayr'],
                ['state_id' => 15, 'city' => 'Albion'],
                ['state_id' => 15, 'city' => 'Avilla'],
                ['state_id' => 15, 'city' => 'Cromwell'],
                ['state_id' => 15, 'city' => 'Kendallville'],
                ['state_id' => 15, 'city' => 'Kimmell'],
                ['state_id' => 15, 'city' => 'Laotto'],
                ['state_id' => 15, 'city' => 'Ligonier'],
                ['state_id' => 15, 'city' => 'Rome City'],
                ['state_id' => 15, 'city' => 'Wawaka'],
                ['state_id' => 15, 'city' => 'Wolflake'],
                ['state_id' => 15, 'city' => 'Rising Sun'],
                ['state_id' => 15, 'city' => 'French Lick'],
                ['state_id' => 15, 'city' => 'Orleans'],
                ['state_id' => 15, 'city' => 'Paoli'],
                ['state_id' => 15, 'city' => 'West Baden Springs'],
                ['state_id' => 15, 'city' => 'Coal City'],
                ['state_id' => 15, 'city' => 'Freedom'],
                ['state_id' => 15, 'city' => 'Gosport'],
                ['state_id' => 15, 'city' => 'Patricksburg'],
                ['state_id' => 15, 'city' => 'Quincy'],
                ['state_id' => 15, 'city' => 'Spencer'],
                ['state_id' => 15, 'city' => 'Bellmore'],
                ['state_id' => 15, 'city' => 'Bloomingdale'],
                ['state_id' => 15, 'city' => 'Bridgeton'],
                ['state_id' => 15, 'city' => 'Marshall'],
                ['state_id' => 15, 'city' => 'Mecca'],
                ['state_id' => 15, 'city' => 'Montezuma'],
                ['state_id' => 15, 'city' => 'Rockville'],
                ['state_id' => 15, 'city' => 'Rosedale'],
                ['state_id' => 15, 'city' => 'Branchville'],
                ['state_id' => 15, 'city' => 'Bristow'],
                ['state_id' => 15, 'city' => 'Cannelton'],
                ['state_id' => 15, 'city' => 'Derby'],
                ['state_id' => 15, 'city' => 'Leopold'],
                ['state_id' => 15, 'city' => 'Rome'],
                ['state_id' => 15, 'city' => 'Saint Croix'],
                ['state_id' => 15, 'city' => 'Tell City'],
                ['state_id' => 15, 'city' => 'Otwell'],
                ['state_id' => 15, 'city' => 'Petersburg'],
                ['state_id' => 15, 'city' => 'Spurgeon'],
                ['state_id' => 15, 'city' => 'Stendal'],
                ['state_id' => 15, 'city' => 'Velpen'],
                ['state_id' => 15, 'city' => 'Winslow'],
                ['state_id' => 15, 'city' => 'Beverly Shores'],
                ['state_id' => 15, 'city' => 'Boone Grove'],
                ['state_id' => 15, 'city' => 'Chesterton'],
                ['state_id' => 15, 'city' => 'Hebron'],
                ['state_id' => 15, 'city' => 'Kouts'],
                ['state_id' => 15, 'city' => 'Portage'],
                ['state_id' => 15, 'city' => 'Valparaiso'],
                ['state_id' => 15, 'city' => 'Wheeler'],
                ['state_id' => 15, 'city' => 'Cynthiana'],
                ['state_id' => 15, 'city' => 'Griffin'],
                ['state_id' => 15, 'city' => 'Mount Vernon'],
                ['state_id' => 15, 'city' => 'New Harmony'],
                ['state_id' => 15, 'city' => 'Poseyville'],
                ['state_id' => 15, 'city' => 'Wadesville'],
                ['state_id' => 15, 'city' => 'Monterey'],
                ['state_id' => 15, 'city' => 'Star City'],
                ['state_id' => 15, 'city' => 'Winamac'],
                ['state_id' => 15, 'city' => 'Francesville'],
                ['state_id' => 15, 'city' => 'Medaryville'],
                ['state_id' => 15, 'city' => 'Bainbridge'],
                ['state_id' => 15, 'city' => 'Cloverdale'],
                ['state_id' => 15, 'city' => 'Fillmore'],
                ['state_id' => 15, 'city' => 'Greencastle'],
                ['state_id' => 15, 'city' => 'Putnamville'],
                ['state_id' => 15, 'city' => 'Reelsville'],
                ['state_id' => 15, 'city' => 'Roachdale'],
                ['state_id' => 15, 'city' => 'Russellville'],
                ['state_id' => 15, 'city' => 'Farmland'],
                ['state_id' => 15, 'city' => 'Losantville'],
                ['state_id' => 15, 'city' => 'Lynn'],
                ['state_id' => 15, 'city' => 'Modoc'],
                ['state_id' => 15, 'city' => 'Parker City'],
                ['state_id' => 15, 'city' => 'Ridgeville'],
                ['state_id' => 15, 'city' => 'Saratoga'],
                ['state_id' => 15, 'city' => 'Union City'],
                ['state_id' => 15, 'city' => 'Winchester'],
                ['state_id' => 15, 'city' => 'Batesville'],
                ['state_id' => 15, 'city' => 'Cross Plains'],
                ['state_id' => 15, 'city' => 'Friendship'],
                ['state_id' => 15, 'city' => 'Holton'],
                ['state_id' => 15, 'city' => 'Milan'],
                ['state_id' => 15, 'city' => 'Morris'],
                ['state_id' => 15, 'city' => 'Napoleon'],
                ['state_id' => 15, 'city' => 'Osgood'],
                ['state_id' => 15, 'city' => 'Pierceville'],
                ['state_id' => 15, 'city' => 'Sunman'],
                ['state_id' => 15, 'city' => 'Versailles'],
                ['state_id' => 15, 'city' => 'Arlington'],
                ['state_id' => 15, 'city' => 'Carthage'],
                ['state_id' => 15, 'city' => 'Falmouth'],
                ['state_id' => 15, 'city' => 'Homer'],
                ['state_id' => 15, 'city' => 'Manilla'],
                ['state_id' => 15, 'city' => 'Mays'],
                ['state_id' => 15, 'city' => 'Milroy'],
                ['state_id' => 15, 'city' => 'Rushville'],
                ['state_id' => 15, 'city' => 'Granger'],
                ['state_id' => 15, 'city' => 'Lakeville'],
                ['state_id' => 15, 'city' => 'Mishawaka'],
                ['state_id' => 15, 'city' => 'New Carlisle'],
                ['state_id' => 15, 'city' => 'North Liberty'],
                ['state_id' => 15, 'city' => 'Notre Dame'],
                ['state_id' => 15, 'city' => 'Osceola'],
                ['state_id' => 15, 'city' => 'Walkerton'],
                ['state_id' => 15, 'city' => 'Wyatt'],
                ['state_id' => 15, 'city' => 'South Bend'],
                ['state_id' => 15, 'city' => 'Austin'],
                ['state_id' => 15, 'city' => 'Lexington'],
                ['state_id' => 15, 'city' => 'Scottsburg'],
                ['state_id' => 15, 'city' => 'Boggstown'],
                ['state_id' => 15, 'city' => 'Fairland'],
                ['state_id' => 15, 'city' => 'Fountaintown'],
                ['state_id' => 15, 'city' => 'Gwynneville'],
                ['state_id' => 15, 'city' => 'Morristown'],
                ['state_id' => 15, 'city' => 'Shelbyville'],
                ['state_id' => 15, 'city' => 'Waldron'],
                ['state_id' => 15, 'city' => 'Flat Rock'],
                ['state_id' => 15, 'city' => 'Dale'],
                ['state_id' => 15, 'city' => 'Evanston'],
                ['state_id' => 15, 'city' => 'Fulda'],
                ['state_id' => 15, 'city' => 'Gentryville'],
                ['state_id' => 15, 'city' => 'Lamar'],
                ['state_id' => 15, 'city' => 'Lincoln City'],
                ['state_id' => 15, 'city' => 'Mariah Hill'],
                ['state_id' => 15, 'city' => 'Saint Meinrad'],
                ['state_id' => 15, 'city' => 'Santa Claus'],
                ['state_id' => 15, 'city' => 'Troy'],
                ['state_id' => 15, 'city' => 'Chrisney'],
                ['state_id' => 15, 'city' => 'Grandview'],
                ['state_id' => 15, 'city' => 'Hatfield'],
                ['state_id' => 15, 'city' => 'Richland'],
                ['state_id' => 15, 'city' => 'Rockport'],
                ['state_id' => 15, 'city' => 'North Judson'],
                ['state_id' => 15, 'city' => 'San Pierre'],
                ['state_id' => 15, 'city' => 'Grovertown'],
                ['state_id' => 15, 'city' => 'Hamlet'],
                ['state_id' => 15, 'city' => 'Knox'],
                ['state_id' => 15, 'city' => 'Ora'],
                ['state_id' => 15, 'city' => 'Angola'],
                ['state_id' => 15, 'city' => 'Fremont'],
                ['state_id' => 15, 'city' => 'Hamilton'],
                ['state_id' => 15, 'city' => 'Hudson'],
                ['state_id' => 15, 'city' => 'Orland'],
                ['state_id' => 15, 'city' => 'Pleasant Lake'],
                ['state_id' => 15, 'city' => 'Carlisle'],
                ['state_id' => 15, 'city' => 'Dugger'],
                ['state_id' => 15, 'city' => 'Fairbanks'],
                ['state_id' => 15, 'city' => 'Farmersburg'],
                ['state_id' => 15, 'city' => 'Graysville'],
                ['state_id' => 15, 'city' => 'Hymera'],
                ['state_id' => 15, 'city' => 'Merom'],
                ['state_id' => 15, 'city' => 'Paxton'],
                ['state_id' => 15, 'city' => 'Shelburn'],
                ['state_id' => 15, 'city' => 'Sullivan'],
                ['state_id' => 15, 'city' => 'Bennington'],
                ['state_id' => 15, 'city' => 'East Enterprise'],
                ['state_id' => 15, 'city' => 'Florence'],
                ['state_id' => 15, 'city' => 'Patriot'],
                ['state_id' => 15, 'city' => 'Vevay'],
                ['state_id' => 15, 'city' => 'Lafayette'],
                ['state_id' => 15, 'city' => 'West Lafayette'],
                ['state_id' => 15, 'city' => 'Battle Ground'],
                ['state_id' => 15, 'city' => 'Buck Creek'],
                ['state_id' => 15, 'city' => 'Clarks Hill'],
                ['state_id' => 15, 'city' => 'Dayton'],
                ['state_id' => 15, 'city' => 'Montmorenci'],
                ['state_id' => 15, 'city' => 'Romney'],
                ['state_id' => 15, 'city' => 'Stockwell'],
                ['state_id' => 15, 'city' => 'Westpoint'],
                ['state_id' => 15, 'city' => 'Goldsmith'],
                ['state_id' => 15, 'city' => 'Hobbs'],
                ['state_id' => 15, 'city' => 'Kempton'],
                ['state_id' => 15, 'city' => 'Sharpsville'],
                ['state_id' => 15, 'city' => 'Tipton'],
                ['state_id' => 15, 'city' => 'Windfall'],
                ['state_id' => 15, 'city' => 'Brownsville'],
                ['state_id' => 15, 'city' => 'Liberty'],
                ['state_id' => 15, 'city' => 'Inglefield'],
                ['state_id' => 15, 'city' => 'Evansville'],
                ['state_id' => 15, 'city' => 'Blanford'],
                ['state_id' => 15, 'city' => 'Clinton'],
                ['state_id' => 15, 'city' => 'Dana'],
                ['state_id' => 15, 'city' => 'Hillsdale'],
                ['state_id' => 15, 'city' => 'Saint Bernice'],
                ['state_id' => 15, 'city' => 'Universal'],
                ['state_id' => 15, 'city' => 'Cayuga'],
                ['state_id' => 15, 'city' => 'Newport'],
                ['state_id' => 15, 'city' => 'Perrysville'],
                ['state_id' => 15, 'city' => 'Terre Haute'],
                ['state_id' => 15, 'city' => 'Fontanet'],
                ['state_id' => 15, 'city' => 'Lewis'],
                ['state_id' => 15, 'city' => 'New Goshen'],
                ['state_id' => 15, 'city' => 'Pimento'],
                ['state_id' => 15, 'city' => 'Prairie Creek'],
                ['state_id' => 15, 'city' => 'Prairieton'],
                ['state_id' => 15, 'city' => 'Riley'],
                ['state_id' => 15, 'city' => 'Saint Mary Of The Woods'],
                ['state_id' => 15, 'city' => 'Seelyville'],
                ['state_id' => 15, 'city' => 'Shepardsville'],
                ['state_id' => 15, 'city' => 'West Terre Haute'],
                ['state_id' => 15, 'city' => 'La Fontaine'],
                ['state_id' => 15, 'city' => 'Lagro'],
                ['state_id' => 15, 'city' => 'Laketon'],
                ['state_id' => 15, 'city' => 'Liberty Mills'],
                ['state_id' => 15, 'city' => 'North Manchester'],
                ['state_id' => 15, 'city' => 'Roann'],
                ['state_id' => 15, 'city' => 'Servia'],
                ['state_id' => 15, 'city' => 'Somerset'],
                ['state_id' => 15, 'city' => 'Urbana'],
                ['state_id' => 15, 'city' => 'Wabash'],
                ['state_id' => 15, 'city' => 'Pine Village'],
                ['state_id' => 15, 'city' => 'State Line'],
                ['state_id' => 15, 'city' => 'West Lebanon'],
                ['state_id' => 15, 'city' => 'Williamsport'],
                ['state_id' => 15, 'city' => 'Boonville'],
                ['state_id' => 15, 'city' => 'Chandler'],
                ['state_id' => 15, 'city' => 'Elberfeld'],
                ['state_id' => 15, 'city' => 'Lynnville'],
                ['state_id' => 15, 'city' => 'Newburgh'],
                ['state_id' => 15, 'city' => 'Tennyson'],
                ['state_id' => 15, 'city' => 'Campbellsburg'],
                ['state_id' => 15, 'city' => 'Fredericksburg'],
                ['state_id' => 15, 'city' => 'Hardinsburg'],
                ['state_id' => 15, 'city' => 'Pekin'],
                ['state_id' => 15, 'city' => 'Salem'],
                ['state_id' => 15, 'city' => 'Boston'],
                ['state_id' => 15, 'city' => 'Cambridge City'],
                ['state_id' => 15, 'city' => 'Centerville'],
                ['state_id' => 15, 'city' => 'Dublin'],
                ['state_id' => 15, 'city' => 'Economy'],
                ['state_id' => 15, 'city' => 'Fountain City'],
                ['state_id' => 15, 'city' => 'Greens Fork'],
                ['state_id' => 15, 'city' => 'Hagerstown'],
                ['state_id' => 15, 'city' => 'Milton'],
                ['state_id' => 15, 'city' => 'Pershing'],
                ['state_id' => 15, 'city' => 'Richmond'],
                ['state_id' => 15, 'city' => 'Webster'],
                ['state_id' => 15, 'city' => 'Williamsburg'],
                ['state_id' => 15, 'city' => 'Bluffton'],
                ['state_id' => 15, 'city' => 'Craigville'],
                ['state_id' => 15, 'city' => 'Keystone'],
                ['state_id' => 15, 'city' => 'Liberty Center'],
                ['state_id' => 15, 'city' => 'Ossian'],
                ['state_id' => 15, 'city' => 'Petroleum'],
                ['state_id' => 15, 'city' => 'Poneto'],
                ['state_id' => 15, 'city' => 'Uniondale'],
                ['state_id' => 15, 'city' => 'Brookston'],
                ['state_id' => 15, 'city' => 'Buffalo'],
                ['state_id' => 15, 'city' => 'Burnettsville'],
                ['state_id' => 15, 'city' => 'Chalmers'],
                ['state_id' => 15, 'city' => 'Idaville'],
                ['state_id' => 15, 'city' => 'Monon'],
                ['state_id' => 15, 'city' => 'Monticello'],
                ['state_id' => 15, 'city' => 'Reynolds'],
                ['state_id' => 15, 'city' => 'Wolcott'],
                ['state_id' => 15, 'city' => 'Churubusco'],
                ['state_id' => 15, 'city' => 'Columbia City'],
                ['state_id' => 15, 'city' => 'Larwill'],
                ['state_id' => 15, 'city' => 'South Whitley']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
