<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State16TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of IA - Iowa.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 16, 'city' => 'Adair'],
                ['state_id' => 16, 'city' => 'Bridgewater'],
                ['state_id' => 16, 'city' => 'Fontanelle'],
                ['state_id' => 16, 'city' => 'Greenfield'],
                ['state_id' => 16, 'city' => 'Orient'],
                ['state_id' => 16, 'city' => 'Carbon'],
                ['state_id' => 16, 'city' => 'Corning'],
                ['state_id' => 16, 'city' => 'Nodaway'],
                ['state_id' => 16, 'city' => 'Prescott'],
                ['state_id' => 16, 'city' => 'Dorchester'],
                ['state_id' => 16, 'city' => 'Harpers Ferry'],
                ['state_id' => 16, 'city' => 'Lansing'],
                ['state_id' => 16, 'city' => 'New Albin'],
                ['state_id' => 16, 'city' => 'Postville'],
                ['state_id' => 16, 'city' => 'Waterville'],
                ['state_id' => 16, 'city' => 'Waukon'],
                ['state_id' => 16, 'city' => 'Centerville'],
                ['state_id' => 16, 'city' => 'Cincinnati'],
                ['state_id' => 16, 'city' => 'Exline'],
                ['state_id' => 16, 'city' => 'Moravia'],
                ['state_id' => 16, 'city' => 'Moulton'],
                ['state_id' => 16, 'city' => 'Mystic'],
                ['state_id' => 16, 'city' => 'Plano'],
                ['state_id' => 16, 'city' => 'Udell'],
                ['state_id' => 16, 'city' => 'Unionville'],
                ['state_id' => 16, 'city' => 'Audubon'],
                ['state_id' => 16, 'city' => 'Brayton'],
                ['state_id' => 16, 'city' => 'Exira'],
                ['state_id' => 16, 'city' => 'Gray'],
                ['state_id' => 16, 'city' => 'Hamlin'],
                ['state_id' => 16, 'city' => 'Kimballton'],
                ['state_id' => 16, 'city' => 'Atkins'],
                ['state_id' => 16, 'city' => 'Belle Plaine'],
                ['state_id' => 16, 'city' => 'Blairstown'],
                ['state_id' => 16, 'city' => 'Garrison'],
                ['state_id' => 16, 'city' => 'Keystone'],
                ['state_id' => 16, 'city' => 'Luzerne'],
                ['state_id' => 16, 'city' => 'Mount Auburn'],
                ['state_id' => 16, 'city' => 'Newhall'],
                ['state_id' => 16, 'city' => 'Norway'],
                ['state_id' => 16, 'city' => 'Shellsburg'],
                ['state_id' => 16, 'city' => 'Urbana'],
                ['state_id' => 16, 'city' => 'Van Horne'],
                ['state_id' => 16, 'city' => 'Vinton'],
                ['state_id' => 16, 'city' => 'Walford'],
                ['state_id' => 16, 'city' => 'Watkins'],
                ['state_id' => 16, 'city' => 'Cedar Falls'],
                ['state_id' => 16, 'city' => 'Dewar'],
                ['state_id' => 16, 'city' => 'Dunkerton'],
                ['state_id' => 16, 'city' => 'Gilbertville'],
                ['state_id' => 16, 'city' => 'Hudson'],
                ['state_id' => 16, 'city' => 'La Porte City'],
                ['state_id' => 16, 'city' => 'Raymond'],
                ['state_id' => 16, 'city' => 'Waterloo'],
                ['state_id' => 16, 'city' => 'Evansdale'],
                ['state_id' => 16, 'city' => 'Beaver'],
                ['state_id' => 16, 'city' => 'Boone'],
                ['state_id' => 16, 'city' => 'Boxholm'],
                ['state_id' => 16, 'city' => 'Luther'],
                ['state_id' => 16, 'city' => 'Madrid'],
                ['state_id' => 16, 'city' => 'Ogden'],
                ['state_id' => 16, 'city' => 'Pilot Mound'],
                ['state_id' => 16, 'city' => 'Denver'],
                ['state_id' => 16, 'city' => 'Frederika'],
                ['state_id' => 16, 'city' => 'Janesville'],
                ['state_id' => 16, 'city' => 'Plainfield'],
                ['state_id' => 16, 'city' => 'Readlyn'],
                ['state_id' => 16, 'city' => 'Sumner'],
                ['state_id' => 16, 'city' => 'Tripoli'],
                ['state_id' => 16, 'city' => 'Waverly'],
                ['state_id' => 16, 'city' => 'Aurora'],
                ['state_id' => 16, 'city' => 'Fairbank'],
                ['state_id' => 16, 'city' => 'Hazleton'],
                ['state_id' => 16, 'city' => 'Independence'],
                ['state_id' => 16, 'city' => 'Jesup'],
                ['state_id' => 16, 'city' => 'Lamont'],
                ['state_id' => 16, 'city' => 'Stanley'],
                ['state_id' => 16, 'city' => 'Winthrop'],
                ['state_id' => 16, 'city' => 'Brandon'],
                ['state_id' => 16, 'city' => 'Quasqueton'],
                ['state_id' => 16, 'city' => 'Rowley'],
                ['state_id' => 16, 'city' => 'Albert City'],
                ['state_id' => 16, 'city' => 'Marathon'],
                ['state_id' => 16, 'city' => 'Newell'],
                ['state_id' => 16, 'city' => 'Rembrandt'],
                ['state_id' => 16, 'city' => 'Sioux Rapids'],
                ['state_id' => 16, 'city' => 'Storm Lake'],
                ['state_id' => 16, 'city' => 'Truesdale'],
                ['state_id' => 16, 'city' => 'Alta'],
                ['state_id' => 16, 'city' => 'Linn Grove'],
                ['state_id' => 16, 'city' => 'Allison'],
                ['state_id' => 16, 'city' => 'Aplington'],
                ['state_id' => 16, 'city' => 'Aredale'],
                ['state_id' => 16, 'city' => 'Austinville'],
                ['state_id' => 16, 'city' => 'Bristow'],
                ['state_id' => 16, 'city' => 'Clarksville'],
                ['state_id' => 16, 'city' => 'Dumont'],
                ['state_id' => 16, 'city' => 'Greene'],
                ['state_id' => 16, 'city' => 'Kesley'],
                ['state_id' => 16, 'city' => 'New Hartford'],
                ['state_id' => 16, 'city' => 'Parkersburg'],
                ['state_id' => 16, 'city' => 'Shell Rock'],
                ['state_id' => 16, 'city' => 'Farnhamville'],
                ['state_id' => 16, 'city' => 'Jolley'],
                ['state_id' => 16, 'city' => 'Knierim'],
                ['state_id' => 16, 'city' => 'Lytton'],
                ['state_id' => 16, 'city' => 'Manson'],
                ['state_id' => 16, 'city' => 'Pomeroy'],
                ['state_id' => 16, 'city' => 'Rockwell City'],
                ['state_id' => 16, 'city' => 'Somers'],
                ['state_id' => 16, 'city' => 'Lake City'],
                ['state_id' => 16, 'city' => 'Lohrville'],
                ['state_id' => 16, 'city' => 'Coon Rapids'],
                ['state_id' => 16, 'city' => 'Carroll'],
                ['state_id' => 16, 'city' => 'Arcadia'],
                ['state_id' => 16, 'city' => 'Breda'],
                ['state_id' => 16, 'city' => 'Dedham'],
                ['state_id' => 16, 'city' => 'Glidden'],
                ['state_id' => 16, 'city' => 'Halbur'],
                ['state_id' => 16, 'city' => 'Lanesboro'],
                ['state_id' => 16, 'city' => 'Lidderdale'],
                ['state_id' => 16, 'city' => 'Manning'],
                ['state_id' => 16, 'city' => 'Ralston'],
                ['state_id' => 16, 'city' => 'Templeton'],
                ['state_id' => 16, 'city' => 'Anita'],
                ['state_id' => 16, 'city' => 'Atlantic'],
                ['state_id' => 16, 'city' => 'Wiota'],
                ['state_id' => 16, 'city' => 'Cumberland'],
                ['state_id' => 16, 'city' => 'Massena'],
                ['state_id' => 16, 'city' => 'Griswold'],
                ['state_id' => 16, 'city' => 'Lewis'],
                ['state_id' => 16, 'city' => 'Marne'],
                ['state_id' => 16, 'city' => 'Clarence'],
                ['state_id' => 16, 'city' => 'Lowden'],
                ['state_id' => 16, 'city' => 'Mechanicsville'],
                ['state_id' => 16, 'city' => 'Stanwood'],
                ['state_id' => 16, 'city' => 'West Branch'],
                ['state_id' => 16, 'city' => 'Bennett'],
                ['state_id' => 16, 'city' => 'Durant'],
                ['state_id' => 16, 'city' => 'Tipton'],
                ['state_id' => 16, 'city' => 'Mason City'],
                ['state_id' => 16, 'city' => 'Clear Lake'],
                ['state_id' => 16, 'city' => 'Dougherty'],
                ['state_id' => 16, 'city' => 'Meservey'],
                ['state_id' => 16, 'city' => 'Plymouth'],
                ['state_id' => 16, 'city' => 'Rock Falls'],
                ['state_id' => 16, 'city' => 'Rockwell'],
                ['state_id' => 16, 'city' => 'Swaledale'],
                ['state_id' => 16, 'city' => 'Thornton'],
                ['state_id' => 16, 'city' => 'Ventura'],
                ['state_id' => 16, 'city' => 'Aurelia'],
                ['state_id' => 16, 'city' => 'Cherokee'],
                ['state_id' => 16, 'city' => 'Cleghorn'],
                ['state_id' => 16, 'city' => 'Larrabee'],
                ['state_id' => 16, 'city' => 'Marcus'],
                ['state_id' => 16, 'city' => 'Meriden'],
                ['state_id' => 16, 'city' => 'Quimby'],
                ['state_id' => 16, 'city' => 'Washta'],
                ['state_id' => 16, 'city' => 'Alta Vista'],
                ['state_id' => 16, 'city' => 'Fredericksburg'],
                ['state_id' => 16, 'city' => 'Ionia'],
                ['state_id' => 16, 'city' => 'Nashua'],
                ['state_id' => 16, 'city' => 'New Hampton'],
                ['state_id' => 16, 'city' => 'North Washington'],
                ['state_id' => 16, 'city' => 'Lawler'],
                ['state_id' => 16, 'city' => 'Murray'],
                ['state_id' => 16, 'city' => 'Osceola'],
                ['state_id' => 16, 'city' => 'Woodburn'],
                ['state_id' => 16, 'city' => 'Peterson'],
                ['state_id' => 16, 'city' => 'Spencer'],
                ['state_id' => 16, 'city' => 'Dickens'],
                ['state_id' => 16, 'city' => 'Everly'],
                ['state_id' => 16, 'city' => 'Fostoria'],
                ['state_id' => 16, 'city' => 'Gillett Grove'],
                ['state_id' => 16, 'city' => 'Greenville'],
                ['state_id' => 16, 'city' => 'Royal'],
                ['state_id' => 16, 'city' => 'Webb'],
                ['state_id' => 16, 'city' => 'Edgewood'],
                ['state_id' => 16, 'city' => 'Elkader'],
                ['state_id' => 16, 'city' => 'Elkport'],
                ['state_id' => 16, 'city' => 'Farmersburg'],
                ['state_id' => 16, 'city' => 'Garber'],
                ['state_id' => 16, 'city' => 'Garnavillo'],
                ['state_id' => 16, 'city' => 'Guttenberg'],
                ['state_id' => 16, 'city' => 'North Buena Vista'],
                ['state_id' => 16, 'city' => 'Saint Olaf'],
                ['state_id' => 16, 'city' => 'Strawberry Point'],
                ['state_id' => 16, 'city' => 'Volga'],
                ['state_id' => 16, 'city' => 'Luana'],
                ['state_id' => 16, 'city' => 'Mc Gregor'],
                ['state_id' => 16, 'city' => 'Marquette'],
                ['state_id' => 16, 'city' => 'Monona'],
                ['state_id' => 16, 'city' => 'Delmar'],
                ['state_id' => 16, 'city' => 'Lost Nation'],
                ['state_id' => 16, 'city' => 'Andover'],
                ['state_id' => 16, 'city' => 'Bryant'],
                ['state_id' => 16, 'city' => 'Calamus'],
                ['state_id' => 16, 'city' => 'Camanche'],
                ['state_id' => 16, 'city' => 'Charlotte'],
                ['state_id' => 16, 'city' => 'Clinton'],
                ['state_id' => 16, 'city' => 'De Witt'],
                ['state_id' => 16, 'city' => 'Goose Lake'],
                ['state_id' => 16, 'city' => 'Grand Mound'],
                ['state_id' => 16, 'city' => 'Low Moor'],
                ['state_id' => 16, 'city' => 'Teeds Grove'],
                ['state_id' => 16, 'city' => 'Welton'],
                ['state_id' => 16, 'city' => 'Wheatland'],
                ['state_id' => 16, 'city' => 'Aspinwall'],
                ['state_id' => 16, 'city' => 'Charter Oak'],
                ['state_id' => 16, 'city' => 'Deloit'],
                ['state_id' => 16, 'city' => 'Denison'],
                ['state_id' => 16, 'city' => 'Kiron'],
                ['state_id' => 16, 'city' => 'Manilla'],
                ['state_id' => 16, 'city' => 'Ricketts'],
                ['state_id' => 16, 'city' => 'Schleswig'],
                ['state_id' => 16, 'city' => 'Vail'],
                ['state_id' => 16, 'city' => 'Westside'],
                ['state_id' => 16, 'city' => 'Arion'],
                ['state_id' => 16, 'city' => 'Dow City'],
                ['state_id' => 16, 'city' => 'Adel'],
                ['state_id' => 16, 'city' => 'Booneville'],
                ['state_id' => 16, 'city' => 'Bouton'],
                ['state_id' => 16, 'city' => 'Dallas Center'],
                ['state_id' => 16, 'city' => 'Dawson'],
                ['state_id' => 16, 'city' => 'De Soto'],
                ['state_id' => 16, 'city' => 'Dexter'],
                ['state_id' => 16, 'city' => 'Granger'],
                ['state_id' => 16, 'city' => 'Linden'],
                ['state_id' => 16, 'city' => 'Minburn'],
                ['state_id' => 16, 'city' => 'Perry'],
                ['state_id' => 16, 'city' => 'Redfield'],
                ['state_id' => 16, 'city' => 'Van Meter'],
                ['state_id' => 16, 'city' => 'Waukee'],
                ['state_id' => 16, 'city' => 'Woodward'],
                ['state_id' => 16, 'city' => 'Bloomfield'],
                ['state_id' => 16, 'city' => 'Drakesville'],
                ['state_id' => 16, 'city' => 'Floris'],
                ['state_id' => 16, 'city' => 'Pulaski'],
                ['state_id' => 16, 'city' => 'Davis City'],
                ['state_id' => 16, 'city' => 'Decatur'],
                ['state_id' => 16, 'city' => 'Garden Grove'],
                ['state_id' => 16, 'city' => 'Grand River'],
                ['state_id' => 16, 'city' => 'Lamoni'],
                ['state_id' => 16, 'city' => 'Leon'],
                ['state_id' => 16, 'city' => 'Van Wert'],
                ['state_id' => 16, 'city' => 'Weldon'],
                ['state_id' => 16, 'city' => 'Masonville'],
                ['state_id' => 16, 'city' => 'Colesburg'],
                ['state_id' => 16, 'city' => 'Delaware'],
                ['state_id' => 16, 'city' => 'Dundee'],
                ['state_id' => 16, 'city' => 'Earlville'],
                ['state_id' => 16, 'city' => 'Greeley'],
                ['state_id' => 16, 'city' => 'Manchester'],
                ['state_id' => 16, 'city' => 'Delhi'],
                ['state_id' => 16, 'city' => 'Hopkinton'],
                ['state_id' => 16, 'city' => 'Ryan'],
                ['state_id' => 16, 'city' => 'Burlington'],
                ['state_id' => 16, 'city' => 'Danville'],
                ['state_id' => 16, 'city' => 'Mediapolis'],
                ['state_id' => 16, 'city' => 'Middletown'],
                ['state_id' => 16, 'city' => 'Sperry'],
                ['state_id' => 16, 'city' => 'West Burlington'],
                ['state_id' => 16, 'city' => 'Yarmouth'],
                ['state_id' => 16, 'city' => 'Arnolds Park'],
                ['state_id' => 16, 'city' => 'Lake Park'],
                ['state_id' => 16, 'city' => 'Milford'],
                ['state_id' => 16, 'city' => 'Okoboji'],
                ['state_id' => 16, 'city' => 'Spirit Lake'],
                ['state_id' => 16, 'city' => 'Superior'],
                ['state_id' => 16, 'city' => 'Terril'],
                ['state_id' => 16, 'city' => 'Dubuque'],
                ['state_id' => 16, 'city' => 'Bernard'],
                ['state_id' => 16, 'city' => 'Cascade'],
                ['state_id' => 16, 'city' => 'Durango'],
                ['state_id' => 16, 'city' => 'Dyersville'],
                ['state_id' => 16, 'city' => 'Epworth'],
                ['state_id' => 16, 'city' => 'Farley'],
                ['state_id' => 16, 'city' => 'Holy Cross'],
                ['state_id' => 16, 'city' => 'Luxemburg'],
                ['state_id' => 16, 'city' => 'New Vienna'],
                ['state_id' => 16, 'city' => 'Peosta'],
                ['state_id' => 16, 'city' => 'Sherrill'],
                ['state_id' => 16, 'city' => 'Worthington'],
                ['state_id' => 16, 'city' => 'Zwingle'],
                ['state_id' => 16, 'city' => 'Armstrong'],
                ['state_id' => 16, 'city' => 'Dolliver'],
                ['state_id' => 16, 'city' => 'Ringsted'],
                ['state_id' => 16, 'city' => 'Estherville'],
                ['state_id' => 16, 'city' => 'Wallingford'],
                ['state_id' => 16, 'city' => 'Arlington'],
                ['state_id' => 16, 'city' => 'Maynard'],
                ['state_id' => 16, 'city' => 'Oelwein'],
                ['state_id' => 16, 'city' => 'Oran'],
                ['state_id' => 16, 'city' => 'Westgate'],
                ['state_id' => 16, 'city' => 'Clermont'],
                ['state_id' => 16, 'city' => 'Elgin'],
                ['state_id' => 16, 'city' => 'Fayette'],
                ['state_id' => 16, 'city' => 'Hawkeye'],
                ['state_id' => 16, 'city' => 'Randalia'],
                ['state_id' => 16, 'city' => 'Saint Lucas'],
                ['state_id' => 16, 'city' => 'Wadena'],
                ['state_id' => 16, 'city' => 'Waucoma'],
                ['state_id' => 16, 'city' => 'West Union'],
                ['state_id' => 16, 'city' => 'Floyd'],
                ['state_id' => 16, 'city' => 'Nora Springs'],
                ['state_id' => 16, 'city' => 'Rockford'],
                ['state_id' => 16, 'city' => 'Rudd'],
                ['state_id' => 16, 'city' => 'Charles City'],
                ['state_id' => 16, 'city' => 'Colwell'],
                ['state_id' => 16, 'city' => 'Marble Rock'],
                ['state_id' => 16, 'city' => 'Bradford'],
                ['state_id' => 16, 'city' => 'Popejoy'],
                ['state_id' => 16, 'city' => 'Alexander'],
                ['state_id' => 16, 'city' => 'Chapin'],
                ['state_id' => 16, 'city' => 'Coulter'],
                ['state_id' => 16, 'city' => 'Hampton'],
                ['state_id' => 16, 'city' => 'Latimer'],
                ['state_id' => 16, 'city' => 'Sheffield'],
                ['state_id' => 16, 'city' => 'Geneva'],
                ['state_id' => 16, 'city' => 'Farragut'],
                ['state_id' => 16, 'city' => 'Hamburg'],
                ['state_id' => 16, 'city' => 'Imogene'],
                ['state_id' => 16, 'city' => 'Percival'],
                ['state_id' => 16, 'city' => 'Randolph'],
                ['state_id' => 16, 'city' => 'Riverton'],
                ['state_id' => 16, 'city' => 'Sidney'],
                ['state_id' => 16, 'city' => 'Tabor'],
                ['state_id' => 16, 'city' => 'Thurman'],
                ['state_id' => 16, 'city' => 'Churdan'],
                ['state_id' => 16, 'city' => 'Cooper'],
                ['state_id' => 16, 'city' => 'Dana'],
                ['state_id' => 16, 'city' => 'Grand Junction'],
                ['state_id' => 16, 'city' => 'Jefferson'],
                ['state_id' => 16, 'city' => 'Paton'],
                ['state_id' => 16, 'city' => 'Rippey'],
                ['state_id' => 16, 'city' => 'Scranton'],
                ['state_id' => 16, 'city' => 'Beaman'],
                ['state_id' => 16, 'city' => 'Conrad'],
                ['state_id' => 16, 'city' => 'Dike'],
                ['state_id' => 16, 'city' => 'Grundy Center'],
                ['state_id' => 16, 'city' => 'Holland'],
                ['state_id' => 16, 'city' => 'Morrison'],
                ['state_id' => 16, 'city' => 'Reinbeck'],
                ['state_id' => 16, 'city' => 'Stout'],
                ['state_id' => 16, 'city' => 'Wellsburg'],
                ['state_id' => 16, 'city' => 'Bagley'],
                ['state_id' => 16, 'city' => 'Bayard'],
                ['state_id' => 16, 'city' => 'Casey'],
                ['state_id' => 16, 'city' => 'Guthrie Center'],
                ['state_id' => 16, 'city' => 'Jamaica'],
                ['state_id' => 16, 'city' => 'Menlo'],
                ['state_id' => 16, 'city' => 'Panora'],
                ['state_id' => 16, 'city' => 'Stuart'],
                ['state_id' => 16, 'city' => 'Yale'],
                ['state_id' => 16, 'city' => 'Blairsburg'],
                ['state_id' => 16, 'city' => 'Ellsworth'],
                ['state_id' => 16, 'city' => 'Jewell'],
                ['state_id' => 16, 'city' => 'Kamrar'],
                ['state_id' => 16, 'city' => 'Randall'],
                ['state_id' => 16, 'city' => 'Stanhope'],
                ['state_id' => 16, 'city' => 'Stratford'],
                ['state_id' => 16, 'city' => 'Williams'],
                ['state_id' => 16, 'city' => 'Webster City'],
                ['state_id' => 16, 'city' => 'Britt'],
                ['state_id' => 16, 'city' => 'Corwith'],
                ['state_id' => 16, 'city' => 'Crystal Lake'],
                ['state_id' => 16, 'city' => 'Garner'],
                ['state_id' => 16, 'city' => 'Goodell'],
                ['state_id' => 16, 'city' => 'Kanawha'],
                ['state_id' => 16, 'city' => 'Klemme'],
                ['state_id' => 16, 'city' => 'Woden'],
                ['state_id' => 16, 'city' => 'Alden'],
                ['state_id' => 16, 'city' => 'Buckeye'],
                ['state_id' => 16, 'city' => 'Garden City'],
                ['state_id' => 16, 'city' => 'Hubbard'],
                ['state_id' => 16, 'city' => 'Iowa Falls'],
                ['state_id' => 16, 'city' => 'New Providence'],
                ['state_id' => 16, 'city' => 'Radcliffe'],
                ['state_id' => 16, 'city' => 'Union'],
                ['state_id' => 16, 'city' => 'Gifford'],
                ['state_id' => 16, 'city' => 'Whitten'],
                ['state_id' => 16, 'city' => 'Ackley'],
                ['state_id' => 16, 'city' => 'Eldora'],
                ['state_id' => 16, 'city' => 'Steamboat Rock'],
                ['state_id' => 16, 'city' => 'Dunlap'],
                ['state_id' => 16, 'city' => 'Little Sioux'],
                ['state_id' => 16, 'city' => 'Logan'],
                ['state_id' => 16, 'city' => 'Magnolia'],
                ['state_id' => 16, 'city' => 'Missouri Valley'],
                ['state_id' => 16, 'city' => 'Modale'],
                ['state_id' => 16, 'city' => 'Mondamin'],
                ['state_id' => 16, 'city' => 'Persia'],
                ['state_id' => 16, 'city' => 'Pisgah'],
                ['state_id' => 16, 'city' => 'Woodbine'],
                ['state_id' => 16, 'city' => 'Hillsboro'],
                ['state_id' => 16, 'city' => 'Mount Pleasant'],
                ['state_id' => 16, 'city' => 'Rome'],
                ['state_id' => 16, 'city' => 'Mount Union'],
                ['state_id' => 16, 'city' => 'New London'],
                ['state_id' => 16, 'city' => 'Olds'],
                ['state_id' => 16, 'city' => 'Salem'],
                ['state_id' => 16, 'city' => 'Swedesburg'],
                ['state_id' => 16, 'city' => 'Wayland'],
                ['state_id' => 16, 'city' => 'Winfield'],
                ['state_id' => 16, 'city' => 'Riceville'],
                ['state_id' => 16, 'city' => 'Elma'],
                ['state_id' => 16, 'city' => 'Chester'],
                ['state_id' => 16, 'city' => 'Cresco'],
                ['state_id' => 16, 'city' => 'Lime Springs'],
                ['state_id' => 16, 'city' => 'Protivin'],
                ['state_id' => 16, 'city' => 'Bode'],
                ['state_id' => 16, 'city' => 'Bradgate'],
                ['state_id' => 16, 'city' => 'Dakota City'],
                ['state_id' => 16, 'city' => 'Gilmore City'],
                ['state_id' => 16, 'city' => 'Hardy'],
                ['state_id' => 16, 'city' => 'Humboldt'],
                ['state_id' => 16, 'city' => 'Livermore'],
                ['state_id' => 16, 'city' => 'Ottosen'],
                ['state_id' => 16, 'city' => 'Renwick'],
                ['state_id' => 16, 'city' => 'Rutland'],
                ['state_id' => 16, 'city' => 'Thor'],
                ['state_id' => 16, 'city' => 'Battle Creek'],
                ['state_id' => 16, 'city' => 'Galva'],
                ['state_id' => 16, 'city' => 'Holstein'],
                ['state_id' => 16, 'city' => 'Arthur'],
                ['state_id' => 16, 'city' => 'Ida Grove'],
                ['state_id' => 16, 'city' => 'Amana'],
                ['state_id' => 16, 'city' => 'Conroy'],
                ['state_id' => 16, 'city' => 'Homestead'],
                ['state_id' => 16, 'city' => 'Ladora'],
                ['state_id' => 16, 'city' => 'Marengo'],
                ['state_id' => 16, 'city' => 'Middle Amana'],
                ['state_id' => 16, 'city' => 'Millersburg'],
                ['state_id' => 16, 'city' => 'North English'],
                ['state_id' => 16, 'city' => 'Parnell'],
                ['state_id' => 16, 'city' => 'South Amana'],
                ['state_id' => 16, 'city' => 'Victor'],
                ['state_id' => 16, 'city' => 'Williamsburg'],
                ['state_id' => 16, 'city' => 'Andrew'],
                ['state_id' => 16, 'city' => 'Bellevue'],
                ['state_id' => 16, 'city' => 'La Motte'],
                ['state_id' => 16, 'city' => 'Maquoketa'],
                ['state_id' => 16, 'city' => 'Miles'],
                ['state_id' => 16, 'city' => 'Preston'],
                ['state_id' => 16, 'city' => 'Sabula'],
                ['state_id' => 16, 'city' => 'Saint Donatus'],
                ['state_id' => 16, 'city' => 'Spragueville'],
                ['state_id' => 16, 'city' => 'Springbrook'],
                ['state_id' => 16, 'city' => 'Baldwin'],
                ['state_id' => 16, 'city' => 'Monmouth'],
                ['state_id' => 16, 'city' => 'Baxter'],
                ['state_id' => 16, 'city' => 'Colfax'],
                ['state_id' => 16, 'city' => 'Ira'],
                ['state_id' => 16, 'city' => 'Kellogg'],
                ['state_id' => 16, 'city' => 'Killduff'],
                ['state_id' => 16, 'city' => 'Lynnville'],
                ['state_id' => 16, 'city' => 'Mingo'],
                ['state_id' => 16, 'city' => 'Monroe'],
                ['state_id' => 16, 'city' => 'Newton'],
                ['state_id' => 16, 'city' => 'Prairie City'],
                ['state_id' => 16, 'city' => 'Reasnor'],
                ['state_id' => 16, 'city' => 'Sully'],
                ['state_id' => 16, 'city' => 'Batavia'],
                ['state_id' => 16, 'city' => 'Fairfield'],
                ['state_id' => 16, 'city' => 'Libertyville'],
                ['state_id' => 16, 'city' => 'Packwood'],
                ['state_id' => 16, 'city' => 'Lockridge'],
                ['state_id' => 16, 'city' => 'Hills'],
                ['state_id' => 16, 'city' => 'Iowa City'],
                ['state_id' => 16, 'city' => 'Coralville'],
                ['state_id' => 16, 'city' => 'North Liberty'],
                ['state_id' => 16, 'city' => 'Oxford'],
                ['state_id' => 16, 'city' => 'Solon'],
                ['state_id' => 16, 'city' => 'Swisher'],
                ['state_id' => 16, 'city' => 'Tiffin'],
                ['state_id' => 16, 'city' => 'Lone Tree'],
                ['state_id' => 16, 'city' => 'Anamosa'],
                ['state_id' => 16, 'city' => 'Center Junction'],
                ['state_id' => 16, 'city' => 'Langworthy'],
                ['state_id' => 16, 'city' => 'Martelle'],
                ['state_id' => 16, 'city' => 'Monticello'],
                ['state_id' => 16, 'city' => 'Morley'],
                ['state_id' => 16, 'city' => 'Olin'],
                ['state_id' => 16, 'city' => 'Onslow'],
                ['state_id' => 16, 'city' => 'Oxford Junction'],
                ['state_id' => 16, 'city' => 'Wyoming'],
                ['state_id' => 16, 'city' => 'Gibson'],
                ['state_id' => 16, 'city' => 'Keswick'],
                ['state_id' => 16, 'city' => 'Thornburg'],
                ['state_id' => 16, 'city' => 'What Cheer'],
                ['state_id' => 16, 'city' => 'Harper'],
                ['state_id' => 16, 'city' => 'Keota'],
                ['state_id' => 16, 'city' => 'South English'],
                ['state_id' => 16, 'city' => 'Webster'],
                ['state_id' => 16, 'city' => 'Delta'],
                ['state_id' => 16, 'city' => 'Hayesville'],
                ['state_id' => 16, 'city' => 'Hedrick'],
                ['state_id' => 16, 'city' => 'Martinsburg'],
                ['state_id' => 16, 'city' => 'Ollie'],
                ['state_id' => 16, 'city' => 'Richland'],
                ['state_id' => 16, 'city' => 'Sigourney'],
                ['state_id' => 16, 'city' => 'Lakota'],
                ['state_id' => 16, 'city' => 'Titonka'],
                ['state_id' => 16, 'city' => 'Wesley'],
                ['state_id' => 16, 'city' => 'Algona'],
                ['state_id' => 16, 'city' => 'Bancroft'],
                ['state_id' => 16, 'city' => 'Burt'],
                ['state_id' => 16, 'city' => 'Fenton'],
                ['state_id' => 16, 'city' => 'Ledyard'],
                ['state_id' => 16, 'city' => 'Lone Rock'],
                ['state_id' => 16, 'city' => 'Lu Verne'],
                ['state_id' => 16, 'city' => 'Swea City'],
                ['state_id' => 16, 'city' => 'Whittemore'],
                ['state_id' => 16, 'city' => 'Argyle'],
                ['state_id' => 16, 'city' => 'Denmark'],
                ['state_id' => 16, 'city' => 'Donnellson'],
                ['state_id' => 16, 'city' => 'Fort Madison'],
                ['state_id' => 16, 'city' => 'Houghton'],
                ['state_id' => 16, 'city' => 'Keokuk'],
                ['state_id' => 16, 'city' => 'Montrose'],
                ['state_id' => 16, 'city' => 'Pilot Grove'],
                ['state_id' => 16, 'city' => 'West Point'],
                ['state_id' => 16, 'city' => 'Saint Paul'],
                ['state_id' => 16, 'city' => 'Wever'],
                ['state_id' => 16, 'city' => 'Alburnett'],
                ['state_id' => 16, 'city' => 'Center Point'],
                ['state_id' => 16, 'city' => 'Central City'],
                ['state_id' => 16, 'city' => 'Coggon'],
                ['state_id' => 16, 'city' => 'Prairieburg'],
                ['state_id' => 16, 'city' => 'Ely'],
                ['state_id' => 16, 'city' => 'Fairfax'],
                ['state_id' => 16, 'city' => 'Hiawatha'],
                ['state_id' => 16, 'city' => 'Lisbon'],
                ['state_id' => 16, 'city' => 'Marion'],
                ['state_id' => 16, 'city' => 'Mount Vernon'],
                ['state_id' => 16, 'city' => 'Palo'],
                ['state_id' => 16, 'city' => 'Robins'],
                ['state_id' => 16, 'city' => 'Springville'],
                ['state_id' => 16, 'city' => 'Toddville'],
                ['state_id' => 16, 'city' => 'Troy Mills'],
                ['state_id' => 16, 'city' => 'Walker'],
                ['state_id' => 16, 'city' => 'Cedar Rapids'],
                ['state_id' => 16, 'city' => 'Morning Sun'],
                ['state_id' => 16, 'city' => 'Oakville'],
                ['state_id' => 16, 'city' => 'Wapello'],
                ['state_id' => 16, 'city' => 'Columbus City'],
                ['state_id' => 16, 'city' => 'Columbus Junction'],
                ['state_id' => 16, 'city' => 'Grandview'],
                ['state_id' => 16, 'city' => 'Letts'],
                ['state_id' => 16, 'city' => 'Chariton'],
                ['state_id' => 16, 'city' => 'Derby'],
                ['state_id' => 16, 'city' => 'Lucas'],
                ['state_id' => 16, 'city' => 'Russell'],
                ['state_id' => 16, 'city' => 'Williamson'],
                ['state_id' => 16, 'city' => 'Alvord'],
                ['state_id' => 16, 'city' => 'Doon'],
                ['state_id' => 16, 'city' => 'George'],
                ['state_id' => 16, 'city' => 'Inwood'],
                ['state_id' => 16, 'city' => 'Larchwood'],
                ['state_id' => 16, 'city' => 'Lester'],
                ['state_id' => 16, 'city' => 'Little Rock'],
                ['state_id' => 16, 'city' => 'Rock Rapids'],
                ['state_id' => 16, 'city' => 'Bevington'],
                ['state_id' => 16, 'city' => 'Earlham'],
                ['state_id' => 16, 'city' => 'Macksburg'],
                ['state_id' => 16, 'city' => 'Patterson'],
                ['state_id' => 16, 'city' => 'Peru'],
                ['state_id' => 16, 'city' => 'Saint Charles'],
                ['state_id' => 16, 'city' => 'Truro'],
                ['state_id' => 16, 'city' => 'Winterset'],
                ['state_id' => 16, 'city' => 'Barnes City'],
                ['state_id' => 16, 'city' => 'Leighton'],
                ['state_id' => 16, 'city' => 'New Sharon'],
                ['state_id' => 16, 'city' => 'Beacon'],
                ['state_id' => 16, 'city' => 'Cedar'],
                ['state_id' => 16, 'city' => 'Fremont'],
                ['state_id' => 16, 'city' => 'Oskaloosa'],
                ['state_id' => 16, 'city' => 'Rose Hill'],
                ['state_id' => 16, 'city' => 'University Park'],
                ['state_id' => 16, 'city' => 'Bussey'],
                ['state_id' => 16, 'city' => 'Columbia'],
                ['state_id' => 16, 'city' => 'Melcher Dallas'],
                ['state_id' => 16, 'city' => 'Hamilton'],
                ['state_id' => 16, 'city' => 'Harvey'],
                ['state_id' => 16, 'city' => 'Knoxville'],
                ['state_id' => 16, 'city' => 'Otley'],
                ['state_id' => 16, 'city' => 'Pella'],
                ['state_id' => 16, 'city' => 'Pleasantville'],
                ['state_id' => 16, 'city' => 'Swan'],
                ['state_id' => 16, 'city' => 'Tracy'],
                ['state_id' => 16, 'city' => 'Albion'],
                ['state_id' => 16, 'city' => 'Clemons'],
                ['state_id' => 16, 'city' => 'Ferguson'],
                ['state_id' => 16, 'city' => 'Gilman'],
                ['state_id' => 16, 'city' => 'Haverhill'],
                ['state_id' => 16, 'city' => 'Laurel'],
                ['state_id' => 16, 'city' => 'Le Grand'],
                ['state_id' => 16, 'city' => 'Liscomb'],
                ['state_id' => 16, 'city' => 'Marshalltown'],
                ['state_id' => 16, 'city' => 'Melbourne'],
                ['state_id' => 16, 'city' => 'Rhodes'],
                ['state_id' => 16, 'city' => 'Saint Anthony'],
                ['state_id' => 16, 'city' => 'State Center'],
                ['state_id' => 16, 'city' => 'Emerson'],
                ['state_id' => 16, 'city' => 'Glenwood'],
                ['state_id' => 16, 'city' => 'Hastings'],
                ['state_id' => 16, 'city' => 'Henderson'],
                ['state_id' => 16, 'city' => 'Malvern'],
                ['state_id' => 16, 'city' => 'Mineola'],
                ['state_id' => 16, 'city' => 'Pacific Junction'],
                ['state_id' => 16, 'city' => 'Silver City'],
                ['state_id' => 16, 'city' => 'Carpenter'],
                ['state_id' => 16, 'city' => 'Little Cedar'],
                ['state_id' => 16, 'city' => 'Mc Intire'],
                ['state_id' => 16, 'city' => 'Orchard'],
                ['state_id' => 16, 'city' => 'Osage'],
                ['state_id' => 16, 'city' => 'Saint Ansgar'],
                ['state_id' => 16, 'city' => 'Stacyville'],
                ['state_id' => 16, 'city' => 'Toeterville'],
                ['state_id' => 16, 'city' => 'Castana'],
                ['state_id' => 16, 'city' => 'Mapleton'],
                ['state_id' => 16, 'city' => 'Onawa'],
                ['state_id' => 16, 'city' => 'Rodney'],
                ['state_id' => 16, 'city' => 'Ute'],
                ['state_id' => 16, 'city' => 'Whiting'],
                ['state_id' => 16, 'city' => 'Blencoe'],
                ['state_id' => 16, 'city' => 'Moorhead'],
                ['state_id' => 16, 'city' => 'Soldier'],
                ['state_id' => 16, 'city' => 'Lovilia'],
                ['state_id' => 16, 'city' => 'Albia'],
                ['state_id' => 16, 'city' => 'Melrose'],
                ['state_id' => 16, 'city' => 'Grant'],
                ['state_id' => 16, 'city' => 'Villisca'],
                ['state_id' => 16, 'city' => 'Elliott'],
                ['state_id' => 16, 'city' => 'Red Oak'],
                ['state_id' => 16, 'city' => 'Stanton'],
                ['state_id' => 16, 'city' => 'Atalissa'],
                ['state_id' => 16, 'city' => 'Conesville'],
                ['state_id' => 16, 'city' => 'Fruitland'],
                ['state_id' => 16, 'city' => 'Montpelier'],
                ['state_id' => 16, 'city' => 'Moscow'],
                ['state_id' => 16, 'city' => 'Muscatine'],
                ['state_id' => 16, 'city' => 'Nichols'],
                ['state_id' => 16, 'city' => 'Stockton'],
                ['state_id' => 16, 'city' => 'West Liberty'],
                ['state_id' => 16, 'city' => 'Wilton'],
                ['state_id' => 16, 'city' => 'Calumet'],
                ['state_id' => 16, 'city' => 'Paullina'],
                ['state_id' => 16, 'city' => 'Sutherland'],
                ['state_id' => 16, 'city' => 'Sheldon'],
                ['state_id' => 16, 'city' => 'Archer'],
                ['state_id' => 16, 'city' => 'Primghar'],
                ['state_id' => 16, 'city' => 'Sanborn'],
                ['state_id' => 16, 'city' => 'Hartley'],
                ['state_id' => 16, 'city' => 'Ashton'],
                ['state_id' => 16, 'city' => 'Sibley'],
                ['state_id' => 16, 'city' => 'Harris'],
                ['state_id' => 16, 'city' => 'Melvin'],
                ['state_id' => 16, 'city' => 'Ocheyedan'],
                ['state_id' => 16, 'city' => 'Shenandoah'],
                ['state_id' => 16, 'city' => 'Blanchard'],
                ['state_id' => 16, 'city' => 'Braddyville'],
                ['state_id' => 16, 'city' => 'Clarinda'],
                ['state_id' => 16, 'city' => 'Coin'],
                ['state_id' => 16, 'city' => 'College Springs'],
                ['state_id' => 16, 'city' => 'Essex'],
                ['state_id' => 16, 'city' => 'Northboro'],
                ['state_id' => 16, 'city' => 'Shambaugh'],
                ['state_id' => 16, 'city' => 'Yorktown'],
                ['state_id' => 16, 'city' => 'Ayrshire'],
                ['state_id' => 16, 'city' => 'Curlew'],
                ['state_id' => 16, 'city' => 'Cylinder'],
                ['state_id' => 16, 'city' => 'Emmetsburg'],
                ['state_id' => 16, 'city' => 'Mallard'],
                ['state_id' => 16, 'city' => 'West Bend'],
                ['state_id' => 16, 'city' => 'Graettinger'],
                ['state_id' => 16, 'city' => 'Ruthven'],
                ['state_id' => 16, 'city' => 'Akron'],
                ['state_id' => 16, 'city' => 'Brunsville'],
                ['state_id' => 16, 'city' => 'Hinton'],
                ['state_id' => 16, 'city' => 'Kingsley'],
                ['state_id' => 16, 'city' => 'Le Mars'],
                ['state_id' => 16, 'city' => 'Merrill'],
                ['state_id' => 16, 'city' => 'Oyens'],
                ['state_id' => 16, 'city' => 'Remsen'],
                ['state_id' => 16, 'city' => 'Westfield'],
                ['state_id' => 16, 'city' => 'Fonda'],
                ['state_id' => 16, 'city' => 'Havelock'],
                ['state_id' => 16, 'city' => 'Laurens'],
                ['state_id' => 16, 'city' => 'Palmer'],
                ['state_id' => 16, 'city' => 'Plover'],
                ['state_id' => 16, 'city' => 'Pocahontas'],
                ['state_id' => 16, 'city' => 'Rolfe'],
                ['state_id' => 16, 'city' => 'Varina'],
                ['state_id' => 16, 'city' => 'Alleman'],
                ['state_id' => 16, 'city' => 'Altoona'],
                ['state_id' => 16, 'city' => 'Ankeny'],
                ['state_id' => 16, 'city' => 'Berwick'],
                ['state_id' => 16, 'city' => 'Bondurant'],
                ['state_id' => 16, 'city' => 'Elkhart'],
                ['state_id' => 16, 'city' => 'Grimes'],
                ['state_id' => 16, 'city' => 'Johnston'],
                ['state_id' => 16, 'city' => 'Mitchellville'],
                ['state_id' => 16, 'city' => 'Polk City'],
                ['state_id' => 16, 'city' => 'Runnells'],
                ['state_id' => 16, 'city' => 'Sheldahl'],
                ['state_id' => 16, 'city' => 'West Des Moines'],
                ['state_id' => 16, 'city' => 'Des Moines'],
                ['state_id' => 16, 'city' => 'Urbandale'],
                ['state_id' => 16, 'city' => 'Windsor Heights'],
                ['state_id' => 16, 'city' => 'Clive'],
                ['state_id' => 16, 'city' => 'Pleasant Hill'],
                ['state_id' => 16, 'city' => 'Council Bluffs'],
                ['state_id' => 16, 'city' => 'Carter Lake'],
                ['state_id' => 16, 'city' => 'Avoca'],
                ['state_id' => 16, 'city' => 'Carson'],
                ['state_id' => 16, 'city' => 'Crescent'],
                ['state_id' => 16, 'city' => 'Hancock'],
                ['state_id' => 16, 'city' => 'Honey Creek'],
                ['state_id' => 16, 'city' => 'Mc Clelland'],
                ['state_id' => 16, 'city' => 'Macedonia'],
                ['state_id' => 16, 'city' => 'Minden'],
                ['state_id' => 16, 'city' => 'Neola'],
                ['state_id' => 16, 'city' => 'Oakland'],
                ['state_id' => 16, 'city' => 'Shelby'],
                ['state_id' => 16, 'city' => 'Treynor'],
                ['state_id' => 16, 'city' => 'Underwood'],
                ['state_id' => 16, 'city' => 'Walnut'],
                ['state_id' => 16, 'city' => 'Harlan'],
                ['state_id' => 16, 'city' => 'Grinnell'],
                ['state_id' => 16, 'city' => 'Malcom'],
                ['state_id' => 16, 'city' => 'Montezuma'],
                ['state_id' => 16, 'city' => 'Searsboro'],
                ['state_id' => 16, 'city' => 'Brooklyn'],
                ['state_id' => 16, 'city' => 'Guernsey'],
                ['state_id' => 16, 'city' => 'Deep River'],
                ['state_id' => 16, 'city' => 'Hartwick'],
                ['state_id' => 16, 'city' => 'Ellston'],
                ['state_id' => 16, 'city' => 'Kellerton'],
                ['state_id' => 16, 'city' => 'Benton'],
                ['state_id' => 16, 'city' => 'Diagonal'],
                ['state_id' => 16, 'city' => 'Mount Ayr'],
                ['state_id' => 16, 'city' => 'Redding'],
                ['state_id' => 16, 'city' => 'Tingley'],
                ['state_id' => 16, 'city' => 'Early'],
                ['state_id' => 16, 'city' => 'Nemaha'],
                ['state_id' => 16, 'city' => 'Sac City'],
                ['state_id' => 16, 'city' => 'Schaller'],
                ['state_id' => 16, 'city' => 'Auburn'],
                ['state_id' => 16, 'city' => 'Lake View'],
                ['state_id' => 16, 'city' => 'Odebolt'],
                ['state_id' => 16, 'city' => 'Wall Lake'],
                ['state_id' => 16, 'city' => 'Bettendorf'],
                ['state_id' => 16, 'city' => 'Blue Grass'],
                ['state_id' => 16, 'city' => 'Buffalo'],
                ['state_id' => 16, 'city' => 'Dixon'],
                ['state_id' => 16, 'city' => 'Donahue'],
                ['state_id' => 16, 'city' => 'Eldridge'],
                ['state_id' => 16, 'city' => 'Le Claire'],
                ['state_id' => 16, 'city' => 'Long Grove'],
                ['state_id' => 16, 'city' => 'Mc Causland'],
                ['state_id' => 16, 'city' => 'New Liberty'],
                ['state_id' => 16, 'city' => 'Pleasant Valley'],
                ['state_id' => 16, 'city' => 'Princeton'],
                ['state_id' => 16, 'city' => 'Walcott'],
                ['state_id' => 16, 'city' => 'Davenport'],
                ['state_id' => 16, 'city' => 'Irwin'],
                ['state_id' => 16, 'city' => 'Kirkman'],
                ['state_id' => 16, 'city' => 'Defiance'],
                ['state_id' => 16, 'city' => 'Earling'],
                ['state_id' => 16, 'city' => 'Elk Horn'],
                ['state_id' => 16, 'city' => 'Panama'],
                ['state_id' => 16, 'city' => 'Portsmouth'],
                ['state_id' => 16, 'city' => 'Westphalia'],
                ['state_id' => 16, 'city' => 'Alton'],
                ['state_id' => 16, 'city' => 'Chatsworth'],
                ['state_id' => 16, 'city' => 'Granville'],
                ['state_id' => 16, 'city' => 'Hawarden'],
                ['state_id' => 16, 'city' => 'Ireton'],
                ['state_id' => 16, 'city' => 'Maurice'],
                ['state_id' => 16, 'city' => 'Orange City'],
                ['state_id' => 16, 'city' => 'Boyden'],
                ['state_id' => 16, 'city' => 'Hospers'],
                ['state_id' => 16, 'city' => 'Hull'],
                ['state_id' => 16, 'city' => 'Matlock'],
                ['state_id' => 16, 'city' => 'Rock Valley'],
                ['state_id' => 16, 'city' => 'Sioux Center'],
                ['state_id' => 16, 'city' => 'Ames'],
                ['state_id' => 16, 'city' => 'Cambridge'],
                ['state_id' => 16, 'city' => 'Collins'],
                ['state_id' => 16, 'city' => 'Colo'],
                ['state_id' => 16, 'city' => 'Gilbert'],
                ['state_id' => 16, 'city' => 'Huxley'],
                ['state_id' => 16, 'city' => 'Kelley'],
                ['state_id' => 16, 'city' => 'Mc Callsburg'],
                ['state_id' => 16, 'city' => 'Maxwell'],
                ['state_id' => 16, 'city' => 'Nevada'],
                ['state_id' => 16, 'city' => 'Roland'],
                ['state_id' => 16, 'city' => 'Slater'],
                ['state_id' => 16, 'city' => 'Story City'],
                ['state_id' => 16, 'city' => 'Zearing'],
                ['state_id' => 16, 'city' => 'Montour'],
                ['state_id' => 16, 'city' => 'Buckingham'],
                ['state_id' => 16, 'city' => 'Garwin'],
                ['state_id' => 16, 'city' => 'Gladbrook'],
                ['state_id' => 16, 'city' => 'Lincoln'],
                ['state_id' => 16, 'city' => 'Traer'],
                ['state_id' => 16, 'city' => 'Chelsea'],
                ['state_id' => 16, 'city' => 'Clutier'],
                ['state_id' => 16, 'city' => 'Dysart'],
                ['state_id' => 16, 'city' => 'Elberon'],
                ['state_id' => 16, 'city' => 'Tama'],
                ['state_id' => 16, 'city' => 'Toledo'],
                ['state_id' => 16, 'city' => 'Vining'],
                ['state_id' => 16, 'city' => 'Bedford'],
                ['state_id' => 16, 'city' => 'Blockton'],
                ['state_id' => 16, 'city' => 'Clearfield'],
                ['state_id' => 16, 'city' => 'Gravity'],
                ['state_id' => 16, 'city' => 'Lenox'],
                ['state_id' => 16, 'city' => 'Sharpsburg'],
                ['state_id' => 16, 'city' => 'New Market'],
                ['state_id' => 16, 'city' => 'Lorimor'],
                ['state_id' => 16, 'city' => 'Thayer'],
                ['state_id' => 16, 'city' => 'Creston'],
                ['state_id' => 16, 'city' => 'Afton'],
                ['state_id' => 16, 'city' => 'Arispe'],
                ['state_id' => 16, 'city' => 'Cromwell'],
                ['state_id' => 16, 'city' => 'Shannon City'],
                ['state_id' => 16, 'city' => 'Birmingham'],
                ['state_id' => 16, 'city' => 'Cantril'],
                ['state_id' => 16, 'city' => 'Douds'],
                ['state_id' => 16, 'city' => 'Keosauqua'],
                ['state_id' => 16, 'city' => 'Milton'],
                ['state_id' => 16, 'city' => 'Mount Sterling'],
                ['state_id' => 16, 'city' => 'Selma'],
                ['state_id' => 16, 'city' => 'Bonaparte'],
                ['state_id' => 16, 'city' => 'Farmington'],
                ['state_id' => 16, 'city' => 'Stockport'],
                ['state_id' => 16, 'city' => 'Ottumwa'],
                ['state_id' => 16, 'city' => 'Agency'],
                ['state_id' => 16, 'city' => 'Blakesburg'],
                ['state_id' => 16, 'city' => 'Chillicothe'],
                ['state_id' => 16, 'city' => 'Eddyville'],
                ['state_id' => 16, 'city' => 'Eldon'],
                ['state_id' => 16, 'city' => 'Kirkville'],
                ['state_id' => 16, 'city' => 'Ackworth'],
                ['state_id' => 16, 'city' => 'Carlisle'],
                ['state_id' => 16, 'city' => 'Cumming'],
                ['state_id' => 16, 'city' => 'Hartford'],
                ['state_id' => 16, 'city' => 'Indianola'],
                ['state_id' => 16, 'city' => 'Lacona'],
                ['state_id' => 16, 'city' => 'Liberty Center'],
                ['state_id' => 16, 'city' => 'Martensdale'],
                ['state_id' => 16, 'city' => 'Milo'],
                ['state_id' => 16, 'city' => 'New Virginia'],
                ['state_id' => 16, 'city' => 'Norwalk'],
                ['state_id' => 16, 'city' => 'Prole'],
                ['state_id' => 16, 'city' => 'Saint Marys'],
                ['state_id' => 16, 'city' => 'Ainsworth'],
                ['state_id' => 16, 'city' => 'Kalona'],
                ['state_id' => 16, 'city' => 'Riverside'],
                ['state_id' => 16, 'city' => 'Washington'],
                ['state_id' => 16, 'city' => 'Wellman'],
                ['state_id' => 16, 'city' => 'West Chester'],
                ['state_id' => 16, 'city' => 'Brighton'],
                ['state_id' => 16, 'city' => 'Crawfordsville'],
                ['state_id' => 16, 'city' => 'Allerton'],
                ['state_id' => 16, 'city' => 'Clio'],
                ['state_id' => 16, 'city' => 'Corydon'],
                ['state_id' => 16, 'city' => 'Humeston'],
                ['state_id' => 16, 'city' => 'Lineville'],
                ['state_id' => 16, 'city' => 'Millerton'],
                ['state_id' => 16, 'city' => 'Promise City'],
                ['state_id' => 16, 'city' => 'Seymour'],
                ['state_id' => 16, 'city' => 'Fort Dodge'],
                ['state_id' => 16, 'city' => 'Badger'],
                ['state_id' => 16, 'city' => 'Barnum'],
                ['state_id' => 16, 'city' => 'Burnside'],
                ['state_id' => 16, 'city' => 'Callender'],
                ['state_id' => 16, 'city' => 'Clare'],
                ['state_id' => 16, 'city' => 'Dayton'],
                ['state_id' => 16, 'city' => 'Duncombe'],
                ['state_id' => 16, 'city' => 'Gowrie'],
                ['state_id' => 16, 'city' => 'Harcourt'],
                ['state_id' => 16, 'city' => 'Lehigh'],
                ['state_id' => 16, 'city' => 'Moorland'],
                ['state_id' => 16, 'city' => 'Otho'],
                ['state_id' => 16, 'city' => 'Vincent'],
                ['state_id' => 16, 'city' => 'Buffalo Center'],
                ['state_id' => 16, 'city' => 'Forest City'],
                ['state_id' => 16, 'city' => 'Lake Mills'],
                ['state_id' => 16, 'city' => 'Leland'],
                ['state_id' => 16, 'city' => 'Rake'],
                ['state_id' => 16, 'city' => 'Scarville'],
                ['state_id' => 16, 'city' => 'Thompson'],
                ['state_id' => 16, 'city' => 'Decorah'],
                ['state_id' => 16, 'city' => 'Calmar'],
                ['state_id' => 16, 'city' => 'Castalia'],
                ['state_id' => 16, 'city' => 'Fort Atkinson'],
                ['state_id' => 16, 'city' => 'Highlandville'],
                ['state_id' => 16, 'city' => 'Ossian'],
                ['state_id' => 16, 'city' => 'Ridgeway'],
                ['state_id' => 16, 'city' => 'Spillville'],
                ['state_id' => 16, 'city' => 'Anthon'],
                ['state_id' => 16, 'city' => 'Bronson'],
                ['state_id' => 16, 'city' => 'Climbing Hill'],
                ['state_id' => 16, 'city' => 'Correctionville'],
                ['state_id' => 16, 'city' => 'Cushing'],
                ['state_id' => 16, 'city' => 'Danbury'],
                ['state_id' => 16, 'city' => 'Hornick'],
                ['state_id' => 16, 'city' => 'Lawton'],
                ['state_id' => 16, 'city' => 'Moville'],
                ['state_id' => 16, 'city' => 'Oto'],
                ['state_id' => 16, 'city' => 'Pierson'],
                ['state_id' => 16, 'city' => 'Salix'],
                ['state_id' => 16, 'city' => 'Sergeant Bluff'],
                ['state_id' => 16, 'city' => 'Sloan'],
                ['state_id' => 16, 'city' => 'Smithland'],
                ['state_id' => 16, 'city' => 'Sioux City'],
                ['state_id' => 16, 'city' => 'Fertile'],
                ['state_id' => 16, 'city' => 'Grafton'],
                ['state_id' => 16, 'city' => 'Hanlontown'],
                ['state_id' => 16, 'city' => 'Joice'],
                ['state_id' => 16, 'city' => 'Kensett'],
                ['state_id' => 16, 'city' => 'Manly'],
                ['state_id' => 16, 'city' => 'Northwood'],
                ['state_id' => 16, 'city' => 'Dows'],
                ['state_id' => 16, 'city' => 'Galt'],
                ['state_id' => 16, 'city' => 'Belmond'],
                ['state_id' => 16, 'city' => 'Rowan'],
                ['state_id' => 16, 'city' => 'Clarion'],
                ['state_id' => 16, 'city' => 'Eagle Grove'],
                ['state_id' => 16, 'city' => 'Goldfield'],
                ['state_id' => 16, 'city' => 'Woolstock']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
