<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State34TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NC - North Carolina.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 34, 'city' => 'Alamance'],
                ['state_id' => 34, 'city' => 'Altamahaw'],
                ['state_id' => 34, 'city' => 'Burlington'],
                ['state_id' => 34, 'city' => 'Elon'],
                ['state_id' => 34, 'city' => 'Graham'],
                ['state_id' => 34, 'city' => 'Haw River'],
                ['state_id' => 34, 'city' => 'Mebane'],
                ['state_id' => 34, 'city' => 'Saxapahaw'],
                ['state_id' => 34, 'city' => 'Snow Camp'],
                ['state_id' => 34, 'city' => 'Swepsonville'],
                ['state_id' => 34, 'city' => 'Hiddenite'],
                ['state_id' => 34, 'city' => 'Stony Point'],
                ['state_id' => 34, 'city' => 'Taylorsville'],
                ['state_id' => 34, 'city' => 'Ennice'],
                ['state_id' => 34, 'city' => 'Glade Valley'],
                ['state_id' => 34, 'city' => 'Piney Creek'],
                ['state_id' => 34, 'city' => 'Roaring Gap'],
                ['state_id' => 34, 'city' => 'Sparta'],
                ['state_id' => 34, 'city' => 'Ansonville'],
                ['state_id' => 34, 'city' => 'Lilesville'],
                ['state_id' => 34, 'city' => 'Mc Farlan'],
                ['state_id' => 34, 'city' => 'Morven'],
                ['state_id' => 34, 'city' => 'Peachland'],
                ['state_id' => 34, 'city' => 'Polkton'],
                ['state_id' => 34, 'city' => 'Wadesboro'],
                ['state_id' => 34, 'city' => 'Creston'],
                ['state_id' => 34, 'city' => 'Crumpler'],
                ['state_id' => 34, 'city' => 'Fleetwood'],
                ['state_id' => 34, 'city' => 'Glendale Springs'],
                ['state_id' => 34, 'city' => 'Grassy Creek'],
                ['state_id' => 34, 'city' => 'Jefferson'],
                ['state_id' => 34, 'city' => 'Lansing'],
                ['state_id' => 34, 'city' => 'Laurel Springs'],
                ['state_id' => 34, 'city' => 'Scottville'],
                ['state_id' => 34, 'city' => 'Todd'],
                ['state_id' => 34, 'city' => 'Warrensville'],
                ['state_id' => 34, 'city' => 'West Jefferson'],
                ['state_id' => 34, 'city' => 'Banner Elk'],
                ['state_id' => 34, 'city' => 'Crossnore'],
                ['state_id' => 34, 'city' => 'Elk Park'],
                ['state_id' => 34, 'city' => 'Linville'],
                ['state_id' => 34, 'city' => 'Minneapolis'],
                ['state_id' => 34, 'city' => 'Montezuma'],
                ['state_id' => 34, 'city' => 'Newland'],
                ['state_id' => 34, 'city' => 'Pineola'],
                ['state_id' => 34, 'city' => 'Plumtree'],
                ['state_id' => 34, 'city' => 'Aurora'],
                ['state_id' => 34, 'city' => 'Bath'],
                ['state_id' => 34, 'city' => 'Belhaven'],
                ['state_id' => 34, 'city' => 'Blounts Creek'],
                ['state_id' => 34, 'city' => 'Chocowinity'],
                ['state_id' => 34, 'city' => 'Edward'],
                ['state_id' => 34, 'city' => 'Pantego'],
                ['state_id' => 34, 'city' => 'Pinetown'],
                ['state_id' => 34, 'city' => 'Washington'],
                ['state_id' => 34, 'city' => 'Aulander'],
                ['state_id' => 34, 'city' => 'Kelford'],
                ['state_id' => 34, 'city' => 'Lewiston Woodville'],
                ['state_id' => 34, 'city' => 'Roxobel'],
                ['state_id' => 34, 'city' => 'Colerain'],
                ['state_id' => 34, 'city' => 'Merry Hill'],
                ['state_id' => 34, 'city' => 'Powellsville'],
                ['state_id' => 34, 'city' => 'Windsor'],
                ['state_id' => 34, 'city' => 'Bladenboro'],
                ['state_id' => 34, 'city' => 'Dublin'],
                ['state_id' => 34, 'city' => 'Elizabethtown'],
                ['state_id' => 34, 'city' => 'Tar Heel'],
                ['state_id' => 34, 'city' => 'White Oak'],
                ['state_id' => 34, 'city' => 'Clarkton'],
                ['state_id' => 34, 'city' => 'Council'],
                ['state_id' => 34, 'city' => 'Kelly'],
                ['state_id' => 34, 'city' => 'Wilmington'],
                ['state_id' => 34, 'city' => 'Ash'],
                ['state_id' => 34, 'city' => 'Bolivia'],
                ['state_id' => 34, 'city' => 'Leland'],
                ['state_id' => 34, 'city' => 'Longwood'],
                ['state_id' => 34, 'city' => 'Shallotte'],
                ['state_id' => 34, 'city' => 'Southport'],
                ['state_id' => 34, 'city' => 'Supply'],
                ['state_id' => 34, 'city' => 'Oak Island'],
                ['state_id' => 34, 'city' => 'Calabash'],
                ['state_id' => 34, 'city' => 'Sunset Beach'],
                ['state_id' => 34, 'city' => 'Ocean Isle Beach'],
                ['state_id' => 34, 'city' => 'Winnabow'],
                ['state_id' => 34, 'city' => 'Alexander'],
                ['state_id' => 34, 'city' => 'Arden'],
                ['state_id' => 34, 'city' => 'Barnardsville'],
                ['state_id' => 34, 'city' => 'Black Mountain'],
                ['state_id' => 34, 'city' => 'Candler'],
                ['state_id' => 34, 'city' => 'Enka'],
                ['state_id' => 34, 'city' => 'Fairview'],
                ['state_id' => 34, 'city' => 'Leicester'],
                ['state_id' => 34, 'city' => 'Montreat'],
                ['state_id' => 34, 'city' => 'Mills River'],
                ['state_id' => 34, 'city' => 'Ridgecrest'],
                ['state_id' => 34, 'city' => 'Skyland'],
                ['state_id' => 34, 'city' => 'Swannanoa'],
                ['state_id' => 34, 'city' => 'Weaverville'],
                ['state_id' => 34, 'city' => 'Asheville'],
                ['state_id' => 34, 'city' => 'Connelly Springs'],
                ['state_id' => 34, 'city' => 'Drexel'],
                ['state_id' => 34, 'city' => 'Glen Alpine'],
                ['state_id' => 34, 'city' => 'Hildebran'],
                ['state_id' => 34, 'city' => 'Jonas Ridge'],
                ['state_id' => 34, 'city' => 'Linville Falls'],
                ['state_id' => 34, 'city' => 'Morganton'],
                ['state_id' => 34, 'city' => 'Icard'],
                ['state_id' => 34, 'city' => 'Rutherford College'],
                ['state_id' => 34, 'city' => 'Valdese'],
                ['state_id' => 34, 'city' => 'Concord'],
                ['state_id' => 34, 'city' => 'Harrisburg'],
                ['state_id' => 34, 'city' => 'Kannapolis'],
                ['state_id' => 34, 'city' => 'Midland'],
                ['state_id' => 34, 'city' => 'Mount Pleasant'],
                ['state_id' => 34, 'city' => 'Collettsville'],
                ['state_id' => 34, 'city' => 'Granite Falls'],
                ['state_id' => 34, 'city' => 'Lenoir'],
                ['state_id' => 34, 'city' => 'Hudson'],
                ['state_id' => 34, 'city' => 'Patterson'],
                ['state_id' => 34, 'city' => 'Rhodhiss'],
                ['state_id' => 34, 'city' => 'Camden'],
                ['state_id' => 34, 'city' => 'Shiloh'],
                ['state_id' => 34, 'city' => 'South Mills'],
                ['state_id' => 34, 'city' => 'Atlantic'],
                ['state_id' => 34, 'city' => 'Atlantic Beach'],
                ['state_id' => 34, 'city' => 'Beaufort'],
                ['state_id' => 34, 'city' => 'Cedar Island'],
                ['state_id' => 34, 'city' => 'Davis'],
                ['state_id' => 34, 'city' => 'Gloucester'],
                ['state_id' => 34, 'city' => 'Harkers Island'],
                ['state_id' => 34, 'city' => 'Marshallberg'],
                ['state_id' => 34, 'city' => 'Morehead City'],
                ['state_id' => 34, 'city' => 'Newport'],
                ['state_id' => 34, 'city' => 'Salter Path'],
                ['state_id' => 34, 'city' => 'Sealevel'],
                ['state_id' => 34, 'city' => 'Smyrna'],
                ['state_id' => 34, 'city' => 'Stacy'],
                ['state_id' => 34, 'city' => 'Stella'],
                ['state_id' => 34, 'city' => 'Williston'],
                ['state_id' => 34, 'city' => 'Emerald Isle'],
                ['state_id' => 34, 'city' => 'Blanch'],
                ['state_id' => 34, 'city' => 'Leasburg'],
                ['state_id' => 34, 'city' => 'Milton'],
                ['state_id' => 34, 'city' => 'Pelham'],
                ['state_id' => 34, 'city' => 'Prospect Hill'],
                ['state_id' => 34, 'city' => 'Providence'],
                ['state_id' => 34, 'city' => 'Yanceyville'],
                ['state_id' => 34, 'city' => 'Hickory'],
                ['state_id' => 34, 'city' => 'Catawba'],
                ['state_id' => 34, 'city' => 'Claremont'],
                ['state_id' => 34, 'city' => 'Conover'],
                ['state_id' => 34, 'city' => 'Maiden'],
                ['state_id' => 34, 'city' => 'Newton'],
                ['state_id' => 34, 'city' => 'Sherrills Ford'],
                ['state_id' => 34, 'city' => 'Terrell'],
                ['state_id' => 34, 'city' => 'Bear Creek'],
                ['state_id' => 34, 'city' => 'Bennett'],
                ['state_id' => 34, 'city' => 'Bonlee'],
                ['state_id' => 34, 'city' => 'Bynum'],
                ['state_id' => 34, 'city' => 'Goldston'],
                ['state_id' => 34, 'city' => 'Gulf'],
                ['state_id' => 34, 'city' => 'Pittsboro'],
                ['state_id' => 34, 'city' => 'Siler City'],
                ['state_id' => 34, 'city' => 'Moncure'],
                ['state_id' => 34, 'city' => 'Topton'],
                ['state_id' => 34, 'city' => 'Andrews'],
                ['state_id' => 34, 'city' => 'Culberson'],
                ['state_id' => 34, 'city' => 'Marble'],
                ['state_id' => 34, 'city' => 'Murphy'],
                ['state_id' => 34, 'city' => 'Edenton'],
                ['state_id' => 34, 'city' => 'Tyner'],
                ['state_id' => 34, 'city' => 'Brasstown'],
                ['state_id' => 34, 'city' => 'Hayesville'],
                ['state_id' => 34, 'city' => 'Warne'],
                ['state_id' => 34, 'city' => 'Boiling Springs'],
                ['state_id' => 34, 'city' => 'Casar'],
                ['state_id' => 34, 'city' => 'Earl'],
                ['state_id' => 34, 'city' => 'Fallston'],
                ['state_id' => 34, 'city' => 'Grover'],
                ['state_id' => 34, 'city' => 'Kings Mountain'],
                ['state_id' => 34, 'city' => 'Lattimore'],
                ['state_id' => 34, 'city' => 'Lawndale'],
                ['state_id' => 34, 'city' => 'Mooresboro'],
                ['state_id' => 34, 'city' => 'Polkville'],
                ['state_id' => 34, 'city' => 'Shelby'],
                ['state_id' => 34, 'city' => 'Waco'],
                ['state_id' => 34, 'city' => 'Bolton'],
                ['state_id' => 34, 'city' => 'Brunswick'],
                ['state_id' => 34, 'city' => 'Cerro Gordo'],
                ['state_id' => 34, 'city' => 'Chadbourn'],
                ['state_id' => 34, 'city' => 'Clarendon'],
                ['state_id' => 34, 'city' => 'Delco'],
                ['state_id' => 34, 'city' => 'Evergreen'],
                ['state_id' => 34, 'city' => 'Fair Bluff'],
                ['state_id' => 34, 'city' => 'Hallsboro'],
                ['state_id' => 34, 'city' => 'Lake Waccamaw'],
                ['state_id' => 34, 'city' => 'Nakina'],
                ['state_id' => 34, 'city' => 'Riegelwood'],
                ['state_id' => 34, 'city' => 'Tabor City'],
                ['state_id' => 34, 'city' => 'Whiteville'],
                ['state_id' => 34, 'city' => 'Bridgeton'],
                ['state_id' => 34, 'city' => 'Cove City'],
                ['state_id' => 34, 'city' => 'Dover'],
                ['state_id' => 34, 'city' => 'Ernul'],
                ['state_id' => 34, 'city' => 'Havelock'],
                ['state_id' => 34, 'city' => 'Cherry Point'],
                ['state_id' => 34, 'city' => 'New Bern'],
                ['state_id' => 34, 'city' => 'Vanceboro'],
                ['state_id' => 34, 'city' => 'Fayetteville'],
                ['state_id' => 34, 'city' => 'Fort Bragg'],
                ['state_id' => 34, 'city' => 'Pope Army Airfield'],
                ['state_id' => 34, 'city' => 'Cumberland'],
                ['state_id' => 34, 'city' => 'Falcon'],
                ['state_id' => 34, 'city' => 'Godwin'],
                ['state_id' => 34, 'city' => 'Hope Mills'],
                ['state_id' => 34, 'city' => 'Linden'],
                ['state_id' => 34, 'city' => 'Spring Lake'],
                ['state_id' => 34, 'city' => 'Stedman'],
                ['state_id' => 34, 'city' => 'Wade'],
                ['state_id' => 34, 'city' => 'Aydlett'],
                ['state_id' => 34, 'city' => 'Barco'],
                ['state_id' => 34, 'city' => 'Coinjock'],
                ['state_id' => 34, 'city' => 'Corolla'],
                ['state_id' => 34, 'city' => 'Currituck'],
                ['state_id' => 34, 'city' => 'Grandy'],
                ['state_id' => 34, 'city' => 'Harbinger'],
                ['state_id' => 34, 'city' => 'Jarvisburg'],
                ['state_id' => 34, 'city' => 'Knotts Island'],
                ['state_id' => 34, 'city' => 'Maple'],
                ['state_id' => 34, 'city' => 'Moyock'],
                ['state_id' => 34, 'city' => 'Point Harbor'],
                ['state_id' => 34, 'city' => 'Poplar Branch'],
                ['state_id' => 34, 'city' => 'Powells Point'],
                ['state_id' => 34, 'city' => 'Shawboro'],
                ['state_id' => 34, 'city' => 'Avon'],
                ['state_id' => 34, 'city' => 'Buxton'],
                ['state_id' => 34, 'city' => 'Frisco'],
                ['state_id' => 34, 'city' => 'Hatteras'],
                ['state_id' => 34, 'city' => 'Kill Devil Hills'],
                ['state_id' => 34, 'city' => 'Kitty Hawk'],
                ['state_id' => 34, 'city' => 'Manns Harbor'],
                ['state_id' => 34, 'city' => 'Manteo'],
                ['state_id' => 34, 'city' => 'Nags Head'],
                ['state_id' => 34, 'city' => 'Rodanthe'],
                ['state_id' => 34, 'city' => 'Salvo'],
                ['state_id' => 34, 'city' => 'Stumpy Point'],
                ['state_id' => 34, 'city' => 'Wanchese'],
                ['state_id' => 34, 'city' => 'Waves'],
                ['state_id' => 34, 'city' => 'Denton'],
                ['state_id' => 34, 'city' => 'Lexington'],
                ['state_id' => 34, 'city' => 'Linwood'],
                ['state_id' => 34, 'city' => 'Southmont'],
                ['state_id' => 34, 'city' => 'Thomasville'],
                ['state_id' => 34, 'city' => 'Wallburg'],
                ['state_id' => 34, 'city' => 'Welcome'],
                ['state_id' => 34, 'city' => 'Advance'],
                ['state_id' => 34, 'city' => 'Cooleemee'],
                ['state_id' => 34, 'city' => 'Mocksville'],
                ['state_id' => 34, 'city' => 'Calypso'],
                ['state_id' => 34, 'city' => 'Faison'],
                ['state_id' => 34, 'city' => 'Kenansville'],
                ['state_id' => 34, 'city' => 'Warsaw'],
                ['state_id' => 34, 'city' => 'Magnolia'],
                ['state_id' => 34, 'city' => 'Rose Hill'],
                ['state_id' => 34, 'city' => 'Teachey'],
                ['state_id' => 34, 'city' => 'Wallace'],
                ['state_id' => 34, 'city' => 'Albertson'],
                ['state_id' => 34, 'city' => 'Beulaville'],
                ['state_id' => 34, 'city' => 'Chinquapin'],
                ['state_id' => 34, 'city' => 'Bahama'],
                ['state_id' => 34, 'city' => 'Rougemont'],
                ['state_id' => 34, 'city' => 'Durham'],
                ['state_id' => 34, 'city' => 'Rocky Mount'],
                ['state_id' => 34, 'city' => 'Battleboro'],
                ['state_id' => 34, 'city' => 'Conetoe'],
                ['state_id' => 34, 'city' => 'Macclesfield'],
                ['state_id' => 34, 'city' => 'Pinetops'],
                ['state_id' => 34, 'city' => 'Speed'],
                ['state_id' => 34, 'city' => 'Tarboro'],
                ['state_id' => 34, 'city' => 'Belews Creek'],
                ['state_id' => 34, 'city' => 'Bethania'],
                ['state_id' => 34, 'city' => 'Clemmons'],
                ['state_id' => 34, 'city' => 'Lewisville'],
                ['state_id' => 34, 'city' => 'Pfafftown'],
                ['state_id' => 34, 'city' => 'Rural Hall'],
                ['state_id' => 34, 'city' => 'Tobaccoville'],
                ['state_id' => 34, 'city' => 'Walkertown'],
                ['state_id' => 34, 'city' => 'Winston-Salem'],
                ['state_id' => 34, 'city' => 'Kernersville'],
                ['state_id' => 34, 'city' => 'Bunn'],
                ['state_id' => 34, 'city' => 'Franklinton'],
                ['state_id' => 34, 'city' => 'Louisburg'],
                ['state_id' => 34, 'city' => 'Youngsville'],
                ['state_id' => 34, 'city' => 'Alexis'],
                ['state_id' => 34, 'city' => 'Belmont'],
                ['state_id' => 34, 'city' => 'Bessemer City'],
                ['state_id' => 34, 'city' => 'Cherryville'],
                ['state_id' => 34, 'city' => 'Cramerton'],
                ['state_id' => 34, 'city' => 'Dallas'],
                ['state_id' => 34, 'city' => 'Davidson'],
                ['state_id' => 34, 'city' => 'Gastonia'],
                ['state_id' => 34, 'city' => 'High Shoals'],
                ['state_id' => 34, 'city' => 'Lowell'],
                ['state_id' => 34, 'city' => 'Mc Adenville'],
                ['state_id' => 34, 'city' => 'Mount Holly'],
                ['state_id' => 34, 'city' => 'Stanley'],
                ['state_id' => 34, 'city' => 'Corapeake'],
                ['state_id' => 34, 'city' => 'Eure'],
                ['state_id' => 34, 'city' => 'Gates'],
                ['state_id' => 34, 'city' => 'Gatesville'],
                ['state_id' => 34, 'city' => 'Hobbsville'],
                ['state_id' => 34, 'city' => 'Roduco'],
                ['state_id' => 34, 'city' => 'Sunbury'],
                ['state_id' => 34, 'city' => 'Fontana Dam'],
                ['state_id' => 34, 'city' => 'Robbinsville'],
                ['state_id' => 34, 'city' => 'Bullock'],
                ['state_id' => 34, 'city' => 'Butner'],
                ['state_id' => 34, 'city' => 'Creedmoor'],
                ['state_id' => 34, 'city' => 'Clayton'],
                ['state_id' => 34, 'city' => 'Oxford'],
                ['state_id' => 34, 'city' => 'Roxboro'],
                ['state_id' => 34, 'city' => 'Stem'],
                ['state_id' => 34, 'city' => 'Stovall'],
                ['state_id' => 34, 'city' => 'Walstonburg'],
                ['state_id' => 34, 'city' => 'Hookerton'],
                ['state_id' => 34, 'city' => 'Maury'],
                ['state_id' => 34, 'city' => 'Snow Hill'],
                ['state_id' => 34, 'city' => 'Browns Summit'],
                ['state_id' => 34, 'city' => 'Climax'],
                ['state_id' => 34, 'city' => 'Colfax'],
                ['state_id' => 34, 'city' => 'Gibsonville'],
                ['state_id' => 34, 'city' => 'High Point'],
                ['state_id' => 34, 'city' => 'Jamestown'],
                ['state_id' => 34, 'city' => 'Julian'],
                ['state_id' => 34, 'city' => 'Mc Leansville'],
                ['state_id' => 34, 'city' => 'Oak Ridge'],
                ['state_id' => 34, 'city' => 'Pleasant Garden'],
                ['state_id' => 34, 'city' => 'Sedalia'],
                ['state_id' => 34, 'city' => 'Stokesdale'],
                ['state_id' => 34, 'city' => 'Summerfield'],
                ['state_id' => 34, 'city' => 'Whitsett'],
                ['state_id' => 34, 'city' => 'Greensboro'],
                ['state_id' => 34, 'city' => 'Enfield'],
                ['state_id' => 34, 'city' => 'Halifax'],
                ['state_id' => 34, 'city' => 'Hobgood'],
                ['state_id' => 34, 'city' => 'Hollister'],
                ['state_id' => 34, 'city' => 'Littleton'],
                ['state_id' => 34, 'city' => 'Roanoke Rapids'],
                ['state_id' => 34, 'city' => 'Scotland Neck'],
                ['state_id' => 34, 'city' => 'Tillery'],
                ['state_id' => 34, 'city' => 'Weldon'],
                ['state_id' => 34, 'city' => 'Angier'],
                ['state_id' => 34, 'city' => 'Buies Creek'],
                ['state_id' => 34, 'city' => 'Coats'],
                ['state_id' => 34, 'city' => 'Kipling'],
                ['state_id' => 34, 'city' => 'Lillington'],
                ['state_id' => 34, 'city' => 'Mamers'],
                ['state_id' => 34, 'city' => 'Bunnlevel'],
                ['state_id' => 34, 'city' => 'Dunn'],
                ['state_id' => 34, 'city' => 'Erwin'],
                ['state_id' => 34, 'city' => 'Olivia'],
                ['state_id' => 34, 'city' => 'Canton'],
                ['state_id' => 34, 'city' => 'Clyde'],
                ['state_id' => 34, 'city' => 'Hazelwood'],
                ['state_id' => 34, 'city' => 'Lake Junaluska'],
                ['state_id' => 34, 'city' => 'Maggie Valley'],
                ['state_id' => 34, 'city' => 'Waynesville'],
                ['state_id' => 34, 'city' => 'Bat Cave'],
                ['state_id' => 34, 'city' => 'Dana'],
                ['state_id' => 34, 'city' => 'East Flat Rock'],
                ['state_id' => 34, 'city' => 'Edneyville'],
                ['state_id' => 34, 'city' => 'Etowah'],
                ['state_id' => 34, 'city' => 'Flat Rock'],
                ['state_id' => 34, 'city' => 'Fletcher'],
                ['state_id' => 34, 'city' => 'Gerton'],
                ['state_id' => 34, 'city' => 'Hendersonville'],
                ['state_id' => 34, 'city' => 'Horse Shoe'],
                ['state_id' => 34, 'city' => 'Mountain Home'],
                ['state_id' => 34, 'city' => 'Naples'],
                ['state_id' => 34, 'city' => 'Tuxedo'],
                ['state_id' => 34, 'city' => 'Zirconia'],
                ['state_id' => 34, 'city' => 'Como'],
                ['state_id' => 34, 'city' => 'Murfreesboro'],
                ['state_id' => 34, 'city' => 'Ahoskie'],
                ['state_id' => 34, 'city' => 'Cofield'],
                ['state_id' => 34, 'city' => 'Harrellsville'],
                ['state_id' => 34, 'city' => 'Winton'],
                ['state_id' => 34, 'city' => 'Raeford'],
                ['state_id' => 34, 'city' => 'Engelhard'],
                ['state_id' => 34, 'city' => 'Fairfield'],
                ['state_id' => 34, 'city' => 'Scranton'],
                ['state_id' => 34, 'city' => 'Swanquarter'],
                ['state_id' => 34, 'city' => 'Ocracoke'],
                ['state_id' => 34, 'city' => 'Barium Springs'],
                ['state_id' => 34, 'city' => 'Mooresville'],
                ['state_id' => 34, 'city' => 'Mount Mourne'],
                ['state_id' => 34, 'city' => 'Troutman'],
                ['state_id' => 34, 'city' => 'Statesville'],
                ['state_id' => 34, 'city' => 'Harmony'],
                ['state_id' => 34, 'city' => 'Olin'],
                ['state_id' => 34, 'city' => 'Turnersburg'],
                ['state_id' => 34, 'city' => 'Union Grove'],
                ['state_id' => 34, 'city' => 'Scotts'],
                ['state_id' => 34, 'city' => 'Balsam'],
                ['state_id' => 34, 'city' => 'Cashiers'],
                ['state_id' => 34, 'city' => 'Cullowhee'],
                ['state_id' => 34, 'city' => 'Dillsboro'],
                ['state_id' => 34, 'city' => 'Glenville'],
                ['state_id' => 34, 'city' => 'Sylva'],
                ['state_id' => 34, 'city' => 'Tuckasegee'],
                ['state_id' => 34, 'city' => 'Webster'],
                ['state_id' => 34, 'city' => 'Whittier'],
                ['state_id' => 34, 'city' => 'Benson'],
                ['state_id' => 34, 'city' => 'Four Oaks'],
                ['state_id' => 34, 'city' => 'Kenly'],
                ['state_id' => 34, 'city' => 'Micro'],
                ['state_id' => 34, 'city' => 'Middlesex'],
                ['state_id' => 34, 'city' => 'Pine Level'],
                ['state_id' => 34, 'city' => 'Princeton'],
                ['state_id' => 34, 'city' => 'Selma'],
                ['state_id' => 34, 'city' => 'Smithfield'],
                ['state_id' => 34, 'city' => 'Wilsons Mills'],
                ['state_id' => 34, 'city' => 'Comfort'],
                ['state_id' => 34, 'city' => 'Maysville'],
                ['state_id' => 34, 'city' => 'Pollocksville'],
                ['state_id' => 34, 'city' => 'Trenton'],
                ['state_id' => 34, 'city' => 'Cumnock'],
                ['state_id' => 34, 'city' => 'Sanford'],
                ['state_id' => 34, 'city' => 'Broadway'],
                ['state_id' => 34, 'city' => 'Lemon Springs'],
                ['state_id' => 34, 'city' => 'Kinston'],
                ['state_id' => 34, 'city' => 'Deep Run'],
                ['state_id' => 34, 'city' => 'La Grange'],
                ['state_id' => 34, 'city' => 'Pink Hill'],
                ['state_id' => 34, 'city' => 'Crouse'],
                ['state_id' => 34, 'city' => 'Denver'],
                ['state_id' => 34, 'city' => 'Iron Station'],
                ['state_id' => 34, 'city' => 'Lincolnton'],
                ['state_id' => 34, 'city' => 'Vale'],
                ['state_id' => 34, 'city' => 'Glenwood'],
                ['state_id' => 34, 'city' => 'Little Switzerland'],
                ['state_id' => 34, 'city' => 'Marion'],
                ['state_id' => 34, 'city' => 'Nebo'],
                ['state_id' => 34, 'city' => 'Old Fort'],
                ['state_id' => 34, 'city' => 'Franklin'],
                ['state_id' => 34, 'city' => 'Highlands'],
                ['state_id' => 34, 'city' => 'Otto'],
                ['state_id' => 34, 'city' => 'Scaly Mountain'],
                ['state_id' => 34, 'city' => 'Hot Springs'],
                ['state_id' => 34, 'city' => 'Marshall'],
                ['state_id' => 34, 'city' => 'Mars Hill'],
                ['state_id' => 34, 'city' => 'Everetts'],
                ['state_id' => 34, 'city' => 'Hamilton'],
                ['state_id' => 34, 'city' => 'Hassell'],
                ['state_id' => 34, 'city' => 'Jamesville'],
                ['state_id' => 34, 'city' => 'Oak City'],
                ['state_id' => 34, 'city' => 'Parmele'],
                ['state_id' => 34, 'city' => 'Robersonville'],
                ['state_id' => 34, 'city' => 'Williamston'],
                ['state_id' => 34, 'city' => 'Cornelius'],
                ['state_id' => 34, 'city' => 'Huntersville'],
                ['state_id' => 34, 'city' => 'Matthews'],
                ['state_id' => 34, 'city' => 'Newell'],
                ['state_id' => 34, 'city' => 'Paw Creek'],
                ['state_id' => 34, 'city' => 'Pineville'],
                ['state_id' => 34, 'city' => 'Charlotte'],
                ['state_id' => 34, 'city' => 'Bakersville'],
                ['state_id' => 34, 'city' => 'Penland'],
                ['state_id' => 34, 'city' => 'Spruce Pine'],
                ['state_id' => 34, 'city' => 'Biscoe'],
                ['state_id' => 34, 'city' => 'Candor'],
                ['state_id' => 34, 'city' => 'Ether'],
                ['state_id' => 34, 'city' => 'Mount Gilead'],
                ['state_id' => 34, 'city' => 'Star'],
                ['state_id' => 34, 'city' => 'Troy'],
                ['state_id' => 34, 'city' => 'Eagle Springs'],
                ['state_id' => 34, 'city' => 'Highfalls'],
                ['state_id' => 34, 'city' => 'Jackson Springs'],
                ['state_id' => 34, 'city' => 'Robbins'],
                ['state_id' => 34, 'city' => 'West End'],
                ['state_id' => 34, 'city' => 'Aberdeen'],
                ['state_id' => 34, 'city' => 'Cameron'],
                ['state_id' => 34, 'city' => 'Carthage'],
                ['state_id' => 34, 'city' => 'Lakeview'],
                ['state_id' => 34, 'city' => 'Pinehurst'],
                ['state_id' => 34, 'city' => 'Pinebluff'],
                ['state_id' => 34, 'city' => 'Southern Pines'],
                ['state_id' => 34, 'city' => 'Vass'],
                ['state_id' => 34, 'city' => 'Bailey'],
                ['state_id' => 34, 'city' => 'Castalia'],
                ['state_id' => 34, 'city' => 'Nashville'],
                ['state_id' => 34, 'city' => 'Red Oak'],
                ['state_id' => 34, 'city' => 'Sharpsburg'],
                ['state_id' => 34, 'city' => 'Spring Hope'],
                ['state_id' => 34, 'city' => 'Whitakers'],
                ['state_id' => 34, 'city' => 'Carolina Beach'],
                ['state_id' => 34, 'city' => 'Castle Hayne'],
                ['state_id' => 34, 'city' => 'Kure Beach'],
                ['state_id' => 34, 'city' => 'Wrightsville Beach'],
                ['state_id' => 34, 'city' => 'Conway'],
                ['state_id' => 34, 'city' => 'Garysburg'],
                ['state_id' => 34, 'city' => 'Gaston'],
                ['state_id' => 34, 'city' => 'Henrico'],
                ['state_id' => 34, 'city' => 'Jackson'],
                ['state_id' => 34, 'city' => 'Margarettsville'],
                ['state_id' => 34, 'city' => 'Pendleton'],
                ['state_id' => 34, 'city' => 'Pleasant Hill'],
                ['state_id' => 34, 'city' => 'Potecasi'],
                ['state_id' => 34, 'city' => 'Rich Square'],
                ['state_id' => 34, 'city' => 'Seaboard'],
                ['state_id' => 34, 'city' => 'Severn'],
                ['state_id' => 34, 'city' => 'Woodland'],
                ['state_id' => 34, 'city' => 'Holly Ridge'],
                ['state_id' => 34, 'city' => 'Sneads Ferry'],
                ['state_id' => 34, 'city' => 'Hubert'],
                ['state_id' => 34, 'city' => 'Jacksonville'],
                ['state_id' => 34, 'city' => 'Camp Lejeune'],
                ['state_id' => 34, 'city' => 'Tarawa Terrace'],
                ['state_id' => 34, 'city' => 'Midway Park'],
                ['state_id' => 34, 'city' => 'Mccutcheon Field'],
                ['state_id' => 34, 'city' => 'Richlands'],
                ['state_id' => 34, 'city' => 'Swansboro'],
                ['state_id' => 34, 'city' => 'Cedar Grove'],
                ['state_id' => 34, 'city' => 'Efland'],
                ['state_id' => 34, 'city' => 'Hillsborough'],
                ['state_id' => 34, 'city' => 'Carrboro'],
                ['state_id' => 34, 'city' => 'Chapel Hill'],
                ['state_id' => 34, 'city' => 'Alliance'],
                ['state_id' => 34, 'city' => 'Arapahoe'],
                ['state_id' => 34, 'city' => 'Bayboro'],
                ['state_id' => 34, 'city' => 'Grantsboro'],
                ['state_id' => 34, 'city' => 'Hobucken'],
                ['state_id' => 34, 'city' => 'Lowland'],
                ['state_id' => 34, 'city' => 'Merritt'],
                ['state_id' => 34, 'city' => 'Oriental'],
                ['state_id' => 34, 'city' => 'Stonewall'],
                ['state_id' => 34, 'city' => 'Vandemere'],
                ['state_id' => 34, 'city' => 'Elizabeth City'],
                ['state_id' => 34, 'city' => 'Atkinson'],
                ['state_id' => 34, 'city' => 'Burgaw'],
                ['state_id' => 34, 'city' => 'Currie'],
                ['state_id' => 34, 'city' => 'Hampstead'],
                ['state_id' => 34, 'city' => 'Maple Hill'],
                ['state_id' => 34, 'city' => 'Rocky Point'],
                ['state_id' => 34, 'city' => 'Willard'],
                ['state_id' => 34, 'city' => 'Belvidere'],
                ['state_id' => 34, 'city' => 'Hertford'],
                ['state_id' => 34, 'city' => 'Winfall'],
                ['state_id' => 34, 'city' => 'Semora'],
                ['state_id' => 34, 'city' => 'Hurdle Mills'],
                ['state_id' => 34, 'city' => 'Timberlake'],
                ['state_id' => 34, 'city' => 'Bellarthur'],
                ['state_id' => 34, 'city' => 'Bethel'],
                ['state_id' => 34, 'city' => 'Falkland'],
                ['state_id' => 34, 'city' => 'Farmville'],
                ['state_id' => 34, 'city' => 'Fountain'],
                ['state_id' => 34, 'city' => 'Greenville'],
                ['state_id' => 34, 'city' => 'Grimesland'],
                ['state_id' => 34, 'city' => 'Simpson'],
                ['state_id' => 34, 'city' => 'Stokes'],
                ['state_id' => 34, 'city' => 'Ayden'],
                ['state_id' => 34, 'city' => 'Grifton'],
                ['state_id' => 34, 'city' => 'Winterville'],
                ['state_id' => 34, 'city' => 'Columbus'],
                ['state_id' => 34, 'city' => 'Lynn'],
                ['state_id' => 34, 'city' => 'Mill Spring'],
                ['state_id' => 34, 'city' => 'Saluda'],
                ['state_id' => 34, 'city' => 'Tryon'],
                ['state_id' => 34, 'city' => 'Asheboro'],
                ['state_id' => 34, 'city' => 'Cedar Falls'],
                ['state_id' => 34, 'city' => 'Franklinville'],
                ['state_id' => 34, 'city' => 'Liberty'],
                ['state_id' => 34, 'city' => 'Ramseur'],
                ['state_id' => 34, 'city' => 'Randleman'],
                ['state_id' => 34, 'city' => 'Seagrove'],
                ['state_id' => 34, 'city' => 'Sophia'],
                ['state_id' => 34, 'city' => 'Staley'],
                ['state_id' => 34, 'city' => 'Trinity'],
                ['state_id' => 34, 'city' => 'Cordova'],
                ['state_id' => 34, 'city' => 'Ellerbe'],
                ['state_id' => 34, 'city' => 'Hamlet'],
                ['state_id' => 34, 'city' => 'Hoffman'],
                ['state_id' => 34, 'city' => 'Marston'],
                ['state_id' => 34, 'city' => 'Norman'],
                ['state_id' => 34, 'city' => 'Rockingham'],
                ['state_id' => 34, 'city' => 'Barnesville'],
                ['state_id' => 34, 'city' => 'Fairmont'],
                ['state_id' => 34, 'city' => 'Lumber Bridge'],
                ['state_id' => 34, 'city' => 'Lumberton'],
                ['state_id' => 34, 'city' => 'Marietta'],
                ['state_id' => 34, 'city' => 'Maxton'],
                ['state_id' => 34, 'city' => 'Orrum'],
                ['state_id' => 34, 'city' => 'Parkton'],
                ['state_id' => 34, 'city' => 'Pembroke'],
                ['state_id' => 34, 'city' => 'Proctorville'],
                ['state_id' => 34, 'city' => 'Red Springs'],
                ['state_id' => 34, 'city' => 'Rex'],
                ['state_id' => 34, 'city' => 'Rowland'],
                ['state_id' => 34, 'city' => 'Saint Pauls'],
                ['state_id' => 34, 'city' => 'Shannon'],
                ['state_id' => 34, 'city' => 'Madison'],
                ['state_id' => 34, 'city' => 'Mayodan'],
                ['state_id' => 34, 'city' => 'Stoneville'],
                ['state_id' => 34, 'city' => 'Eden'],
                ['state_id' => 34, 'city' => 'Reidsville'],
                ['state_id' => 34, 'city' => 'Ruffin'],
                ['state_id' => 34, 'city' => 'Wentworth'],
                ['state_id' => 34, 'city' => 'Cleveland'],
                ['state_id' => 34, 'city' => 'Woodleaf'],
                ['state_id' => 34, 'city' => 'China Grove'],
                ['state_id' => 34, 'city' => 'East Spencer'],
                ['state_id' => 34, 'city' => 'Faith'],
                ['state_id' => 34, 'city' => 'Gold Hill'],
                ['state_id' => 34, 'city' => 'Granite Quarry'],
                ['state_id' => 34, 'city' => 'Landis'],
                ['state_id' => 34, 'city' => 'Mount Ulla'],
                ['state_id' => 34, 'city' => 'Rockwell'],
                ['state_id' => 34, 'city' => 'Salisbury'],
                ['state_id' => 34, 'city' => 'Spencer'],
                ['state_id' => 34, 'city' => 'Bostic'],
                ['state_id' => 34, 'city' => 'Caroleen'],
                ['state_id' => 34, 'city' => 'Cliffside'],
                ['state_id' => 34, 'city' => 'Ellenboro'],
                ['state_id' => 34, 'city' => 'Forest City'],
                ['state_id' => 34, 'city' => 'Harris'],
                ['state_id' => 34, 'city' => 'Henrietta'],
                ['state_id' => 34, 'city' => 'Rutherfordton'],
                ['state_id' => 34, 'city' => 'Spindale'],
                ['state_id' => 34, 'city' => 'Union Mills'],
                ['state_id' => 34, 'city' => 'Chimney Rock'],
                ['state_id' => 34, 'city' => 'Lake Lure'],
                ['state_id' => 34, 'city' => 'Autryville'],
                ['state_id' => 34, 'city' => 'Clinton'],
                ['state_id' => 34, 'city' => 'Newton Grove'],
                ['state_id' => 34, 'city' => 'Roseboro'],
                ['state_id' => 34, 'city' => 'Salemburg'],
                ['state_id' => 34, 'city' => 'Turkey'],
                ['state_id' => 34, 'city' => 'Garland'],
                ['state_id' => 34, 'city' => 'Harrells'],
                ['state_id' => 34, 'city' => 'Ivanhoe'],
                ['state_id' => 34, 'city' => 'Gibson'],
                ['state_id' => 34, 'city' => 'Laurel Hill'],
                ['state_id' => 34, 'city' => 'Laurinburg'],
                ['state_id' => 34, 'city' => 'Wagram'],
                ['state_id' => 34, 'city' => 'Albemarle'],
                ['state_id' => 34, 'city' => 'Badin'],
                ['state_id' => 34, 'city' => 'Locust'],
                ['state_id' => 34, 'city' => 'Misenheimer'],
                ['state_id' => 34, 'city' => 'New London'],
                ['state_id' => 34, 'city' => 'Norwood'],
                ['state_id' => 34, 'city' => 'Oakboro'],
                ['state_id' => 34, 'city' => 'Richfield'],
                ['state_id' => 34, 'city' => 'Stanfield'],
                ['state_id' => 34, 'city' => 'Danbury'],
                ['state_id' => 34, 'city' => 'Germanton'],
                ['state_id' => 34, 'city' => 'King'],
                ['state_id' => 34, 'city' => 'Lawsonville'],
                ['state_id' => 34, 'city' => 'Pine Hall'],
                ['state_id' => 34, 'city' => 'Pinnacle'],
                ['state_id' => 34, 'city' => 'Sandy Ridge'],
                ['state_id' => 34, 'city' => 'Walnut Cove'],
                ['state_id' => 34, 'city' => 'Ararat'],
                ['state_id' => 34, 'city' => 'Dobson'],
                ['state_id' => 34, 'city' => 'Lowgap'],
                ['state_id' => 34, 'city' => 'Mount Airy'],
                ['state_id' => 34, 'city' => 'White Plains'],
                ['state_id' => 34, 'city' => 'Pilot Mountain'],
                ['state_id' => 34, 'city' => 'Siloam'],
                ['state_id' => 34, 'city' => 'Toast'],
                ['state_id' => 34, 'city' => 'Westfield'],
                ['state_id' => 34, 'city' => 'Elkin'],
                ['state_id' => 34, 'city' => 'State Road'],
                ['state_id' => 34, 'city' => 'Almond'],
                ['state_id' => 34, 'city' => 'Bryson City'],
                ['state_id' => 34, 'city' => 'Cherokee'],
                ['state_id' => 34, 'city' => 'Balsam Grove'],
                ['state_id' => 34, 'city' => 'Brevard'],
                ['state_id' => 34, 'city' => 'Cedar Mountain'],
                ['state_id' => 34, 'city' => 'Lake Toxaway'],
                ['state_id' => 34, 'city' => 'Penrose'],
                ['state_id' => 34, 'city' => 'Pisgah Forest'],
                ['state_id' => 34, 'city' => 'Rosman'],
                ['state_id' => 34, 'city' => 'Sapphire'],
                ['state_id' => 34, 'city' => 'Columbia'],
                ['state_id' => 34, 'city' => 'Indian Trail'],
                ['state_id' => 34, 'city' => 'Marshville'],
                ['state_id' => 34, 'city' => 'Mineral Springs'],
                ['state_id' => 34, 'city' => 'Monroe'],
                ['state_id' => 34, 'city' => 'Waxhaw'],
                ['state_id' => 34, 'city' => 'Wingate'],
                ['state_id' => 34, 'city' => 'Henderson'],
                ['state_id' => 34, 'city' => 'Kittrell'],
                ['state_id' => 34, 'city' => 'Manson'],
                ['state_id' => 34, 'city' => 'Middleburg'],
                ['state_id' => 34, 'city' => 'Townsville'],
                ['state_id' => 34, 'city' => 'Apex'],
                ['state_id' => 34, 'city' => 'Cary'],
                ['state_id' => 34, 'city' => 'Fuquay Varina'],
                ['state_id' => 34, 'city' => 'Garner'],
                ['state_id' => 34, 'city' => 'Holly Springs'],
                ['state_id' => 34, 'city' => 'Knightdale'],
                ['state_id' => 34, 'city' => 'Morrisville'],
                ['state_id' => 34, 'city' => 'New Hill'],
                ['state_id' => 34, 'city' => 'Rolesville'],
                ['state_id' => 34, 'city' => 'Wake Forest'],
                ['state_id' => 34, 'city' => 'Wendell'],
                ['state_id' => 34, 'city' => 'Willow Spring'],
                ['state_id' => 34, 'city' => 'Zebulon'],
                ['state_id' => 34, 'city' => 'Raleigh'],
                ['state_id' => 34, 'city' => 'Macon'],
                ['state_id' => 34, 'city' => 'Norlina'],
                ['state_id' => 34, 'city' => 'Ridgeway'],
                ['state_id' => 34, 'city' => 'Vaughan'],
                ['state_id' => 34, 'city' => 'Warrenton'],
                ['state_id' => 34, 'city' => 'Wise'],
                ['state_id' => 34, 'city' => 'Creswell'],
                ['state_id' => 34, 'city' => 'Plymouth'],
                ['state_id' => 34, 'city' => 'Roper'],
                ['state_id' => 34, 'city' => 'Blowing Rock'],
                ['state_id' => 34, 'city' => 'Boone'],
                ['state_id' => 34, 'city' => 'Deep Gap'],
                ['state_id' => 34, 'city' => 'Sugar Grove'],
                ['state_id' => 34, 'city' => 'Valle Crucis'],
                ['state_id' => 34, 'city' => 'Vilas'],
                ['state_id' => 34, 'city' => 'Zionville'],
                ['state_id' => 34, 'city' => 'Goldsboro'],
                ['state_id' => 34, 'city' => 'Fremont'],
                ['state_id' => 34, 'city' => 'Pikeville'],
                ['state_id' => 34, 'city' => 'Dudley'],
                ['state_id' => 34, 'city' => 'Mount Olive'],
                ['state_id' => 34, 'city' => 'Seven Springs'],
                ['state_id' => 34, 'city' => 'Boomer'],
                ['state_id' => 34, 'city' => 'Ferguson'],
                ['state_id' => 34, 'city' => 'Hays'],
                ['state_id' => 34, 'city' => 'Mc Grady'],
                ['state_id' => 34, 'city' => 'Millers Creek'],
                ['state_id' => 34, 'city' => 'Moravian Falls'],
                ['state_id' => 34, 'city' => 'North Wilkesboro'],
                ['state_id' => 34, 'city' => 'Purlear'],
                ['state_id' => 34, 'city' => 'Roaring River'],
                ['state_id' => 34, 'city' => 'Ronda'],
                ['state_id' => 34, 'city' => 'Thurmond'],
                ['state_id' => 34, 'city' => 'Traphill'],
                ['state_id' => 34, 'city' => 'Wilkesboro'],
                ['state_id' => 34, 'city' => 'Black Creek'],
                ['state_id' => 34, 'city' => 'Elm City'],
                ['state_id' => 34, 'city' => 'Lucama'],
                ['state_id' => 34, 'city' => 'Saratoga'],
                ['state_id' => 34, 'city' => 'Sims'],
                ['state_id' => 34, 'city' => 'Stantonsburg'],
                ['state_id' => 34, 'city' => 'Wilson'],
                ['state_id' => 34, 'city' => 'Boonville'],
                ['state_id' => 34, 'city' => 'East Bend'],
                ['state_id' => 34, 'city' => 'Hamptonville'],
                ['state_id' => 34, 'city' => 'Yadkinville'],
                ['state_id' => 34, 'city' => 'Jonesville'],
                ['state_id' => 34, 'city' => 'Burnsville'],
                ['state_id' => 34, 'city' => 'Green Mountain'],
                ['state_id' => 34, 'city' => 'Micaville', 'state_id' => 28]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
