<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State20TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of ME - Maine.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 20, 'city' => 'Auburn'],
                ['state_id' => 20, 'city' => 'Durham'],
                ['state_id' => 20, 'city' => 'Danville'],
                ['state_id' => 20, 'city' => 'East Livermore'],
                ['state_id' => 20, 'city' => 'East Poland'],
                ['state_id' => 20, 'city' => 'Greene'],
                ['state_id' => 20, 'city' => 'Lewiston'],
                ['state_id' => 20, 'city' => 'Lisbon'],
                ['state_id' => 20, 'city' => 'Lisbon Falls'],
                ['state_id' => 20, 'city' => 'Livermore'],
                ['state_id' => 20, 'city' => 'Livermore Falls'],
                ['state_id' => 20, 'city' => 'Mechanic Falls'],
                ['state_id' => 20, 'city' => 'Minot'],
                ['state_id' => 20, 'city' => 'Leeds'],
                ['state_id' => 20, 'city' => 'North Turner'],
                ['state_id' => 20, 'city' => 'Poland'],
                ['state_id' => 20, 'city' => 'Sabattus'],
                ['state_id' => 20, 'city' => 'Turner'],
                ['state_id' => 20, 'city' => 'West Minot'],
                ['state_id' => 20, 'city' => 'West Poland'],
                ['state_id' => 20, 'city' => 'Orient'],
                ['state_id' => 20, 'city' => 'Wytopitlock'],
                ['state_id' => 20, 'city' => 'Houlton'],
                ['state_id' => 20, 'city' => 'Ashland'],
                ['state_id' => 20, 'city' => 'Benedicta'],
                ['state_id' => 20, 'city' => 'Blaine'],
                ['state_id' => 20, 'city' => 'Bridgewater'],
                ['state_id' => 20, 'city' => 'Caribou'],
                ['state_id' => 20, 'city' => 'Clayton Lake'],
                ['state_id' => 20, 'city' => 'Crouseville'],
                ['state_id' => 20, 'city' => 'Eagle Lake'],
                ['state_id' => 20, 'city' => 'Easton'],
                ['state_id' => 20, 'city' => 'Estcourt Station'],
                ['state_id' => 20, 'city' => 'Fort Fairfield'],
                ['state_id' => 20, 'city' => 'Fort Kent'],
                ['state_id' => 20, 'city' => 'Fort Kent Mills'],
                ['state_id' => 20, 'city' => 'Frenchville'],
                ['state_id' => 20, 'city' => 'Grand Isle'],
                ['state_id' => 20, 'city' => 'Island Falls'],
                ['state_id' => 20, 'city' => 'Limestone'],
                ['state_id' => 20, 'city' => 'Madawaska'],
                ['state_id' => 20, 'city' => 'Mapleton'],
                ['state_id' => 20, 'city' => 'Mars Hill'],
                ['state_id' => 20, 'city' => 'Monticello'],
                ['state_id' => 20, 'city' => 'New Limerick'],
                ['state_id' => 20, 'city' => 'New Sweden'],
                ['state_id' => 20, 'city' => 'Oakfield'],
                ['state_id' => 20, 'city' => 'Oxbow'],
                ['state_id' => 20, 'city' => 'Perham'],
                ['state_id' => 20, 'city' => 'Portage'],
                ['state_id' => 20, 'city' => 'Presque Isle'],
                ['state_id' => 20, 'city' => 'Saint Agatha'],
                ['state_id' => 20, 'city' => 'Saint David'],
                ['state_id' => 20, 'city' => 'Saint Francis'],
                ['state_id' => 20, 'city' => 'Sheridan'],
                ['state_id' => 20, 'city' => 'Sherman'],
                ['state_id' => 20, 'city' => 'Sinclair'],
                ['state_id' => 20, 'city' => 'Smyrna Mills'],
                ['state_id' => 20, 'city' => 'Wallagrass'],
                ['state_id' => 20, 'city' => 'Stockholm'],
                ['state_id' => 20, 'city' => 'Van Buren'],
                ['state_id' => 20, 'city' => 'Washburn'],
                ['state_id' => 20, 'city' => 'Westfield'],
                ['state_id' => 20, 'city' => 'Bailey Island'],
                ['state_id' => 20, 'city' => 'Bridgton'],
                ['state_id' => 20, 'city' => 'Brunswick'],
                ['state_id' => 20, 'city' => 'Bustins Island'],
                ['state_id' => 20, 'city' => 'Casco'],
                ['state_id' => 20, 'city' => 'Chebeague Island'],
                ['state_id' => 20, 'city' => 'Cliff Island'],
                ['state_id' => 20, 'city' => 'Cumberland Center'],
                ['state_id' => 20, 'city' => 'East Baldwin'],
                ['state_id' => 20, 'city' => 'Sebago'],
                ['state_id' => 20, 'city' => 'Freeport'],
                ['state_id' => 20, 'city' => 'Gorham'],
                ['state_id' => 20, 'city' => 'Gray'],
                ['state_id' => 20, 'city' => 'Harrison'],
                ['state_id' => 20, 'city' => 'Long Island'],
                ['state_id' => 20, 'city' => 'Naples'],
                ['state_id' => 20, 'city' => 'North Bridgton'],
                ['state_id' => 20, 'city' => 'Windham'],
                ['state_id' => 20, 'city' => 'Orrs Island'],
                ['state_id' => 20, 'city' => 'Pownal'],
                ['state_id' => 20, 'city' => 'Scarborough'],
                ['state_id' => 20, 'city' => 'Raymond'],
                ['state_id' => 20, 'city' => 'South Casco'],
                ['state_id' => 20, 'city' => 'South Freeport'],
                ['state_id' => 20, 'city' => 'Harpswell'],
                ['state_id' => 20, 'city' => 'South Windham'],
                ['state_id' => 20, 'city' => 'Standish'],
                ['state_id' => 20, 'city' => 'Steep Falls'],
                ['state_id' => 20, 'city' => 'West Baldwin'],
                ['state_id' => 20, 'city' => 'Westbrook'],
                ['state_id' => 20, 'city' => 'Yarmouth'],
                ['state_id' => 20, 'city' => 'North Yarmouth'],
                ['state_id' => 20, 'city' => 'Portland'],
                ['state_id' => 20, 'city' => 'Falmouth'],
                ['state_id' => 20, 'city' => 'South Portland'],
                ['state_id' => 20, 'city' => 'Cape Elizabeth'],
                ['state_id' => 20, 'city' => 'Peaks Island'],
                ['state_id' => 20, 'city' => 'Cumberland Foreside'],
                ['state_id' => 20, 'city' => 'New Gloucester'],
                ['state_id' => 20, 'city' => 'Dryden'],
                ['state_id' => 20, 'city' => 'East Dixfield'],
                ['state_id' => 20, 'city' => 'East Wilton'],
                ['state_id' => 20, 'city' => 'Jay'],
                ['state_id' => 20, 'city' => 'North Jay'],
                ['state_id' => 20, 'city' => 'Weld'],
                ['state_id' => 20, 'city' => 'Wilton'],
                ['state_id' => 20, 'city' => 'Eustis'],
                ['state_id' => 20, 'city' => 'Farmington'],
                ['state_id' => 20, 'city' => 'Farmington Falls'],
                ['state_id' => 20, 'city' => 'Kingfield'],
                ['state_id' => 20, 'city' => 'New Sharon'],
                ['state_id' => 20, 'city' => 'New Vineyard'],
                ['state_id' => 20, 'city' => 'Oquossoc'],
                ['state_id' => 20, 'city' => 'Phillips'],
                ['state_id' => 20, 'city' => 'Rangeley'],
                ['state_id' => 20, 'city' => 'Stratton'],
                ['state_id' => 20, 'city' => 'Strong'],
                ['state_id' => 20, 'city' => 'Temple'],
                ['state_id' => 20, 'city' => 'West Farmington'],
                ['state_id' => 20, 'city' => 'Aurora'],
                ['state_id' => 20, 'city' => 'Bucksport'],
                ['state_id' => 20, 'city' => 'Castine'],
                ['state_id' => 20, 'city' => 'East Orland'],
                ['state_id' => 20, 'city' => 'Orland'],
                ['state_id' => 20, 'city' => 'Penobscot'],
                ['state_id' => 20, 'city' => 'Ellsworth'],
                ['state_id' => 20, 'city' => 'Gouldsboro'],
                ['state_id' => 20, 'city' => 'Bar Harbor'],
                ['state_id' => 20, 'city' => 'Bernard'],
                ['state_id' => 20, 'city' => 'Birch Harbor'],
                ['state_id' => 20, 'city' => 'Blue Hill'],
                ['state_id' => 20, 'city' => 'Brooklin'],
                ['state_id' => 20, 'city' => 'Brooksville'],
                ['state_id' => 20, 'city' => 'Corea'],
                ['state_id' => 20, 'city' => 'Cranberry Isles'],
                ['state_id' => 20, 'city' => 'Deer Isle'],
                ['state_id' => 20, 'city' => 'East Blue Hill'],
                ['state_id' => 20, 'city' => 'Franklin'],
                ['state_id' => 20, 'city' => 'Frenchboro'],
                ['state_id' => 20, 'city' => 'Hancock'],
                ['state_id' => 20, 'city' => 'Harborside'],
                ['state_id' => 20, 'city' => 'Hulls Cove'],
                ['state_id' => 20, 'city' => 'Islesford'],
                ['state_id' => 20, 'city' => 'Little Deer Isle'],
                ['state_id' => 20, 'city' => 'Bass Harbor'],
                ['state_id' => 20, 'city' => 'Mount Desert'],
                ['state_id' => 20, 'city' => 'Northeast Harbor'],
                ['state_id' => 20, 'city' => 'Sullivan'],
                ['state_id' => 20, 'city' => 'Prospect Harbor'],
                ['state_id' => 20, 'city' => 'Salsbury Cove'],
                ['state_id' => 20, 'city' => 'Sargentville'],
                ['state_id' => 20, 'city' => 'Seal Cove'],
                ['state_id' => 20, 'city' => 'Seal Harbor'],
                ['state_id' => 20, 'city' => 'Sedgwick'],
                ['state_id' => 20, 'city' => 'Sorrento'],
                ['state_id' => 20, 'city' => 'Southwest Harbor'],
                ['state_id' => 20, 'city' => 'Stonington'],
                ['state_id' => 20, 'city' => 'Sunset'],
                ['state_id' => 20, 'city' => 'Surry'],
                ['state_id' => 20, 'city' => 'Swans Island'],
                ['state_id' => 20, 'city' => 'Winter Harbor'],
                ['state_id' => 20, 'city' => 'Monmouth'],
                ['state_id' => 20, 'city' => 'North Monmouth'],
                ['state_id' => 20, 'city' => 'Wayne'],
                ['state_id' => 20, 'city' => 'Augusta'],
                ['state_id' => 20, 'city' => 'East Winthrop'],
                ['state_id' => 20, 'city' => 'Farmingdale'],
                ['state_id' => 20, 'city' => 'Gardiner'],
                ['state_id' => 20, 'city' => 'Randolph'],
                ['state_id' => 20, 'city' => 'Hallowell'],
                ['state_id' => 20, 'city' => 'Kents Hill'],
                ['state_id' => 20, 'city' => 'Litchfield'],
                ['state_id' => 20, 'city' => 'Manchester'],
                ['state_id' => 20, 'city' => 'Mount Vernon'],
                ['state_id' => 20, 'city' => 'Readfield'],
                ['state_id' => 20, 'city' => 'South China'],
                ['state_id' => 20, 'city' => 'South Gardiner'],
                ['state_id' => 20, 'city' => 'Vienna'],
                ['state_id' => 20, 'city' => 'Windsor'],
                ['state_id' => 20, 'city' => 'Winthrop'],
                ['state_id' => 20, 'city' => 'Waterville'],
                ['state_id' => 20, 'city' => 'Albion'],
                ['state_id' => 20, 'city' => 'Belgrade'],
                ['state_id' => 20, 'city' => 'Belgrade Lakes'],
                ['state_id' => 20, 'city' => 'China Village'],
                ['state_id' => 20, 'city' => 'Clinton'],
                ['state_id' => 20, 'city' => 'East Vassalboro'],
                ['state_id' => 20, 'city' => 'North Vassalboro'],
                ['state_id' => 20, 'city' => 'Oakland'],
                ['state_id' => 20, 'city' => 'Vassalboro'],
                ['state_id' => 20, 'city' => 'Friendship'],
                ['state_id' => 20, 'city' => 'Cushing'],
                ['state_id' => 20, 'city' => 'Washington'],
                ['state_id' => 20, 'city' => 'Isle Au Haut'],
                ['state_id' => 20, 'city' => 'Rockland'],
                ['state_id' => 20, 'city' => 'Camden'],
                ['state_id' => 20, 'city' => 'Hope'],
                ['state_id' => 20, 'city' => 'Matinicus'],
                ['state_id' => 20, 'city' => 'North Haven'],
                ['state_id' => 20, 'city' => 'Owls Head'],
                ['state_id' => 20, 'city' => 'Port Clyde'],
                ['state_id' => 20, 'city' => 'Rockport'],
                ['state_id' => 20, 'city' => 'South Thomaston'],
                ['state_id' => 20, 'city' => 'Spruce Head'],
                ['state_id' => 20, 'city' => 'Tenants Harbor'],
                ['state_id' => 20, 'city' => 'Thomaston'],
                ['state_id' => 20, 'city' => 'Union'],
                ['state_id' => 20, 'city' => 'Vinalhaven'],
                ['state_id' => 20, 'city' => 'Warren'],
                ['state_id' => 20, 'city' => 'West Rockport'],
                ['state_id' => 20, 'city' => 'Coopers Mills'],
                ['state_id' => 20, 'city' => 'Dresden'],
                ['state_id' => 20, 'city' => 'Jefferson'],
                ['state_id' => 20, 'city' => 'Whitefield'],
                ['state_id' => 20, 'city' => 'Alna'],
                ['state_id' => 20, 'city' => 'Boothbay'],
                ['state_id' => 20, 'city' => 'Boothbay Harbor'],
                ['state_id' => 20, 'city' => 'Bristol'],
                ['state_id' => 20, 'city' => 'Chamberlain'],
                ['state_id' => 20, 'city' => 'Damariscotta'],
                ['state_id' => 20, 'city' => 'East Boothbay'],
                ['state_id' => 20, 'city' => 'Isle Of Springs'],
                ['state_id' => 20, 'city' => 'Bremen'],
                ['state_id' => 20, 'city' => 'Newcastle'],
                ['state_id' => 20, 'city' => 'New Harbor'],
                ['state_id' => 20, 'city' => 'Nobleboro'],
                ['state_id' => 20, 'city' => 'Edgecomb'],
                ['state_id' => 20, 'city' => 'Pemaquid'],
                ['state_id' => 20, 'city' => 'Round Pond'],
                ['state_id' => 20, 'city' => 'South Bristol'],
                ['state_id' => 20, 'city' => 'Squirrel Island'],
                ['state_id' => 20, 'city' => 'Trevett'],
                ['state_id' => 20, 'city' => 'Waldoboro'],
                ['state_id' => 20, 'city' => 'Walpole'],
                ['state_id' => 20, 'city' => 'West Boothbay Harbor'],
                ['state_id' => 20, 'city' => 'Southport'],
                ['state_id' => 20, 'city' => 'Wiscasset'],
                ['state_id' => 20, 'city' => 'Monhegan'],
                ['state_id' => 20, 'city' => 'Brownfield'],
                ['state_id' => 20, 'city' => 'Center Lovell'],
                ['state_id' => 20, 'city' => 'Denmark'],
                ['state_id' => 20, 'city' => 'Fryeburg'],
                ['state_id' => 20, 'city' => 'Hiram'],
                ['state_id' => 20, 'city' => 'Lovell'],
                ['state_id' => 20, 'city' => 'Porter'],
                ['state_id' => 20, 'city' => 'Waterford'],
                ['state_id' => 20, 'city' => 'Andover'],
                ['state_id' => 20, 'city' => 'Bethel'],
                ['state_id' => 20, 'city' => 'Bryant Pond'],
                ['state_id' => 20, 'city' => 'Buckfield'],
                ['state_id' => 20, 'city' => 'Canton'],
                ['state_id' => 20, 'city' => 'Dixfield'],
                ['state_id' => 20, 'city' => 'East Andover'],
                ['state_id' => 20, 'city' => 'Stoneham'],
                ['state_id' => 20, 'city' => 'Hanover'],
                ['state_id' => 20, 'city' => 'Hebron'],
                ['state_id' => 20, 'city' => 'Greenwood'],
                ['state_id' => 20, 'city' => 'Mexico'],
                ['state_id' => 20, 'city' => 'Newry'],
                ['state_id' => 20, 'city' => 'North Waterford'],
                ['state_id' => 20, 'city' => 'Norway'],
                ['state_id' => 20, 'city' => 'Oxford'],
                ['state_id' => 20, 'city' => 'Paris'],
                ['state_id' => 20, 'city' => 'Roxbury'],
                ['state_id' => 20, 'city' => 'Rumford'],
                ['state_id' => 20, 'city' => 'South Paris'],
                ['state_id' => 20, 'city' => 'West Bethel'],
                ['state_id' => 20, 'city' => 'West Paris'],
                ['state_id' => 20, 'city' => 'Peru'],
                ['state_id' => 20, 'city' => 'Sumner'],
                ['state_id' => 20, 'city' => 'Bangor'],
                ['state_id' => 20, 'city' => 'Bradford'],
                ['state_id' => 20, 'city' => 'Bradley'],
                ['state_id' => 20, 'city' => 'Brewer'],
                ['state_id' => 20, 'city' => 'Burlington'],
                ['state_id' => 20, 'city' => 'Greenbush'],
                ['state_id' => 20, 'city' => 'Carmel'],
                ['state_id' => 20, 'city' => 'Charleston'],
                ['state_id' => 20, 'city' => 'Corinth'],
                ['state_id' => 20, 'city' => 'Eddington'],
                ['state_id' => 20, 'city' => 'Holden'],
                ['state_id' => 20, 'city' => 'East Millinocket'],
                ['state_id' => 20, 'city' => 'Etna'],
                ['state_id' => 20, 'city' => 'Exeter'],
                ['state_id' => 20, 'city' => 'Hampden'],
                ['state_id' => 20, 'city' => 'Howland'],
                ['state_id' => 20, 'city' => 'Hudson'],
                ['state_id' => 20, 'city' => 'Kenduskeag'],
                ['state_id' => 20, 'city' => 'Kingman'],
                ['state_id' => 20, 'city' => 'Lagrange'],
                ['state_id' => 20, 'city' => 'Lee'],
                ['state_id' => 20, 'city' => 'Levant'],
                ['state_id' => 20, 'city' => 'Lincoln'],
                ['state_id' => 20, 'city' => 'Mattawamkeag'],
                ['state_id' => 20, 'city' => 'Medway'],
                ['state_id' => 20, 'city' => 'Milford'],
                ['state_id' => 20, 'city' => 'Millinocket'],
                ['state_id' => 20, 'city' => 'Old Town'],
                ['state_id' => 20, 'city' => 'Orono'],
                ['state_id' => 20, 'city' => 'Orrington'],
                ['state_id' => 20, 'city' => 'Passadumkeag'],
                ['state_id' => 20, 'city' => 'Springfield'],
                ['state_id' => 20, 'city' => 'Stetson'],
                ['state_id' => 20, 'city' => 'Stillwater'],
                ['state_id' => 20, 'city' => 'West Enfield'],
                ['state_id' => 20, 'city' => 'Winn'],
                ['state_id' => 20, 'city' => 'Patten'],
                ['state_id' => 20, 'city' => 'Stacyville'],
                ['state_id' => 20, 'city' => 'Corinna'],
                ['state_id' => 20, 'city' => 'Dexter'],
                ['state_id' => 20, 'city' => 'Dixmont'],
                ['state_id' => 20, 'city' => 'East Newport'],
                ['state_id' => 20, 'city' => 'Garland'],
                ['state_id' => 20, 'city' => 'Newport'],
                ['state_id' => 20, 'city' => 'Plymouth'],
                ['state_id' => 20, 'city' => 'Abbot'],
                ['state_id' => 20, 'city' => 'Brownville'],
                ['state_id' => 20, 'city' => 'Brownville Junction'],
                ['state_id' => 20, 'city' => 'Dover Foxcroft'],
                ['state_id' => 20, 'city' => 'Greenville'],
                ['state_id' => 20, 'city' => 'Greenville Junction'],
                ['state_id' => 20, 'city' => 'Guilford'],
                ['state_id' => 20, 'city' => 'Milo'],
                ['state_id' => 20, 'city' => 'Monson'],
                ['state_id' => 20, 'city' => 'Sangerville'],
                ['state_id' => 20, 'city' => 'Sebec'],
                ['state_id' => 20, 'city' => 'Shirley Mills'],
                ['state_id' => 20, 'city' => 'Bowdoinham'],
                ['state_id' => 20, 'city' => 'Topsham'],
                ['state_id' => 20, 'city' => 'Bowdoin'],
                ['state_id' => 20, 'city' => 'Richmond'],
                ['state_id' => 20, 'city' => 'Bath'],
                ['state_id' => 20, 'city' => 'Georgetown'],
                ['state_id' => 20, 'city' => 'Phippsburg'],
                ['state_id' => 20, 'city' => 'Sebasco Estates'],
                ['state_id' => 20, 'city' => 'Woolwich'],
                ['state_id' => 20, 'city' => 'Rockwood'],
                ['state_id' => 20, 'city' => 'Anson'],
                ['state_id' => 20, 'city' => 'Athens'],
                ['state_id' => 20, 'city' => 'Bingham'],
                ['state_id' => 20, 'city' => 'Cambridge'],
                ['state_id' => 20, 'city' => 'Canaan'],
                ['state_id' => 20, 'city' => 'Caratunk'],
                ['state_id' => 20, 'city' => 'Detroit'],
                ['state_id' => 20, 'city' => 'Fairfield'],
                ['state_id' => 20, 'city' => 'Harmony'],
                ['state_id' => 20, 'city' => 'Hartland'],
                ['state_id' => 20, 'city' => 'Hinckley'],
                ['state_id' => 20, 'city' => 'Jackman'],
                ['state_id' => 20, 'city' => 'Madison'],
                ['state_id' => 20, 'city' => 'New Portland'],
                ['state_id' => 20, 'city' => 'Norridgewock'],
                ['state_id' => 20, 'city' => 'North Anson'],
                ['state_id' => 20, 'city' => 'Palmyra'],
                ['state_id' => 20, 'city' => 'Pittsfield'],
                ['state_id' => 20, 'city' => 'Saint Albans'],
                ['state_id' => 20, 'city' => 'Shawmut'],
                ['state_id' => 20, 'city' => 'Skowhegan'],
                ['state_id' => 20, 'city' => 'Smithfield'],
                ['state_id' => 20, 'city' => 'Solon'],
                ['state_id' => 20, 'city' => 'West Forks'],
                ['state_id' => 20, 'city' => 'Palermo'],
                ['state_id' => 20, 'city' => 'Frankfort'],
                ['state_id' => 20, 'city' => 'Winterport'],
                ['state_id' => 20, 'city' => 'Islesboro'],
                ['state_id' => 20, 'city' => 'Lincolnville'],
                ['state_id' => 20, 'city' => 'Lincolnville Center'],
                ['state_id' => 20, 'city' => 'Belfast'],
                ['state_id' => 20, 'city' => 'Brooks'],
                ['state_id' => 20, 'city' => 'Burnham'],
                ['state_id' => 20, 'city' => 'Freedom'],
                ['state_id' => 20, 'city' => 'Liberty'],
                ['state_id' => 20, 'city' => 'Monroe'],
                ['state_id' => 20, 'city' => 'Morrill'],
                ['state_id' => 20, 'city' => 'Sandy Point'],
                ['state_id' => 20, 'city' => 'Searsmont'],
                ['state_id' => 20, 'city' => 'Searsport'],
                ['state_id' => 20, 'city' => 'Stockton Springs'],
                ['state_id' => 20, 'city' => 'Thorndike'],
                ['state_id' => 20, 'city' => 'Troy'],
                ['state_id' => 20, 'city' => 'Unity'],
                ['state_id' => 20, 'city' => 'Brookton'],
                ['state_id' => 20, 'city' => 'Danforth'],
                ['state_id' => 20, 'city' => 'Lambert Lake'],
                ['state_id' => 20, 'city' => 'Topsfield'],
                ['state_id' => 20, 'city' => 'Vanceboro'],
                ['state_id' => 20, 'city' => 'Waite'],
                ['state_id' => 20, 'city' => 'Addison'],
                ['state_id' => 20, 'city' => 'Beals'],
                ['state_id' => 20, 'city' => 'Calais'],
                ['state_id' => 20, 'city' => 'Cherryfield'],
                ['state_id' => 20, 'city' => 'Columbia Falls'],
                ['state_id' => 20, 'city' => 'Cutler'],
                ['state_id' => 20, 'city' => 'Dennysville'],
                ['state_id' => 20, 'city' => 'East Machias'],
                ['state_id' => 20, 'city' => 'Eastport'],
                ['state_id' => 20, 'city' => 'Grand Lake Stream'],
                ['state_id' => 20, 'city' => 'Harrington'],
                ['state_id' => 20, 'city' => 'Jonesboro'],
                ['state_id' => 20, 'city' => 'Jonesport'],
                ['state_id' => 20, 'city' => 'Lubec'],
                ['state_id' => 20, 'city' => 'Machias'],
                ['state_id' => 20, 'city' => 'Machiasport'],
                ['state_id' => 20, 'city' => 'Meddybemps'],
                ['state_id' => 20, 'city' => 'Milbridge'],
                ['state_id' => 20, 'city' => 'Pembroke'],
                ['state_id' => 20, 'city' => 'Perry'],
                ['state_id' => 20, 'city' => 'Princeton'],
                ['state_id' => 20, 'city' => 'Robbinston'],
                ['state_id' => 20, 'city' => 'Steuben'],
                ['state_id' => 20, 'city' => 'Wesley'],
                ['state_id' => 20, 'city' => 'Whiting'],
                ['state_id' => 20, 'city' => 'Baileyville'],
                ['state_id' => 20, 'city' => 'Berwick'],
                ['state_id' => 20, 'city' => 'Cape Neddick'],
                ['state_id' => 20, 'city' => 'Eliot'],
                ['state_id' => 20, 'city' => 'Kittery'],
                ['state_id' => 20, 'city' => 'Kittery Point'],
                ['state_id' => 20, 'city' => 'North Berwick'],
                ['state_id' => 20, 'city' => 'Ogunquit'],
                ['state_id' => 20, 'city' => 'South Berwick'],
                ['state_id' => 20, 'city' => 'York'],
                ['state_id' => 20, 'city' => 'York Beach'],
                ['state_id' => 20, 'city' => 'York Harbor'],
                ['state_id' => 20, 'city' => 'Acton'],
                ['state_id' => 20, 'city' => 'Alfred'],
                ['state_id' => 20, 'city' => 'Bar Mills'],
                ['state_id' => 20, 'city' => 'Biddeford'],
                ['state_id' => 20, 'city' => 'Biddeford Pool'],
                ['state_id' => 20, 'city' => 'Cape Porpoise'],
                ['state_id' => 20, 'city' => 'Cornish'],
                ['state_id' => 20, 'city' => 'Lebanon'],
                ['state_id' => 20, 'city' => 'East Parsonsfield'],
                ['state_id' => 20, 'city' => 'East Waterboro'],
                ['state_id' => 20, 'city' => 'Hollis Center'],
                ['state_id' => 20, 'city' => 'Kennebunk'],
                ['state_id' => 20, 'city' => 'Kennebunkport'],
                ['state_id' => 20, 'city' => 'Parsonsfield'],
                ['state_id' => 20, 'city' => 'Limerick'],
                ['state_id' => 20, 'city' => 'Limington'],
                ['state_id' => 20, 'city' => 'Moody'],
                ['state_id' => 20, 'city' => 'Newfield'],
                ['state_id' => 20, 'city' => 'North Waterboro'],
                ['state_id' => 20, 'city' => 'Ocean Park'],
                ['state_id' => 20, 'city' => 'Old Orchard Beach'],
                ['state_id' => 20, 'city' => 'Saco'],
                ['state_id' => 20, 'city' => 'Sanford'],
                ['state_id' => 20, 'city' => 'Shapleigh'],
                ['state_id' => 20, 'city' => 'Springvale'],
                ['state_id' => 20, 'city' => 'Waterboro'],
                ['state_id' => 20, 'city' => 'Wells'],
                ['state_id' => 20, 'city' => 'Buxton'],
                ['state_id' => 20, 'city' => 'West Kennebunk'],
                ['state_id' => 20, 'city' => 'West Newfield']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
