<?php

namespace Database\Seeders\statecities;
use App\Models\City;
use Illuminate\Database\Seeder;

class State41TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of SC - South Carolina.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 41, 'city' => 'Abbeville'],
                ['state_id' => 41, 'city' => 'Calhoun Falls'],
                ['state_id' => 41, 'city' => 'Donalds'],
                ['state_id' => 41, 'city' => 'Due West'],
                ['state_id' => 41, 'city' => 'Lowndesville'],
                ['state_id' => 41, 'city' => 'Salley'],
                ['state_id' => 41, 'city' => 'Wagener'],
                ['state_id' => 41, 'city' => 'Aiken'],
                ['state_id' => 41, 'city' => 'New Ellenton'],
                ['state_id' => 41, 'city' => 'Bath'],
                ['state_id' => 41, 'city' => 'Clearwater'],
                ['state_id' => 41, 'city' => 'Gloverville'],
                ['state_id' => 41, 'city' => 'Graniteville'],
                ['state_id' => 41, 'city' => 'Jackson'],
                ['state_id' => 41, 'city' => 'Langley'],
                ['state_id' => 41, 'city' => 'Montmorenci'],
                ['state_id' => 41, 'city' => 'North Augusta'],
                ['state_id' => 41, 'city' => 'Beech Island'],
                ['state_id' => 41, 'city' => 'Vaucluse'],
                ['state_id' => 41, 'city' => 'Warrenville'],
                ['state_id' => 41, 'city' => 'Windsor'],
                ['state_id' => 41, 'city' => 'Allendale'],
                ['state_id' => 41, 'city' => 'Fairfax'],
                ['state_id' => 41, 'city' => 'Martin'],
                ['state_id' => 41, 'city' => 'Sycamore'],
                ['state_id' => 41, 'city' => 'Ulmer'],
                ['state_id' => 41, 'city' => 'Anderson'],
                ['state_id' => 41, 'city' => 'Belton'],
                ['state_id' => 41, 'city' => 'Honea Path'],
                ['state_id' => 41, 'city' => 'Iva'],
                ['state_id' => 41, 'city' => 'La France'],
                ['state_id' => 41, 'city' => 'Pelzer'],
                ['state_id' => 41, 'city' => 'Pendleton'],
                ['state_id' => 41, 'city' => 'Sandy Springs'],
                ['state_id' => 41, 'city' => 'Starr'],
                ['state_id' => 41, 'city' => 'Townville'],
                ['state_id' => 41, 'city' => 'Williamston'],
                ['state_id' => 41, 'city' => 'Bamberg'],
                ['state_id' => 41, 'city' => 'Denmark'],
                ['state_id' => 41, 'city' => 'Ehrhardt'],
                ['state_id' => 41, 'city' => 'Olar'],
                ['state_id' => 41, 'city' => 'Barnwell'],
                ['state_id' => 41, 'city' => 'Hilda'],
                ['state_id' => 41, 'city' => 'Blackville'],
                ['state_id' => 41, 'city' => 'Elko'],
                ['state_id' => 41, 'city' => 'Williston'],
                ['state_id' => 41, 'city' => 'Beaufort'],
                ['state_id' => 41, 'city' => 'Parris Island'],
                ['state_id' => 41, 'city' => 'Bluffton'],
                ['state_id' => 41, 'city' => 'Dale'],
                ['state_id' => 41, 'city' => 'Daufuskie Island'],
                ['state_id' => 41, 'city' => 'Saint Helena Island'],
                ['state_id' => 41, 'city' => 'Hilton Head Island'],
                ['state_id' => 41, 'city' => 'Lobeco'],
                ['state_id' => 41, 'city' => 'Port Royal'],
                ['state_id' => 41, 'city' => 'Seabrook'],
                ['state_id' => 41, 'city' => 'Sheldon'],
                ['state_id' => 41, 'city' => 'Hanahan'],
                ['state_id' => 41, 'city' => 'Bonneau'],
                ['state_id' => 41, 'city' => 'Cordesville'],
                ['state_id' => 41, 'city' => 'Cross'],
                ['state_id' => 41, 'city' => 'Goose Creek'],
                ['state_id' => 41, 'city' => 'Huger'],
                ['state_id' => 41, 'city' => 'Jamestown'],
                ['state_id' => 41, 'city' => 'Ladson'],
                ['state_id' => 41, 'city' => 'Moncks Corner'],
                ['state_id' => 41, 'city' => 'Pineville'],
                ['state_id' => 41, 'city' => 'Pinopolis'],
                ['state_id' => 41, 'city' => 'Russellville'],
                ['state_id' => 41, 'city' => 'Saint Stephen'],
                ['state_id' => 41, 'city' => 'Summerville'],
                ['state_id' => 41, 'city' => 'Charleston'],
                ['state_id' => 41, 'city' => 'Cameron'],
                ['state_id' => 41, 'city' => 'Saint Matthews'],
                ['state_id' => 41, 'city' => 'Charleston Afb'],
                ['state_id' => 41, 'city' => 'North Charleston'],
                ['state_id' => 41, 'city' => 'Adams Run'],
                ['state_id' => 41, 'city' => 'Awendaw'],
                ['state_id' => 41, 'city' => 'Folly Beach'],
                ['state_id' => 41, 'city' => 'Hollywood'],
                ['state_id' => 41, 'city' => 'Isle Of Palms'],
                ['state_id' => 41, 'city' => 'Johns Island'],
                ['state_id' => 41, 'city' => 'Mc Clellanville'],
                ['state_id' => 41, 'city' => 'Mount Pleasant'],
                ['state_id' => 41, 'city' => 'Ravenel'],
                ['state_id' => 41, 'city' => 'Sullivans Island'],
                ['state_id' => 41, 'city' => 'Wadmalaw Island'],
                ['state_id' => 41, 'city' => 'Gaffney'],
                ['state_id' => 41, 'city' => 'Blacksburg'],
                ['state_id' => 41, 'city' => 'Blackstock'],
                ['state_id' => 41, 'city' => 'Great Falls'],
                ['state_id' => 41, 'city' => 'Chester'],
                ['state_id' => 41, 'city' => 'Edgemoor'],
                ['state_id' => 41, 'city' => 'Fort Lawn'],
                ['state_id' => 41, 'city' => 'Lando'],
                ['state_id' => 41, 'city' => 'Richburg'],
                ['state_id' => 41, 'city' => 'Mc Bee'],
                ['state_id' => 41, 'city' => 'Cheraw'],
                ['state_id' => 41, 'city' => 'Patrick'],
                ['state_id' => 41, 'city' => 'Chesterfield'],
                ['state_id' => 41, 'city' => 'Jefferson'],
                ['state_id' => 41, 'city' => 'Mount Croghan'],
                ['state_id' => 41, 'city' => 'Pageland'],
                ['state_id' => 41, 'city' => 'Ruby'],
                ['state_id' => 41, 'city' => 'Alcolu'],
                ['state_id' => 41, 'city' => 'Davis Station'],
                ['state_id' => 41, 'city' => 'Gable'],
                ['state_id' => 41, 'city' => 'Manning'],
                ['state_id' => 41, 'city' => 'New Zion'],
                ['state_id' => 41, 'city' => 'Sardinia'],
                ['state_id' => 41, 'city' => 'Summerton'],
                ['state_id' => 41, 'city' => 'Turbeville'],
                ['state_id' => 41, 'city' => 'Lodge'],
                ['state_id' => 41, 'city' => 'Canadys'],
                ['state_id' => 41, 'city' => 'Cottageville'],
                ['state_id' => 41, 'city' => 'Edisto Island'],
                ['state_id' => 41, 'city' => 'Green Pond'],
                ['state_id' => 41, 'city' => 'Jacksonboro'],
                ['state_id' => 41, 'city' => 'Round O'],
                ['state_id' => 41, 'city' => 'Ruffin'],
                ['state_id' => 41, 'city' => 'Smoaks'],
                ['state_id' => 41, 'city' => 'Walterboro'],
                ['state_id' => 41, 'city' => 'Williams'],
                ['state_id' => 41, 'city' => 'Islandton'],
                ['state_id' => 41, 'city' => 'Lamar'],
                ['state_id' => 41, 'city' => 'Lydia'],
                ['state_id' => 41, 'city' => 'Darlington'],
                ['state_id' => 41, 'city' => 'Hartsville'],
                ['state_id' => 41, 'city' => 'Society Hill'],
                ['state_id' => 41, 'city' => 'Dillon'],
                ['state_id' => 41, 'city' => 'Fork'],
                ['state_id' => 41, 'city' => 'Hamer'],
                ['state_id' => 41, 'city' => 'Lake View'],
                ['state_id' => 41, 'city' => 'Latta'],
                ['state_id' => 41, 'city' => 'Little Rock'],
                ['state_id' => 41, 'city' => 'Dorchester'],
                ['state_id' => 41, 'city' => 'Grover'],
                ['state_id' => 41, 'city' => 'Harleyville'],
                ['state_id' => 41, 'city' => 'Reevesville'],
                ['state_id' => 41, 'city' => 'Ridgeville'],
                ['state_id' => 41, 'city' => 'Saint George'],
                ['state_id' => 41, 'city' => 'Edgefield'],
                ['state_id' => 41, 'city' => 'Johnston'],
                ['state_id' => 41, 'city' => 'Trenton'],
                ['state_id' => 41, 'city' => 'Blair'],
                ['state_id' => 41, 'city' => 'Jenkinsville'],
                ['state_id' => 41, 'city' => 'Ridgeway'],
                ['state_id' => 41, 'city' => 'Rion'],
                ['state_id' => 41, 'city' => 'Winnsboro'],
                ['state_id' => 41, 'city' => 'Olanta'],
                ['state_id' => 41, 'city' => 'Timmonsville'],
                ['state_id' => 41, 'city' => 'Florence'],
                ['state_id' => 41, 'city' => 'Coward'],
                ['state_id' => 41, 'city' => 'Effingham'],
                ['state_id' => 41, 'city' => 'Johnsonville'],
                ['state_id' => 41, 'city' => 'Lake City'],
                ['state_id' => 41, 'city' => 'Pamplico'],
                ['state_id' => 41, 'city' => 'Scranton'],
                ['state_id' => 41, 'city' => 'Georgetown'],
                ['state_id' => 41, 'city' => 'Andrews'],
                ['state_id' => 41, 'city' => 'Murrells Inlet'],
                ['state_id' => 41, 'city' => 'Pawleys Island'],
                ['state_id' => 41, 'city' => 'Greenville'],
                ['state_id' => 41, 'city' => 'Cleveland'],
                ['state_id' => 41, 'city' => 'Conestee'],
                ['state_id' => 41, 'city' => 'Fountain Inn'],
                ['state_id' => 41, 'city' => 'Greer'],
                ['state_id' => 41, 'city' => 'Marietta'],
                ['state_id' => 41, 'city' => 'Mauldin'],
                ['state_id' => 41, 'city' => 'Piedmont'],
                ['state_id' => 41, 'city' => 'Simpsonville'],
                ['state_id' => 41, 'city' => 'Slater'],
                ['state_id' => 41, 'city' => 'Taylors'],
                ['state_id' => 41, 'city' => 'Tigerville'],
                ['state_id' => 41, 'city' => 'Travelers Rest'],
                ['state_id' => 41, 'city' => 'Greenwood'],
                ['state_id' => 41, 'city' => 'Hodges'],
                ['state_id' => 41, 'city' => 'Ninety Six'],
                ['state_id' => 41, 'city' => 'Ware Shoals'],
                ['state_id' => 41, 'city' => 'Bradley'],
                ['state_id' => 41, 'city' => 'Troy'],
                ['state_id' => 41, 'city' => 'Brunson'],
                ['state_id' => 41, 'city' => 'Crocketville'],
                ['state_id' => 41, 'city' => 'Early Branch'],
                ['state_id' => 41, 'city' => 'Estill'],
                ['state_id' => 41, 'city' => 'Furman'],
                ['state_id' => 41, 'city' => 'Garnett'],
                ['state_id' => 41, 'city' => 'Gifford'],
                ['state_id' => 41, 'city' => 'Hampton'],
                ['state_id' => 41, 'city' => 'Luray'],
                ['state_id' => 41, 'city' => 'Miley'],
                ['state_id' => 41, 'city' => 'Scotia'],
                ['state_id' => 41, 'city' => 'Varnville'],
                ['state_id' => 41, 'city' => 'Yemassee'],
                ['state_id' => 41, 'city' => 'Aynor'],
                ['state_id' => 41, 'city' => 'Conway'],
                ['state_id' => 41, 'city' => 'Galivants Ferry'],
                ['state_id' => 41, 'city' => 'Green Sea'],
                ['state_id' => 41, 'city' => 'Little River'],
                ['state_id' => 41, 'city' => 'Longs'],
                ['state_id' => 41, 'city' => 'Loris'],
                ['state_id' => 41, 'city' => 'Myrtle Beach'],
                ['state_id' => 41, 'city' => 'Nichols'],
                ['state_id' => 41, 'city' => 'North Myrtle Beach'],
                ['state_id' => 41, 'city' => 'Okatie'],
                ['state_id' => 41, 'city' => 'Coosawhatchie'],
                ['state_id' => 41, 'city' => 'Hardeeville'],
                ['state_id' => 41, 'city' => 'Pineland'],
                ['state_id' => 41, 'city' => 'Ridgeland'],
                ['state_id' => 41, 'city' => 'Tillman'],
                ['state_id' => 41, 'city' => 'Bethune'],
                ['state_id' => 41, 'city' => 'Camden'],
                ['state_id' => 41, 'city' => 'Cassatt'],
                ['state_id' => 41, 'city' => 'Elgin'],
                ['state_id' => 41, 'city' => 'Liberty Hill'],
                ['state_id' => 41, 'city' => 'Lugoff'],
                ['state_id' => 41, 'city' => 'Westville'],
                ['state_id' => 41, 'city' => 'Heath Springs'],
                ['state_id' => 41, 'city' => 'Kershaw'],
                ['state_id' => 41, 'city' => 'Fort Mill'],
                ['state_id' => 41, 'city' => 'Lancaster'],
                ['state_id' => 41, 'city' => 'Van Wyck'],
                ['state_id' => 41, 'city' => 'Clinton'],
                ['state_id' => 41, 'city' => 'Cross Hill'],
                ['state_id' => 41, 'city' => 'Joanna'],
                ['state_id' => 41, 'city' => 'Laurens'],
                ['state_id' => 41, 'city' => 'Mountville'],
                ['state_id' => 41, 'city' => 'Waterloo'],
                ['state_id' => 41, 'city' => 'Gray Court'],
                ['state_id' => 41, 'city' => 'Bishopville'],
                ['state_id' => 41, 'city' => 'Elliott'],
                ['state_id' => 41, 'city' => 'Lynchburg'],
                ['state_id' => 41, 'city' => 'Batesburg'],
                ['state_id' => 41, 'city' => 'Cayce'],
                ['state_id' => 41, 'city' => 'Chapin'],
                ['state_id' => 41, 'city' => 'Gaston'],
                ['state_id' => 41, 'city' => 'Gilbert'],
                ['state_id' => 41, 'city' => 'Leesville'],
                ['state_id' => 41, 'city' => 'Lexington'],
                ['state_id' => 41, 'city' => 'Pelion'],
                ['state_id' => 41, 'city' => 'Swansea'],
                ['state_id' => 41, 'city' => 'West Columbia'],
                ['state_id' => 41, 'city' => 'Columbia'],
                ['state_id' => 41, 'city' => 'Clarks Hill'],
                ['state_id' => 41, 'city' => 'Mc Cormick'],
                ['state_id' => 41, 'city' => 'Modoc'],
                ['state_id' => 41, 'city' => 'Mount Carmel'],
                ['state_id' => 41, 'city' => 'Parksville'],
                ['state_id' => 41, 'city' => 'Plum Branch'],
                ['state_id' => 41, 'city' => 'Centenary'],
                ['state_id' => 41, 'city' => 'Gresham'],
                ['state_id' => 41, 'city' => 'Marion'],
                ['state_id' => 41, 'city' => 'Mullins'],
                ['state_id' => 41, 'city' => 'Rains'],
                ['state_id' => 41, 'city' => 'Sellers'],
                ['state_id' => 41, 'city' => 'Bennettsville'],
                ['state_id' => 41, 'city' => 'Blenheim'],
                ['state_id' => 41, 'city' => 'Clio'],
                ['state_id' => 41, 'city' => 'Mc Coll'],
                ['state_id' => 41, 'city' => 'Tatum'],
                ['state_id' => 41, 'city' => 'Wallace'],
                ['state_id' => 41, 'city' => 'Chappells'],
                ['state_id' => 41, 'city' => 'Little Mountain'],
                ['state_id' => 41, 'city' => 'Newberry'],
                ['state_id' => 41, 'city' => 'Peak'],
                ['state_id' => 41, 'city' => 'Pomaria'],
                ['state_id' => 41, 'city' => 'Prosperity'],
                ['state_id' => 41, 'city' => 'Silverstreet'],
                ['state_id' => 41, 'city' => 'Whitmire'],
                ['state_id' => 41, 'city' => 'Kinards'],
                ['state_id' => 41, 'city' => 'Fair Play'],
                ['state_id' => 41, 'city' => 'Long Creek'],
                ['state_id' => 41, 'city' => 'Mountain Rest'],
                ['state_id' => 41, 'city' => 'Newry'],
                ['state_id' => 41, 'city' => 'Seneca'],
                ['state_id' => 41, 'city' => 'Richland'],
                ['state_id' => 41, 'city' => 'Salem'],
                ['state_id' => 41, 'city' => 'Tamassee'],
                ['state_id' => 41, 'city' => 'Walhalla'],
                ['state_id' => 41, 'city' => 'Westminster'],
                ['state_id' => 41, 'city' => 'West Union'],
                ['state_id' => 41, 'city' => 'Bowman'],
                ['state_id' => 41, 'city' => 'Cope'],
                ['state_id' => 41, 'city' => 'Cordova'],
                ['state_id' => 41, 'city' => 'Elloree'],
                ['state_id' => 41, 'city' => 'Eutawville'],
                ['state_id' => 41, 'city' => 'Holly Hill'],
                ['state_id' => 41, 'city' => 'Neeses'],
                ['state_id' => 41, 'city' => 'North'],
                ['state_id' => 41, 'city' => 'Norway'],
                ['state_id' => 41, 'city' => 'Orangeburg'],
                ['state_id' => 41, 'city' => 'Rowesville'],
                ['state_id' => 41, 'city' => 'Santee'],
                ['state_id' => 41, 'city' => 'Springfield'],
                ['state_id' => 41, 'city' => 'Vance'],
                ['state_id' => 41, 'city' => 'Branchville'],
                ['state_id' => 41, 'city' => 'Central'],
                ['state_id' => 41, 'city' => 'Clemson'],
                ['state_id' => 41, 'city' => 'Easley'],
                ['state_id' => 41, 'city' => 'Liberty'],
                ['state_id' => 41, 'city' => 'Norris'],
                ['state_id' => 41, 'city' => 'Pickens'],
                ['state_id' => 41, 'city' => 'Six Mile'],
                ['state_id' => 41, 'city' => 'Sunset'],
                ['state_id' => 41, 'city' => 'Ballentine'],
                ['state_id' => 41, 'city' => 'Blythewood'],
                ['state_id' => 41, 'city' => 'Eastover'],
                ['state_id' => 41, 'city' => 'Gadsden'],
                ['state_id' => 41, 'city' => 'Hopkins'],
                ['state_id' => 41, 'city' => 'Irmo'],
                ['state_id' => 41, 'city' => 'State Park'],
                ['state_id' => 41, 'city' => 'White Rock'],
                ['state_id' => 41, 'city' => 'Monetta'],
                ['state_id' => 41, 'city' => 'Ridge Spring'],
                ['state_id' => 41, 'city' => 'Saluda'],
                ['state_id' => 41, 'city' => 'Ward'],
                ['state_id' => 41, 'city' => 'Spartanburg'],
                ['state_id' => 41, 'city' => 'Boiling Springs'],
                ['state_id' => 41, 'city' => 'Arcadia'],
                ['state_id' => 41, 'city' => 'Campobello'],
                ['state_id' => 41, 'city' => 'Chesnee'],
                ['state_id' => 41, 'city' => 'Clifton'],
                ['state_id' => 41, 'city' => 'Converse'],
                ['state_id' => 41, 'city' => 'Cowpens'],
                ['state_id' => 41, 'city' => 'Cross Anchor'],
                ['state_id' => 41, 'city' => 'Drayton'],
                ['state_id' => 41, 'city' => 'Duncan'],
                ['state_id' => 41, 'city' => 'Enoree'],
                ['state_id' => 41, 'city' => 'Fairforest'],
                ['state_id' => 41, 'city' => 'Fingerville'],
                ['state_id' => 41, 'city' => 'Glendale'],
                ['state_id' => 41, 'city' => 'Gramling'],
                ['state_id' => 41, 'city' => 'Inman'],
                ['state_id' => 41, 'city' => 'Landrum'],
                ['state_id' => 41, 'city' => 'Lyman'],
                ['state_id' => 41, 'city' => 'Mayo'],
                ['state_id' => 41, 'city' => 'Moore'],
                ['state_id' => 41, 'city' => 'Pacolet'],
                ['state_id' => 41, 'city' => 'Pacolet Mills'],
                ['state_id' => 41, 'city' => 'Pauline'],
                ['state_id' => 41, 'city' => 'Reidville'],
                ['state_id' => 41, 'city' => 'Roebuck'],
                ['state_id' => 41, 'city' => 'Startex'],
                ['state_id' => 41, 'city' => 'Una'],
                ['state_id' => 41, 'city' => 'Wellford'],
                ['state_id' => 41, 'city' => 'White Stone'],
                ['state_id' => 41, 'city' => 'Woodruff'],
                ['state_id' => 41, 'city' => 'Dalzell'],
                ['state_id' => 41, 'city' => 'Horatio'],
                ['state_id' => 41, 'city' => 'Mayesville'],
                ['state_id' => 41, 'city' => 'Pinewood'],
                ['state_id' => 41, 'city' => 'Rembert'],
                ['state_id' => 41, 'city' => 'Sumter'],
                ['state_id' => 41, 'city' => 'Shaw Afb'],
                ['state_id' => 41, 'city' => 'Wedgefield'],
                ['state_id' => 41, 'city' => 'Carlisle'],
                ['state_id' => 41, 'city' => 'Buffalo'],
                ['state_id' => 41, 'city' => 'Jonesville'],
                ['state_id' => 41, 'city' => 'Lockhart'],
                ['state_id' => 41, 'city' => 'Union'],
                ['state_id' => 41, 'city' => 'Greeleyville'],
                ['state_id' => 41, 'city' => 'Cades'],
                ['state_id' => 41, 'city' => 'Hemingway'],
                ['state_id' => 41, 'city' => 'Kingstree'],
                ['state_id' => 41, 'city' => 'Lane'],
                ['state_id' => 41, 'city' => 'Nesmith'],
                ['state_id' => 41, 'city' => 'Salters'],
                ['state_id' => 41, 'city' => 'Bowling Green'],
                ['state_id' => 41, 'city' => 'Catawba'],
                ['state_id' => 41, 'city' => 'Clover'],
                ['state_id' => 41, 'city' => 'Hickory Grove'],
                ['state_id' => 41, 'city' => 'Mc Connells'],
                ['state_id' => 41, 'city' => 'Rock Hill'],
                ['state_id' => 41, 'city' => 'Sharon'],
                ['state_id' => 41, 'city' => 'Smyrna'],
                ['state_id' => 41, 'city' => 'York', 'state_id' => 41]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
