<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State22TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MA - Massachusetts.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 22, 'city' => 'Buzzards Bay'],
                ['state_id' => 22, 'city' => 'Cataumet'],
                ['state_id' => 22, 'city' => 'East Falmouth'],
                ['state_id' => 22, 'city' => 'East Sandwich'],
                ['state_id' => 22, 'city' => 'Falmouth'],
                ['state_id' => 22, 'city' => 'Woods Hole'],
                ['state_id' => 22, 'city' => 'Monument Beach'],
                ['state_id' => 22, 'city' => 'North Falmouth'],
                ['state_id' => 22, 'city' => 'Pocasset'],
                ['state_id' => 22, 'city' => 'Sagamore'],
                ['state_id' => 22, 'city' => 'Sagamore Beach'],
                ['state_id' => 22, 'city' => 'Sandwich'],
                ['state_id' => 22, 'city' => 'West Falmouth'],
                ['state_id' => 22, 'city' => 'Hyannis'],
                ['state_id' => 22, 'city' => 'Barnstable'],
                ['state_id' => 22, 'city' => 'Brewster'],
                ['state_id' => 22, 'city' => 'Centerville'],
                ['state_id' => 22, 'city' => 'Chatham'],
                ['state_id' => 22, 'city' => 'Cotuit'],
                ['state_id' => 22, 'city' => 'Cummaquid'],
                ['state_id' => 22, 'city' => 'Dennis'],
                ['state_id' => 22, 'city' => 'Dennis Port'],
                ['state_id' => 22, 'city' => 'East Dennis'],
                ['state_id' => 22, 'city' => 'Eastham'],
                ['state_id' => 22, 'city' => 'East Orleans'],
                ['state_id' => 22, 'city' => 'Forestdale'],
                ['state_id' => 22, 'city' => 'Harwich'],
                ['state_id' => 22, 'city' => 'Harwich Port'],
                ['state_id' => 22, 'city' => 'Hyannis Port'],
                ['state_id' => 22, 'city' => 'Marstons Mills'],
                ['state_id' => 22, 'city' => 'Mashpee'],
                ['state_id' => 22, 'city' => 'North Chatham'],
                ['state_id' => 22, 'city' => 'North Eastham'],
                ['state_id' => 22, 'city' => 'North Truro'],
                ['state_id' => 22, 'city' => 'Orleans'],
                ['state_id' => 22, 'city' => 'Osterville'],
                ['state_id' => 22, 'city' => 'Provincetown'],
                ['state_id' => 22, 'city' => 'South Chatham'],
                ['state_id' => 22, 'city' => 'South Dennis'],
                ['state_id' => 22, 'city' => 'South Harwich'],
                ['state_id' => 22, 'city' => 'South Orleans'],
                ['state_id' => 22, 'city' => 'South Wellfleet'],
                ['state_id' => 22, 'city' => 'South Yarmouth'],
                ['state_id' => 22, 'city' => 'Truro'],
                ['state_id' => 22, 'city' => 'Wellfleet'],
                ['state_id' => 22, 'city' => 'West Barnstable'],
                ['state_id' => 22, 'city' => 'West Chatham'],
                ['state_id' => 22, 'city' => 'West Dennis'],
                ['state_id' => 22, 'city' => 'West Harwich'],
                ['state_id' => 22, 'city' => 'West Hyannisport'],
                ['state_id' => 22, 'city' => 'West Yarmouth'],
                ['state_id' => 22, 'city' => 'Yarmouth Port'],
                ['state_id' => 22, 'city' => 'East Otis'],
                ['state_id' => 22, 'city' => 'Pittsfield'],
                ['state_id' => 22, 'city' => 'Adams'],
                ['state_id' => 22, 'city' => 'Ashley Falls'],
                ['state_id' => 22, 'city' => 'Becket'],
                ['state_id' => 22, 'city' => 'Berkshire'],
                ['state_id' => 22, 'city' => 'Cheshire'],
                ['state_id' => 22, 'city' => 'Dalton'],
                ['state_id' => 22, 'city' => 'Glendale'],
                ['state_id' => 22, 'city' => 'Great Barrington'],
                ['state_id' => 22, 'city' => 'Hinsdale'],
                ['state_id' => 22, 'city' => 'Housatonic'],
                ['state_id' => 22, 'city' => 'Lanesborough'],
                ['state_id' => 22, 'city' => 'Lee'],
                ['state_id' => 22, 'city' => 'Lenox'],
                ['state_id' => 22, 'city' => 'Lenox Dale'],
                ['state_id' => 22, 'city' => 'Mill River'],
                ['state_id' => 22, 'city' => 'Monterey'],
                ['state_id' => 22, 'city' => 'North Adams'],
                ['state_id' => 22, 'city' => 'North Egremont'],
                ['state_id' => 22, 'city' => 'Otis'],
                ['state_id' => 22, 'city' => 'Richmond'],
                ['state_id' => 22, 'city' => 'Sandisfield'],
                ['state_id' => 22, 'city' => 'Savoy'],
                ['state_id' => 22, 'city' => 'Sheffield'],
                ['state_id' => 22, 'city' => 'South Egremont'],
                ['state_id' => 22, 'city' => 'Southfield'],
                ['state_id' => 22, 'city' => 'South Lee'],
                ['state_id' => 22, 'city' => 'Stockbridge'],
                ['state_id' => 22, 'city' => 'Tyringham'],
                ['state_id' => 22, 'city' => 'West Stockbridge'],
                ['state_id' => 22, 'city' => 'Williamstown'],
                ['state_id' => 22, 'city' => 'Windsor'],
                ['state_id' => 22, 'city' => 'Drury'],
                ['state_id' => 22, 'city' => 'Mansfield'],
                ['state_id' => 22, 'city' => 'Easton'],
                ['state_id' => 22, 'city' => 'North Easton'],
                ['state_id' => 22, 'city' => 'South Easton'],
                ['state_id' => 22, 'city' => 'Assonet'],
                ['state_id' => 22, 'city' => 'Attleboro'],
                ['state_id' => 22, 'city' => 'Chartley'],
                ['state_id' => 22, 'city' => 'Dartmouth'],
                ['state_id' => 22, 'city' => 'Dighton'],
                ['state_id' => 22, 'city' => 'East Freetown'],
                ['state_id' => 22, 'city' => 'East Taunton'],
                ['state_id' => 22, 'city' => 'Fairhaven'],
                ['state_id' => 22, 'city' => 'Fall River'],
                ['state_id' => 22, 'city' => 'Somerset'],
                ['state_id' => 22, 'city' => 'New Bedford'],
                ['state_id' => 22, 'city' => 'Acushnet'],
                ['state_id' => 22, 'city' => 'North Dartmouth'],
                ['state_id' => 22, 'city' => 'South Dartmouth'],
                ['state_id' => 22, 'city' => 'North Attleboro'],
                ['state_id' => 22, 'city' => 'Attleboro Falls'],
                ['state_id' => 22, 'city' => 'North Dighton'],
                ['state_id' => 22, 'city' => 'Norton'],
                ['state_id' => 22, 'city' => 'Raynham'],
                ['state_id' => 22, 'city' => 'Raynham Center'],
                ['state_id' => 22, 'city' => 'Rehoboth'],
                ['state_id' => 22, 'city' => 'Seekonk'],
                ['state_id' => 22, 'city' => 'Swansea'],
                ['state_id' => 22, 'city' => 'Berkley'],
                ['state_id' => 22, 'city' => 'Taunton'],
                ['state_id' => 22, 'city' => 'Westport'],
                ['state_id' => 22, 'city' => 'Westport Point'],
                ['state_id' => 22, 'city' => 'Chilmark'],
                ['state_id' => 22, 'city' => 'Edgartown'],
                ['state_id' => 22, 'city' => 'Menemsha'],
                ['state_id' => 22, 'city' => 'Oak Bluffs'],
                ['state_id' => 22, 'city' => 'Vineyard Haven'],
                ['state_id' => 22, 'city' => 'West Tisbury'],
                ['state_id' => 22, 'city' => 'Cuttyhunk'],
                ['state_id' => 22, 'city' => 'Andover'],
                ['state_id' => 22, 'city' => 'Haverhill'],
                ['state_id' => 22, 'city' => 'Georgetown'],
                ['state_id' => 22, 'city' => 'Groveland'],
                ['state_id' => 22, 'city' => 'Lawrence'],
                ['state_id' => 22, 'city' => 'Methuen'],
                ['state_id' => 22, 'city' => 'North Andover'],
                ['state_id' => 22, 'city' => 'Merrimac'],
                ['state_id' => 22, 'city' => 'West Boxford'],
                ['state_id' => 22, 'city' => 'Lynn'],
                ['state_id' => 22, 'city' => 'Saugus'],
                ['state_id' => 22, 'city' => 'Swampscott'],
                ['state_id' => 22, 'city' => 'Nahant'],
                ['state_id' => 22, 'city' => 'Amesbury'],
                ['state_id' => 22, 'city' => 'Beverly'],
                ['state_id' => 22, 'city' => 'Boxford'],
                ['state_id' => 22, 'city' => 'Byfield'],
                ['state_id' => 22, 'city' => 'Danvers'],
                ['state_id' => 22, 'city' => 'Essex'],
                ['state_id' => 22, 'city' => 'Gloucester'],
                ['state_id' => 22, 'city' => 'Hamilton'],
                ['state_id' => 22, 'city' => 'Hathorne'],
                ['state_id' => 22, 'city' => 'Ipswich'],
                ['state_id' => 22, 'city' => 'Lynnfield'],
                ['state_id' => 22, 'city' => 'Manchester'],
                ['state_id' => 22, 'city' => 'Marblehead'],
                ['state_id' => 22, 'city' => 'Middleton'],
                ['state_id' => 22, 'city' => 'Newburyport'],
                ['state_id' => 22, 'city' => 'Newbury'],
                ['state_id' => 22, 'city' => 'Salisbury'],
                ['state_id' => 22, 'city' => 'Peabody'],
                ['state_id' => 22, 'city' => 'Prides Crossing'],
                ['state_id' => 22, 'city' => 'Rockport'],
                ['state_id' => 22, 'city' => 'Rowley'],
                ['state_id' => 22, 'city' => 'Salem'],
                ['state_id' => 22, 'city' => 'South Hamilton'],
                ['state_id' => 22, 'city' => 'Topsfield'],
                ['state_id' => 22, 'city' => 'Wenham'],
                ['state_id' => 22, 'city' => 'West Newbury'],
                ['state_id' => 22, 'city' => 'Leverett'],
                ['state_id' => 22, 'city' => 'Shutesbury'],
                ['state_id' => 22, 'city' => 'Whately'],
                ['state_id' => 22, 'city' => 'Greenfield'],
                ['state_id' => 22, 'city' => 'Ashfield'],
                ['state_id' => 22, 'city' => 'Bernardston'],
                ['state_id' => 22, 'city' => 'Buckland'],
                ['state_id' => 22, 'city' => 'Charlemont'],
                ['state_id' => 22, 'city' => 'Colrain'],
                ['state_id' => 22, 'city' => 'Conway'],
                ['state_id' => 22, 'city' => 'Deerfield'],
                ['state_id' => 22, 'city' => 'Erving'],
                ['state_id' => 22, 'city' => 'Heath'],
                ['state_id' => 22, 'city' => 'Lake Pleasant'],
                ['state_id' => 22, 'city' => 'Millers Falls'],
                ['state_id' => 22, 'city' => 'Monroe Bridge'],
                ['state_id' => 22, 'city' => 'Montague'],
                ['state_id' => 22, 'city' => 'Gill'],
                ['state_id' => 22, 'city' => 'New Salem'],
                ['state_id' => 22, 'city' => 'Northfield'],
                ['state_id' => 22, 'city' => 'Orange'],
                ['state_id' => 22, 'city' => 'Rowe'],
                ['state_id' => 22, 'city' => 'Shelburne Falls'],
                ['state_id' => 22, 'city' => 'South Deerfield'],
                ['state_id' => 22, 'city' => 'Sunderland'],
                ['state_id' => 22, 'city' => 'Turners Falls'],
                ['state_id' => 22, 'city' => 'Warwick'],
                ['state_id' => 22, 'city' => 'Wendell'],
                ['state_id' => 22, 'city' => 'Wendell Depot'],
                ['state_id' => 22, 'city' => 'Agawam'],
                ['state_id' => 22, 'city' => 'Blandford'],
                ['state_id' => 22, 'city' => 'Bondsville'],
                ['state_id' => 22, 'city' => 'Brimfield'],
                ['state_id' => 22, 'city' => 'Chester'],
                ['state_id' => 22, 'city' => 'Chicopee'],
                ['state_id' => 22, 'city' => 'East Longmeadow'],
                ['state_id' => 22, 'city' => 'Feeding Hills'],
                ['state_id' => 22, 'city' => 'Granville'],
                ['state_id' => 22, 'city' => 'Hampden'],
                ['state_id' => 22, 'city' => 'Holyoke'],
                ['state_id' => 22, 'city' => 'Ludlow'],
                ['state_id' => 22, 'city' => 'Monson'],
                ['state_id' => 22, 'city' => 'Palmer'],
                ['state_id' => 22, 'city' => 'Russell'],
                ['state_id' => 22, 'city' => 'Southwick'],
                ['state_id' => 22, 'city' => 'Thorndike'],
                ['state_id' => 22, 'city' => 'Three Rivers'],
                ['state_id' => 22, 'city' => 'Wales'],
                ['state_id' => 22, 'city' => 'Westfield'],
                ['state_id' => 22, 'city' => 'West Springfield'],
                ['state_id' => 22, 'city' => 'Wilbraham'],
                ['state_id' => 22, 'city' => 'Woronoco'],
                ['state_id' => 22, 'city' => 'Springfield'],
                ['state_id' => 22, 'city' => 'Longmeadow'],
                ['state_id' => 22, 'city' => 'Indian Orchard'],
                ['state_id' => 22, 'city' => 'Holland'],
                ['state_id' => 22, 'city' => 'Amherst'],
                ['state_id' => 22, 'city' => 'Belchertown'],
                ['state_id' => 22, 'city' => 'Chesterfield'],
                ['state_id' => 22, 'city' => 'Cummington'],
                ['state_id' => 22, 'city' => 'Easthampton'],
                ['state_id' => 22, 'city' => 'Goshen'],
                ['state_id' => 22, 'city' => 'Granby'],
                ['state_id' => 22, 'city' => 'Hadley'],
                ['state_id' => 22, 'city' => 'Hatfield'],
                ['state_id' => 22, 'city' => 'Haydenville'],
                ['state_id' => 22, 'city' => 'Huntington'],
                ['state_id' => 22, 'city' => 'Leeds'],
                ['state_id' => 22, 'city' => 'North Amherst'],
                ['state_id' => 22, 'city' => 'Northampton'],
                ['state_id' => 22, 'city' => 'Florence'],
                ['state_id' => 22, 'city' => 'North Hatfield'],
                ['state_id' => 22, 'city' => 'Plainfield'],
                ['state_id' => 22, 'city' => 'Southampton'],
                ['state_id' => 22, 'city' => 'South Hadley'],
                ['state_id' => 22, 'city' => 'Ware'],
                ['state_id' => 22, 'city' => 'West Chesterfield'],
                ['state_id' => 22, 'city' => 'West Hatfield'],
                ['state_id' => 22, 'city' => 'Williamsburg'],
                ['state_id' => 22, 'city' => 'Worthington'],
                ['state_id' => 22, 'city' => 'Middlefield'],
                ['state_id' => 22, 'city' => 'Ashby'],
                ['state_id' => 22, 'city' => 'Ayer'],
                ['state_id' => 22, 'city' => 'Groton'],
                ['state_id' => 22, 'city' => 'Littleton'],
                ['state_id' => 22, 'city' => 'Pepperell'],
                ['state_id' => 22, 'city' => 'Shirley'],
                ['state_id' => 22, 'city' => 'Townsend'],
                ['state_id' => 22, 'city' => 'West Groton'],
                ['state_id' => 22, 'city' => 'West Townsend'],
                ['state_id' => 22, 'city' => 'Framingham'],
                ['state_id' => 22, 'city' => 'Acton'],
                ['state_id' => 22, 'city' => 'Boxborough'],
                ['state_id' => 22, 'city' => 'Ashland'],
                ['state_id' => 22, 'city' => 'Bedford'],
                ['state_id' => 22, 'city' => 'Hanscom Afb'],
                ['state_id' => 22, 'city' => 'Carlisle'],
                ['state_id' => 22, 'city' => 'Concord'],
                ['state_id' => 22, 'city' => 'Holliston'],
                ['state_id' => 22, 'city' => 'Hopkinton'],
                ['state_id' => 22, 'city' => 'Hudson'],
                ['state_id' => 22, 'city' => 'Marlborough'],
                ['state_id' => 22, 'city' => 'Maynard'],
                ['state_id' => 22, 'city' => 'Natick'],
                ['state_id' => 22, 'city' => 'Sherborn'],
                ['state_id' => 22, 'city' => 'Lincoln'],
                ['state_id' => 22, 'city' => 'Stow'],
                ['state_id' => 22, 'city' => 'Sudbury'],
                ['state_id' => 22, 'city' => 'Wayland'],
                ['state_id' => 22, 'city' => 'Woodville'],
                ['state_id' => 22, 'city' => 'Woburn'],
                ['state_id' => 22, 'city' => 'Burlington'],
                ['state_id' => 22, 'city' => 'Billerica'],
                ['state_id' => 22, 'city' => 'Chelmsford'],
                ['state_id' => 22, 'city' => 'Dracut'],
                ['state_id' => 22, 'city' => 'Dunstable'],
                ['state_id' => 22, 'city' => 'Lowell'],
                ['state_id' => 22, 'city' => 'North Billerica'],
                ['state_id' => 22, 'city' => 'North Chelmsford'],
                ['state_id' => 22, 'city' => 'North Reading'],
                ['state_id' => 22, 'city' => 'Nutting Lake'],
                ['state_id' => 22, 'city' => 'Pinehurst'],
                ['state_id' => 22, 'city' => 'Reading'],
                ['state_id' => 22, 'city' => 'Tewksbury'],
                ['state_id' => 22, 'city' => 'Tyngsboro'],
                ['state_id' => 22, 'city' => 'Wakefield'],
                ['state_id' => 22, 'city' => 'Westford'],
                ['state_id' => 22, 'city' => 'Wilmington'],
                ['state_id' => 22, 'city' => 'Winchester'],
                ['state_id' => 22, 'city' => 'Cambridge'],
                ['state_id' => 22, 'city' => 'Somerville'],
                ['state_id' => 22, 'city' => 'Malden'],
                ['state_id' => 22, 'city' => 'Everett'],
                ['state_id' => 22, 'city' => 'Medford'],
                ['state_id' => 22, 'city' => 'West Medford'],
                ['state_id' => 22, 'city' => 'Melrose'],
                ['state_id' => 22, 'city' => 'Stoneham'],
                ['state_id' => 22, 'city' => 'Boston'],
                ['state_id' => 22, 'city' => 'Lexington'],
                ['state_id' => 22, 'city' => 'Waltham'],
                ['state_id' => 22, 'city' => 'North Waltham'],
                ['state_id' => 22, 'city' => 'New Town'],
                ['state_id' => 22, 'city' => 'Newton'],
                ['state_id' => 22, 'city' => 'Newton Center'],
                ['state_id' => 22, 'city' => 'Newtonville'],
                ['state_id' => 22, 'city' => 'Newton Highlands'],
                ['state_id' => 22, 'city' => 'Newton Lower Falls'],
                ['state_id' => 22, 'city' => 'Newton Upper Falls'],
                ['state_id' => 22, 'city' => 'West Newton'],
                ['state_id' => 22, 'city' => 'Auburndale'],
                ['state_id' => 22, 'city' => 'Chestnut Hill'],
                ['state_id' => 22, 'city' => 'Waban'],
                ['state_id' => 22, 'city' => 'Watertown'],
                ['state_id' => 22, 'city' => 'Arlington'],
                ['state_id' => 22, 'city' => 'Arlington Heights'],
                ['state_id' => 22, 'city' => 'Belmont'],
                ['state_id' => 22, 'city' => 'Waverley'],
                ['state_id' => 22, 'city' => 'Weston'],
                ['state_id' => 22, 'city' => 'Nonantum'],
                ['state_id' => 22, 'city' => 'Nantucket'],
                ['state_id' => 22, 'city' => 'Siasconset'],
                ['state_id' => 22, 'city' => 'Bellingham'],
                ['state_id' => 22, 'city' => 'Canton'],
                ['state_id' => 22, 'city' => 'Cohasset'],
                ['state_id' => 22, 'city' => 'Dedham'],
                ['state_id' => 22, 'city' => 'Dover'],
                ['state_id' => 22, 'city' => 'East Walpole'],
                ['state_id' => 22, 'city' => 'Foxboro'],
                ['state_id' => 22, 'city' => 'Franklin'],
                ['state_id' => 22, 'city' => 'Medfield'],
                ['state_id' => 22, 'city' => 'Medway'],
                ['state_id' => 22, 'city' => 'Millis'],
                ['state_id' => 22, 'city' => 'Norfolk'],
                ['state_id' => 22, 'city' => 'Norwood'],
                ['state_id' => 22, 'city' => 'Sharon'],
                ['state_id' => 22, 'city' => 'Sheldonville'],
                ['state_id' => 22, 'city' => 'South Walpole'],
                ['state_id' => 22, 'city' => 'Stoughton'],
                ['state_id' => 22, 'city' => 'Walpole'],
                ['state_id' => 22, 'city' => 'Westwood'],
                ['state_id' => 22, 'city' => 'Wrentham'],
                ['state_id' => 22, 'city' => 'Quincy'],
                ['state_id' => 22, 'city' => 'Braintree'],
                ['state_id' => 22, 'city' => 'Milton'],
                ['state_id' => 22, 'city' => 'Milton Village'],
                ['state_id' => 22, 'city' => 'Weymouth'],
                ['state_id' => 22, 'city' => 'East Weymouth'],
                ['state_id' => 22, 'city' => 'South Weymouth'],
                ['state_id' => 22, 'city' => 'North Weymouth'],
                ['state_id' => 22, 'city' => 'Avon'],
                ['state_id' => 22, 'city' => 'Holbrook'],
                ['state_id' => 22, 'city' => 'Randolph'],
                ['state_id' => 22, 'city' => 'Brookline'],
                ['state_id' => 22, 'city' => 'Brookline Village'],
                ['state_id' => 22, 'city' => 'Babson Park'],
                ['state_id' => 22, 'city' => 'Wellesley Hills'],
                ['state_id' => 22, 'city' => 'Wellesley'],
                ['state_id' => 22, 'city' => 'Needham'],
                ['state_id' => 22, 'city' => 'Needham Heights'],
                ['state_id' => 22, 'city' => 'Plainville'],
                ['state_id' => 22, 'city' => 'Accord'],
                ['state_id' => 22, 'city' => 'Brant Rock'],
                ['state_id' => 22, 'city' => 'Greenbush'],
                ['state_id' => 22, 'city' => 'Green Harbor'],
                ['state_id' => 22, 'city' => 'Hingham'],
                ['state_id' => 22, 'city' => 'Hull'],
                ['state_id' => 22, 'city' => 'Humarock'],
                ['state_id' => 22, 'city' => 'Marshfield'],
                ['state_id' => 22, 'city' => 'Marshfield Hills'],
                ['state_id' => 22, 'city' => 'Minot'],
                ['state_id' => 22, 'city' => 'North Marshfield'],
                ['state_id' => 22, 'city' => 'North Scituate'],
                ['state_id' => 22, 'city' => 'Norwell'],
                ['state_id' => 22, 'city' => 'Ocean Bluff'],
                ['state_id' => 22, 'city' => 'Scituate'],
                ['state_id' => 22, 'city' => 'Brockton'],
                ['state_id' => 22, 'city' => 'Bridgewater'],
                ['state_id' => 22, 'city' => 'Bryantville'],
                ['state_id' => 22, 'city' => 'Carver'],
                ['state_id' => 22, 'city' => 'Duxbury'],
                ['state_id' => 22, 'city' => 'East Bridgewater'],
                ['state_id' => 22, 'city' => 'Elmwood'],
                ['state_id' => 22, 'city' => 'Halifax'],
                ['state_id' => 22, 'city' => 'Hanover'],
                ['state_id' => 22, 'city' => 'Hanson'],
                ['state_id' => 22, 'city' => 'Middleboro'],
                ['state_id' => 22, 'city' => 'Manomet'],
                ['state_id' => 22, 'city' => 'Lakeville'],
                ['state_id' => 22, 'city' => 'Monponsett'],
                ['state_id' => 22, 'city' => 'Abington'],
                ['state_id' => 22, 'city' => 'North Carver'],
                ['state_id' => 22, 'city' => 'North Pembroke'],
                ['state_id' => 22, 'city' => 'Pembroke'],
                ['state_id' => 22, 'city' => 'Plymouth'],
                ['state_id' => 22, 'city' => 'Kingston'],
                ['state_id' => 22, 'city' => 'South Carver'],
                ['state_id' => 22, 'city' => 'Plympton'],
                ['state_id' => 22, 'city' => 'Rockland'],
                ['state_id' => 22, 'city' => 'West Bridgewater'],
                ['state_id' => 22, 'city' => 'White Horse Beach'],
                ['state_id' => 22, 'city' => 'Whitman'],
                ['state_id' => 22, 'city' => 'East Wareham'],
                ['state_id' => 22, 'city' => 'Onset'],
                ['state_id' => 22, 'city' => 'Wareham'],
                ['state_id' => 22, 'city' => 'West Wareham'],
                ['state_id' => 22, 'city' => 'Marion'],
                ['state_id' => 22, 'city' => 'Mattapoisett'],
                ['state_id' => 22, 'city' => 'Rochester'],
                ['state_id' => 22, 'city' => 'Roxbury'],
                ['state_id' => 22, 'city' => 'Roxbury Crossing'],
                ['state_id' => 22, 'city' => 'Dorchester'],
                ['state_id' => 22, 'city' => 'Dorchester Center'],
                ['state_id' => 22, 'city' => 'Mattapan'],
                ['state_id' => 22, 'city' => 'Charlestown'],
                ['state_id' => 22, 'city' => 'Jamaica Plain'],
                ['state_id' => 22, 'city' => 'Roslindale'],
                ['state_id' => 22, 'city' => 'West Roxbury'],
                ['state_id' => 22, 'city' => 'Allston'],
                ['state_id' => 22, 'city' => 'Brighton'],
                ['state_id' => 22, 'city' => 'Hyde Park'],
                ['state_id' => 22, 'city' => 'Readville'],
                ['state_id' => 22, 'city' => 'Chelsea'],
                ['state_id' => 22, 'city' => 'Revere'],
                ['state_id' => 22, 'city' => 'Winthrop'],
                ['state_id' => 22, 'city' => 'Barre'],
                ['state_id' => 22, 'city' => 'Gilbertville'],
                ['state_id' => 22, 'city' => 'Hardwick'],
                ['state_id' => 22, 'city' => 'Oakham'],
                ['state_id' => 22, 'city' => 'South Barre'],
                ['state_id' => 22, 'city' => 'Warren'],
                ['state_id' => 22, 'city' => 'West Warren'],
                ['state_id' => 22, 'city' => 'Wheelwright'],
                ['state_id' => 22, 'city' => 'Athol'],
                ['state_id' => 22, 'city' => 'Petersham'],
                ['state_id' => 22, 'city' => 'Royalston'],
                ['state_id' => 22, 'city' => 'Fitchburg'],
                ['state_id' => 22, 'city' => 'Ashburnham'],
                ['state_id' => 22, 'city' => 'Devens'],
                ['state_id' => 22, 'city' => 'Baldwinville'],
                ['state_id' => 22, 'city' => 'East Templeton'],
                ['state_id' => 22, 'city' => 'Gardner'],
                ['state_id' => 22, 'city' => 'Westminster'],
                ['state_id' => 22, 'city' => 'Harvard'],
                ['state_id' => 22, 'city' => 'Hubbardston'],
                ['state_id' => 22, 'city' => 'Leominster'],
                ['state_id' => 22, 'city' => 'Lunenburg'],
                ['state_id' => 22, 'city' => 'Still River'],
                ['state_id' => 22, 'city' => 'Templeton'],
                ['state_id' => 22, 'city' => 'Winchendon'],
                ['state_id' => 22, 'city' => 'Auburn'],
                ['state_id' => 22, 'city' => 'Berlin'],
                ['state_id' => 22, 'city' => 'Blackstone'],
                ['state_id' => 22, 'city' => 'Boylston'],
                ['state_id' => 22, 'city' => 'Brookfield'],
                ['state_id' => 22, 'city' => 'Charlton'],
                ['state_id' => 22, 'city' => 'Charlton City'],
                ['state_id' => 22, 'city' => 'Charlton Depot'],
                ['state_id' => 22, 'city' => 'Clinton'],
                ['state_id' => 22, 'city' => 'East Brookfield'],
                ['state_id' => 22, 'city' => 'Douglas'],
                ['state_id' => 22, 'city' => 'Fiskdale'],
                ['state_id' => 22, 'city' => 'Grafton'],
                ['state_id' => 22, 'city' => 'Holden'],
                ['state_id' => 22, 'city' => 'Jefferson'],
                ['state_id' => 22, 'city' => 'Lancaster'],
                ['state_id' => 22, 'city' => 'Leicester'],
                ['state_id' => 22, 'city' => 'Linwood'],
                ['state_id' => 22, 'city' => 'Manchaug'],
                ['state_id' => 22, 'city' => 'Millbury'],
                ['state_id' => 22, 'city' => 'Millville'],
                ['state_id' => 22, 'city' => 'New Braintree'],
                ['state_id' => 22, 'city' => 'Northborough'],
                ['state_id' => 22, 'city' => 'Northbridge'],
                ['state_id' => 22, 'city' => 'North Brookfield'],
                ['state_id' => 22, 'city' => 'North Grafton'],
                ['state_id' => 22, 'city' => 'North Oxford'],
                ['state_id' => 22, 'city' => 'North Uxbridge'],
                ['state_id' => 22, 'city' => 'Oxford'],
                ['state_id' => 22, 'city' => 'Princeton'],
                ['state_id' => 22, 'city' => 'Rochdale'],
                ['state_id' => 22, 'city' => 'Rutland'],
                ['state_id' => 22, 'city' => 'Shrewsbury'],
                ['state_id' => 22, 'city' => 'Southbridge'],
                ['state_id' => 22, 'city' => 'South Grafton'],
                ['state_id' => 22, 'city' => 'South Lancaster'],
                ['state_id' => 22, 'city' => 'Spencer'],
                ['state_id' => 22, 'city' => 'Sterling'],
                ['state_id' => 22, 'city' => 'Sturbridge'],
                ['state_id' => 22, 'city' => 'Upton'],
                ['state_id' => 22, 'city' => 'Uxbridge'],
                ['state_id' => 22, 'city' => 'Webster'],
                ['state_id' => 22, 'city' => 'Dudley'],
                ['state_id' => 22, 'city' => 'Westborough'],
                ['state_id' => 22, 'city' => 'West Boylston'],
                ['state_id' => 22, 'city' => 'West Brookfield'],
                ['state_id' => 22, 'city' => 'West Millbury'],
                ['state_id' => 22, 'city' => 'Whitinsville'],
                ['state_id' => 22, 'city' => 'Sutton'],
                ['state_id' => 22, 'city' => 'Worcester'],
                ['state_id' => 22, 'city' => 'Cherry Valley'],
                ['state_id' => 22, 'city' => 'Paxton'],
                ['state_id' => 22, 'city' => 'Bolton'],
                ['state_id' => 22, 'city' => 'Fayville'],
                ['state_id' => 22, 'city' => 'Hopedale'],
                ['state_id' => 22, 'city' => 'Mendon'],
                ['state_id' => 22, 'city' => 'Milford'],
                ['state_id' => 22, 'city' => 'Southborough']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
