<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State32TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NM - New Mexico.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 32, 'city' => 'Cedar Crest'],
                ['state_id' => 32, 'city' => 'Isleta'],
                ['state_id' => 32, 'city' => 'Sandia Park'],
                ['state_id' => 32, 'city' => 'Tijeras'],
                ['state_id' => 32, 'city' => 'Albuquerque'],
                ['state_id' => 32, 'city' => 'Kirtland Afb'],
                ['state_id' => 32, 'city' => 'Rio Rancho'],
                ['state_id' => 32, 'city' => 'Aragon'],
                ['state_id' => 32, 'city' => 'Datil'],
                ['state_id' => 32, 'city' => 'Luna'],
                ['state_id' => 32, 'city' => 'Pie Town'],
                ['state_id' => 32, 'city' => 'Quemado'],
                ['state_id' => 32, 'city' => 'Reserve'],
                ['state_id' => 32, 'city' => 'Glenwood'],
                ['state_id' => 32, 'city' => 'Roswell'],
                ['state_id' => 32, 'city' => 'Dexter'],
                ['state_id' => 32, 'city' => 'Hagerman'],
                ['state_id' => 32, 'city' => 'Lake Arthur'],
                ['state_id' => 32, 'city' => 'Bluewater'],
                ['state_id' => 32, 'city' => 'Casa Blanca'],
                ['state_id' => 32, 'city' => 'Cubero'],
                ['state_id' => 32, 'city' => 'Grants'],
                ['state_id' => 32, 'city' => 'Milan'],
                ['state_id' => 32, 'city' => 'Laguna'],
                ['state_id' => 32, 'city' => 'New Laguna'],
                ['state_id' => 32, 'city' => 'Paguate'],
                ['state_id' => 32, 'city' => 'San Fidel'],
                ['state_id' => 32, 'city' => 'San Rafael'],
                ['state_id' => 32, 'city' => 'Fence Lake'],
                ['state_id' => 32, 'city' => 'Pinehill'],
                ['state_id' => 32, 'city' => 'Angel Fire'],
                ['state_id' => 32, 'city' => 'Cimarron'],
                ['state_id' => 32, 'city' => 'Eagle Nest'],
                ['state_id' => 32, 'city' => 'Maxwell'],
                ['state_id' => 32, 'city' => 'Miami'],
                ['state_id' => 32, 'city' => 'Raton'],
                ['state_id' => 32, 'city' => 'Springer'],
                ['state_id' => 32, 'city' => 'Ute Park'],
                ['state_id' => 32, 'city' => 'Clovis'],
                ['state_id' => 32, 'city' => 'Cannon Afb'],
                ['state_id' => 32, 'city' => 'Broadview'],
                ['state_id' => 32, 'city' => 'Grady'],
                ['state_id' => 32, 'city' => 'Melrose'],
                ['state_id' => 32, 'city' => 'Saint Vrain'],
                ['state_id' => 32, 'city' => 'Texico'],
                ['state_id' => 32, 'city' => 'Fort Sumner'],
                ['state_id' => 32, 'city' => 'Taiban'],
                ['state_id' => 32, 'city' => 'Yeso'],
                ['state_id' => 32, 'city' => 'Garfield'],
                ['state_id' => 32, 'city' => 'Hatch'],
                ['state_id' => 32, 'city' => 'Rincon'],
                ['state_id' => 32, 'city' => 'Salem'],
                ['state_id' => 32, 'city' => 'Las Cruces'],
                ['state_id' => 32, 'city' => 'White Sands Missile Range'],
                ['state_id' => 32, 'city' => 'Santa Teresa'],
                ['state_id' => 32, 'city' => 'Anthony'],
                ['state_id' => 32, 'city' => 'Berino'],
                ['state_id' => 32, 'city' => 'Chamberino'],
                ['state_id' => 32, 'city' => 'Dona Ana'],
                ['state_id' => 32, 'city' => 'Fairacres'],
                ['state_id' => 32, 'city' => 'La Mesa'],
                ['state_id' => 32, 'city' => 'Mesilla'],
                ['state_id' => 32, 'city' => 'Mesilla Park'],
                ['state_id' => 32, 'city' => 'Mesquite'],
                ['state_id' => 32, 'city' => 'Organ'],
                ['state_id' => 32, 'city' => 'Radium Springs'],
                ['state_id' => 32, 'city' => 'San Miguel'],
                ['state_id' => 32, 'city' => 'Sunland Park'],
                ['state_id' => 32, 'city' => 'Vado'],
                ['state_id' => 32, 'city' => 'Artesia'],
                ['state_id' => 32, 'city' => 'Carlsbad'],
                ['state_id' => 32, 'city' => 'Hope'],
                ['state_id' => 32, 'city' => 'Lakewood'],
                ['state_id' => 32, 'city' => 'Loco Hills'],
                ['state_id' => 32, 'city' => 'Loving'],
                ['state_id' => 32, 'city' => 'Malaga'],
                ['state_id' => 32, 'city' => 'Whites City'],
                ['state_id' => 32, 'city' => 'Arenas Valley'],
                ['state_id' => 32, 'city' => 'Bayard'],
                ['state_id' => 32, 'city' => 'Buckhorn'],
                ['state_id' => 32, 'city' => 'Santa Clara'],
                ['state_id' => 32, 'city' => 'Cliff'],
                ['state_id' => 32, 'city' => 'Faywood'],
                ['state_id' => 32, 'city' => 'Fort Bayard'],
                ['state_id' => 32, 'city' => 'Gila'],
                ['state_id' => 32, 'city' => 'Hachita'],
                ['state_id' => 32, 'city' => 'Hanover'],
                ['state_id' => 32, 'city' => 'Hurley'],
                ['state_id' => 32, 'city' => 'Mimbres'],
                ['state_id' => 32, 'city' => 'Mule Creek'],
                ['state_id' => 32, 'city' => 'Pinos Altos'],
                ['state_id' => 32, 'city' => 'Redrock'],
                ['state_id' => 32, 'city' => 'Silver City'],
                ['state_id' => 32, 'city' => 'Tyrone'],
                ['state_id' => 32, 'city' => 'Anton Chico'],
                ['state_id' => 32, 'city' => 'La Loma'],
                ['state_id' => 32, 'city' => 'Vaughn'],
                ['state_id' => 32, 'city' => 'Cuervo'],
                ['state_id' => 32, 'city' => 'Newkirk'],
                ['state_id' => 32, 'city' => 'Santa Rosa'],
                ['state_id' => 32, 'city' => 'Mills'],
                ['state_id' => 32, 'city' => 'Mosquero'],
                ['state_id' => 32, 'city' => 'Roy'],
                ['state_id' => 32, 'city' => 'Solano'],
                ['state_id' => 32, 'city' => 'Playas'],
                ['state_id' => 32, 'city' => 'Animas'],
                ['state_id' => 32, 'city' => 'Lordsburg'],
                ['state_id' => 32, 'city' => 'Rodeo'],
                ['state_id' => 32, 'city' => 'Crossroads'],
                ['state_id' => 32, 'city' => 'Caprock'],
                ['state_id' => 32, 'city' => 'Eunice'],
                ['state_id' => 32, 'city' => 'Hobbs'],
                ['state_id' => 32, 'city' => 'Jal'],
                ['state_id' => 32, 'city' => 'Lovington'],
                ['state_id' => 32, 'city' => 'Mcdonald'],
                ['state_id' => 32, 'city' => 'Maljamar'],
                ['state_id' => 32, 'city' => 'Monument'],
                ['state_id' => 32, 'city' => 'Tatum'],
                ['state_id' => 32, 'city' => 'Carrizozo'],
                ['state_id' => 32, 'city' => 'Alto'],
                ['state_id' => 32, 'city' => 'Capitan'],
                ['state_id' => 32, 'city' => 'Corona'],
                ['state_id' => 32, 'city' => 'Fort Stanton'],
                ['state_id' => 32, 'city' => 'Glencoe'],
                ['state_id' => 32, 'city' => 'Hondo'],
                ['state_id' => 32, 'city' => 'Lincoln'],
                ['state_id' => 32, 'city' => 'Nogal'],
                ['state_id' => 32, 'city' => 'Picacho'],
                ['state_id' => 32, 'city' => 'Ruidoso'],
                ['state_id' => 32, 'city' => 'Ruidoso Downs'],
                ['state_id' => 32, 'city' => 'San Patricio'],
                ['state_id' => 32, 'city' => 'Tinnie'],
                ['state_id' => 32, 'city' => 'Los Alamos'],
                ['state_id' => 32, 'city' => 'White Rock'],
                ['state_id' => 32, 'city' => 'Columbus'],
                ['state_id' => 32, 'city' => 'Deming'],
                ['state_id' => 32, 'city' => 'Prewitt'],
                ['state_id' => 32, 'city' => 'Gallup'],
                ['state_id' => 32, 'city' => 'Brimhall'],
                ['state_id' => 32, 'city' => 'Church Rock'],
                ['state_id' => 32, 'city' => 'Continental Divide'],
                ['state_id' => 32, 'city' => 'Crownpoint'],
                ['state_id' => 32, 'city' => 'Fort Wingate'],
                ['state_id' => 32, 'city' => 'Gamerco'],
                ['state_id' => 32, 'city' => 'Mentmore'],
                ['state_id' => 32, 'city' => 'Mexican Springs'],
                ['state_id' => 32, 'city' => 'Ramah'],
                ['state_id' => 32, 'city' => 'Rehoboth'],
                ['state_id' => 32, 'city' => 'Thoreau'],
                ['state_id' => 32, 'city' => 'Tohatchi'],
                ['state_id' => 32, 'city' => 'Vanderwagen'],
                ['state_id' => 32, 'city' => 'Zuni'],
                ['state_id' => 32, 'city' => 'Navajo'],
                ['state_id' => 32, 'city' => 'Jamestown'],
                ['state_id' => 32, 'city' => 'Smith Lake'],
                ['state_id' => 32, 'city' => 'Yatahey'],
                ['state_id' => 32, 'city' => 'Buena Vista'],
                ['state_id' => 32, 'city' => 'Chacon'],
                ['state_id' => 32, 'city' => 'Cleveland'],
                ['state_id' => 32, 'city' => 'Guadalupita'],
                ['state_id' => 32, 'city' => 'Holman'],
                ['state_id' => 32, 'city' => 'Mora'],
                ['state_id' => 32, 'city' => 'Ocate'],
                ['state_id' => 32, 'city' => 'Ojo Feliz'],
                ['state_id' => 32, 'city' => 'Rainsville'],
                ['state_id' => 32, 'city' => 'Valmora'],
                ['state_id' => 32, 'city' => 'Wagon Mound'],
                ['state_id' => 32, 'city' => 'Watrous'],
                ['state_id' => 32, 'city' => 'Chaparral'],
                ['state_id' => 32, 'city' => 'Alamogordo'],
                ['state_id' => 32, 'city' => 'Bent'],
                ['state_id' => 32, 'city' => 'Cloudcroft'],
                ['state_id' => 32, 'city' => 'High Rolls Mountain Park'],
                ['state_id' => 32, 'city' => 'Holloman Air Force Base'],
                ['state_id' => 32, 'city' => 'La Luz'],
                ['state_id' => 32, 'city' => 'Mayhill'],
                ['state_id' => 32, 'city' => 'Mescalero'],
                ['state_id' => 32, 'city' => 'Orogrande'],
                ['state_id' => 32, 'city' => 'Pinon'],
                ['state_id' => 32, 'city' => 'Sacramento'],
                ['state_id' => 32, 'city' => 'Sunspot'],
                ['state_id' => 32, 'city' => 'Timberon'],
                ['state_id' => 32, 'city' => 'Tularosa'],
                ['state_id' => 32, 'city' => 'Weed'],
                ['state_id' => 32, 'city' => 'House'],
                ['state_id' => 32, 'city' => 'Tucumcari'],
                ['state_id' => 32, 'city' => 'Bard'],
                ['state_id' => 32, 'city' => 'Logan'],
                ['state_id' => 32, 'city' => 'Mcalister'],
                ['state_id' => 32, 'city' => 'Nara Visa'],
                ['state_id' => 32, 'city' => 'Quay'],
                ['state_id' => 32, 'city' => 'San Jon'],
                ['state_id' => 32, 'city' => 'Coyote'],
                ['state_id' => 32, 'city' => 'Gallina'],
                ['state_id' => 32, 'city' => 'Lindrith'],
                ['state_id' => 32, 'city' => 'Youngsville'],
                ['state_id' => 32, 'city' => 'Abiquiu'],
                ['state_id' => 32, 'city' => 'Alcalde'],
                ['state_id' => 32, 'city' => 'Canjilon'],
                ['state_id' => 32, 'city' => 'Canones'],
                ['state_id' => 32, 'city' => 'Cebolla'],
                ['state_id' => 32, 'city' => 'Chama'],
                ['state_id' => 32, 'city' => 'Chimayo'],
                ['state_id' => 32, 'city' => 'Cordova'],
                ['state_id' => 32, 'city' => 'Dixon'],
                ['state_id' => 32, 'city' => 'Dulce'],
                ['state_id' => 32, 'city' => 'El Rito'],
                ['state_id' => 32, 'city' => 'Embudo'],
                ['state_id' => 32, 'city' => 'Espanola'],
                ['state_id' => 32, 'city' => 'Hernandez'],
                ['state_id' => 32, 'city' => 'La Madera'],
                ['state_id' => 32, 'city' => 'Medanales'],
                ['state_id' => 32, 'city' => 'Los Ojos'],
                ['state_id' => 32, 'city' => 'Petaca'],
                ['state_id' => 32, 'city' => 'Ohkay Owingeh'],
                ['state_id' => 32, 'city' => 'Tierra Amarilla'],
                ['state_id' => 32, 'city' => 'Truchas'],
                ['state_id' => 32, 'city' => 'Vallecitos'],
                ['state_id' => 32, 'city' => 'Velarde'],
                ['state_id' => 32, 'city' => 'Causey'],
                ['state_id' => 32, 'city' => 'Dora'],
                ['state_id' => 32, 'city' => 'Elida'],
                ['state_id' => 32, 'city' => 'Floyd'],
                ['state_id' => 32, 'city' => 'Kenna'],
                ['state_id' => 32, 'city' => 'Lingo'],
                ['state_id' => 32, 'city' => 'Milnesand'],
                ['state_id' => 32, 'city' => 'Pep'],
                ['state_id' => 32, 'city' => 'Portales'],
                ['state_id' => 32, 'city' => 'Rogers'],
                ['state_id' => 32, 'city' => 'Algodones'],
                ['state_id' => 32, 'city' => 'Bernalillo'],
                ['state_id' => 32, 'city' => 'Cuba'],
                ['state_id' => 32, 'city' => 'Counselor'],
                ['state_id' => 32, 'city' => 'Jemez Pueblo'],
                ['state_id' => 32, 'city' => 'Jemez Springs'],
                ['state_id' => 32, 'city' => 'La Jara'],
                ['state_id' => 32, 'city' => 'Pena Blanca'],
                ['state_id' => 32, 'city' => 'Placitas'],
                ['state_id' => 32, 'city' => 'Ponderosa'],
                ['state_id' => 32, 'city' => 'Regina'],
                ['state_id' => 32, 'city' => 'Corrales'],
                ['state_id' => 32, 'city' => 'Santo Domingo Pueblo'],
                ['state_id' => 32, 'city' => 'San Ysidro'],
                ['state_id' => 32, 'city' => 'Cochiti Pueblo'],
                ['state_id' => 32, 'city' => 'Cochiti Lake'],
                ['state_id' => 32, 'city' => 'Nageezi'],
                ['state_id' => 32, 'city' => 'Sheep Springs'],
                ['state_id' => 32, 'city' => 'Farmington'],
                ['state_id' => 32, 'city' => 'Aztec'],
                ['state_id' => 32, 'city' => 'Blanco'],
                ['state_id' => 32, 'city' => 'Bloomfield'],
                ['state_id' => 32, 'city' => 'Flora Vista'],
                ['state_id' => 32, 'city' => 'Fruitland'],
                ['state_id' => 32, 'city' => 'Kirtland'],
                ['state_id' => 32, 'city' => 'La Plata'],
                ['state_id' => 32, 'city' => 'Navajo Dam'],
                ['state_id' => 32, 'city' => 'Shiprock'],
                ['state_id' => 32, 'city' => 'Waterflow'],
                ['state_id' => 32, 'city' => 'Newcomb'],
                ['state_id' => 32, 'city' => 'Sanostee'],
                ['state_id' => 32, 'city' => 'Ilfeld'],
                ['state_id' => 32, 'city' => 'Pecos'],
                ['state_id' => 32, 'city' => 'Ribera'],
                ['state_id' => 32, 'city' => 'Rowe'],
                ['state_id' => 32, 'city' => 'San Jose'],
                ['state_id' => 32, 'city' => 'Serafina'],
                ['state_id' => 32, 'city' => 'Tererro'],
                ['state_id' => 32, 'city' => 'Villanueva'],
                ['state_id' => 32, 'city' => 'Las Vegas'],
                ['state_id' => 32, 'city' => 'Montezuma'],
                ['state_id' => 32, 'city' => 'Rociada'],
                ['state_id' => 32, 'city' => 'Sapello'],
                ['state_id' => 32, 'city' => 'Conchas Dam'],
                ['state_id' => 32, 'city' => 'Garita'],
                ['state_id' => 32, 'city' => 'Trementina'],
                ['state_id' => 32, 'city' => 'Cerrillos'],
                ['state_id' => 32, 'city' => 'Edgewood'],
                ['state_id' => 32, 'city' => 'Stanley'],
                ['state_id' => 32, 'city' => 'Santa Fe'],
                ['state_id' => 32, 'city' => 'Glorieta'],
                ['state_id' => 32, 'city' => 'Lamy'],
                ['state_id' => 32, 'city' => 'Santa Cruz'],
                ['state_id' => 32, 'city' => 'Tesuque'],
                ['state_id' => 32, 'city' => 'Spaceport City'],
                ['state_id' => 32, 'city' => 'Truth Or Consequences'],
                ['state_id' => 32, 'city' => 'Arrey'],
                ['state_id' => 32, 'city' => 'Caballo'],
                ['state_id' => 32, 'city' => 'Derry'],
                ['state_id' => 32, 'city' => 'Elephant Butte'],
                ['state_id' => 32, 'city' => 'Monticello'],
                ['state_id' => 32, 'city' => 'Williamsburg'],
                ['state_id' => 32, 'city' => 'Winston'],
                ['state_id' => 32, 'city' => 'Hillsboro'],
                ['state_id' => 32, 'city' => 'Claunch'],
                ['state_id' => 32, 'city' => 'La Joya'],
                ['state_id' => 32, 'city' => 'Veguita'],
                ['state_id' => 32, 'city' => 'Socorro'],
                ['state_id' => 32, 'city' => 'Lemitar'],
                ['state_id' => 32, 'city' => 'Magdalena'],
                ['state_id' => 32, 'city' => 'Polvadera'],
                ['state_id' => 32, 'city' => 'San Acacia'],
                ['state_id' => 32, 'city' => 'San Antonio'],
                ['state_id' => 32, 'city' => 'Amalia'],
                ['state_id' => 32, 'city' => 'Arroyo Hondo'],
                ['state_id' => 32, 'city' => 'Arroyo Seco'],
                ['state_id' => 32, 'city' => 'Carson'],
                ['state_id' => 32, 'city' => 'Cerro'],
                ['state_id' => 32, 'city' => 'Chamisal'],
                ['state_id' => 32, 'city' => 'Costilla'],
                ['state_id' => 32, 'city' => 'Taos Ski Valley'],
                ['state_id' => 32, 'city' => 'El Prado'],
                ['state_id' => 32, 'city' => 'Llano'],
                ['state_id' => 32, 'city' => 'Ojo Caliente'],
                ['state_id' => 32, 'city' => 'Penasco'],
                ['state_id' => 32, 'city' => 'Questa'],
                ['state_id' => 32, 'city' => 'Ranchos De Taos'],
                ['state_id' => 32, 'city' => 'Red River'],
                ['state_id' => 32, 'city' => 'San Cristobal'],
                ['state_id' => 32, 'city' => 'Taos'],
                ['state_id' => 32, 'city' => 'Trampas'],
                ['state_id' => 32, 'city' => 'Tres Piedras'],
                ['state_id' => 32, 'city' => 'Vadito'],
                ['state_id' => 32, 'city' => 'Valdez'],
                ['state_id' => 32, 'city' => 'Cedarvale'],
                ['state_id' => 32, 'city' => 'Estancia'],
                ['state_id' => 32, 'city' => 'Mcintosh'],
                ['state_id' => 32, 'city' => 'Moriarty'],
                ['state_id' => 32, 'city' => 'Mountainair'],
                ['state_id' => 32, 'city' => 'Torreon'],
                ['state_id' => 32, 'city' => 'Willard'],
                ['state_id' => 32, 'city' => 'Clines Corners'],
                ['state_id' => 32, 'city' => 'Encino'],
                ['state_id' => 32, 'city' => 'Amistad'],
                ['state_id' => 32, 'city' => 'Capulin'],
                ['state_id' => 32, 'city' => 'Clayton'],
                ['state_id' => 32, 'city' => 'Des Moines'],
                ['state_id' => 32, 'city' => 'Folsom'],
                ['state_id' => 32, 'city' => 'Gladstone'],
                ['state_id' => 32, 'city' => 'Grenville'],
                ['state_id' => 32, 'city' => 'Sedan'],
                ['state_id' => 32, 'city' => 'Belen'],
                ['state_id' => 32, 'city' => 'Bosque'],
                ['state_id' => 32, 'city' => 'Jarales'],
                ['state_id' => 32, 'city' => 'Los Lunas'],
                ['state_id' => 32, 'city' => 'Pueblo Of Acoma'],
                ['state_id' => 32, 'city' => 'Peralta'],
                ['state_id' => 32, 'city' => 'Tome'],
                ['state_id' => 32, 'city' => 'Bosque Farms']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
