<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State38TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of OR - Oregon.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 38, 'city' => 'Baker City'],
                ['state_id' => 38, 'city' => 'Bridgeport'],
                ['state_id' => 38, 'city' => 'Haines'],
                ['state_id' => 38, 'city' => 'Halfway'],
                ['state_id' => 38, 'city' => 'Hereford'],
                ['state_id' => 38, 'city' => 'Oxbow'],
                ['state_id' => 38, 'city' => 'Richland'],
                ['state_id' => 38, 'city' => 'Sumpter'],
                ['state_id' => 38, 'city' => 'Unity'],
                ['state_id' => 38, 'city' => 'Durkee'],
                ['state_id' => 38, 'city' => 'Huntington'],
                ['state_id' => 38, 'city' => 'Alsea'],
                ['state_id' => 38, 'city' => 'Blodgett'],
                ['state_id' => 38, 'city' => 'Corvallis'],
                ['state_id' => 38, 'city' => 'Philomath'],
                ['state_id' => 38, 'city' => 'Monroe'],
                ['state_id' => 38, 'city' => 'Beavercreek'],
                ['state_id' => 38, 'city' => 'Boring'],
                ['state_id' => 38, 'city' => 'Brightwood'],
                ['state_id' => 38, 'city' => 'Canby'],
                ['state_id' => 38, 'city' => 'Clackamas'],
                ['state_id' => 38, 'city' => 'Colton'],
                ['state_id' => 38, 'city' => 'Eagle Creek'],
                ['state_id' => 38, 'city' => 'Estacada'],
                ['state_id' => 38, 'city' => 'Gladstone'],
                ['state_id' => 38, 'city' => 'Government Camp'],
                ['state_id' => 38, 'city' => 'Lake Oswego'],
                ['state_id' => 38, 'city' => 'Marylhurst'],
                ['state_id' => 38, 'city' => 'Molalla'],
                ['state_id' => 38, 'city' => 'Mulino'],
                ['state_id' => 38, 'city' => 'Oregon City'],
                ['state_id' => 38, 'city' => 'Rhododendron'],
                ['state_id' => 38, 'city' => 'Sandy'],
                ['state_id' => 38, 'city' => 'Welches'],
                ['state_id' => 38, 'city' => 'West Linn'],
                ['state_id' => 38, 'city' => 'Wilsonville'],
                ['state_id' => 38, 'city' => 'Damascus'],
                ['state_id' => 38, 'city' => 'Portland'],
                ['state_id' => 38, 'city' => 'Arch Cape'],
                ['state_id' => 38, 'city' => 'Astoria'],
                ['state_id' => 38, 'city' => 'Cannon Beach'],
                ['state_id' => 38, 'city' => 'Hammond'],
                ['state_id' => 38, 'city' => 'Seaside'],
                ['state_id' => 38, 'city' => 'Tolovana Park'],
                ['state_id' => 38, 'city' => 'Warrenton'],
                ['state_id' => 38, 'city' => 'Clatskanie'],
                ['state_id' => 38, 'city' => 'Columbia City'],
                ['state_id' => 38, 'city' => 'Rainier'],
                ['state_id' => 38, 'city' => 'Saint Helens'],
                ['state_id' => 38, 'city' => 'Warren'],
                ['state_id' => 38, 'city' => 'Deer Island'],
                ['state_id' => 38, 'city' => 'Scappoose'],
                ['state_id' => 38, 'city' => 'Vernonia'],
                ['state_id' => 38, 'city' => 'Allegany'],
                ['state_id' => 38, 'city' => 'Bandon'],
                ['state_id' => 38, 'city' => 'Broadbent'],
                ['state_id' => 38, 'city' => 'Coos Bay'],
                ['state_id' => 38, 'city' => 'Coquille'],
                ['state_id' => 38, 'city' => 'Lakeside'],
                ['state_id' => 38, 'city' => 'Myrtle Point'],
                ['state_id' => 38, 'city' => 'North Bend'],
                ['state_id' => 38, 'city' => 'Powers'],
                ['state_id' => 38, 'city' => 'Paulina'],
                ['state_id' => 38, 'city' => 'Post'],
                ['state_id' => 38, 'city' => 'Powell Butte'],
                ['state_id' => 38, 'city' => 'Prineville'],
                ['state_id' => 38, 'city' => 'Agness'],
                ['state_id' => 38, 'city' => 'Brookings'],
                ['state_id' => 38, 'city' => 'Gold Beach'],
                ['state_id' => 38, 'city' => 'Langlois'],
                ['state_id' => 38, 'city' => 'Ophir'],
                ['state_id' => 38, 'city' => 'Port Orford'],
                ['state_id' => 38, 'city' => 'Sixes'],
                ['state_id' => 38, 'city' => 'Wedderburn'],
                ['state_id' => 38, 'city' => 'Bend'],
                ['state_id' => 38, 'city' => 'Brothers'],
                ['state_id' => 38, 'city' => 'La Pine'],
                ['state_id' => 38, 'city' => 'Redmond'],
                ['state_id' => 38, 'city' => 'Sisters'],
                ['state_id' => 38, 'city' => 'Terrebonne'],
                ['state_id' => 38, 'city' => 'Azalea'],
                ['state_id' => 38, 'city' => 'Camas Valley'],
                ['state_id' => 38, 'city' => 'Canyonville'],
                ['state_id' => 38, 'city' => 'Days Creek'],
                ['state_id' => 38, 'city' => 'Dillard'],
                ['state_id' => 38, 'city' => 'Drain'],
                ['state_id' => 38, 'city' => 'Elkton'],
                ['state_id' => 38, 'city' => 'Gardiner'],
                ['state_id' => 38, 'city' => 'Glendale'],
                ['state_id' => 38, 'city' => 'Glide'],
                ['state_id' => 38, 'city' => 'Idleyld Park'],
                ['state_id' => 38, 'city' => 'Myrtle Creek'],
                ['state_id' => 38, 'city' => 'Oakland'],
                ['state_id' => 38, 'city' => 'Reedsport'],
                ['state_id' => 38, 'city' => 'Riddle'],
                ['state_id' => 38, 'city' => 'Roseburg'],
                ['state_id' => 38, 'city' => 'Scottsburg'],
                ['state_id' => 38, 'city' => 'Sutherlin'],
                ['state_id' => 38, 'city' => 'Tenmile'],
                ['state_id' => 38, 'city' => 'Tiller'],
                ['state_id' => 38, 'city' => 'Umpqua'],
                ['state_id' => 38, 'city' => 'Wilbur'],
                ['state_id' => 38, 'city' => 'Winchester'],
                ['state_id' => 38, 'city' => 'Winston'],
                ['state_id' => 38, 'city' => 'Yoncalla'],
                ['state_id' => 38, 'city' => 'Arlington'],
                ['state_id' => 38, 'city' => 'Condon'],
                ['state_id' => 38, 'city' => 'Mikkalo'],
                ['state_id' => 38, 'city' => 'Bates'],
                ['state_id' => 38, 'city' => 'Canyon City'],
                ['state_id' => 38, 'city' => 'Dayville'],
                ['state_id' => 38, 'city' => 'John Day'],
                ['state_id' => 38, 'city' => 'Kimberly'],
                ['state_id' => 38, 'city' => 'Long Creek'],
                ['state_id' => 38, 'city' => 'Monument'],
                ['state_id' => 38, 'city' => 'Mount Vernon'],
                ['state_id' => 38, 'city' => 'Prairie City'],
                ['state_id' => 38, 'city' => 'Seneca'],
                ['state_id' => 38, 'city' => 'Fields'],
                ['state_id' => 38, 'city' => 'Burns'],
                ['state_id' => 38, 'city' => 'Princeton'],
                ['state_id' => 38, 'city' => 'Diamond'],
                ['state_id' => 38, 'city' => 'Crane'],
                ['state_id' => 38, 'city' => 'Frenchglen'],
                ['state_id' => 38, 'city' => 'Hines'],
                ['state_id' => 38, 'city' => 'Riley'],
                ['state_id' => 38, 'city' => 'Drewsey'],
                ['state_id' => 38, 'city' => 'Cascade Locks'],
                ['state_id' => 38, 'city' => 'Hood River'],
                ['state_id' => 38, 'city' => 'Mount Hood Parkdale'],
                ['state_id' => 38, 'city' => 'Odell'],
                ['state_id' => 38, 'city' => 'Medford'],
                ['state_id' => 38, 'city' => 'Central Point'],
                ['state_id' => 38, 'city' => 'White City'],
                ['state_id' => 38, 'city' => 'Ashland'],
                ['state_id' => 38, 'city' => 'Butte Falls'],
                ['state_id' => 38, 'city' => 'Eagle Point'],
                ['state_id' => 38, 'city' => 'Gold Hill'],
                ['state_id' => 38, 'city' => 'Jacksonville'],
                ['state_id' => 38, 'city' => 'Phoenix'],
                ['state_id' => 38, 'city' => 'Prospect'],
                ['state_id' => 38, 'city' => 'Rogue River'],
                ['state_id' => 38, 'city' => 'Shady Cove'],
                ['state_id' => 38, 'city' => 'Talent'],
                ['state_id' => 38, 'city' => 'Trail'],
                ['state_id' => 38, 'city' => 'Ashwood'],
                ['state_id' => 38, 'city' => 'Camp Sherman'],
                ['state_id' => 38, 'city' => 'Culver'],
                ['state_id' => 38, 'city' => 'Madras'],
                ['state_id' => 38, 'city' => 'Warm Springs'],
                ['state_id' => 38, 'city' => 'Wolf Creek'],
                ['state_id' => 38, 'city' => 'Cave Junction'],
                ['state_id' => 38, 'city' => 'Grants Pass'],
                ['state_id' => 38, 'city' => 'Kerby'],
                ['state_id' => 38, 'city' => 'Merlin'],
                ['state_id' => 38, 'city' => 'Murphy'],
                ['state_id' => 38, 'city' => 'O Brien'],
                ['state_id' => 38, 'city' => 'Selma'],
                ['state_id' => 38, 'city' => 'Wilderville'],
                ['state_id' => 38, 'city' => 'Williams'],
                ['state_id' => 38, 'city' => 'Klamath Falls'],
                ['state_id' => 38, 'city' => 'Crater Lake'],
                ['state_id' => 38, 'city' => 'Beatty'],
                ['state_id' => 38, 'city' => 'Bly'],
                ['state_id' => 38, 'city' => 'Bonanza'],
                ['state_id' => 38, 'city' => 'Chiloquin'],
                ['state_id' => 38, 'city' => 'Dairy'],
                ['state_id' => 38, 'city' => 'Fort Klamath'],
                ['state_id' => 38, 'city' => 'Keno'],
                ['state_id' => 38, 'city' => 'Malin'],
                ['state_id' => 38, 'city' => 'Merrill'],
                ['state_id' => 38, 'city' => 'Midland'],
                ['state_id' => 38, 'city' => 'Sprague River'],
                ['state_id' => 38, 'city' => 'Chemult'],
                ['state_id' => 38, 'city' => 'Crescent'],
                ['state_id' => 38, 'city' => 'Gilchrist'],
                ['state_id' => 38, 'city' => 'Adel'],
                ['state_id' => 38, 'city' => 'Lakeview'],
                ['state_id' => 38, 'city' => 'New Pine Creek'],
                ['state_id' => 38, 'city' => 'Paisley'],
                ['state_id' => 38, 'city' => 'Plush'],
                ['state_id' => 38, 'city' => 'Silver Lake'],
                ['state_id' => 38, 'city' => 'Summer Lake'],
                ['state_id' => 38, 'city' => 'Christmas Valley'],
                ['state_id' => 38, 'city' => 'Fort Rock'],
                ['state_id' => 38, 'city' => 'Eugene'],
                ['state_id' => 38, 'city' => 'Alvadore'],
                ['state_id' => 38, 'city' => 'Blachly'],
                ['state_id' => 38, 'city' => 'Blue River'],
                ['state_id' => 38, 'city' => 'Cheshire'],
                ['state_id' => 38, 'city' => 'Cottage Grove'],
                ['state_id' => 38, 'city' => 'Creswell'],
                ['state_id' => 38, 'city' => 'Deadwood'],
                ['state_id' => 38, 'city' => 'Dexter'],
                ['state_id' => 38, 'city' => 'Dorena'],
                ['state_id' => 38, 'city' => 'Elmira'],
                ['state_id' => 38, 'city' => 'Fall Creek'],
                ['state_id' => 38, 'city' => 'Florence'],
                ['state_id' => 38, 'city' => 'Junction City'],
                ['state_id' => 38, 'city' => 'Lorane'],
                ['state_id' => 38, 'city' => 'Lowell'],
                ['state_id' => 38, 'city' => 'Mapleton'],
                ['state_id' => 38, 'city' => 'Marcola'],
                ['state_id' => 38, 'city' => 'Pleasant Hill'],
                ['state_id' => 38, 'city' => 'Noti'],
                ['state_id' => 38, 'city' => 'Oakridge'],
                ['state_id' => 38, 'city' => 'Springfield'],
                ['state_id' => 38, 'city' => 'Swisshome'],
                ['state_id' => 38, 'city' => 'Veneta'],
                ['state_id' => 38, 'city' => 'Vida'],
                ['state_id' => 38, 'city' => 'Walterville'],
                ['state_id' => 38, 'city' => 'Walton'],
                ['state_id' => 38, 'city' => 'Westfir'],
                ['state_id' => 38, 'city' => 'Westlake'],
                ['state_id' => 38, 'city' => 'Depoe Bay'],
                ['state_id' => 38, 'city' => 'Eddyville'],
                ['state_id' => 38, 'city' => 'Logsden'],
                ['state_id' => 38, 'city' => 'Neotsu'],
                ['state_id' => 38, 'city' => 'Newport'],
                ['state_id' => 38, 'city' => 'South Beach'],
                ['state_id' => 38, 'city' => 'Lincoln City'],
                ['state_id' => 38, 'city' => 'Otis'],
                ['state_id' => 38, 'city' => 'Otter Rock'],
                ['state_id' => 38, 'city' => 'Seal Rock'],
                ['state_id' => 38, 'city' => 'Siletz'],
                ['state_id' => 38, 'city' => 'Gleneden Beach'],
                ['state_id' => 38, 'city' => 'Tidewater'],
                ['state_id' => 38, 'city' => 'Toledo'],
                ['state_id' => 38, 'city' => 'Waldport'],
                ['state_id' => 38, 'city' => 'Yachats'],
                ['state_id' => 38, 'city' => 'Albany'],
                ['state_id' => 38, 'city' => 'Brownsville'],
                ['state_id' => 38, 'city' => 'Cascadia'],
                ['state_id' => 38, 'city' => 'Crabtree'],
                ['state_id' => 38, 'city' => 'Crawfordsville'],
                ['state_id' => 38, 'city' => 'Foster'],
                ['state_id' => 38, 'city' => 'Halsey'],
                ['state_id' => 38, 'city' => 'Lebanon'],
                ['state_id' => 38, 'city' => 'Lyons'],
                ['state_id' => 38, 'city' => 'Mill City'],
                ['state_id' => 38, 'city' => 'Scio'],
                ['state_id' => 38, 'city' => 'Shedd'],
                ['state_id' => 38, 'city' => 'Sweet Home'],
                ['state_id' => 38, 'city' => 'Tangent'],
                ['state_id' => 38, 'city' => 'Harrisburg'],
                ['state_id' => 38, 'city' => 'Adrian'],
                ['state_id' => 38, 'city' => 'Arock'],
                ['state_id' => 38, 'city' => 'Brogan'],
                ['state_id' => 38, 'city' => 'Harper'],
                ['state_id' => 38, 'city' => 'Ironside'],
                ['state_id' => 38, 'city' => 'Jamieson'],
                ['state_id' => 38, 'city' => 'Jordan Valley'],
                ['state_id' => 38, 'city' => 'Juntura'],
                ['state_id' => 38, 'city' => 'Nyssa'],
                ['state_id' => 38, 'city' => 'Ontario'],
                ['state_id' => 38, 'city' => 'Riverside'],
                ['state_id' => 38, 'city' => 'Vale'],
                ['state_id' => 38, 'city' => 'Westfall'],
                ['state_id' => 38, 'city' => 'Aurora'],
                ['state_id' => 38, 'city' => 'Donald'],
                ['state_id' => 38, 'city' => 'Gervais'],
                ['state_id' => 38, 'city' => 'Hubbard'],
                ['state_id' => 38, 'city' => 'Woodburn'],
                ['state_id' => 38, 'city' => 'Saint Paul'],
                ['state_id' => 38, 'city' => 'Salem'],
                ['state_id' => 38, 'city' => 'Keizer'],
                ['state_id' => 38, 'city' => 'Aumsville'],
                ['state_id' => 38, 'city' => 'Detroit'],
                ['state_id' => 38, 'city' => 'Gates'],
                ['state_id' => 38, 'city' => 'Idanha'],
                ['state_id' => 38, 'city' => 'Jefferson'],
                ['state_id' => 38, 'city' => 'Mount Angel'],
                ['state_id' => 38, 'city' => 'Saint Benedict'],
                ['state_id' => 38, 'city' => 'Scotts Mills'],
                ['state_id' => 38, 'city' => 'Silverton'],
                ['state_id' => 38, 'city' => 'Stayton'],
                ['state_id' => 38, 'city' => 'Mehama'],
                ['state_id' => 38, 'city' => 'Sublimity'],
                ['state_id' => 38, 'city' => 'Turner'],
                ['state_id' => 38, 'city' => 'Boardman'],
                ['state_id' => 38, 'city' => 'Heppner'],
                ['state_id' => 38, 'city' => 'Lexington'],
                ['state_id' => 38, 'city' => 'Ione'],
                ['state_id' => 38, 'city' => 'Irrigon'],
                ['state_id' => 38, 'city' => 'Bridal Veil'],
                ['state_id' => 38, 'city' => 'Corbett'],
                ['state_id' => 38, 'city' => 'Fairview'],
                ['state_id' => 38, 'city' => 'Gresham'],
                ['state_id' => 38, 'city' => 'Troutdale'],
                ['state_id' => 38, 'city' => 'Happy Valley'],
                ['state_id' => 38, 'city' => 'Dallas'],
                ['state_id' => 38, 'city' => 'Falls City'],
                ['state_id' => 38, 'city' => 'Grand Ronde'],
                ['state_id' => 38, 'city' => 'Independence'],
                ['state_id' => 38, 'city' => 'Monmouth'],
                ['state_id' => 38, 'city' => 'Rickreall'],
                ['state_id' => 38, 'city' => 'Grass Valley'],
                ['state_id' => 38, 'city' => 'Kent'],
                ['state_id' => 38, 'city' => 'Moro'],
                ['state_id' => 38, 'city' => 'Rufus'],
                ['state_id' => 38, 'city' => 'Wasco'],
                ['state_id' => 38, 'city' => 'Bay City'],
                ['state_id' => 38, 'city' => 'Beaver'],
                ['state_id' => 38, 'city' => 'Cloverdale'],
                ['state_id' => 38, 'city' => 'Garibaldi'],
                ['state_id' => 38, 'city' => 'Hebo'],
                ['state_id' => 38, 'city' => 'Manzanita'],
                ['state_id' => 38, 'city' => 'Nehalem'],
                ['state_id' => 38, 'city' => 'Oceanside'],
                ['state_id' => 38, 'city' => 'Pacific City'],
                ['state_id' => 38, 'city' => 'Rockaway Beach'],
                ['state_id' => 38, 'city' => 'Tillamook'],
                ['state_id' => 38, 'city' => 'Netarts'],
                ['state_id' => 38, 'city' => 'Wheeler'],
                ['state_id' => 38, 'city' => 'Neskowin'],
                ['state_id' => 38, 'city' => 'Pendleton'],
                ['state_id' => 38, 'city' => 'Adams'],
                ['state_id' => 38, 'city' => 'Athena'],
                ['state_id' => 38, 'city' => 'Echo'],
                ['state_id' => 38, 'city' => 'Helix'],
                ['state_id' => 38, 'city' => 'Hermiston'],
                ['state_id' => 38, 'city' => 'Meacham'],
                ['state_id' => 38, 'city' => 'Milton Freewater'],
                ['state_id' => 38, 'city' => 'Pilot Rock'],
                ['state_id' => 38, 'city' => 'Stanfield'],
                ['state_id' => 38, 'city' => 'Ukiah'],
                ['state_id' => 38, 'city' => 'Umatilla'],
                ['state_id' => 38, 'city' => 'Weston'],
                ['state_id' => 38, 'city' => 'Cove'],
                ['state_id' => 38, 'city' => 'Elgin'],
                ['state_id' => 38, 'city' => 'Imbler'],
                ['state_id' => 38, 'city' => 'La Grande'],
                ['state_id' => 38, 'city' => 'North Powder'],
                ['state_id' => 38, 'city' => 'Summerville'],
                ['state_id' => 38, 'city' => 'Union'],
                ['state_id' => 38, 'city' => 'Enterprise'],
                ['state_id' => 38, 'city' => 'Imnaha'],
                ['state_id' => 38, 'city' => 'Joseph'],
                ['state_id' => 38, 'city' => 'Lostine'],
                ['state_id' => 38, 'city' => 'Wallowa'],
                ['state_id' => 38, 'city' => 'Antelope'],
                ['state_id' => 38, 'city' => 'Dufur'],
                ['state_id' => 38, 'city' => 'Maupin'],
                ['state_id' => 38, 'city' => 'Mosier'],
                ['state_id' => 38, 'city' => 'Shaniko'],
                ['state_id' => 38, 'city' => 'The Dalles'],
                ['state_id' => 38, 'city' => 'Tygh Valley'],
                ['state_id' => 38, 'city' => 'Beaverton'],
                ['state_id' => 38, 'city' => 'Tualatin'],
                ['state_id' => 38, 'city' => 'Banks'],
                ['state_id' => 38, 'city' => 'Buxton'],
                ['state_id' => 38, 'city' => 'Cornelius'],
                ['state_id' => 38, 'city' => 'Forest Grove'],
                ['state_id' => 38, 'city' => 'Gales Creek'],
                ['state_id' => 38, 'city' => 'Gaston'],
                ['state_id' => 38, 'city' => 'Hillsboro'],
                ['state_id' => 38, 'city' => 'Manning'],
                ['state_id' => 38, 'city' => 'North Plains'],
                ['state_id' => 38, 'city' => 'Sherwood'],
                ['state_id' => 38, 'city' => 'Timber'],
                ['state_id' => 38, 'city' => 'Mitchell'],
                ['state_id' => 38, 'city' => 'Fossil'],
                ['state_id' => 38, 'city' => 'Spray'],
                ['state_id' => 38, 'city' => 'Amity'],
                ['state_id' => 38, 'city' => 'Carlton'],
                ['state_id' => 38, 'city' => 'Dayton'],
                ['state_id' => 38, 'city' => 'Dundee'],
                ['state_id' => 38, 'city' => 'Lafayette'],
                ['state_id' => 38, 'city' => 'Mcminnville'],
                ['state_id' => 38, 'city' => 'Newberg'],
                ['state_id' => 38, 'city' => 'Yamhill'],
                ['state_id' => 38, 'city' => 'Sheridan'],
                ['state_id' => 38, 'city' => 'Willamina', 'state_id' => 38]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
