<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State1TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of AL - Alabama.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 1, 'city' => 'Autaugaville'],
                ['state_id' => 1, 'city' => 'Billingsley'],
                ['state_id' => 1, 'city' => 'Booth'],
                ['state_id' => 1, 'city' => 'Marbury'],
                ['state_id' => 1, 'city' => 'Prattville'],
                ['state_id' => 1, 'city' => 'Jones'],
                ['state_id' => 1, 'city' => 'Bay Minette'],
                ['state_id' => 1, 'city' => 'Bon Secour'],
                ['state_id' => 1, 'city' => 'Daphne'],
                ['state_id' => 1, 'city' => 'Spanish Fort'],
                ['state_id' => 1, 'city' => 'Elberta'],
                ['state_id' => 1, 'city' => 'Fairhope'],
                ['state_id' => 1, 'city' => 'Foley'],
                ['state_id' => 1, 'city' => 'Gulf Shores'],
                ['state_id' => 1, 'city' => 'Lillian'],
                ['state_id' => 1, 'city' => 'Little River'],
                ['state_id' => 1, 'city' => 'Loxley'],
                ['state_id' => 1, 'city' => 'Magnolia Springs'],
                ['state_id' => 1, 'city' => 'Montrose'],
                ['state_id' => 1, 'city' => 'Orange Beach'],
                ['state_id' => 1, 'city' => 'Perdido'],
                ['state_id' => 1, 'city' => 'Point Clear'],
                ['state_id' => 1, 'city' => 'Robertsdale'],
                ['state_id' => 1, 'city' => 'Seminole'],
                ['state_id' => 1, 'city' => 'Silverhill'],
                ['state_id' => 1, 'city' => 'Stapleton'],
                ['state_id' => 1, 'city' => 'Stockton'],
                ['state_id' => 1, 'city' => 'Summerdale'],
                ['state_id' => 1, 'city' => 'Clayton'],
                ['state_id' => 1, 'city' => 'Clio'],
                ['state_id' => 1, 'city' => 'Eufaula'],
                ['state_id' => 1, 'city' => 'Louisville'],
                ['state_id' => 1, 'city' => 'Brent'],
                ['state_id' => 1, 'city' => 'Brierfield'],
                ['state_id' => 1, 'city' => 'Centreville'],
                ['state_id' => 1, 'city' => 'Green Pond'],
                ['state_id' => 1, 'city' => 'West Blocton'],
                ['state_id' => 1, 'city' => 'Woodstock'],
                ['state_id' => 1, 'city' => 'Randolph'],
                ['state_id' => 1, 'city' => 'Lawley'],
                ['state_id' => 1, 'city' => 'Allgood'],
                ['state_id' => 1, 'city' => 'Blountsville'],
                ['state_id' => 1, 'city' => 'Cleveland'],
                ['state_id' => 1, 'city' => 'Hayden'],
                ['state_id' => 1, 'city' => 'Locust Fork'],
                ['state_id' => 1, 'city' => 'Oneonta'],
                ['state_id' => 1, 'city' => 'Remlap'],
                ['state_id' => 1, 'city' => 'Fitzpatrick'],
                ['state_id' => 1, 'city' => 'Midway'],
                ['state_id' => 1, 'city' => 'Perote'],
                ['state_id' => 1, 'city' => 'Union Springs'],
                ['state_id' => 1, 'city' => 'Chapman'],
                ['state_id' => 1, 'city' => 'Forest Home'],
                ['state_id' => 1, 'city' => 'Georgiana'],
                ['state_id' => 1, 'city' => 'Greenville'],
                ['state_id' => 1, 'city' => 'Mc Kenzie'],
                ['state_id' => 1, 'city' => 'Anniston'],
                ['state_id' => 1, 'city' => 'Oxford'],
                ['state_id' => 1, 'city' => 'Alexandria'],
                ['state_id' => 1, 'city' => 'Bynum'],
                ['state_id' => 1, 'city' => 'Choccolocco'],
                ['state_id' => 1, 'city' => 'De Armanville'],
                ['state_id' => 1, 'city' => 'Eastaboga'],
                ['state_id' => 1, 'city' => 'Jacksonville'],
                ['state_id' => 1, 'city' => 'Ohatchee'],
                ['state_id' => 1, 'city' => 'Piedmont'],
                ['state_id' => 1, 'city' => 'Weaver'],
                ['state_id' => 1, 'city' => 'Wellington'],
                ['state_id' => 1, 'city' => 'Cusseta'],
                ['state_id' => 1, 'city' => 'Valley'],
                ['state_id' => 1, 'city' => 'Five Points'],
                ['state_id' => 1, 'city' => 'Lafayette'],
                ['state_id' => 1, 'city' => 'Lanett'],
                ['state_id' => 1, 'city' => 'Cedar Bluff'],
                ['state_id' => 1, 'city' => 'Centre'],
                ['state_id' => 1, 'city' => 'Gaylesville'],
                ['state_id' => 1, 'city' => 'Leesburg'],
                ['state_id' => 1, 'city' => 'Spring Garden'],
                ['state_id' => 1, 'city' => 'Clanton'],
                ['state_id' => 1, 'city' => 'Jemison'],
                ['state_id' => 1, 'city' => 'Thorsby'],
                ['state_id' => 1, 'city' => 'Verbena'],
                ['state_id' => 1, 'city' => 'Maplesville'],
                ['state_id' => 1, 'city' => 'Stanton'],
                ['state_id' => 1, 'city' => 'Butler'],
                ['state_id' => 1, 'city' => 'Gilbertown'],
                ['state_id' => 1, 'city' => 'Jachin'],
                ['state_id' => 1, 'city' => 'Lisman'],
                ['state_id' => 1, 'city' => 'Melvin'],
                ['state_id' => 1, 'city' => 'Needham'],
                ['state_id' => 1, 'city' => 'Pennington'],
                ['state_id' => 1, 'city' => 'Silas'],
                ['state_id' => 1, 'city' => 'Toxey'],
                ['state_id' => 1, 'city' => 'Ward'],
                ['state_id' => 1, 'city' => 'Dickinson'],
                ['state_id' => 1, 'city' => 'Fulton'],
                ['state_id' => 1, 'city' => 'Grove Hill'],
                ['state_id' => 1, 'city' => 'Whatley'],
                ['state_id' => 1, 'city' => 'Coffeeville'],
                ['state_id' => 1, 'city' => 'Gainestown'],
                ['state_id' => 1, 'city' => 'Jackson'],
                ['state_id' => 1, 'city' => 'Campbell'],
                ['state_id' => 1, 'city' => 'Thomasville'],
                ['state_id' => 1, 'city' => 'Hollins'],
                ['state_id' => 1, 'city' => 'Ashland'],
                ['state_id' => 1, 'city' => 'Cragford'],
                ['state_id' => 1, 'city' => 'Delta'],
                ['state_id' => 1, 'city' => 'Lineville'],
                ['state_id' => 1, 'city' => 'Millerville'],
                ['state_id' => 1, 'city' => 'Edwardsville'],
                ['state_id' => 1, 'city' => 'Fruithurst'],
                ['state_id' => 1, 'city' => 'Heflin'],
                ['state_id' => 1, 'city' => 'Muscadine'],
                ['state_id' => 1, 'city' => 'Ranburne'],
                ['state_id' => 1, 'city' => 'Elba'],
                ['state_id' => 1, 'city' => 'Enterprise'],
                ['state_id' => 1, 'city' => 'Jack'],
                ['state_id' => 1, 'city' => 'New Brockton'],
                ['state_id' => 1, 'city' => 'Kinston'],
                ['state_id' => 1, 'city' => 'Cherokee'],
                ['state_id' => 1, 'city' => 'Leighton'],
                ['state_id' => 1, 'city' => 'Sheffield'],
                ['state_id' => 1, 'city' => 'Muscle Shoals'],
                ['state_id' => 1, 'city' => 'Tuscumbia'],
                ['state_id' => 1, 'city' => 'Evergreen'],
                ['state_id' => 1, 'city' => 'Brooklyn'],
                ['state_id' => 1, 'city' => 'Castleberry'],
                ['state_id' => 1, 'city' => 'Lenox'],
                ['state_id' => 1, 'city' => 'Range'],
                ['state_id' => 1, 'city' => 'Repton'],
                ['state_id' => 1, 'city' => 'Goodwater'],
                ['state_id' => 1, 'city' => 'Kellyton'],
                ['state_id' => 1, 'city' => 'Rockford'],
                ['state_id' => 1, 'city' => 'Weogufka'],
                ['state_id' => 1, 'city' => 'Equality'],
                ['state_id' => 1, 'city' => 'Gantt'],
                ['state_id' => 1, 'city' => 'Andalusia'],
                ['state_id' => 1, 'city' => 'Florala'],
                ['state_id' => 1, 'city' => 'Lockhart'],
                ['state_id' => 1, 'city' => 'Opp'],
                ['state_id' => 1, 'city' => 'Red Level'],
                ['state_id' => 1, 'city' => 'River Falls'],
                ['state_id' => 1, 'city' => 'Wing'],
                ['state_id' => 1, 'city' => 'Brantley'],
                ['state_id' => 1, 'city' => 'Dozier'],
                ['state_id' => 1, 'city' => 'Glenwood'],
                ['state_id' => 1, 'city' => 'Highland Home'],
                ['state_id' => 1, 'city' => 'Honoraville'],
                ['state_id' => 1, 'city' => 'Luverne'],
                ['state_id' => 1, 'city' => 'Petrey'],
                ['state_id' => 1, 'city' => 'Rutledge'],
                ['state_id' => 1, 'city' => 'Baileyton'],
                ['state_id' => 1, 'city' => 'Bremen'],
                ['state_id' => 1, 'city' => 'Crane Hill'],
                ['state_id' => 1, 'city' => 'Cullman'],
                ['state_id' => 1, 'city' => 'Garden City'],
                ['state_id' => 1, 'city' => 'Hanceville'],
                ['state_id' => 1, 'city' => 'Holly Pond'],
                ['state_id' => 1, 'city' => 'Joppa'],
                ['state_id' => 1, 'city' => 'Logan'],
                ['state_id' => 1, 'city' => 'Vinemont'],
                ['state_id' => 1, 'city' => 'Ariton'],
                ['state_id' => 1, 'city' => 'Clopton'],
                ['state_id' => 1, 'city' => 'Daleville'],
                ['state_id' => 1, 'city' => 'Midland City'],
                ['state_id' => 1, 'city' => 'Newton'],
                ['state_id' => 1, 'city' => 'Ozark'],
                ['state_id' => 1, 'city' => 'Fort Rucker'],
                ['state_id' => 1, 'city' => 'Pinckard'],
                ['state_id' => 1, 'city' => 'Skipperville'],
                ['state_id' => 1, 'city' => 'Selma'],
                ['state_id' => 1, 'city' => 'Plantersville'],
                ['state_id' => 1, 'city' => 'Marion Junction'],
                ['state_id' => 1, 'city' => 'Minter'],
                ['state_id' => 1, 'city' => 'Orrville'],
                ['state_id' => 1, 'city' => 'Safford'],
                ['state_id' => 1, 'city' => 'Sardis'],
                ['state_id' => 1, 'city' => 'Tyler'],
                ['state_id' => 1, 'city' => 'Collinsville'],
                ['state_id' => 1, 'city' => 'Crossville'],
                ['state_id' => 1, 'city' => 'Dawson'],
                ['state_id' => 1, 'city' => 'Fort Payne'],
                ['state_id' => 1, 'city' => 'Fyffe'],
                ['state_id' => 1, 'city' => 'Geraldine'],
                ['state_id' => 1, 'city' => 'Groveoak'],
                ['state_id' => 1, 'city' => 'Henagar'],
                ['state_id' => 1, 'city' => 'Ider'],
                ['state_id' => 1, 'city' => 'Mentone'],
                ['state_id' => 1, 'city' => 'Rainsville'],
                ['state_id' => 1, 'city' => 'Sylvania'],
                ['state_id' => 1, 'city' => 'Valley Head'],
                ['state_id' => 1, 'city' => 'Coosada'],
                ['state_id' => 1, 'city' => 'Deatsville'],
                ['state_id' => 1, 'city' => 'Eclectic'],
                ['state_id' => 1, 'city' => 'Elmore'],
                ['state_id' => 1, 'city' => 'Kent'],
                ['state_id' => 1, 'city' => 'Millbrook'],
                ['state_id' => 1, 'city' => 'Tallassee'],
                ['state_id' => 1, 'city' => 'Titus'],
                ['state_id' => 1, 'city' => 'Wetumpka'],
                ['state_id' => 1, 'city' => 'Brewton'],
                ['state_id' => 1, 'city' => 'Flomaton'],
                ['state_id' => 1, 'city' => 'Atmore'],
                ['state_id' => 1, 'city' => 'Huxford'],
                ['state_id' => 1, 'city' => 'Gadsden'],
                ['state_id' => 1, 'city' => 'Rainbow City'],
                ['state_id' => 1, 'city' => 'Altoona'],
                ['state_id' => 1, 'city' => 'Attalla'],
                ['state_id' => 1, 'city' => 'Gallant'],
                ['state_id' => 1, 'city' => 'Walnut Grove'],
                ['state_id' => 1, 'city' => 'Bankston'],
                ['state_id' => 1, 'city' => 'Belk'],
                ['state_id' => 1, 'city' => 'Berry'],
                ['state_id' => 1, 'city' => 'Fayette'],
                ['state_id' => 1, 'city' => 'Glen Allen'],
                ['state_id' => 1, 'city' => 'Hodges'],
                ['state_id' => 1, 'city' => 'Phil Campbell'],
                ['state_id' => 1, 'city' => 'Red Bay'],
                ['state_id' => 1, 'city' => 'Spruce Pine'],
                ['state_id' => 1, 'city' => 'Vina'],
                ['state_id' => 1, 'city' => 'Russellville'],
                ['state_id' => 1, 'city' => 'Bellwood'],
                ['state_id' => 1, 'city' => 'Black'],
                ['state_id' => 1, 'city' => 'Chancellor'],
                ['state_id' => 1, 'city' => 'Coffee Springs'],
                ['state_id' => 1, 'city' => 'Geneva'],
                ['state_id' => 1, 'city' => 'Hartford'],
                ['state_id' => 1, 'city' => 'Malvern'],
                ['state_id' => 1, 'city' => 'Slocomb'],
                ['state_id' => 1, 'city' => 'Samson'],
                ['state_id' => 1, 'city' => 'Boligee'],
                ['state_id' => 1, 'city' => 'Clinton'],
                ['state_id' => 1, 'city' => 'Eutaw'],
                ['state_id' => 1, 'city' => 'Knoxville'],
                ['state_id' => 1, 'city' => 'West Greene'],
                ['state_id' => 1, 'city' => 'Forkland'],
                ['state_id' => 1, 'city' => 'Akron'],
                ['state_id' => 1, 'city' => 'Moundville'],
                ['state_id' => 1, 'city' => 'Gallion'],
                ['state_id' => 1, 'city' => 'Greensboro'],
                ['state_id' => 1, 'city' => 'Newbern'],
                ['state_id' => 1, 'city' => 'Sawyerville'],
                ['state_id' => 1, 'city' => 'Abbeville'],
                ['state_id' => 1, 'city' => 'Headland'],
                ['state_id' => 1, 'city' => 'Newville'],
                ['state_id' => 1, 'city' => 'Shorterville'],
                ['state_id' => 1, 'city' => 'Dothan'],
                ['state_id' => 1, 'city' => 'Ashford'],
                ['state_id' => 1, 'city' => 'Columbia'],
                ['state_id' => 1, 'city' => 'Cottonwood'],
                ['state_id' => 1, 'city' => 'Cowarts'],
                ['state_id' => 1, 'city' => 'Gordon'],
                ['state_id' => 1, 'city' => 'Pansey'],
                ['state_id' => 1, 'city' => 'Webb'],
                ['state_id' => 1, 'city' => 'Bridgeport'],
                ['state_id' => 1, 'city' => 'Dutton'],
                ['state_id' => 1, 'city' => 'Estillfork'],
                ['state_id' => 1, 'city' => 'Fackler'],
                ['state_id' => 1, 'city' => 'Hollytree'],
                ['state_id' => 1, 'city' => 'Hollywood'],
                ['state_id' => 1, 'city' => 'Langston'],
                ['state_id' => 1, 'city' => 'Paint Rock'],
                ['state_id' => 1, 'city' => 'Pisgah'],
                ['state_id' => 1, 'city' => 'Princeton'],
                ['state_id' => 1, 'city' => 'Scottsboro'],
                ['state_id' => 1, 'city' => 'Section'],
                ['state_id' => 1, 'city' => 'Stevenson'],
                ['state_id' => 1, 'city' => 'Trenton'],
                ['state_id' => 1, 'city' => 'Woodville'],
                ['state_id' => 1, 'city' => 'Bryant'],
                ['state_id' => 1, 'city' => 'Flat Rock'],
                ['state_id' => 1, 'city' => 'Higdon'],
                ['state_id' => 1, 'city' => 'Adamsville'],
                ['state_id' => 1, 'city' => 'Adger'],
                ['state_id' => 1, 'city' => 'Alton'],
                ['state_id' => 1, 'city' => 'Bessemer'],
                ['state_id' => 1, 'city' => 'Brookside'],
                ['state_id' => 1, 'city' => 'Clay'],
                ['state_id' => 1, 'city' => 'Docena'],
                ['state_id' => 1, 'city' => 'Dolomite'],
                ['state_id' => 1, 'city' => 'Fairfield'],
                ['state_id' => 1, 'city' => 'Fultondale'],
                ['state_id' => 1, 'city' => 'Gardendale'],
                ['state_id' => 1, 'city' => 'Graysville'],
                ['state_id' => 1, 'city' => 'Kimberly'],
                ['state_id' => 1, 'city' => 'Leeds'],
                ['state_id' => 1, 'city' => 'Mc Calla'],
                ['state_id' => 1, 'city' => 'Morris'],
                ['state_id' => 1, 'city' => 'Mount Olive'],
                ['state_id' => 1, 'city' => 'Mulga'],
                ['state_id' => 1, 'city' => 'New Castle'],
                ['state_id' => 1, 'city' => 'Palmerdale'],
                ['state_id' => 1, 'city' => 'Pinson'],
                ['state_id' => 1, 'city' => 'Pleasant Grove'],
                ['state_id' => 1, 'city' => 'Sayre'],
                ['state_id' => 1, 'city' => 'Shannon'],
                ['state_id' => 1, 'city' => 'Trafford'],
                ['state_id' => 1, 'city' => 'Trussville'],
                ['state_id' => 1, 'city' => 'Warrior'],
                ['state_id' => 1, 'city' => 'Watson'],
                ['state_id' => 1, 'city' => 'Birmingham'],
                ['state_id' => 1, 'city' => 'Beaverton'],
                ['state_id' => 1, 'city' => 'Detroit'],
                ['state_id' => 1, 'city' => 'Kennedy'],
                ['state_id' => 1, 'city' => 'Millport'],
                ['state_id' => 1, 'city' => 'Sulligent'],
                ['state_id' => 1, 'city' => 'Vernon'],
                ['state_id' => 1, 'city' => 'Anderson'],
                ['state_id' => 1, 'city' => 'Cloverdale'],
                ['state_id' => 1, 'city' => 'Florence'],
                ['state_id' => 1, 'city' => 'Killen'],
                ['state_id' => 1, 'city' => 'Lexington'],
                ['state_id' => 1, 'city' => 'Rogersville'],
                ['state_id' => 1, 'city' => 'Waterloo'],
                ['state_id' => 1, 'city' => 'Courtland'],
                ['state_id' => 1, 'city' => 'Hillsboro'],
                ['state_id' => 1, 'city' => 'Moulton'],
                ['state_id' => 1, 'city' => 'Mount Hope'],
                ['state_id' => 1, 'city' => 'Town Creek'],
                ['state_id' => 1, 'city' => 'Opelika'],
                ['state_id' => 1, 'city' => 'Auburn'],
                ['state_id' => 1, 'city' => 'Auburn University'],
                ['state_id' => 1, 'city' => 'Loachapoka'],
                ['state_id' => 1, 'city' => 'Salem'],
                ['state_id' => 1, 'city' => 'Smiths Station'],
                ['state_id' => 1, 'city' => 'Waverly'],
                ['state_id' => 1, 'city' => 'Athens'],
                ['state_id' => 1, 'city' => 'Belle Mina'],
                ['state_id' => 1, 'city' => 'Elkmont'],
                ['state_id' => 1, 'city' => 'Lester'],
                ['state_id' => 1, 'city' => 'Mooresville'],
                ['state_id' => 1, 'city' => 'Tanner'],
                ['state_id' => 1, 'city' => 'Ardmore'],
                ['state_id' => 1, 'city' => 'Capshaw'],
                ['state_id' => 1, 'city' => 'Fort Deposit'],
                ['state_id' => 1, 'city' => 'Hayneville'],
                ['state_id' => 1, 'city' => 'Letohatchee'],
                ['state_id' => 1, 'city' => 'Lowndesboro'],
                ['state_id' => 1, 'city' => 'Fort Davis'],
                ['state_id' => 1, 'city' => 'Hardaway'],
                ['state_id' => 1, 'city' => 'Shorter'],
                ['state_id' => 1, 'city' => 'Tuskegee'],
                ['state_id' => 1, 'city' => 'Tuskegee Institute'],
                ['state_id' => 1, 'city' => 'Notasulga'],
                ['state_id' => 1, 'city' => 'Brownsboro'],
                ['state_id' => 1, 'city' => 'Gurley'],
                ['state_id' => 1, 'city' => 'Harvest'],
                ['state_id' => 1, 'city' => 'Hazel Green'],
                ['state_id' => 1, 'city' => 'Madison'],
                ['state_id' => 1, 'city' => 'Meridianville'],
                ['state_id' => 1, 'city' => 'New Hope'],
                ['state_id' => 1, 'city' => 'New Market'],
                ['state_id' => 1, 'city' => 'Normal'],
                ['state_id' => 1, 'city' => 'Owens Cross Roads'],
                ['state_id' => 1, 'city' => 'Ryland'],
                ['state_id' => 1, 'city' => 'Toney'],
                ['state_id' => 1, 'city' => 'Huntsville'],
                ['state_id' => 1, 'city' => 'Demopolis'],
                ['state_id' => 1, 'city' => 'Dixons Mills'],
                ['state_id' => 1, 'city' => 'Faunsdale'],
                ['state_id' => 1, 'city' => 'Jefferson'],
                ['state_id' => 1, 'city' => 'Linden'],
                ['state_id' => 1, 'city' => 'Magnolia'],
                ['state_id' => 1, 'city' => 'Myrtlewood'],
                ['state_id' => 1, 'city' => 'Nanafalia'],
                ['state_id' => 1, 'city' => 'Sweet Water'],
                ['state_id' => 1, 'city' => 'Thomaston'],
                ['state_id' => 1, 'city' => 'Bear Creek'],
                ['state_id' => 1, 'city' => 'Brilliant'],
                ['state_id' => 1, 'city' => 'Guin'],
                ['state_id' => 1, 'city' => 'Hackleburg'],
                ['state_id' => 1, 'city' => 'Hamilton'],
                ['state_id' => 1, 'city' => 'Winfield'],
                ['state_id' => 1, 'city' => 'Arab'],
                ['state_id' => 1, 'city' => 'Union Grove'],
                ['state_id' => 1, 'city' => 'Grant'],
                ['state_id' => 1, 'city' => 'Albertville'],
                ['state_id' => 1, 'city' => 'Boaz'],
                ['state_id' => 1, 'city' => 'Douglas'],
                ['state_id' => 1, 'city' => 'Guntersville'],
                ['state_id' => 1, 'city' => 'Horton'],
                ['state_id' => 1, 'city' => 'Axis'],
                ['state_id' => 1, 'city' => 'Bayou La Batre'],
                ['state_id' => 1, 'city' => 'Bucks'],
                ['state_id' => 1, 'city' => 'Chunchula'],
                ['state_id' => 1, 'city' => 'Citronelle'],
                ['state_id' => 1, 'city' => 'Coden'],
                ['state_id' => 1, 'city' => 'Creola'],
                ['state_id' => 1, 'city' => 'Dauphin Island'],
                ['state_id' => 1, 'city' => 'Grand Bay'],
                ['state_id' => 1, 'city' => 'Irvington'],
                ['state_id' => 1, 'city' => 'Mount Vernon'],
                ['state_id' => 1, 'city' => 'Saint Elmo'],
                ['state_id' => 1, 'city' => 'Saraland'],
                ['state_id' => 1, 'city' => 'Satsuma'],
                ['state_id' => 1, 'city' => 'Semmes'],
                ['state_id' => 1, 'city' => 'Theodore'],
                ['state_id' => 1, 'city' => 'Wilmer'],
                ['state_id' => 1, 'city' => 'Mobile'],
                ['state_id' => 1, 'city' => 'Eight Mile'],
                ['state_id' => 1, 'city' => 'Beatrice'],
                ['state_id' => 1, 'city' => 'Excel'],
                ['state_id' => 1, 'city' => 'Franklin'],
                ['state_id' => 1, 'city' => 'Frisco City'],
                ['state_id' => 1, 'city' => 'Goodway'],
                ['state_id' => 1, 'city' => 'Megargel'],
                ['state_id' => 1, 'city' => 'Mexia'],
                ['state_id' => 1, 'city' => 'Monroeville'],
                ['state_id' => 1, 'city' => 'Perdue Hill'],
                ['state_id' => 1, 'city' => 'Peterman'],
                ['state_id' => 1, 'city' => 'Uriah'],
                ['state_id' => 1, 'city' => 'Vredenburgh'],
                ['state_id' => 1, 'city' => 'Cecil'],
                ['state_id' => 1, 'city' => 'Grady'],
                ['state_id' => 1, 'city' => 'Hope Hull'],
                ['state_id' => 1, 'city' => 'Lapine'],
                ['state_id' => 1, 'city' => 'Mathews'],
                ['state_id' => 1, 'city' => 'Mount Meigs'],
                ['state_id' => 1, 'city' => 'Pike Road'],
                ['state_id' => 1, 'city' => 'Pine Level'],
                ['state_id' => 1, 'city' => 'Ramer'],
                ['state_id' => 1, 'city' => 'Montgomery'],
                ['state_id' => 1, 'city' => 'Decatur'],
                ['state_id' => 1, 'city' => 'Danville'],
                ['state_id' => 1, 'city' => 'Eva'],
                ['state_id' => 1, 'city' => 'Falkville'],
                ['state_id' => 1, 'city' => 'Hartselle'],
                ['state_id' => 1, 'city' => 'Somerville'],
                ['state_id' => 1, 'city' => 'Trinity'],
                ['state_id' => 1, 'city' => 'Laceys Spring'],
                ['state_id' => 1, 'city' => 'Valhermoso Springs'],
                ['state_id' => 1, 'city' => 'Marion'],
                ['state_id' => 1, 'city' => 'Uniontown'],
                ['state_id' => 1, 'city' => 'Aliceville'],
                ['state_id' => 1, 'city' => 'Carrollton'],
                ['state_id' => 1, 'city' => 'Ethelsville'],
                ['state_id' => 1, 'city' => 'Gordo'],
                ['state_id' => 1, 'city' => 'Mc Shan'],
                ['state_id' => 1, 'city' => 'Reform'],
                ['state_id' => 1, 'city' => 'Banks'],
                ['state_id' => 1, 'city' => 'Brundidge'],
                ['state_id' => 1, 'city' => 'Goshen'],
                ['state_id' => 1, 'city' => 'Troy'],
                ['state_id' => 1, 'city' => 'Graham'],
                ['state_id' => 1, 'city' => 'Roanoke'],
                ['state_id' => 1, 'city' => 'Wadley'],
                ['state_id' => 1, 'city' => 'Wedowee'],
                ['state_id' => 1, 'city' => 'Woodland'],
                ['state_id' => 1, 'city' => 'Cottonton'],
                ['state_id' => 1, 'city' => 'Fort Mitchell'],
                ['state_id' => 1, 'city' => 'Hatchechubbee'],
                ['state_id' => 1, 'city' => 'Holy Trinity'],
                ['state_id' => 1, 'city' => 'Hurtsboro'],
                ['state_id' => 1, 'city' => 'Phenix City'],
                ['state_id' => 1, 'city' => 'Pittsview'],
                ['state_id' => 1, 'city' => 'Seale'],
                ['state_id' => 1, 'city' => 'Moody'],
                ['state_id' => 1, 'city' => 'Cook Springs'],
                ['state_id' => 1, 'city' => 'Cropwell'],
                ['state_id' => 1, 'city' => 'Margaret'],
                ['state_id' => 1, 'city' => 'Odenville'],
                ['state_id' => 1, 'city' => 'Pell City'],
                ['state_id' => 1, 'city' => 'Ragland'],
                ['state_id' => 1, 'city' => 'Riverside'],
                ['state_id' => 1, 'city' => 'Springville'],
                ['state_id' => 1, 'city' => 'Wattsville'],
                ['state_id' => 1, 'city' => 'Ashville'],
                ['state_id' => 1, 'city' => 'Steele'],
                ['state_id' => 1, 'city' => 'Alabaster'],
                ['state_id' => 1, 'city' => 'Calera'],
                ['state_id' => 1, 'city' => 'Chelsea'],
                ['state_id' => 1, 'city' => 'Columbiana'],
                ['state_id' => 1, 'city' => 'Harpersville'],
                ['state_id' => 1, 'city' => 'Helena'],
                ['state_id' => 1, 'city' => 'Maylene'],
                ['state_id' => 1, 'city' => 'Montevallo'],
                ['state_id' => 1, 'city' => 'Pelham'],
                ['state_id' => 1, 'city' => 'Saginaw'],
                ['state_id' => 1, 'city' => 'Shelby'],
                ['state_id' => 1, 'city' => 'Siluria'],
                ['state_id' => 1, 'city' => 'Sterrett'],
                ['state_id' => 1, 'city' => 'Vandiver'],
                ['state_id' => 1, 'city' => 'Vincent'],
                ['state_id' => 1, 'city' => 'Westover'],
                ['state_id' => 1, 'city' => 'Wilsonville'],
                ['state_id' => 1, 'city' => 'Wilton'],
                ['state_id' => 1, 'city' => 'Emelle'],
                ['state_id' => 1, 'city' => 'Epes'],
                ['state_id' => 1, 'city' => 'Gainesville'],
                ['state_id' => 1, 'city' => 'Livingston'],
                ['state_id' => 1, 'city' => 'Panola'],
                ['state_id' => 1, 'city' => 'Bellamy'],
                ['state_id' => 1, 'city' => 'Cuba'],
                ['state_id' => 1, 'city' => 'York'],
                ['state_id' => 1, 'city' => 'Alpine'],
                ['state_id' => 1, 'city' => 'Bon Air'],
                ['state_id' => 1, 'city' => 'Childersburg'],
                ['state_id' => 1, 'city' => 'Lincoln'],
                ['state_id' => 1, 'city' => 'Sycamore'],
                ['state_id' => 1, 'city' => 'Sylacauga'],
                ['state_id' => 1, 'city' => 'Talladega'],
                ['state_id' => 1, 'city' => 'Munford'],
                ['state_id' => 1, 'city' => 'Alexander City'],
                ['state_id' => 1, 'city' => 'East Tallassee'],
                ['state_id' => 1, 'city' => 'Daviston'],
                ['state_id' => 1, 'city' => 'Camp Hill'],
                ['state_id' => 1, 'city' => 'Dadeville'],
                ['state_id' => 1, 'city' => 'Jacksons Gap'],
                ['state_id' => 1, 'city' => 'Tuscaloosa'],
                ['state_id' => 1, 'city' => 'Abernant'],
                ['state_id' => 1, 'city' => 'Brookwood'],
                ['state_id' => 1, 'city' => 'Buhl'],
                ['state_id' => 1, 'city' => 'Coaling'],
                ['state_id' => 1, 'city' => 'Coker'],
                ['state_id' => 1, 'city' => 'Cottondale'],
                ['state_id' => 1, 'city' => 'Duncanville'],
                ['state_id' => 1, 'city' => 'Echola'],
                ['state_id' => 1, 'city' => 'Elrod'],
                ['state_id' => 1, 'city' => 'Fosters'],
                ['state_id' => 1, 'city' => 'Kellerman'],
                ['state_id' => 1, 'city' => 'Northport'],
                ['state_id' => 1, 'city' => 'Peterson'],
                ['state_id' => 1, 'city' => 'Ralph'],
                ['state_id' => 1, 'city' => 'Samantha'],
                ['state_id' => 1, 'city' => 'Vance'],
                ['state_id' => 1, 'city' => 'Burnwell'],
                ['state_id' => 1, 'city' => 'Dora'],
                ['state_id' => 1, 'city' => 'Empire'],
                ['state_id' => 1, 'city' => 'Quinton'],
                ['state_id' => 1, 'city' => 'Sumiton'],
                ['state_id' => 1, 'city' => 'Jasper'],
                ['state_id' => 1, 'city' => 'Carbon Hill'],
                ['state_id' => 1, 'city' => 'Cordova'],
                ['state_id' => 1, 'city' => 'Eldridge'],
                ['state_id' => 1, 'city' => 'Goodsprings'],
                ['state_id' => 1, 'city' => 'Kansas'],
                ['state_id' => 1, 'city' => 'Nauvoo'],
                ['state_id' => 1, 'city' => 'Oakman'],
                ['state_id' => 1, 'city' => 'Parrish'],
                ['state_id' => 1, 'city' => 'Sipsey'],
                ['state_id' => 1, 'city' => 'Townley'],
                ['state_id' => 1, 'city' => 'Calvert'],
                ['state_id' => 1, 'city' => 'Chatom'],
                ['state_id' => 1, 'city' => 'Deer Park'],
                ['state_id' => 1, 'city' => 'Frankville'],
                ['state_id' => 1, 'city' => 'Fruitdale'],
                ['state_id' => 1, 'city' => 'Leroy'],
                ['state_id' => 1, 'city' => 'Mc Intosh'],
                ['state_id' => 1, 'city' => 'Malcolm'],
                ['state_id' => 1, 'city' => 'Millry'],
                ['state_id' => 1, 'city' => 'Saint Stephens'],
                ['state_id' => 1, 'city' => 'Sunflower'],
                ['state_id' => 1, 'city' => 'Tibbie'],
                ['state_id' => 1, 'city' => 'Vinegar Bend'],
                ['state_id' => 1, 'city' => 'Wagarville'],
                ['state_id' => 1, 'city' => 'Coy'],
                ['state_id' => 1, 'city' => 'Alberta'],
                ['state_id' => 1, 'city' => 'Arlington'],
                ['state_id' => 1, 'city' => 'Boykin'],
                ['state_id' => 1, 'city' => 'Camden'],
                ['state_id' => 1, 'city' => 'Catherine'],
                ['state_id' => 1, 'city' => 'Furman'],
                ['state_id' => 1, 'city' => 'Lower Peach Tree'],
                ['state_id' => 1, 'city' => 'Mc Williams'],
                ['state_id' => 1, 'city' => 'Oak Hill'],
                ['state_id' => 1, 'city' => 'Pine Apple'],
                ['state_id' => 1, 'city' => 'Pine Hill'],
                ['state_id' => 1, 'city' => 'Addison'],
                ['state_id' => 1, 'city' => 'Arley'],
                ['state_id' => 1, 'city' => 'Delmar'],
                ['state_id' => 1, 'city' => 'Double Springs'],
                ['state_id' => 1, 'city' => 'Haleyville'],
                ['state_id' => 1, 'city' => 'Houston'],
                ['state_id' => 1, 'city' => 'Lynn'],
                ['state_id' => 1, 'city' => 'Natural Bridge']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
