<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State49TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of WV - West Virginia.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 49, 'city' => 'Volga'],
                ['state_id' => 49, 'city' => 'Belington'],
                ['state_id' => 49, 'city' => 'Junior'],
                ['state_id' => 49, 'city' => 'Galloway'],
                ['state_id' => 49, 'city' => 'Moatsville'],
                ['state_id' => 49, 'city' => 'Philippi'],
                ['state_id' => 49, 'city' => 'Martinsburg'],
                ['state_id' => 49, 'city' => 'Bunker Hill'],
                ['state_id' => 49, 'city' => 'Falling Waters'],
                ['state_id' => 49, 'city' => 'Gerrardstown'],
                ['state_id' => 49, 'city' => 'Glengary'],
                ['state_id' => 49, 'city' => 'Hedgesville'],
                ['state_id' => 49, 'city' => 'Inwood'],
                ['state_id' => 49, 'city' => 'Ridgeway'],
                ['state_id' => 49, 'city' => 'Ashford'],
                ['state_id' => 49, 'city' => 'Bim'],
                ['state_id' => 49, 'city' => 'Bloomingrose'],
                ['state_id' => 49, 'city' => 'Bob White'],
                ['state_id' => 49, 'city' => 'Comfort'],
                ['state_id' => 49, 'city' => 'Costa'],
                ['state_id' => 49, 'city' => 'Danville'],
                ['state_id' => 49, 'city' => 'Foster'],
                ['state_id' => 49, 'city' => 'Gordon'],
                ['state_id' => 49, 'city' => 'Hewett'],
                ['state_id' => 49, 'city' => 'Jeffrey'],
                ['state_id' => 49, 'city' => 'Madison'],
                ['state_id' => 49, 'city' => 'Nellis'],
                ['state_id' => 49, 'city' => 'Orgas'],
                ['state_id' => 49, 'city' => 'Ottawa'],
                ['state_id' => 49, 'city' => 'Peytona'],
                ['state_id' => 49, 'city' => 'Racine'],
                ['state_id' => 49, 'city' => 'Ridgeview'],
                ['state_id' => 49, 'city' => 'Seth'],
                ['state_id' => 49, 'city' => 'Sylvester'],
                ['state_id' => 49, 'city' => 'Turtle Creek'],
                ['state_id' => 49, 'city' => 'Twilight'],
                ['state_id' => 49, 'city' => 'Uneeda'],
                ['state_id' => 49, 'city' => 'Van'],
                ['state_id' => 49, 'city' => 'Wharton'],
                ['state_id' => 49, 'city' => 'Whitesville'],
                ['state_id' => 49, 'city' => 'Julian'],
                ['state_id' => 49, 'city' => 'Burnsville'],
                ['state_id' => 49, 'city' => 'Sutton'],
                ['state_id' => 49, 'city' => 'Copen'],
                ['state_id' => 49, 'city' => 'Exchange'],
                ['state_id' => 49, 'city' => 'Flatwoods'],
                ['state_id' => 49, 'city' => 'Frametown'],
                ['state_id' => 49, 'city' => 'Gassaway'],
                ['state_id' => 49, 'city' => 'Heaters'],
                ['state_id' => 49, 'city' => 'Little Birch'],
                ['state_id' => 49, 'city' => 'Napier'],
                ['state_id' => 49, 'city' => 'Beech Bottom'],
                ['state_id' => 49, 'city' => 'Bethany'],
                ['state_id' => 49, 'city' => 'Colliers'],
                ['state_id' => 49, 'city' => 'Follansbee'],
                ['state_id' => 49, 'city' => 'Short Creek'],
                ['state_id' => 49, 'city' => 'Wellsburg'],
                ['state_id' => 49, 'city' => 'Windsor Heights'],
                ['state_id' => 49, 'city' => 'Barboursville'],
                ['state_id' => 49, 'city' => 'Culloden'],
                ['state_id' => 49, 'city' => 'Lesage'],
                ['state_id' => 49, 'city' => 'Milton'],
                ['state_id' => 49, 'city' => 'Ona'],
                ['state_id' => 49, 'city' => 'Salt Rock'],
                ['state_id' => 49, 'city' => 'Huntington'],
                ['state_id' => 49, 'city' => 'Arnoldsburg'],
                ['state_id' => 49, 'city' => 'Chloe'],
                ['state_id' => 49, 'city' => 'Millstone'],
                ['state_id' => 49, 'city' => 'Orma'],
                ['state_id' => 49, 'city' => 'Big Bend'],
                ['state_id' => 49, 'city' => 'Big Springs'],
                ['state_id' => 49, 'city' => 'Grantsville'],
                ['state_id' => 49, 'city' => 'Mount Zion'],
                ['state_id' => 49, 'city' => 'Bickmore'],
                ['state_id' => 49, 'city' => 'Bomont'],
                ['state_id' => 49, 'city' => 'Clay'],
                ['state_id' => 49, 'city' => 'Duck'],
                ['state_id' => 49, 'city' => 'Glen'],
                ['state_id' => 49, 'city' => 'Indore'],
                ['state_id' => 49, 'city' => 'Ivydale'],
                ['state_id' => 49, 'city' => 'Lizemores'],
                ['state_id' => 49, 'city' => 'Maysel'],
                ['state_id' => 49, 'city' => 'Nebo'],
                ['state_id' => 49, 'city' => 'Procious'],
                ['state_id' => 49, 'city' => 'Widen'],
                ['state_id' => 49, 'city' => 'Wallback'],
                ['state_id' => 49, 'city' => 'Dille'],
                ['state_id' => 49, 'city' => 'Center Point'],
                ['state_id' => 49, 'city' => 'New Milton'],
                ['state_id' => 49, 'city' => 'Smithburg'],
                ['state_id' => 49, 'city' => 'West Union'],
                ['state_id' => 49, 'city' => 'Alloy'],
                ['state_id' => 49, 'city' => 'Boomer'],
                ['state_id' => 49, 'city' => 'Cannelton'],
                ['state_id' => 49, 'city' => 'Charlton Heights'],
                ['state_id' => 49, 'city' => 'Deep Water'],
                ['state_id' => 49, 'city' => 'Gauley Bridge'],
                ['state_id' => 49, 'city' => 'Glen Ferris'],
                ['state_id' => 49, 'city' => 'Kanawha Falls'],
                ['state_id' => 49, 'city' => 'Kimberly'],
                ['state_id' => 49, 'city' => 'Kincaid'],
                ['state_id' => 49, 'city' => 'Montgomery'],
                ['state_id' => 49, 'city' => 'Mount Carbon'],
                ['state_id' => 49, 'city' => 'Page'],
                ['state_id' => 49, 'city' => 'Powellton'],
                ['state_id' => 49, 'city' => 'Robson'],
                ['state_id' => 49, 'city' => 'Mount Olive'],
                ['state_id' => 49, 'city' => 'Smithers'],
                ['state_id' => 49, 'city' => 'Ansted'],
                ['state_id' => 49, 'city' => 'Danese'],
                ['state_id' => 49, 'city' => 'Dothan'],
                ['state_id' => 49, 'city' => 'Edmond'],
                ['state_id' => 49, 'city' => 'Fayetteville'],
                ['state_id' => 49, 'city' => 'Glen Jean'],
                ['state_id' => 49, 'city' => 'Hico'],
                ['state_id' => 49, 'city' => 'Hilltop'],
                ['state_id' => 49, 'city' => 'Lansing'],
                ['state_id' => 49, 'city' => 'Layland'],
                ['state_id' => 49, 'city' => 'Lochgelly'],
                ['state_id' => 49, 'city' => 'Lookout'],
                ['state_id' => 49, 'city' => 'Minden'],
                ['state_id' => 49, 'city' => 'Mount Hope'],
                ['state_id' => 49, 'city' => 'Oak Hill'],
                ['state_id' => 49, 'city' => 'Pax'],
                ['state_id' => 49, 'city' => 'Prince'],
                ['state_id' => 49, 'city' => 'Scarbro'],
                ['state_id' => 49, 'city' => 'Thurmond'],
                ['state_id' => 49, 'city' => 'Victor'],
                ['state_id' => 49, 'city' => 'Winona'],
                ['state_id' => 49, 'city' => 'Meadow Bridge'],
                ['state_id' => 49, 'city' => 'Spring Dale'],
                ['state_id' => 49, 'city' => 'Nallen'],
                ['state_id' => 49, 'city' => 'Normantown'],
                ['state_id' => 49, 'city' => 'Coxs Mills'],
                ['state_id' => 49, 'city' => 'Glenville'],
                ['state_id' => 49, 'city' => 'Linn'],
                ['state_id' => 49, 'city' => 'Sand Fork'],
                ['state_id' => 49, 'city' => 'Troy'],
                ['state_id' => 49, 'city' => 'Cedarville'],
                ['state_id' => 49, 'city' => 'Rosedale'],
                ['state_id' => 49, 'city' => 'Shock'],
                ['state_id' => 49, 'city' => 'Bayard'],
                ['state_id' => 49, 'city' => 'Gormania'],
                ['state_id' => 49, 'city' => 'Lahmansville'],
                ['state_id' => 49, 'city' => 'Mount Storm'],
                ['state_id' => 49, 'city' => 'Maysville'],
                ['state_id' => 49, 'city' => 'Petersburg'],
                ['state_id' => 49, 'city' => 'Cabins'],
                ['state_id' => 49, 'city' => 'Lewisburg'],
                ['state_id' => 49, 'city' => 'Fairlea'],
                ['state_id' => 49, 'city' => 'Alderson'],
                ['state_id' => 49, 'city' => 'Asbury'],
                ['state_id' => 49, 'city' => 'Caldwell'],
                ['state_id' => 49, 'city' => 'Crawley'],
                ['state_id' => 49, 'city' => 'Frankford'],
                ['state_id' => 49, 'city' => 'Grassy Meadows'],
                ['state_id' => 49, 'city' => 'Maxwelton'],
                ['state_id' => 49, 'city' => 'Renick'],
                ['state_id' => 49, 'city' => 'Ronceverte'],
                ['state_id' => 49, 'city' => 'Smoot'],
                ['state_id' => 49, 'city' => 'White Sulphur Springs'],
                ['state_id' => 49, 'city' => 'Williamsburg'],
                ['state_id' => 49, 'city' => 'Charmco'],
                ['state_id' => 49, 'city' => 'Rainelle'],
                ['state_id' => 49, 'city' => 'Leslie'],
                ['state_id' => 49, 'city' => 'Quinwood'],
                ['state_id' => 49, 'city' => 'Rupert'],
                ['state_id' => 49, 'city' => 'Levels'],
                ['state_id' => 49, 'city' => 'Points'],
                ['state_id' => 49, 'city' => 'Slanesville'],
                ['state_id' => 49, 'city' => 'Augusta'],
                ['state_id' => 49, 'city' => 'Capon Bridge'],
                ['state_id' => 49, 'city' => 'Delray'],
                ['state_id' => 49, 'city' => 'Green Spring'],
                ['state_id' => 49, 'city' => 'Rio'],
                ['state_id' => 49, 'city' => 'Romney'],
                ['state_id' => 49, 'city' => 'Shanks'],
                ['state_id' => 49, 'city' => 'Springfield'],
                ['state_id' => 49, 'city' => 'High View'],
                ['state_id' => 49, 'city' => 'Bloomery'],
                ['state_id' => 49, 'city' => 'Capon Springs'],
                ['state_id' => 49, 'city' => 'Purgitsville'],
                ['state_id' => 49, 'city' => 'Yellow Spring'],
                ['state_id' => 49, 'city' => 'Chester'],
                ['state_id' => 49, 'city' => 'New Cumberland'],
                ['state_id' => 49, 'city' => 'Newell'],
                ['state_id' => 49, 'city' => 'New Manchester'],
                ['state_id' => 49, 'city' => 'Weirton'],
                ['state_id' => 49, 'city' => 'Baker'],
                ['state_id' => 49, 'city' => 'Lost City'],
                ['state_id' => 49, 'city' => 'Mathias'],
                ['state_id' => 49, 'city' => 'Fisher'],
                ['state_id' => 49, 'city' => 'Moorefield'],
                ['state_id' => 49, 'city' => 'Milam'],
                ['state_id' => 49, 'city' => 'Old Fields'],
                ['state_id' => 49, 'city' => 'Wardensville'],
                ['state_id' => 49, 'city' => 'Clarksburg'],
                ['state_id' => 49, 'city' => 'Anmoore'],
                ['state_id' => 49, 'city' => 'Bridgeport'],
                ['state_id' => 49, 'city' => 'Gypsy'],
                ['state_id' => 49, 'city' => 'Haywood'],
                ['state_id' => 49, 'city' => 'Hepzibah'],
                ['state_id' => 49, 'city' => 'Lost Creek'],
                ['state_id' => 49, 'city' => 'Lumberport'],
                ['state_id' => 49, 'city' => 'Meadowbrook'],
                ['state_id' => 49, 'city' => 'Mount Clare'],
                ['state_id' => 49, 'city' => 'Reynoldsville'],
                ['state_id' => 49, 'city' => 'Salem'],
                ['state_id' => 49, 'city' => 'Shinnston'],
                ['state_id' => 49, 'city' => 'Spelter'],
                ['state_id' => 49, 'city' => 'Wallace'],
                ['state_id' => 49, 'city' => 'West Milford'],
                ['state_id' => 49, 'city' => 'Wyatt'],
                ['state_id' => 49, 'city' => 'Enterprise'],
                ['state_id' => 49, 'city' => 'Advent'],
                ['state_id' => 49, 'city' => 'Cottageville'],
                ['state_id' => 49, 'city' => 'Evans'],
                ['state_id' => 49, 'city' => 'Gay'],
                ['state_id' => 49, 'city' => 'Given'],
                ['state_id' => 49, 'city' => 'Kenna'],
                ['state_id' => 49, 'city' => 'Le Roy'],
                ['state_id' => 49, 'city' => 'Millwood'],
                ['state_id' => 49, 'city' => 'Mount Alto'],
                ['state_id' => 49, 'city' => 'Ripley'],
                ['state_id' => 49, 'city' => 'Sandyville'],
                ['state_id' => 49, 'city' => 'Ravenswood'],
                ['state_id' => 49, 'city' => 'Bakerton'],
                ['state_id' => 49, 'city' => 'Charles Town'],
                ['state_id' => 49, 'city' => 'Halltown'],
                ['state_id' => 49, 'city' => 'Harpers Ferry'],
                ['state_id' => 49, 'city' => 'Kearneysville'],
                ['state_id' => 49, 'city' => 'Millville'],
                ['state_id' => 49, 'city' => 'Ranson'],
                ['state_id' => 49, 'city' => 'Rippon'],
                ['state_id' => 49, 'city' => 'Shenandoah Junction'],
                ['state_id' => 49, 'city' => 'Shepherdstown'],
                ['state_id' => 49, 'city' => 'Summit Point'],
                ['state_id' => 49, 'city' => 'Alum Creek'],
                ['state_id' => 49, 'city' => 'Belle'],
                ['state_id' => 49, 'city' => 'Blount'],
                ['state_id' => 49, 'city' => 'Blue Creek'],
                ['state_id' => 49, 'city' => 'Cabin Creek'],
                ['state_id' => 49, 'city' => 'Cedar Grove'],
                ['state_id' => 49, 'city' => 'Clendenin'],
                ['state_id' => 49, 'city' => 'Dawes'],
                ['state_id' => 49, 'city' => 'Drybranch'],
                ['state_id' => 49, 'city' => 'Dunbar'],
                ['state_id' => 49, 'city' => 'East Bank'],
                ['state_id' => 49, 'city' => 'Elkview'],
                ['state_id' => 49, 'city' => 'Eskdale'],
                ['state_id' => 49, 'city' => 'Falling Rock'],
                ['state_id' => 49, 'city' => 'Gallagher'],
                ['state_id' => 49, 'city' => 'Glasgow'],
                ['state_id' => 49, 'city' => 'Handley'],
                ['state_id' => 49, 'city' => 'Hansford'],
                ['state_id' => 49, 'city' => 'Hernshaw'],
                ['state_id' => 49, 'city' => 'Hugheston'],
                ['state_id' => 49, 'city' => 'Institute'],
                ['state_id' => 49, 'city' => 'London'],
                ['state_id' => 49, 'city' => 'Mammoth'],
                ['state_id' => 49, 'city' => 'Miami'],
                ['state_id' => 49, 'city' => 'Nitro'],
                ['state_id' => 49, 'city' => 'Pinch'],
                ['state_id' => 49, 'city' => 'Pond Gap'],
                ['state_id' => 49, 'city' => 'Pratt'],
                ['state_id' => 49, 'city' => 'Saint Albans'],
                ['state_id' => 49, 'city' => 'Tad'],
                ['state_id' => 49, 'city' => 'Tornado'],
                ['state_id' => 49, 'city' => 'Winifrede'],
                ['state_id' => 49, 'city' => 'Charleston'],
                ['state_id' => 49, 'city' => 'South Charleston'],
                ['state_id' => 49, 'city' => 'Alum Bridge'],
                ['state_id' => 49, 'city' => 'Camden'],
                ['state_id' => 49, 'city' => 'Crawford'],
                ['state_id' => 49, 'city' => 'Horner'],
                ['state_id' => 49, 'city' => 'Ireland'],
                ['state_id' => 49, 'city' => 'Jane Lew'],
                ['state_id' => 49, 'city' => 'Orlando'],
                ['state_id' => 49, 'city' => 'Walkersville'],
                ['state_id' => 49, 'city' => 'Weston'],
                ['state_id' => 49, 'city' => 'Alkol'],
                ['state_id' => 49, 'city' => 'Branchland'],
                ['state_id' => 49, 'city' => 'Griffithsville'],
                ['state_id' => 49, 'city' => 'Hamlin'],
                ['state_id' => 49, 'city' => 'Harts'],
                ['state_id' => 49, 'city' => 'Midkiff'],
                ['state_id' => 49, 'city' => 'Myra'],
                ['state_id' => 49, 'city' => 'Ranger'],
                ['state_id' => 49, 'city' => 'Sod'],
                ['state_id' => 49, 'city' => 'Spurlockville'],
                ['state_id' => 49, 'city' => 'Sumerco'],
                ['state_id' => 49, 'city' => 'West Hamlin'],
                ['state_id' => 49, 'city' => 'Woodville'],
                ['state_id' => 49, 'city' => 'Yawkey'],
                ['state_id' => 49, 'city' => 'Blair'],
                ['state_id' => 49, 'city' => 'Clothier'],
                ['state_id' => 49, 'city' => 'Ethel'],
                ['state_id' => 49, 'city' => 'Lake'],
                ['state_id' => 49, 'city' => 'Sharples'],
                ['state_id' => 49, 'city' => 'Big Creek'],
                ['state_id' => 49, 'city' => 'Chapmanville'],
                ['state_id' => 49, 'city' => 'Pecks Mill'],
                ['state_id' => 49, 'city' => 'Logan'],
                ['state_id' => 49, 'city' => 'Accoville'],
                ['state_id' => 49, 'city' => 'Amherstdale'],
                ['state_id' => 49, 'city' => 'Bruno'],
                ['state_id' => 49, 'city' => 'Chauncey'],
                ['state_id' => 49, 'city' => 'Cora'],
                ['state_id' => 49, 'city' => 'Davin'],
                ['state_id' => 49, 'city' => 'Henlawson'],
                ['state_id' => 49, 'city' => 'Holden'],
                ['state_id' => 49, 'city' => 'Kistler'],
                ['state_id' => 49, 'city' => 'Lorado'],
                ['state_id' => 49, 'city' => 'Lyburn'],
                ['state_id' => 49, 'city' => 'Mallory'],
                ['state_id' => 49, 'city' => 'Man'],
                ['state_id' => 49, 'city' => 'Mount Gay'],
                ['state_id' => 49, 'city' => 'Omar'],
                ['state_id' => 49, 'city' => 'Peach Creek'],
                ['state_id' => 49, 'city' => 'Sarah Ann'],
                ['state_id' => 49, 'city' => 'Stollings'],
                ['state_id' => 49, 'city' => 'Switzer'],
                ['state_id' => 49, 'city' => 'Verdunville'],
                ['state_id' => 49, 'city' => 'Whitman'],
                ['state_id' => 49, 'city' => 'Wilkinson'],
                ['state_id' => 49, 'city' => 'Yolyn'],
                ['state_id' => 49, 'city' => 'Welch'],
                ['state_id' => 49, 'city' => 'Anawalt'],
                ['state_id' => 49, 'city' => 'Avondale'],
                ['state_id' => 49, 'city' => 'Bartley'],
                ['state_id' => 49, 'city' => 'Berwind'],
                ['state_id' => 49, 'city' => 'Big Sandy'],
                ['state_id' => 49, 'city' => 'Bradshaw'],
                ['state_id' => 49, 'city' => 'Cucumber'],
                ['state_id' => 49, 'city' => 'Davy'],
                ['state_id' => 49, 'city' => 'Eckman'],
                ['state_id' => 49, 'city' => 'Elbert'],
                ['state_id' => 49, 'city' => 'Elkhorn'],
                ['state_id' => 49, 'city' => 'Gary'],
                ['state_id' => 49, 'city' => 'Hensley'],
                ['state_id' => 49, 'city' => 'Iaeger'],
                ['state_id' => 49, 'city' => 'Isaban'],
                ['state_id' => 49, 'city' => 'Jenkinjones'],
                ['state_id' => 49, 'city' => 'Jolo'],
                ['state_id' => 49, 'city' => 'Kimball'],
                ['state_id' => 49, 'city' => 'Kyle'],
                ['state_id' => 49, 'city' => 'Maybeury'],
                ['state_id' => 49, 'city' => 'Mohawk'],
                ['state_id' => 49, 'city' => 'Newhall'],
                ['state_id' => 49, 'city' => 'Northfork'],
                ['state_id' => 49, 'city' => 'Pageton'],
                ['state_id' => 49, 'city' => 'Panther'],
                ['state_id' => 49, 'city' => 'Paynesville'],
                ['state_id' => 49, 'city' => 'Premier'],
                ['state_id' => 49, 'city' => 'Raysal'],
                ['state_id' => 49, 'city' => 'Roderfield'],
                ['state_id' => 49, 'city' => 'Squire'],
                ['state_id' => 49, 'city' => 'Switchback'],
                ['state_id' => 49, 'city' => 'Thorpe'],
                ['state_id' => 49, 'city' => 'War'],
                ['state_id' => 49, 'city' => 'Warriormine'],
                ['state_id' => 49, 'city' => 'Wilcoe'],
                ['state_id' => 49, 'city' => 'Fairmont'],
                ['state_id' => 49, 'city' => 'Barrackville'],
                ['state_id' => 49, 'city' => 'Baxter'],
                ['state_id' => 49, 'city' => 'Carolina'],
                ['state_id' => 49, 'city' => 'Colfax'],
                ['state_id' => 49, 'city' => 'Fairview'],
                ['state_id' => 49, 'city' => 'Farmington'],
                ['state_id' => 49, 'city' => 'Four States'],
                ['state_id' => 49, 'city' => 'Grant Town'],
                ['state_id' => 49, 'city' => 'Idamay'],
                ['state_id' => 49, 'city' => 'Kingmont'],
                ['state_id' => 49, 'city' => 'Mannington'],
                ['state_id' => 49, 'city' => 'Metz'],
                ['state_id' => 49, 'city' => 'Montana Mines'],
                ['state_id' => 49, 'city' => 'Rachel'],
                ['state_id' => 49, 'city' => 'Rivesville'],
                ['state_id' => 49, 'city' => 'Worthington'],
                ['state_id' => 49, 'city' => 'Benwood'],
                ['state_id' => 49, 'city' => 'Cameron'],
                ['state_id' => 49, 'city' => 'Dallas'],
                ['state_id' => 49, 'city' => 'Glen Dale'],
                ['state_id' => 49, 'city' => 'Glen Easton'],
                ['state_id' => 49, 'city' => 'Mcmechen'],
                ['state_id' => 49, 'city' => 'Moundsville'],
                ['state_id' => 49, 'city' => 'Proctor'],
                ['state_id' => 49, 'city' => 'Henderson'],
                ['state_id' => 49, 'city' => 'Leon'],
                ['state_id' => 49, 'city' => 'Southside'],
                ['state_id' => 49, 'city' => 'Hartford'],
                ['state_id' => 49, 'city' => 'Letart'],
                ['state_id' => 49, 'city' => 'Mason'],
                ['state_id' => 49, 'city' => 'New Haven'],
                ['state_id' => 49, 'city' => 'West Columbia'],
                ['state_id' => 49, 'city' => 'Apple Grove'],
                ['state_id' => 49, 'city' => 'Ashton'],
                ['state_id' => 49, 'city' => 'Gallipolis Ferry'],
                ['state_id' => 49, 'city' => 'Glenwood'],
                ['state_id' => 49, 'city' => 'Point Pleasant'],
                ['state_id' => 49, 'city' => 'Bluefield'],
                ['state_id' => 49, 'city' => 'Athens'],
                ['state_id' => 49, 'city' => 'Beeson'],
                ['state_id' => 49, 'city' => 'Bramwell'],
                ['state_id' => 49, 'city' => 'Freeman'],
                ['state_id' => 49, 'city' => 'Hiawatha'],
                ['state_id' => 49, 'city' => 'Kegley'],
                ['state_id' => 49, 'city' => 'Kellysville'],
                ['state_id' => 49, 'city' => 'Lashmeet'],
                ['state_id' => 49, 'city' => 'Matoaka'],
                ['state_id' => 49, 'city' => 'Montcalm'],
                ['state_id' => 49, 'city' => 'Nemours'],
                ['state_id' => 49, 'city' => 'Princeton'],
                ['state_id' => 49, 'city' => 'Rock'],
                ['state_id' => 49, 'city' => 'Wolfe'],
                ['state_id' => 49, 'city' => 'Camp Creek'],
                ['state_id' => 49, 'city' => 'Flat Top'],
                ['state_id' => 49, 'city' => 'Spanishburg'],
                ['state_id' => 49, 'city' => 'Lerona'],
                ['state_id' => 49, 'city' => 'Burlington'],
                ['state_id' => 49, 'city' => 'Elk Garden'],
                ['state_id' => 49, 'city' => 'Fort Ashby'],
                ['state_id' => 49, 'city' => 'Keyser'],
                ['state_id' => 49, 'city' => 'New Creek'],
                ['state_id' => 49, 'city' => 'Piedmont'],
                ['state_id' => 49, 'city' => 'Ridgeley'],
                ['state_id' => 49, 'city' => 'Wiley Ford'],
                ['state_id' => 49, 'city' => 'Justice'],
                ['state_id' => 49, 'city' => 'Baisden'],
                ['state_id' => 49, 'city' => 'Gilbert'],
                ['state_id' => 49, 'city' => 'Verner'],
                ['state_id' => 49, 'city' => 'Wharncliffe'],
                ['state_id' => 49, 'city' => 'Williamson'],
                ['state_id' => 49, 'city' => 'Borderland'],
                ['state_id' => 49, 'city' => 'Breeden'],
                ['state_id' => 49, 'city' => 'Chattaroy'],
                ['state_id' => 49, 'city' => 'Delbarton'],
                ['state_id' => 49, 'city' => 'Dingess'],
                ['state_id' => 49, 'city' => 'Edgarton'],
                ['state_id' => 49, 'city' => 'Kermit'],
                ['state_id' => 49, 'city' => 'Lenore'],
                ['state_id' => 49, 'city' => 'Matewan'],
                ['state_id' => 49, 'city' => 'Naugatuck'],
                ['state_id' => 49, 'city' => 'Newtown'],
                ['state_id' => 49, 'city' => 'North Matewan'],
                ['state_id' => 49, 'city' => 'Ragland'],
                ['state_id' => 49, 'city' => 'Rawl'],
                ['state_id' => 49, 'city' => 'Red Jacket'],
                ['state_id' => 49, 'city' => 'Varney'],
                ['state_id' => 49, 'city' => 'Morgantown'],
                ['state_id' => 49, 'city' => 'Blacksville'],
                ['state_id' => 49, 'city' => 'Cassville'],
                ['state_id' => 49, 'city' => 'Dellslow'],
                ['state_id' => 49, 'city' => 'Granville'],
                ['state_id' => 49, 'city' => 'Maidsville'],
                ['state_id' => 49, 'city' => 'Osage'],
                ['state_id' => 49, 'city' => 'Pentress'],
                ['state_id' => 49, 'city' => 'Pursglove'],
                ['state_id' => 49, 'city' => 'Wana'],
                ['state_id' => 49, 'city' => 'Ballard'],
                ['state_id' => 49, 'city' => 'Gap Mills'],
                ['state_id' => 49, 'city' => 'Greenville'],
                ['state_id' => 49, 'city' => 'Lindside'],
                ['state_id' => 49, 'city' => 'Peterstown'],
                ['state_id' => 49, 'city' => 'Secondcreek'],
                ['state_id' => 49, 'city' => 'Sinks Grove'],
                ['state_id' => 49, 'city' => 'Union'],
                ['state_id' => 49, 'city' => 'Waiteville'],
                ['state_id' => 49, 'city' => 'Wayside'],
                ['state_id' => 49, 'city' => 'Wolfcreek'],
                ['state_id' => 49, 'city' => 'Berkeley Springs'],
                ['state_id' => 49, 'city' => 'Great Cacapon'],
                ['state_id' => 49, 'city' => 'Paw Paw'],
                ['state_id' => 49, 'city' => 'Dixie'],
                ['state_id' => 49, 'city' => 'Fenwick'],
                ['state_id' => 49, 'city' => 'Craigsville'],
                ['state_id' => 49, 'city' => 'Richwood'],
                ['state_id' => 49, 'city' => 'Birch River'],
                ['state_id' => 49, 'city' => 'Summersville'],
                ['state_id' => 49, 'city' => 'Belva'],
                ['state_id' => 49, 'city' => 'Calvin'],
                ['state_id' => 49, 'city' => 'Canvas'],
                ['state_id' => 49, 'city' => 'Drennen'],
                ['state_id' => 49, 'city' => 'Gilboa'],
                ['state_id' => 49, 'city' => 'Keslers Cross Lanes'],
                ['state_id' => 49, 'city' => 'Leivasy'],
                ['state_id' => 49, 'city' => 'Mount Lookout'],
                ['state_id' => 49, 'city' => 'Mount Nebo'],
                ['state_id' => 49, 'city' => 'Nettie'],
                ['state_id' => 49, 'city' => 'Pool'],
                ['state_id' => 49, 'city' => 'Swiss'],
                ['state_id' => 49, 'city' => 'Tioga'],
                ['state_id' => 49, 'city' => 'Wheeling'],
                ['state_id' => 49, 'city' => 'Triadelphia'],
                ['state_id' => 49, 'city' => 'Valley Grove'],
                ['state_id' => 49, 'city' => 'West Liberty'],
                ['state_id' => 49, 'city' => 'Brandywine'],
                ['state_id' => 49, 'city' => 'Circleville'],
                ['state_id' => 49, 'city' => 'Franklin'],
                ['state_id' => 49, 'city' => 'Riverton'],
                ['state_id' => 49, 'city' => 'Sugar Grove'],
                ['state_id' => 49, 'city' => 'Upper Tract'],
                ['state_id' => 49, 'city' => 'Seneca Rocks'],
                ['state_id' => 49, 'city' => 'Onego'],
                ['state_id' => 49, 'city' => 'Belmont'],
                ['state_id' => 49, 'city' => 'Saint Marys'],
                ['state_id' => 49, 'city' => 'Arbovale'],
                ['state_id' => 49, 'city' => 'Bartow'],
                ['state_id' => 49, 'city' => 'Buckeye'],
                ['state_id' => 49, 'city' => 'Cass'],
                ['state_id' => 49, 'city' => 'Dunmore'],
                ['state_id' => 49, 'city' => 'Green Bank'],
                ['state_id' => 49, 'city' => 'Hillsboro'],
                ['state_id' => 49, 'city' => 'Marlinton'],
                ['state_id' => 49, 'city' => 'Snowshoe'],
                ['state_id' => 49, 'city' => 'Durbin'],
                ['state_id' => 49, 'city' => 'Slatyfork'],
                ['state_id' => 49, 'city' => 'Independence'],
                ['state_id' => 49, 'city' => 'Newburg'],
                ['state_id' => 49, 'city' => 'Rowlesburg'],
                ['state_id' => 49, 'city' => 'Tunnelton'],
                ['state_id' => 49, 'city' => 'Albright'],
                ['state_id' => 49, 'city' => 'Arthurdale'],
                ['state_id' => 49, 'city' => 'Bretz'],
                ['state_id' => 49, 'city' => 'Bruceton Mills'],
                ['state_id' => 49, 'city' => 'Kingwood'],
                ['state_id' => 49, 'city' => 'Masontown'],
                ['state_id' => 49, 'city' => 'Reedsville'],
                ['state_id' => 49, 'city' => 'Aurora'],
                ['state_id' => 49, 'city' => 'Eglon'],
                ['state_id' => 49, 'city' => 'Terra Alta'],
                ['state_id' => 49, 'city' => 'Bancroft'],
                ['state_id' => 49, 'city' => 'Buffalo'],
                ['state_id' => 49, 'city' => 'Eleanor'],
                ['state_id' => 49, 'city' => 'Fraziers Bottom'],
                ['state_id' => 49, 'city' => 'Hometown'],
                ['state_id' => 49, 'city' => 'Liberty'],
                ['state_id' => 49, 'city' => 'Poca'],
                ['state_id' => 49, 'city' => 'Red House'],
                ['state_id' => 49, 'city' => 'Winfield'],
                ['state_id' => 49, 'city' => 'Hurricane'],
                ['state_id' => 49, 'city' => 'Scott Depot'],
                ['state_id' => 49, 'city' => 'Teays'],
                ['state_id' => 49, 'city' => 'Arnett'],
                ['state_id' => 49, 'city' => 'Artie'],
                ['state_id' => 49, 'city' => 'Clear Creek'],
                ['state_id' => 49, 'city' => 'Colcord'],
                ['state_id' => 49, 'city' => 'Dorothy'],
                ['state_id' => 49, 'city' => 'Dry Creek'],
                ['state_id' => 49, 'city' => 'Naoma'],
                ['state_id' => 49, 'city' => 'Rock Creek'],
                ['state_id' => 49, 'city' => 'Saxon'],
                ['state_id' => 49, 'city' => 'Beckley'],
                ['state_id' => 49, 'city' => 'Beaver'],
                ['state_id' => 49, 'city' => 'Bolt'],
                ['state_id' => 49, 'city' => 'Bradley'],
                ['state_id' => 49, 'city' => 'Coal City'],
                ['state_id' => 49, 'city' => 'Cool Ridge'],
                ['state_id' => 49, 'city' => 'Crab Orchard'],
                ['state_id' => 49, 'city' => 'Daniels'],
                ['state_id' => 49, 'city' => 'Eccles'],
                ['state_id' => 49, 'city' => 'Fairdale'],
                ['state_id' => 49, 'city' => 'Ghent'],
                ['state_id' => 49, 'city' => 'Glen Daniel'],
                ['state_id' => 49, 'city' => 'Glen White'],
                ['state_id' => 49, 'city' => 'Harper'],
                ['state_id' => 49, 'city' => 'Helen'],
                ['state_id' => 49, 'city' => 'Josephine'],
                ['state_id' => 49, 'city' => 'Lanark'],
                ['state_id' => 49, 'city' => 'Lester'],
                ['state_id' => 49, 'city' => 'Mabscott'],
                ['state_id' => 49, 'city' => 'Mac Arthur'],
                ['state_id' => 49, 'city' => 'Midway'],
                ['state_id' => 49, 'city' => 'Odd'],
                ['state_id' => 49, 'city' => 'Piney View'],
                ['state_id' => 49, 'city' => 'Princewick'],
                ['state_id' => 49, 'city' => 'Prosperity'],
                ['state_id' => 49, 'city' => 'Raleigh'],
                ['state_id' => 49, 'city' => 'Rhodell'],
                ['state_id' => 49, 'city' => 'Shady Spring'],
                ['state_id' => 49, 'city' => 'Skelton'],
                ['state_id' => 49, 'city' => 'Slab Fork'],
                ['state_id' => 49, 'city' => 'Sophia'],
                ['state_id' => 49, 'city' => 'Stanaford'],
                ['state_id' => 49, 'city' => 'Surveyor'],
                ['state_id' => 49, 'city' => 'White Oak'],
                ['state_id' => 49, 'city' => 'Helvetia'],
                ['state_id' => 49, 'city' => 'Pickens'],
                ['state_id' => 49, 'city' => 'Elkins'],
                ['state_id' => 49, 'city' => 'Beverly'],
                ['state_id' => 49, 'city' => 'Bowden'],
                ['state_id' => 49, 'city' => 'Coalton'],
                ['state_id' => 49, 'city' => 'Dailey'],
                ['state_id' => 49, 'city' => 'Dryfork'],
                ['state_id' => 49, 'city' => 'Ellamore'],
                ['state_id' => 49, 'city' => 'Glady'],
                ['state_id' => 49, 'city' => 'Harman'],
                ['state_id' => 49, 'city' => 'Huttonsville'],
                ['state_id' => 49, 'city' => 'Kerens'],
                ['state_id' => 49, 'city' => 'Mabie'],
                ['state_id' => 49, 'city' => 'Mill Creek'],
                ['state_id' => 49, 'city' => 'Monterville'],
                ['state_id' => 49, 'city' => 'Montrose'],
                ['state_id' => 49, 'city' => 'Norton'],
                ['state_id' => 49, 'city' => 'Valley Bend'],
                ['state_id' => 49, 'city' => 'Valley Head'],
                ['state_id' => 49, 'city' => 'Whitmer'],
                ['state_id' => 49, 'city' => 'Macfarlan'],
                ['state_id' => 49, 'city' => 'Petroleum'],
                ['state_id' => 49, 'city' => 'Smithville'],
                ['state_id' => 49, 'city' => 'Auburn'],
                ['state_id' => 49, 'city' => 'Berea'],
                ['state_id' => 49, 'city' => 'Cairo'],
                ['state_id' => 49, 'city' => 'Ellenboro'],
                ['state_id' => 49, 'city' => 'Harrisville'],
                ['state_id' => 49, 'city' => 'Pennsboro'],
                ['state_id' => 49, 'city' => 'Pullman'],
                ['state_id' => 49, 'city' => 'Amma'],
                ['state_id' => 49, 'city' => 'Gandeeville'],
                ['state_id' => 49, 'city' => 'Left Hand'],
                ['state_id' => 49, 'city' => 'Looneyville'],
                ['state_id' => 49, 'city' => 'Newton'],
                ['state_id' => 49, 'city' => 'Reedy'],
                ['state_id' => 49, 'city' => 'Spencer'],
                ['state_id' => 49, 'city' => 'Walton'],
                ['state_id' => 49, 'city' => 'Forest Hill'],
                ['state_id' => 49, 'city' => 'Pence Springs'],
                ['state_id' => 49, 'city' => 'Talcott'],
                ['state_id' => 49, 'city' => 'Hinton'],
                ['state_id' => 49, 'city' => 'Green Sulphur Springs'],
                ['state_id' => 49, 'city' => 'Jumping Branch'],
                ['state_id' => 49, 'city' => 'Meadow Creek'],
                ['state_id' => 49, 'city' => 'Nimitz'],
                ['state_id' => 49, 'city' => 'Pipestem'],
                ['state_id' => 49, 'city' => 'Sandstone'],
                ['state_id' => 49, 'city' => 'Flemington'],
                ['state_id' => 49, 'city' => 'Grafton'],
                ['state_id' => 49, 'city' => 'Rosemont'],
                ['state_id' => 49, 'city' => 'Simpson'],
                ['state_id' => 49, 'city' => 'Thornton'],
                ['state_id' => 49, 'city' => 'Davis'],
                ['state_id' => 49, 'city' => 'Hambleton'],
                ['state_id' => 49, 'city' => 'Hendricks'],
                ['state_id' => 49, 'city' => 'Parsons'],
                ['state_id' => 49, 'city' => 'Red Creek'],
                ['state_id' => 49, 'city' => 'Thomas'],
                ['state_id' => 49, 'city' => 'Friendly'],
                ['state_id' => 49, 'city' => 'Middlebourne'],
                ['state_id' => 49, 'city' => 'Sistersville'],
                ['state_id' => 49, 'city' => 'Alma'],
                ['state_id' => 49, 'city' => 'Shirley'],
                ['state_id' => 49, 'city' => 'Buckhannon'],
                ['state_id' => 49, 'city' => 'Adrian'],
                ['state_id' => 49, 'city' => 'Cleveland'],
                ['state_id' => 49, 'city' => 'French Creek'],
                ['state_id' => 49, 'city' => 'Frenchton'],
                ['state_id' => 49, 'city' => 'Kanawha Head'],
                ['state_id' => 49, 'city' => 'Lorentz'],
                ['state_id' => 49, 'city' => 'Rock Cave'],
                ['state_id' => 49, 'city' => 'Selbyville'],
                ['state_id' => 49, 'city' => 'Tallmansville'],
                ['state_id' => 49, 'city' => 'Ceredo'],
                ['state_id' => 49, 'city' => 'Dunlow'],
                ['state_id' => 49, 'city' => 'East Lynn'],
                ['state_id' => 49, 'city' => 'Fort Gay'],
                ['state_id' => 49, 'city' => 'Genoa'],
                ['state_id' => 49, 'city' => 'Kenova'],
                ['state_id' => 49, 'city' => 'Kiahsville'],
                ['state_id' => 49, 'city' => 'Lavalette'],
                ['state_id' => 49, 'city' => 'Prichard'],
                ['state_id' => 49, 'city' => 'Shoals'],
                ['state_id' => 49, 'city' => 'Wayne'],
                ['state_id' => 49, 'city' => 'Crum'],
                ['state_id' => 49, 'city' => 'Wilsondale'],
                ['state_id' => 49, 'city' => 'Erbacon'],
                ['state_id' => 49, 'city' => 'Cowen'],
                ['state_id' => 49, 'city' => 'Camden On Gauley'],
                ['state_id' => 49, 'city' => 'Diana'],
                ['state_id' => 49, 'city' => 'Hacker Valley'],
                ['state_id' => 49, 'city' => 'Upperglade'],
                ['state_id' => 49, 'city' => 'Webster Springs'],
                ['state_id' => 49, 'city' => 'Bergoo'],
                ['state_id' => 49, 'city' => 'New Martinsville'],
                ['state_id' => 49, 'city' => 'Paden City'],
                ['state_id' => 49, 'city' => 'Porters Falls'],
                ['state_id' => 49, 'city' => 'Reader'],
                ['state_id' => 49, 'city' => 'Folsom'],
                ['state_id' => 49, 'city' => 'Jacksonburg'],
                ['state_id' => 49, 'city' => 'Pine Grove'],
                ['state_id' => 49, 'city' => 'Smithfield'],
                ['state_id' => 49, 'city' => 'Big Run'],
                ['state_id' => 49, 'city' => 'Burton'],
                ['state_id' => 49, 'city' => 'Hundred'],
                ['state_id' => 49, 'city' => 'Littleton'],
                ['state_id' => 49, 'city' => 'Brohard'],
                ['state_id' => 49, 'city' => 'Creston'],
                ['state_id' => 49, 'city' => 'Elizabeth'],
                ['state_id' => 49, 'city' => 'Munday'],
                ['state_id' => 49, 'city' => 'Palestine'],
                ['state_id' => 49, 'city' => 'Parkersburg'],
                ['state_id' => 49, 'city' => 'Vienna'],
                ['state_id' => 49, 'city' => 'Mineral Wells'],
                ['state_id' => 49, 'city' => 'Belleville'],
                ['state_id' => 49, 'city' => 'Davisville'],
                ['state_id' => 49, 'city' => 'Rockport'],
                ['state_id' => 49, 'city' => 'Walker'],
                ['state_id' => 49, 'city' => 'Washington'],
                ['state_id' => 49, 'city' => 'Waverly'],
                ['state_id' => 49, 'city' => 'Williamstown'],
                ['state_id' => 49, 'city' => 'Bud'],
                ['state_id' => 49, 'city' => 'Covel'],
                ['state_id' => 49, 'city' => 'Herndon'],
                ['state_id' => 49, 'city' => 'Brenton'],
                ['state_id' => 49, 'city' => 'Clear Fork'],
                ['state_id' => 49, 'city' => 'Coal Mountain'],
                ['state_id' => 49, 'city' => 'Cyclone'],
                ['state_id' => 49, 'city' => 'Fanrock'],
                ['state_id' => 49, 'city' => 'Hanover'],
                ['state_id' => 49, 'city' => 'Ikes Fork'],
                ['state_id' => 49, 'city' => 'Itmann'],
                ['state_id' => 49, 'city' => 'Jesse'],
                ['state_id' => 49, 'city' => 'Kopperston'],
                ['state_id' => 49, 'city' => 'Lynco'],
                ['state_id' => 49, 'city' => 'Marianna'],
                ['state_id' => 49, 'city' => 'Matheny'],
                ['state_id' => 49, 'city' => 'New Richmond'],
                ['state_id' => 49, 'city' => 'North Spring'],
                ['state_id' => 49, 'city' => 'Oceana'],
                ['state_id' => 49, 'city' => 'Pineville'],
                ['state_id' => 49, 'city' => 'Rock View'],
                ['state_id' => 49, 'city' => 'Simon'],
                ['state_id' => 49, 'city' => 'Wyoming'],
                ['state_id' => 49, 'city' => 'Allen Junction'],
                ['state_id' => 49, 'city' => 'Amigo'],
                ['state_id' => 49, 'city' => 'Corinne'],
                ['state_id' => 49, 'city' => 'Glen Fork'],
                ['state_id' => 49, 'city' => 'Glen Rogers'],
                ['state_id' => 49, 'city' => 'Maben'],
                ['state_id' => 49, 'city' => 'Mc Graws'],
                ['state_id' => 49, 'city' => 'Saulsville'],
                ['state_id' => 49, 'city' => 'Mullens'],
                ['state_id' => 49, 'city' => 'Ravencliff'],
                ['state_id' => 49, 'city' => 'Sabine'],
                ['state_id' => 49, 'city' => 'Stephenson'],
                ['state_id' => 49, 'city' => 'Wyco', 'state_id' => 50]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
