<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State21TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MD - Maryland.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 21, 'city' => 'Cumberland'],
                ['state_id' => 21, 'city' => 'Barton'],
                ['state_id' => 21, 'city' => 'Corriganville'],
                ['state_id' => 21, 'city' => 'Eckhart Mines'],
                ['state_id' => 21, 'city' => 'Ellerslie'],
                ['state_id' => 21, 'city' => 'Flintstone'],
                ['state_id' => 21, 'city' => 'Frostburg'],
                ['state_id' => 21, 'city' => 'Lonaconing'],
                ['state_id' => 21, 'city' => 'Luke'],
                ['state_id' => 21, 'city' => 'Midland'],
                ['state_id' => 21, 'city' => 'Midlothian'],
                ['state_id' => 21, 'city' => 'Mount Savage'],
                ['state_id' => 21, 'city' => 'Oldtown'],
                ['state_id' => 21, 'city' => 'Pinto'],
                ['state_id' => 21, 'city' => 'Rawlings'],
                ['state_id' => 21, 'city' => 'Spring Gap'],
                ['state_id' => 21, 'city' => 'Westernport'],
                ['state_id' => 21, 'city' => 'Little Orleans'],
                ['state_id' => 21, 'city' => 'Lothian'],
                ['state_id' => 21, 'city' => 'Laurel'],
                ['state_id' => 21, 'city' => 'Churchton'],
                ['state_id' => 21, 'city' => 'Deale'],
                ['state_id' => 21, 'city' => 'Fort George G Meade'],
                ['state_id' => 21, 'city' => 'Friendship'],
                ['state_id' => 21, 'city' => 'Shady Side'],
                ['state_id' => 21, 'city' => 'Galesville'],
                ['state_id' => 21, 'city' => 'Harwood'],
                ['state_id' => 21, 'city' => 'West River'],
                ['state_id' => 21, 'city' => 'Tracys Landing'],
                ['state_id' => 21, 'city' => 'Arnold'],
                ['state_id' => 21, 'city' => 'Crownsville'],
                ['state_id' => 21, 'city' => 'Davidsonville'],
                ['state_id' => 21, 'city' => 'Edgewater'],
                ['state_id' => 21, 'city' => 'Gambrills'],
                ['state_id' => 21, 'city' => 'Gibson Island'],
                ['state_id' => 21, 'city' => 'Glen Burnie'],
                ['state_id' => 21, 'city' => 'Hanover'],
                ['state_id' => 21, 'city' => 'Harmans'],
                ['state_id' => 21, 'city' => 'Linthicum Heights'],
                ['state_id' => 21, 'city' => 'Mayo'],
                ['state_id' => 21, 'city' => 'Millersville'],
                ['state_id' => 21, 'city' => 'Odenton'],
                ['state_id' => 21, 'city' => 'Crofton'],
                ['state_id' => 21, 'city' => 'Pasadena'],
                ['state_id' => 21, 'city' => 'Riva'],
                ['state_id' => 21, 'city' => 'Severn'],
                ['state_id' => 21, 'city' => 'Severna Park'],
                ['state_id' => 21, 'city' => 'Brooklyn'],
                ['state_id' => 21, 'city' => 'Curtis Bay'],
                ['state_id' => 21, 'city' => 'Baltimore'],
                ['state_id' => 21, 'city' => 'Annapolis'],
                ['state_id' => 21, 'city' => 'Baldwin'],
                ['state_id' => 21, 'city' => 'Boring'],
                ['state_id' => 21, 'city' => 'Brooklandville'],
                ['state_id' => 21, 'city' => 'Butler'],
                ['state_id' => 21, 'city' => 'Chase'],
                ['state_id' => 21, 'city' => 'Cockeysville'],
                ['state_id' => 21, 'city' => 'Hunt Valley'],
                ['state_id' => 21, 'city' => 'Fork'],
                ['state_id' => 21, 'city' => 'Fort Howard'],
                ['state_id' => 21, 'city' => 'Freeland'],
                ['state_id' => 21, 'city' => 'Glen Arm'],
                ['state_id' => 21, 'city' => 'Glyndon'],
                ['state_id' => 21, 'city' => 'Hydes'],
                ['state_id' => 21, 'city' => 'Kingsville'],
                ['state_id' => 21, 'city' => 'Long Green'],
                ['state_id' => 21, 'city' => 'Lutherville Timonium'],
                ['state_id' => 21, 'city' => 'Maryland Line'],
                ['state_id' => 21, 'city' => 'Monkton'],
                ['state_id' => 21, 'city' => 'Owings Mills'],
                ['state_id' => 21, 'city' => 'Parkton'],
                ['state_id' => 21, 'city' => 'Perry Hall'],
                ['state_id' => 21, 'city' => 'Phoenix'],
                ['state_id' => 21, 'city' => 'Randallstown'],
                ['state_id' => 21, 'city' => 'Reisterstown'],
                ['state_id' => 21, 'city' => 'Riderwood'],
                ['state_id' => 21, 'city' => 'Sparks Glencoe'],
                ['state_id' => 21, 'city' => 'Stevenson'],
                ['state_id' => 21, 'city' => 'Upperco'],
                ['state_id' => 21, 'city' => 'Upper Falls'],
                ['state_id' => 21, 'city' => 'White Marsh'],
                ['state_id' => 21, 'city' => 'Woodstock'],
                ['state_id' => 21, 'city' => 'Towson'],
                ['state_id' => 21, 'city' => 'Gwynn Oak'],
                ['state_id' => 21, 'city' => 'Pikesville'],
                ['state_id' => 21, 'city' => 'Sparrows Point'],
                ['state_id' => 21, 'city' => 'Middle River'],
                ['state_id' => 21, 'city' => 'Essex'],
                ['state_id' => 21, 'city' => 'Dundalk'],
                ['state_id' => 21, 'city' => 'Halethorpe'],
                ['state_id' => 21, 'city' => 'Catonsville'],
                ['state_id' => 21, 'city' => 'Parkville'],
                ['state_id' => 21, 'city' => 'Nottingham'],
                ['state_id' => 21, 'city' => 'Rosedale'],
                ['state_id' => 21, 'city' => 'Windsor Mill'],
                ['state_id' => 21, 'city' => 'Barstow'],
                ['state_id' => 21, 'city' => 'Broomes Island'],
                ['state_id' => 21, 'city' => 'Dowell'],
                ['state_id' => 21, 'city' => 'Huntingtown'],
                ['state_id' => 21, 'city' => 'Lusby'],
                ['state_id' => 21, 'city' => 'Port Republic'],
                ['state_id' => 21, 'city' => 'Prince Frederick'],
                ['state_id' => 21, 'city' => 'Saint Leonard'],
                ['state_id' => 21, 'city' => 'Solomons'],
                ['state_id' => 21, 'city' => 'Sunderland'],
                ['state_id' => 21, 'city' => 'North Beach'],
                ['state_id' => 21, 'city' => 'Chesapeake Beach'],
                ['state_id' => 21, 'city' => 'Owings'],
                ['state_id' => 21, 'city' => 'Dunkirk'],
                ['state_id' => 21, 'city' => 'Bethlehem'],
                ['state_id' => 21, 'city' => 'Denton'],
                ['state_id' => 21, 'city' => 'Federalsburg'],
                ['state_id' => 21, 'city' => 'Goldsboro'],
                ['state_id' => 21, 'city' => 'Greensboro'],
                ['state_id' => 21, 'city' => 'Henderson'],
                ['state_id' => 21, 'city' => 'Hillsboro'],
                ['state_id' => 21, 'city' => 'Marydel'],
                ['state_id' => 21, 'city' => 'Preston'],
                ['state_id' => 21, 'city' => 'Ridgely'],
                ['state_id' => 21, 'city' => 'Templeville'],
                ['state_id' => 21, 'city' => 'Finksburg'],
                ['state_id' => 21, 'city' => 'Hampstead'],
                ['state_id' => 21, 'city' => 'Lineboro'],
                ['state_id' => 21, 'city' => 'Manchester'],
                ['state_id' => 21, 'city' => 'Marriottsville'],
                ['state_id' => 21, 'city' => 'Westminster'],
                ['state_id' => 21, 'city' => 'Keymar'],
                ['state_id' => 21, 'city' => 'New Windsor'],
                ['state_id' => 21, 'city' => 'Sykesville'],
                ['state_id' => 21, 'city' => 'Taneytown'],
                ['state_id' => 21, 'city' => 'Union Bridge'],
                ['state_id' => 21, 'city' => 'Woodbine'],
                ['state_id' => 21, 'city' => 'North East'],
                ['state_id' => 21, 'city' => 'Perry Point'],
                ['state_id' => 21, 'city' => 'Perryville'],
                ['state_id' => 21, 'city' => 'Port Deposit'],
                ['state_id' => 21, 'city' => 'Rising Sun'],
                ['state_id' => 21, 'city' => 'Warwick'],
                ['state_id' => 21, 'city' => 'Cecilton'],
                ['state_id' => 21, 'city' => 'Charlestown'],
                ['state_id' => 21, 'city' => 'Chesapeake City'],
                ['state_id' => 21, 'city' => 'Childs'],
                ['state_id' => 21, 'city' => 'Colora'],
                ['state_id' => 21, 'city' => 'Conowingo'],
                ['state_id' => 21, 'city' => 'Earleville'],
                ['state_id' => 21, 'city' => 'Elk Mills'],
                ['state_id' => 21, 'city' => 'Elkton'],
                ['state_id' => 21, 'city' => 'Georgetown'],
                ['state_id' => 21, 'city' => 'Waldorf'],
                ['state_id' => 21, 'city' => 'Bel Alton'],
                ['state_id' => 21, 'city' => 'Benedict'],
                ['state_id' => 21, 'city' => 'Bryans Road'],
                ['state_id' => 21, 'city' => 'Bryantown'],
                ['state_id' => 21, 'city' => 'Cobb Island'],
                ['state_id' => 21, 'city' => 'Faulkner'],
                ['state_id' => 21, 'city' => 'Hughesville'],
                ['state_id' => 21, 'city' => 'Indian Head'],
                ['state_id' => 21, 'city' => 'Ironsides'],
                ['state_id' => 21, 'city' => 'Issue'],
                ['state_id' => 21, 'city' => 'La Plata'],
                ['state_id' => 21, 'city' => 'Marbury'],
                ['state_id' => 21, 'city' => 'Mount Victoria'],
                ['state_id' => 21, 'city' => 'Nanjemoy'],
                ['state_id' => 21, 'city' => 'Newburg'],
                ['state_id' => 21, 'city' => 'Pomfret'],
                ['state_id' => 21, 'city' => 'Port Tobacco'],
                ['state_id' => 21, 'city' => 'Rock Point'],
                ['state_id' => 21, 'city' => 'Welcome'],
                ['state_id' => 21, 'city' => 'White Plains'],
                ['state_id' => 21, 'city' => 'Cambridge'],
                ['state_id' => 21, 'city' => 'Church Creek'],
                ['state_id' => 21, 'city' => 'Crapo'],
                ['state_id' => 21, 'city' => 'Crocheron'],
                ['state_id' => 21, 'city' => 'East New Market'],
                ['state_id' => 21, 'city' => 'Fishing Creek'],
                ['state_id' => 21, 'city' => 'Hurlock'],
                ['state_id' => 21, 'city' => 'Madison'],
                ['state_id' => 21, 'city' => 'Rhodesdale'],
                ['state_id' => 21, 'city' => 'Secretary'],
                ['state_id' => 21, 'city' => 'Taylors Island'],
                ['state_id' => 21, 'city' => 'Toddville'],
                ['state_id' => 21, 'city' => 'Wingate'],
                ['state_id' => 21, 'city' => 'Woolford'],
                ['state_id' => 21, 'city' => 'Linkwood'],
                ['state_id' => 21, 'city' => 'Vienna'],
                ['state_id' => 21, 'city' => 'Frederick'],
                ['state_id' => 21, 'city' => 'Adamstown'],
                ['state_id' => 21, 'city' => 'Braddock Heights'],
                ['state_id' => 21, 'city' => 'Brunswick'],
                ['state_id' => 21, 'city' => 'Buckeystown'],
                ['state_id' => 21, 'city' => 'Burkittsville'],
                ['state_id' => 21, 'city' => 'Emmitsburg'],
                ['state_id' => 21, 'city' => 'Ijamsville'],
                ['state_id' => 21, 'city' => 'Jefferson'],
                ['state_id' => 21, 'city' => 'Knoxville'],
                ['state_id' => 21, 'city' => 'Ladiesburg'],
                ['state_id' => 21, 'city' => 'Libertytown'],
                ['state_id' => 21, 'city' => 'Middletown'],
                ['state_id' => 21, 'city' => 'Monrovia'],
                ['state_id' => 21, 'city' => 'Mount Airy'],
                ['state_id' => 21, 'city' => 'Myersville'],
                ['state_id' => 21, 'city' => 'New Market'],
                ['state_id' => 21, 'city' => 'New Midway'],
                ['state_id' => 21, 'city' => 'Point Of Rocks'],
                ['state_id' => 21, 'city' => 'Rocky Ridge'],
                ['state_id' => 21, 'city' => 'Sabillasville'],
                ['state_id' => 21, 'city' => 'Thurmont'],
                ['state_id' => 21, 'city' => 'Tuscarora'],
                ['state_id' => 21, 'city' => 'Unionville'],
                ['state_id' => 21, 'city' => 'Walkersville'],
                ['state_id' => 21, 'city' => 'Woodsboro'],
                ['state_id' => 21, 'city' => 'Accident'],
                ['state_id' => 21, 'city' => 'Bittinger'],
                ['state_id' => 21, 'city' => 'Bloomington'],
                ['state_id' => 21, 'city' => 'Friendsville'],
                ['state_id' => 21, 'city' => 'Grantsville'],
                ['state_id' => 21, 'city' => 'Kitzmiller'],
                ['state_id' => 21, 'city' => 'Mc Henry'],
                ['state_id' => 21, 'city' => 'Oakland'],
                ['state_id' => 21, 'city' => 'Swanton'],
                ['state_id' => 21, 'city' => 'Aberdeen'],
                ['state_id' => 21, 'city' => 'Aberdeen Proving Ground'],
                ['state_id' => 21, 'city' => 'Abingdon'],
                ['state_id' => 21, 'city' => 'Gunpowder'],
                ['state_id' => 21, 'city' => 'Bel Air'],
                ['state_id' => 21, 'city' => 'Belcamp'],
                ['state_id' => 21, 'city' => 'Benson'],
                ['state_id' => 21, 'city' => 'Churchville'],
                ['state_id' => 21, 'city' => 'Darlington'],
                ['state_id' => 21, 'city' => 'Edgewood'],
                ['state_id' => 21, 'city' => 'Fallston'],
                ['state_id' => 21, 'city' => 'Forest Hill'],
                ['state_id' => 21, 'city' => 'Havre De Grace'],
                ['state_id' => 21, 'city' => 'Jarrettsville'],
                ['state_id' => 21, 'city' => 'Joppa'],
                ['state_id' => 21, 'city' => 'Perryman'],
                ['state_id' => 21, 'city' => 'Pylesville'],
                ['state_id' => 21, 'city' => 'Street'],
                ['state_id' => 21, 'city' => 'Whiteford'],
                ['state_id' => 21, 'city' => 'White Hall'],
                ['state_id' => 21, 'city' => 'Dhs'],
                ['state_id' => 21, 'city' => 'Annapolis Junction'],
                ['state_id' => 21, 'city' => 'Fulton'],
                ['state_id' => 21, 'city' => 'Savage'],
                ['state_id' => 21, 'city' => 'Highland'],
                ['state_id' => 21, 'city' => 'Jessup'],
                ['state_id' => 21, 'city' => 'Clarksville'],
                ['state_id' => 21, 'city' => 'Dayton'],
                ['state_id' => 21, 'city' => 'Ellicott City'],
                ['state_id' => 21, 'city' => 'Columbia'],
                ['state_id' => 21, 'city' => 'Elkridge'],
                ['state_id' => 21, 'city' => 'Simpsonville'],
                ['state_id' => 21, 'city' => 'Cooksville'],
                ['state_id' => 21, 'city' => 'Glenelg'],
                ['state_id' => 21, 'city' => 'Glenwood'],
                ['state_id' => 21, 'city' => 'Lisbon'],
                ['state_id' => 21, 'city' => 'West Friendship'],
                ['state_id' => 21, 'city' => 'Betterton'],
                ['state_id' => 21, 'city' => 'Chestertown'],
                ['state_id' => 21, 'city' => 'Galena'],
                ['state_id' => 21, 'city' => 'Kennedyville'],
                ['state_id' => 21, 'city' => 'Massey'],
                ['state_id' => 21, 'city' => 'Millington'],
                ['state_id' => 21, 'city' => 'Rock Hall'],
                ['state_id' => 21, 'city' => 'Still Pond'],
                ['state_id' => 21, 'city' => 'Worton'],
                ['state_id' => 21, 'city' => 'Bethesda'],
                ['state_id' => 21, 'city' => 'Glen Echo'],
                ['state_id' => 21, 'city' => 'Chevy Chase'],
                ['state_id' => 21, 'city' => 'Cabin John'],
                ['state_id' => 21, 'city' => 'Olney'],
                ['state_id' => 21, 'city' => 'Brookeville'],
                ['state_id' => 21, 'city' => 'Poolesville'],
                ['state_id' => 21, 'city' => 'Barnesville'],
                ['state_id' => 21, 'city' => 'Beallsville'],
                ['state_id' => 21, 'city' => 'Boyds'],
                ['state_id' => 21, 'city' => 'Dickerson'],
                ['state_id' => 21, 'city' => 'Rockville'],
                ['state_id' => 21, 'city' => 'Potomac'],
                ['state_id' => 21, 'city' => 'Derwood'],
                ['state_id' => 21, 'city' => 'Sandy Spring'],
                ['state_id' => 21, 'city' => 'Ashton'],
                ['state_id' => 21, 'city' => 'Brinklow'],
                ['state_id' => 21, 'city' => 'Burtonsville'],
                ['state_id' => 21, 'city' => 'Spencerville'],
                ['state_id' => 21, 'city' => 'Clarksburg'],
                ['state_id' => 21, 'city' => 'Damascus'],
                ['state_id' => 21, 'city' => 'Germantown'],
                ['state_id' => 21, 'city' => 'Gaithersburg'],
                ['state_id' => 21, 'city' => 'Washington Grove'],
                ['state_id' => 21, 'city' => 'Montgomery Village'],
                ['state_id' => 21, 'city' => 'Kensington'],
                ['state_id' => 21, 'city' => 'Garrett Park'],
                ['state_id' => 21, 'city' => 'Suburb Maryland Fac'],
                ['state_id' => 21, 'city' => 'Silver Spring'],
                ['state_id' => 21, 'city' => 'Takoma Park'],
                ['state_id' => 21, 'city' => 'Accokeek'],
                ['state_id' => 21, 'city' => 'Aquasco'],
                ['state_id' => 21, 'city' => 'Brandywine'],
                ['state_id' => 21, 'city' => 'Cheltenham'],
                ['state_id' => 21, 'city' => 'Southern Md Facility'],
                ['state_id' => 21, 'city' => 'Lanham'],
                ['state_id' => 21, 'city' => 'Beltsville'],
                ['state_id' => 21, 'city' => 'Bladensburg'],
                ['state_id' => 21, 'city' => 'Mount Rainier'],
                ['state_id' => 21, 'city' => 'Bowie'],
                ['state_id' => 21, 'city' => 'Brentwood'],
                ['state_id' => 21, 'city' => 'Capitol Heights'],
                ['state_id' => 21, 'city' => 'Clinton'],
                ['state_id' => 21, 'city' => 'Riverdale'],
                ['state_id' => 21, 'city' => 'College Park'],
                ['state_id' => 21, 'city' => 'Fort Washington'],
                ['state_id' => 21, 'city' => 'Oxon Hill'],
                ['state_id' => 21, 'city' => 'Suitland'],
                ['state_id' => 21, 'city' => 'District Heights'],
                ['state_id' => 21, 'city' => 'Temple Hills'],
                ['state_id' => 21, 'city' => 'Andrews Air Force Base'],
                ['state_id' => 21, 'city' => 'Greenbelt'],
                ['state_id' => 21, 'city' => 'Glenn Dale'],
                ['state_id' => 21, 'city' => 'Upper Marlboro'],
                ['state_id' => 21, 'city' => 'Hyattsville'],
                ['state_id' => 21, 'city' => 'Barclay'],
                ['state_id' => 21, 'city' => 'Centreville'],
                ['state_id' => 21, 'city' => 'Chester'],
                ['state_id' => 21, 'city' => 'Church Hill'],
                ['state_id' => 21, 'city' => 'Crumpton'],
                ['state_id' => 21, 'city' => 'Grasonville'],
                ['state_id' => 21, 'city' => 'Ingleside'],
                ['state_id' => 21, 'city' => 'Price'],
                ['state_id' => 21, 'city' => 'Queen Anne'],
                ['state_id' => 21, 'city' => 'Queenstown'],
                ['state_id' => 21, 'city' => 'Stevensville'],
                ['state_id' => 21, 'city' => 'Sudlersville'],
                ['state_id' => 21, 'city' => 'Abell'],
                ['state_id' => 21, 'city' => 'Avenue'],
                ['state_id' => 21, 'city' => 'Bushwood'],
                ['state_id' => 21, 'city' => 'California'],
                ['state_id' => 21, 'city' => 'Callaway'],
                ['state_id' => 21, 'city' => 'Chaptico'],
                ['state_id' => 21, 'city' => 'Charlotte Hall'],
                ['state_id' => 21, 'city' => 'Clements'],
                ['state_id' => 21, 'city' => 'Coltons Point'],
                ['state_id' => 21, 'city' => 'Compton'],
                ['state_id' => 21, 'city' => 'Dameron'],
                ['state_id' => 21, 'city' => 'Drayden'],
                ['state_id' => 21, 'city' => 'Great Mills'],
                ['state_id' => 21, 'city' => 'Helen'],
                ['state_id' => 21, 'city' => 'Hollywood'],
                ['state_id' => 21, 'city' => 'Leonardtown'],
                ['state_id' => 21, 'city' => 'Lexington Park'],
                ['state_id' => 21, 'city' => 'Loveville'],
                ['state_id' => 21, 'city' => 'Mechanicsville'],
                ['state_id' => 21, 'city' => 'Morganza'],
                ['state_id' => 21, 'city' => 'Park Hall'],
                ['state_id' => 21, 'city' => 'Patuxent River'],
                ['state_id' => 21, 'city' => 'Piney Point'],
                ['state_id' => 21, 'city' => 'Ridge'],
                ['state_id' => 21, 'city' => 'Saint Inigoes'],
                ['state_id' => 21, 'city' => 'Saint Marys City'],
                ['state_id' => 21, 'city' => 'Scotland'],
                ['state_id' => 21, 'city' => 'Tall Timbers'],
                ['state_id' => 21, 'city' => 'Valley Lee'],
                ['state_id' => 21, 'city' => 'Crisfield'],
                ['state_id' => 21, 'city' => 'Deal Island'],
                ['state_id' => 21, 'city' => 'Ewell'],
                ['state_id' => 21, 'city' => 'Manokin'],
                ['state_id' => 21, 'city' => 'Marion Station'],
                ['state_id' => 21, 'city' => 'Princess Anne'],
                ['state_id' => 21, 'city' => 'Rehobeth'],
                ['state_id' => 21, 'city' => 'Tylerton'],
                ['state_id' => 21, 'city' => 'Upper Fairmount'],
                ['state_id' => 21, 'city' => 'Westover'],
                ['state_id' => 21, 'city' => 'Easton'],
                ['state_id' => 21, 'city' => 'Bozman'],
                ['state_id' => 21, 'city' => 'Claiborne'],
                ['state_id' => 21, 'city' => 'Cordova'],
                ['state_id' => 21, 'city' => 'Mcdaniel'],
                ['state_id' => 21, 'city' => 'Neavitt'],
                ['state_id' => 21, 'city' => 'Newcomb'],
                ['state_id' => 21, 'city' => 'Oxford'],
                ['state_id' => 21, 'city' => 'Royal Oak'],
                ['state_id' => 21, 'city' => 'Saint Michaels'],
                ['state_id' => 21, 'city' => 'Sherwood'],
                ['state_id' => 21, 'city' => 'Tilghman'],
                ['state_id' => 21, 'city' => 'Trappe'],
                ['state_id' => 21, 'city' => 'Wittman'],
                ['state_id' => 21, 'city' => 'Wye Mills'],
                ['state_id' => 21, 'city' => 'Big Pool'],
                ['state_id' => 21, 'city' => 'Boonsboro'],
                ['state_id' => 21, 'city' => 'Brownsville'],
                ['state_id' => 21, 'city' => 'Cascade'],
                ['state_id' => 21, 'city' => 'Cavetown'],
                ['state_id' => 21, 'city' => 'Chewsville'],
                ['state_id' => 21, 'city' => 'Clear Spring'],
                ['state_id' => 21, 'city' => 'Fairplay'],
                ['state_id' => 21, 'city' => 'Funkstown'],
                ['state_id' => 21, 'city' => 'Hagerstown'],
                ['state_id' => 21, 'city' => 'Hancock'],
                ['state_id' => 21, 'city' => 'Keedysville'],
                ['state_id' => 21, 'city' => 'Maugansville'],
                ['state_id' => 21, 'city' => 'Rohrersville'],
                ['state_id' => 21, 'city' => 'Saint James'],
                ['state_id' => 21, 'city' => 'Sharpsburg'],
                ['state_id' => 21, 'city' => 'Smithsburg'],
                ['state_id' => 21, 'city' => 'Williamsport'],
                ['state_id' => 21, 'city' => 'Salisbury'],
                ['state_id' => 21, 'city' => 'Allen'],
                ['state_id' => 21, 'city' => 'Bivalve'],
                ['state_id' => 21, 'city' => 'Fruitland'],
                ['state_id' => 21, 'city' => 'Hebron'],
                ['state_id' => 21, 'city' => 'Mardela Springs'],
                ['state_id' => 21, 'city' => 'Nanticoke'],
                ['state_id' => 21, 'city' => 'Parsonsburg'],
                ['state_id' => 21, 'city' => 'Pittsville'],
                ['state_id' => 21, 'city' => 'Powellville'],
                ['state_id' => 21, 'city' => 'Quantico'],
                ['state_id' => 21, 'city' => 'Sharptown'],
                ['state_id' => 21, 'city' => 'Tyaskin'],
                ['state_id' => 21, 'city' => 'Willards'],
                ['state_id' => 21, 'city' => 'Delmar'],
                ['state_id' => 21, 'city' => 'Berlin'],
                ['state_id' => 21, 'city' => 'Bishopville'],
                ['state_id' => 21, 'city' => 'Eden'],
                ['state_id' => 21, 'city' => 'Girdletree'],
                ['state_id' => 21, 'city' => 'Newark'],
                ['state_id' => 21, 'city' => 'Ocean City'],
                ['state_id' => 21, 'city' => 'Pocomoke City'],
                ['state_id' => 21, 'city' => 'Showell'],
                ['state_id' => 21, 'city' => 'Snow Hill'],
                ['state_id' => 21, 'city' => 'Stockton'],
                ['state_id' => 21, 'city' => 'Whaleyville']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
