<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State31TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MJ - New Jersey.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 31, 'city' => 'Hammonton'],
                ['state_id' => 31, 'city' => 'Absecon'],
                ['state_id' => 31, 'city' => 'Brigantine'],
                ['state_id' => 31, 'city' => 'Cologne'],
                ['state_id' => 31, 'city' => 'Egg Harbor City'],
                ['state_id' => 31, 'city' => 'Elwood'],
                ['state_id' => 31, 'city' => 'Leeds Point'],
                ['state_id' => 31, 'city' => 'Linwood'],
                ['state_id' => 31, 'city' => 'Northfield'],
                ['state_id' => 31, 'city' => 'Oceanville'],
                ['state_id' => 31, 'city' => 'Pleasantville'],
                ['state_id' => 31, 'city' => 'Egg Harbor Township'],
                ['state_id' => 31, 'city' => 'Pomona'],
                ['state_id' => 31, 'city' => 'Port Republic'],
                ['state_id' => 31, 'city' => 'Somers Point'],
                ['state_id' => 31, 'city' => 'Buena'],
                ['state_id' => 31, 'city' => 'Dorothy'],
                ['state_id' => 31, 'city' => 'Estell Manor'],
                ['state_id' => 31, 'city' => 'Landisville'],
                ['state_id' => 31, 'city' => 'Mays Landing'],
                ['state_id' => 31, 'city' => 'Milmay'],
                ['state_id' => 31, 'city' => 'Minotola'],
                ['state_id' => 31, 'city' => 'Mizpah'],
                ['state_id' => 31, 'city' => 'Newtonville'],
                ['state_id' => 31, 'city' => 'Richland'],
                ['state_id' => 31, 'city' => 'Atlantic City'],
                ['state_id' => 31, 'city' => 'Margate City'],
                ['state_id' => 31, 'city' => 'Longport'],
                ['state_id' => 31, 'city' => 'Ventnor City'],
                ['state_id' => 31, 'city' => 'Cliffside Park'],
                ['state_id' => 31, 'city' => 'Edgewater'],
                ['state_id' => 31, 'city' => 'Fairview'],
                ['state_id' => 31, 'city' => 'Fort Lee'],
                ['state_id' => 31, 'city' => 'Garfield'],
                ['state_id' => 31, 'city' => 'North Arlington'],
                ['state_id' => 31, 'city' => 'Wallington'],
                ['state_id' => 31, 'city' => 'Rutherford'],
                ['state_id' => 31, 'city' => 'Lyndhurst'],
                ['state_id' => 31, 'city' => 'Carlstadt'],
                ['state_id' => 31, 'city' => 'East Rutherford'],
                ['state_id' => 31, 'city' => 'Moonachie'],
                ['state_id' => 31, 'city' => 'Wood Ridge'],
                ['state_id' => 31, 'city' => 'Allendale'],
                ['state_id' => 31, 'city' => 'Elmwood Park'],
                ['state_id' => 31, 'city' => 'Fair Lawn'],
                ['state_id' => 31, 'city' => 'Franklin Lakes'],
                ['state_id' => 31, 'city' => 'Ho Ho Kus'],
                ['state_id' => 31, 'city' => 'Mahwah'],
                ['state_id' => 31, 'city' => 'Midland Park'],
                ['state_id' => 31, 'city' => 'Oakland'],
                ['state_id' => 31, 'city' => 'Ramsey'],
                ['state_id' => 31, 'city' => 'Ridgewood'],
                ['state_id' => 31, 'city' => 'Glen Rock'],
                ['state_id' => 31, 'city' => 'Saddle River'],
                ['state_id' => 31, 'city' => 'Waldwick'],
                ['state_id' => 31, 'city' => 'Wyckoff'],
                ['state_id' => 31, 'city' => 'Hackensack'],
                ['state_id' => 31, 'city' => 'Bogota'],
                ['state_id' => 31, 'city' => 'Hasbrouck Heights'],
                ['state_id' => 31, 'city' => 'Leonia'],
                ['state_id' => 31, 'city' => 'South Hackensack'],
                ['state_id' => 31, 'city' => 'Maywood'],
                ['state_id' => 31, 'city' => 'Teterboro'],
                ['state_id' => 31, 'city' => 'Alpine'],
                ['state_id' => 31, 'city' => 'Bergenfield'],
                ['state_id' => 31, 'city' => 'Closter'],
                ['state_id' => 31, 'city' => 'Cresskill'],
                ['state_id' => 31, 'city' => 'Demarest'],
                ['state_id' => 31, 'city' => 'Dumont'],
                ['state_id' => 31, 'city' => 'Emerson'],
                ['state_id' => 31, 'city' => 'Englewood'],
                ['state_id' => 31, 'city' => 'Englewood Cliffs'],
                ['state_id' => 31, 'city' => 'Harrington Park'],
                ['state_id' => 31, 'city' => 'Haworth'],
                ['state_id' => 31, 'city' => 'Hillsdale'],
                ['state_id' => 31, 'city' => 'Little Ferry'],
                ['state_id' => 31, 'city' => 'Lodi'],
                ['state_id' => 31, 'city' => 'Montvale'],
                ['state_id' => 31, 'city' => 'New Milford'],
                ['state_id' => 31, 'city' => 'Northvale'],
                ['state_id' => 31, 'city' => 'Norwood'],
                ['state_id' => 31, 'city' => 'Oradell'],
                ['state_id' => 31, 'city' => 'Palisades Park'],
                ['state_id' => 31, 'city' => 'Paramus'],
                ['state_id' => 31, 'city' => 'Park Ridge'],
                ['state_id' => 31, 'city' => 'Ridgefield'],
                ['state_id' => 31, 'city' => 'Ridgefield Park'],
                ['state_id' => 31, 'city' => 'River Edge'],
                ['state_id' => 31, 'city' => 'Rochelle Park'],
                ['state_id' => 31, 'city' => 'Saddle Brook'],
                ['state_id' => 31, 'city' => 'Teaneck'],
                ['state_id' => 31, 'city' => 'Tenafly'],
                ['state_id' => 31, 'city' => 'Westwood'],
                ['state_id' => 31, 'city' => 'Township Of Washington'],
                ['state_id' => 31, 'city' => 'Woodcliff Lake'],
                ['state_id' => 31, 'city' => 'Beverly'],
                ['state_id' => 31, 'city' => 'Birmingham'],
                ['state_id' => 31, 'city' => 'Browns Mills'],
                ['state_id' => 31, 'city' => 'Burlington'],
                ['state_id' => 31, 'city' => 'Chatsworth'],
                ['state_id' => 31, 'city' => 'Columbus'],
                ['state_id' => 31, 'city' => 'Hainesport'],
                ['state_id' => 31, 'city' => 'Jobstown'],
                ['state_id' => 31, 'city' => 'Juliustown'],
                ['state_id' => 31, 'city' => 'Willingboro'],
                ['state_id' => 31, 'city' => 'Lumberton'],
                ['state_id' => 31, 'city' => 'Maple Shade'],
                ['state_id' => 31, 'city' => 'Marlton'],
                ['state_id' => 31, 'city' => 'Mount Laurel'],
                ['state_id' => 31, 'city' => 'Medford'],
                ['state_id' => 31, 'city' => 'Moorestown'],
                ['state_id' => 31, 'city' => 'Mount Holly'],
                ['state_id' => 31, 'city' => 'New Lisbon'],
                ['state_id' => 31, 'city' => 'Palmyra'],
                ['state_id' => 31, 'city' => 'Pemberton'],
                ['state_id' => 31, 'city' => 'Rancocas'],
                ['state_id' => 31, 'city' => 'Riverside'],
                ['state_id' => 31, 'city' => 'Riverton'],
                ['state_id' => 31, 'city' => 'Vincentown'],
                ['state_id' => 31, 'city' => 'New Gretna'],
                ['state_id' => 31, 'city' => 'Bordentown'],
                ['state_id' => 31, 'city' => 'Cookstown'],
                ['state_id' => 31, 'city' => 'Chesterfield'],
                ['state_id' => 31, 'city' => 'Florence'],
                ['state_id' => 31, 'city' => 'Roebling'],
                ['state_id' => 31, 'city' => 'Wrightstown'],
                ['state_id' => 31, 'city' => 'Joint Base Mdl'],
                ['state_id' => 31, 'city' => 'Cherry Hill'],
                ['state_id' => 31, 'city' => 'Atco'],
                ['state_id' => 31, 'city' => 'Barrington'],
                ['state_id' => 31, 'city' => 'Berlin'],
                ['state_id' => 31, 'city' => 'Blackwood'],
                ['state_id' => 31, 'city' => 'Cedar Brook'],
                ['state_id' => 31, 'city' => 'Clementon'],
                ['state_id' => 31, 'city' => 'Gibbsboro'],
                ['state_id' => 31, 'city' => 'Glendora'],
                ['state_id' => 31, 'city' => 'Gloucester City'],
                ['state_id' => 31, 'city' => 'Bellmawr'],
                ['state_id' => 31, 'city' => 'Haddonfield'],
                ['state_id' => 31, 'city' => 'Haddon Heights'],
                ['state_id' => 31, 'city' => 'Voorhees'],
                ['state_id' => 31, 'city' => 'Lawnside'],
                ['state_id' => 31, 'city' => 'Magnolia'],
                ['state_id' => 31, 'city' => 'Mount Ephraim'],
                ['state_id' => 31, 'city' => 'Runnemede'],
                ['state_id' => 31, 'city' => 'Sicklerville'],
                ['state_id' => 31, 'city' => 'Somerdale'],
                ['state_id' => 31, 'city' => 'Stratford'],
                ['state_id' => 31, 'city' => 'Waterford Works'],
                ['state_id' => 31, 'city' => 'West Berlin'],
                ['state_id' => 31, 'city' => 'Winslow'],
                ['state_id' => 31, 'city' => 'Camden'],
                ['state_id' => 31, 'city' => 'Audubon'],
                ['state_id' => 31, 'city' => 'Oaklyn'],
                ['state_id' => 31, 'city' => 'Collingswood'],
                ['state_id' => 31, 'city' => 'Merchantville'],
                ['state_id' => 31, 'city' => 'Pennsauken'],
                ['state_id' => 31, 'city' => 'Avalon'],
                ['state_id' => 31, 'city' => 'Cape May'],
                ['state_id' => 31, 'city' => 'Cape May Court House'],
                ['state_id' => 31, 'city' => 'Cape May Point'],
                ['state_id' => 31, 'city' => 'Dennisville'],
                ['state_id' => 31, 'city' => 'Goshen'],
                ['state_id' => 31, 'city' => 'Green Creek'],
                ['state_id' => 31, 'city' => 'Marmora'],
                ['state_id' => 31, 'city' => 'Ocean City'],
                ['state_id' => 31, 'city' => 'Ocean View'],
                ['state_id' => 31, 'city' => 'Rio Grande'],
                ['state_id' => 31, 'city' => 'Sea Isle City'],
                ['state_id' => 31, 'city' => 'South Dennis'],
                ['state_id' => 31, 'city' => 'South Seaville'],
                ['state_id' => 31, 'city' => 'Stone Harbor'],
                ['state_id' => 31, 'city' => 'Strathmere'],
                ['state_id' => 31, 'city' => 'Tuckahoe'],
                ['state_id' => 31, 'city' => 'Villas'],
                ['state_id' => 31, 'city' => 'Whitesboro'],
                ['state_id' => 31, 'city' => 'Wildwood'],
                ['state_id' => 31, 'city' => 'Woodbine'],
                ['state_id' => 31, 'city' => 'Bridgeton'],
                ['state_id' => 31, 'city' => 'Cedarville'],
                ['state_id' => 31, 'city' => 'Deerfield Street'],
                ['state_id' => 31, 'city' => 'Delmont'],
                ['state_id' => 31, 'city' => 'Dividing Creek'],
                ['state_id' => 31, 'city' => 'Dorchester'],
                ['state_id' => 31, 'city' => 'Fairton'],
                ['state_id' => 31, 'city' => 'Fortescue'],
                ['state_id' => 31, 'city' => 'Greenwich'],
                ['state_id' => 31, 'city' => 'Heislerville'],
                ['state_id' => 31, 'city' => 'Leesburg'],
                ['state_id' => 31, 'city' => 'Mauricetown'],
                ['state_id' => 31, 'city' => 'Millville'],
                ['state_id' => 31, 'city' => 'Newport'],
                ['state_id' => 31, 'city' => 'Port Elizabeth'],
                ['state_id' => 31, 'city' => 'Port Norris'],
                ['state_id' => 31, 'city' => 'Rosenhayn'],
                ['state_id' => 31, 'city' => 'Shiloh'],
                ['state_id' => 31, 'city' => 'Vineland'],
                ['state_id' => 31, 'city' => 'Bloomfield'],
                ['state_id' => 31, 'city' => 'Fairfield'],
                ['state_id' => 31, 'city' => 'Caldwell'],
                ['state_id' => 31, 'city' => 'Cedar Grove'],
                ['state_id' => 31, 'city' => 'East Orange'],
                ['state_id' => 31, 'city' => 'Essex Fells'],
                ['state_id' => 31, 'city' => 'Glen Ridge'],
                ['state_id' => 31, 'city' => 'Livingston'],
                ['state_id' => 31, 'city' => 'Maplewood'],
                ['state_id' => 31, 'city' => 'Millburn'],
                ['state_id' => 31, 'city' => 'Montclair'],
                ['state_id' => 31, 'city' => 'Verona'],
                ['state_id' => 31, 'city' => 'Orange'],
                ['state_id' => 31, 'city' => 'West Orange'],
                ['state_id' => 31, 'city' => 'Roseland'],
                ['state_id' => 31, 'city' => 'Short Hills'],
                ['state_id' => 31, 'city' => 'South Orange'],
                ['state_id' => 31, 'city' => 'Newark'],
                ['state_id' => 31, 'city' => 'Belleville'],
                ['state_id' => 31, 'city' => 'Nutley'],
                ['state_id' => 31, 'city' => 'Irvington'],
                ['state_id' => 31, 'city' => 'Bridgeport'],
                ['state_id' => 31, 'city' => 'Clarksboro'],
                ['state_id' => 31, 'city' => 'Ewan'],
                ['state_id' => 31, 'city' => 'Gibbstown'],
                ['state_id' => 31, 'city' => 'Glassboro'],
                ['state_id' => 31, 'city' => 'Grenloch'],
                ['state_id' => 31, 'city' => 'Harrisonville'],
                ['state_id' => 31, 'city' => 'Mantua'],
                ['state_id' => 31, 'city' => 'Mickleton'],
                ['state_id' => 31, 'city' => 'Mount Royal'],
                ['state_id' => 31, 'city' => 'Mullica Hill'],
                ['state_id' => 31, 'city' => 'National Park'],
                ['state_id' => 31, 'city' => 'Paulsboro'],
                ['state_id' => 31, 'city' => 'Pitman'],
                ['state_id' => 31, 'city' => 'Richwood'],
                ['state_id' => 31, 'city' => 'Sewell'],
                ['state_id' => 31, 'city' => 'Swedesboro'],
                ['state_id' => 31, 'city' => 'Thorofare'],
                ['state_id' => 31, 'city' => 'Wenonah'],
                ['state_id' => 31, 'city' => 'Westville'],
                ['state_id' => 31, 'city' => 'Williamstown'],
                ['state_id' => 31, 'city' => 'Deptford'],
                ['state_id' => 31, 'city' => 'Woodbury Heights'],
                ['state_id' => 31, 'city' => 'Clayton'],
                ['state_id' => 31, 'city' => 'Franklinville'],
                ['state_id' => 31, 'city' => 'Malaga'],
                ['state_id' => 31, 'city' => 'Monroeville'],
                ['state_id' => 31, 'city' => 'Newfield'],
                ['state_id' => 31, 'city' => 'Bayonne'],
                ['state_id' => 31, 'city' => 'Harrison'],
                ['state_id' => 31, 'city' => 'Hoboken'],
                ['state_id' => 31, 'city' => 'Kearny'],
                ['state_id' => 31, 'city' => 'North Bergen'],
                ['state_id' => 31, 'city' => 'Weehawken'],
                ['state_id' => 31, 'city' => 'Union City'],
                ['state_id' => 31, 'city' => 'West New York'],
                ['state_id' => 31, 'city' => 'Secaucus'],
                ['state_id' => 31, 'city' => 'Jersey City'],
                ['state_id' => 31, 'city' => 'Califon'],
                ['state_id' => 31, 'city' => 'Pottersville'],
                ['state_id' => 31, 'city' => 'Lambertville'],
                ['state_id' => 31, 'city' => 'Ringoes'],
                ['state_id' => 31, 'city' => 'Rosemont'],
                ['state_id' => 31, 'city' => 'Sergeantsville'],
                ['state_id' => 31, 'city' => 'Stockton'],
                ['state_id' => 31, 'city' => 'Annandale'],
                ['state_id' => 31, 'city' => 'Baptistown'],
                ['state_id' => 31, 'city' => 'Bloomsbury'],
                ['state_id' => 31, 'city' => 'Clinton'],
                ['state_id' => 31, 'city' => 'Flemington'],
                ['state_id' => 31, 'city' => 'Frenchtown'],
                ['state_id' => 31, 'city' => 'Glen Gardner'],
                ['state_id' => 31, 'city' => 'Hampton'],
                ['state_id' => 31, 'city' => 'High Bridge'],
                ['state_id' => 31, 'city' => 'Lebanon'],
                ['state_id' => 31, 'city' => 'Little York'],
                ['state_id' => 31, 'city' => 'Milford'],
                ['state_id' => 31, 'city' => 'Oldwick'],
                ['state_id' => 31, 'city' => 'Pittstown'],
                ['state_id' => 31, 'city' => 'Quakertown'],
                ['state_id' => 31, 'city' => 'Readington'],
                ['state_id' => 31, 'city' => 'Stanton'],
                ['state_id' => 31, 'city' => 'Three Bridges'],
                ['state_id' => 31, 'city' => 'Whitehouse'],
                ['state_id' => 31, 'city' => 'Whitehouse Station'],
                ['state_id' => 31, 'city' => 'Hightstown'],
                ['state_id' => 31, 'city' => 'Hopewell'],
                ['state_id' => 31, 'city' => 'Pennington'],
                ['state_id' => 31, 'city' => 'Princeton'],
                ['state_id' => 31, 'city' => 'Princeton Junction'],
                ['state_id' => 31, 'city' => 'Titusville'],
                ['state_id' => 31, 'city' => 'Windsor'],
                ['state_id' => 31, 'city' => 'Trenton'],
                ['state_id' => 31, 'city' => 'Lawrence Township'],
                ['state_id' => 31, 'city' => 'Avenel'],
                ['state_id' => 31, 'city' => 'Carteret'],
                ['state_id' => 31, 'city' => 'Port Reading'],
                ['state_id' => 31, 'city' => 'Colonia'],
                ['state_id' => 31, 'city' => 'Sewaren'],
                ['state_id' => 31, 'city' => 'South Plainfield'],
                ['state_id' => 31, 'city' => 'Woodbridge'],
                ['state_id' => 31, 'city' => 'Cranbury'],
                ['state_id' => 31, 'city' => 'Plainsboro'],
                ['state_id' => 31, 'city' => 'Dayton'],
                ['state_id' => 31, 'city' => 'Dunellen'],
                ['state_id' => 31, 'city' => 'East Brunswick'],
                ['state_id' => 31, 'city' => 'Edison'],
                ['state_id' => 31, 'city' => 'Kendall Park'],
                ['state_id' => 31, 'city' => 'Helmetta'],
                ['state_id' => 31, 'city' => 'Iselin'],
                ['state_id' => 31, 'city' => 'Monroe Township'],
                ['state_id' => 31, 'city' => 'Keasbey'],
                ['state_id' => 31, 'city' => 'Metuchen'],
                ['state_id' => 31, 'city' => 'Middlesex'],
                ['state_id' => 31, 'city' => 'Milltown'],
                ['state_id' => 31, 'city' => 'Monmouth Junction'],
                ['state_id' => 31, 'city' => 'Piscataway'],
                ['state_id' => 31, 'city' => 'Old Bridge'],
                ['state_id' => 31, 'city' => 'Parlin'],
                ['state_id' => 31, 'city' => 'Perth Amboy'],
                ['state_id' => 31, 'city' => 'Fords'],
                ['state_id' => 31, 'city' => 'Sayreville'],
                ['state_id' => 31, 'city' => 'South Amboy'],
                ['state_id' => 31, 'city' => 'South River'],
                ['state_id' => 31, 'city' => 'Spotswood'],
                ['state_id' => 31, 'city' => 'New Brunswick'],
                ['state_id' => 31, 'city' => 'North Brunswick'],
                ['state_id' => 31, 'city' => 'Highland Park'],
                ['state_id' => 31, 'city' => 'Red Bank'],
                ['state_id' => 31, 'city' => 'Shrewsbury'],
                ['state_id' => 31, 'city' => 'Fort Monmouth'],
                ['state_id' => 31, 'city' => 'Fair Haven'],
                ['state_id' => 31, 'city' => 'Adelphia'],
                ['state_id' => 31, 'city' => 'Allenhurst'],
                ['state_id' => 31, 'city' => 'Asbury Park'],
                ['state_id' => 31, 'city' => 'Belmar'],
                ['state_id' => 31, 'city' => 'Atlantic Highlands'],
                ['state_id' => 31, 'city' => 'Avon By The Sea'],
                ['state_id' => 31, 'city' => 'Belford'],
                ['state_id' => 31, 'city' => 'Bradley Beach'],
                ['state_id' => 31, 'city' => 'Cliffwood'],
                ['state_id' => 31, 'city' => 'Colts Neck'],
                ['state_id' => 31, 'city' => 'Deal'],
                ['state_id' => 31, 'city' => 'Eatontown'],
                ['state_id' => 31, 'city' => 'Englishtown'],
                ['state_id' => 31, 'city' => 'Farmingdale'],
                ['state_id' => 31, 'city' => 'Freehold'],
                ['state_id' => 31, 'city' => 'Hazlet'],
                ['state_id' => 31, 'city' => 'Howell'],
                ['state_id' => 31, 'city' => 'Highlands'],
                ['state_id' => 31, 'city' => 'Holmdel'],
                ['state_id' => 31, 'city' => 'Keansburg'],
                ['state_id' => 31, 'city' => 'Keyport'],
                ['state_id' => 31, 'city' => 'Leonardo'],
                ['state_id' => 31, 'city' => 'Lincroft'],
                ['state_id' => 31, 'city' => 'Little Silver'],
                ['state_id' => 31, 'city' => 'Long Branch'],
                ['state_id' => 31, 'city' => 'Marlboro'],
                ['state_id' => 31, 'city' => 'Matawan'],
                ['state_id' => 31, 'city' => 'Middletown'],
                ['state_id' => 31, 'city' => 'Monmouth Beach'],
                ['state_id' => 31, 'city' => 'Morganville'],
                ['state_id' => 31, 'city' => 'Navesink'],
                ['state_id' => 31, 'city' => 'Neptune'],
                ['state_id' => 31, 'city' => 'Oakhurst'],
                ['state_id' => 31, 'city' => 'Ocean Grove'],
                ['state_id' => 31, 'city' => 'Oceanport'],
                ['state_id' => 31, 'city' => 'Port Monmouth'],
                ['state_id' => 31, 'city' => 'Rumson'],
                ['state_id' => 31, 'city' => 'Spring Lake'],
                ['state_id' => 31, 'city' => 'Tennent'],
                ['state_id' => 31, 'city' => 'West Long Branch'],
                ['state_id' => 31, 'city' => 'Wickatunk'],
                ['state_id' => 31, 'city' => 'Allentown'],
                ['state_id' => 31, 'city' => 'Millstone Township'],
                ['state_id' => 31, 'city' => 'Cream Ridge'],
                ['state_id' => 31, 'city' => 'Imlaystown'],
                ['state_id' => 31, 'city' => 'Roosevelt'],
                ['state_id' => 31, 'city' => 'Allenwood'],
                ['state_id' => 31, 'city' => 'Brielle'],
                ['state_id' => 31, 'city' => 'Manasquan'],
                ['state_id' => 31, 'city' => 'Sea Girt'],
                ['state_id' => 31, 'city' => 'Boonton'],
                ['state_id' => 31, 'city' => 'Lake Hiawatha'],
                ['state_id' => 31, 'city' => 'Lincoln Park'],
                ['state_id' => 31, 'city' => 'Montville'],
                ['state_id' => 31, 'city' => 'Mountain Lakes'],
                ['state_id' => 31, 'city' => 'Parsippany'],
                ['state_id' => 31, 'city' => 'Pine Brook'],
                ['state_id' => 31, 'city' => 'Towaco'],
                ['state_id' => 31, 'city' => 'Butler'],
                ['state_id' => 31, 'city' => 'Pequannock'],
                ['state_id' => 31, 'city' => 'Pompton Plains'],
                ['state_id' => 31, 'city' => 'Riverdale'],
                ['state_id' => 31, 'city' => 'Dover'],
                ['state_id' => 31, 'city' => 'Mine Hill'],
                ['state_id' => 31, 'city' => 'Picatinny Arsenal'],
                ['state_id' => 31, 'city' => 'Budd Lake'],
                ['state_id' => 31, 'city' => 'Denville'],
                ['state_id' => 31, 'city' => 'Flanders'],
                ['state_id' => 31, 'city' => 'Hibernia'],
                ['state_id' => 31, 'city' => 'Ironia'],
                ['state_id' => 31, 'city' => 'Kenvil'],
                ['state_id' => 31, 'city' => 'Lake Hopatcong'],
                ['state_id' => 31, 'city' => 'Landing'],
                ['state_id' => 31, 'city' => 'Ledgewood'],
                ['state_id' => 31, 'city' => 'Long Valley'],
                ['state_id' => 31, 'city' => 'Mount Arlington'],
                ['state_id' => 31, 'city' => 'Netcong'],
                ['state_id' => 31, 'city' => 'Rockaway'],
                ['state_id' => 31, 'city' => 'Randolph'],
                ['state_id' => 31, 'city' => 'Schooleys Mountain'],
                ['state_id' => 31, 'city' => 'Succasunna'],
                ['state_id' => 31, 'city' => 'Mount Tabor'],
                ['state_id' => 31, 'city' => 'Wharton'],
                ['state_id' => 31, 'city' => 'Brookside'],
                ['state_id' => 31, 'city' => 'Cedar Knolls'],
                ['state_id' => 31, 'city' => 'Chatham'],
                ['state_id' => 31, 'city' => 'Chester'],
                ['state_id' => 31, 'city' => 'Florham Park'],
                ['state_id' => 31, 'city' => 'Gillette'],
                ['state_id' => 31, 'city' => 'Green Village'],
                ['state_id' => 31, 'city' => 'East Hanover'],
                ['state_id' => 31, 'city' => 'Madison'],
                ['state_id' => 31, 'city' => 'Mendham'],
                ['state_id' => 31, 'city' => 'Millington'],
                ['state_id' => 31, 'city' => 'Morris Plains'],
                ['state_id' => 31, 'city' => 'Morristown'],
                ['state_id' => 31, 'city' => 'Convent Station'],
                ['state_id' => 31, 'city' => 'Mount Freedom'],
                ['state_id' => 31, 'city' => 'New Vernon'],
                ['state_id' => 31, 'city' => 'Stirling'],
                ['state_id' => 31, 'city' => 'Whippany'],
                ['state_id' => 31, 'city' => 'Barnegat'],
                ['state_id' => 31, 'city' => 'Barnegat Light'],
                ['state_id' => 31, 'city' => 'Beach Haven'],
                ['state_id' => 31, 'city' => 'Manahawkin'],
                ['state_id' => 31, 'city' => 'Tuckerton'],
                ['state_id' => 31, 'city' => 'West Creek'],
                ['state_id' => 31, 'city' => 'Jackson'],
                ['state_id' => 31, 'city' => 'New Egypt'],
                ['state_id' => 31, 'city' => 'Lakewood'],
                ['state_id' => 31, 'city' => 'Bayville'],
                ['state_id' => 31, 'city' => 'Beachwood'],
                ['state_id' => 31, 'city' => 'Brick'],
                ['state_id' => 31, 'city' => 'Forked River'],
                ['state_id' => 31, 'city' => 'Island Heights'],
                ['state_id' => 31, 'city' => 'Lakehurst'],
                ['state_id' => 31, 'city' => 'Lanoka Harbor'],
                ['state_id' => 31, 'city' => 'Lavallette'],
                ['state_id' => 31, 'city' => 'Mantoloking'],
                ['state_id' => 31, 'city' => 'Normandy Beach'],
                ['state_id' => 31, 'city' => 'Ocean Gate'],
                ['state_id' => 31, 'city' => 'Pine Beach'],
                ['state_id' => 31, 'city' => 'Point Pleasant Beach'],
                ['state_id' => 31, 'city' => 'Seaside Heights'],
                ['state_id' => 31, 'city' => 'Seaside Park'],
                ['state_id' => 31, 'city' => 'Toms River'],
                ['state_id' => 31, 'city' => 'Waretown'],
                ['state_id' => 31, 'city' => 'Manchester Township'],
                ['state_id' => 31, 'city' => 'Clifton'],
                ['state_id' => 31, 'city' => 'Passaic'],
                ['state_id' => 31, 'city' => 'Bloomingdale'],
                ['state_id' => 31, 'city' => 'Haskell'],
                ['state_id' => 31, 'city' => 'Hewitt'],
                ['state_id' => 31, 'city' => 'Little Falls'],
                ['state_id' => 31, 'city' => 'Newfoundland'],
                ['state_id' => 31, 'city' => 'Oak Ridge'],
                ['state_id' => 31, 'city' => 'Pompton Lakes'],
                ['state_id' => 31, 'city' => 'Ringwood'],
                ['state_id' => 31, 'city' => 'Wanaque'],
                ['state_id' => 31, 'city' => 'Wayne'],
                ['state_id' => 31, 'city' => 'West Milford'],
                ['state_id' => 31, 'city' => 'Paterson'],
                ['state_id' => 31, 'city' => 'Hawthorne'],
                ['state_id' => 31, 'city' => 'Haledon'],
                ['state_id' => 31, 'city' => 'Totowa'],
                ['state_id' => 31, 'city' => 'Alloway'],
                ['state_id' => 31, 'city' => 'Deepwater'],
                ['state_id' => 31, 'city' => 'Hancocks Bridge'],
                ['state_id' => 31, 'city' => 'Pedricktown'],
                ['state_id' => 31, 'city' => 'Penns Grove'],
                ['state_id' => 31, 'city' => 'Pennsville'],
                ['state_id' => 31, 'city' => 'Quinton'],
                ['state_id' => 31, 'city' => 'Salem'],
                ['state_id' => 31, 'city' => 'Woodstown'],
                ['state_id' => 31, 'city' => 'Elmer'],
                ['state_id' => 31, 'city' => 'Norma'],
                ['state_id' => 31, 'city' => 'Warren'],
                ['state_id' => 31, 'city' => 'Basking Ridge'],
                ['state_id' => 31, 'city' => 'Bedminster'],
                ['state_id' => 31, 'city' => 'Bernardsville'],
                ['state_id' => 31, 'city' => 'Far Hills'],
                ['state_id' => 31, 'city' => 'Gladstone'],
                ['state_id' => 31, 'city' => 'Liberty Corner'],
                ['state_id' => 31, 'city' => 'Lyons'],
                ['state_id' => 31, 'city' => 'Peapack'],
                ['state_id' => 31, 'city' => 'Pluckemin'],
                ['state_id' => 31, 'city' => 'Belle Mead'],
                ['state_id' => 31, 'city' => 'Blawenburg'],
                ['state_id' => 31, 'city' => 'Kingston'],
                ['state_id' => 31, 'city' => 'Rocky Hill'],
                ['state_id' => 31, 'city' => 'Skillman'],
                ['state_id' => 31, 'city' => 'Bound Brook'],
                ['state_id' => 31, 'city' => 'Bridgewater'],
                ['state_id' => 31, 'city' => 'Flagtown'],
                ['state_id' => 31, 'city' => 'Franklin Park'],
                ['state_id' => 31, 'city' => 'Manville'],
                ['state_id' => 31, 'city' => 'Martinsville'],
                ['state_id' => 31, 'city' => 'Hillsborough'],
                ['state_id' => 31, 'city' => 'Neshanic Station'],
                ['state_id' => 31, 'city' => 'Raritan'],
                ['state_id' => 31, 'city' => 'Somerset'],
                ['state_id' => 31, 'city' => 'Somerville'],
                ['state_id' => 31, 'city' => 'South Bound Brook'],
                ['state_id' => 31, 'city' => 'Zarephath'],
                ['state_id' => 31, 'city' => 'Franklin'],
                ['state_id' => 31, 'city' => 'Glenwood'],
                ['state_id' => 31, 'city' => 'Hamburg'],
                ['state_id' => 31, 'city' => 'Highland Lakes'],
                ['state_id' => 31, 'city' => 'Mc Afee'],
                ['state_id' => 31, 'city' => 'Ogdensburg'],
                ['state_id' => 31, 'city' => 'Stockholm'],
                ['state_id' => 31, 'city' => 'Sussex'],
                ['state_id' => 31, 'city' => 'Vernon'],
                ['state_id' => 31, 'city' => 'Andover'],
                ['state_id' => 31, 'city' => 'Augusta'],
                ['state_id' => 31, 'city' => 'Branchville'],
                ['state_id' => 31, 'city' => 'Montague'],
                ['state_id' => 31, 'city' => 'Glasser'],
                ['state_id' => 31, 'city' => 'Greendell'],
                ['state_id' => 31, 'city' => 'Hopatcong'],
                ['state_id' => 31, 'city' => 'Lafayette'],
                ['state_id' => 31, 'city' => 'Layton'],
                ['state_id' => 31, 'city' => 'Middleville'],
                ['state_id' => 31, 'city' => 'Newton'],
                ['state_id' => 31, 'city' => 'Sparta'],
                ['state_id' => 31, 'city' => 'Stanhope'],
                ['state_id' => 31, 'city' => 'Stillwater'],
                ['state_id' => 31, 'city' => 'Swartswood'],
                ['state_id' => 31, 'city' => 'Tranquility'],
                ['state_id' => 31, 'city' => 'Wallpack Center'],
                ['state_id' => 31, 'city' => 'Cranford'],
                ['state_id' => 31, 'city' => 'Fanwood'],
                ['state_id' => 31, 'city' => 'Garwood'],
                ['state_id' => 31, 'city' => 'Kenilworth'],
                ['state_id' => 31, 'city' => 'Linden'],
                ['state_id' => 31, 'city' => 'Plainfield'],
                ['state_id' => 31, 'city' => 'Rahway'],
                ['state_id' => 31, 'city' => 'Clark'],
                ['state_id' => 31, 'city' => 'Watchung'],
                ['state_id' => 31, 'city' => 'Scotch Plains'],
                ['state_id' => 31, 'city' => 'Springfield'],
                ['state_id' => 31, 'city' => 'Union'],
                ['state_id' => 31, 'city' => 'Vauxhall'],
                ['state_id' => 31, 'city' => 'Westfield'],
                ['state_id' => 31, 'city' => 'Mountainside'],
                ['state_id' => 31, 'city' => 'Elizabeth'],
                ['state_id' => 31, 'city' => 'Roselle'],
                ['state_id' => 31, 'city' => 'Roselle Park'],
                ['state_id' => 31, 'city' => 'Hillside'],
                ['state_id' => 31, 'city' => 'Elizabethport'],
                ['state_id' => 31, 'city' => 'Summit'],
                ['state_id' => 31, 'city' => 'Berkeley Heights'],
                ['state_id' => 31, 'city' => 'New Providence'],
                ['state_id' => 31, 'city' => 'Allamuchy'],
                ['state_id' => 31, 'city' => 'Belvidere'],
                ['state_id' => 31, 'city' => 'Blairstown'],
                ['state_id' => 31, 'city' => 'Buttzville'],
                ['state_id' => 31, 'city' => 'Changewater'],
                ['state_id' => 31, 'city' => 'Columbia'],
                ['state_id' => 31, 'city' => 'Delaware'],
                ['state_id' => 31, 'city' => 'Great Meadows'],
                ['state_id' => 31, 'city' => 'Hackettstown'],
                ['state_id' => 31, 'city' => 'Hope'],
                ['state_id' => 31, 'city' => 'Johnsonburg'],
                ['state_id' => 31, 'city' => 'Oxford'],
                ['state_id' => 31, 'city' => 'Port Murray'],
                ['state_id' => 31, 'city' => 'Vienna'],
                ['state_id' => 31, 'city' => 'Washington'],
                ['state_id' => 31, 'city' => 'Asbury'],
                ['state_id' => 31, 'city' => 'Broadway'],
                ['state_id' => 31, 'city' => 'Phillipsburg'],
                ['state_id' => 31, 'city' => 'Stewartsville']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
