<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State27TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MT - Montana.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 27, 'city' => 'Dell'],
                ['state_id' => 27, 'city' => 'Dillon'],
                ['state_id' => 27, 'city' => 'Glen'],
                ['state_id' => 27, 'city' => 'Jackson'],
                ['state_id' => 27, 'city' => 'Lima'],
                ['state_id' => 27, 'city' => 'Polaris'],
                ['state_id' => 27, 'city' => 'Wisdom'],
                ['state_id' => 27, 'city' => 'Wise River'],
                ['state_id' => 27, 'city' => 'Busby'],
                ['state_id' => 27, 'city' => 'Crow Agency'],
                ['state_id' => 27, 'city' => 'Decker'],
                ['state_id' => 27, 'city' => 'Garryowen'],
                ['state_id' => 27, 'city' => 'Hardin'],
                ['state_id' => 27, 'city' => 'Fort Smith'],
                ['state_id' => 27, 'city' => 'Lodge Grass'],
                ['state_id' => 27, 'city' => 'Pryor'],
                ['state_id' => 27, 'city' => 'Saint Xavier'],
                ['state_id' => 27, 'city' => 'Wyola'],
                ['state_id' => 27, 'city' => 'Chinook'],
                ['state_id' => 27, 'city' => 'Harlem'],
                ['state_id' => 27, 'city' => 'Hays'],
                ['state_id' => 27, 'city' => 'Hogeland'],
                ['state_id' => 27, 'city' => 'Lloyd'],
                ['state_id' => 27, 'city' => 'Turner'],
                ['state_id' => 27, 'city' => 'Zurich'],
                ['state_id' => 27, 'city' => 'Radersburg'],
                ['state_id' => 27, 'city' => 'Toston'],
                ['state_id' => 27, 'city' => 'Townsend'],
                ['state_id' => 27, 'city' => 'Winston'],
                ['state_id' => 27, 'city' => 'Bearcreek'],
                ['state_id' => 27, 'city' => 'Belfry'],
                ['state_id' => 27, 'city' => 'Boyd'],
                ['state_id' => 27, 'city' => 'Bridger'],
                ['state_id' => 27, 'city' => 'Edgar'],
                ['state_id' => 27, 'city' => 'Fromberg'],
                ['state_id' => 27, 'city' => 'Joliet'],
                ['state_id' => 27, 'city' => 'Red Lodge'],
                ['state_id' => 27, 'city' => 'Roberts'],
                ['state_id' => 27, 'city' => 'Roscoe'],
                ['state_id' => 27, 'city' => 'Alzada'],
                ['state_id' => 27, 'city' => 'Boyes'],
                ['state_id' => 27, 'city' => 'Capitol'],
                ['state_id' => 27, 'city' => 'Ekalaka'],
                ['state_id' => 27, 'city' => 'Hammond'],
                ['state_id' => 27, 'city' => 'Great Falls'],
                ['state_id' => 27, 'city' => 'Malmstrom Afb'],
                ['state_id' => 27, 'city' => 'Belt'],
                ['state_id' => 27, 'city' => 'Black Eagle'],
                ['state_id' => 27, 'city' => 'Cascade'],
                ['state_id' => 27, 'city' => 'Fort Shaw'],
                ['state_id' => 27, 'city' => 'Monarch'],
                ['state_id' => 27, 'city' => 'Neihart'],
                ['state_id' => 27, 'city' => 'Sand Coulee'],
                ['state_id' => 27, 'city' => 'Simms'],
                ['state_id' => 27, 'city' => 'Stockett'],
                ['state_id' => 27, 'city' => 'Sun River'],
                ['state_id' => 27, 'city' => 'Ulm'],
                ['state_id' => 27, 'city' => 'Vaughn'],
                ['state_id' => 27, 'city' => 'Carter'],
                ['state_id' => 27, 'city' => 'Floweree'],
                ['state_id' => 27, 'city' => 'Fort Benton'],
                ['state_id' => 27, 'city' => 'Geraldine'],
                ['state_id' => 27, 'city' => 'Highwood'],
                ['state_id' => 27, 'city' => 'Loma'],
                ['state_id' => 27, 'city' => 'Big Sandy'],
                ['state_id' => 27, 'city' => 'Miles City'],
                ['state_id' => 27, 'city' => 'Ismay'],
                ['state_id' => 27, 'city' => 'Kinsey'],
                ['state_id' => 27, 'city' => 'Volborg'],
                ['state_id' => 27, 'city' => 'Flaxville'],
                ['state_id' => 27, 'city' => 'Peerless'],
                ['state_id' => 27, 'city' => 'Scobey'],
                ['state_id' => 27, 'city' => 'Whitetail'],
                ['state_id' => 27, 'city' => 'Richey'],
                ['state_id' => 27, 'city' => 'Bloomfield'],
                ['state_id' => 27, 'city' => 'Glendive'],
                ['state_id' => 27, 'city' => 'Lindsay'],
                ['state_id' => 27, 'city' => 'Anaconda'],
                ['state_id' => 27, 'city' => 'Warm Springs'],
                ['state_id' => 27, 'city' => 'Baker'],
                ['state_id' => 27, 'city' => 'Plevna'],
                ['state_id' => 27, 'city' => 'Willard'],
                ['state_id' => 27, 'city' => 'Grass Range'],
                ['state_id' => 27, 'city' => 'Buffalo'],
                ['state_id' => 27, 'city' => 'Coffee Creek'],
                ['state_id' => 27, 'city' => 'Denton'],
                ['state_id' => 27, 'city' => 'Forest Grove'],
                ['state_id' => 27, 'city' => 'Hilger'],
                ['state_id' => 27, 'city' => 'Lewistown'],
                ['state_id' => 27, 'city' => 'Moore'],
                ['state_id' => 27, 'city' => 'Roy'],
                ['state_id' => 27, 'city' => 'Winifred'],
                ['state_id' => 27, 'city' => 'Kalispell'],
                ['state_id' => 27, 'city' => 'Bigfork'],
                ['state_id' => 27, 'city' => 'Columbia Falls'],
                ['state_id' => 27, 'city' => 'Coram'],
                ['state_id' => 27, 'city' => 'Essex'],
                ['state_id' => 27, 'city' => 'Hungry Horse'],
                ['state_id' => 27, 'city' => 'Kila'],
                ['state_id' => 27, 'city' => 'Lake Mc Donald'],
                ['state_id' => 27, 'city' => 'Lakeside'],
                ['state_id' => 27, 'city' => 'Marion'],
                ['state_id' => 27, 'city' => 'Martin City'],
                ['state_id' => 27, 'city' => 'Olney'],
                ['state_id' => 27, 'city' => 'Polebridge'],
                ['state_id' => 27, 'city' => 'Somers'],
                ['state_id' => 27, 'city' => 'West Glacier'],
                ['state_id' => 27, 'city' => 'Whitefish'],
                ['state_id' => 27, 'city' => 'Belgrade'],
                ['state_id' => 27, 'city' => 'Bozeman'],
                ['state_id' => 27, 'city' => 'Big Sky'],
                ['state_id' => 27, 'city' => 'Gallatin Gateway'],
                ['state_id' => 27, 'city' => 'Manhattan'],
                ['state_id' => 27, 'city' => 'Three Forks'],
                ['state_id' => 27, 'city' => 'West Yellowstone'],
                ['state_id' => 27, 'city' => 'Willow Creek'],
                ['state_id' => 27, 'city' => 'Mosby'],
                ['state_id' => 27, 'city' => 'Sand Springs'],
                ['state_id' => 27, 'city' => 'Brusett'],
                ['state_id' => 27, 'city' => 'Cohagen'],
                ['state_id' => 27, 'city' => 'Jordan'],
                ['state_id' => 27, 'city' => 'Babb'],
                ['state_id' => 27, 'city' => 'Browning'],
                ['state_id' => 27, 'city' => 'Cut Bank'],
                ['state_id' => 27, 'city' => 'East Glacier Park'],
                ['state_id' => 27, 'city' => 'Lavina'],
                ['state_id' => 27, 'city' => 'Ryegate'],
                ['state_id' => 27, 'city' => 'Drummond'],
                ['state_id' => 27, 'city' => 'Hall'],
                ['state_id' => 27, 'city' => 'Philipsburg'],
                ['state_id' => 27, 'city' => 'Havre'],
                ['state_id' => 27, 'city' => 'Box Elder'],
                ['state_id' => 27, 'city' => 'Gildford'],
                ['state_id' => 27, 'city' => 'Hingham'],
                ['state_id' => 27, 'city' => 'Inverness'],
                ['state_id' => 27, 'city' => 'Kremlin'],
                ['state_id' => 27, 'city' => 'Rudyard'],
                ['state_id' => 27, 'city' => 'Basin'],
                ['state_id' => 27, 'city' => 'Boulder'],
                ['state_id' => 27, 'city' => 'Clancy'],
                ['state_id' => 27, 'city' => 'Jefferson City'],
                ['state_id' => 27, 'city' => 'Cardwell'],
                ['state_id' => 27, 'city' => 'Whitehall'],
                ['state_id' => 27, 'city' => 'Geyser'],
                ['state_id' => 27, 'city' => 'Hobson'],
                ['state_id' => 27, 'city' => 'Moccasin'],
                ['state_id' => 27, 'city' => 'Raynesford'],
                ['state_id' => 27, 'city' => 'Stanford'],
                ['state_id' => 27, 'city' => 'Arlee'],
                ['state_id' => 27, 'city' => 'Charlo'],
                ['state_id' => 27, 'city' => 'Pablo'],
                ['state_id' => 27, 'city' => 'Polson'],
                ['state_id' => 27, 'city' => 'Ravalli'],
                ['state_id' => 27, 'city' => 'Ronan'],
                ['state_id' => 27, 'city' => 'Saint Ignatius'],
                ['state_id' => 27, 'city' => 'Big Arm'],
                ['state_id' => 27, 'city' => 'Dayton'],
                ['state_id' => 27, 'city' => 'Elmo'],
                ['state_id' => 27, 'city' => 'Proctor'],
                ['state_id' => 27, 'city' => 'Rollins'],
                ['state_id' => 27, 'city' => 'Augusta'],
                ['state_id' => 27, 'city' => 'Helena'],
                ['state_id' => 27, 'city' => 'Canyon Creek'],
                ['state_id' => 27, 'city' => 'East Helena'],
                ['state_id' => 27, 'city' => 'Fort Harrison'],
                ['state_id' => 27, 'city' => 'Lincoln'],
                ['state_id' => 27, 'city' => 'Marysville'],
                ['state_id' => 27, 'city' => 'Wolf Creek'],
                ['state_id' => 27, 'city' => 'Chester'],
                ['state_id' => 27, 'city' => 'Joplin'],
                ['state_id' => 27, 'city' => 'Whitlash'],
                ['state_id' => 27, 'city' => 'Eureka'],
                ['state_id' => 27, 'city' => 'Fortine'],
                ['state_id' => 27, 'city' => 'Libby'],
                ['state_id' => 27, 'city' => 'Rexford'],
                ['state_id' => 27, 'city' => 'Stryker'],
                ['state_id' => 27, 'city' => 'Trego'],
                ['state_id' => 27, 'city' => 'Troy'],
                ['state_id' => 27, 'city' => 'Brockway'],
                ['state_id' => 27, 'city' => 'Circle'],
                ['state_id' => 27, 'city' => 'Vida'],
                ['state_id' => 27, 'city' => 'Alder'],
                ['state_id' => 27, 'city' => 'Cameron'],
                ['state_id' => 27, 'city' => 'Ennis'],
                ['state_id' => 27, 'city' => 'Harrison'],
                ['state_id' => 27, 'city' => 'Mc Allister'],
                ['state_id' => 27, 'city' => 'Norris'],
                ['state_id' => 27, 'city' => 'Pony'],
                ['state_id' => 27, 'city' => 'Sheridan'],
                ['state_id' => 27, 'city' => 'Silver Star'],
                ['state_id' => 27, 'city' => 'Twin Bridges'],
                ['state_id' => 27, 'city' => 'Virginia City'],
                ['state_id' => 27, 'city' => 'Martinsdale'],
                ['state_id' => 27, 'city' => 'Ringling'],
                ['state_id' => 27, 'city' => 'White Sulphur Springs'],
                ['state_id' => 27, 'city' => 'Alberton'],
                ['state_id' => 27, 'city' => 'De Borgia'],
                ['state_id' => 27, 'city' => 'Haugan'],
                ['state_id' => 27, 'city' => 'Saint Regis'],
                ['state_id' => 27, 'city' => 'Saltese'],
                ['state_id' => 27, 'city' => 'Superior'],
                ['state_id' => 27, 'city' => 'Missoula'],
                ['state_id' => 27, 'city' => 'Bonner'],
                ['state_id' => 27, 'city' => 'Clinton'],
                ['state_id' => 27, 'city' => 'Condon'],
                ['state_id' => 27, 'city' => 'Frenchtown'],
                ['state_id' => 27, 'city' => 'Huson'],
                ['state_id' => 27, 'city' => 'Lolo'],
                ['state_id' => 27, 'city' => 'Milltown'],
                ['state_id' => 27, 'city' => 'Seeley Lake'],
                ['state_id' => 27, 'city' => 'Melstone'],
                ['state_id' => 27, 'city' => 'Musselshell'],
                ['state_id' => 27, 'city' => 'Roundup'],
                ['state_id' => 27, 'city' => 'Clyde Park'],
                ['state_id' => 27, 'city' => 'Cooke City'],
                ['state_id' => 27, 'city' => 'Emigrant'],
                ['state_id' => 27, 'city' => 'Gardiner'],
                ['state_id' => 27, 'city' => 'Livingston'],
                ['state_id' => 27, 'city' => 'Pray'],
                ['state_id' => 27, 'city' => 'Silver Gate'],
                ['state_id' => 27, 'city' => 'Springdale'],
                ['state_id' => 27, 'city' => 'Wilsall'],
                ['state_id' => 27, 'city' => 'Teigen'],
                ['state_id' => 27, 'city' => 'Winnett'],
                ['state_id' => 27, 'city' => 'Saco'],
                ['state_id' => 27, 'city' => 'Dodson'],
                ['state_id' => 27, 'city' => 'Loring'],
                ['state_id' => 27, 'city' => 'Malta'],
                ['state_id' => 27, 'city' => 'Whitewater'],
                ['state_id' => 27, 'city' => 'Zortman'],
                ['state_id' => 27, 'city' => 'Brady'],
                ['state_id' => 27, 'city' => 'Conrad'],
                ['state_id' => 27, 'city' => 'Dupuyer'],
                ['state_id' => 27, 'city' => 'Heart Butte'],
                ['state_id' => 27, 'city' => 'Ledger'],
                ['state_id' => 27, 'city' => 'Valier'],
                ['state_id' => 27, 'city' => 'Otter'],
                ['state_id' => 27, 'city' => 'Biddle'],
                ['state_id' => 27, 'city' => 'Broadus'],
                ['state_id' => 27, 'city' => 'Olive'],
                ['state_id' => 27, 'city' => 'Powderville'],
                ['state_id' => 27, 'city' => 'Avon'],
                ['state_id' => 27, 'city' => 'Deer Lodge'],
                ['state_id' => 27, 'city' => 'Elliston'],
                ['state_id' => 27, 'city' => 'Garrison'],
                ['state_id' => 27, 'city' => 'Gold Creek'],
                ['state_id' => 27, 'city' => 'Helmville'],
                ['state_id' => 27, 'city' => 'Ovando'],
                ['state_id' => 27, 'city' => 'Fallon'],
                ['state_id' => 27, 'city' => 'Mildred'],
                ['state_id' => 27, 'city' => 'Terry'],
                ['state_id' => 27, 'city' => 'Conner'],
                ['state_id' => 27, 'city' => 'Corvallis'],
                ['state_id' => 27, 'city' => 'Darby'],
                ['state_id' => 27, 'city' => 'Florence'],
                ['state_id' => 27, 'city' => 'Grantsdale'],
                ['state_id' => 27, 'city' => 'Hamilton'],
                ['state_id' => 27, 'city' => 'Pinesdale'],
                ['state_id' => 27, 'city' => 'Stevensville'],
                ['state_id' => 27, 'city' => 'Sula'],
                ['state_id' => 27, 'city' => 'Victor'],
                ['state_id' => 27, 'city' => 'Crane'],
                ['state_id' => 27, 'city' => 'Fairview'],
                ['state_id' => 27, 'city' => 'Lambert'],
                ['state_id' => 27, 'city' => 'Savage'],
                ['state_id' => 27, 'city' => 'Sidney'],
                ['state_id' => 27, 'city' => 'Wolf Point'],
                ['state_id' => 27, 'city' => 'Bainville'],
                ['state_id' => 27, 'city' => 'Brockton'],
                ['state_id' => 27, 'city' => 'Culbertson'],
                ['state_id' => 27, 'city' => 'Froid'],
                ['state_id' => 27, 'city' => 'Homestead'],
                ['state_id' => 27, 'city' => 'Poplar'],
                ['state_id' => 27, 'city' => 'Ashland'],
                ['state_id' => 27, 'city' => 'Birney'],
                ['state_id' => 27, 'city' => 'Ingomar'],
                ['state_id' => 27, 'city' => 'Lame Deer'],
                ['state_id' => 27, 'city' => 'Sumatra'],
                ['state_id' => 27, 'city' => 'Angela'],
                ['state_id' => 27, 'city' => 'Colstrip'],
                ['state_id' => 27, 'city' => 'Forsyth'],
                ['state_id' => 27, 'city' => 'Hathaway'],
                ['state_id' => 27, 'city' => 'Rosebud'],
                ['state_id' => 27, 'city' => 'Dixon'],
                ['state_id' => 27, 'city' => 'Heron'],
                ['state_id' => 27, 'city' => 'Hot Springs'],
                ['state_id' => 27, 'city' => 'Lonepine'],
                ['state_id' => 27, 'city' => 'Noxon'],
                ['state_id' => 27, 'city' => 'Paradise'],
                ['state_id' => 27, 'city' => 'Plains'],
                ['state_id' => 27, 'city' => 'Thompson Falls'],
                ['state_id' => 27, 'city' => 'Trout Creek'],
                ['state_id' => 27, 'city' => 'Antelope'],
                ['state_id' => 27, 'city' => 'Dagmar'],
                ['state_id' => 27, 'city' => 'Medicine Lake'],
                ['state_id' => 27, 'city' => 'Outlook'],
                ['state_id' => 27, 'city' => 'Plentywood'],
                ['state_id' => 27, 'city' => 'Raymond'],
                ['state_id' => 27, 'city' => 'Redstone'],
                ['state_id' => 27, 'city' => 'Reserve'],
                ['state_id' => 27, 'city' => 'Westby'],
                ['state_id' => 27, 'city' => 'Butte'],
                ['state_id' => 27, 'city' => 'Divide'],
                ['state_id' => 27, 'city' => 'Melrose'],
                ['state_id' => 27, 'city' => 'Ramsay'],
                ['state_id' => 27, 'city' => 'Absarokee'],
                ['state_id' => 27, 'city' => 'Columbus'],
                ['state_id' => 27, 'city' => 'Fishtail'],
                ['state_id' => 27, 'city' => 'Molt'],
                ['state_id' => 27, 'city' => 'Nye'],
                ['state_id' => 27, 'city' => 'Park City'],
                ['state_id' => 27, 'city' => 'Rapelje'],
                ['state_id' => 27, 'city' => 'Reed Point'],
                ['state_id' => 27, 'city' => 'Big Timber'],
                ['state_id' => 27, 'city' => 'Greycliff'],
                ['state_id' => 27, 'city' => 'Mc Leod'],
                ['state_id' => 27, 'city' => 'Melville'],
                ['state_id' => 27, 'city' => 'Bynum'],
                ['state_id' => 27, 'city' => 'Choteau'],
                ['state_id' => 27, 'city' => 'Dutton'],
                ['state_id' => 27, 'city' => 'Fairfield'],
                ['state_id' => 27, 'city' => 'Pendroy'],
                ['state_id' => 27, 'city' => 'Power'],
                ['state_id' => 27, 'city' => 'Ethridge'],
                ['state_id' => 27, 'city' => 'Galata'],
                ['state_id' => 27, 'city' => 'Kevin'],
                ['state_id' => 27, 'city' => 'Lothair'],
                ['state_id' => 27, 'city' => 'Oilmont'],
                ['state_id' => 27, 'city' => 'Shelby'],
                ['state_id' => 27, 'city' => 'Sunburst'],
                ['state_id' => 27, 'city' => 'Sweet Grass'],
                ['state_id' => 27, 'city' => 'Bighorn'],
                ['state_id' => 27, 'city' => 'Hysham'],
                ['state_id' => 27, 'city' => 'Sanders'],
                ['state_id' => 27, 'city' => 'Fort Peck'],
                ['state_id' => 27, 'city' => 'Frazer'],
                ['state_id' => 27, 'city' => 'Glasgow'],
                ['state_id' => 27, 'city' => 'Saint Marie'],
                ['state_id' => 27, 'city' => 'Glentana'],
                ['state_id' => 27, 'city' => 'Hinsdale'],
                ['state_id' => 27, 'city' => 'Larslan'],
                ['state_id' => 27, 'city' => 'Nashua'],
                ['state_id' => 27, 'city' => 'Opheim'],
                ['state_id' => 27, 'city' => 'Richland'],
                ['state_id' => 27, 'city' => 'Vandalia'],
                ['state_id' => 27, 'city' => 'Harlowton'],
                ['state_id' => 27, 'city' => 'Shawmut'],
                ['state_id' => 27, 'city' => 'Two Dot'],
                ['state_id' => 27, 'city' => 'Judith Gap'],
                ['state_id' => 27, 'city' => 'Wibaux'],
                ['state_id' => 27, 'city' => 'Acton'],
                ['state_id' => 27, 'city' => 'Ballantine'],
                ['state_id' => 27, 'city' => 'Broadview'],
                ['state_id' => 27, 'city' => 'Custer'],
                ['state_id' => 27, 'city' => 'Huntley'],
                ['state_id' => 27, 'city' => 'Laurel'],
                ['state_id' => 27, 'city' => 'Pompeys Pillar'],
                ['state_id' => 27, 'city' => 'Shepherd'],
                ['state_id' => 27, 'city' => 'Worden'],
                ['state_id' => 27, 'city' => 'Billings']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
