<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State14TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of IL - Illinois.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 14, 'city' => 'Quincy'],
                ['state_id' => 14, 'city' => 'Camp Point'],
                ['state_id' => 14, 'city' => 'Clayton'],
                ['state_id' => 14, 'city' => 'Coatsburg'],
                ['state_id' => 14, 'city' => 'Fowler'],
                ['state_id' => 14, 'city' => 'Golden'],
                ['state_id' => 14, 'city' => 'La Prairie'],
                ['state_id' => 14, 'city' => 'Liberty'],
                ['state_id' => 14, 'city' => 'Lima'],
                ['state_id' => 14, 'city' => 'Loraine'],
                ['state_id' => 14, 'city' => 'Mendon'],
                ['state_id' => 14, 'city' => 'Paloma'],
                ['state_id' => 14, 'city' => 'Payson'],
                ['state_id' => 14, 'city' => 'Plainville'],
                ['state_id' => 14, 'city' => 'Ursa'],
                ['state_id' => 14, 'city' => 'Cairo'],
                ['state_id' => 14, 'city' => 'Mc Clure'],
                ['state_id' => 14, 'city' => 'Miller City'],
                ['state_id' => 14, 'city' => 'Olive Branch'],
                ['state_id' => 14, 'city' => 'Tamms'],
                ['state_id' => 14, 'city' => 'Thebes'],
                ['state_id' => 14, 'city' => 'Unity'],
                ['state_id' => 14, 'city' => 'Donnellson'],
                ['state_id' => 14, 'city' => 'Sorento'],
                ['state_id' => 14, 'city' => 'Greenville'],
                ['state_id' => 14, 'city' => 'Mulberry Grove'],
                ['state_id' => 14, 'city' => 'Pierron'],
                ['state_id' => 14, 'city' => 'Pocahontas'],
                ['state_id' => 14, 'city' => 'Smithboro'],
                ['state_id' => 14, 'city' => 'Belvidere'],
                ['state_id' => 14, 'city' => 'Caledonia'],
                ['state_id' => 14, 'city' => 'Capron'],
                ['state_id' => 14, 'city' => 'Garden Prairie'],
                ['state_id' => 14, 'city' => 'Poplar Grove'],
                ['state_id' => 14, 'city' => 'Mount Sterling'],
                ['state_id' => 14, 'city' => 'Timewell'],
                ['state_id' => 14, 'city' => 'Versailles'],
                ['state_id' => 14, 'city' => 'Arlington'],
                ['state_id' => 14, 'city' => 'Buda'],
                ['state_id' => 14, 'city' => 'Bureau'],
                ['state_id' => 14, 'city' => 'Cherry'],
                ['state_id' => 14, 'city' => 'Dalzell'],
                ['state_id' => 14, 'city' => 'Depue'],
                ['state_id' => 14, 'city' => 'Dover'],
                ['state_id' => 14, 'city' => 'Kasbeer'],
                ['state_id' => 14, 'city' => 'Ladd'],
                ['state_id' => 14, 'city' => 'La Moille'],
                ['state_id' => 14, 'city' => 'Malden'],
                ['state_id' => 14, 'city' => 'Manlius'],
                ['state_id' => 14, 'city' => 'Mineral'],
                ['state_id' => 14, 'city' => 'Neponset'],
                ['state_id' => 14, 'city' => 'New Bedford'],
                ['state_id' => 14, 'city' => 'Ohio'],
                ['state_id' => 14, 'city' => 'Princeton'],
                ['state_id' => 14, 'city' => 'Seatonville'],
                ['state_id' => 14, 'city' => 'Sheffield'],
                ['state_id' => 14, 'city' => 'Spring Valley'],
                ['state_id' => 14, 'city' => 'Tiskilwa'],
                ['state_id' => 14, 'city' => 'Van Orin'],
                ['state_id' => 14, 'city' => 'Walnut'],
                ['state_id' => 14, 'city' => 'Wyanet'],
                ['state_id' => 14, 'city' => 'Batchtown'],
                ['state_id' => 14, 'city' => 'Brussels'],
                ['state_id' => 14, 'city' => 'Golden Eagle'],
                ['state_id' => 14, 'city' => 'Hamburg'],
                ['state_id' => 14, 'city' => 'Hardin'],
                ['state_id' => 14, 'city' => 'Kampsville'],
                ['state_id' => 14, 'city' => 'Michael'],
                ['state_id' => 14, 'city' => 'Mozier'],
                ['state_id' => 14, 'city' => 'Chadwick'],
                ['state_id' => 14, 'city' => 'Lanark'],
                ['state_id' => 14, 'city' => 'Milledgeville'],
                ['state_id' => 14, 'city' => 'Mount Carroll'],
                ['state_id' => 14, 'city' => 'Savanna'],
                ['state_id' => 14, 'city' => 'Shannon'],
                ['state_id' => 14, 'city' => 'Thomson'],
                ['state_id' => 14, 'city' => 'Arenzville'],
                ['state_id' => 14, 'city' => 'Ashland'],
                ['state_id' => 14, 'city' => 'Beardstown'],
                ['state_id' => 14, 'city' => 'Bluff Springs'],
                ['state_id' => 14, 'city' => 'Chandlerville'],
                ['state_id' => 14, 'city' => 'Virginia'],
                ['state_id' => 14, 'city' => 'Ludlow'],
                ['state_id' => 14, 'city' => 'Urbana'],
                ['state_id' => 14, 'city' => 'Bondville'],
                ['state_id' => 14, 'city' => 'Broadlands'],
                ['state_id' => 14, 'city' => 'Champaign'],
                ['state_id' => 14, 'city' => 'Dewey'],
                ['state_id' => 14, 'city' => 'Fisher'],
                ['state_id' => 14, 'city' => 'Foosland'],
                ['state_id' => 14, 'city' => 'Gifford'],
                ['state_id' => 14, 'city' => 'Homer'],
                ['state_id' => 14, 'city' => 'Ivesdale'],
                ['state_id' => 14, 'city' => 'Longview'],
                ['state_id' => 14, 'city' => 'Mahomet'],
                ['state_id' => 14, 'city' => 'Ogden'],
                ['state_id' => 14, 'city' => 'Penfield'],
                ['state_id' => 14, 'city' => 'Pesotum'],
                ['state_id' => 14, 'city' => 'Philo'],
                ['state_id' => 14, 'city' => 'Rantoul'],
                ['state_id' => 14, 'city' => 'Royal'],
                ['state_id' => 14, 'city' => 'Sadorus'],
                ['state_id' => 14, 'city' => 'Saint Joseph'],
                ['state_id' => 14, 'city' => 'Savoy'],
                ['state_id' => 14, 'city' => 'Seymour'],
                ['state_id' => 14, 'city' => 'Sidney'],
                ['state_id' => 14, 'city' => 'Thomasboro'],
                ['state_id' => 14, 'city' => 'Tolono'],
                ['state_id' => 14, 'city' => 'Rosamond'],
                ['state_id' => 14, 'city' => 'Assumption'],
                ['state_id' => 14, 'city' => 'Bulpitt'],
                ['state_id' => 14, 'city' => 'Edinburg'],
                ['state_id' => 14, 'city' => 'Kincaid'],
                ['state_id' => 14, 'city' => 'Morrisonville'],
                ['state_id' => 14, 'city' => 'Mount Auburn'],
                ['state_id' => 14, 'city' => 'Owaneco'],
                ['state_id' => 14, 'city' => 'Palmer'],
                ['state_id' => 14, 'city' => 'Pana'],
                ['state_id' => 14, 'city' => 'Stonington'],
                ['state_id' => 14, 'city' => 'Taylorville'],
                ['state_id' => 14, 'city' => 'Tovey'],
                ['state_id' => 14, 'city' => 'Casey'],
                ['state_id' => 14, 'city' => 'Dennison'],
                ['state_id' => 14, 'city' => 'Marshall'],
                ['state_id' => 14, 'city' => 'Martinsville'],
                ['state_id' => 14, 'city' => 'Westfield'],
                ['state_id' => 14, 'city' => 'West Union'],
                ['state_id' => 14, 'city' => 'Ingraham'],
                ['state_id' => 14, 'city' => 'Clay City'],
                ['state_id' => 14, 'city' => 'Flora'],
                ['state_id' => 14, 'city' => 'Louisville'],
                ['state_id' => 14, 'city' => 'Sailor Springs'],
                ['state_id' => 14, 'city' => 'Xenia'],
                ['state_id' => 14, 'city' => 'Albers'],
                ['state_id' => 14, 'city' => 'Aviston'],
                ['state_id' => 14, 'city' => 'Bartelso'],
                ['state_id' => 14, 'city' => 'Beckemeyer'],
                ['state_id' => 14, 'city' => 'Breese'],
                ['state_id' => 14, 'city' => 'Carlyle'],
                ['state_id' => 14, 'city' => 'Germantown'],
                ['state_id' => 14, 'city' => 'Hoffman'],
                ['state_id' => 14, 'city' => 'Huey'],
                ['state_id' => 14, 'city' => 'Keyesport'],
                ['state_id' => 14, 'city' => 'New Baden'],
                ['state_id' => 14, 'city' => 'New Memphis'],
                ['state_id' => 14, 'city' => 'Trenton'],
                ['state_id' => 14, 'city' => 'Ashmore'],
                ['state_id' => 14, 'city' => 'Charleston'],
                ['state_id' => 14, 'city' => 'Humboldt'],
                ['state_id' => 14, 'city' => 'Mattoon'],
                ['state_id' => 14, 'city' => 'Oakland'],
                ['state_id' => 14, 'city' => 'Lerna'],
                ['state_id' => 14, 'city' => 'Trilla'],
                ['state_id' => 14, 'city' => 'Arlington Heights'],
                ['state_id' => 14, 'city' => 'Elk Grove Village'],
                ['state_id' => 14, 'city' => 'Rolling Meadows'],
                ['state_id' => 14, 'city' => 'Des Plaines'],
                ['state_id' => 14, 'city' => 'Glencoe'],
                ['state_id' => 14, 'city' => 'Glenview'],
                ['state_id' => 14, 'city' => 'Golf'],
                ['state_id' => 14, 'city' => 'Palatine'],
                ['state_id' => 14, 'city' => 'Kenilworth'],
                ['state_id' => 14, 'city' => 'Morton Grove'],
                ['state_id' => 14, 'city' => 'Mount Prospect'],
                ['state_id' => 14, 'city' => 'Northbrook'],
                ['state_id' => 14, 'city' => 'Park Ridge'],
                ['state_id' => 14, 'city' => 'Prospect Heights'],
                ['state_id' => 14, 'city' => 'Skokie'],
                ['state_id' => 14, 'city' => 'Techny'],
                ['state_id' => 14, 'city' => 'Wheeling'],
                ['state_id' => 14, 'city' => 'Wilmette'],
                ['state_id' => 14, 'city' => 'Winnetka'],
                ['state_id' => 14, 'city' => 'Bartlett'],
                ['state_id' => 14, 'city' => 'Bellwood'],
                ['state_id' => 14, 'city' => 'Streamwood'],
                ['state_id' => 14, 'city' => 'Forest Park'],
                ['state_id' => 14, 'city' => 'Franklin Park'],
                ['state_id' => 14, 'city' => 'Hines'],
                ['state_id' => 14, 'city' => 'Maywood'],
                ['state_id' => 14, 'city' => 'Westchester'],
                ['state_id' => 14, 'city' => 'Broadview'],
                ['state_id' => 14, 'city' => 'Schaumburg'],
                ['state_id' => 14, 'city' => 'Melrose Park'],
                ['state_id' => 14, 'city' => 'Hillside'],
                ['state_id' => 14, 'city' => 'Berkeley'],
                ['state_id' => 14, 'city' => 'Stone Park'],
                ['state_id' => 14, 'city' => 'Hoffman Estates'],
                ['state_id' => 14, 'city' => 'River Grove'],
                ['state_id' => 14, 'city' => 'Schiller Park'],
                ['state_id' => 14, 'city' => 'Evanston'],
                ['state_id' => 14, 'city' => 'Oak Park'],
                ['state_id' => 14, 'city' => 'River Forest'],
                ['state_id' => 14, 'city' => 'Berwyn'],
                ['state_id' => 14, 'city' => 'Blue Island'],
                ['state_id' => 14, 'city' => 'Calumet City'],
                ['state_id' => 14, 'city' => 'Chicago Heights'],
                ['state_id' => 14, 'city' => 'Chicago Ridge'],
                ['state_id' => 14, 'city' => 'Crestwood'],
                ['state_id' => 14, 'city' => 'Dolton'],
                ['state_id' => 14, 'city' => 'Flossmoor'],
                ['state_id' => 14, 'city' => 'Glenwood'],
                ['state_id' => 14, 'city' => 'Harvey'],
                ['state_id' => 14, 'city' => 'Hazel Crest'],
                ['state_id' => 14, 'city' => 'Homewood'],
                ['state_id' => 14, 'city' => 'Lansing'],
                ['state_id' => 14, 'city' => 'Matteson'],
                ['state_id' => 14, 'city' => 'Midlothian'],
                ['state_id' => 14, 'city' => 'Oak Forest'],
                ['state_id' => 14, 'city' => 'Oak Lawn'],
                ['state_id' => 14, 'city' => 'Bridgeview'],
                ['state_id' => 14, 'city' => 'Hometown'],
                ['state_id' => 14, 'city' => 'Hickory Hills'],
                ['state_id' => 14, 'city' => 'Justice'],
                ['state_id' => 14, 'city' => 'Burbank'],
                ['state_id' => 14, 'city' => 'Olympia Fields'],
                ['state_id' => 14, 'city' => 'Orland Park'],
                ['state_id' => 14, 'city' => 'Palos Heights'],
                ['state_id' => 14, 'city' => 'Palos Park'],
                ['state_id' => 14, 'city' => 'Palos Hills'],
                ['state_id' => 14, 'city' => 'Park Forest'],
                ['state_id' => 14, 'city' => 'Posen'],
                ['state_id' => 14, 'city' => 'Richton Park'],
                ['state_id' => 14, 'city' => 'Robbins'],
                ['state_id' => 14, 'city' => 'South Holland'],
                ['state_id' => 14, 'city' => 'Steger'],
                ['state_id' => 14, 'city' => 'Thornton'],
                ['state_id' => 14, 'city' => 'Tinley Park'],
                ['state_id' => 14, 'city' => 'Country Club Hills'],
                ['state_id' => 14, 'city' => 'Willow Springs'],
                ['state_id' => 14, 'city' => 'Worth'],
                ['state_id' => 14, 'city' => 'Bedford Park'],
                ['state_id' => 14, 'city' => 'Summit Argo'],
                ['state_id' => 14, 'city' => 'Brookfield'],
                ['state_id' => 14, 'city' => 'La Grange'],
                ['state_id' => 14, 'city' => 'La Grange Park'],
                ['state_id' => 14, 'city' => 'Lyons'],
                ['state_id' => 14, 'city' => 'Riverside'],
                ['state_id' => 14, 'city' => 'Western Springs'],
                ['state_id' => 14, 'city' => 'Chicago'],
                ['state_id' => 14, 'city' => 'Harwood Heights'],
                ['state_id' => 14, 'city' => 'Elmwood Park'],
                ['state_id' => 14, 'city' => 'Lincolnwood'],
                ['state_id' => 14, 'city' => 'Niles'],
                ['state_id' => 14, 'city' => 'Alsip'],
                ['state_id' => 14, 'city' => 'Cicero'],
                ['state_id' => 14, 'city' => 'Evergreen Park'],
                ['state_id' => 14, 'city' => 'Riverdale'],
                ['state_id' => 14, 'city' => 'Annapolis'],
                ['state_id' => 14, 'city' => 'Flat Rock'],
                ['state_id' => 14, 'city' => 'Hutsonville'],
                ['state_id' => 14, 'city' => 'Oblong'],
                ['state_id' => 14, 'city' => 'Palestine'],
                ['state_id' => 14, 'city' => 'Robinson'],
                ['state_id' => 14, 'city' => 'Stoy'],
                ['state_id' => 14, 'city' => 'West York'],
                ['state_id' => 14, 'city' => 'Greenup'],
                ['state_id' => 14, 'city' => 'Janesville'],
                ['state_id' => 14, 'city' => 'Jewett'],
                ['state_id' => 14, 'city' => 'Neoga'],
                ['state_id' => 14, 'city' => 'Toledo'],
                ['state_id' => 14, 'city' => 'Clare'],
                ['state_id' => 14, 'city' => 'Cortland'],
                ['state_id' => 14, 'city' => 'Dekalb'],
                ['state_id' => 14, 'city' => 'Esmond'],
                ['state_id' => 14, 'city' => 'Genoa'],
                ['state_id' => 14, 'city' => 'Kingston'],
                ['state_id' => 14, 'city' => 'Kirkland'],
                ['state_id' => 14, 'city' => 'Malta'],
                ['state_id' => 14, 'city' => 'Sycamore'],
                ['state_id' => 14, 'city' => 'Hinckley'],
                ['state_id' => 14, 'city' => 'Sandwich'],
                ['state_id' => 14, 'city' => 'Shabbona'],
                ['state_id' => 14, 'city' => 'Somonauk'],
                ['state_id' => 14, 'city' => 'Waterman'],
                ['state_id' => 14, 'city' => 'Clinton'],
                ['state_id' => 14, 'city' => 'Dewitt'],
                ['state_id' => 14, 'city' => 'Kenney'],
                ['state_id' => 14, 'city' => 'Lane'],
                ['state_id' => 14, 'city' => 'Wapella'],
                ['state_id' => 14, 'city' => 'Waynesville'],
                ['state_id' => 14, 'city' => 'Farmer City'],
                ['state_id' => 14, 'city' => 'Weldon'],
                ['state_id' => 14, 'city' => 'Arcola'],
                ['state_id' => 14, 'city' => 'Arthur'],
                ['state_id' => 14, 'city' => 'Atwood'],
                ['state_id' => 14, 'city' => 'Camargo'],
                ['state_id' => 14, 'city' => 'Hindsboro'],
                ['state_id' => 14, 'city' => 'Murdock'],
                ['state_id' => 14, 'city' => 'Newman'],
                ['state_id' => 14, 'city' => 'Tuscola'],
                ['state_id' => 14, 'city' => 'Villa Grove'],
                ['state_id' => 14, 'city' => 'Addison'],
                ['state_id' => 14, 'city' => 'Bensenville'],
                ['state_id' => 14, 'city' => 'Bloomingdale'],
                ['state_id' => 14, 'city' => 'Carol Stream'],
                ['state_id' => 14, 'city' => 'Elmhurst'],
                ['state_id' => 14, 'city' => 'Hanover Park'],
                ['state_id' => 14, 'city' => 'Glen Ellyn'],
                ['state_id' => 14, 'city' => 'Glendale Heights'],
                ['state_id' => 14, 'city' => 'Itasca'],
                ['state_id' => 14, 'city' => 'Lombard'],
                ['state_id' => 14, 'city' => 'Medinah'],
                ['state_id' => 14, 'city' => 'Roselle'],
                ['state_id' => 14, 'city' => 'Villa Park'],
                ['state_id' => 14, 'city' => 'Wayne'],
                ['state_id' => 14, 'city' => 'West Chicago'],
                ['state_id' => 14, 'city' => 'Wheaton'],
                ['state_id' => 14, 'city' => 'Winfield'],
                ['state_id' => 14, 'city' => 'Wood Dale'],
                ['state_id' => 14, 'city' => 'Lemont'],
                ['state_id' => 14, 'city' => 'Aurora'],
                ['state_id' => 14, 'city' => 'Clarendon Hills'],
                ['state_id' => 14, 'city' => 'Downers Grove'],
                ['state_id' => 14, 'city' => 'Woodridge'],
                ['state_id' => 14, 'city' => 'Eola'],
                ['state_id' => 14, 'city' => 'Hinsdale'],
                ['state_id' => 14, 'city' => 'Oak Brook'],
                ['state_id' => 14, 'city' => 'Willowbrook'],
                ['state_id' => 14, 'city' => 'Lisle'],
                ['state_id' => 14, 'city' => 'Naperville'],
                ['state_id' => 14, 'city' => 'Warrenville'],
                ['state_id' => 14, 'city' => 'Westmont'],
                ['state_id' => 14, 'city' => 'Darien'],
                ['state_id' => 14, 'city' => 'Fox Valley'],
                ['state_id' => 14, 'city' => 'Brocton'],
                ['state_id' => 14, 'city' => 'Chrisman'],
                ['state_id' => 14, 'city' => 'Hume'],
                ['state_id' => 14, 'city' => 'Kansas'],
                ['state_id' => 14, 'city' => 'Metcalf'],
                ['state_id' => 14, 'city' => 'Paris'],
                ['state_id' => 14, 'city' => 'Redmon'],
                ['state_id' => 14, 'city' => 'Vermilion'],
                ['state_id' => 14, 'city' => 'West Salem'],
                ['state_id' => 14, 'city' => 'Albion'],
                ['state_id' => 14, 'city' => 'Bone Gap'],
                ['state_id' => 14, 'city' => 'Browns'],
                ['state_id' => 14, 'city' => 'Ellery'],
                ['state_id' => 14, 'city' => 'Effingham'],
                ['state_id' => 14, 'city' => 'Altamont'],
                ['state_id' => 14, 'city' => 'Beecher City'],
                ['state_id' => 14, 'city' => 'Dieterich'],
                ['state_id' => 14, 'city' => 'Edgewood'],
                ['state_id' => 14, 'city' => 'Mason'],
                ['state_id' => 14, 'city' => 'Montrose'],
                ['state_id' => 14, 'city' => 'Shumway'],
                ['state_id' => 14, 'city' => 'Teutopolis'],
                ['state_id' => 14, 'city' => 'Watson'],
                ['state_id' => 14, 'city' => 'Bingham'],
                ['state_id' => 14, 'city' => 'Ramsey'],
                ['state_id' => 14, 'city' => 'Hagarstown'],
                ['state_id' => 14, 'city' => 'Brownstown'],
                ['state_id' => 14, 'city' => 'Saint Elmo'],
                ['state_id' => 14, 'city' => 'Vandalia'],
                ['state_id' => 14, 'city' => 'Farina'],
                ['state_id' => 14, 'city' => 'Saint Peter'],
                ['state_id' => 14, 'city' => 'Shobonier'],
                ['state_id' => 14, 'city' => 'Cabery'],
                ['state_id' => 14, 'city' => 'Elliott'],
                ['state_id' => 14, 'city' => 'Gibson City'],
                ['state_id' => 14, 'city' => 'Kempton'],
                ['state_id' => 14, 'city' => 'Melvin'],
                ['state_id' => 14, 'city' => 'Paxton'],
                ['state_id' => 14, 'city' => 'Piper City'],
                ['state_id' => 14, 'city' => 'Roberts'],
                ['state_id' => 14, 'city' => 'Sibley'],
                ['state_id' => 14, 'city' => 'Benton'],
                ['state_id' => 14, 'city' => 'Buckner'],
                ['state_id' => 14, 'city' => 'Christopher'],
                ['state_id' => 14, 'city' => 'Coello'],
                ['state_id' => 14, 'city' => 'Ewing'],
                ['state_id' => 14, 'city' => 'Frankfort Heights'],
                ['state_id' => 14, 'city' => 'Logan'],
                ['state_id' => 14, 'city' => 'Mulkeytown'],
                ['state_id' => 14, 'city' => 'Orient'],
                ['state_id' => 14, 'city' => 'Sesser'],
                ['state_id' => 14, 'city' => 'Thompsonville'],
                ['state_id' => 14, 'city' => 'Valier'],
                ['state_id' => 14, 'city' => 'West Frankfort'],
                ['state_id' => 14, 'city' => 'Whittington'],
                ['state_id' => 14, 'city' => 'Royalton'],
                ['state_id' => 14, 'city' => 'Zeigler'],
                ['state_id' => 14, 'city' => 'Avon'],
                ['state_id' => 14, 'city' => 'Cuba'],
                ['state_id' => 14, 'city' => 'Ellisville'],
                ['state_id' => 14, 'city' => 'Fairview'],
                ['state_id' => 14, 'city' => 'Fiatt'],
                ['state_id' => 14, 'city' => 'Ipava'],
                ['state_id' => 14, 'city' => 'Marietta'],
                ['state_id' => 14, 'city' => 'Smithfield'],
                ['state_id' => 14, 'city' => 'Table Grove'],
                ['state_id' => 14, 'city' => 'Vermont'],
                ['state_id' => 14, 'city' => 'Astoria'],
                ['state_id' => 14, 'city' => 'Bryant'],
                ['state_id' => 14, 'city' => 'Canton'],
                ['state_id' => 14, 'city' => 'Dunfermline'],
                ['state_id' => 14, 'city' => 'Farmington'],
                ['state_id' => 14, 'city' => 'Lewistown'],
                ['state_id' => 14, 'city' => 'Liverpool'],
                ['state_id' => 14, 'city' => 'London Mills'],
                ['state_id' => 14, 'city' => 'Norris'],
                ['state_id' => 14, 'city' => 'Saint David'],
                ['state_id' => 14, 'city' => 'New Haven'],
                ['state_id' => 14, 'city' => 'Omaha'],
                ['state_id' => 14, 'city' => 'Equality'],
                ['state_id' => 14, 'city' => 'Junction'],
                ['state_id' => 14, 'city' => 'Ridgway'],
                ['state_id' => 14, 'city' => 'Shawneetown'],
                ['state_id' => 14, 'city' => 'Carrollton'],
                ['state_id' => 14, 'city' => 'Eldred'],
                ['state_id' => 14, 'city' => 'Greenfield'],
                ['state_id' => 14, 'city' => 'Hillview'],
                ['state_id' => 14, 'city' => 'Kane'],
                ['state_id' => 14, 'city' => 'Patterson'],
                ['state_id' => 14, 'city' => 'Rockbridge'],
                ['state_id' => 14, 'city' => 'Roodhouse'],
                ['state_id' => 14, 'city' => 'White Hall'],
                ['state_id' => 14, 'city' => 'Wrights'],
                ['state_id' => 14, 'city' => 'Braceville'],
                ['state_id' => 14, 'city' => 'Coal City'],
                ['state_id' => 14, 'city' => 'Gardner'],
                ['state_id' => 14, 'city' => 'Kinsman'],
                ['state_id' => 14, 'city' => 'Mazon'],
                ['state_id' => 14, 'city' => 'Minooka'],
                ['state_id' => 14, 'city' => 'Morris'],
                ['state_id' => 14, 'city' => 'South Wilmington'],
                ['state_id' => 14, 'city' => 'Verona'],
                ['state_id' => 14, 'city' => 'Broughton'],
                ['state_id' => 14, 'city' => 'Dahlgren'],
                ['state_id' => 14, 'city' => 'Dale'],
                ['state_id' => 14, 'city' => 'Mc Leansboro'],
                ['state_id' => 14, 'city' => 'Macedonia'],
                ['state_id' => 14, 'city' => 'La Harpe'],
                ['state_id' => 14, 'city' => 'Augusta'],
                ['state_id' => 14, 'city' => 'Basco'],
                ['state_id' => 14, 'city' => 'Bowen'],
                ['state_id' => 14, 'city' => 'Carthage'],
                ['state_id' => 14, 'city' => 'Colusa'],
                ['state_id' => 14, 'city' => 'Dallas City'],
                ['state_id' => 14, 'city' => 'Elvaston'],
                ['state_id' => 14, 'city' => 'Ferris'],
                ['state_id' => 14, 'city' => 'Hamilton'],
                ['state_id' => 14, 'city' => 'Nauvoo'],
                ['state_id' => 14, 'city' => 'Niota'],
                ['state_id' => 14, 'city' => 'Plymouth'],
                ['state_id' => 14, 'city' => 'Sutter'],
                ['state_id' => 14, 'city' => 'Warsaw'],
                ['state_id' => 14, 'city' => 'West Point'],
                ['state_id' => 14, 'city' => 'Cave In Rock'],
                ['state_id' => 14, 'city' => 'Elizabethtown'],
                ['state_id' => 14, 'city' => 'Karbers Ridge'],
                ['state_id' => 14, 'city' => 'Rosiclare'],
                ['state_id' => 14, 'city' => 'Biggsville'],
                ['state_id' => 14, 'city' => 'Carman'],
                ['state_id' => 14, 'city' => 'Gladstone'],
                ['state_id' => 14, 'city' => 'Lomax'],
                ['state_id' => 14, 'city' => 'Media'],
                ['state_id' => 14, 'city' => 'Oquawka'],
                ['state_id' => 14, 'city' => 'Raritan'],
                ['state_id' => 14, 'city' => 'Stronghurst'],
                ['state_id' => 14, 'city' => 'Andover'],
                ['state_id' => 14, 'city' => 'Annawan'],
                ['state_id' => 14, 'city' => 'Atkinson'],
                ['state_id' => 14, 'city' => 'Cambridge'],
                ['state_id' => 14, 'city' => 'Colona'],
                ['state_id' => 14, 'city' => 'Geneseo'],
                ['state_id' => 14, 'city' => 'Hooppole'],
                ['state_id' => 14, 'city' => 'Lynn Center'],
                ['state_id' => 14, 'city' => 'Orion'],
                ['state_id' => 14, 'city' => 'Osco'],
                ['state_id' => 14, 'city' => 'Alpha'],
                ['state_id' => 14, 'city' => 'Bishop Hill'],
                ['state_id' => 14, 'city' => 'Galva'],
                ['state_id' => 14, 'city' => 'Kewanee'],
                ['state_id' => 14, 'city' => 'Ophiem'],
                ['state_id' => 14, 'city' => 'Woodhull'],
                ['state_id' => 14, 'city' => 'Ashkum'],
                ['state_id' => 14, 'city' => 'Beaverville'],
                ['state_id' => 14, 'city' => 'Buckley'],
                ['state_id' => 14, 'city' => 'Chebanse'],
                ['state_id' => 14, 'city' => 'Cissna Park'],
                ['state_id' => 14, 'city' => 'Claytonville'],
                ['state_id' => 14, 'city' => 'Clifton'],
                ['state_id' => 14, 'city' => 'Crescent City'],
                ['state_id' => 14, 'city' => 'Danforth'],
                ['state_id' => 14, 'city' => 'Donovan'],
                ['state_id' => 14, 'city' => 'Gilman'],
                ['state_id' => 14, 'city' => 'Goodwine'],
                ['state_id' => 14, 'city' => 'Iroquois'],
                ['state_id' => 14, 'city' => 'Loda'],
                ['state_id' => 14, 'city' => 'Martinton'],
                ['state_id' => 14, 'city' => 'Milford'],
                ['state_id' => 14, 'city' => 'Onarga'],
                ['state_id' => 14, 'city' => 'Papineau'],
                ['state_id' => 14, 'city' => 'Sheldon'],
                ['state_id' => 14, 'city' => 'Stockland'],
                ['state_id' => 14, 'city' => 'Thawville'],
                ['state_id' => 14, 'city' => 'Watseka'],
                ['state_id' => 14, 'city' => 'Wellington'],
                ['state_id' => 14, 'city' => 'Woodland'],
                ['state_id' => 14, 'city' => 'Carbondale'],
                ['state_id' => 14, 'city' => 'Ava'],
                ['state_id' => 14, 'city' => 'Campbell Hill'],
                ['state_id' => 14, 'city' => 'De Soto'],
                ['state_id' => 14, 'city' => 'Dowell'],
                ['state_id' => 14, 'city' => 'Elkville'],
                ['state_id' => 14, 'city' => 'Gorham'],
                ['state_id' => 14, 'city' => 'Grand Tower'],
                ['state_id' => 14, 'city' => 'Jacob'],
                ['state_id' => 14, 'city' => 'Makanda'],
                ['state_id' => 14, 'city' => 'Murphysboro'],
                ['state_id' => 14, 'city' => 'Oraville'],
                ['state_id' => 14, 'city' => 'Pomona'],
                ['state_id' => 14, 'city' => 'Vergennes'],
                ['state_id' => 14, 'city' => 'Hidalgo'],
                ['state_id' => 14, 'city' => 'Newton'],
                ['state_id' => 14, 'city' => 'Sainte Marie'],
                ['state_id' => 14, 'city' => 'West Liberty'],
                ['state_id' => 14, 'city' => 'Wheeler'],
                ['state_id' => 14, 'city' => 'Willow Hill'],
                ['state_id' => 14, 'city' => 'Yale'],
                ['state_id' => 14, 'city' => 'Belle Rive'],
                ['state_id' => 14, 'city' => 'Bluford'],
                ['state_id' => 14, 'city' => 'Bonnie'],
                ['state_id' => 14, 'city' => 'Dix'],
                ['state_id' => 14, 'city' => 'Ina'],
                ['state_id' => 14, 'city' => 'Mount Vernon'],
                ['state_id' => 14, 'city' => 'Nason'],
                ['state_id' => 14, 'city' => 'Opdyke'],
                ['state_id' => 14, 'city' => 'Scheller'],
                ['state_id' => 14, 'city' => 'Texico'],
                ['state_id' => 14, 'city' => 'Waltonville'],
                ['state_id' => 14, 'city' => 'Woodlawn'],
                ['state_id' => 14, 'city' => 'Brighton'],
                ['state_id' => 14, 'city' => 'Dow'],
                ['state_id' => 14, 'city' => 'Elsah'],
                ['state_id' => 14, 'city' => 'Fidelity'],
                ['state_id' => 14, 'city' => 'Fieldon'],
                ['state_id' => 14, 'city' => 'Grafton'],
                ['state_id' => 14, 'city' => 'Jerseyville'],
                ['state_id' => 14, 'city' => 'Medora'],
                ['state_id' => 14, 'city' => 'Apple River'],
                ['state_id' => 14, 'city' => 'East Dubuque'],
                ['state_id' => 14, 'city' => 'Elizabeth'],
                ['state_id' => 14, 'city' => 'Galena'],
                ['state_id' => 14, 'city' => 'Hanover'],
                ['state_id' => 14, 'city' => 'Nora'],
                ['state_id' => 14, 'city' => 'Scales Mound'],
                ['state_id' => 14, 'city' => 'Stockton'],
                ['state_id' => 14, 'city' => 'Warren'],
                ['state_id' => 14, 'city' => 'Belknap'],
                ['state_id' => 14, 'city' => 'Boles'],
                ['state_id' => 14, 'city' => 'Buncombe'],
                ['state_id' => 14, 'city' => 'Cypress'],
                ['state_id' => 14, 'city' => 'Goreville'],
                ['state_id' => 14, 'city' => 'Grantsburg'],
                ['state_id' => 14, 'city' => 'New Burnside'],
                ['state_id' => 14, 'city' => 'Ozark'],
                ['state_id' => 14, 'city' => 'Simpson'],
                ['state_id' => 14, 'city' => 'Vienna'],
                ['state_id' => 14, 'city' => 'Burlington'],
                ['state_id' => 14, 'city' => 'Carpentersville'],
                ['state_id' => 14, 'city' => 'Dundee'],
                ['state_id' => 14, 'city' => 'Elburn'],
                ['state_id' => 14, 'city' => 'Elgin'],
                ['state_id' => 14, 'city' => 'Geneva'],
                ['state_id' => 14, 'city' => 'Gilberts'],
                ['state_id' => 14, 'city' => 'Hampshire'],
                ['state_id' => 14, 'city' => 'Kaneville'],
                ['state_id' => 14, 'city' => 'Lafox'],
                ['state_id' => 14, 'city' => 'Maple Park'],
                ['state_id' => 14, 'city' => 'Saint Charles'],
                ['state_id' => 14, 'city' => 'South Elgin'],
                ['state_id' => 14, 'city' => 'Wasco'],
                ['state_id' => 14, 'city' => 'Batavia'],
                ['state_id' => 14, 'city' => 'Big Rock'],
                ['state_id' => 14, 'city' => 'Mooseheart'],
                ['state_id' => 14, 'city' => 'North Aurora'],
                ['state_id' => 14, 'city' => 'Sugar Grove'],
                ['state_id' => 14, 'city' => 'Kankakee'],
                ['state_id' => 14, 'city' => 'Aroma Park'],
                ['state_id' => 14, 'city' => 'Bonfield'],
                ['state_id' => 14, 'city' => 'Bourbonnais'],
                ['state_id' => 14, 'city' => 'Bradley'],
                ['state_id' => 14, 'city' => 'Buckingham'],
                ['state_id' => 14, 'city' => 'Essex'],
                ['state_id' => 14, 'city' => 'Grant Park'],
                ['state_id' => 14, 'city' => 'Herscher'],
                ['state_id' => 14, 'city' => 'Hopkins Park'],
                ['state_id' => 14, 'city' => 'Manteno'],
                ['state_id' => 14, 'city' => 'Momence'],
                ['state_id' => 14, 'city' => 'Pembroke Township'],
                ['state_id' => 14, 'city' => 'Reddick'],
                ['state_id' => 14, 'city' => 'Saint Anne'],
                ['state_id' => 14, 'city' => 'Union Hill'],
                ['state_id' => 14, 'city' => 'Bristol'],
                ['state_id' => 14, 'city' => 'Millbrook'],
                ['state_id' => 14, 'city' => 'Millington'],
                ['state_id' => 14, 'city' => 'Montgomery'],
                ['state_id' => 14, 'city' => 'Newark'],
                ['state_id' => 14, 'city' => 'Oswego'],
                ['state_id' => 14, 'city' => 'Plano'],
                ['state_id' => 14, 'city' => 'Yorkville'],
                ['state_id' => 14, 'city' => 'Galesburg'],
                ['state_id' => 14, 'city' => 'Abingdon'],
                ['state_id' => 14, 'city' => 'Altona'],
                ['state_id' => 14, 'city' => 'Dahinda'],
                ['state_id' => 14, 'city' => 'East Galesburg'],
                ['state_id' => 14, 'city' => 'Gilson'],
                ['state_id' => 14, 'city' => 'Henderson'],
                ['state_id' => 14, 'city' => 'Knoxville'],
                ['state_id' => 14, 'city' => 'Maquon'],
                ['state_id' => 14, 'city' => 'Oneida'],
                ['state_id' => 14, 'city' => 'Rio'],
                ['state_id' => 14, 'city' => 'Saint Augustine'],
                ['state_id' => 14, 'city' => 'Victoria'],
                ['state_id' => 14, 'city' => 'Wataga'],
                ['state_id' => 14, 'city' => 'Williamsfield'],
                ['state_id' => 14, 'city' => 'Yates City'],
                ['state_id' => 14, 'city' => 'Antioch'],
                ['state_id' => 14, 'city' => 'Barrington'],
                ['state_id' => 14, 'city' => 'Deerfield'],
                ['state_id' => 14, 'city' => 'Fox Lake'],
                ['state_id' => 14, 'city' => 'Grayslake'],
                ['state_id' => 14, 'city' => 'Gurnee'],
                ['state_id' => 14, 'city' => 'Highland Park'],
                ['state_id' => 14, 'city' => 'Fort Sheridan'],
                ['state_id' => 14, 'city' => 'Highwood'],
                ['state_id' => 14, 'city' => 'Ingleside'],
                ['state_id' => 14, 'city' => 'Island Lake'],
                ['state_id' => 14, 'city' => 'Lake Bluff'],
                ['state_id' => 14, 'city' => 'Lake Forest'],
                ['state_id' => 14, 'city' => 'Lake Villa'],
                ['state_id' => 14, 'city' => 'Lake Zurich'],
                ['state_id' => 14, 'city' => 'Libertyville'],
                ['state_id' => 14, 'city' => 'Mundelein'],
                ['state_id' => 14, 'city' => 'Vernon Hills'],
                ['state_id' => 14, 'city' => 'North Chicago'],
                ['state_id' => 14, 'city' => 'Lincolnshire'],
                ['state_id' => 14, 'city' => 'Round Lake'],
                ['state_id' => 14, 'city' => 'Russell'],
                ['state_id' => 14, 'city' => 'Waukegan'],
                ['state_id' => 14, 'city' => 'Wadsworth'],
                ['state_id' => 14, 'city' => 'Wauconda'],
                ['state_id' => 14, 'city' => 'Great Lakes'],
                ['state_id' => 14, 'city' => 'Buffalo Grove'],
                ['state_id' => 14, 'city' => 'Winthrop Harbor'],
                ['state_id' => 14, 'city' => 'Zion'],
                ['state_id' => 14, 'city' => 'Ransom'],
                ['state_id' => 14, 'city' => 'Earlville'],
                ['state_id' => 14, 'city' => 'Leland'],
                ['state_id' => 14, 'city' => 'Serena'],
                ['state_id' => 14, 'city' => 'Sheridan'],
                ['state_id' => 14, 'city' => 'Wedron'],
                ['state_id' => 14, 'city' => 'La Salle'],
                ['state_id' => 14, 'city' => 'Cedar Point'],
                ['state_id' => 14, 'city' => 'Dana'],
                ['state_id' => 14, 'city' => 'Grand Ridge'],
                ['state_id' => 14, 'city' => 'Leonore'],
                ['state_id' => 14, 'city' => 'Lostant'],
                ['state_id' => 14, 'city' => 'Marseilles'],
                ['state_id' => 14, 'city' => 'Mendota'],
                ['state_id' => 14, 'city' => 'Oglesby'],
                ['state_id' => 14, 'city' => 'Ottawa'],
                ['state_id' => 14, 'city' => 'Peru'],
                ['state_id' => 14, 'city' => 'Rutland'],
                ['state_id' => 14, 'city' => 'Seneca'],
                ['state_id' => 14, 'city' => 'Streator'],
                ['state_id' => 14, 'city' => 'Tonica'],
                ['state_id' => 14, 'city' => 'Triumph'],
                ['state_id' => 14, 'city' => 'Troy Grove'],
                ['state_id' => 14, 'city' => 'Utica'],
                ['state_id' => 14, 'city' => 'Bridgeport'],
                ['state_id' => 14, 'city' => 'Lawrenceville'],
                ['state_id' => 14, 'city' => 'Saint Francisville'],
                ['state_id' => 14, 'city' => 'Sumner'],
                ['state_id' => 14, 'city' => 'Lee'],
                ['state_id' => 14, 'city' => 'Steward'],
                ['state_id' => 14, 'city' => 'Ashton'],
                ['state_id' => 14, 'city' => 'Dixon'],
                ['state_id' => 14, 'city' => 'Franklin Grove'],
                ['state_id' => 14, 'city' => 'Harmon'],
                ['state_id' => 14, 'city' => 'Nachusa'],
                ['state_id' => 14, 'city' => 'Amboy'],
                ['state_id' => 14, 'city' => 'Compton'],
                ['state_id' => 14, 'city' => 'Eldena'],
                ['state_id' => 14, 'city' => 'Lee Center'],
                ['state_id' => 14, 'city' => 'Paw Paw'],
                ['state_id' => 14, 'city' => 'Sublette'],
                ['state_id' => 14, 'city' => 'West Brooklyn'],
                ['state_id' => 14, 'city' => 'Dwight'],
                ['state_id' => 14, 'city' => 'Odell'],
                ['state_id' => 14, 'city' => 'Campus'],
                ['state_id' => 14, 'city' => 'Chatsworth'],
                ['state_id' => 14, 'city' => 'Cullom'],
                ['state_id' => 14, 'city' => 'Emington'],
                ['state_id' => 14, 'city' => 'Ancona'],
                ['state_id' => 14, 'city' => 'Blackstone'],
                ['state_id' => 14, 'city' => 'Cornell'],
                ['state_id' => 14, 'city' => 'Long Point'],
                ['state_id' => 14, 'city' => 'Fairbury'],
                ['state_id' => 14, 'city' => 'Flanagan'],
                ['state_id' => 14, 'city' => 'Forrest'],
                ['state_id' => 14, 'city' => 'Graymont'],
                ['state_id' => 14, 'city' => 'Pontiac'],
                ['state_id' => 14, 'city' => 'Saunemin'],
                ['state_id' => 14, 'city' => 'Strawn'],
                ['state_id' => 14, 'city' => 'Atlanta'],
                ['state_id' => 14, 'city' => 'Lawndale'],
                ['state_id' => 14, 'city' => 'Beason'],
                ['state_id' => 14, 'city' => 'Chestnut'],
                ['state_id' => 14, 'city' => 'Cornland'],
                ['state_id' => 14, 'city' => 'Lake Fork'],
                ['state_id' => 14, 'city' => 'Latham'],
                ['state_id' => 14, 'city' => 'Mount Pulaski'],
                ['state_id' => 14, 'city' => 'Elkhart'],
                ['state_id' => 14, 'city' => 'Emden'],
                ['state_id' => 14, 'city' => 'Hartsburg'],
                ['state_id' => 14, 'city' => 'Lincoln'],
                ['state_id' => 14, 'city' => 'Middletown'],
                ['state_id' => 14, 'city' => 'New Holland'],
                ['state_id' => 14, 'city' => 'Adair'],
                ['state_id' => 14, 'city' => 'Bardolph'],
                ['state_id' => 14, 'city' => 'Blandinsville'],
                ['state_id' => 14, 'city' => 'Bushnell'],
                ['state_id' => 14, 'city' => 'Good Hope'],
                ['state_id' => 14, 'city' => 'Industry'],
                ['state_id' => 14, 'city' => 'Macomb'],
                ['state_id' => 14, 'city' => 'Prairie City'],
                ['state_id' => 14, 'city' => 'Sciota'],
                ['state_id' => 14, 'city' => 'Colchester'],
                ['state_id' => 14, 'city' => 'Tennessee'],
                ['state_id' => 14, 'city' => 'Alden'],
                ['state_id' => 14, 'city' => 'Crystal Lake'],
                ['state_id' => 14, 'city' => 'Cary'],
                ['state_id' => 14, 'city' => 'Fox River Grove'],
                ['state_id' => 14, 'city' => 'Harvard'],
                ['state_id' => 14, 'city' => 'Hebron'],
                ['state_id' => 14, 'city' => 'Mchenry'],
                ['state_id' => 14, 'city' => 'Richmond'],
                ['state_id' => 14, 'city' => 'Ringwood'],
                ['state_id' => 14, 'city' => 'Spring Grove'],
                ['state_id' => 14, 'city' => 'Wonder Lake'],
                ['state_id' => 14, 'city' => 'Woodstock'],
                ['state_id' => 14, 'city' => 'Algonquin'],
                ['state_id' => 14, 'city' => 'Huntley'],
                ['state_id' => 14, 'city' => 'Marengo'],
                ['state_id' => 14, 'city' => 'Lake In The Hills'],
                ['state_id' => 14, 'city' => 'Union'],
                ['state_id' => 14, 'city' => 'Bloomington'],
                ['state_id' => 14, 'city' => 'Anchor'],
                ['state_id' => 14, 'city' => 'Arrowsmith'],
                ['state_id' => 14, 'city' => 'Bellflower'],
                ['state_id' => 14, 'city' => 'Carlock'],
                ['state_id' => 14, 'city' => 'Chenoa'],
                ['state_id' => 14, 'city' => 'Colfax'],
                ['state_id' => 14, 'city' => 'Cooksville'],
                ['state_id' => 14, 'city' => 'Cropsey'],
                ['state_id' => 14, 'city' => 'Danvers'],
                ['state_id' => 14, 'city' => 'Downs'],
                ['state_id' => 14, 'city' => 'Ellsworth'],
                ['state_id' => 14, 'city' => 'Gridley'],
                ['state_id' => 14, 'city' => 'Heyworth'],
                ['state_id' => 14, 'city' => 'Hudson'],
                ['state_id' => 14, 'city' => 'Le Roy'],
                ['state_id' => 14, 'city' => 'Lexington'],
                ['state_id' => 14, 'city' => 'Mc Lean'],
                ['state_id' => 14, 'city' => 'Merna'],
                ['state_id' => 14, 'city' => 'Normal'],
                ['state_id' => 14, 'city' => 'Saybrook'],
                ['state_id' => 14, 'city' => 'Shirley'],
                ['state_id' => 14, 'city' => 'Stanford'],
                ['state_id' => 14, 'city' => 'Towanda'],
                ['state_id' => 14, 'city' => 'Maroa'],
                ['state_id' => 14, 'city' => 'Argenta'],
                ['state_id' => 14, 'city' => 'Blue Mound'],
                ['state_id' => 14, 'city' => 'Boody'],
                ['state_id' => 14, 'city' => 'Decatur'],
                ['state_id' => 14, 'city' => 'Elwin'],
                ['state_id' => 14, 'city' => 'Forsyth'],
                ['state_id' => 14, 'city' => 'Harristown'],
                ['state_id' => 14, 'city' => 'Macon'],
                ['state_id' => 14, 'city' => 'Mt Zion'],
                ['state_id' => 14, 'city' => 'Niantic'],
                ['state_id' => 14, 'city' => 'Oreana'],
                ['state_id' => 14, 'city' => 'Warrensburg'],
                ['state_id' => 14, 'city' => 'Benld'],
                ['state_id' => 14, 'city' => 'Bunker Hill'],
                ['state_id' => 14, 'city' => 'Eagarville'],
                ['state_id' => 14, 'city' => 'Gillespie'],
                ['state_id' => 14, 'city' => 'Mount Olive'],
                ['state_id' => 14, 'city' => 'Piasa'],
                ['state_id' => 14, 'city' => 'Sawyerville'],
                ['state_id' => 14, 'city' => 'Staunton'],
                ['state_id' => 14, 'city' => 'Wilsonville'],
                ['state_id' => 14, 'city' => 'Carlinville'],
                ['state_id' => 14, 'city' => 'Chesterfield'],
                ['state_id' => 14, 'city' => 'Girard'],
                ['state_id' => 14, 'city' => 'Hettick'],
                ['state_id' => 14, 'city' => 'Modesto'],
                ['state_id' => 14, 'city' => 'Nilwood'],
                ['state_id' => 14, 'city' => 'Palmyra'],
                ['state_id' => 14, 'city' => 'Scottville'],
                ['state_id' => 14, 'city' => 'Shipman'],
                ['state_id' => 14, 'city' => 'Virden'],
                ['state_id' => 14, 'city' => 'Alhambra'],
                ['state_id' => 14, 'city' => 'Alton'],
                ['state_id' => 14, 'city' => 'Bethalto'],
                ['state_id' => 14, 'city' => 'Cottage Hills'],
                ['state_id' => 14, 'city' => 'Dorsey'],
                ['state_id' => 14, 'city' => 'East Alton'],
                ['state_id' => 14, 'city' => 'Edwardsville'],
                ['state_id' => 14, 'city' => 'Glen Carbon'],
                ['state_id' => 14, 'city' => 'Godfrey'],
                ['state_id' => 14, 'city' => 'Granite City'],
                ['state_id' => 14, 'city' => 'Hamel'],
                ['state_id' => 14, 'city' => 'Hartford'],
                ['state_id' => 14, 'city' => 'Livingston'],
                ['state_id' => 14, 'city' => 'Madison'],
                ['state_id' => 14, 'city' => 'Marine'],
                ['state_id' => 14, 'city' => 'Maryville'],
                ['state_id' => 14, 'city' => 'Moro'],
                ['state_id' => 14, 'city' => 'New Douglas'],
                ['state_id' => 14, 'city' => 'Roxana'],
                ['state_id' => 14, 'city' => 'South Roxana'],
                ['state_id' => 14, 'city' => 'Venice'],
                ['state_id' => 14, 'city' => 'Wood River'],
                ['state_id' => 14, 'city' => 'Worden'],
                ['state_id' => 14, 'city' => 'Collinsville'],
                ['state_id' => 14, 'city' => 'Highland'],
                ['state_id' => 14, 'city' => 'Saint Jacob'],
                ['state_id' => 14, 'city' => 'Troy'],
                ['state_id' => 14, 'city' => 'Centralia'],
                ['state_id' => 14, 'city' => 'Alma'],
                ['state_id' => 14, 'city' => 'Iuka'],
                ['state_id' => 14, 'city' => 'Kell'],
                ['state_id' => 14, 'city' => 'Kinmundy'],
                ['state_id' => 14, 'city' => 'Odin'],
                ['state_id' => 14, 'city' => 'Patoka'],
                ['state_id' => 14, 'city' => 'Salem'],
                ['state_id' => 14, 'city' => 'Sandoval'],
                ['state_id' => 14, 'city' => 'Vernon'],
                ['state_id' => 14, 'city' => 'Walnut Hill'],
                ['state_id' => 14, 'city' => 'Toluca'],
                ['state_id' => 14, 'city' => 'Varna'],
                ['state_id' => 14, 'city' => 'Wenona'],
                ['state_id' => 14, 'city' => 'Camp Grove'],
                ['state_id' => 14, 'city' => 'Henry'],
                ['state_id' => 14, 'city' => 'Lacon'],
                ['state_id' => 14, 'city' => 'La Rose'],
                ['state_id' => 14, 'city' => 'Sparland'],
                ['state_id' => 14, 'city' => 'Washburn'],
                ['state_id' => 14, 'city' => 'Forest City'],
                ['state_id' => 14, 'city' => 'Manito'],
                ['state_id' => 14, 'city' => 'Topeka'],
                ['state_id' => 14, 'city' => 'Bath'],
                ['state_id' => 14, 'city' => 'Easton'],
                ['state_id' => 14, 'city' => 'Havana'],
                ['state_id' => 14, 'city' => 'Kilbourne'],
                ['state_id' => 14, 'city' => 'Mason City'],
                ['state_id' => 14, 'city' => 'San Jose'],
                ['state_id' => 14, 'city' => 'Brookport'],
                ['state_id' => 14, 'city' => 'Joppa'],
                ['state_id' => 14, 'city' => 'Metropolis'],
                ['state_id' => 14, 'city' => 'Athens'],
                ['state_id' => 14, 'city' => 'Greenview'],
                ['state_id' => 14, 'city' => "Lincoln'S New Salem"],
                ['state_id' => 14, 'city' => 'Oakford'],
                ['state_id' => 14, 'city' => 'Petersburg'],
                ['state_id' => 14, 'city' => 'Tallula'],
                ['state_id' => 14, 'city' => 'Aledo'],
                ['state_id' => 14, 'city' => 'Joy'],
                ['state_id' => 14, 'city' => 'Matherville'],
                ['state_id' => 14, 'city' => 'New Boston'],
                ['state_id' => 14, 'city' => 'Preemption'],
                ['state_id' => 14, 'city' => 'Sherrard'],
                ['state_id' => 14, 'city' => 'Alexis'],
                ['state_id' => 14, 'city' => 'Keithsburg'],
                ['state_id' => 14, 'city' => 'New Windsor'],
                ['state_id' => 14, 'city' => 'North Henderson'],
                ['state_id' => 14, 'city' => 'Seaton'],
                ['state_id' => 14, 'city' => 'Viola'],
                ['state_id' => 14, 'city' => 'Columbia'],
                ['state_id' => 14, 'city' => 'Fults'],
                ['state_id' => 14, 'city' => 'Hecker'],
                ['state_id' => 14, 'city' => 'Maeystown'],
                ['state_id' => 14, 'city' => 'Renault'],
                ['state_id' => 14, 'city' => 'Valmeyer'],
                ['state_id' => 14, 'city' => 'Waterloo'],
                ['state_id' => 14, 'city' => 'Butler'],
                ['state_id' => 14, 'city' => 'Coffeen'],
                ['state_id' => 14, 'city' => 'Fillmore'],
                ['state_id' => 14, 'city' => 'Hillsboro'],
                ['state_id' => 14, 'city' => 'Irving'],
                ['state_id' => 14, 'city' => 'Litchfield'],
                ['state_id' => 14, 'city' => 'Nokomis'],
                ['state_id' => 14, 'city' => 'Ohlman'],
                ['state_id' => 14, 'city' => 'Panama'],
                ['state_id' => 14, 'city' => 'Taylor Springs'],
                ['state_id' => 14, 'city' => 'Walshville'],
                ['state_id' => 14, 'city' => 'Witt'],
                ['state_id' => 14, 'city' => 'Farmersville'],
                ['state_id' => 14, 'city' => 'Harvel'],
                ['state_id' => 14, 'city' => 'Raymond'],
                ['state_id' => 14, 'city' => 'Waggoner'],
                ['state_id' => 14, 'city' => 'Alexander'],
                ['state_id' => 14, 'city' => 'Chapin'],
                ['state_id' => 14, 'city' => 'Concord'],
                ['state_id' => 14, 'city' => 'Franklin'],
                ['state_id' => 14, 'city' => 'Jacksonville'],
                ['state_id' => 14, 'city' => 'Literberry'],
                ['state_id' => 14, 'city' => 'Meredosia'],
                ['state_id' => 14, 'city' => 'Murrayville'],
                ['state_id' => 14, 'city' => 'Waverly'],
                ['state_id' => 14, 'city' => 'Woodson'],
                ['state_id' => 14, 'city' => 'Bethany'],
                ['state_id' => 14, 'city' => 'Dalton City'],
                ['state_id' => 14, 'city' => 'Gays'],
                ['state_id' => 14, 'city' => 'Lovington'],
                ['state_id' => 14, 'city' => 'Sullivan'],
                ['state_id' => 14, 'city' => 'Creston'],
                ['state_id' => 14, 'city' => 'Baileyville'],
                ['state_id' => 14, 'city' => 'Byron'],
                ['state_id' => 14, 'city' => 'Chana'],
                ['state_id' => 14, 'city' => 'Davis Junction'],
                ['state_id' => 14, 'city' => 'Forreston'],
                ['state_id' => 14, 'city' => 'Holcomb'],
                ['state_id' => 14, 'city' => 'Leaf River'],
                ['state_id' => 14, 'city' => 'Lindenwood'],
                ['state_id' => 14, 'city' => 'Monroe Center'],
                ['state_id' => 14, 'city' => 'Mount Morris'],
                ['state_id' => 14, 'city' => 'Oregon'],
                ['state_id' => 14, 'city' => 'Polo'],
                ['state_id' => 14, 'city' => 'Rochelle'],
                ['state_id' => 14, 'city' => 'Stillman Valley'],
                ['state_id' => 14, 'city' => 'Woosung'],
                ['state_id' => 14, 'city' => 'Laura'],
                ['state_id' => 14, 'city' => 'Brimfield'],
                ['state_id' => 14, 'city' => 'Chillicothe'],
                ['state_id' => 14, 'city' => 'Dunlap'],
                ['state_id' => 14, 'city' => 'Edelstein'],
                ['state_id' => 14, 'city' => 'Edwards'],
                ['state_id' => 14, 'city' => 'Elmwood'],
                ['state_id' => 14, 'city' => 'Glasford'],
                ['state_id' => 14, 'city' => 'Hanna City'],
                ['state_id' => 14, 'city' => 'Kingston Mines'],
                ['state_id' => 14, 'city' => 'Mapleton'],
                ['state_id' => 14, 'city' => 'Mossville'],
                ['state_id' => 14, 'city' => 'Rome'],
                ['state_id' => 14, 'city' => 'Trivoli'],
                ['state_id' => 14, 'city' => 'Peoria'],
                ['state_id' => 14, 'city' => 'Peoria Heights'],
                ['state_id' => 14, 'city' => 'Cutler'],
                ['state_id' => 14, 'city' => 'Pinckneyville'],
                ['state_id' => 14, 'city' => 'Du Quoin'],
                ['state_id' => 14, 'city' => 'Tamaroa'],
                ['state_id' => 14, 'city' => 'Willisville'],
                ['state_id' => 14, 'city' => 'Bement'],
                ['state_id' => 14, 'city' => 'Cerro Gordo'],
                ['state_id' => 14, 'city' => 'Cisco'],
                ['state_id' => 14, 'city' => 'De Land'],
                ['state_id' => 14, 'city' => 'Mansfield'],
                ['state_id' => 14, 'city' => 'Milmine'],
                ['state_id' => 14, 'city' => 'Monticello'],
                ['state_id' => 14, 'city' => 'White Heath'],
                ['state_id' => 14, 'city' => 'Hammond'],
                ['state_id' => 14, 'city' => 'La Place'],
                ['state_id' => 14, 'city' => 'Barry'],
                ['state_id' => 14, 'city' => 'Baylis'],
                ['state_id' => 14, 'city' => 'Chambersburg'],
                ['state_id' => 14, 'city' => 'Griggsville'],
                ['state_id' => 14, 'city' => 'Hull'],
                ['state_id' => 14, 'city' => 'Kinderhook'],
                ['state_id' => 14, 'city' => 'Milton'],
                ['state_id' => 14, 'city' => 'Nebo'],
                ['state_id' => 14, 'city' => 'New Canton'],
                ['state_id' => 14, 'city' => 'New Salem'],
                ['state_id' => 14, 'city' => 'Pearl'],
                ['state_id' => 14, 'city' => 'Perry'],
                ['state_id' => 14, 'city' => 'Pittsfield'],
                ['state_id' => 14, 'city' => 'Pleasant Hill'],
                ['state_id' => 14, 'city' => 'Rockport'],
                ['state_id' => 14, 'city' => 'Eddyville'],
                ['state_id' => 14, 'city' => 'Golconda'],
                ['state_id' => 14, 'city' => 'Herod'],
                ['state_id' => 14, 'city' => 'Grand Chain'],
                ['state_id' => 14, 'city' => 'Karnak'],
                ['state_id' => 14, 'city' => 'Mound City'],
                ['state_id' => 14, 'city' => 'Mounds'],
                ['state_id' => 14, 'city' => 'Olmsted'],
                ['state_id' => 14, 'city' => 'Perks'],
                ['state_id' => 14, 'city' => 'Pulaski'],
                ['state_id' => 14, 'city' => 'Ullin'],
                ['state_id' => 14, 'city' => 'Villa Ridge'],
                ['state_id' => 14, 'city' => 'Granville'],
                ['state_id' => 14, 'city' => 'Hennepin'],
                ['state_id' => 14, 'city' => 'Mc Nabb'],
                ['state_id' => 14, 'city' => 'Magnolia'],
                ['state_id' => 14, 'city' => 'Mark'],
                ['state_id' => 14, 'city' => 'Standard'],
                ['state_id' => 14, 'city' => 'Putnam'],
                ['state_id' => 14, 'city' => 'Baldwin'],
                ['state_id' => 14, 'city' => 'Chester'],
                ['state_id' => 14, 'city' => 'Coulterville'],
                ['state_id' => 14, 'city' => 'Ellis Grove'],
                ['state_id' => 14, 'city' => 'Evansville'],
                ['state_id' => 14, 'city' => 'Menard'],
                ['state_id' => 14, 'city' => 'Modoc'],
                ['state_id' => 14, 'city' => 'Percy'],
                ['state_id' => 14, 'city' => 'Prairie Du Rocher'],
                ['state_id' => 14, 'city' => 'Red Bud'],
                ['state_id' => 14, 'city' => 'Rockwood'],
                ['state_id' => 14, 'city' => 'Sparta'],
                ['state_id' => 14, 'city' => 'Steeleville'],
                ['state_id' => 14, 'city' => 'Tilden'],
                ['state_id' => 14, 'city' => 'Walsh'],
                ['state_id' => 14, 'city' => 'Calhoun'],
                ['state_id' => 14, 'city' => 'Claremont'],
                ['state_id' => 14, 'city' => 'Dundas'],
                ['state_id' => 14, 'city' => 'Olney'],
                ['state_id' => 14, 'city' => 'Parkersburg'],
                ['state_id' => 14, 'city' => 'Noble'],
                ['state_id' => 14, 'city' => 'Rock Island'],
                ['state_id' => 14, 'city' => 'Andalusia'],
                ['state_id' => 14, 'city' => 'Barstow'],
                ['state_id' => 14, 'city' => 'Buffalo Prairie'],
                ['state_id' => 14, 'city' => 'Carbon Cliff'],
                ['state_id' => 14, 'city' => 'Coal Valley'],
                ['state_id' => 14, 'city' => 'Cordova'],
                ['state_id' => 14, 'city' => 'East Moline'],
                ['state_id' => 14, 'city' => 'Hampton'],
                ['state_id' => 14, 'city' => 'Hillsdale'],
                ['state_id' => 14, 'city' => 'Illinois City'],
                ['state_id' => 14, 'city' => 'Milan'],
                ['state_id' => 14, 'city' => 'Moline'],
                ['state_id' => 14, 'city' => 'Port Byron'],
                ['state_id' => 14, 'city' => 'Rapids City'],
                ['state_id' => 14, 'city' => 'Reynolds'],
                ['state_id' => 14, 'city' => 'Silvis'],
                ['state_id' => 14, 'city' => 'Taylor Ridge'],
                ['state_id' => 14, 'city' => 'Lovejoy'],
                ['state_id' => 14, 'city' => 'National Stock Yards'],
                ['state_id' => 14, 'city' => 'East Saint Louis'],
                ['state_id' => 14, 'city' => 'Fairview Heights'],
                ['state_id' => 14, 'city' => 'Belleville'],
                ['state_id' => 14, 'city' => 'Scott Air Force Base'],
                ['state_id' => 14, 'city' => 'Caseyville'],
                ['state_id' => 14, 'city' => 'Dupo'],
                ['state_id' => 14, 'city' => 'East Carondelet'],
                ['state_id' => 14, 'city' => 'Freeburg'],
                ['state_id' => 14, 'city' => 'Lebanon'],
                ['state_id' => 14, 'city' => 'Lenzburg'],
                ['state_id' => 14, 'city' => 'Marissa'],
                ['state_id' => 14, 'city' => 'Mascoutah'],
                ['state_id' => 14, 'city' => 'Millstadt'],
                ['state_id' => 14, 'city' => 'New Athens'],
                ['state_id' => 14, 'city' => 'O Fallon'],
                ['state_id' => 14, 'city' => 'Saint Libory'],
                ['state_id' => 14, 'city' => 'Smithton'],
                ['state_id' => 14, 'city' => 'Summerfield'],
                ['state_id' => 14, 'city' => 'Carrier Mills'],
                ['state_id' => 14, 'city' => 'Eldorado'],
                ['state_id' => 14, 'city' => 'Galatia'],
                ['state_id' => 14, 'city' => 'Harrisburg'],
                ['state_id' => 14, 'city' => 'Muddy'],
                ['state_id' => 14, 'city' => 'Raleigh'],
                ['state_id' => 14, 'city' => 'Stonefort'],
                ['state_id' => 14, 'city' => 'Buffalo'],
                ['state_id' => 14, 'city' => 'Dawson'],
                ['state_id' => 14, 'city' => 'Divernon'],
                ['state_id' => 14, 'city' => 'Glenarm'],
                ['state_id' => 14, 'city' => 'Illiopolis'],
                ['state_id' => 14, 'city' => 'Mechanicsburg'],
                ['state_id' => 14, 'city' => 'Pawnee'],
                ['state_id' => 14, 'city' => 'Riverton'],
                ['state_id' => 14, 'city' => 'Rochester'],
                ['state_id' => 14, 'city' => 'Auburn'],
                ['state_id' => 14, 'city' => 'Cantrall'],
                ['state_id' => 14, 'city' => 'Chatham'],
                ['state_id' => 14, 'city' => 'Loami'],
                ['state_id' => 14, 'city' => 'Lowder'],
                ['state_id' => 14, 'city' => 'New Berlin'],
                ['state_id' => 14, 'city' => 'Pleasant Plains'],
                ['state_id' => 14, 'city' => 'Sherman'],
                ['state_id' => 14, 'city' => 'Thayer'],
                ['state_id' => 14, 'city' => 'Williamsville'],
                ['state_id' => 14, 'city' => 'Springfield'],
                ['state_id' => 14, 'city' => 'Littleton'],
                ['state_id' => 14, 'city' => 'Camden'],
                ['state_id' => 14, 'city' => 'Huntsville'],
                ['state_id' => 14, 'city' => 'Browning'],
                ['state_id' => 14, 'city' => 'Frederick'],
                ['state_id' => 14, 'city' => 'Rushville'],
                ['state_id' => 14, 'city' => 'Alsey'],
                ['state_id' => 14, 'city' => 'Bluffs'],
                ['state_id' => 14, 'city' => 'Manchester'],
                ['state_id' => 14, 'city' => 'Winchester'],
                ['state_id' => 14, 'city' => 'Windsor'],
                ['state_id' => 14, 'city' => 'Cowden'],
                ['state_id' => 14, 'city' => 'Herrick'],
                ['state_id' => 14, 'city' => 'Lakewood'],
                ['state_id' => 14, 'city' => 'Mode'],
                ['state_id' => 14, 'city' => 'Sigel'],
                ['state_id' => 14, 'city' => 'Stewardson'],
                ['state_id' => 14, 'city' => 'Strasburg'],
                ['state_id' => 14, 'city' => 'Findlay'],
                ['state_id' => 14, 'city' => 'Moweaqua'],
                ['state_id' => 14, 'city' => 'Oconee'],
                ['state_id' => 14, 'city' => 'Shelbyville'],
                ['state_id' => 14, 'city' => 'Tower Hill'],
                ['state_id' => 14, 'city' => 'Bradford'],
                ['state_id' => 14, 'city' => 'Castleton'],
                ['state_id' => 14, 'city' => 'La Fayette'],
                ['state_id' => 14, 'city' => 'Speer'],
                ['state_id' => 14, 'city' => 'Toulon'],
                ['state_id' => 14, 'city' => 'Wyoming'],
                ['state_id' => 14, 'city' => 'Princeville'],
                ['state_id' => 14, 'city' => 'Cedarville'],
                ['state_id' => 14, 'city' => 'Dakota'],
                ['state_id' => 14, 'city' => 'Davis'],
                ['state_id' => 14, 'city' => 'Eleroy'],
                ['state_id' => 14, 'city' => 'Freeport'],
                ['state_id' => 14, 'city' => 'German Valley'],
                ['state_id' => 14, 'city' => 'Kent'],
                ['state_id' => 14, 'city' => 'Lena'],
                ['state_id' => 14, 'city' => 'Mc Connell'],
                ['state_id' => 14, 'city' => 'Orangeville'],
                ['state_id' => 14, 'city' => 'Pearl City'],
                ['state_id' => 14, 'city' => 'Ridott'],
                ['state_id' => 14, 'city' => 'Rock City'],
                ['state_id' => 14, 'city' => 'Winslow'],
                ['state_id' => 14, 'city' => 'Green Valley'],
                ['state_id' => 14, 'city' => 'Groveland'],
                ['state_id' => 14, 'city' => 'Morton'],
                ['state_id' => 14, 'city' => 'Pekin'],
                ['state_id' => 14, 'city' => 'South Pekin'],
                ['state_id' => 14, 'city' => 'Tremont'],
                ['state_id' => 14, 'city' => 'Washington'],
                ['state_id' => 14, 'city' => 'Creve Coeur'],
                ['state_id' => 14, 'city' => 'East Peoria'],
                ['state_id' => 14, 'city' => 'Armington'],
                ['state_id' => 14, 'city' => 'Deer Creek'],
                ['state_id' => 14, 'city' => 'Delavan'],
                ['state_id' => 14, 'city' => 'Hopedale'],
                ['state_id' => 14, 'city' => 'Mackinaw'],
                ['state_id' => 14, 'city' => 'Minier'],
                ['state_id' => 14, 'city' => 'Alto Pass'],
                ['state_id' => 14, 'city' => 'Anna'],
                ['state_id' => 14, 'city' => 'Cobden'],
                ['state_id' => 14, 'city' => 'Dongola'],
                ['state_id' => 14, 'city' => 'Jonesboro'],
                ['state_id' => 14, 'city' => 'Millcreek'],
                ['state_id' => 14, 'city' => 'Wolf Lake'],
                ['state_id' => 14, 'city' => 'East Lynn'],
                ['state_id' => 14, 'city' => 'Hoopeston'],
                ['state_id' => 14, 'city' => 'Rankin'],
                ['state_id' => 14, 'city' => 'Rossville'],
                ['state_id' => 14, 'city' => 'Allerton'],
                ['state_id' => 14, 'city' => 'Alvin'],
                ['state_id' => 14, 'city' => 'Armstrong'],
                ['state_id' => 14, 'city' => 'Bismarck'],
                ['state_id' => 14, 'city' => 'Catlin'],
                ['state_id' => 14, 'city' => 'Collison'],
                ['state_id' => 14, 'city' => 'Danville'],
                ['state_id' => 14, 'city' => 'Tilton'],
                ['state_id' => 14, 'city' => 'Fairmount'],
                ['state_id' => 14, 'city' => 'Fithian'],
                ['state_id' => 14, 'city' => 'Georgetown'],
                ['state_id' => 14, 'city' => 'Henning'],
                ['state_id' => 14, 'city' => 'Indianola'],
                ['state_id' => 14, 'city' => 'Muncie'],
                ['state_id' => 14, 'city' => 'Oakwood'],
                ['state_id' => 14, 'city' => 'Potomac'],
                ['state_id' => 14, 'city' => 'Ridge Farm'],
                ['state_id' => 14, 'city' => 'Sidell'],
                ['state_id' => 14, 'city' => 'Westville'],
                ['state_id' => 14, 'city' => 'Allendale'],
                ['state_id' => 14, 'city' => 'Bellmont'],
                ['state_id' => 14, 'city' => 'Keensburg'],
                ['state_id' => 14, 'city' => 'Lancaster'],
                ['state_id' => 14, 'city' => 'Mount Carmel'],
                ['state_id' => 14, 'city' => 'Berwick'],
                ['state_id' => 14, 'city' => 'Cameron'],
                ['state_id' => 14, 'city' => 'Gerlaw'],
                ['state_id' => 14, 'city' => 'Kirkwood'],
                ['state_id' => 14, 'city' => 'Little York'],
                ['state_id' => 14, 'city' => 'Monmouth'],
                ['state_id' => 14, 'city' => 'Roseville'],
                ['state_id' => 14, 'city' => 'Smithshire'],
                ['state_id' => 14, 'city' => 'Addieville'],
                ['state_id' => 14, 'city' => 'Nashville'],
                ['state_id' => 14, 'city' => 'Oakdale'],
                ['state_id' => 14, 'city' => 'Okawville'],
                ['state_id' => 14, 'city' => 'Hoyleton'],
                ['state_id' => 14, 'city' => 'Ashley'],
                ['state_id' => 14, 'city' => 'Du Bois'],
                ['state_id' => 14, 'city' => 'Irvington'],
                ['state_id' => 14, 'city' => 'Radom'],
                ['state_id' => 14, 'city' => 'Richview'],
                ['state_id' => 14, 'city' => 'Mount Erie'],
                ['state_id' => 14, 'city' => 'Barnhill'],
                ['state_id' => 14, 'city' => 'Cisne'],
                ['state_id' => 14, 'city' => 'Fairfield'],
                ['state_id' => 14, 'city' => 'Geff'],
                ['state_id' => 14, 'city' => 'Golden Gate'],
                ['state_id' => 14, 'city' => 'Johnsonville'],
                ['state_id' => 14, 'city' => 'Keenes'],
                ['state_id' => 14, 'city' => 'Rinard'],
                ['state_id' => 14, 'city' => 'Sims'],
                ['state_id' => 14, 'city' => 'Wayne City'],
                ['state_id' => 14, 'city' => 'Burnt Prairie'],
                ['state_id' => 14, 'city' => 'Carmi'],
                ['state_id' => 14, 'city' => 'Crossville'],
                ['state_id' => 14, 'city' => 'Emma'],
                ['state_id' => 14, 'city' => 'Enfield'],
                ['state_id' => 14, 'city' => 'Grayville'],
                ['state_id' => 14, 'city' => 'Maunie'],
                ['state_id' => 14, 'city' => 'Mill Shoals'],
                ['state_id' => 14, 'city' => 'Norris City'],
                ['state_id' => 14, 'city' => 'Springerton'],
                ['state_id' => 14, 'city' => 'Galt'],
                ['state_id' => 14, 'city' => 'Rock Falls'],
                ['state_id' => 14, 'city' => 'Sterling'],
                ['state_id' => 14, 'city' => 'Albany'],
                ['state_id' => 14, 'city' => 'Deer Grove'],
                ['state_id' => 14, 'city' => 'Erie'],
                ['state_id' => 14, 'city' => 'Fenton'],
                ['state_id' => 14, 'city' => 'Fulton'],
                ['state_id' => 14, 'city' => 'Lyndon'],
                ['state_id' => 14, 'city' => 'Morrison'],
                ['state_id' => 14, 'city' => 'Prophetstown'],
                ['state_id' => 14, 'city' => 'Tampico'],
                ['state_id' => 14, 'city' => 'Beecher'],
                ['state_id' => 14, 'city' => 'Crest Hill'],
                ['state_id' => 14, 'city' => 'Shorewood'],
                ['state_id' => 14, 'city' => 'Braidwood'],
                ['state_id' => 14, 'city' => 'Channahon'],
                ['state_id' => 14, 'city' => 'Crete'],
                ['state_id' => 14, 'city' => 'Elwood'],
                ['state_id' => 14, 'city' => 'Frankfort'],
                ['state_id' => 14, 'city' => 'Markham'],
                ['state_id' => 14, 'city' => 'Joliet'],
                ['state_id' => 14, 'city' => 'Bolingbrook'],
                ['state_id' => 14, 'city' => 'Lockport'],
                ['state_id' => 14, 'city' => 'Manhattan'],
                ['state_id' => 14, 'city' => 'Romeoville'],
                ['state_id' => 14, 'city' => 'Mokena'],
                ['state_id' => 14, 'city' => 'Monee'],
                ['state_id' => 14, 'city' => 'New Lenox'],
                ['state_id' => 14, 'city' => 'Peotone'],
                ['state_id' => 14, 'city' => 'Wilmington'],
                ['state_id' => 14, 'city' => 'University Park'],
                ['state_id' => 14, 'city' => 'Homer Glen'],
                ['state_id' => 14, 'city' => 'Plainfield'],
                ['state_id' => 14, 'city' => 'Freeman Spur'],
                ['state_id' => 14, 'city' => 'Cambria'],
                ['state_id' => 14, 'city' => 'Carterville'],
                ['state_id' => 14, 'city' => 'Colp'],
                ['state_id' => 14, 'city' => 'Creal Springs'],
                ['state_id' => 14, 'city' => 'Energy'],
                ['state_id' => 14, 'city' => 'Herrin'],
                ['state_id' => 14, 'city' => 'Hurst'],
                ['state_id' => 14, 'city' => 'Johnston City'],
                ['state_id' => 14, 'city' => 'Marion'],
                ['state_id' => 14, 'city' => 'Pittsburg'],
                ['state_id' => 14, 'city' => 'Cherry Valley'],
                ['state_id' => 14, 'city' => 'Durand'],
                ['state_id' => 14, 'city' => 'Pecatonica'],
                ['state_id' => 14, 'city' => 'Rockton'],
                ['state_id' => 14, 'city' => 'Roscoe'],
                ['state_id' => 14, 'city' => 'Seward'],
                ['state_id' => 14, 'city' => 'Shirland'],
                ['state_id' => 14, 'city' => 'South Beloit'],
                ['state_id' => 14, 'city' => 'Winnebago'],
                ['state_id' => 14, 'city' => 'Rockford'],
                ['state_id' => 14, 'city' => 'Loves Park'],
                ['state_id' => 14, 'city' => 'Machesney Park'],
                ['state_id' => 14, 'city' => 'Benson'],
                ['state_id' => 14, 'city' => 'Eureka'],
                ['state_id' => 14, 'city' => 'Lowpoint'],
                ['state_id' => 14, 'city' => 'Metamora'],
                ['state_id' => 14, 'city' => 'Roanoke'],
                ['state_id' => 14, 'city' => 'Congerville'],
                ['state_id' => 14, 'city' => 'El Paso'],
                ['state_id' => 14, 'city' => 'Goodfield'],
                ['state_id' => 14, 'city' => 'Minonk'],
                ['state_id' => 14, 'city' => 'Secor']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
