<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State47TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of VA - Virginia.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 47, 'city' => 'Accomac'],
                ['state_id' => 47, 'city' => 'Assawoman'],
                ['state_id' => 47, 'city' => 'Atlantic'],
                ['state_id' => 47, 'city' => 'Belle Haven'],
                ['state_id' => 47, 'city' => 'Bloxom'],
                ['state_id' => 47, 'city' => 'Chincoteague Island'],
                ['state_id' => 47, 'city' => 'Wallops Island'],
                ['state_id' => 47, 'city' => 'Craddockville'],
                ['state_id' => 47, 'city' => 'Davis Wharf'],
                ['state_id' => 47, 'city' => 'Greenbackville'],
                ['state_id' => 47, 'city' => 'Greenbush'],
                ['state_id' => 47, 'city' => 'Hacksneck'],
                ['state_id' => 47, 'city' => 'Hallwood'],
                ['state_id' => 47, 'city' => 'Harborton'],
                ['state_id' => 47, 'city' => 'Horntown'],
                ['state_id' => 47, 'city' => 'Oak Hall'],
                ['state_id' => 47, 'city' => 'Jenkins Bridge'],
                ['state_id' => 47, 'city' => 'Keller'],
                ['state_id' => 47, 'city' => 'Locustville'],
                ['state_id' => 47, 'city' => 'Mappsville'],
                ['state_id' => 47, 'city' => 'Mears'],
                ['state_id' => 47, 'city' => 'Melfa'],
                ['state_id' => 47, 'city' => 'Modest Town'],
                ['state_id' => 47, 'city' => 'Nelsonia'],
                ['state_id' => 47, 'city' => 'New Church'],
                ['state_id' => 47, 'city' => 'Onancock'],
                ['state_id' => 47, 'city' => 'Onley'],
                ['state_id' => 47, 'city' => 'Painter'],
                ['state_id' => 47, 'city' => 'Parksley'],
                ['state_id' => 47, 'city' => 'Pungoteague'],
                ['state_id' => 47, 'city' => 'Quinby'],
                ['state_id' => 47, 'city' => 'Sanford'],
                ['state_id' => 47, 'city' => 'Saxis'],
                ['state_id' => 47, 'city' => 'Tangier'],
                ['state_id' => 47, 'city' => 'Tasley'],
                ['state_id' => 47, 'city' => 'Temperanceville'],
                ['state_id' => 47, 'city' => 'Wachapreague'],
                ['state_id' => 47, 'city' => 'Wattsville'],
                ['state_id' => 47, 'city' => 'Withams'],
                ['state_id' => 47, 'city' => 'Charlottesville'],
                ['state_id' => 47, 'city' => 'Batesville'],
                ['state_id' => 47, 'city' => 'Covesville'],
                ['state_id' => 47, 'city' => 'Crozet'],
                ['state_id' => 47, 'city' => 'Earlysville'],
                ['state_id' => 47, 'city' => 'Esmont'],
                ['state_id' => 47, 'city' => 'Free Union'],
                ['state_id' => 47, 'city' => 'Greenwood'],
                ['state_id' => 47, 'city' => 'Ivy'],
                ['state_id' => 47, 'city' => 'Keene'],
                ['state_id' => 47, 'city' => 'Keswick'],
                ['state_id' => 47, 'city' => 'North Garden'],
                ['state_id' => 47, 'city' => 'White Hall'],
                ['state_id' => 47, 'city' => 'Howardsville'],
                ['state_id' => 47, 'city' => 'Scottsville'],
                ['state_id' => 47, 'city' => 'Clifton Forge'],
                ['state_id' => 47, 'city' => 'Iron Gate'],
                ['state_id' => 47, 'city' => 'Low Moor'],
                ['state_id' => 47, 'city' => 'Selma'],
                ['state_id' => 47, 'city' => 'Amelia Court House'],
                ['state_id' => 47, 'city' => 'Jetersville'],
                ['state_id' => 47, 'city' => 'Mannboro'],
                ['state_id' => 47, 'city' => 'Amherst'],
                ['state_id' => 47, 'city' => 'Clifford'],
                ['state_id' => 47, 'city' => 'Madison Heights'],
                ['state_id' => 47, 'city' => 'Monroe'],
                ['state_id' => 47, 'city' => 'Sweet Briar'],
                ['state_id' => 47, 'city' => 'Evergreen'],
                ['state_id' => 47, 'city' => 'Pamplin'],
                ['state_id' => 47, 'city' => 'Appomattox'],
                ['state_id' => 47, 'city' => 'Spout Spring'],
                ['state_id' => 47, 'city' => 'Arlington'],
                ['state_id' => 47, 'city' => 'Fort Myer'],
                ['state_id' => 47, 'city' => 'Mount Solon'],
                ['state_id' => 47, 'city' => 'Fishersville'],
                ['state_id' => 47, 'city' => 'Lyndhurst'],
                ['state_id' => 47, 'city' => 'Augusta Springs'],
                ['state_id' => 47, 'city' => 'Churchville'],
                ['state_id' => 47, 'city' => 'Craigsville'],
                ['state_id' => 47, 'city' => 'Crimora'],
                ['state_id' => 47, 'city' => 'Deerfield'],
                ['state_id' => 47, 'city' => 'Fort Defiance'],
                ['state_id' => 47, 'city' => 'Greenville'],
                ['state_id' => 47, 'city' => 'Middlebrook'],
                ['state_id' => 47, 'city' => 'Mint Spring'],
                ['state_id' => 47, 'city' => 'Mount Sidney'],
                ['state_id' => 47, 'city' => 'New Hope'],
                ['state_id' => 47, 'city' => 'Steeles Tavern'],
                ['state_id' => 47, 'city' => 'Stuarts Draft'],
                ['state_id' => 47, 'city' => 'Swoope'],
                ['state_id' => 47, 'city' => 'Verona'],
                ['state_id' => 47, 'city' => 'West Augusta'],
                ['state_id' => 47, 'city' => 'Weyers Cave'],
                ['state_id' => 47, 'city' => 'Bacova'],
                ['state_id' => 47, 'city' => 'Hot Springs'],
                ['state_id' => 47, 'city' => 'Millboro'],
                ['state_id' => 47, 'city' => 'Warm Springs'],
                ['state_id' => 47, 'city' => 'Williamsville'],
                ['state_id' => 47, 'city' => 'Goodview'],
                ['state_id' => 47, 'city' => 'Hardy'],
                ['state_id' => 47, 'city' => 'Huddleston'],
                ['state_id' => 47, 'city' => 'Moneta'],
                ['state_id' => 47, 'city' => 'Montvale'],
                ['state_id' => 47, 'city' => 'Thaxton'],
                ['state_id' => 47, 'city' => 'Villamont'],
                ['state_id' => 47, 'city' => 'Big Island'],
                ['state_id' => 47, 'city' => 'Coleman Falls'],
                ['state_id' => 47, 'city' => 'Forest'],
                ['state_id' => 47, 'city' => 'Goode'],
                ['state_id' => 47, 'city' => 'Lowry'],
                ['state_id' => 47, 'city' => 'Bastian'],
                ['state_id' => 47, 'city' => 'Bland'],
                ['state_id' => 47, 'city' => 'Ceres'],
                ['state_id' => 47, 'city' => 'Rocky Gap'],
                ['state_id' => 47, 'city' => 'Roanoke'],
                ['state_id' => 47, 'city' => 'Blue Ridge'],
                ['state_id' => 47, 'city' => 'Buchanan'],
                ['state_id' => 47, 'city' => 'Cloverdale'],
                ['state_id' => 47, 'city' => 'Daleville'],
                ['state_id' => 47, 'city' => 'Eagle Rock'],
                ['state_id' => 47, 'city' => 'Fincastle'],
                ['state_id' => 47, 'city' => 'Oriskany'],
                ['state_id' => 47, 'city' => 'Troutville'],
                ['state_id' => 47, 'city' => 'Glen Wilton'],
                ['state_id' => 47, 'city' => 'Alberta'],
                ['state_id' => 47, 'city' => 'Dolphin'],
                ['state_id' => 47, 'city' => 'Ebony'],
                ['state_id' => 47, 'city' => 'Freeman'],
                ['state_id' => 47, 'city' => 'Gasburg'],
                ['state_id' => 47, 'city' => 'Lawrenceville'],
                ['state_id' => 47, 'city' => 'Meredithville'],
                ['state_id' => 47, 'city' => 'Rawlings'],
                ['state_id' => 47, 'city' => 'Valentines'],
                ['state_id' => 47, 'city' => 'Warfield'],
                ['state_id' => 47, 'city' => 'White Plains'],
                ['state_id' => 47, 'city' => 'Brodnax'],
                ['state_id' => 47, 'city' => 'Davenport'],
                ['state_id' => 47, 'city' => 'Big Rock'],
                ['state_id' => 47, 'city' => 'Grundy'],
                ['state_id' => 47, 'city' => 'Hurley'],
                ['state_id' => 47, 'city' => 'Keen Mountain'],
                ['state_id' => 47, 'city' => 'Mavisdale'],
                ['state_id' => 47, 'city' => 'Maxie'],
                ['state_id' => 47, 'city' => 'Oakwood'],
                ['state_id' => 47, 'city' => 'Pilgrims Knob'],
                ['state_id' => 47, 'city' => 'Raven'],
                ['state_id' => 47, 'city' => 'Rowe'],
                ['state_id' => 47, 'city' => 'Shortt Gap'],
                ['state_id' => 47, 'city' => 'Vansant'],
                ['state_id' => 47, 'city' => 'Whitewood'],
                ['state_id' => 47, 'city' => 'Wolford'],
                ['state_id' => 47, 'city' => 'Arvonia'],
                ['state_id' => 47, 'city' => 'New Canton'],
                ['state_id' => 47, 'city' => 'Buckingham'],
                ['state_id' => 47, 'city' => 'Dillwyn'],
                ['state_id' => 47, 'city' => 'Lynchburg'],
                ['state_id' => 47, 'city' => 'Altavista'],
                ['state_id' => 47, 'city' => 'Brookneal'],
                ['state_id' => 47, 'city' => 'Concord'],
                ['state_id' => 47, 'city' => 'Evington'],
                ['state_id' => 47, 'city' => 'Gladys'],
                ['state_id' => 47, 'city' => 'Long Island'],
                ['state_id' => 47, 'city' => 'Lynch Station'],
                ['state_id' => 47, 'city' => 'Naruna'],
                ['state_id' => 47, 'city' => 'Rustburg'],
                ['state_id' => 47, 'city' => 'Bowling Green'],
                ['state_id' => 47, 'city' => 'Corbin'],
                ['state_id' => 47, 'city' => 'Ladysmith'],
                ['state_id' => 47, 'city' => 'Milford'],
                ['state_id' => 47, 'city' => 'Port Royal'],
                ['state_id' => 47, 'city' => 'Rappahannock Academy'],
                ['state_id' => 47, 'city' => 'Ruther Glen'],
                ['state_id' => 47, 'city' => 'Sparta'],
                ['state_id' => 47, 'city' => 'Woodford'],
                ['state_id' => 47, 'city' => 'Cana'],
                ['state_id' => 47, 'city' => 'Dugspur'],
                ['state_id' => 47, 'city' => 'Fancy Gap'],
                ['state_id' => 47, 'city' => 'Hillsville'],
                ['state_id' => 47, 'city' => 'Lambsburg'],
                ['state_id' => 47, 'city' => 'Laurel Fork'],
                ['state_id' => 47, 'city' => 'Woodlawn'],
                ['state_id' => 47, 'city' => 'Charles City'],
                ['state_id' => 47, 'city' => 'Ruthville'],
                ['state_id' => 47, 'city' => 'Charlotte Court House'],
                ['state_id' => 47, 'city' => 'Cullen'],
                ['state_id' => 47, 'city' => 'Drakes Branch'],
                ['state_id' => 47, 'city' => 'Keysville'],
                ['state_id' => 47, 'city' => 'Phenix'],
                ['state_id' => 47, 'city' => 'Randolph'],
                ['state_id' => 47, 'city' => 'Red House'],
                ['state_id' => 47, 'city' => 'Red Oak'],
                ['state_id' => 47, 'city' => 'Saxe'],
                ['state_id' => 47, 'city' => 'Wylliesburg'],
                ['state_id' => 47, 'city' => 'Midlothian'],
                ['state_id' => 47, 'city' => 'Moseley'],
                ['state_id' => 47, 'city' => 'Richmond'],
                ['state_id' => 47, 'city' => 'Chester'],
                ['state_id' => 47, 'city' => 'Chesterfield'],
                ['state_id' => 47, 'city' => 'Berryville'],
                ['state_id' => 47, 'city' => 'Boyce'],
                ['state_id' => 47, 'city' => 'Millwood'],
                ['state_id' => 47, 'city' => 'White Post'],
                ['state_id' => 47, 'city' => 'New Castle'],
                ['state_id' => 47, 'city' => 'Paint Bank'],
                ['state_id' => 47, 'city' => 'Culpeper'],
                ['state_id' => 47, 'city' => 'Boston'],
                ['state_id' => 47, 'city' => 'Brandy Station'],
                ['state_id' => 47, 'city' => 'Elkwood'],
                ['state_id' => 47, 'city' => 'Jeffersonton'],
                ['state_id' => 47, 'city' => 'Lignum'],
                ['state_id' => 47, 'city' => 'Mitchells'],
                ['state_id' => 47, 'city' => 'Rapidan'],
                ['state_id' => 47, 'city' => 'Reva'],
                ['state_id' => 47, 'city' => 'Richardsville'],
                ['state_id' => 47, 'city' => 'Rixeyville'],
                ['state_id' => 47, 'city' => 'Stevensburg'],
                ['state_id' => 47, 'city' => 'Cartersville'],
                ['state_id' => 47, 'city' => 'Cumberland'],
                ['state_id' => 47, 'city' => 'Bee'],
                ['state_id' => 47, 'city' => 'Birchleaf'],
                ['state_id' => 47, 'city' => 'Clinchco'],
                ['state_id' => 47, 'city' => 'Clintwood'],
                ['state_id' => 47, 'city' => 'Haysi'],
                ['state_id' => 47, 'city' => 'Mc Clure'],
                ['state_id' => 47, 'city' => 'Nora'],
                ['state_id' => 47, 'city' => 'Breaks'],
                ['state_id' => 47, 'city' => 'Ammon'],
                ['state_id' => 47, 'city' => 'Carson'],
                ['state_id' => 47, 'city' => 'Church Road'],
                ['state_id' => 47, 'city' => 'Dewitt'],
                ['state_id' => 47, 'city' => 'Dinwiddie'],
                ['state_id' => 47, 'city' => 'Ford'],
                ['state_id' => 47, 'city' => 'Mc Kenney'],
                ['state_id' => 47, 'city' => 'Sutherland'],
                ['state_id' => 47, 'city' => 'Wilsons'],
                ['state_id' => 47, 'city' => 'Caret'],
                ['state_id' => 47, 'city' => 'Center Cross'],
                ['state_id' => 47, 'city' => 'Champlain'],
                ['state_id' => 47, 'city' => 'Dunnsville'],
                ['state_id' => 47, 'city' => 'Hustle'],
                ['state_id' => 47, 'city' => 'Laneview'],
                ['state_id' => 47, 'city' => 'Loretto'],
                ['state_id' => 47, 'city' => 'Tappahannock'],
                ['state_id' => 47, 'city' => 'Millers Tavern'],
                ['state_id' => 47, 'city' => 'Centreville'],
                ['state_id' => 47, 'city' => 'Clifton'],
                ['state_id' => 47, 'city' => 'Chantilly'],
                ['state_id' => 47, 'city' => 'Herndon'],
                ['state_id' => 47, 'city' => 'Reston'],
                ['state_id' => 47, 'city' => 'Annandale'],
                ['state_id' => 47, 'city' => 'Burke'],
                ['state_id' => 47, 'city' => 'Dunn Loring'],
                ['state_id' => 47, 'city' => 'Fairfax'],
                ['state_id' => 47, 'city' => 'Fairfax Station'],
                ['state_id' => 47, 'city' => 'Falls Church'],
                ['state_id' => 47, 'city' => 'Fort Belvoir'],
                ['state_id' => 47, 'city' => 'Great Falls'],
                ['state_id' => 47, 'city' => 'Greenway'],
                ['state_id' => 47, 'city' => 'Lorton'],
                ['state_id' => 47, 'city' => 'Merrifield'],
                ['state_id' => 47, 'city' => 'Mc Lean'],
                ['state_id' => 47, 'city' => 'West Mclean'],
                ['state_id' => 47, 'city' => 'Mount Vernon'],
                ['state_id' => 47, 'city' => 'Newington'],
                ['state_id' => 47, 'city' => 'Oakton'],
                ['state_id' => 47, 'city' => 'Springfield'],
                ['state_id' => 47, 'city' => 'Vienna'],
                ['state_id' => 47, 'city' => 'Alexandria'],
                ['state_id' => 47, 'city' => 'Marshall'],
                ['state_id' => 47, 'city' => 'Catlett'],
                ['state_id' => 47, 'city' => 'Orlean'],
                ['state_id' => 47, 'city' => 'Paris'],
                ['state_id' => 47, 'city' => 'Broad Run'],
                ['state_id' => 47, 'city' => 'Calverton'],
                ['state_id' => 47, 'city' => 'Casanova'],
                ['state_id' => 47, 'city' => 'Rectortown'],
                ['state_id' => 47, 'city' => 'Delaplane'],
                ['state_id' => 47, 'city' => 'Upperville'],
                ['state_id' => 47, 'city' => 'Warrenton'],
                ['state_id' => 47, 'city' => 'The Plains'],
                ['state_id' => 47, 'city' => 'Hume'],
                ['state_id' => 47, 'city' => 'Markham'],
                ['state_id' => 47, 'city' => 'Bealeton'],
                ['state_id' => 47, 'city' => 'Goldvein'],
                ['state_id' => 47, 'city' => 'Midland'],
                ['state_id' => 47, 'city' => 'Remington'],
                ['state_id' => 47, 'city' => 'Somerville'],
                ['state_id' => 47, 'city' => 'Sumerduck'],
                ['state_id' => 47, 'city' => 'Check'],
                ['state_id' => 47, 'city' => 'Copper Hill'],
                ['state_id' => 47, 'city' => 'Floyd'],
                ['state_id' => 47, 'city' => 'Indian Valley'],
                ['state_id' => 47, 'city' => 'Willis'],
                ['state_id' => 47, 'city' => 'Palmyra'],
                ['state_id' => 47, 'city' => 'Troy'],
                ['state_id' => 47, 'city' => 'Bremo Bluff'],
                ['state_id' => 47, 'city' => 'Fork Union'],
                ['state_id' => 47, 'city' => 'Kents Store'],
                ['state_id' => 47, 'city' => 'Boones Mill'],
                ['state_id' => 47, 'city' => 'Callaway'],
                ['state_id' => 47, 'city' => 'Ferrum'],
                ['state_id' => 47, 'city' => 'Glade Hill'],
                ['state_id' => 47, 'city' => 'Henry'],
                ['state_id' => 47, 'city' => 'Penhook'],
                ['state_id' => 47, 'city' => 'Redwood'],
                ['state_id' => 47, 'city' => 'Rocky Mount'],
                ['state_id' => 47, 'city' => 'Union Hall'],
                ['state_id' => 47, 'city' => 'Wirtz'],
                ['state_id' => 47, 'city' => 'Winchester'],
                ['state_id' => 47, 'city' => 'Brucetown'],
                ['state_id' => 47, 'city' => 'Clear Brook'],
                ['state_id' => 47, 'city' => 'Cross Junction'],
                ['state_id' => 47, 'city' => 'Gore'],
                ['state_id' => 47, 'city' => 'Middletown'],
                ['state_id' => 47, 'city' => 'Star Tannery'],
                ['state_id' => 47, 'city' => 'Stephens City'],
                ['state_id' => 47, 'city' => 'Stephenson'],
                ['state_id' => 47, 'city' => 'Eggleston'],
                ['state_id' => 47, 'city' => 'Glen Lyn'],
                ['state_id' => 47, 'city' => 'Narrows'],
                ['state_id' => 47, 'city' => 'Newport'],
                ['state_id' => 47, 'city' => 'Pearisburg'],
                ['state_id' => 47, 'city' => 'Pembroke'],
                ['state_id' => 47, 'city' => 'Rich Creek'],
                ['state_id' => 47, 'city' => 'Ripplemead'],
                ['state_id' => 47, 'city' => 'Staffordsville'],
                ['state_id' => 47, 'city' => 'Achilles'],
                ['state_id' => 47, 'city' => 'Ark'],
                ['state_id' => 47, 'city' => 'Bena'],
                ['state_id' => 47, 'city' => 'Dutton'],
                ['state_id' => 47, 'city' => 'Gloucester'],
                ['state_id' => 47, 'city' => 'Gloucester Point'],
                ['state_id' => 47, 'city' => 'Hayes'],
                ['state_id' => 47, 'city' => 'Maryus'],
                ['state_id' => 47, 'city' => 'Ordinary'],
                ['state_id' => 47, 'city' => 'Schley'],
                ['state_id' => 47, 'city' => 'Severn'],
                ['state_id' => 47, 'city' => 'Ware Neck'],
                ['state_id' => 47, 'city' => 'White Marsh'],
                ['state_id' => 47, 'city' => 'Wicomico'],
                ['state_id' => 47, 'city' => 'Woods Cross Roads'],
                ['state_id' => 47, 'city' => 'Beaumont'],
                ['state_id' => 47, 'city' => 'Columbia'],
                ['state_id' => 47, 'city' => 'Crozier'],
                ['state_id' => 47, 'city' => 'Goochland'],
                ['state_id' => 47, 'city' => 'Gum Spring'],
                ['state_id' => 47, 'city' => 'Hadensville'],
                ['state_id' => 47, 'city' => 'Maidens'],
                ['state_id' => 47, 'city' => 'Manakin Sabot'],
                ['state_id' => 47, 'city' => 'Oilville'],
                ['state_id' => 47, 'city' => 'Sandy Hook'],
                ['state_id' => 47, 'city' => 'State Farm'],
                ['state_id' => 47, 'city' => 'Whitetop'],
                ['state_id' => 47, 'city' => 'Elk Creek'],
                ['state_id' => 47, 'city' => 'Fries'],
                ['state_id' => 47, 'city' => 'Independence'],
                ['state_id' => 47, 'city' => 'Mouth Of Wilson'],
                ['state_id' => 47, 'city' => 'Troutdale'],
                ['state_id' => 47, 'city' => 'Dyke'],
                ['state_id' => 47, 'city' => 'Quinque'],
                ['state_id' => 47, 'city' => 'Ruckersville'],
                ['state_id' => 47, 'city' => 'Stanardsville'],
                ['state_id' => 47, 'city' => 'Jarratt'],
                ['state_id' => 47, 'city' => 'Skippers'],
                ['state_id' => 47, 'city' => 'Alton'],
                ['state_id' => 47, 'city' => 'Clover'],
                ['state_id' => 47, 'city' => 'Cluster Springs'],
                ['state_id' => 47, 'city' => 'Crystal Hill'],
                ['state_id' => 47, 'city' => 'Halifax'],
                ['state_id' => 47, 'city' => 'Nathalie'],
                ['state_id' => 47, 'city' => 'Scottsburg'],
                ['state_id' => 47, 'city' => 'South Boston'],
                ['state_id' => 47, 'city' => 'Vernon Hill'],
                ['state_id' => 47, 'city' => 'Virgilina'],
                ['state_id' => 47, 'city' => 'Ashland'],
                ['state_id' => 47, 'city' => 'Beaverdam'],
                ['state_id' => 47, 'city' => 'Doswell'],
                ['state_id' => 47, 'city' => 'Glen Allen'],
                ['state_id' => 47, 'city' => 'Hanover'],
                ['state_id' => 47, 'city' => 'Mechanicsville'],
                ['state_id' => 47, 'city' => 'Rockville'],
                ['state_id' => 47, 'city' => 'Studley'],
                ['state_id' => 47, 'city' => 'Montpelier'],
                ['state_id' => 47, 'city' => 'Henrico'],
                ['state_id' => 47, 'city' => 'Sandston'],
                ['state_id' => 47, 'city' => 'Axton'],
                ['state_id' => 47, 'city' => 'Bassett'],
                ['state_id' => 47, 'city' => 'Collinsville'],
                ['state_id' => 47, 'city' => 'Fieldale'],
                ['state_id' => 47, 'city' => 'Ridgeway'],
                ['state_id' => 47, 'city' => 'Spencer'],
                ['state_id' => 47, 'city' => 'Stanleytown'],
                ['state_id' => 47, 'city' => 'Blue Grass'],
                ['state_id' => 47, 'city' => 'Doe Hill'],
                ['state_id' => 47, 'city' => 'Head Waters'],
                ['state_id' => 47, 'city' => 'Mc Dowell'],
                ['state_id' => 47, 'city' => 'Monterey'],
                ['state_id' => 47, 'city' => 'Mustoe'],
                ['state_id' => 47, 'city' => 'Battery Park'],
                ['state_id' => 47, 'city' => 'Carrollton'],
                ['state_id' => 47, 'city' => 'Carrsville'],
                ['state_id' => 47, 'city' => 'Isle Of Wight'],
                ['state_id' => 47, 'city' => 'Rescue'],
                ['state_id' => 47, 'city' => 'Smithfield'],
                ['state_id' => 47, 'city' => 'Windsor'],
                ['state_id' => 47, 'city' => 'Zuni'],
                ['state_id' => 47, 'city' => 'Jamestown'],
                ['state_id' => 47, 'city' => 'Norge'],
                ['state_id' => 47, 'city' => 'Toano'],
                ['state_id' => 47, 'city' => 'Williamsburg'],
                ['state_id' => 47, 'city' => 'Bruington'],
                ['state_id' => 47, 'city' => 'King And Queen Court House'],
                ['state_id' => 47, 'city' => 'Little Plymouth'],
                ['state_id' => 47, 'city' => 'Mascot'],
                ['state_id' => 47, 'city' => 'Mattaponi'],
                ['state_id' => 47, 'city' => 'Newtown'],
                ['state_id' => 47, 'city' => 'Saint Stephens Church'],
                ['state_id' => 47, 'city' => 'Shacklefords'],
                ['state_id' => 47, 'city' => 'Stevensville'],
                ['state_id' => 47, 'city' => 'Walkerton'],
                ['state_id' => 47, 'city' => 'Dahlgren'],
                ['state_id' => 47, 'city' => 'Dogue'],
                ['state_id' => 47, 'city' => 'Jersey'],
                ['state_id' => 47, 'city' => 'King George'],
                ['state_id' => 47, 'city' => 'Ninde'],
                ['state_id' => 47, 'city' => 'Rollins Fork'],
                ['state_id' => 47, 'city' => 'Sealston'],
                ['state_id' => 47, 'city' => 'Aylett'],
                ['state_id' => 47, 'city' => 'King William'],
                ['state_id' => 47, 'city' => 'Manquin'],
                ['state_id' => 47, 'city' => 'West Point'],
                ['state_id' => 47, 'city' => 'Irvington'],
                ['state_id' => 47, 'city' => 'Kilmarnock'],
                ['state_id' => 47, 'city' => 'Lancaster'],
                ['state_id' => 47, 'city' => 'Lively'],
                ['state_id' => 47, 'city' => 'Merry Point'],
                ['state_id' => 47, 'city' => 'Mollusk'],
                ['state_id' => 47, 'city' => 'Morattico'],
                ['state_id' => 47, 'city' => 'Nuttsville'],
                ['state_id' => 47, 'city' => 'Weems'],
                ['state_id' => 47, 'city' => 'White Stone'],
                ['state_id' => 47, 'city' => 'Ben Hur'],
                ['state_id' => 47, 'city' => 'Blackwater'],
                ['state_id' => 47, 'city' => 'Dryden'],
                ['state_id' => 47, 'city' => 'Ewing'],
                ['state_id' => 47, 'city' => 'Jonesville'],
                ['state_id' => 47, 'city' => 'Keokee'],
                ['state_id' => 47, 'city' => 'Pennington Gap'],
                ['state_id' => 47, 'city' => 'Rose Hill'],
                ['state_id' => 47, 'city' => 'Saint Charles'],
                ['state_id' => 47, 'city' => 'Dulles'],
                ['state_id' => 47, 'city' => 'Aldie'],
                ['state_id' => 47, 'city' => 'Middleburg'],
                ['state_id' => 47, 'city' => 'Paeonian Springs'],
                ['state_id' => 47, 'city' => 'Philomont'],
                ['state_id' => 47, 'city' => 'Purcellville'],
                ['state_id' => 47, 'city' => 'Bluemont'],
                ['state_id' => 47, 'city' => 'Round Hill'],
                ['state_id' => 47, 'city' => 'Ashburn'],
                ['state_id' => 47, 'city' => 'Hamilton'],
                ['state_id' => 47, 'city' => 'Lincoln'],
                ['state_id' => 47, 'city' => 'Sterling'],
                ['state_id' => 47, 'city' => 'Leesburg'],
                ['state_id' => 47, 'city' => 'Lovettsville'],
                ['state_id' => 47, 'city' => 'Waterford'],
                ['state_id' => 47, 'city' => 'Dhs'],
                ['state_id' => 47, 'city' => 'Bumpass'],
                ['state_id' => 47, 'city' => 'Louisa'],
                ['state_id' => 47, 'city' => 'Mineral'],
                ['state_id' => 47, 'city' => 'Trevilians'],
                ['state_id' => 47, 'city' => 'Dundas'],
                ['state_id' => 47, 'city' => 'Fort Mitchell'],
                ['state_id' => 47, 'city' => 'Kenbridge'],
                ['state_id' => 47, 'city' => 'Lunenburg'],
                ['state_id' => 47, 'city' => 'Victoria'],
                ['state_id' => 47, 'city' => 'Aroda'],
                ['state_id' => 47, 'city' => 'Banco'],
                ['state_id' => 47, 'city' => 'Brightwood'],
                ['state_id' => 47, 'city' => 'Etlan'],
                ['state_id' => 47, 'city' => 'Haywood'],
                ['state_id' => 47, 'city' => 'Hood'],
                ['state_id' => 47, 'city' => 'Leon'],
                ['state_id' => 47, 'city' => 'Madison'],
                ['state_id' => 47, 'city' => 'Oakpark'],
                ['state_id' => 47, 'city' => 'Pratts'],
                ['state_id' => 47, 'city' => 'Radiant'],
                ['state_id' => 47, 'city' => 'Rochelle'],
                ['state_id' => 47, 'city' => 'Syria'],
                ['state_id' => 47, 'city' => 'Wolftown'],
                ['state_id' => 47, 'city' => 'Locust Dale'],
                ['state_id' => 47, 'city' => 'Woodberry Forest'],
                ['state_id' => 47, 'city' => 'Bohannon'],
                ['state_id' => 47, 'city' => 'Cardinal'],
                ['state_id' => 47, 'city' => 'Cobbs Creek'],
                ['state_id' => 47, 'city' => 'Diggs'],
                ['state_id' => 47, 'city' => 'Foster'],
                ['state_id' => 47, 'city' => 'Grimstead'],
                ['state_id' => 47, 'city' => 'Gwynn'],
                ['state_id' => 47, 'city' => 'Hallieford'],
                ['state_id' => 47, 'city' => 'Hudgins'],
                ['state_id' => 47, 'city' => 'Mathews'],
                ['state_id' => 47, 'city' => 'Moon'],
                ['state_id' => 47, 'city' => 'New Point'],
                ['state_id' => 47, 'city' => 'North'],
                ['state_id' => 47, 'city' => 'Onemo'],
                ['state_id' => 47, 'city' => 'Port Haywood'],
                ['state_id' => 47, 'city' => 'Susan'],
                ['state_id' => 47, 'city' => 'Baskerville'],
                ['state_id' => 47, 'city' => 'Boydton'],
                ['state_id' => 47, 'city' => 'Bracey'],
                ['state_id' => 47, 'city' => 'Chase City'],
                ['state_id' => 47, 'city' => 'Clarksville'],
                ['state_id' => 47, 'city' => 'La Crosse'],
                ['state_id' => 47, 'city' => 'Skipwith'],
                ['state_id' => 47, 'city' => 'South Hill'],
                ['state_id' => 47, 'city' => 'Buffalo Junction'],
                ['state_id' => 47, 'city' => 'Nelson'],
                ['state_id' => 47, 'city' => 'Christchurch'],
                ['state_id' => 47, 'city' => 'Church View'],
                ['state_id' => 47, 'city' => 'Deltaville'],
                ['state_id' => 47, 'city' => 'Hardyville'],
                ['state_id' => 47, 'city' => 'Hartfield'],
                ['state_id' => 47, 'city' => 'Jamaica'],
                ['state_id' => 47, 'city' => 'Locust Hill'],
                ['state_id' => 47, 'city' => 'Saluda'],
                ['state_id' => 47, 'city' => 'Topping'],
                ['state_id' => 47, 'city' => 'Urbanna'],
                ['state_id' => 47, 'city' => 'Wake'],
                ['state_id' => 47, 'city' => 'Water View'],
                ['state_id' => 47, 'city' => 'Blacksburg'],
                ['state_id' => 47, 'city' => 'Christiansburg'],
                ['state_id' => 47, 'city' => 'Mc Coy'],
                ['state_id' => 47, 'city' => 'Pilot'],
                ['state_id' => 47, 'city' => 'Riner'],
                ['state_id' => 47, 'city' => 'Shawsville'],
                ['state_id' => 47, 'city' => 'Afton'],
                ['state_id' => 47, 'city' => 'Arrington'],
                ['state_id' => 47, 'city' => 'Faber'],
                ['state_id' => 47, 'city' => 'Lovingston'],
                ['state_id' => 47, 'city' => 'Nellysford'],
                ['state_id' => 47, 'city' => 'Piney River'],
                ['state_id' => 47, 'city' => 'Roseland'],
                ['state_id' => 47, 'city' => 'Schuyler'],
                ['state_id' => 47, 'city' => 'Shipman'],
                ['state_id' => 47, 'city' => 'Tyro'],
                ['state_id' => 47, 'city' => 'Montebello'],
                ['state_id' => 47, 'city' => 'Gladstone'],
                ['state_id' => 47, 'city' => 'Norwood'],
                ['state_id' => 47, 'city' => 'Wingina'],
                ['state_id' => 47, 'city' => 'Barhamsville'],
                ['state_id' => 47, 'city' => 'Lanexa'],
                ['state_id' => 47, 'city' => 'New Kent'],
                ['state_id' => 47, 'city' => 'Providence Forge'],
                ['state_id' => 47, 'city' => 'Quinton'],
                ['state_id' => 47, 'city' => 'Birdsnest'],
                ['state_id' => 47, 'city' => 'Cape Charles'],
                ['state_id' => 47, 'city' => 'Capeville'],
                ['state_id' => 47, 'city' => 'Cheriton'],
                ['state_id' => 47, 'city' => 'Eastville'],
                ['state_id' => 47, 'city' => 'Exmore'],
                ['state_id' => 47, 'city' => 'Franktown'],
                ['state_id' => 47, 'city' => 'Jamesville'],
                ['state_id' => 47, 'city' => 'Machipongo'],
                ['state_id' => 47, 'city' => 'Marionville'],
                ['state_id' => 47, 'city' => 'Nassawadox'],
                ['state_id' => 47, 'city' => 'Oyster'],
                ['state_id' => 47, 'city' => 'Seaview'],
                ['state_id' => 47, 'city' => 'Townsend'],
                ['state_id' => 47, 'city' => 'Wardtown'],
                ['state_id' => 47, 'city' => 'Willis Wharf'],
                ['state_id' => 47, 'city' => 'Burgess'],
                ['state_id' => 47, 'city' => 'Callao'],
                ['state_id' => 47, 'city' => 'Edwardsville'],
                ['state_id' => 47, 'city' => 'Heathsville'],
                ['state_id' => 47, 'city' => 'Lottsburg'],
                ['state_id' => 47, 'city' => 'Ophelia'],
                ['state_id' => 47, 'city' => 'Reedville'],
                ['state_id' => 47, 'city' => 'Wicomico Church'],
                ['state_id' => 47, 'city' => 'Blackstone'],
                ['state_id' => 47, 'city' => 'Burkeville'],
                ['state_id' => 47, 'city' => 'Crewe'],
                ['state_id' => 47, 'city' => 'Nottoway'],
                ['state_id' => 47, 'city' => 'Burr Hill'],
                ['state_id' => 47, 'city' => 'Locust Grove'],
                ['state_id' => 47, 'city' => 'Rhoadesville'],
                ['state_id' => 47, 'city' => 'Unionville'],
                ['state_id' => 47, 'city' => 'Barboursville'],
                ['state_id' => 47, 'city' => 'Gordonsville'],
                ['state_id' => 47, 'city' => 'Montpelier Station'],
                ['state_id' => 47, 'city' => 'Orange'],
                ['state_id' => 47, 'city' => 'Somerset'],
                ['state_id' => 47, 'city' => 'Rileyville'],
                ['state_id' => 47, 'city' => 'Luray'],
                ['state_id' => 47, 'city' => 'Shenandoah'],
                ['state_id' => 47, 'city' => 'Stanley'],
                ['state_id' => 47, 'city' => 'Ararat'],
                ['state_id' => 47, 'city' => 'Claudville'],
                ['state_id' => 47, 'city' => 'Critz'],
                ['state_id' => 47, 'city' => 'Meadows Of Dan'],
                ['state_id' => 47, 'city' => 'Patrick Springs'],
                ['state_id' => 47, 'city' => 'Stuart'],
                ['state_id' => 47, 'city' => 'Vesta'],
                ['state_id' => 47, 'city' => 'Woolwine'],
                ['state_id' => 47, 'city' => 'Cascade'],
                ['state_id' => 47, 'city' => 'Pittsville'],
                ['state_id' => 47, 'city' => 'Sandy Level'],
                ['state_id' => 47, 'city' => 'Blairs'],
                ['state_id' => 47, 'city' => 'Callands'],
                ['state_id' => 47, 'city' => 'Chatham'],
                ['state_id' => 47, 'city' => 'Dry Fork'],
                ['state_id' => 47, 'city' => 'Gretna'],
                ['state_id' => 47, 'city' => 'Hurt'],
                ['state_id' => 47, 'city' => 'Java'],
                ['state_id' => 47, 'city' => 'Keeling'],
                ['state_id' => 47, 'city' => 'Ringgold'],
                ['state_id' => 47, 'city' => 'Sutherlin'],
                ['state_id' => 47, 'city' => 'Powhatan'],
                ['state_id' => 47, 'city' => 'Farmville'],
                ['state_id' => 47, 'city' => 'Green Bay'],
                ['state_id' => 47, 'city' => 'Hampden Sydney'],
                ['state_id' => 47, 'city' => 'Meherrin'],
                ['state_id' => 47, 'city' => 'Prospect'],
                ['state_id' => 47, 'city' => 'Rice'],
                ['state_id' => 47, 'city' => 'Fort Lee'],
                ['state_id' => 47, 'city' => 'Disputanta'],
                ['state_id' => 47, 'city' => 'Prince George'],
                ['state_id' => 47, 'city' => 'Bristow'],
                ['state_id' => 47, 'city' => 'Catharpin'],
                ['state_id' => 47, 'city' => 'Gainesville'],
                ['state_id' => 47, 'city' => 'Haymarket'],
                ['state_id' => 47, 'city' => 'Nokesville'],
                ['state_id' => 47, 'city' => 'Dumfries'],
                ['state_id' => 47, 'city' => 'Occoquan'],
                ['state_id' => 47, 'city' => 'Quantico'],
                ['state_id' => 47, 'city' => 'Triangle'],
                ['state_id' => 47, 'city' => 'Woodbridge'],
                ['state_id' => 47, 'city' => 'Belspring'],
                ['state_id' => 47, 'city' => 'Dublin'],
                ['state_id' => 47, 'city' => 'Newbern'],
                ['state_id' => 47, 'city' => 'New River'],
                ['state_id' => 47, 'city' => 'Parrott'],
                ['state_id' => 47, 'city' => 'Pulaski'],
                ['state_id' => 47, 'city' => 'Draper'],
                ['state_id' => 47, 'city' => 'Hiwassee'],
                ['state_id' => 47, 'city' => 'Amissville'],
                ['state_id' => 47, 'city' => 'Chester Gap'],
                ['state_id' => 47, 'city' => 'Flint Hill'],
                ['state_id' => 47, 'city' => 'Huntly'],
                ['state_id' => 47, 'city' => 'Castleton'],
                ['state_id' => 47, 'city' => 'Sperryville'],
                ['state_id' => 47, 'city' => 'Viewtown'],
                ['state_id' => 47, 'city' => 'Washington'],
                ['state_id' => 47, 'city' => 'Woodville'],
                ['state_id' => 47, 'city' => 'Farnham'],
                ['state_id' => 47, 'city' => 'Haynesville'],
                ['state_id' => 47, 'city' => 'Sharps'],
                ['state_id' => 47, 'city' => 'Village'],
                ['state_id' => 47, 'city' => 'Warsaw'],
                ['state_id' => 47, 'city' => 'Bent Mountain'],
                ['state_id' => 47, 'city' => 'Catawba'],
                ['state_id' => 47, 'city' => 'Elliston'],
                ['state_id' => 47, 'city' => 'Vinton'],
                ['state_id' => 47, 'city' => 'Brownsburg'],
                ['state_id' => 47, 'city' => 'Fairfield'],
                ['state_id' => 47, 'city' => 'Goshen'],
                ['state_id' => 47, 'city' => 'Raphine'],
                ['state_id' => 47, 'city' => 'Rockbridge Baths'],
                ['state_id' => 47, 'city' => 'Vesuvius'],
                ['state_id' => 47, 'city' => 'Glasgow'],
                ['state_id' => 47, 'city' => 'Natural Bridge'],
                ['state_id' => 47, 'city' => 'Natural Bridge Station'],
                ['state_id' => 47, 'city' => 'Harrisonburg'],
                ['state_id' => 47, 'city' => 'Bergton'],
                ['state_id' => 47, 'city' => 'Bridgewater'],
                ['state_id' => 47, 'city' => 'Broadway'],
                ['state_id' => 47, 'city' => 'Criders'],
                ['state_id' => 47, 'city' => 'Dayton'],
                ['state_id' => 47, 'city' => 'Elkton'],
                ['state_id' => 47, 'city' => 'Fulks Run'],
                ['state_id' => 47, 'city' => 'Hinton'],
                ['state_id' => 47, 'city' => 'Keezletown'],
                ['state_id' => 47, 'city' => 'Lacey Spring'],
                ['state_id' => 47, 'city' => 'Linville'],
                ['state_id' => 47, 'city' => 'Mc Gaheysville'],
                ['state_id' => 47, 'city' => 'Mount Crawford'],
                ['state_id' => 47, 'city' => 'Penn Laird'],
                ['state_id' => 47, 'city' => 'Pleasant Valley'],
                ['state_id' => 47, 'city' => 'Singers Glen'],
                ['state_id' => 47, 'city' => 'Timberville'],
                ['state_id' => 47, 'city' => 'Grottoes'],
                ['state_id' => 47, 'city' => 'Port Republic'],
                ['state_id' => 47, 'city' => 'Castlewood'],
                ['state_id' => 47, 'city' => 'Cleveland'],
                ['state_id' => 47, 'city' => 'Dante'],
                ['state_id' => 47, 'city' => 'Honaker'],
                ['state_id' => 47, 'city' => 'Lebanon'],
                ['state_id' => 47, 'city' => 'Rosedale'],
                ['state_id' => 47, 'city' => 'Swords Creek'],
                ['state_id' => 47, 'city' => 'Duffield'],
                ['state_id' => 47, 'city' => 'Dungannon'],
                ['state_id' => 47, 'city' => 'Fort Blackmore'],
                ['state_id' => 47, 'city' => 'Gate City'],
                ['state_id' => 47, 'city' => 'Hiltons'],
                ['state_id' => 47, 'city' => 'Nickelsville'],
                ['state_id' => 47, 'city' => 'Weber City'],
                ['state_id' => 47, 'city' => 'Fishers Hill'],
                ['state_id' => 47, 'city' => 'Strasburg'],
                ['state_id' => 47, 'city' => 'Maurertown'],
                ['state_id' => 47, 'city' => 'Fort Valley'],
                ['state_id' => 47, 'city' => 'Toms Brook'],
                ['state_id' => 47, 'city' => 'Woodstock'],
                ['state_id' => 47, 'city' => 'Basye'],
                ['state_id' => 47, 'city' => 'Edinburg'],
                ['state_id' => 47, 'city' => 'Mount Jackson'],
                ['state_id' => 47, 'city' => 'New Market'],
                ['state_id' => 47, 'city' => 'Orkney Springs'],
                ['state_id' => 47, 'city' => 'Quicksburg'],
                ['state_id' => 47, 'city' => 'Atkins'],
                ['state_id' => 47, 'city' => 'Broadford'],
                ['state_id' => 47, 'city' => 'Chilhowie'],
                ['state_id' => 47, 'city' => 'Marion'],
                ['state_id' => 47, 'city' => 'Saltville'],
                ['state_id' => 47, 'city' => 'Sugar Grove'],
                ['state_id' => 47, 'city' => 'Boykins'],
                ['state_id' => 47, 'city' => 'Branchville'],
                ['state_id' => 47, 'city' => 'Capron'],
                ['state_id' => 47, 'city' => 'Courtland'],
                ['state_id' => 47, 'city' => 'Drewryville'],
                ['state_id' => 47, 'city' => 'Ivor'],
                ['state_id' => 47, 'city' => 'Newsoms'],
                ['state_id' => 47, 'city' => 'Sedley'],
                ['state_id' => 47, 'city' => 'Fredericksburg'],
                ['state_id' => 47, 'city' => 'Partlow'],
                ['state_id' => 47, 'city' => 'Spotsylvania'],
                ['state_id' => 47, 'city' => 'Thornburg'],
                ['state_id' => 47, 'city' => 'Brooke'],
                ['state_id' => 47, 'city' => 'Garrisonville'],
                ['state_id' => 47, 'city' => 'Hartwood'],
                ['state_id' => 47, 'city' => 'Ruby'],
                ['state_id' => 47, 'city' => 'Stafford'],
                ['state_id' => 47, 'city' => 'Dendron'],
                ['state_id' => 47, 'city' => 'Elberon'],
                ['state_id' => 47, 'city' => 'Spring Grove'],
                ['state_id' => 47, 'city' => 'Surry'],
                ['state_id' => 47, 'city' => 'Claremont'],
                ['state_id' => 47, 'city' => 'Stony Creek'],
                ['state_id' => 47, 'city' => 'Sussex'],
                ['state_id' => 47, 'city' => 'Wakefield'],
                ['state_id' => 47, 'city' => 'Waverly'],
                ['state_id' => 47, 'city' => 'Yale'],
                ['state_id' => 47, 'city' => 'Tannersville'],
                ['state_id' => 47, 'city' => 'Amonate'],
                ['state_id' => 47, 'city' => 'Bandy'],
                ['state_id' => 47, 'city' => 'Bishop'],
                ['state_id' => 47, 'city' => 'Bluefield'],
                ['state_id' => 47, 'city' => 'Boissevain'],
                ['state_id' => 47, 'city' => 'Burkes Garden'],
                ['state_id' => 47, 'city' => 'Cedar Bluff'],
                ['state_id' => 47, 'city' => 'Doran'],
                ['state_id' => 47, 'city' => 'Falls Mills'],
                ['state_id' => 47, 'city' => 'Horsepen'],
                ['state_id' => 47, 'city' => 'Jewell Ridge'],
                ['state_id' => 47, 'city' => 'North Tazewell'],
                ['state_id' => 47, 'city' => 'Pocahontas'],
                ['state_id' => 47, 'city' => 'Pounding Mill'],
                ['state_id' => 47, 'city' => 'Red Ash'],
                ['state_id' => 47, 'city' => 'Richlands'],
                ['state_id' => 47, 'city' => 'Tazewell'],
                ['state_id' => 47, 'city' => 'Bentonville'],
                ['state_id' => 47, 'city' => 'Front Royal'],
                ['state_id' => 47, 'city' => 'Linden'],
                ['state_id' => 47, 'city' => 'Abingdon'],
                ['state_id' => 47, 'city' => 'Damascus'],
                ['state_id' => 47, 'city' => 'Mendota'],
                ['state_id' => 47, 'city' => 'Emory'],
                ['state_id' => 47, 'city' => 'Glade Spring'],
                ['state_id' => 47, 'city' => 'Meadowview'],
                ['state_id' => 47, 'city' => 'Coles Point'],
                ['state_id' => 47, 'city' => 'Colonial Beach'],
                ['state_id' => 47, 'city' => 'Hague'],
                ['state_id' => 47, 'city' => 'Kinsale'],
                ['state_id' => 47, 'city' => 'Montross'],
                ['state_id' => 47, 'city' => 'Mount Holly'],
                ['state_id' => 47, 'city' => 'Oldhams'],
                ['state_id' => 47, 'city' => 'Stratford'],
                ['state_id' => 47, 'city' => 'Sandy Point'],
                ['state_id' => 47, 'city' => 'Zacata'],
                ['state_id' => 47, 'city' => 'Andover'],
                ['state_id' => 47, 'city' => 'Appalachia'],
                ['state_id' => 47, 'city' => 'Big Stone Gap'],
                ['state_id' => 47, 'city' => 'Coeburn'],
                ['state_id' => 47, 'city' => 'East Stone Gap'],
                ['state_id' => 47, 'city' => 'Pound'],
                ['state_id' => 47, 'city' => 'Saint Paul'],
                ['state_id' => 47, 'city' => 'Wise'],
                ['state_id' => 47, 'city' => 'Austinville'],
                ['state_id' => 47, 'city' => 'Barren Springs'],
                ['state_id' => 47, 'city' => 'Cripple Creek'],
                ['state_id' => 47, 'city' => 'Crockett'],
                ['state_id' => 47, 'city' => 'Ivanhoe'],
                ['state_id' => 47, 'city' => 'Max Meadows'],
                ['state_id' => 47, 'city' => 'Rural Retreat'],
                ['state_id' => 47, 'city' => 'Speedwell'],
                ['state_id' => 47, 'city' => 'Wytheville'],
                ['state_id' => 47, 'city' => 'Lightfoot'],
                ['state_id' => 47, 'city' => 'Yorktown'],
                ['state_id' => 47, 'city' => 'Lackey'],
                ['state_id' => 47, 'city' => 'Seaford'],
                ['state_id' => 47, 'city' => 'Bedford'],
                ['state_id' => 47, 'city' => 'Bristol'],
                ['state_id' => 47, 'city' => 'Buena Vista'],
                ['state_id' => 47, 'city' => 'Chesapeake'],
                ['state_id' => 47, 'city' => 'Colonial Heights'],
                ['state_id' => 47, 'city' => 'Covington'],
                ['state_id' => 47, 'city' => 'Danville'],
                ['state_id' => 47, 'city' => 'Emporia'],
                ['state_id' => 47, 'city' => 'Franklin'],
                ['state_id' => 47, 'city' => 'Galax'],
                ['state_id' => 47, 'city' => 'Hampton'],
                ['state_id' => 47, 'city' => 'Fort Monroe'],
                ['state_id' => 47, 'city' => 'Hopewell'],
                ['state_id' => 47, 'city' => 'Lexington'],
                ['state_id' => 47, 'city' => 'Manassas'],
                ['state_id' => 47, 'city' => 'Martinsville'],
                ['state_id' => 47, 'city' => 'Newport News'],
                ['state_id' => 47, 'city' => 'Fort Eustis'],
                ['state_id' => 47, 'city' => 'Norfolk'],
                ['state_id' => 47, 'city' => 'Norton'],
                ['state_id' => 47, 'city' => 'Petersburg'],
                ['state_id' => 47, 'city' => 'Virginia State University'],
                ['state_id' => 47, 'city' => 'Poquoson'],
                ['state_id' => 47, 'city' => 'Portsmouth'],
                ['state_id' => 47, 'city' => 'Radford'],
                ['state_id' => 47, 'city' => 'Salem'],
                ['state_id' => 47, 'city' => 'Staunton'],
                ['state_id' => 47, 'city' => 'Suffolk'],
                ['state_id' => 47, 'city' => 'Virginia Beach'],
                ['state_id' => 47, 'city' => 'Waynesboro', 'state_id' => 46]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
       }
    }
}
