<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State2TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of AK - Alaska.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 2, 'city' => 'Akutan'],
                ['state_id' => 2, 'city' => 'Cold Bay'],
                ['state_id' => 2, 'city' => 'False Pass'],
                ['state_id' => 2, 'city' => 'King Cove'],
                ['state_id' => 2, 'city' => 'Sand Point'],
                ['state_id' => 2, 'city' => 'Adak'],
                ['state_id' => 2, 'city' => 'Atka'],
                ['state_id' => 2, 'city' => 'Saint George Island'],
                ['state_id' => 2, 'city' => 'Nikolski'],
                ['state_id' => 2, 'city' => 'Saint Paul Island'],
                ['state_id' => 2, 'city' => 'Unalaska'],
                ['state_id' => 2, 'city' => 'Dutch Harbor'],
                ['state_id' => 2, 'city' => 'Anchorage'],
                ['state_id' => 2, 'city' => 'Jber'],
                ['state_id' => 2, 'city' => 'Indian'],
                ['state_id' => 2, 'city' => 'Chugiak'],
                ['state_id' => 2, 'city' => 'Eagle River'],
                ['state_id' => 2, 'city' => 'Girdwood'],
                ['state_id' => 2, 'city' => 'Kongiganak'],
                ['state_id' => 2, 'city' => 'Akiachak'],
                ['state_id' => 2, 'city' => 'Akiak'],
                ['state_id' => 2, 'city' => 'Aniak'],
                ['state_id' => 2, 'city' => 'Bethel'],
                ['state_id' => 2, 'city' => 'Chefornak'],
                ['state_id' => 2, 'city' => 'Crooked Creek'],
                ['state_id' => 2, 'city' => 'Eek'],
                ['state_id' => 2, 'city' => 'Goodnews Bay'],
                ['state_id' => 2, 'city' => 'Kalskag'],
                ['state_id' => 2, 'city' => 'Kasigluk'],
                ['state_id' => 2, 'city' => 'Kipnuk'],
                ['state_id' => 2, 'city' => 'Kwethluk'],
                ['state_id' => 2, 'city' => 'Kwigillingok'],
                ['state_id' => 2, 'city' => 'Lower Kalskag'],
                ['state_id' => 2, 'city' => 'Mekoryuk'],
                ['state_id' => 2, 'city' => 'Napakiak'],
                ['state_id' => 2, 'city' => 'Toksook Bay'],
                ['state_id' => 2, 'city' => 'Nunapitchuk'],
                ['state_id' => 2, 'city' => 'Platinum'],
                ['state_id' => 2, 'city' => 'Quinhagak'],
                ['state_id' => 2, 'city' => 'Red Devil'],
                ['state_id' => 2, 'city' => 'Sleetmute'],
                ['state_id' => 2, 'city' => 'Tuluksak'],
                ['state_id' => 2, 'city' => 'Tuntutuliak'],
                ['state_id' => 2, 'city' => 'Tununak'],
                ['state_id' => 2, 'city' => 'Nightmute'],
                ['state_id' => 2, 'city' => 'King Salmon'],
                ['state_id' => 2, 'city' => 'Naknek'],
                ['state_id' => 2, 'city' => 'South Naknek'],
                ['state_id' => 2, 'city' => 'Clear'],
                ['state_id' => 2, 'city' => 'Cantwell'],
                ['state_id' => 2, 'city' => 'Healy'],
                ['state_id' => 2, 'city' => 'Anderson'],
                ['state_id' => 2, 'city' => 'Denali National Park'],
                ['state_id' => 2, 'city' => 'Aleknagik'],
                ['state_id' => 2, 'city' => 'Clarks Point'],
                ['state_id' => 2, 'city' => 'Dillingham'],
                ['state_id' => 2, 'city' => 'Ekwok'],
                ['state_id' => 2, 'city' => 'Manokotak'],
                ['state_id' => 2, 'city' => 'New Stuyahok'],
                ['state_id' => 2, 'city' => 'Togiak'],
                ['state_id' => 2, 'city' => 'Fairbanks'],
                ['state_id' => 2, 'city' => 'Eielson Afb'],
                ['state_id' => 2, 'city' => 'Fort Wainwright'],
                ['state_id' => 2, 'city' => 'North Pole'],
                ['state_id' => 2, 'city' => 'Salcha'],
                ['state_id' => 2, 'city' => 'Two Rivers'],
                ['state_id' => 2, 'city' => 'Ester'],
                ['state_id' => 2, 'city' => 'Haines'],
                ['state_id' => 2, 'city' => 'Juneau'],
                ['state_id' => 2, 'city' => 'Auke Bay'],
                ['state_id' => 2, 'city' => 'Douglas'],
                ['state_id' => 2, 'city' => 'Anchor Point'],
                ['state_id' => 2, 'city' => 'Clam Gulch'],
                ['state_id' => 2, 'city' => 'Cooper Landing'],
                ['state_id' => 2, 'city' => 'Homer'],
                ['state_id' => 2, 'city' => 'Hope'],
                ['state_id' => 2, 'city' => 'Kasilof'],
                ['state_id' => 2, 'city' => 'Kenai'],
                ['state_id' => 2, 'city' => 'Moose Pass'],
                ['state_id' => 2, 'city' => 'Nikiski'],
                ['state_id' => 2, 'city' => 'Ninilchik'],
                ['state_id' => 2, 'city' => 'Seldovia'],
                ['state_id' => 2, 'city' => 'Seward'],
                ['state_id' => 2, 'city' => 'Soldotna'],
                ['state_id' => 2, 'city' => 'Sterling'],
                ['state_id' => 2, 'city' => 'Tyonek'],
                ['state_id' => 2, 'city' => 'Ketchikan'],
                ['state_id' => 2, 'city' => 'Ward Cove'],
                ['state_id' => 2, 'city' => 'Port Lions'],
                ['state_id' => 2, 'city' => 'Karluk'],
                ['state_id' => 2, 'city' => 'Kodiak'],
                ['state_id' => 2, 'city' => 'Larsen Bay'],
                ['state_id' => 2, 'city' => 'Old Harbor'],
                ['state_id' => 2, 'city' => 'Ouzinkie'],
                ['state_id' => 2, 'city' => 'Alakanuk'],
                ['state_id' => 2, 'city' => 'Chevak'],
                ['state_id' => 2, 'city' => 'Emmonak'],
                ['state_id' => 2, 'city' => 'Marshall'],
                ['state_id' => 2, 'city' => 'Hooper Bay'],
                ['state_id' => 2, 'city' => 'Kotlik'],
                ['state_id' => 2, 'city' => 'Mountain Village'],
                ['state_id' => 2, 'city' => 'Pilot Station'],
                ['state_id' => 2, 'city' => 'Russian Mission'],
                ['state_id' => 2, 'city' => 'Saint Marys'],
                ['state_id' => 2, 'city' => 'Scammon Bay'],
                ['state_id' => 2, 'city' => 'Nunam Iqua'],
                ['state_id' => 2, 'city' => 'Chignik Lake'],
                ['state_id' => 2, 'city' => 'Port Heiden'],
                ['state_id' => 2, 'city' => 'Chignik'],
                ['state_id' => 2, 'city' => 'Chignik Lagoon'],
                ['state_id' => 2, 'city' => 'Egegik'],
                ['state_id' => 2, 'city' => 'Iliamna'],
                ['state_id' => 2, 'city' => 'Levelock'],
                ['state_id' => 2, 'city' => 'Nondalton'],
                ['state_id' => 2, 'city' => 'Pedro Bay'],
                ['state_id' => 2, 'city' => 'Perryville'],
                ['state_id' => 2, 'city' => 'Pilot Point'],
                ['state_id' => 2, 'city' => 'Port Alsworth'],
                ['state_id' => 2, 'city' => 'Wasilla'],
                ['state_id' => 2, 'city' => 'Palmer'],
                ['state_id' => 2, 'city' => 'Big Lake'],
                ['state_id' => 2, 'city' => 'Skwentna'],
                ['state_id' => 2, 'city' => 'Sutton'],
                ['state_id' => 2, 'city' => 'Talkeetna'],
                ['state_id' => 2, 'city' => 'Trapper Creek'],
                ['state_id' => 2, 'city' => 'Willow'],
                ['state_id' => 2, 'city' => 'Houston'],
                ['state_id' => 2, 'city' => 'Saint Michael'],
                ['state_id' => 2, 'city' => 'Stebbins'],
                ['state_id' => 2, 'city' => 'Unalakleet'],
                ['state_id' => 2, 'city' => 'Elim'],
                ['state_id' => 2, 'city' => 'Gambell'],
                ['state_id' => 2, 'city' => 'Koyuk'],
                ['state_id' => 2, 'city' => 'Nome'],
                ['state_id' => 2, 'city' => 'Savoonga'],
                ['state_id' => 2, 'city' => 'Shaktoolik'],
                ['state_id' => 2, 'city' => 'Shishmaref'],
                ['state_id' => 2, 'city' => 'Teller'],
                ['state_id' => 2, 'city' => 'Wales'],
                ['state_id' => 2, 'city' => 'White Mountain'],
                ['state_id' => 2, 'city' => 'Brevig Mission'],
                ['state_id' => 2, 'city' => 'Anaktuvuk Pass'],
                ['state_id' => 2, 'city' => 'Barrow'],
                ['state_id' => 2, 'city' => 'Prudhoe Bay'],
                ['state_id' => 2, 'city' => 'Kaktovik'],
                ['state_id' => 2, 'city' => 'Point Lay'],
                ['state_id' => 2, 'city' => 'Point Hope'],
                ['state_id' => 2, 'city' => 'Wainwright'],
                ['state_id' => 2, 'city' => 'Nuiqsut'],
                ['state_id' => 2, 'city' => 'Atqasuk'],
                ['state_id' => 2, 'city' => 'Buckland'],
                ['state_id' => 2, 'city' => 'Deering'],
                ['state_id' => 2, 'city' => 'Kiana'],
                ['state_id' => 2, 'city' => 'Kivalina'],
                ['state_id' => 2, 'city' => 'Kobuk'],
                ['state_id' => 2, 'city' => 'Kotzebue'],
                ['state_id' => 2, 'city' => 'Noatak'],
                ['state_id' => 2, 'city' => 'Noorvik'],
                ['state_id' => 2, 'city' => 'Selawik'],
                ['state_id' => 2, 'city' => 'Shungnak'],
                ['state_id' => 2, 'city' => 'Ambler'],
                ['state_id' => 2, 'city' => 'Meyers Chuck'],
                ['state_id' => 2, 'city' => 'Coffman Cove'],
                ['state_id' => 2, 'city' => 'Thorne Bay'],
                ['state_id' => 2, 'city' => 'Craig'],
                ['state_id' => 2, 'city' => 'Hydaburg'],
                ['state_id' => 2, 'city' => 'Hyder'],
                ['state_id' => 2, 'city' => 'Klawock'],
                ['state_id' => 2, 'city' => 'Metlakatla'],
                ['state_id' => 2, 'city' => 'Point Baker'],
                ['state_id' => 2, 'city' => 'Sitka'],
                ['state_id' => 2, 'city' => 'Yakutat'],
                ['state_id' => 2, 'city' => 'Angoon'],
                ['state_id' => 2, 'city' => 'Elfin Cove'],
                ['state_id' => 2, 'city' => 'Gustavus'],
                ['state_id' => 2, 'city' => 'Hoonah'],
                ['state_id' => 2, 'city' => 'Pelican'],
                ['state_id' => 2, 'city' => 'Skagway'],
                ['state_id' => 2, 'city' => 'Tenakee Springs'],
                ['state_id' => 2, 'city' => 'Fort Greely'],
                ['state_id' => 2, 'city' => 'Chicken'],
                ['state_id' => 2, 'city' => 'Delta Junction'],
                ['state_id' => 2, 'city' => 'Eagle'],
                ['state_id' => 2, 'city' => 'Northway'],
                ['state_id' => 2, 'city' => 'Tanacross'],
                ['state_id' => 2, 'city' => 'Tok'],
                ['state_id' => 2, 'city' => 'Chitina'],
                ['state_id' => 2, 'city' => 'Copper Center'],
                ['state_id' => 2, 'city' => 'Cordova'],
                ['state_id' => 2, 'city' => 'Gakona'],
                ['state_id' => 2, 'city' => 'Glennallen'],
                ['state_id' => 2, 'city' => 'Tatitlek'],
                ['state_id' => 2, 'city' => 'Valdez'],
                ['state_id' => 2, 'city' => 'Whittier'],
                ['state_id' => 2, 'city' => 'Kake'],
                ['state_id' => 2, 'city' => 'Petersburg'],
                ['state_id' => 2, 'city' => 'Port Alexander'],
                ['state_id' => 2, 'city' => 'Wrangell'],
                ['state_id' => 2, 'city' => 'Anvik'],
                ['state_id' => 2, 'city' => 'Grayling'],
                ['state_id' => 2, 'city' => 'Holy Cross'],
                ['state_id' => 2, 'city' => 'Mc Grath'],
                ['state_id' => 2, 'city' => 'Shageluk'],
                ['state_id' => 2, 'city' => 'Takotna'],
                ['state_id' => 2, 'city' => 'Nikolai'],
                ['state_id' => 2, 'city' => 'Allakaket'],
                ['state_id' => 2, 'city' => 'Arctic Village'],
                ['state_id' => 2, 'city' => 'Beaver'],
                ['state_id' => 2, 'city' => 'Bettles Field'],
                ['state_id' => 2, 'city' => 'Central'],
                ['state_id' => 2, 'city' => 'Circle'],
                ['state_id' => 2, 'city' => 'Fort Yukon'],
                ['state_id' => 2, 'city' => 'Galena'],
                ['state_id' => 2, 'city' => 'Hughes'],
                ['state_id' => 2, 'city' => 'Huslia'],
                ['state_id' => 2, 'city' => 'Kaltag'],
                ['state_id' => 2, 'city' => 'Koyukuk'],
                ['state_id' => 2, 'city' => 'Manley Hot Springs'],
                ['state_id' => 2, 'city' => 'Lake Minchumina'],
                ['state_id' => 2, 'city' => 'Minto'],
                ['state_id' => 2, 'city' => 'Nenana'],
                ['state_id' => 2, 'city' => 'Nulato'],
                ['state_id' => 2, 'city' => 'Rampart'],
                ['state_id' => 2, 'city' => 'Ruby'],
                ['state_id' => 2, 'city' => 'Stevens Village'],
                ['state_id' => 2, 'city' => 'Tanana'],
                ['state_id' => 2, 'city' => 'Venetie'],
                ['state_id' => 2, 'city' => 'Chalkyitsik']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
