<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State4TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of AR - Arkansas.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 4, 'city' => 'Almyra'],
                ['state_id' => 4, 'city' => 'Casscoe'],
                ['state_id' => 4, 'city' => 'Crocketts Bluff'],
                ['state_id' => 4, 'city' => 'De Witt'],
                ['state_id' => 4, 'city' => 'Ethel'],
                ['state_id' => 4, 'city' => 'Gillett'],
                ['state_id' => 4, 'city' => 'Humphrey'],
                ['state_id' => 4, 'city' => 'Saint Charles'],
                ['state_id' => 4, 'city' => 'Stuttgart'],
                ['state_id' => 4, 'city' => 'Tichnor'],
                ['state_id' => 4, 'city' => 'Crossett'],
                ['state_id' => 4, 'city' => 'Fountain Hill'],
                ['state_id' => 4, 'city' => 'Hamburg'],
                ['state_id' => 4, 'city' => 'Montrose'],
                ['state_id' => 4, 'city' => 'Parkdale'],
                ['state_id' => 4, 'city' => 'Portland'],
                ['state_id' => 4, 'city' => 'Wilmot'],
                ['state_id' => 4, 'city' => 'Gamaliel'],
                ['state_id' => 4, 'city' => 'Henderson'],
                ['state_id' => 4, 'city' => 'Big Flat'],
                ['state_id' => 4, 'city' => 'Clarkridge'],
                ['state_id' => 4, 'city' => 'Cotter'],
                ['state_id' => 4, 'city' => 'Gassville'],
                ['state_id' => 4, 'city' => 'Lakeview'],
                ['state_id' => 4, 'city' => 'Midway'],
                ['state_id' => 4, 'city' => 'Mountain Home'],
                ['state_id' => 4, 'city' => 'Norfork'],
                ['state_id' => 4, 'city' => 'Avoca'],
                ['state_id' => 4, 'city' => 'Bentonville'],
                ['state_id' => 4, 'city' => 'Bella Vista'],
                ['state_id' => 4, 'city' => 'Cave Springs'],
                ['state_id' => 4, 'city' => 'Centerton'],
                ['state_id' => 4, 'city' => 'Decatur'],
                ['state_id' => 4, 'city' => 'Garfield'],
                ['state_id' => 4, 'city' => 'Gateway'],
                ['state_id' => 4, 'city' => 'Gentry'],
                ['state_id' => 4, 'city' => 'Gravette'],
                ['state_id' => 4, 'city' => 'Hiwasse'],
                ['state_id' => 4, 'city' => 'Lowell'],
                ['state_id' => 4, 'city' => 'Maysville'],
                ['state_id' => 4, 'city' => 'Pea Ridge'],
                ['state_id' => 4, 'city' => 'Rogers'],
                ['state_id' => 4, 'city' => 'Siloam Springs'],
                ['state_id' => 4, 'city' => 'Sulphur Springs'],
                ['state_id' => 4, 'city' => 'Little Rock'],
                ['state_id' => 4, 'city' => 'Harrison'],
                ['state_id' => 4, 'city' => 'Alpena'],
                ['state_id' => 4, 'city' => 'Bergman'],
                ['state_id' => 4, 'city' => 'Diamond City'],
                ['state_id' => 4, 'city' => 'Everton'],
                ['state_id' => 4, 'city' => 'Lead Hill'],
                ['state_id' => 4, 'city' => 'Omaha'],
                ['state_id' => 4, 'city' => 'Valley Springs'],
                ['state_id' => 4, 'city' => 'Banks'],
                ['state_id' => 4, 'city' => 'Hermitage'],
                ['state_id' => 4, 'city' => 'Jersey'],
                ['state_id' => 4, 'city' => 'Warren'],
                ['state_id' => 4, 'city' => 'Hampton'],
                ['state_id' => 4, 'city' => 'Harrell'],
                ['state_id' => 4, 'city' => 'Thornton'],
                ['state_id' => 4, 'city' => 'Beaver'],
                ['state_id' => 4, 'city' => 'Berryville'],
                ['state_id' => 4, 'city' => 'Eureka Springs'],
                ['state_id' => 4, 'city' => 'Green Forest'],
                ['state_id' => 4, 'city' => 'Oak Grove'],
                ['state_id' => 4, 'city' => 'Dermott'],
                ['state_id' => 4, 'city' => 'Eudora'],
                ['state_id' => 4, 'city' => 'Lake Village'],
                ['state_id' => 4, 'city' => 'Beirne'],
                ['state_id' => 4, 'city' => 'Curtis'],
                ['state_id' => 4, 'city' => 'Gurdon'],
                ['state_id' => 4, 'city' => 'Whelen Springs'],
                ['state_id' => 4, 'city' => 'Alpine'],
                ['state_id' => 4, 'city' => 'Amity'],
                ['state_id' => 4, 'city' => 'Arkadelphia'],
                ['state_id' => 4, 'city' => 'Okolona'],
                ['state_id' => 4, 'city' => 'Corning'],
                ['state_id' => 4, 'city' => 'Datto'],
                ['state_id' => 4, 'city' => 'Greenway'],
                ['state_id' => 4, 'city' => 'Knobel'],
                ['state_id' => 4, 'city' => 'Mc Dougal'],
                ['state_id' => 4, 'city' => 'Peach Orchard'],
                ['state_id' => 4, 'city' => 'Piggott'],
                ['state_id' => 4, 'city' => 'Pollard'],
                ['state_id' => 4, 'city' => 'Rector'],
                ['state_id' => 4, 'city' => 'Saint Francis'],
                ['state_id' => 4, 'city' => 'Success'],
                ['state_id' => 4, 'city' => 'Edgemont'],
                ['state_id' => 4, 'city' => 'Higden'],
                ['state_id' => 4, 'city' => 'Prim'],
                ['state_id' => 4, 'city' => 'Quitman'],
                ['state_id' => 4, 'city' => 'Wilburn'],
                ['state_id' => 4, 'city' => 'Concord'],
                ['state_id' => 4, 'city' => 'Drasco'],
                ['state_id' => 4, 'city' => 'Heber Springs'],
                ['state_id' => 4, 'city' => 'Ida'],
                ['state_id' => 4, 'city' => 'Tumbling Shoals'],
                ['state_id' => 4, 'city' => 'Kingsland'],
                ['state_id' => 4, 'city' => 'New Edinburg'],
                ['state_id' => 4, 'city' => 'Rison'],
                ['state_id' => 4, 'city' => 'Emerson'],
                ['state_id' => 4, 'city' => 'Mc Neil'],
                ['state_id' => 4, 'city' => 'Magnolia'],
                ['state_id' => 4, 'city' => 'Waldo'],
                ['state_id' => 4, 'city' => 'Taylor'],
                ['state_id' => 4, 'city' => 'Center Ridge'],
                ['state_id' => 4, 'city' => 'Cleveland'],
                ['state_id' => 4, 'city' => 'Hattieville'],
                ['state_id' => 4, 'city' => 'Jerusalem'],
                ['state_id' => 4, 'city' => 'Menifee'],
                ['state_id' => 4, 'city' => 'Morrilton'],
                ['state_id' => 4, 'city' => 'Plumerville'],
                ['state_id' => 4, 'city' => 'Solgohachia'],
                ['state_id' => 4, 'city' => 'Springfield'],
                ['state_id' => 4, 'city' => 'Jonesboro'],
                ['state_id' => 4, 'city' => 'Bay'],
                ['state_id' => 4, 'city' => 'Black Oak'],
                ['state_id' => 4, 'city' => 'Bono'],
                ['state_id' => 4, 'city' => 'Brookland'],
                ['state_id' => 4, 'city' => 'Caraway'],
                ['state_id' => 4, 'city' => 'Cash'],
                ['state_id' => 4, 'city' => 'Egypt'],
                ['state_id' => 4, 'city' => 'Lake City'],
                ['state_id' => 4, 'city' => 'Monette'],
                ['state_id' => 4, 'city' => 'State University'],
                ['state_id' => 4, 'city' => 'Alma'],
                ['state_id' => 4, 'city' => 'Cedarville'],
                ['state_id' => 4, 'city' => 'Chester'],
                ['state_id' => 4, 'city' => 'Dyer'],
                ['state_id' => 4, 'city' => 'Mountainburg'],
                ['state_id' => 4, 'city' => 'Mulberry'],
                ['state_id' => 4, 'city' => 'Natural Dam'],
                ['state_id' => 4, 'city' => 'Rudy'],
                ['state_id' => 4, 'city' => 'Uniontown'],
                ['state_id' => 4, 'city' => 'Van Buren'],
                ['state_id' => 4, 'city' => 'West Memphis'],
                ['state_id' => 4, 'city' => 'Clarkedale'],
                ['state_id' => 4, 'city' => 'Crawfordsville'],
                ['state_id' => 4, 'city' => 'Earle'],
                ['state_id' => 4, 'city' => 'Edmondson'],
                ['state_id' => 4, 'city' => 'Gilmore'],
                ['state_id' => 4, 'city' => 'Marion'],
                ['state_id' => 4, 'city' => 'Proctor'],
                ['state_id' => 4, 'city' => 'Turrell'],
                ['state_id' => 4, 'city' => 'Cherry Valley'],
                ['state_id' => 4, 'city' => 'Hickory Ridge'],
                ['state_id' => 4, 'city' => 'Parkin'],
                ['state_id' => 4, 'city' => 'Vanndale'],
                ['state_id' => 4, 'city' => 'Wynne'],
                ['state_id' => 4, 'city' => 'Carthage'],
                ['state_id' => 4, 'city' => 'Fordyce'],
                ['state_id' => 4, 'city' => 'Ivan'],
                ['state_id' => 4, 'city' => 'Sparkman'],
                ['state_id' => 4, 'city' => 'Arkansas City'],
                ['state_id' => 4, 'city' => 'Dumas'],
                ['state_id' => 4, 'city' => 'Mc Gehee'],
                ['state_id' => 4, 'city' => 'Pickens'],
                ['state_id' => 4, 'city' => 'Rohwer'],
                ['state_id' => 4, 'city' => 'Tillar'],
                ['state_id' => 4, 'city' => 'Watson'],
                ['state_id' => 4, 'city' => 'Snow Lake'],
                ['state_id' => 4, 'city' => 'Monticello'],
                ['state_id' => 4, 'city' => 'Wilmar'],
                ['state_id' => 4, 'city' => 'Winchester'],
                ['state_id' => 4, 'city' => 'Conway'],
                ['state_id' => 4, 'city' => 'Damascus'],
                ['state_id' => 4, 'city' => 'Enola'],
                ['state_id' => 4, 'city' => 'Greenbrier'],
                ['state_id' => 4, 'city' => 'Guy'],
                ['state_id' => 4, 'city' => 'Mayflower'],
                ['state_id' => 4, 'city' => 'Mount Vernon'],
                ['state_id' => 4, 'city' => 'Vilonia'],
                ['state_id' => 4, 'city' => 'Wooster'],
                ['state_id' => 4, 'city' => 'Alix'],
                ['state_id' => 4, 'city' => 'Altus'],
                ['state_id' => 4, 'city' => 'Branch'],
                ['state_id' => 4, 'city' => 'Cecil'],
                ['state_id' => 4, 'city' => 'Charleston'],
                ['state_id' => 4, 'city' => 'Ozark'],
                ['state_id' => 4, 'city' => 'Bexar'],
                ['state_id' => 4, 'city' => 'Camp'],
                ['state_id' => 4, 'city' => 'Elizabeth'],
                ['state_id' => 4, 'city' => 'Gepp'],
                ['state_id' => 4, 'city' => 'Glencoe'],
                ['state_id' => 4, 'city' => 'Mammoth Spring'],
                ['state_id' => 4, 'city' => 'Salem'],
                ['state_id' => 4, 'city' => 'Sturkie'],
                ['state_id' => 4, 'city' => 'Viola'],
                ['state_id' => 4, 'city' => 'Hot Springs National Park'],
                ['state_id' => 4, 'city' => 'Hot Springs Village'],
                ['state_id' => 4, 'city' => 'Jessieville'],
                ['state_id' => 4, 'city' => 'Mountain Pine'],
                ['state_id' => 4, 'city' => 'Pearcy'],
                ['state_id' => 4, 'city' => 'Royal'],
                ['state_id' => 4, 'city' => 'Lonsdale'],
                ['state_id' => 4, 'city' => 'Grapevine'],
                ['state_id' => 4, 'city' => 'Leola'],
                ['state_id' => 4, 'city' => 'Poyen'],
                ['state_id' => 4, 'city' => 'Prattsville'],
                ['state_id' => 4, 'city' => 'Sheridan'],
                ['state_id' => 4, 'city' => 'Beech Grove'],
                ['state_id' => 4, 'city' => 'Delaplaine'],
                ['state_id' => 4, 'city' => 'Lafe'],
                ['state_id' => 4, 'city' => 'Marmaduke'],
                ['state_id' => 4, 'city' => 'Paragould'],
                ['state_id' => 4, 'city' => 'Walcott'],
                ['state_id' => 4, 'city' => 'Hope'],
                ['state_id' => 4, 'city' => 'Blevins'],
                ['state_id' => 4, 'city' => 'Columbus'],
                ['state_id' => 4, 'city' => 'Fulton'],
                ['state_id' => 4, 'city' => 'Mc Caskill'],
                ['state_id' => 4, 'city' => 'Ozan'],
                ['state_id' => 4, 'city' => 'Washington'],
                ['state_id' => 4, 'city' => 'Bismarck'],
                ['state_id' => 4, 'city' => 'Bonnerdale'],
                ['state_id' => 4, 'city' => 'Donaldson'],
                ['state_id' => 4, 'city' => 'Friendship'],
                ['state_id' => 4, 'city' => 'Benton'],
                ['state_id' => 4, 'city' => 'Malvern'],
                ['state_id' => 4, 'city' => 'Jones Mill'],
                ['state_id' => 4, 'city' => 'Dierks'],
                ['state_id' => 4, 'city' => 'Mineral Springs'],
                ['state_id' => 4, 'city' => 'Nashville'],
                ['state_id' => 4, 'city' => 'Saratoga'],
                ['state_id' => 4, 'city' => 'Umpire'],
                ['state_id' => 4, 'city' => 'Thida'],
                ['state_id' => 4, 'city' => 'Batesville'],
                ['state_id' => 4, 'city' => 'Charlotte'],
                ['state_id' => 4, 'city' => 'Cord'],
                ['state_id' => 4, 'city' => 'Cushman'],
                ['state_id' => 4, 'city' => 'Desha'],
                ['state_id' => 4, 'city' => 'Floral'],
                ['state_id' => 4, 'city' => 'Locust Grove'],
                ['state_id' => 4, 'city' => 'Magness'],
                ['state_id' => 4, 'city' => 'Newark'],
                ['state_id' => 4, 'city' => 'Oil Trough'],
                ['state_id' => 4, 'city' => 'Pleasant Plains'],
                ['state_id' => 4, 'city' => 'Rosie'],
                ['state_id' => 4, 'city' => 'Salado'],
                ['state_id' => 4, 'city' => 'Sulphur Rock'],
                ['state_id' => 4, 'city' => 'Horseshoe Bend'],
                ['state_id' => 4, 'city' => 'Brockwell'],
                ['state_id' => 4, 'city' => 'Calico Rock'],
                ['state_id' => 4, 'city' => 'Dolph'],
                ['state_id' => 4, 'city' => 'Franklin'],
                ['state_id' => 4, 'city' => 'Guion'],
                ['state_id' => 4, 'city' => 'Melbourne'],
                ['state_id' => 4, 'city' => 'Mount Pleasant'],
                ['state_id' => 4, 'city' => 'Oxford'],
                ['state_id' => 4, 'city' => 'Pineville'],
                ['state_id' => 4, 'city' => 'Sage'],
                ['state_id' => 4, 'city' => 'Violet Hill'],
                ['state_id' => 4, 'city' => 'Wideman'],
                ['state_id' => 4, 'city' => 'Wiseman'],
                ['state_id' => 4, 'city' => 'Amagon'],
                ['state_id' => 4, 'city' => 'Beedeville'],
                ['state_id' => 4, 'city' => 'Diaz'],
                ['state_id' => 4, 'city' => 'Jacksonport'],
                ['state_id' => 4, 'city' => 'Newport'],
                ['state_id' => 4, 'city' => 'Tupelo'],
                ['state_id' => 4, 'city' => 'Grubbs'],
                ['state_id' => 4, 'city' => 'Swifton'],
                ['state_id' => 4, 'city' => 'Tuckerman'],
                ['state_id' => 4, 'city' => 'Pine Bluff'],
                ['state_id' => 4, 'city' => 'White Hall'],
                ['state_id' => 4, 'city' => 'Moscow'],
                ['state_id' => 4, 'city' => 'Altheimer'],
                ['state_id' => 4, 'city' => 'Jefferson'],
                ['state_id' => 4, 'city' => 'Redfield'],
                ['state_id' => 4, 'city' => 'Reydell'],
                ['state_id' => 4, 'city' => 'Sherrill'],
                ['state_id' => 4, 'city' => 'Tucker'],
                ['state_id' => 4, 'city' => 'Wabbaseka'],
                ['state_id' => 4, 'city' => 'Wright'],
                ['state_id' => 4, 'city' => 'Clarksville'],
                ['state_id' => 4, 'city' => 'Coal Hill'],
                ['state_id' => 4, 'city' => 'Hagarville'],
                ['state_id' => 4, 'city' => 'Hartman'],
                ['state_id' => 4, 'city' => 'Knoxville'],
                ['state_id' => 4, 'city' => 'Lamar'],
                ['state_id' => 4, 'city' => 'Oark'],
                ['state_id' => 4, 'city' => 'Ozone'],
                ['state_id' => 4, 'city' => 'Bradley'],
                ['state_id' => 4, 'city' => 'Buckner'],
                ['state_id' => 4, 'city' => 'Garland City'],
                ['state_id' => 4, 'city' => 'Lewisville'],
                ['state_id' => 4, 'city' => 'Stamps'],
                ['state_id' => 4, 'city' => 'Alicia'],
                ['state_id' => 4, 'city' => 'Black Rock'],
                ['state_id' => 4, 'city' => 'Hoxie'],
                ['state_id' => 4, 'city' => 'Imboden'],
                ['state_id' => 4, 'city' => 'Lynn'],
                ['state_id' => 4, 'city' => 'Minturn'],
                ['state_id' => 4, 'city' => 'Portia'],
                ['state_id' => 4, 'city' => 'Powhatan'],
                ['state_id' => 4, 'city' => 'Ravenden'],
                ['state_id' => 4, 'city' => 'Sedgwick'],
                ['state_id' => 4, 'city' => 'Smithville'],
                ['state_id' => 4, 'city' => 'Strawberry'],
                ['state_id' => 4, 'city' => 'Walnut Ridge'],
                ['state_id' => 4, 'city' => 'Saffell'],
                ['state_id' => 4, 'city' => 'Aubrey'],
                ['state_id' => 4, 'city' => 'Brickeys'],
                ['state_id' => 4, 'city' => 'Haynes'],
                ['state_id' => 4, 'city' => 'La Grange'],
                ['state_id' => 4, 'city' => 'Marianna'],
                ['state_id' => 4, 'city' => 'Moro'],
                ['state_id' => 4, 'city' => 'Gould'],
                ['state_id' => 4, 'city' => 'Grady'],
                ['state_id' => 4, 'city' => 'Star City'],
                ['state_id' => 4, 'city' => 'Yorktown'],
                ['state_id' => 4, 'city' => 'Alleene'],
                ['state_id' => 4, 'city' => 'Ashdown'],
                ['state_id' => 4, 'city' => 'Foreman'],
                ['state_id' => 4, 'city' => 'Ogden'],
                ['state_id' => 4, 'city' => 'Wilton'],
                ['state_id' => 4, 'city' => 'Winthrop'],
                ['state_id' => 4, 'city' => 'Blue Mountain'],
                ['state_id' => 4, 'city' => 'Delaware'],
                ['state_id' => 4, 'city' => 'New Blaine'],
                ['state_id' => 4, 'city' => 'Paris'],
                ['state_id' => 4, 'city' => 'Scranton'],
                ['state_id' => 4, 'city' => 'Subiaco'],
                ['state_id' => 4, 'city' => 'Booneville'],
                ['state_id' => 4, 'city' => 'Magazine'],
                ['state_id' => 4, 'city' => 'Ratcliff'],
                ['state_id' => 4, 'city' => 'Austin'],
                ['state_id' => 4, 'city' => 'Cabot'],
                ['state_id' => 4, 'city' => 'Carlisle'],
                ['state_id' => 4, 'city' => 'Coy'],
                ['state_id' => 4, 'city' => 'England'],
                ['state_id' => 4, 'city' => 'Humnoke'],
                ['state_id' => 4, 'city' => 'Keo'],
                ['state_id' => 4, 'city' => 'Lonoke'],
                ['state_id' => 4, 'city' => 'Ward'],
                ['state_id' => 4, 'city' => 'Combs'],
                ['state_id' => 4, 'city' => 'Hindsville'],
                ['state_id' => 4, 'city' => 'Huntsville'],
                ['state_id' => 4, 'city' => 'Kingston'],
                ['state_id' => 4, 'city' => 'Pettigrew'],
                ['state_id' => 4, 'city' => 'Saint Paul'],
                ['state_id' => 4, 'city' => 'Wesley'],
                ['state_id' => 4, 'city' => 'Witter'],
                ['state_id' => 4, 'city' => 'Bull Shoals'],
                ['state_id' => 4, 'city' => 'Flippin'],
                ['state_id' => 4, 'city' => 'Oakland'],
                ['state_id' => 4, 'city' => 'Peel'],
                ['state_id' => 4, 'city' => 'Pyatt'],
                ['state_id' => 4, 'city' => 'Summit'],
                ['state_id' => 4, 'city' => 'Yellville'],
                ['state_id' => 4, 'city' => 'Doddridge'],
                ['state_id' => 4, 'city' => 'Fouke'],
                ['state_id' => 4, 'city' => 'Genoa'],
                ['state_id' => 4, 'city' => 'Texarkana'],
                ['state_id' => 4, 'city' => 'Armorel'],
                ['state_id' => 4, 'city' => 'Bassett'],
                ['state_id' => 4, 'city' => 'Blytheville'],
                ['state_id' => 4, 'city' => 'Gosnell'],
                ['state_id' => 4, 'city' => 'Burdette'],
                ['state_id' => 4, 'city' => 'Driver'],
                ['state_id' => 4, 'city' => 'Dyess'],
                ['state_id' => 4, 'city' => 'Frenchmans Bayou'],
                ['state_id' => 4, 'city' => 'Joiner'],
                ['state_id' => 4, 'city' => 'Keiser'],
                ['state_id' => 4, 'city' => 'Luxora'],
                ['state_id' => 4, 'city' => 'Osceola'],
                ['state_id' => 4, 'city' => 'West Ridge'],
                ['state_id' => 4, 'city' => 'Wilson'],
                ['state_id' => 4, 'city' => 'Dell'],
                ['state_id' => 4, 'city' => 'Etowah'],
                ['state_id' => 4, 'city' => 'Leachville'],
                ['state_id' => 4, 'city' => 'Manila'],
                ['state_id' => 4, 'city' => 'Brinkley'],
                ['state_id' => 4, 'city' => 'Clarendon'],
                ['state_id' => 4, 'city' => 'Holly Grove'],
                ['state_id' => 4, 'city' => 'Monroe'],
                ['state_id' => 4, 'city' => 'Roe'],
                ['state_id' => 4, 'city' => 'Caddo Gap'],
                ['state_id' => 4, 'city' => 'Mount Ida'],
                ['state_id' => 4, 'city' => 'Norman'],
                ['state_id' => 4, 'city' => 'Oden'],
                ['state_id' => 4, 'city' => 'Pencil Bluff'],
                ['state_id' => 4, 'city' => 'Sims'],
                ['state_id' => 4, 'city' => 'Story'],
                ['state_id' => 4, 'city' => 'Bluff City'],
                ['state_id' => 4, 'city' => 'Cale'],
                ['state_id' => 4, 'city' => 'Emmet'],
                ['state_id' => 4, 'city' => 'Prescott'],
                ['state_id' => 4, 'city' => 'Rosston'],
                ['state_id' => 4, 'city' => 'Willisville'],
                ['state_id' => 4, 'city' => 'Compton'],
                ['state_id' => 4, 'city' => 'Deer'],
                ['state_id' => 4, 'city' => 'Hasty'],
                ['state_id' => 4, 'city' => 'Jasper'],
                ['state_id' => 4, 'city' => 'Marble Falls'],
                ['state_id' => 4, 'city' => 'Mount Judea'],
                ['state_id' => 4, 'city' => 'Parthenon'],
                ['state_id' => 4, 'city' => 'Ponca'],
                ['state_id' => 4, 'city' => 'Vendor'],
                ['state_id' => 4, 'city' => 'Western Grove'],
                ['state_id' => 4, 'city' => 'Camden'],
                ['state_id' => 4, 'city' => 'Bearden'],
                ['state_id' => 4, 'city' => 'Chidester'],
                ['state_id' => 4, 'city' => 'Louann'],
                ['state_id' => 4, 'city' => 'Stephens'],
                ['state_id' => 4, 'city' => 'Adona'],
                ['state_id' => 4, 'city' => 'Bigelow'],
                ['state_id' => 4, 'city' => 'Casa'],
                ['state_id' => 4, 'city' => 'Houston'],
                ['state_id' => 4, 'city' => 'Perry'],
                ['state_id' => 4, 'city' => 'Perryville'],
                ['state_id' => 4, 'city' => 'Barton'],
                ['state_id' => 4, 'city' => 'Crumrod'],
                ['state_id' => 4, 'city' => 'Elaine'],
                ['state_id' => 4, 'city' => 'Helena'],
                ['state_id' => 4, 'city' => 'Lambrook'],
                ['state_id' => 4, 'city' => 'Lexa'],
                ['state_id' => 4, 'city' => 'Marvell'],
                ['state_id' => 4, 'city' => 'Mellwood'],
                ['state_id' => 4, 'city' => 'Oneida'],
                ['state_id' => 4, 'city' => 'Poplar Grove'],
                ['state_id' => 4, 'city' => 'Turner'],
                ['state_id' => 4, 'city' => 'Wabash'],
                ['state_id' => 4, 'city' => 'West Helena'],
                ['state_id' => 4, 'city' => 'Antoine'],
                ['state_id' => 4, 'city' => 'Delight'],
                ['state_id' => 4, 'city' => 'Glenwood'],
                ['state_id' => 4, 'city' => 'Kirby'],
                ['state_id' => 4, 'city' => 'Langley'],
                ['state_id' => 4, 'city' => 'Murfreesboro'],
                ['state_id' => 4, 'city' => 'Newhope'],
                ['state_id' => 4, 'city' => 'Lepanto'],
                ['state_id' => 4, 'city' => 'Marked Tree'],
                ['state_id' => 4, 'city' => 'Rivervale'],
                ['state_id' => 4, 'city' => 'Tyronza'],
                ['state_id' => 4, 'city' => 'Fisher'],
                ['state_id' => 4, 'city' => 'Harrisburg'],
                ['state_id' => 4, 'city' => 'Trumann'],
                ['state_id' => 4, 'city' => 'Waldenburg'],
                ['state_id' => 4, 'city' => 'Weiner'],
                ['state_id' => 4, 'city' => 'Board Camp'],
                ['state_id' => 4, 'city' => 'Cove'],
                ['state_id' => 4, 'city' => 'Grannis'],
                ['state_id' => 4, 'city' => 'Hatfield'],
                ['state_id' => 4, 'city' => 'Mena'],
                ['state_id' => 4, 'city' => 'Vandervoort'],
                ['state_id' => 4, 'city' => 'Wickes'],
                ['state_id' => 4, 'city' => 'Tilly'],
                ['state_id' => 4, 'city' => 'Russellville'],
                ['state_id' => 4, 'city' => 'Atkins'],
                ['state_id' => 4, 'city' => 'Dover'],
                ['state_id' => 4, 'city' => 'Hector'],
                ['state_id' => 4, 'city' => 'London'],
                ['state_id' => 4, 'city' => 'Pelsor'],
                ['state_id' => 4, 'city' => 'Pottsville'],
                ['state_id' => 4, 'city' => 'Biscoe'],
                ['state_id' => 4, 'city' => 'Des Arc'],
                ['state_id' => 4, 'city' => 'De Valls Bluff'],
                ['state_id' => 4, 'city' => 'Hazen'],
                ['state_id' => 4, 'city' => 'Hickory Plains'],
                ['state_id' => 4, 'city' => 'Ulm'],
                ['state_id' => 4, 'city' => 'Alexander'],
                ['state_id' => 4, 'city' => 'College Station'],
                ['state_id' => 4, 'city' => 'Hensley'],
                ['state_id' => 4, 'city' => 'Jacksonville'],
                ['state_id' => 4, 'city' => 'Little Rock Air Force Base'],
                ['state_id' => 4, 'city' => 'Mabelvale'],
                ['state_id' => 4, 'city' => 'Maumelle'],
                ['state_id' => 4, 'city' => 'North Little Rock'],
                ['state_id' => 4, 'city' => 'Sherwood'],
                ['state_id' => 4, 'city' => 'Roland'],
                ['state_id' => 4, 'city' => 'Scott'],
                ['state_id' => 4, 'city' => 'Sweet Home'],
                ['state_id' => 4, 'city' => 'Woodson'],
                ['state_id' => 4, 'city' => 'Wrightsville'],
                ['state_id' => 4, 'city' => 'Biggers'],
                ['state_id' => 4, 'city' => 'Maynard'],
                ['state_id' => 4, 'city' => 'O Kean'],
                ['state_id' => 4, 'city' => 'Pocahontas'],
                ['state_id' => 4, 'city' => 'Ravenden Springs'],
                ['state_id' => 4, 'city' => 'Reyno'],
                ['state_id' => 4, 'city' => 'Warm Springs'],
                ['state_id' => 4, 'city' => 'Caldwell'],
                ['state_id' => 4, 'city' => 'Colt'],
                ['state_id' => 4, 'city' => 'Forrest City'],
                ['state_id' => 4, 'city' => 'Goodwin'],
                ['state_id' => 4, 'city' => 'Heth'],
                ['state_id' => 4, 'city' => 'Hughes'],
                ['state_id' => 4, 'city' => 'Madison'],
                ['state_id' => 4, 'city' => 'Palestine'],
                ['state_id' => 4, 'city' => 'Wheatley'],
                ['state_id' => 4, 'city' => 'Widener'],
                ['state_id' => 4, 'city' => 'Bauxite'],
                ['state_id' => 4, 'city' => 'Bryant'],
                ['state_id' => 4, 'city' => 'Paron'],
                ['state_id' => 4, 'city' => 'Traskwood'],
                ['state_id' => 4, 'city' => 'Harvey'],
                ['state_id' => 4, 'city' => 'Boles'],
                ['state_id' => 4, 'city' => 'Mansfield'],
                ['state_id' => 4, 'city' => 'Parks'],
                ['state_id' => 4, 'city' => 'Waldron'],
                ['state_id' => 4, 'city' => 'Gilbert'],
                ['state_id' => 4, 'city' => 'Harriet'],
                ['state_id' => 4, 'city' => 'Leslie'],
                ['state_id' => 4, 'city' => 'Marshall'],
                ['state_id' => 4, 'city' => 'Pindall'],
                ['state_id' => 4, 'city' => 'Saint Joe'],
                ['state_id' => 4, 'city' => 'Witts Springs'],
                ['state_id' => 4, 'city' => 'Fort Smith'],
                ['state_id' => 4, 'city' => 'Barling'],
                ['state_id' => 4, 'city' => 'Greenwood'],
                ['state_id' => 4, 'city' => 'Hackett'],
                ['state_id' => 4, 'city' => 'Hartford'],
                ['state_id' => 4, 'city' => 'Huntington'],
                ['state_id' => 4, 'city' => 'Lavaca'],
                ['state_id' => 4, 'city' => 'Midland'],
                ['state_id' => 4, 'city' => 'Ben Lomond'],
                ['state_id' => 4, 'city' => 'De Queen'],
                ['state_id' => 4, 'city' => 'Gillham'],
                ['state_id' => 4, 'city' => 'Horatio'],
                ['state_id' => 4, 'city' => 'Lockesburg'],
                ['state_id' => 4, 'city' => 'Williford'],
                ['state_id' => 4, 'city' => 'Ash Flat'],
                ['state_id' => 4, 'city' => 'Cave City'],
                ['state_id' => 4, 'city' => 'Cherokee Village'],
                ['state_id' => 4, 'city' => 'Evening Shade'],
                ['state_id' => 4, 'city' => 'Hardy'],
                ['state_id' => 4, 'city' => 'Poughkeepsie'],
                ['state_id' => 4, 'city' => 'Sidney'],
                ['state_id' => 4, 'city' => 'Fox'],
                ['state_id' => 4, 'city' => 'Fifty Six'],
                ['state_id' => 4, 'city' => 'Marcella'],
                ['state_id' => 4, 'city' => 'Mountain View'],
                ['state_id' => 4, 'city' => 'Pleasant Grove'],
                ['state_id' => 4, 'city' => 'Timbo'],
                ['state_id' => 4, 'city' => 'Onia'],
                ['state_id' => 4, 'city' => 'Calion'],
                ['state_id' => 4, 'city' => 'El Dorado'],
                ['state_id' => 4, 'city' => 'Huttig'],
                ['state_id' => 4, 'city' => 'Junction City'],
                ['state_id' => 4, 'city' => 'Lawson'],
                ['state_id' => 4, 'city' => 'Mount Holly'],
                ['state_id' => 4, 'city' => 'Norphlet'],
                ['state_id' => 4, 'city' => 'Smackover'],
                ['state_id' => 4, 'city' => 'Strong'],
                ['state_id' => 4, 'city' => 'Bee Branch'],
                ['state_id' => 4, 'city' => 'Choctaw'],
                ['state_id' => 4, 'city' => 'Clinton'],
                ['state_id' => 4, 'city' => 'Fairfield Bay'],
                ['state_id' => 4, 'city' => 'Scotland'],
                ['state_id' => 4, 'city' => 'Shirley'],
                ['state_id' => 4, 'city' => 'Dennard'],
                ['state_id' => 4, 'city' => 'Fayetteville'],
                ['state_id' => 4, 'city' => 'Canehill'],
                ['state_id' => 4, 'city' => 'Elkins'],
                ['state_id' => 4, 'city' => 'Elm Springs'],
                ['state_id' => 4, 'city' => 'Evansville'],
                ['state_id' => 4, 'city' => 'Farmington'],
                ['state_id' => 4, 'city' => 'Goshen'],
                ['state_id' => 4, 'city' => 'Greenland'],
                ['state_id' => 4, 'city' => 'Johnson'],
                ['state_id' => 4, 'city' => 'Lincoln'],
                ['state_id' => 4, 'city' => 'Morrow'],
                ['state_id' => 4, 'city' => 'Prairie Grove'],
                ['state_id' => 4, 'city' => 'Springdale'],
                ['state_id' => 4, 'city' => 'Summers'],
                ['state_id' => 4, 'city' => 'Tontitown'],
                ['state_id' => 4, 'city' => 'West Fork'],
                ['state_id' => 4, 'city' => 'Winslow'],
                ['state_id' => 4, 'city' => 'Bald Knob'],
                ['state_id' => 4, 'city' => 'Beebe'],
                ['state_id' => 4, 'city' => 'Bradford'],
                ['state_id' => 4, 'city' => 'El Paso'],
                ['state_id' => 4, 'city' => 'Garner'],
                ['state_id' => 4, 'city' => 'Griffithville'],
                ['state_id' => 4, 'city' => 'Higginson'],
                ['state_id' => 4, 'city' => 'Judsonia'],
                ['state_id' => 4, 'city' => 'Kensett'],
                ['state_id' => 4, 'city' => 'Letona'],
                ['state_id' => 4, 'city' => 'Mc Rae'],
                ['state_id' => 4, 'city' => 'Pangburn'],
                ['state_id' => 4, 'city' => 'Romance'],
                ['state_id' => 4, 'city' => 'Rose Bud'],
                ['state_id' => 4, 'city' => 'Russell'],
                ['state_id' => 4, 'city' => 'Searcy'],
                ['state_id' => 4, 'city' => 'West Point'],
                ['state_id' => 4, 'city' => 'Augusta'],
                ['state_id' => 4, 'city' => 'Cotton Plant'],
                ['state_id' => 4, 'city' => 'Gregory'],
                ['state_id' => 4, 'city' => 'Hunter'],
                ['state_id' => 4, 'city' => 'Mc Crory'],
                ['state_id' => 4, 'city' => 'Patterson'],
                ['state_id' => 4, 'city' => 'Belleville'],
                ['state_id' => 4, 'city' => 'Bluffton'],
                ['state_id' => 4, 'city' => 'Briggsville'],
                ['state_id' => 4, 'city' => 'Centerville'],
                ['state_id' => 4, 'city' => 'Danville'],
                ['state_id' => 4, 'city' => 'Dardanelle'],
                ['state_id' => 4, 'city' => 'Gravelly'],
                ['state_id' => 4, 'city' => 'Havana'],
                ['state_id' => 4, 'city' => 'Ola'],
                ['state_id' => 4, 'city' => 'Plainview'],
                ['state_id' => 4, 'city' => 'Rover']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
