<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State35TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of ND - North Dakota.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 35, 'city' => 'Hettinger'],
                ['state_id' => 35, 'city' => 'Reeder'],
                ['state_id' => 35, 'city' => 'Fingal'],
                ['state_id' => 35, 'city' => 'Kathryn'],
                ['state_id' => 35, 'city' => 'Nome'],
                ['state_id' => 35, 'city' => 'Oriska'],
                ['state_id' => 35, 'city' => 'Pillsbury'],
                ['state_id' => 35, 'city' => 'Valley City'],
                ['state_id' => 35, 'city' => 'Dazey'],
                ['state_id' => 35, 'city' => 'Litchville'],
                ['state_id' => 35, 'city' => 'Rogers'],
                ['state_id' => 35, 'city' => 'Sanborn'],
                ['state_id' => 35, 'city' => 'Wimbledon'],
                ['state_id' => 35, 'city' => 'Esmond'],
                ['state_id' => 35, 'city' => 'Fort Totten'],
                ['state_id' => 35, 'city' => 'Knox'],
                ['state_id' => 35, 'city' => 'Leeds'],
                ['state_id' => 35, 'city' => 'Maddock'],
                ['state_id' => 35, 'city' => 'Minnewaukan'],
                ['state_id' => 35, 'city' => 'Oberon'],
                ['state_id' => 35, 'city' => 'Saint Michael'],
                ['state_id' => 35, 'city' => 'Tokio'],
                ['state_id' => 35, 'city' => 'Warwick'],
                ['state_id' => 35, 'city' => 'York'],
                ['state_id' => 35, 'city' => 'Fairfield'],
                ['state_id' => 35, 'city' => 'Medora'],
                ['state_id' => 35, 'city' => 'Bottineau'],
                ['state_id' => 35, 'city' => 'Willow City'],
                ['state_id' => 35, 'city' => 'Antler'],
                ['state_id' => 35, 'city' => 'Kramer'],
                ['state_id' => 35, 'city' => 'Lansford'],
                ['state_id' => 35, 'city' => 'Maxbass'],
                ['state_id' => 35, 'city' => 'Newburg'],
                ['state_id' => 35, 'city' => 'Souris'],
                ['state_id' => 35, 'city' => 'Westhope'],
                ['state_id' => 35, 'city' => 'Bowman'],
                ['state_id' => 35, 'city' => 'Rhame'],
                ['state_id' => 35, 'city' => 'Scranton'],
                ['state_id' => 35, 'city' => 'Bowbells'],
                ['state_id' => 35, 'city' => 'Columbus'],
                ['state_id' => 35, 'city' => 'Flaxton'],
                ['state_id' => 35, 'city' => 'Lignite'],
                ['state_id' => 35, 'city' => 'Portal'],
                ['state_id' => 35, 'city' => 'Powers Lake'],
                ['state_id' => 35, 'city' => 'Regan'],
                ['state_id' => 35, 'city' => 'Wing'],
                ['state_id' => 35, 'city' => 'Bismarck'],
                ['state_id' => 35, 'city' => 'Baldwin'],
                ['state_id' => 35, 'city' => 'Driscoll'],
                ['state_id' => 35, 'city' => 'Menoken'],
                ['state_id' => 35, 'city' => 'Moffit'],
                ['state_id' => 35, 'city' => 'Sterling'],
                ['state_id' => 35, 'city' => 'Absaraka'],
                ['state_id' => 35, 'city' => 'Amenia'],
                ['state_id' => 35, 'city' => 'Argusville'],
                ['state_id' => 35, 'city' => 'Arthur'],
                ['state_id' => 35, 'city' => 'Ayr'],
                ['state_id' => 35, 'city' => 'Buffalo'],
                ['state_id' => 35, 'city' => 'Casselton'],
                ['state_id' => 35, 'city' => 'Davenport'],
                ['state_id' => 35, 'city' => 'Erie'],
                ['state_id' => 35, 'city' => 'Gardner'],
                ['state_id' => 35, 'city' => 'Grandin'],
                ['state_id' => 35, 'city' => 'Harwood'],
                ['state_id' => 35, 'city' => 'Horace'],
                ['state_id' => 35, 'city' => 'Hunter'],
                ['state_id' => 35, 'city' => 'Kindred'],
                ['state_id' => 35, 'city' => 'Leonard'],
                ['state_id' => 35, 'city' => 'Mapleton'],
                ['state_id' => 35, 'city' => 'Page'],
                ['state_id' => 35, 'city' => 'Tower City'],
                ['state_id' => 35, 'city' => 'West Fargo'],
                ['state_id' => 35, 'city' => 'Wheatland'],
                ['state_id' => 35, 'city' => 'Fargo'],
                ['state_id' => 35, 'city' => 'Hannah'],
                ['state_id' => 35, 'city' => 'Langdon'],
                ['state_id' => 35, 'city' => 'Maida'],
                ['state_id' => 35, 'city' => 'Milton'],
                ['state_id' => 35, 'city' => 'Osnabrock'],
                ['state_id' => 35, 'city' => 'Wales'],
                ['state_id' => 35, 'city' => 'Alsen'],
                ['state_id' => 35, 'city' => 'Calvin'],
                ['state_id' => 35, 'city' => 'Munich'],
                ['state_id' => 35, 'city' => 'Nekoma'],
                ['state_id' => 35, 'city' => 'Sarles'],
                ['state_id' => 35, 'city' => 'Ellendale'],
                ['state_id' => 35, 'city' => 'Forbes'],
                ['state_id' => 35, 'city' => 'Fullerton'],
                ['state_id' => 35, 'city' => 'Oakes'],
                ['state_id' => 35, 'city' => 'Crosby'],
                ['state_id' => 35, 'city' => 'Noonan'],
                ['state_id' => 35, 'city' => 'Ambrose'],
                ['state_id' => 35, 'city' => 'Fortuna'],
                ['state_id' => 35, 'city' => 'Dodge'],
                ['state_id' => 35, 'city' => 'Dunn Center'],
                ['state_id' => 35, 'city' => 'Halliday'],
                ['state_id' => 35, 'city' => 'Killdeer'],
                ['state_id' => 35, 'city' => 'Manning'],
                ['state_id' => 35, 'city' => 'Marshall'],
                ['state_id' => 35, 'city' => 'New Rockford'],
                ['state_id' => 35, 'city' => 'Sheyenne'],
                ['state_id' => 35, 'city' => 'Braddock'],
                ['state_id' => 35, 'city' => 'Hague'],
                ['state_id' => 35, 'city' => 'Hazelton'],
                ['state_id' => 35, 'city' => 'Kintyre'],
                ['state_id' => 35, 'city' => 'Linton'],
                ['state_id' => 35, 'city' => 'Strasburg'],
                ['state_id' => 35, 'city' => 'Carrington'],
                ['state_id' => 35, 'city' => 'Glenfield'],
                ['state_id' => 35, 'city' => 'Grace City'],
                ['state_id' => 35, 'city' => 'Mchenry'],
                ['state_id' => 35, 'city' => 'Beach'],
                ['state_id' => 35, 'city' => 'Golva'],
                ['state_id' => 35, 'city' => 'Sentinel Butte'],
                ['state_id' => 35, 'city' => 'Grand Forks'],
                ['state_id' => 35, 'city' => 'Grand Forks Afb'],
                ['state_id' => 35, 'city' => 'Arvilla'],
                ['state_id' => 35, 'city' => 'Emerado'],
                ['state_id' => 35, 'city' => 'Gilby'],
                ['state_id' => 35, 'city' => 'Inkster'],
                ['state_id' => 35, 'city' => 'Larimore'],
                ['state_id' => 35, 'city' => 'Manvel'],
                ['state_id' => 35, 'city' => 'Mekinock'],
                ['state_id' => 35, 'city' => 'Niagara'],
                ['state_id' => 35, 'city' => 'Northwood'],
                ['state_id' => 35, 'city' => 'Reynolds'],
                ['state_id' => 35, 'city' => 'Thompson'],
                ['state_id' => 35, 'city' => 'Carson'],
                ['state_id' => 35, 'city' => 'Elgin'],
                ['state_id' => 35, 'city' => 'New Leipzig'],
                ['state_id' => 35, 'city' => 'Raleigh'],
                ['state_id' => 35, 'city' => 'Shields'],
                ['state_id' => 35, 'city' => 'Binford'],
                ['state_id' => 35, 'city' => 'Cooperstown'],
                ['state_id' => 35, 'city' => 'Hannaford'],
                ['state_id' => 35, 'city' => 'Jessie'],
                ['state_id' => 35, 'city' => 'Sutton'],
                ['state_id' => 35, 'city' => 'Mott'],
                ['state_id' => 35, 'city' => 'New England'],
                ['state_id' => 35, 'city' => 'Regent'],
                ['state_id' => 35, 'city' => 'Dawson'],
                ['state_id' => 35, 'city' => 'Pettibone'],
                ['state_id' => 35, 'city' => 'Robinson'],
                ['state_id' => 35, 'city' => 'Steele'],
                ['state_id' => 35, 'city' => 'Tappen'],
                ['state_id' => 35, 'city' => 'Tuttle'],
                ['state_id' => 35, 'city' => 'Berlin'],
                ['state_id' => 35, 'city' => 'Dickey'],
                ['state_id' => 35, 'city' => 'Edgeley'],
                ['state_id' => 35, 'city' => 'Jud'],
                ['state_id' => 35, 'city' => 'Kulm'],
                ['state_id' => 35, 'city' => 'Lamoure'],
                ['state_id' => 35, 'city' => 'Marion'],
                ['state_id' => 35, 'city' => 'Verona'],
                ['state_id' => 35, 'city' => 'Fredonia'],
                ['state_id' => 35, 'city' => 'Gackle'],
                ['state_id' => 35, 'city' => 'Napoleon'],
                ['state_id' => 35, 'city' => 'Anamoose'],
                ['state_id' => 35, 'city' => 'Balfour'],
                ['state_id' => 35, 'city' => 'Bantry'],
                ['state_id' => 35, 'city' => 'Deering'],
                ['state_id' => 35, 'city' => 'Drake'],
                ['state_id' => 35, 'city' => 'Granville'],
                ['state_id' => 35, 'city' => 'Karlsruhe'],
                ['state_id' => 35, 'city' => 'Norwich'],
                ['state_id' => 35, 'city' => 'Towner'],
                ['state_id' => 35, 'city' => 'Upham'],
                ['state_id' => 35, 'city' => 'Velva'],
                ['state_id' => 35, 'city' => 'Voltaire'],
                ['state_id' => 35, 'city' => 'Ashley'],
                ['state_id' => 35, 'city' => 'Lehr'],
                ['state_id' => 35, 'city' => 'Wishek'],
                ['state_id' => 35, 'city' => 'Zeeland'],
                ['state_id' => 35, 'city' => 'Grassy Butte'],
                ['state_id' => 35, 'city' => 'Mandaree'],
                ['state_id' => 35, 'city' => 'Alexander'],
                ['state_id' => 35, 'city' => 'Arnegard'],
                ['state_id' => 35, 'city' => 'Cartwright'],
                ['state_id' => 35, 'city' => 'Keene'],
                ['state_id' => 35, 'city' => 'Watford City'],
                ['state_id' => 35, 'city' => 'Coleharbor'],
                ['state_id' => 35, 'city' => 'Garrison'],
                ['state_id' => 35, 'city' => 'Mercer'],
                ['state_id' => 35, 'city' => 'Riverdale'],
                ['state_id' => 35, 'city' => 'Turtle Lake'],
                ['state_id' => 35, 'city' => 'Underwood'],
                ['state_id' => 35, 'city' => 'Washburn'],
                ['state_id' => 35, 'city' => 'Wilton'],
                ['state_id' => 35, 'city' => 'Benedict'],
                ['state_id' => 35, 'city' => 'Butte'],
                ['state_id' => 35, 'city' => 'Max'],
                ['state_id' => 35, 'city' => 'Roseglen'],
                ['state_id' => 35, 'city' => 'Ruso'],
                ['state_id' => 35, 'city' => 'Beulah'],
                ['state_id' => 35, 'city' => 'Golden Valley'],
                ['state_id' => 35, 'city' => 'Hazen'],
                ['state_id' => 35, 'city' => 'Stanton'],
                ['state_id' => 35, 'city' => 'Zap'],
                ['state_id' => 35, 'city' => 'Almont'],
                ['state_id' => 35, 'city' => 'Flasher'],
                ['state_id' => 35, 'city' => 'Mandan'],
                ['state_id' => 35, 'city' => 'New Salem'],
                ['state_id' => 35, 'city' => 'Saint Anthony'],
                ['state_id' => 35, 'city' => 'Glen Ullin'],
                ['state_id' => 35, 'city' => 'Hebron'],
                ['state_id' => 35, 'city' => 'New Town'],
                ['state_id' => 35, 'city' => 'Palermo'],
                ['state_id' => 35, 'city' => 'Parshall'],
                ['state_id' => 35, 'city' => 'Plaza'],
                ['state_id' => 35, 'city' => 'Ross'],
                ['state_id' => 35, 'city' => 'Stanley'],
                ['state_id' => 35, 'city' => 'White Earth'],
                ['state_id' => 35, 'city' => 'Aneta'],
                ['state_id' => 35, 'city' => 'Dahlen'],
                ['state_id' => 35, 'city' => 'Mcville'],
                ['state_id' => 35, 'city' => 'Michigan'],
                ['state_id' => 35, 'city' => 'Petersburg'],
                ['state_id' => 35, 'city' => 'Lakota'],
                ['state_id' => 35, 'city' => 'Pekin'],
                ['state_id' => 35, 'city' => 'Tolna'],
                ['state_id' => 35, 'city' => 'Center'],
                ['state_id' => 35, 'city' => 'Bathgate'],
                ['state_id' => 35, 'city' => 'Cavalier'],
                ['state_id' => 35, 'city' => 'Crystal'],
                ['state_id' => 35, 'city' => 'Drayton'],
                ['state_id' => 35, 'city' => 'Glasston'],
                ['state_id' => 35, 'city' => 'Hamilton'],
                ['state_id' => 35, 'city' => 'Hensel'],
                ['state_id' => 35, 'city' => 'Mountain'],
                ['state_id' => 35, 'city' => 'Neche'],
                ['state_id' => 35, 'city' => 'Pembina'],
                ['state_id' => 35, 'city' => 'Saint Thomas'],
                ['state_id' => 35, 'city' => 'Walhalla'],
                ['state_id' => 35, 'city' => 'Balta'],
                ['state_id' => 35, 'city' => 'Rugby'],
                ['state_id' => 35, 'city' => 'Wolford'],
                ['state_id' => 35, 'city' => 'Devils Lake'],
                ['state_id' => 35, 'city' => 'Brocket'],
                ['state_id' => 35, 'city' => 'Churchs Ferry'],
                ['state_id' => 35, 'city' => 'Crary'],
                ['state_id' => 35, 'city' => 'Edmore'],
                ['state_id' => 35, 'city' => 'Hampden'],
                ['state_id' => 35, 'city' => 'Lawton'],
                ['state_id' => 35, 'city' => 'Penn'],
                ['state_id' => 35, 'city' => 'Starkweather'],
                ['state_id' => 35, 'city' => 'Webster'],
                ['state_id' => 35, 'city' => 'Enderlin'],
                ['state_id' => 35, 'city' => 'Fort Ransom'],
                ['state_id' => 35, 'city' => 'Lisbon'],
                ['state_id' => 35, 'city' => 'Mcleod'],
                ['state_id' => 35, 'city' => 'Sheldon'],
                ['state_id' => 35, 'city' => 'Glenburn'],
                ['state_id' => 35, 'city' => 'Mohall'],
                ['state_id' => 35, 'city' => 'Sherwood'],
                ['state_id' => 35, 'city' => 'Tolley'],
                ['state_id' => 35, 'city' => 'Abercrombie'],
                ['state_id' => 35, 'city' => 'Barney'],
                ['state_id' => 35, 'city' => 'Christine'],
                ['state_id' => 35, 'city' => 'Colfax'],
                ['state_id' => 35, 'city' => 'Fairmount'],
                ['state_id' => 35, 'city' => 'Hankinson'],
                ['state_id' => 35, 'city' => 'Lidgerwood'],
                ['state_id' => 35, 'city' => 'Mantador'],
                ['state_id' => 35, 'city' => 'Mooreton'],
                ['state_id' => 35, 'city' => 'Wahpeton'],
                ['state_id' => 35, 'city' => 'Walcott'],
                ['state_id' => 35, 'city' => 'Wyndmere'],
                ['state_id' => 35, 'city' => 'Agate'],
                ['state_id' => 35, 'city' => 'Belcourt'],
                ['state_id' => 35, 'city' => 'Dunseith'],
                ['state_id' => 35, 'city' => 'Mylo'],
                ['state_id' => 35, 'city' => 'Rolette'],
                ['state_id' => 35, 'city' => 'Rolla'],
                ['state_id' => 35, 'city' => 'Saint John'],
                ['state_id' => 35, 'city' => 'Cayuga'],
                ['state_id' => 35, 'city' => 'Cogswell'],
                ['state_id' => 35, 'city' => 'Forman'],
                ['state_id' => 35, 'city' => 'Gwinner'],
                ['state_id' => 35, 'city' => 'Havana'],
                ['state_id' => 35, 'city' => 'Milnor'],
                ['state_id' => 35, 'city' => 'Rutland'],
                ['state_id' => 35, 'city' => 'Stirum'],
                ['state_id' => 35, 'city' => 'Denhoff'],
                ['state_id' => 35, 'city' => 'Goodrich'],
                ['state_id' => 35, 'city' => 'Mcclusky'],
                ['state_id' => 35, 'city' => 'Martin'],
                ['state_id' => 35, 'city' => 'Cannon Ball'],
                ['state_id' => 35, 'city' => 'Fort Yates'],
                ['state_id' => 35, 'city' => 'Selfridge'],
                ['state_id' => 35, 'city' => 'Solen'],
                ['state_id' => 35, 'city' => 'Amidon'],
                ['state_id' => 35, 'city' => 'Marmarth'],
                ['state_id' => 35, 'city' => 'Dickinson'],
                ['state_id' => 35, 'city' => 'Belfield'],
                ['state_id' => 35, 'city' => 'Gladstone'],
                ['state_id' => 35, 'city' => 'Lefor'],
                ['state_id' => 35, 'city' => 'Richardton'],
                ['state_id' => 35, 'city' => 'South Heart'],
                ['state_id' => 35, 'city' => 'Taylor'],
                ['state_id' => 35, 'city' => 'Hope'],
                ['state_id' => 35, 'city' => 'Luverne'],
                ['state_id' => 35, 'city' => 'Finley'],
                ['state_id' => 35, 'city' => 'Sharon'],
                ['state_id' => 35, 'city' => 'Jamestown'],
                ['state_id' => 35, 'city' => 'Buchanan'],
                ['state_id' => 35, 'city' => 'Cleveland'],
                ['state_id' => 35, 'city' => 'Courtenay'],
                ['state_id' => 35, 'city' => 'Kensal'],
                ['state_id' => 35, 'city' => 'Medina'],
                ['state_id' => 35, 'city' => 'Montpelier'],
                ['state_id' => 35, 'city' => 'Pingree'],
                ['state_id' => 35, 'city' => 'Spiritwood'],
                ['state_id' => 35, 'city' => 'Streeter'],
                ['state_id' => 35, 'city' => 'Woodworth'],
                ['state_id' => 35, 'city' => 'Ypsilanti'],
                ['state_id' => 35, 'city' => 'Bisbee'],
                ['state_id' => 35, 'city' => 'Cando'],
                ['state_id' => 35, 'city' => 'Egeland'],
                ['state_id' => 35, 'city' => 'Hansboro'],
                ['state_id' => 35, 'city' => 'Perth'],
                ['state_id' => 35, 'city' => 'Rocklake'],
                ['state_id' => 35, 'city' => 'Blanchard'],
                ['state_id' => 35, 'city' => 'Clifford'],
                ['state_id' => 35, 'city' => 'Galesburg'],
                ['state_id' => 35, 'city' => 'Hillsboro'],
                ['state_id' => 35, 'city' => 'Buxton'],
                ['state_id' => 35, 'city' => 'Caledonia'],
                ['state_id' => 35, 'city' => 'Cummings'],
                ['state_id' => 35, 'city' => 'Hatton'],
                ['state_id' => 35, 'city' => 'Mayville'],
                ['state_id' => 35, 'city' => 'Portland'],
                ['state_id' => 35, 'city' => 'Adams'],
                ['state_id' => 35, 'city' => 'Edinburg'],
                ['state_id' => 35, 'city' => 'Fairdale'],
                ['state_id' => 35, 'city' => 'Fordville'],
                ['state_id' => 35, 'city' => 'Forest River'],
                ['state_id' => 35, 'city' => 'Grafton'],
                ['state_id' => 35, 'city' => 'Hoople'],
                ['state_id' => 35, 'city' => 'Lankin'],
                ['state_id' => 35, 'city' => 'Minto'],
                ['state_id' => 35, 'city' => 'Park River'],
                ['state_id' => 35, 'city' => 'Pisek'],
                ['state_id' => 35, 'city' => 'Minot'],
                ['state_id' => 35, 'city' => 'Minot Afb'],
                ['state_id' => 35, 'city' => 'Berthold'],
                ['state_id' => 35, 'city' => 'Burlington'],
                ['state_id' => 35, 'city' => 'Carpio'],
                ['state_id' => 35, 'city' => 'Des Lacs'],
                ['state_id' => 35, 'city' => 'Donnybrook'],
                ['state_id' => 35, 'city' => 'Douglas'],
                ['state_id' => 35, 'city' => 'Kenmare'],
                ['state_id' => 35, 'city' => 'Makoti'],
                ['state_id' => 35, 'city' => 'Ryder'],
                ['state_id' => 35, 'city' => 'Sawyer'],
                ['state_id' => 35, 'city' => 'Surrey'],
                ['state_id' => 35, 'city' => 'Harvey'],
                ['state_id' => 35, 'city' => 'Bowdon'],
                ['state_id' => 35, 'city' => 'Cathay'],
                ['state_id' => 35, 'city' => 'Chaseley'],
                ['state_id' => 35, 'city' => 'Fessenden'],
                ['state_id' => 35, 'city' => 'Hurdsfield'],
                ['state_id' => 35, 'city' => 'Sykeston'],
                ['state_id' => 35, 'city' => 'Mcgregor'],
                ['state_id' => 35, 'city' => 'Wildrose'],
                ['state_id' => 35, 'city' => 'Williston'],
                ['state_id' => 35, 'city' => 'Alamo'],
                ['state_id' => 35, 'city' => 'Epping'],
                ['state_id' => 35, 'city' => 'Grenora'],
                ['state_id' => 35, 'city' => 'Ray'],
                ['state_id' => 35, 'city' => 'Tioga'],
                ['state_id' => 35, 'city' => 'Trenton'],
                ['state_id' => 35, 'city' => 'Zahl', 'state_id' => 29]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
