<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State11TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of GA - Georgia.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 11, 'city' => 'Baxley'],
                ['state_id' => 11, 'city' => 'Saint George'],
                ['state_id' => 11, 'city' => 'Surrency'],
                ['state_id' => 11, 'city' => 'Axson'],
                ['state_id' => 11, 'city' => 'Pearson'],
                ['state_id' => 11, 'city' => 'Willacoochee'],
                ['state_id' => 11, 'city' => 'Alma'],
                ['state_id' => 11, 'city' => 'Albany'],
                ['state_id' => 11, 'city' => 'Colquitt'],
                ['state_id' => 11, 'city' => 'Damascus'],
                ['state_id' => 11, 'city' => 'Donalsonville'],
                ['state_id' => 11, 'city' => 'Leary'],
                ['state_id' => 11, 'city' => 'Newton'],
                ['state_id' => 11, 'city' => 'Hardwick'],
                ['state_id' => 11, 'city' => 'Milledgeville'],
                ['state_id' => 11, 'city' => 'Baldwin'],
                ['state_id' => 11, 'city' => 'Homer'],
                ['state_id' => 11, 'city' => 'Maysville'],
                ['state_id' => 11, 'city' => 'Auburn'],
                ['state_id' => 11, 'city' => 'Bethlehem'],
                ['state_id' => 11, 'city' => 'Statham'],
                ['state_id' => 11, 'city' => 'Winder'],
                ['state_id' => 11, 'city' => 'Adairsville'],
                ['state_id' => 11, 'city' => 'Cartersville'],
                ['state_id' => 11, 'city' => 'Cassville'],
                ['state_id' => 11, 'city' => 'Emerson'],
                ['state_id' => 11, 'city' => 'Kingston'],
                ['state_id' => 11, 'city' => 'Rydal'],
                ['state_id' => 11, 'city' => 'Taylorsville'],
                ['state_id' => 11, 'city' => 'White'],
                ['state_id' => 11, 'city' => 'Fitzgerald'],
                ['state_id' => 11, 'city' => 'Cuthbert'],
                ['state_id' => 11, 'city' => 'Alapaha'],
                ['state_id' => 11, 'city' => 'Nashville'],
                ['state_id' => 11, 'city' => 'Ray City'],
                ['state_id' => 11, 'city' => 'Enigma'],
                ['state_id' => 11, 'city' => 'Lizella'],
                ['state_id' => 11, 'city' => 'Macon'],
                ['state_id' => 11, 'city' => 'Cochran'],
                ['state_id' => 11, 'city' => 'Hoboken'],
                ['state_id' => 11, 'city' => 'Hortense'],
                ['state_id' => 11, 'city' => 'Nahunta'],
                ['state_id' => 11, 'city' => 'Waynesville'],
                ['state_id' => 11, 'city' => 'Barney'],
                ['state_id' => 11, 'city' => 'Dixie'],
                ['state_id' => 11, 'city' => 'Morven'],
                ['state_id' => 11, 'city' => 'Quitman'],
                ['state_id' => 11, 'city' => 'Barwick'],
                ['state_id' => 11, 'city' => 'Ellabell'],
                ['state_id' => 11, 'city' => 'Pembroke'],
                ['state_id' => 11, 'city' => 'Richmond Hill'],
                ['state_id' => 11, 'city' => 'Brooklet'],
                ['state_id' => 11, 'city' => 'Portal'],
                ['state_id' => 11, 'city' => 'Register'],
                ['state_id' => 11, 'city' => 'Statesboro'],
                ['state_id' => 11, 'city' => 'Girard'],
                ['state_id' => 11, 'city' => 'Midville'],
                ['state_id' => 11, 'city' => 'Sardis'],
                ['state_id' => 11, 'city' => 'Gough'],
                ['state_id' => 11, 'city' => 'Keysville'],
                ['state_id' => 11, 'city' => 'Waynesboro'],
                ['state_id' => 11, 'city' => 'Flovilla'],
                ['state_id' => 11, 'city' => 'Jackson'],
                ['state_id' => 11, 'city' => 'Jenkinsburg'],
                ['state_id' => 11, 'city' => 'Dawson'],
                ['state_id' => 11, 'city' => 'Morgan'],
                ['state_id' => 11, 'city' => 'Shellman'],
                ['state_id' => 11, 'city' => 'Kings Bay'],
                ['state_id' => 11, 'city' => 'Kingsland'],
                ['state_id' => 11, 'city' => 'Saint Marys'],
                ['state_id' => 11, 'city' => 'Waverly'],
                ['state_id' => 11, 'city' => 'White Oak'],
                ['state_id' => 11, 'city' => 'Woodbine'],
                ['state_id' => 11, 'city' => 'Metter'],
                ['state_id' => 11, 'city' => 'Pulaski'],
                ['state_id' => 11, 'city' => 'Bowdon'],
                ['state_id' => 11, 'city' => 'Bowdon Junction'],
                ['state_id' => 11, 'city' => 'Carrollton'],
                ['state_id' => 11, 'city' => 'Mount Zion'],
                ['state_id' => 11, 'city' => 'Roopville'],
                ['state_id' => 11, 'city' => 'Temple'],
                ['state_id' => 11, 'city' => 'Villa Rica'],
                ['state_id' => 11, 'city' => 'Whitesburg'],
                ['state_id' => 11, 'city' => 'Graysville'],
                ['state_id' => 11, 'city' => 'Ringgold'],
                ['state_id' => 11, 'city' => 'Fort Oglethorpe'],
                ['state_id' => 11, 'city' => 'Folkston'],
                ['state_id' => 11, 'city' => 'Bloomingdale'],
                ['state_id' => 11, 'city' => 'Pooler'],
                ['state_id' => 11, 'city' => 'Tybee Island'],
                ['state_id' => 11, 'city' => 'Savannah'],
                ['state_id' => 11, 'city' => 'Port Wentworth'],
                ['state_id' => 11, 'city' => 'Cusseta'],
                ['state_id' => 11, 'city' => 'Lyerly'],
                ['state_id' => 11, 'city' => 'Menlo'],
                ['state_id' => 11, 'city' => 'Summerville'],
                ['state_id' => 11, 'city' => 'Trion'],
                ['state_id' => 11, 'city' => 'Ball Ground'],
                ['state_id' => 11, 'city' => 'Canton'],
                ['state_id' => 11, 'city' => 'Holly Springs'],
                ['state_id' => 11, 'city' => 'Lebanon'],
                ['state_id' => 11, 'city' => 'Nelson'],
                ['state_id' => 11, 'city' => 'Waleska'],
                ['state_id' => 11, 'city' => 'Woodstock'],
                ['state_id' => 11, 'city' => 'Athens'],
                ['state_id' => 11, 'city' => 'Winterville'],
                ['state_id' => 11, 'city' => 'Blakely'],
                ['state_id' => 11, 'city' => 'Bluffton'],
                ['state_id' => 11, 'city' => 'Coleman'],
                ['state_id' => 11, 'city' => 'Edison'],
                ['state_id' => 11, 'city' => 'Fort Gaines'],
                ['state_id' => 11, 'city' => 'Georgetown'],
                ['state_id' => 11, 'city' => 'Morris'],
                ['state_id' => 11, 'city' => 'Jonesboro'],
                ['state_id' => 11, 'city' => 'Lovejoy'],
                ['state_id' => 11, 'city' => 'Morrow'],
                ['state_id' => 11, 'city' => 'Rex'],
                ['state_id' => 11, 'city' => 'Riverdale'],
                ['state_id' => 11, 'city' => 'Conley'],
                ['state_id' => 11, 'city' => 'Ellenwood'],
                ['state_id' => 11, 'city' => 'Forest Park'],
                ['state_id' => 11, 'city' => 'Argyle'],
                ['state_id' => 11, 'city' => 'Du Pont'],
                ['state_id' => 11, 'city' => 'Fargo'],
                ['state_id' => 11, 'city' => 'Homerville'],
                ['state_id' => 11, 'city' => 'Marietta'],
                ['state_id' => 11, 'city' => 'Smyrna'],
                ['state_id' => 11, 'city' => 'Acworth'],
                ['state_id' => 11, 'city' => 'Austell'],
                ['state_id' => 11, 'city' => 'Clarkdale'],
                ['state_id' => 11, 'city' => 'Mableton'],
                ['state_id' => 11, 'city' => 'Powder Springs'],
                ['state_id' => 11, 'city' => 'Kennesaw'],
                ['state_id' => 11, 'city' => 'Ambrose'],
                ['state_id' => 11, 'city' => 'Broxton'],
                ['state_id' => 11, 'city' => 'Douglas'],
                ['state_id' => 11, 'city' => 'Nicholls'],
                ['state_id' => 11, 'city' => 'West Green'],
                ['state_id' => 11, 'city' => 'Berlin'],
                ['state_id' => 11, 'city' => 'Doerun'],
                ['state_id' => 11, 'city' => 'Ellenton'],
                ['state_id' => 11, 'city' => 'Funston'],
                ['state_id' => 11, 'city' => 'Hartsfield'],
                ['state_id' => 11, 'city' => 'Moultrie'],
                ['state_id' => 11, 'city' => 'Norman Park'],
                ['state_id' => 11, 'city' => 'Appling'],
                ['state_id' => 11, 'city' => 'Evans'],
                ['state_id' => 11, 'city' => 'Grovetown'],
                ['state_id' => 11, 'city' => 'Harlem'],
                ['state_id' => 11, 'city' => 'Augusta'],
                ['state_id' => 11, 'city' => 'Arlington'],
                ['state_id' => 11, 'city' => 'Adel'],
                ['state_id' => 11, 'city' => 'Cecil'],
                ['state_id' => 11, 'city' => 'Lenox'],
                ['state_id' => 11, 'city' => 'Sparks'],
                ['state_id' => 11, 'city' => 'Grantville'],
                ['state_id' => 11, 'city' => 'Haralson'],
                ['state_id' => 11, 'city' => 'Moreland'],
                ['state_id' => 11, 'city' => 'Newnan'],
                ['state_id' => 11, 'city' => 'Sargent'],
                ['state_id' => 11, 'city' => 'Senoia'],
                ['state_id' => 11, 'city' => 'Sharpsburg'],
                ['state_id' => 11, 'city' => 'Turin'],
                ['state_id' => 11, 'city' => 'Knoxville'],
                ['state_id' => 11, 'city' => 'Musella'],
                ['state_id' => 11, 'city' => 'Roberta'],
                ['state_id' => 11, 'city' => 'Cordele'],
                ['state_id' => 11, 'city' => 'Arabi'],
                ['state_id' => 11, 'city' => 'Rising Fawn'],
                ['state_id' => 11, 'city' => 'Trenton'],
                ['state_id' => 11, 'city' => 'Wildwood'],
                ['state_id' => 11, 'city' => 'Dawsonville'],
                ['state_id' => 11, 'city' => 'Attapulgus'],
                ['state_id' => 11, 'city' => 'Bainbridge'],
                ['state_id' => 11, 'city' => 'Fowlstown'],
                ['state_id' => 11, 'city' => 'Avondale Estates'],
                ['state_id' => 11, 'city' => 'Clarkston'],
                ['state_id' => 11, 'city' => 'Decatur'],
                ['state_id' => 11, 'city' => 'Lithonia'],
                ['state_id' => 11, 'city' => 'Pine Lake'],
                ['state_id' => 11, 'city' => 'Redan'],
                ['state_id' => 11, 'city' => 'Scottdale'],
                ['state_id' => 11, 'city' => 'Stone Mountain'],
                ['state_id' => 11, 'city' => 'Tucker'],
                ['state_id' => 11, 'city' => 'Atlanta'],
                ['state_id' => 11, 'city' => 'Chauncey'],
                ['state_id' => 11, 'city' => 'Chester'],
                ['state_id' => 11, 'city' => 'Eastman'],
                ['state_id' => 11, 'city' => 'Rhine'],
                ['state_id' => 11, 'city' => 'Byromville'],
                ['state_id' => 11, 'city' => 'Lilly'],
                ['state_id' => 11, 'city' => 'Montezuma'],
                ['state_id' => 11, 'city' => 'Pinehurst'],
                ['state_id' => 11, 'city' => 'Unadilla'],
                ['state_id' => 11, 'city' => 'Vienna'],
                ['state_id' => 11, 'city' => 'Putney'],
                ['state_id' => 11, 'city' => 'Lithia Springs'],
                ['state_id' => 11, 'city' => 'Douglasville'],
                ['state_id' => 11, 'city' => 'Winston'],
                ['state_id' => 11, 'city' => 'Cedar Springs'],
                ['state_id' => 11, 'city' => 'Climax'],
                ['state_id' => 11, 'city' => 'Statenville'],
                ['state_id' => 11, 'city' => 'Clyo'],
                ['state_id' => 11, 'city' => 'Eden'],
                ['state_id' => 11, 'city' => 'Guyton'],
                ['state_id' => 11, 'city' => 'Meldrim'],
                ['state_id' => 11, 'city' => 'Rincon'],
                ['state_id' => 11, 'city' => 'Springfield'],
                ['state_id' => 11, 'city' => 'Bowman'],
                ['state_id' => 11, 'city' => 'Dewy Rose'],
                ['state_id' => 11, 'city' => 'Elberton'],
                ['state_id' => 11, 'city' => 'Swainsboro'],
                ['state_id' => 11, 'city' => 'Garfield'],
                ['state_id' => 11, 'city' => 'Norristown'],
                ['state_id' => 11, 'city' => 'Nunez'],
                ['state_id' => 11, 'city' => 'Stillmore'],
                ['state_id' => 11, 'city' => 'Twin City'],
                ['state_id' => 11, 'city' => 'Adrian'],
                ['state_id' => 11, 'city' => 'Bellville'],
                ['state_id' => 11, 'city' => 'Claxton'],
                ['state_id' => 11, 'city' => 'Daisy'],
                ['state_id' => 11, 'city' => 'Hagan'],
                ['state_id' => 11, 'city' => 'Blue Ridge'],
                ['state_id' => 11, 'city' => 'Epworth'],
                ['state_id' => 11, 'city' => 'Mc Caysville'],
                ['state_id' => 11, 'city' => 'Mineral Bluff'],
                ['state_id' => 11, 'city' => 'Morganton'],
                ['state_id' => 11, 'city' => 'Brooks'],
                ['state_id' => 11, 'city' => 'Fayetteville'],
                ['state_id' => 11, 'city' => 'Peachtree City'],
                ['state_id' => 11, 'city' => 'Tyrone'],
                ['state_id' => 11, 'city' => 'Armuchee'],
                ['state_id' => 11, 'city' => 'Cave Spring'],
                ['state_id' => 11, 'city' => 'Coosa'],
                ['state_id' => 11, 'city' => 'Lindale'],
                ['state_id' => 11, 'city' => 'Mount Berry'],
                ['state_id' => 11, 'city' => 'Rome'],
                ['state_id' => 11, 'city' => 'Shannon'],
                ['state_id' => 11, 'city' => 'Silver Creek'],
                ['state_id' => 11, 'city' => 'Cumming'],
                ['state_id' => 11, 'city' => 'Canon'],
                ['state_id' => 11, 'city' => 'Carnesville'],
                ['state_id' => 11, 'city' => 'Lavonia'],
                ['state_id' => 11, 'city' => 'Franklin Springs'],
                ['state_id' => 11, 'city' => 'Royston'],
                ['state_id' => 11, 'city' => 'Alpharetta'],
                ['state_id' => 11, 'city' => 'Roswell'],
                ['state_id' => 11, 'city' => 'Fairburn'],
                ['state_id' => 11, 'city' => 'Palmetto'],
                ['state_id' => 11, 'city' => 'Red Oak'],
                ['state_id' => 11, 'city' => 'Union City'],
                ['state_id' => 11, 'city' => 'Cherry Log'],
                ['state_id' => 11, 'city' => 'Ellijay'],
                ['state_id' => 11, 'city' => 'East Ellijay'],
                ['state_id' => 11, 'city' => 'Gibson'],
                ['state_id' => 11, 'city' => 'Mitchell'],
                ['state_id' => 11, 'city' => 'Brunswick'],
                ['state_id' => 11, 'city' => 'Saint Simons Island'],
                ['state_id' => 11, 'city' => 'Jekyll Island'],
                ['state_id' => 11, 'city' => 'Sea Island'],
                ['state_id' => 11, 'city' => 'Fairmount'],
                ['state_id' => 11, 'city' => 'Calhoun'],
                ['state_id' => 11, 'city' => 'Oakman'],
                ['state_id' => 11, 'city' => 'Plainville'],
                ['state_id' => 11, 'city' => 'Ranger'],
                ['state_id' => 11, 'city' => 'Resaca'],
                ['state_id' => 11, 'city' => 'Sugar Valley'],
                ['state_id' => 11, 'city' => 'Cairo'],
                ['state_id' => 11, 'city' => 'Calvary'],
                ['state_id' => 11, 'city' => 'Whigham'],
                ['state_id' => 11, 'city' => 'Greensboro'],
                ['state_id' => 11, 'city' => 'Siloam'],
                ['state_id' => 11, 'city' => 'Union Point'],
                ['state_id' => 11, 'city' => 'White Plains'],
                ['state_id' => 11, 'city' => 'Norcross'],
                ['state_id' => 11, 'city' => 'Grayson'],
                ['state_id' => 11, 'city' => 'Dacula'],
                ['state_id' => 11, 'city' => 'Suwanee'],
                ['state_id' => 11, 'city' => 'North Metro'],
                ['state_id' => 11, 'city' => 'Snellville'],
                ['state_id' => 11, 'city' => 'Lawrenceville'],
                ['state_id' => 11, 'city' => 'Lilburn'],
                ['state_id' => 11, 'city' => 'Loganville'],
                ['state_id' => 11, 'city' => 'Peachtree Corners'],
                ['state_id' => 11, 'city' => 'Duluth'],
                ['state_id' => 11, 'city' => 'Buford'],
                ['state_id' => 11, 'city' => 'Alto'],
                ['state_id' => 11, 'city' => 'Clarkesville'],
                ['state_id' => 11, 'city' => 'Cornelia'],
                ['state_id' => 11, 'city' => 'Demorest'],
                ['state_id' => 11, 'city' => 'Mount Airy'],
                ['state_id' => 11, 'city' => 'Turnerville'],
                ['state_id' => 11, 'city' => 'Gainesville'],
                ['state_id' => 11, 'city' => 'Chestnut Mountain'],
                ['state_id' => 11, 'city' => 'Clermont'],
                ['state_id' => 11, 'city' => 'Flowery Branch'],
                ['state_id' => 11, 'city' => 'Gillsville'],
                ['state_id' => 11, 'city' => 'Lula'],
                ['state_id' => 11, 'city' => 'Murrayville'],
                ['state_id' => 11, 'city' => 'Oakwood'],
                ['state_id' => 11, 'city' => 'Sparta'],
                ['state_id' => 11, 'city' => 'Bremen'],
                ['state_id' => 11, 'city' => 'Buchanan'],
                ['state_id' => 11, 'city' => 'Felton'],
                ['state_id' => 11, 'city' => 'Tallapoosa'],
                ['state_id' => 11, 'city' => 'Waco'],
                ['state_id' => 11, 'city' => 'Cataula'],
                ['state_id' => 11, 'city' => 'Ellerslie'],
                ['state_id' => 11, 'city' => 'Hamilton'],
                ['state_id' => 11, 'city' => 'Pine Mountain'],
                ['state_id' => 11, 'city' => 'Pine Mountain Valley'],
                ['state_id' => 11, 'city' => 'Shiloh'],
                ['state_id' => 11, 'city' => 'Waverly Hall'],
                ['state_id' => 11, 'city' => 'Bowersville'],
                ['state_id' => 11, 'city' => 'Hartwell'],
                ['state_id' => 11, 'city' => 'Franklin'],
                ['state_id' => 11, 'city' => 'Hampton'],
                ['state_id' => 11, 'city' => 'Locust Grove'],
                ['state_id' => 11, 'city' => 'Mcdonough'],
                ['state_id' => 11, 'city' => 'Stockbridge'],
                ['state_id' => 11, 'city' => 'Bonaire'],
                ['state_id' => 11, 'city' => 'Clinchfield'],
                ['state_id' => 11, 'city' => 'Elko'],
                ['state_id' => 11, 'city' => 'Centerville'],
                ['state_id' => 11, 'city' => 'Kathleen'],
                ['state_id' => 11, 'city' => 'Perry'],
                ['state_id' => 11, 'city' => 'Warner Robins'],
                ['state_id' => 11, 'city' => 'Irwinville'],
                ['state_id' => 11, 'city' => 'Mystic'],
                ['state_id' => 11, 'city' => 'Ocilla'],
                ['state_id' => 11, 'city' => 'Wray'],
                ['state_id' => 11, 'city' => 'Braselton'],
                ['state_id' => 11, 'city' => 'Commerce'],
                ['state_id' => 11, 'city' => 'Hoschton'],
                ['state_id' => 11, 'city' => 'Jefferson'],
                ['state_id' => 11, 'city' => 'Nicholson'],
                ['state_id' => 11, 'city' => 'Pendergrass'],
                ['state_id' => 11, 'city' => 'Talmo'],
                ['state_id' => 11, 'city' => 'Mansfield'],
                ['state_id' => 11, 'city' => 'Hillsboro'],
                ['state_id' => 11, 'city' => 'Monticello'],
                ['state_id' => 11, 'city' => 'Shady Dale'],
                ['state_id' => 11, 'city' => 'Denton'],
                ['state_id' => 11, 'city' => 'Hazlehurst'],
                ['state_id' => 11, 'city' => 'Bartow'],
                ['state_id' => 11, 'city' => 'Louisville'],
                ['state_id' => 11, 'city' => 'Wadley'],
                ['state_id' => 11, 'city' => 'Avera'],
                ['state_id' => 11, 'city' => 'Matthews'],
                ['state_id' => 11, 'city' => 'Stapleton'],
                ['state_id' => 11, 'city' => 'Wrens'],
                ['state_id' => 11, 'city' => 'Millen'],
                ['state_id' => 11, 'city' => 'Perkins'],
                ['state_id' => 11, 'city' => 'Kite'],
                ['state_id' => 11, 'city' => 'Wrightsville'],
                ['state_id' => 11, 'city' => 'Gray'],
                ['state_id' => 11, 'city' => 'Haddock'],
                ['state_id' => 11, 'city' => 'Barnesville'],
                ['state_id' => 11, 'city' => 'Milner'],
                ['state_id' => 11, 'city' => 'Lakeland'],
                ['state_id' => 11, 'city' => 'Stockton'],
                ['state_id' => 11, 'city' => 'Rockledge'],
                ['state_id' => 11, 'city' => 'Cadwell'],
                ['state_id' => 11, 'city' => 'Dexter'],
                ['state_id' => 11, 'city' => 'Dublin'],
                ['state_id' => 11, 'city' => 'Dudley'],
                ['state_id' => 11, 'city' => 'East Dublin'],
                ['state_id' => 11, 'city' => 'Montrose'],
                ['state_id' => 11, 'city' => 'Rentz'],
                ['state_id' => 11, 'city' => 'Leesburg'],
                ['state_id' => 11, 'city' => 'Smithville'],
                ['state_id' => 11, 'city' => 'Allenhurst'],
                ['state_id' => 11, 'city' => 'Fleming'],
                ['state_id' => 11, 'city' => 'Hinesville'],
                ['state_id' => 11, 'city' => 'Fort Stewart'],
                ['state_id' => 11, 'city' => 'Midway'],
                ['state_id' => 11, 'city' => 'Riceboro'],
                ['state_id' => 11, 'city' => 'Walthourville'],
                ['state_id' => 11, 'city' => 'Lincolnton'],
                ['state_id' => 11, 'city' => 'Ludowici'],
                ['state_id' => 11, 'city' => 'Valdosta'],
                ['state_id' => 11, 'city' => 'Hahira'],
                ['state_id' => 11, 'city' => 'Lake Park'],
                ['state_id' => 11, 'city' => 'Naylor'],
                ['state_id' => 11, 'city' => 'Moody Afb'],
                ['state_id' => 11, 'city' => 'Dahlonega'],
                ['state_id' => 11, 'city' => 'Boneville'],
                ['state_id' => 11, 'city' => 'Dearing'],
                ['state_id' => 11, 'city' => 'Thomson'],
                ['state_id' => 11, 'city' => 'Crescent'],
                ['state_id' => 11, 'city' => 'Darien'],
                ['state_id' => 11, 'city' => 'Meridian'],
                ['state_id' => 11, 'city' => 'Sapelo Island'],
                ['state_id' => 11, 'city' => 'Townsend'],
                ['state_id' => 11, 'city' => 'Ideal'],
                ['state_id' => 11, 'city' => 'Marshallville'],
                ['state_id' => 11, 'city' => 'Oglethorpe'],
                ['state_id' => 11, 'city' => 'Carlton'],
                ['state_id' => 11, 'city' => 'Colbert'],
                ['state_id' => 11, 'city' => 'Comer'],
                ['state_id' => 11, 'city' => 'Danielsville'],
                ['state_id' => 11, 'city' => 'Hull'],
                ['state_id' => 11, 'city' => 'Ila'],
                ['state_id' => 11, 'city' => 'Buena Vista'],
                ['state_id' => 11, 'city' => 'Gay'],
                ['state_id' => 11, 'city' => 'Greenville'],
                ['state_id' => 11, 'city' => 'Luthersville'],
                ['state_id' => 11, 'city' => 'Woodbury'],
                ['state_id' => 11, 'city' => 'Manchester'],
                ['state_id' => 11, 'city' => 'Warm Springs'],
                ['state_id' => 11, 'city' => 'Baconton'],
                ['state_id' => 11, 'city' => 'Camilla'],
                ['state_id' => 11, 'city' => 'Cotton'],
                ['state_id' => 11, 'city' => 'Pelham'],
                ['state_id' => 11, 'city' => 'Sale City'],
                ['state_id' => 11, 'city' => 'Bolingbroke'],
                ['state_id' => 11, 'city' => 'Culloden'],
                ['state_id' => 11, 'city' => 'Forsyth'],
                ['state_id' => 11, 'city' => 'Juliette'],
                ['state_id' => 11, 'city' => 'Smarr'],
                ['state_id' => 11, 'city' => 'Ailey'],
                ['state_id' => 11, 'city' => 'Alston'],
                ['state_id' => 11, 'city' => 'Mount Vernon'],
                ['state_id' => 11, 'city' => 'Tarrytown'],
                ['state_id' => 11, 'city' => 'Uvalda'],
                ['state_id' => 11, 'city' => 'Bostwick'],
                ['state_id' => 11, 'city' => 'Buckhead'],
                ['state_id' => 11, 'city' => 'High Shoals'],
                ['state_id' => 11, 'city' => 'Madison'],
                ['state_id' => 11, 'city' => 'Rutledge'],
                ['state_id' => 11, 'city' => 'Chatsworth'],
                ['state_id' => 11, 'city' => 'Cisco'],
                ['state_id' => 11, 'city' => 'Crandall'],
                ['state_id' => 11, 'city' => 'Eton'],
                ['state_id' => 11, 'city' => 'Tennga'],
                ['state_id' => 11, 'city' => 'Fortson'],
                ['state_id' => 11, 'city' => 'Midland'],
                ['state_id' => 11, 'city' => 'Upatoi'],
                ['state_id' => 11, 'city' => 'Columbus'],
                ['state_id' => 11, 'city' => 'Fort Benning'],
                ['state_id' => 11, 'city' => 'Covington'],
                ['state_id' => 11, 'city' => 'Oxford'],
                ['state_id' => 11, 'city' => 'Newborn'],
                ['state_id' => 11, 'city' => 'Porterdale'],
                ['state_id' => 11, 'city' => 'Bishop'],
                ['state_id' => 11, 'city' => 'Bogart'],
                ['state_id' => 11, 'city' => 'Farmington'],
                ['state_id' => 11, 'city' => 'Watkinsville'],
                ['state_id' => 11, 'city' => 'Arnoldsville'],
                ['state_id' => 11, 'city' => 'Crawford'],
                ['state_id' => 11, 'city' => 'Lexington'],
                ['state_id' => 11, 'city' => 'Stephens'],
                ['state_id' => 11, 'city' => 'Maxeys'],
                ['state_id' => 11, 'city' => 'Dallas'],
                ['state_id' => 11, 'city' => 'Hiram'],
                ['state_id' => 11, 'city' => 'Byron'],
                ['state_id' => 11, 'city' => 'Fort Valley'],
                ['state_id' => 11, 'city' => 'Jasper'],
                ['state_id' => 11, 'city' => 'Marble Hill'],
                ['state_id' => 11, 'city' => 'Talking Rock'],
                ['state_id' => 11, 'city' => 'Tate'],
                ['state_id' => 11, 'city' => 'Blackshear'],
                ['state_id' => 11, 'city' => 'Bristol'],
                ['state_id' => 11, 'city' => 'Mershon'],
                ['state_id' => 11, 'city' => 'Offerman'],
                ['state_id' => 11, 'city' => 'Patterson'],
                ['state_id' => 11, 'city' => 'Concord'],
                ['state_id' => 11, 'city' => 'Meansville'],
                ['state_id' => 11, 'city' => 'Molena'],
                ['state_id' => 11, 'city' => 'Williamson'],
                ['state_id' => 11, 'city' => 'Zebulon'],
                ['state_id' => 11, 'city' => 'Aragon'],
                ['state_id' => 11, 'city' => 'Cedartown'],
                ['state_id' => 11, 'city' => 'Esom Hill'],
                ['state_id' => 11, 'city' => 'Rockmart'],
                ['state_id' => 11, 'city' => 'Hawkinsville'],
                ['state_id' => 11, 'city' => 'Eatonton'],
                ['state_id' => 11, 'city' => 'Clayton'],
                ['state_id' => 11, 'city' => 'Dillard'],
                ['state_id' => 11, 'city' => 'Lakemont'],
                ['state_id' => 11, 'city' => 'Mountain City'],
                ['state_id' => 11, 'city' => 'Rabun Gap'],
                ['state_id' => 11, 'city' => 'Tallulah Falls'],
                ['state_id' => 11, 'city' => 'Tiger'],
                ['state_id' => 11, 'city' => 'Wiley'],
                ['state_id' => 11, 'city' => 'Blythe'],
                ['state_id' => 11, 'city' => 'Gracewood'],
                ['state_id' => 11, 'city' => 'Hephzibah'],
                ['state_id' => 11, 'city' => 'Conyers'],
                ['state_id' => 11, 'city' => 'Ellaville'],
                ['state_id' => 11, 'city' => 'Dover'],
                ['state_id' => 11, 'city' => 'Newington'],
                ['state_id' => 11, 'city' => 'Oliver'],
                ['state_id' => 11, 'city' => 'Rocky Ford'],
                ['state_id' => 11, 'city' => 'Sylvania'],
                ['state_id' => 11, 'city' => 'Brinson'],
                ['state_id' => 11, 'city' => 'Iron City'],
                ['state_id' => 11, 'city' => 'Jakin'],
                ['state_id' => 11, 'city' => 'Experiment'],
                ['state_id' => 11, 'city' => 'Griffin'],
                ['state_id' => 11, 'city' => 'Orchard Hill'],
                ['state_id' => 11, 'city' => 'Sunny Side'],
                ['state_id' => 11, 'city' => 'Eastanollee'],
                ['state_id' => 11, 'city' => 'Martin'],
                ['state_id' => 11, 'city' => 'Toccoa'],
                ['state_id' => 11, 'city' => 'Toccoa Falls'],
                ['state_id' => 11, 'city' => 'Louvale'],
                ['state_id' => 11, 'city' => 'Lumpkin'],
                ['state_id' => 11, 'city' => 'Omaha'],
                ['state_id' => 11, 'city' => 'Richland'],
                ['state_id' => 11, 'city' => 'Americus'],
                ['state_id' => 11, 'city' => 'Andersonville'],
                ['state_id' => 11, 'city' => 'Cobb'],
                ['state_id' => 11, 'city' => 'De Soto'],
                ['state_id' => 11, 'city' => 'Leslie'],
                ['state_id' => 11, 'city' => 'Plains'],
                ['state_id' => 11, 'city' => 'Box Springs'],
                ['state_id' => 11, 'city' => 'Geneva'],
                ['state_id' => 11, 'city' => 'Junction City'],
                ['state_id' => 11, 'city' => 'Talbotton'],
                ['state_id' => 11, 'city' => 'Woodland'],
                ['state_id' => 11, 'city' => 'Crawfordville'],
                ['state_id' => 11, 'city' => 'Sharon'],
                ['state_id' => 11, 'city' => 'Cobbtown'],
                ['state_id' => 11, 'city' => 'Collins'],
                ['state_id' => 11, 'city' => 'Glennville'],
                ['state_id' => 11, 'city' => 'Manassas'],
                ['state_id' => 11, 'city' => 'Reidsville'],
                ['state_id' => 11, 'city' => 'Butler'],
                ['state_id' => 11, 'city' => 'Howard'],
                ['state_id' => 11, 'city' => 'Mauk'],
                ['state_id' => 11, 'city' => 'Reynolds'],
                ['state_id' => 11, 'city' => 'Rupert'],
                ['state_id' => 11, 'city' => 'Mc Rae Helena'],
                ['state_id' => 11, 'city' => 'Milan'],
                ['state_id' => 11, 'city' => 'Scotland'],
                ['state_id' => 11, 'city' => 'Jacksonville'],
                ['state_id' => 11, 'city' => 'Lumber City'],
                ['state_id' => 11, 'city' => 'Bronwood'],
                ['state_id' => 11, 'city' => 'Sasser'],
                ['state_id' => 11, 'city' => 'Boston'],
                ['state_id' => 11, 'city' => 'Coolidge'],
                ['state_id' => 11, 'city' => 'Thomasville'],
                ['state_id' => 11, 'city' => 'Meigs'],
                ['state_id' => 11, 'city' => 'Ochlocknee'],
                ['state_id' => 11, 'city' => 'Pavo'],
                ['state_id' => 11, 'city' => 'Brookfield'],
                ['state_id' => 11, 'city' => 'Chula'],
                ['state_id' => 11, 'city' => 'Omega'],
                ['state_id' => 11, 'city' => 'Tifton'],
                ['state_id' => 11, 'city' => 'Ty Ty'],
                ['state_id' => 11, 'city' => 'Lyons'],
                ['state_id' => 11, 'city' => 'Vidalia'],
                ['state_id' => 11, 'city' => 'Hiawassee'],
                ['state_id' => 11, 'city' => 'Young Harris'],
                ['state_id' => 11, 'city' => 'Soperton'],
                ['state_id' => 11, 'city' => 'Hogansville'],
                ['state_id' => 11, 'city' => 'Lagrange'],
                ['state_id' => 11, 'city' => 'West Point'],
                ['state_id' => 11, 'city' => 'Ashburn'],
                ['state_id' => 11, 'city' => 'Rebecca'],
                ['state_id' => 11, 'city' => 'Sycamore'],
                ['state_id' => 11, 'city' => 'Danville'],
                ['state_id' => 11, 'city' => 'Dry Branch'],
                ['state_id' => 11, 'city' => 'Jeffersonville'],
                ['state_id' => 11, 'city' => 'Blairsville'],
                ['state_id' => 11, 'city' => 'Suches'],
                ['state_id' => 11, 'city' => 'The Rock'],
                ['state_id' => 11, 'city' => 'Thomaston'],
                ['state_id' => 11, 'city' => 'Yatesville'],
                ['state_id' => 11, 'city' => 'Chickamauga'],
                ['state_id' => 11, 'city' => 'Flintstone'],
                ['state_id' => 11, 'city' => 'La Fayette'],
                ['state_id' => 11, 'city' => 'Rock Spring'],
                ['state_id' => 11, 'city' => 'Rossville'],
                ['state_id' => 11, 'city' => 'Lookout Mountain'],
                ['state_id' => 11, 'city' => 'Jersey'],
                ['state_id' => 11, 'city' => 'Social Circle'],
                ['state_id' => 11, 'city' => 'Good Hope'],
                ['state_id' => 11, 'city' => 'Monroe'],
                ['state_id' => 11, 'city' => 'Waycross'],
                ['state_id' => 11, 'city' => 'Manor'],
                ['state_id' => 11, 'city' => 'Millwood'],
                ['state_id' => 11, 'city' => 'Waresboro'],
                ['state_id' => 11, 'city' => 'Camak'],
                ['state_id' => 11, 'city' => 'Mesena'],
                ['state_id' => 11, 'city' => 'Norwood'],
                ['state_id' => 11, 'city' => 'Warrenton'],
                ['state_id' => 11, 'city' => 'Jewell'],
                ['state_id' => 11, 'city' => 'Davisboro'],
                ['state_id' => 11, 'city' => 'Harrison'],
                ['state_id' => 11, 'city' => 'Oconee'],
                ['state_id' => 11, 'city' => 'Sandersville'],
                ['state_id' => 11, 'city' => 'Tennille'],
                ['state_id' => 11, 'city' => 'Warthen'],
                ['state_id' => 11, 'city' => 'Jesup'],
                ['state_id' => 11, 'city' => 'Odum'],
                ['state_id' => 11, 'city' => 'Screven'],
                ['state_id' => 11, 'city' => 'Preston'],
                ['state_id' => 11, 'city' => 'Weston'],
                ['state_id' => 11, 'city' => 'Parrott'],
                ['state_id' => 11, 'city' => 'Alamo'],
                ['state_id' => 11, 'city' => 'Glenwood'],
                ['state_id' => 11, 'city' => 'Cleveland'],
                ['state_id' => 11, 'city' => 'Helen'],
                ['state_id' => 11, 'city' => 'Sautee Nacoochee'],
                ['state_id' => 11, 'city' => 'Cohutta'],
                ['state_id' => 11, 'city' => 'Dalton'],
                ['state_id' => 11, 'city' => 'Rocky Face'],
                ['state_id' => 11, 'city' => 'Tunnel Hill'],
                ['state_id' => 11, 'city' => 'Varnell'],
                ['state_id' => 11, 'city' => 'Abbeville'],
                ['state_id' => 11, 'city' => 'Pineview'],
                ['state_id' => 11, 'city' => 'Pitts'],
                ['state_id' => 11, 'city' => 'Rochelle'],
                ['state_id' => 11, 'city' => 'Seville'],
                ['state_id' => 11, 'city' => 'Rayle'],
                ['state_id' => 11, 'city' => 'Tignall'],
                ['state_id' => 11, 'city' => 'Washington'],
                ['state_id' => 11, 'city' => 'Allentown'],
                ['state_id' => 11, 'city' => 'Gordon'],
                ['state_id' => 11, 'city' => 'Irwinton'],
                ['state_id' => 11, 'city' => 'Mc Intyre'],
                ['state_id' => 11, 'city' => 'Toomsboro'],
                ['state_id' => 11, 'city' => 'Oakfield'],
                ['state_id' => 11, 'city' => 'Poulan'],
                ['state_id' => 11, 'city' => 'Sumner'],
                ['state_id' => 11, 'city' => 'Sylvester'],
                ['state_id' => 11, 'city' => 'Warwick']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
