<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State45TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of UT - Utah.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 45, 'city' => 'Beaver'],
                ['state_id' => 45, 'city' => 'Greenville'],
                ['state_id' => 45, 'city' => 'Milford'],
                ['state_id' => 45, 'city' => 'Minersville'],
                ['state_id' => 45, 'city' => 'Bear River City'],
                ['state_id' => 45, 'city' => 'Brigham City'],
                ['state_id' => 45, 'city' => 'Collinston'],
                ['state_id' => 45, 'city' => 'Corinne'],
                ['state_id' => 45, 'city' => 'Deweyville'],
                ['state_id' => 45, 'city' => 'Fielding'],
                ['state_id' => 45, 'city' => 'Garland'],
                ['state_id' => 45, 'city' => 'Grouse Creek'],
                ['state_id' => 45, 'city' => 'Honeyville'],
                ['state_id' => 45, 'city' => 'Howell'],
                ['state_id' => 45, 'city' => 'Mantua'],
                ['state_id' => 45, 'city' => 'Park Valley'],
                ['state_id' => 45, 'city' => 'Plymouth'],
                ['state_id' => 45, 'city' => 'Portage'],
                ['state_id' => 45, 'city' => 'Riverside'],
                ['state_id' => 45, 'city' => 'Snowville'],
                ['state_id' => 45, 'city' => 'Tremonton'],
                ['state_id' => 45, 'city' => 'Willard'],
                ['state_id' => 45, 'city' => 'Cache Junction'],
                ['state_id' => 45, 'city' => 'Clarkston'],
                ['state_id' => 45, 'city' => 'Cornish'],
                ['state_id' => 45, 'city' => 'Hyde Park'],
                ['state_id' => 45, 'city' => 'Hyrum'],
                ['state_id' => 45, 'city' => 'Lewiston'],
                ['state_id' => 45, 'city' => 'Logan'],
                ['state_id' => 45, 'city' => 'Mendon'],
                ['state_id' => 45, 'city' => 'Millville'],
                ['state_id' => 45, 'city' => 'Newton'],
                ['state_id' => 45, 'city' => 'Paradise'],
                ['state_id' => 45, 'city' => 'Providence'],
                ['state_id' => 45, 'city' => 'Richmond'],
                ['state_id' => 45, 'city' => 'Smithfield'],
                ['state_id' => 45, 'city' => 'Trenton'],
                ['state_id' => 45, 'city' => 'Wellsville'],
                ['state_id' => 45, 'city' => 'Price'],
                ['state_id' => 45, 'city' => 'East Carbon'],
                ['state_id' => 45, 'city' => 'Helper'],
                ['state_id' => 45, 'city' => 'Kenilworth'],
                ['state_id' => 45, 'city' => 'Sunnyside'],
                ['state_id' => 45, 'city' => 'Wellington'],
                ['state_id' => 45, 'city' => 'Dutch John'],
                ['state_id' => 45, 'city' => 'Manila'],
                ['state_id' => 45, 'city' => 'Bountiful'],
                ['state_id' => 45, 'city' => 'Centerville'],
                ['state_id' => 45, 'city' => 'Clearfield'],
                ['state_id' => 45, 'city' => 'Farmington'],
                ['state_id' => 45, 'city' => 'Kaysville'],
                ['state_id' => 45, 'city' => 'Layton'],
                ['state_id' => 45, 'city' => 'North Salt Lake'],
                ['state_id' => 45, 'city' => 'Hill Afb'],
                ['state_id' => 45, 'city' => 'Syracuse'],
                ['state_id' => 45, 'city' => 'Woods Cross'],
                ['state_id' => 45, 'city' => 'Altamont'],
                ['state_id' => 45, 'city' => 'Altonah'],
                ['state_id' => 45, 'city' => 'Bluebell'],
                ['state_id' => 45, 'city' => 'Duchesne'],
                ['state_id' => 45, 'city' => 'Fruitland'],
                ['state_id' => 45, 'city' => 'Hanna'],
                ['state_id' => 45, 'city' => 'Mountain Home'],
                ['state_id' => 45, 'city' => 'Myton'],
                ['state_id' => 45, 'city' => 'Neola'],
                ['state_id' => 45, 'city' => 'Roosevelt'],
                ['state_id' => 45, 'city' => 'Tabiona'],
                ['state_id' => 45, 'city' => 'Talmage'],
                ['state_id' => 45, 'city' => 'Castle Dale'],
                ['state_id' => 45, 'city' => 'Clawson'],
                ['state_id' => 45, 'city' => 'Cleveland'],
                ['state_id' => 45, 'city' => 'Elmo'],
                ['state_id' => 45, 'city' => 'Emery'],
                ['state_id' => 45, 'city' => 'Ferron'],
                ['state_id' => 45, 'city' => 'Green River'],
                ['state_id' => 45, 'city' => 'Huntington'],
                ['state_id' => 45, 'city' => 'Orangeville'],
                ['state_id' => 45, 'city' => 'Antimony'],
                ['state_id' => 45, 'city' => 'Boulder'],
                ['state_id' => 45, 'city' => 'Cannonville'],
                ['state_id' => 45, 'city' => 'Escalante'],
                ['state_id' => 45, 'city' => 'Hatch'],
                ['state_id' => 45, 'city' => 'Henrieville'],
                ['state_id' => 45, 'city' => 'Panguitch'],
                ['state_id' => 45, 'city' => 'Bryce'],
                ['state_id' => 45, 'city' => 'Tropic'],
                ['state_id' => 45, 'city' => 'Cisco'],
                ['state_id' => 45, 'city' => 'Moab'],
                ['state_id' => 45, 'city' => 'Thompson'],
                ['state_id' => 45, 'city' => 'Beryl'],
                ['state_id' => 45, 'city' => 'Brian Head'],
                ['state_id' => 45, 'city' => 'Cedar City'],
                ['state_id' => 45, 'city' => 'Kanarraville'],
                ['state_id' => 45, 'city' => 'Modena'],
                ['state_id' => 45, 'city' => 'Newcastle'],
                ['state_id' => 45, 'city' => 'Paragonah'],
                ['state_id' => 45, 'city' => 'Parowan'],
                ['state_id' => 45, 'city' => 'Summit'],
                ['state_id' => 45, 'city' => 'Eureka'],
                ['state_id' => 45, 'city' => 'Levan'],
                ['state_id' => 45, 'city' => 'Mona'],
                ['state_id' => 45, 'city' => 'Nephi'],
                ['state_id' => 45, 'city' => 'Alton'],
                ['state_id' => 45, 'city' => 'Glendale'],
                ['state_id' => 45, 'city' => 'Kanab'],
                ['state_id' => 45, 'city' => 'Mount Carmel'],
                ['state_id' => 45, 'city' => 'Orderville'],
                ['state_id' => 45, 'city' => 'Duck Creek Village'],
                ['state_id' => 45, 'city' => 'Delta'],
                ['state_id' => 45, 'city' => 'Fillmore'],
                ['state_id' => 45, 'city' => 'Hinckley'],
                ['state_id' => 45, 'city' => 'Holden'],
                ['state_id' => 45, 'city' => 'Kanosh'],
                ['state_id' => 45, 'city' => 'Leamington'],
                ['state_id' => 45, 'city' => 'Lynndyl'],
                ['state_id' => 45, 'city' => 'Meadow'],
                ['state_id' => 45, 'city' => 'Oak City'],
                ['state_id' => 45, 'city' => 'Scipio'],
                ['state_id' => 45, 'city' => 'Garrison'],
                ['state_id' => 45, 'city' => 'Croydon'],
                ['state_id' => 45, 'city' => 'Morgan'],
                ['state_id' => 45, 'city' => 'Circleville'],
                ['state_id' => 45, 'city' => 'Greenwich'],
                ['state_id' => 45, 'city' => 'Junction'],
                ['state_id' => 45, 'city' => 'Kingston'],
                ['state_id' => 45, 'city' => 'Marysvale'],
                ['state_id' => 45, 'city' => 'Garden City'],
                ['state_id' => 45, 'city' => 'Laketown'],
                ['state_id' => 45, 'city' => 'Randolph'],
                ['state_id' => 45, 'city' => 'Woodruff'],
                ['state_id' => 45, 'city' => 'Bingham Canyon'],
                ['state_id' => 45, 'city' => 'South Jordan'],
                ['state_id' => 45, 'city' => 'Draper'],
                ['state_id' => 45, 'city' => 'Magna'],
                ['state_id' => 45, 'city' => 'Midvale'],
                ['state_id' => 45, 'city' => 'Riverton'],
                ['state_id' => 45, 'city' => 'Sandy'],
                ['state_id' => 45, 'city' => 'West Jordan'],
                ['state_id' => 45, 'city' => 'Herriman'],
                ['state_id' => 45, 'city' => 'Salt Lake City'],
                ['state_id' => 45, 'city' => 'West Valley City'],
                ['state_id' => 45, 'city' => 'Aneth'],
                ['state_id' => 45, 'city' => 'Blanding'],
                ['state_id' => 45, 'city' => 'Bluff'],
                ['state_id' => 45, 'city' => 'La Sal'],
                ['state_id' => 45, 'city' => 'Mexican Hat'],
                ['state_id' => 45, 'city' => 'Lake Powell'],
                ['state_id' => 45, 'city' => 'Montezuma Creek'],
                ['state_id' => 45, 'city' => 'Monticello'],
                ['state_id' => 45, 'city' => 'Monument Valley'],
                ['state_id' => 45, 'city' => 'Axtell'],
                ['state_id' => 45, 'city' => 'Centerfield'],
                ['state_id' => 45, 'city' => 'Chester'],
                ['state_id' => 45, 'city' => 'Ephraim'],
                ['state_id' => 45, 'city' => 'Fairview'],
                ['state_id' => 45, 'city' => 'Fayette'],
                ['state_id' => 45, 'city' => 'Fountain Green'],
                ['state_id' => 45, 'city' => 'Gunnison'],
                ['state_id' => 45, 'city' => 'Manti'],
                ['state_id' => 45, 'city' => 'Mayfield'],
                ['state_id' => 45, 'city' => 'Moroni'],
                ['state_id' => 45, 'city' => 'Mount Pleasant'],
                ['state_id' => 45, 'city' => 'Spring City'],
                ['state_id' => 45, 'city' => 'Sterling'],
                ['state_id' => 45, 'city' => 'Wales'],
                ['state_id' => 45, 'city' => 'Aurora'],
                ['state_id' => 45, 'city' => 'Redmond'],
                ['state_id' => 45, 'city' => 'Salina'],
                ['state_id' => 45, 'city' => 'Sigurd'],
                ['state_id' => 45, 'city' => 'Richfield'],
                ['state_id' => 45, 'city' => 'Annabella'],
                ['state_id' => 45, 'city' => 'Elsinore'],
                ['state_id' => 45, 'city' => 'Glenwood'],
                ['state_id' => 45, 'city' => 'Joseph'],
                ['state_id' => 45, 'city' => 'Koosharem'],
                ['state_id' => 45, 'city' => 'Monroe'],
                ['state_id' => 45, 'city' => 'Sevier'],
                ['state_id' => 45, 'city' => 'Coalville'],
                ['state_id' => 45, 'city' => 'Echo'],
                ['state_id' => 45, 'city' => 'Henefer'],
                ['state_id' => 45, 'city' => 'Kamas'],
                ['state_id' => 45, 'city' => 'Oakley'],
                ['state_id' => 45, 'city' => 'Park City'],
                ['state_id' => 45, 'city' => 'Peoa'],
                ['state_id' => 45, 'city' => 'Dugway'],
                ['state_id' => 45, 'city' => 'Grantsville'],
                ['state_id' => 45, 'city' => 'Ibapah'],
                ['state_id' => 45, 'city' => 'Rush Valley'],
                ['state_id' => 45, 'city' => 'Stockton'],
                ['state_id' => 45, 'city' => 'Tooele'],
                ['state_id' => 45, 'city' => 'Vernon'],
                ['state_id' => 45, 'city' => 'Wendover'],
                ['state_id' => 45, 'city' => 'Bonanza'],
                ['state_id' => 45, 'city' => 'Fort Duchesne'],
                ['state_id' => 45, 'city' => 'Jensen'],
                ['state_id' => 45, 'city' => 'Lapoint'],
                ['state_id' => 45, 'city' => 'Randlett'],
                ['state_id' => 45, 'city' => 'Tridell'],
                ['state_id' => 45, 'city' => 'Vernal'],
                ['state_id' => 45, 'city' => 'Whiterocks'],
                ['state_id' => 45, 'city' => 'American Fork'],
                ['state_id' => 45, 'city' => 'Alpine'],
                ['state_id' => 45, 'city' => 'Eagle Mountain'],
                ['state_id' => 45, 'city' => 'Cedar Valley'],
                ['state_id' => 45, 'city' => 'Lindon'],
                ['state_id' => 45, 'city' => 'Lehi'],
                ['state_id' => 45, 'city' => 'Saratoga Springs'],
                ['state_id' => 45, 'city' => 'Orem'],
                ['state_id' => 45, 'city' => 'Pleasant Grove'],
                ['state_id' => 45, 'city' => 'Provo'],
                ['state_id' => 45, 'city' => 'Elberta'],
                ['state_id' => 45, 'city' => 'Goshen'],
                ['state_id' => 45, 'city' => 'Payson'],
                ['state_id' => 45, 'city' => 'Salem'],
                ['state_id' => 45, 'city' => 'Santaquin'],
                ['state_id' => 45, 'city' => 'Spanish Fork'],
                ['state_id' => 45, 'city' => 'Springville'],
                ['state_id' => 45, 'city' => 'Mapleton'],
                ['state_id' => 45, 'city' => 'Heber City'],
                ['state_id' => 45, 'city' => 'Midway'],
                ['state_id' => 45, 'city' => 'Wallsburg'],
                ['state_id' => 45, 'city' => 'Central'],
                ['state_id' => 45, 'city' => 'Enterprise'],
                ['state_id' => 45, 'city' => 'Gunlock'],
                ['state_id' => 45, 'city' => 'Hurricane'],
                ['state_id' => 45, 'city' => 'Ivins'],
                ['state_id' => 45, 'city' => 'La Verkin'],
                ['state_id' => 45, 'city' => 'Leeds'],
                ['state_id' => 45, 'city' => 'New Harmony'],
                ['state_id' => 45, 'city' => 'Rockville'],
                ['state_id' => 45, 'city' => 'Santa Clara'],
                ['state_id' => 45, 'city' => 'Springdale'],
                ['state_id' => 45, 'city' => 'Saint George'],
                ['state_id' => 45, 'city' => 'Toquerville'],
                ['state_id' => 45, 'city' => 'Virgin'],
                ['state_id' => 45, 'city' => 'Washington'],
                ['state_id' => 45, 'city' => 'Pine Valley'],
                ['state_id' => 45, 'city' => 'Veyo'],
                ['state_id' => 45, 'city' => 'Dammeron Valley'],
                ['state_id' => 45, 'city' => 'Hildale'],
                ['state_id' => 45, 'city' => 'Bicknell'],
                ['state_id' => 45, 'city' => 'Hanksville'],
                ['state_id' => 45, 'city' => 'Loa'],
                ['state_id' => 45, 'city' => 'Lyman'],
                ['state_id' => 45, 'city' => 'Teasdale'],
                ['state_id' => 45, 'city' => 'Torrey'],
                ['state_id' => 45, 'city' => 'Roy'],
                ['state_id' => 45, 'city' => 'Ogden'],
                ['state_id' => 45, 'city' => 'Eden'],
                ['state_id' => 45, 'city' => 'Hooper'],
                ['state_id' => 45, 'city' => 'Huntsville', 'state_id' => 45]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
