<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State13TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of ID - Idaho.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 13, 'city' => 'Eagle'],
                ['state_id' => 13, 'city' => 'Kuna'],
                ['state_id' => 13, 'city' => 'Meridian'],
                ['state_id' => 13, 'city' => 'Star'],
                ['state_id' => 13, 'city' => 'Boise'],
                ['state_id' => 13, 'city' => 'Garden City'],
                ['state_id' => 13, 'city' => 'Council'],
                ['state_id' => 13, 'city' => 'Indian Valley'],
                ['state_id' => 13, 'city' => 'Mesa'],
                ['state_id' => 13, 'city' => 'New Meadows'],
                ['state_id' => 13, 'city' => 'Pocatello'],
                ['state_id' => 13, 'city' => 'Arimo'],
                ['state_id' => 13, 'city' => 'Downey'],
                ['state_id' => 13, 'city' => 'Inkom'],
                ['state_id' => 13, 'city' => 'Lava Hot Springs'],
                ['state_id' => 13, 'city' => 'McCammon'],
                ['state_id' => 13, 'city' => 'Swanlake'],
                ['state_id' => 13, 'city' => 'Bern'],
                ['state_id' => 13, 'city' => 'Bloomington'],
                ['state_id' => 13, 'city' => 'Dingle'],
                ['state_id' => 13, 'city' => 'Geneva'],
                ['state_id' => 13, 'city' => 'Georgetown'],
                ['state_id' => 13, 'city' => 'Montpelier'],
                ['state_id' => 13, 'city' => 'Paris'],
                ['state_id' => 13, 'city' => 'Saint Charles'],
                ['state_id' => 13, 'city' => 'Fish Haven'],
                ['state_id' => 13, 'city' => 'Desmet'],
                ['state_id' => 13, 'city' => 'Fernwood'],
                ['state_id' => 13, 'city' => 'Plummer'],
                ['state_id' => 13, 'city' => 'Saint Maries'],
                ['state_id' => 13, 'city' => 'Santa'],
                ['state_id' => 13, 'city' => 'Tensed'],
                ['state_id' => 13, 'city' => 'Fort Hall'],
                ['state_id' => 13, 'city' => 'Aberdeen'],
                ['state_id' => 13, 'city' => 'Atomic City'],
                ['state_id' => 13, 'city' => 'Basalt'],
                ['state_id' => 13, 'city' => 'Blackfoot'],
                ['state_id' => 13, 'city' => 'Firth'],
                ['state_id' => 13, 'city' => 'Moreland'],
                ['state_id' => 13, 'city' => 'Pingree'],
                ['state_id' => 13, 'city' => 'Shelley'],
                ['state_id' => 13, 'city' => 'Springfield'],
                ['state_id' => 13, 'city' => 'Bellevue'],
                ['state_id' => 13, 'city' => 'Carey'],
                ['state_id' => 13, 'city' => 'Hailey'],
                ['state_id' => 13, 'city' => 'Ketchum'],
                ['state_id' => 13, 'city' => 'Picabo'],
                ['state_id' => 13, 'city' => 'Sun Valley'],
                ['state_id' => 13, 'city' => 'Banks'],
                ['state_id' => 13, 'city' => 'Garden Valley'],
                ['state_id' => 13, 'city' => 'Horseshoe Bend'],
                ['state_id' => 13, 'city' => 'Idaho City'],
                ['state_id' => 13, 'city' => 'Lowman'],
                ['state_id' => 13, 'city' => 'Placerville'],
                ['state_id' => 13, 'city' => 'Blanchard'],
                ['state_id' => 13, 'city' => 'Careywood'],
                ['state_id' => 13, 'city' => 'Clark Fork'],
                ['state_id' => 13, 'city' => 'Cocolalla'],
                ['state_id' => 13, 'city' => 'Coolin'],
                ['state_id' => 13, 'city' => 'Oldtown'],
                ['state_id' => 13, 'city' => 'Dover'],
                ['state_id' => 13, 'city' => 'Hope'],
                ['state_id' => 13, 'city' => 'Kootenai'],
                ['state_id' => 13, 'city' => 'Laclede'],
                ['state_id' => 13, 'city' => 'Nordman'],
                ['state_id' => 13, 'city' => 'Ponderay'],
                ['state_id' => 13, 'city' => 'Priest River'],
                ['state_id' => 13, 'city' => 'Sagle'],
                ['state_id' => 13, 'city' => 'Sandpoint'],
                ['state_id' => 13, 'city' => 'Colburn'],
                ['state_id' => 13, 'city' => 'Idaho Falls'],
                ['state_id' => 13, 'city' => 'Iona'],
                ['state_id' => 13, 'city' => 'Irwin'],
                ['state_id' => 13, 'city' => 'Swan Valley'],
                ['state_id' => 13, 'city' => 'Ucon'],
                ['state_id' => 13, 'city' => 'Bonners Ferry'],
                ['state_id' => 13, 'city' => 'Eastport'],
                ['state_id' => 13, 'city' => 'Moyie Springs'],
                ['state_id' => 13, 'city' => 'Naples'],
                ['state_id' => 13, 'city' => 'Porthill'],
                ['state_id' => 13, 'city' => 'Arco'],
                ['state_id' => 13, 'city' => 'Howe'],
                ['state_id' => 13, 'city' => 'Moore'],
                ['state_id' => 13, 'city' => 'Corral'],
                ['state_id' => 13, 'city' => 'Fairfield'],
                ['state_id' => 13, 'city' => 'Hill City'],
                ['state_id' => 13, 'city' => 'Caldwell'],
                ['state_id' => 13, 'city' => 'Greenleaf'],
                ['state_id' => 13, 'city' => 'Huston'],
                ['state_id' => 13, 'city' => 'Melba'],
                ['state_id' => 13, 'city' => 'Middleton'],
                ['state_id' => 13, 'city' => 'Nampa'],
                ['state_id' => 13, 'city' => 'Notus'],
                ['state_id' => 13, 'city' => 'Parma'],
                ['state_id' => 13, 'city' => 'Wilder'],
                ['state_id' => 13, 'city' => 'Bancroft'],
                ['state_id' => 13, 'city' => 'Conda'],
                ['state_id' => 13, 'city' => 'Grace'],
                ['state_id' => 13, 'city' => 'Soda Springs'],
                ['state_id' => 13, 'city' => 'Wayan'],
                ['state_id' => 13, 'city' => 'Albion'],
                ['state_id' => 13, 'city' => 'Almo'],
                ['state_id' => 13, 'city' => 'Burley'],
                ['state_id' => 13, 'city' => 'Declo'],
                ['state_id' => 13, 'city' => 'Malta'],
                ['state_id' => 13, 'city' => 'Oakley'],
                ['state_id' => 13, 'city' => 'Dubois'],
                ['state_id' => 13, 'city' => 'Spencer'],
                ['state_id' => 13, 'city' => 'Ahsahka'],
                ['state_id' => 13, 'city' => 'Lenore'],
                ['state_id' => 13, 'city' => 'Orofino'],
                ['state_id' => 13, 'city' => 'Pierce'],
                ['state_id' => 13, 'city' => 'Weippe'],
                ['state_id' => 13, 'city' => 'Elk River'],
                ['state_id' => 13, 'city' => 'Challis'],
                ['state_id' => 13, 'city' => 'Clayton'],
                ['state_id' => 13, 'city' => 'Ellis'],
                ['state_id' => 13, 'city' => 'Mackay'],
                ['state_id' => 13, 'city' => 'Stanley'],
                ['state_id' => 13, 'city' => 'Atlanta'],
                ['state_id' => 13, 'city' => 'Glenns Ferry'],
                ['state_id' => 13, 'city' => 'Hammett'],
                ['state_id' => 13, 'city' => 'King Hill'],
                ['state_id' => 13, 'city' => 'Mountain Home'],
                ['state_id' => 13, 'city' => 'Mountain Home Afb'],
                ['state_id' => 13, 'city' => 'Clifton'],
                ['state_id' => 13, 'city' => 'Dayton'],
                ['state_id' => 13, 'city' => 'Franklin'],
                ['state_id' => 13, 'city' => 'Preston'],
                ['state_id' => 13, 'city' => 'Thatcher'],
                ['state_id' => 13, 'city' => 'Weston'],
                ['state_id' => 13, 'city' => 'Ashton'],
                ['state_id' => 13, 'city' => 'Chester'],
                ['state_id' => 13, 'city' => 'Island Park'],
                ['state_id' => 13, 'city' => 'Macks Inn'],
                ['state_id' => 13, 'city' => 'Newdale'],
                ['state_id' => 13, 'city' => 'Parker'],
                ['state_id' => 13, 'city' => 'Saint Anthony'],
                ['state_id' => 13, 'city' => 'Teton'],
                ['state_id' => 13, 'city' => 'Emmett'],
                ['state_id' => 13, 'city' => 'Letha'],
                ['state_id' => 13, 'city' => 'Ola'],
                ['state_id' => 13, 'city' => 'Sweet'],
                ['state_id' => 13, 'city' => 'Bliss'],
                ['state_id' => 13, 'city' => 'Gooding'],
                ['state_id' => 13, 'city' => 'Hagerman'],
                ['state_id' => 13, 'city' => 'Wendell'],
                ['state_id' => 13, 'city' => 'Cottonwood'],
                ['state_id' => 13, 'city' => 'Elk City'],
                ['state_id' => 13, 'city' => 'Ferdinand'],
                ['state_id' => 13, 'city' => 'Grangeville'],
                ['state_id' => 13, 'city' => 'Fenn'],
                ['state_id' => 13, 'city' => 'Greencreek'],
                ['state_id' => 13, 'city' => 'Kooskia'],
                ['state_id' => 13, 'city' => 'Lucile'],
                ['state_id' => 13, 'city' => 'Pollock'],
                ['state_id' => 13, 'city' => 'Riggins'],
                ['state_id' => 13, 'city' => 'Stites'],
                ['state_id' => 13, 'city' => 'White Bird'],
                ['state_id' => 13, 'city' => 'Warren'],
                ['state_id' => 13, 'city' => 'Hamer'],
                ['state_id' => 13, 'city' => 'Lewisville'],
                ['state_id' => 13, 'city' => 'Menan'],
                ['state_id' => 13, 'city' => 'Monteview'],
                ['state_id' => 13, 'city' => 'Rigby'],
                ['state_id' => 13, 'city' => 'Ririe'],
                ['state_id' => 13, 'city' => 'Roberts'],
                ['state_id' => 13, 'city' => 'Terreton'],
                ['state_id' => 13, 'city' => 'Eden'],
                ['state_id' => 13, 'city' => 'Hazelton'],
                ['state_id' => 13, 'city' => 'Jerome'],
                ['state_id' => 13, 'city' => 'Athol'],
                ['state_id' => 13, 'city' => 'Bayview'],
                ['state_id' => 13, 'city' => 'Cataldo'],
                ['state_id' => 13, 'city' => "Coeur d'Alene"],
                ['state_id' => 13, 'city' => 'Harrison'],
                ['state_id' => 13, 'city' => 'Hayden'],
                ['state_id' => 13, 'city' => 'Medimont'],
                ['state_id' => 13, 'city' => 'Post Falls'],
                ['state_id' => 13, 'city' => 'Rathdrum'],
                ['state_id' => 13, 'city' => 'Spirit Lake'],
                ['state_id' => 13, 'city' => 'Worley'],
                ['state_id' => 13, 'city' => 'Juliaetta'],
                ['state_id' => 13, 'city' => 'Kendrick'],
                ['state_id' => 13, 'city' => 'Bovill'],
                ['state_id' => 13, 'city' => 'Deary'],
                ['state_id' => 13, 'city' => 'Genesee'],
                ['state_id' => 13, 'city' => 'Harvard'],
                ['state_id' => 13, 'city' => 'Moscow'],
                ['state_id' => 13, 'city' => 'Potlatch'],
                ['state_id' => 13, 'city' => 'Princeton'],
                ['state_id' => 13, 'city' => 'Troy'],
                ['state_id' => 13, 'city' => 'Viola'],
                ['state_id' => 13, 'city' => 'Cobalt'],
                ['state_id' => 13, 'city' => 'May'],
                ['state_id' => 13, 'city' => 'Carmen'],
                ['state_id' => 13, 'city' => 'Gibbonsville'],
                ['state_id' => 13, 'city' => 'Leadore'],
                ['state_id' => 13, 'city' => 'Lemhi'],
                ['state_id' => 13, 'city' => 'North Fork'],
                ['state_id' => 13, 'city' => 'Salmon'],
                ['state_id' => 13, 'city' => 'Tendoy'],
                ['state_id' => 13, 'city' => 'Shoup'],
                ['state_id' => 13, 'city' => 'Craigmont'],
                ['state_id' => 13, 'city' => 'Kamiah'],
                ['state_id' => 13, 'city' => 'Nezperce'],
                ['state_id' => 13, 'city' => 'Reubens'],
                ['state_id' => 13, 'city' => 'Winchester'],
                ['state_id' => 13, 'city' => 'Dietrich'],
                ['state_id' => 13, 'city' => 'Richfield'],
                ['state_id' => 13, 'city' => 'Shoshone'],
                ['state_id' => 13, 'city' => 'Rexburg'],
                ['state_id' => 13, 'city' => 'Sugar City'],
                ['state_id' => 13, 'city' => 'Heyburn'],
                ['state_id' => 13, 'city' => 'Minidoka'],
                ['state_id' => 13, 'city' => 'Paul'],
                ['state_id' => 13, 'city' => 'Rupert'],
                ['state_id' => 13, 'city' => 'Lewiston'],
                ['state_id' => 13, 'city' => 'Culdesac'],
                ['state_id' => 13, 'city' => 'Lapwai'],
                ['state_id' => 13, 'city' => 'Peck'],
                ['state_id' => 13, 'city' => 'Holbrook'],
                ['state_id' => 13, 'city' => 'Malad City'],
                ['state_id' => 13, 'city' => 'Bruneau'],
                ['state_id' => 13, 'city' => 'Grand View'],
                ['state_id' => 13, 'city' => 'Homedale'],
                ['state_id' => 13, 'city' => 'Marsing'],
                ['state_id' => 13, 'city' => 'Murphy'],
                ['state_id' => 13, 'city' => 'Fruitland'],
                ['state_id' => 13, 'city' => 'New Plymouth'],
                ['state_id' => 13, 'city' => 'Payette'],
                ['state_id' => 13, 'city' => 'American Falls'],
                ['state_id' => 13, 'city' => 'Arbon'],
                ['state_id' => 13, 'city' => 'Rockland'],
                ['state_id' => 13, 'city' => 'Avery'],
                ['state_id' => 13, 'city' => 'Calder'],
                ['state_id' => 13, 'city' => 'Clarkia'],
                ['state_id' => 13, 'city' => 'Kellogg'],
                ['state_id' => 13, 'city' => 'Kingston'],
                ['state_id' => 13, 'city' => 'Mullan'],
                ['state_id' => 13, 'city' => 'Osburn'],
                ['state_id' => 13, 'city' => 'Pinehurst'],
                ['state_id' => 13, 'city' => 'Silverton'],
                ['state_id' => 13, 'city' => 'Smelterville'],
                ['state_id' => 13, 'city' => 'Wallace'],
                ['state_id' => 13, 'city' => 'Murray'],
                ['state_id' => 13, 'city' => 'Driggs'],
                ['state_id' => 13, 'city' => 'Felt'],
                ['state_id' => 13, 'city' => 'Tetonia'],
                ['state_id' => 13, 'city' => 'Victor'],
                ['state_id' => 13, 'city' => 'Twin Falls'],
                ['state_id' => 13, 'city' => 'Rogerson'],
                ['state_id' => 13, 'city' => 'Buhl'],
                ['state_id' => 13, 'city' => 'Castleford'],
                ['state_id' => 13, 'city' => 'Filer'],
                ['state_id' => 13, 'city' => 'Hansen'],
                ['state_id' => 13, 'city' => 'Kimberly'],
                ['state_id' => 13, 'city' => 'Murtaugh'],
                ['state_id' => 13, 'city' => 'Cascade'],
                ['state_id' => 13, 'city' => 'Donnelly'],
                ['state_id' => 13, 'city' => 'Lake Fork'],
                ['state_id' => 13, 'city' => 'McCall'],
                ['state_id' => 13, 'city' => 'Yellow Pine'],
                ['state_id' => 13, 'city' => 'Cambridge'],
                ['state_id' => 13, 'city' => 'Midvale'],
                ['state_id' => 13, 'city' => 'Weiser']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
