<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State37TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of OK - Oklahoma.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 37, 'city' => 'Proctor'],
                ['state_id' => 37, 'city' => 'Bunch'],
                ['state_id' => 37, 'city' => 'Stilwell'],
                ['state_id' => 37, 'city' => 'Watts'],
                ['state_id' => 37, 'city' => 'Westville'],
                ['state_id' => 37, 'city' => 'Aline'],
                ['state_id' => 37, 'city' => 'Amorita'],
                ['state_id' => 37, 'city' => 'Burlington'],
                ['state_id' => 37, 'city' => 'Carmen'],
                ['state_id' => 37, 'city' => 'Cherokee'],
                ['state_id' => 37, 'city' => 'Goltry'],
                ['state_id' => 37, 'city' => 'Helena'],
                ['state_id' => 37, 'city' => 'Jet'],
                ['state_id' => 37, 'city' => 'Atoka'],
                ['state_id' => 37, 'city' => 'Caney'],
                ['state_id' => 37, 'city' => 'Daisy'],
                ['state_id' => 37, 'city' => 'Lane'],
                ['state_id' => 37, 'city' => 'Stringtown'],
                ['state_id' => 37, 'city' => 'Gate'],
                ['state_id' => 37, 'city' => 'Balko'],
                ['state_id' => 37, 'city' => 'Beaver'],
                ['state_id' => 37, 'city' => 'Forgan'],
                ['state_id' => 37, 'city' => 'Turpin'],
                ['state_id' => 37, 'city' => 'Carter'],
                ['state_id' => 37, 'city' => 'Elk City'],
                ['state_id' => 37, 'city' => 'Erick'],
                ['state_id' => 37, 'city' => 'Sayre'],
                ['state_id' => 37, 'city' => 'Texola'],
                ['state_id' => 37, 'city' => 'Geary'],
                ['state_id' => 37, 'city' => 'Greenfield'],
                ['state_id' => 37, 'city' => 'Canton'],
                ['state_id' => 37, 'city' => 'Hitchcock'],
                ['state_id' => 37, 'city' => 'Longdale'],
                ['state_id' => 37, 'city' => 'Okeene'],
                ['state_id' => 37, 'city' => 'Southard'],
                ['state_id' => 37, 'city' => 'Watonga'],
                ['state_id' => 37, 'city' => 'Mead'],
                ['state_id' => 37, 'city' => 'Durant'],
                ['state_id' => 37, 'city' => 'Achille'],
                ['state_id' => 37, 'city' => 'Albany'],
                ['state_id' => 37, 'city' => 'Bennington'],
                ['state_id' => 37, 'city' => 'Bokchito'],
                ['state_id' => 37, 'city' => 'Caddo'],
                ['state_id' => 37, 'city' => 'Calera'],
                ['state_id' => 37, 'city' => 'Cartwright'],
                ['state_id' => 37, 'city' => 'Colbert'],
                ['state_id' => 37, 'city' => 'Hendrix'],
                ['state_id' => 37, 'city' => 'Kemp'],
                ['state_id' => 37, 'city' => 'Kenefic'],
                ['state_id' => 37, 'city' => 'Platter'],
                ['state_id' => 37, 'city' => 'Albert'],
                ['state_id' => 37, 'city' => 'Anadarko'],
                ['state_id' => 37, 'city' => 'Apache'],
                ['state_id' => 37, 'city' => 'Binger'],
                ['state_id' => 37, 'city' => 'Carnegie'],
                ['state_id' => 37, 'city' => 'Cement'],
                ['state_id' => 37, 'city' => 'Cyril'],
                ['state_id' => 37, 'city' => 'Eakly'],
                ['state_id' => 37, 'city' => 'Fort Cobb'],
                ['state_id' => 37, 'city' => 'Gracemont'],
                ['state_id' => 37, 'city' => 'Hinton'],
                ['state_id' => 37, 'city' => 'Hydro'],
                ['state_id' => 37, 'city' => 'Lookeba'],
                ['state_id' => 37, 'city' => 'Calumet'],
                ['state_id' => 37, 'city' => 'Concho'],
                ['state_id' => 37, 'city' => 'El Reno'],
                ['state_id' => 37, 'city' => 'Mustang'],
                ['state_id' => 37, 'city' => 'Piedmont'],
                ['state_id' => 37, 'city' => 'Yukon'],
                ['state_id' => 37, 'city' => 'Union City'],
                ['state_id' => 37, 'city' => 'Ardmore'],
                ['state_id' => 37, 'city' => 'Fox'],
                ['state_id' => 37, 'city' => 'Gene Autry'],
                ['state_id' => 37, 'city' => 'Graham'],
                ['state_id' => 37, 'city' => 'Healdton'],
                ['state_id' => 37, 'city' => 'Lone Grove'],
                ['state_id' => 37, 'city' => 'Springer'],
                ['state_id' => 37, 'city' => 'Wilson'],
                ['state_id' => 37, 'city' => 'Ratliff City'],
                ['state_id' => 37, 'city' => 'Tatums'],
                ['state_id' => 37, 'city' => 'Tussy'],
                ['state_id' => 37, 'city' => 'Cookson'],
                ['state_id' => 37, 'city' => 'Hulbert'],
                ['state_id' => 37, 'city' => 'Moodys'],
                ['state_id' => 37, 'city' => 'Park Hill'],
                ['state_id' => 37, 'city' => 'Peggs'],
                ['state_id' => 37, 'city' => 'Tahlequah'],
                ['state_id' => 37, 'city' => 'Welling'],
                ['state_id' => 37, 'city' => 'Boswell'],
                ['state_id' => 37, 'city' => 'Fort Towson'],
                ['state_id' => 37, 'city' => 'Grant'],
                ['state_id' => 37, 'city' => 'Hugo'],
                ['state_id' => 37, 'city' => 'Sawyer'],
                ['state_id' => 37, 'city' => 'Soper'],
                ['state_id' => 37, 'city' => 'Spencerville'],
                ['state_id' => 37, 'city' => 'Swink'],
                ['state_id' => 37, 'city' => 'Boise City'],
                ['state_id' => 37, 'city' => 'Felt'],
                ['state_id' => 37, 'city' => 'Kenton'],
                ['state_id' => 37, 'city' => 'Keyes'],
                ['state_id' => 37, 'city' => 'Norman'],
                ['state_id' => 37, 'city' => 'Lexington'],
                ['state_id' => 37, 'city' => 'Noble'],
                ['state_id' => 37, 'city' => 'Oklahoma City'],
                ['state_id' => 37, 'city' => 'Centrahoma'],
                ['state_id' => 37, 'city' => 'Clarita'],
                ['state_id' => 37, 'city' => 'Coalgate'],
                ['state_id' => 37, 'city' => 'Lehigh'],
                ['state_id' => 37, 'city' => 'Tupelo'],
                ['state_id' => 37, 'city' => 'Lawton'],
                ['state_id' => 37, 'city' => 'Fort Sill'],
                ['state_id' => 37, 'city' => 'Cache'],
                ['state_id' => 37, 'city' => 'Chattanooga'],
                ['state_id' => 37, 'city' => 'Elgin'],
                ['state_id' => 37, 'city' => 'Faxon'],
                ['state_id' => 37, 'city' => 'Fletcher'],
                ['state_id' => 37, 'city' => 'Geronimo'],
                ['state_id' => 37, 'city' => 'Indiahoma'],
                ['state_id' => 37, 'city' => 'Medicine Park'],
                ['state_id' => 37, 'city' => 'Meers'],
                ['state_id' => 37, 'city' => 'Sterling'],
                ['state_id' => 37, 'city' => 'Devol'],
                ['state_id' => 37, 'city' => 'Randlett'],
                ['state_id' => 37, 'city' => 'Temple'],
                ['state_id' => 37, 'city' => 'Walters'],
                ['state_id' => 37, 'city' => 'Vinita'],
                ['state_id' => 37, 'city' => 'Big Cabin'],
                ['state_id' => 37, 'city' => 'Bluejacket'],
                ['state_id' => 37, 'city' => 'Welch'],
                ['state_id' => 37, 'city' => 'Bristow'],
                ['state_id' => 37, 'city' => 'Depew'],
                ['state_id' => 37, 'city' => 'Drumright'],
                ['state_id' => 37, 'city' => 'Kellyville'],
                ['state_id' => 37, 'city' => 'Kiefer'],
                ['state_id' => 37, 'city' => 'Mannford'],
                ['state_id' => 37, 'city' => 'Milfay'],
                ['state_id' => 37, 'city' => 'Mounds'],
                ['state_id' => 37, 'city' => 'Oilton'],
                ['state_id' => 37, 'city' => 'Sapulpa'],
                ['state_id' => 37, 'city' => 'Shamrock'],
                ['state_id' => 37, 'city' => 'Slick'],
                ['state_id' => 37, 'city' => 'Tulsa'],
                ['state_id' => 37, 'city' => 'Weatherford'],
                ['state_id' => 37, 'city' => 'Clinton'],
                ['state_id' => 37, 'city' => 'Arapaho'],
                ['state_id' => 37, 'city' => 'Butler'],
                ['state_id' => 37, 'city' => 'Custer City'],
                ['state_id' => 37, 'city' => 'Thomas'],
                ['state_id' => 37, 'city' => 'Colcord'],
                ['state_id' => 37, 'city' => 'Eucha'],
                ['state_id' => 37, 'city' => 'Grove'],
                ['state_id' => 37, 'city' => 'Jay'],
                ['state_id' => 37, 'city' => 'Kansas'],
                ['state_id' => 37, 'city' => 'Oaks'],
                ['state_id' => 37, 'city' => 'Twin Oaks'],
                ['state_id' => 37, 'city' => 'Fay'],
                ['state_id' => 37, 'city' => 'Leedey'],
                ['state_id' => 37, 'city' => 'Oakwood'],
                ['state_id' => 37, 'city' => 'Putnam'],
                ['state_id' => 37, 'city' => 'Seiling'],
                ['state_id' => 37, 'city' => 'Taloga'],
                ['state_id' => 37, 'city' => 'Camargo'],
                ['state_id' => 37, 'city' => 'Vici'],
                ['state_id' => 37, 'city' => 'Arnett'],
                ['state_id' => 37, 'city' => 'Fargo'],
                ['state_id' => 37, 'city' => 'Gage'],
                ['state_id' => 37, 'city' => 'Shattuck'],
                ['state_id' => 37, 'city' => 'Enid'],
                ['state_id' => 37, 'city' => 'Bison'],
                ['state_id' => 37, 'city' => 'Carrier'],
                ['state_id' => 37, 'city' => 'Covington'],
                ['state_id' => 37, 'city' => 'Douglas'],
                ['state_id' => 37, 'city' => 'Drummond'],
                ['state_id' => 37, 'city' => 'Fairmont'],
                ['state_id' => 37, 'city' => 'Garber'],
                ['state_id' => 37, 'city' => 'Hillsdale'],
                ['state_id' => 37, 'city' => 'Kremlin'],
                ['state_id' => 37, 'city' => 'Lahoma'],
                ['state_id' => 37, 'city' => 'Waukomis'],
                ['state_id' => 37, 'city' => 'Hunter'],
                ['state_id' => 37, 'city' => 'Lindsay'],
                ['state_id' => 37, 'city' => 'Maysville'],
                ['state_id' => 37, 'city' => 'Paoli'],
                ['state_id' => 37, 'city' => 'Pauls Valley'],
                ['state_id' => 37, 'city' => 'Wynnewood'],
                ['state_id' => 37, 'city' => 'Elmore City'],
                ['state_id' => 37, 'city' => 'Hennepin'],
                ['state_id' => 37, 'city' => 'Stratford'],
                ['state_id' => 37, 'city' => 'Alex'],
                ['state_id' => 37, 'city' => 'Amber'],
                ['state_id' => 37, 'city' => 'Bradley'],
                ['state_id' => 37, 'city' => 'Chickasha'],
                ['state_id' => 37, 'city' => 'Minco'],
                ['state_id' => 37, 'city' => 'Ninnekah'],
                ['state_id' => 37, 'city' => 'Pocasset'],
                ['state_id' => 37, 'city' => 'Rush Springs'],
                ['state_id' => 37, 'city' => 'Tuttle'],
                ['state_id' => 37, 'city' => 'Verden'],
                ['state_id' => 37, 'city' => 'Manchester'],
                ['state_id' => 37, 'city' => 'Medford'],
                ['state_id' => 37, 'city' => 'Nash'],
                ['state_id' => 37, 'city' => 'Pond Creek'],
                ['state_id' => 37, 'city' => 'Wakita'],
                ['state_id' => 37, 'city' => 'Deer Creek'],
                ['state_id' => 37, 'city' => 'Lamont'],
                ['state_id' => 37, 'city' => 'Granite'],
                ['state_id' => 37, 'city' => 'Mangum'],
                ['state_id' => 37, 'city' => 'Willow'],
                ['state_id' => 37, 'city' => 'Gould'],
                ['state_id' => 37, 'city' => 'Hollis'],
                ['state_id' => 37, 'city' => 'Vinson'],
                ['state_id' => 37, 'city' => 'Buffalo'],
                ['state_id' => 37, 'city' => 'Laverne'],
                ['state_id' => 37, 'city' => 'May'],
                ['state_id' => 37, 'city' => 'Rosston'],
                ['state_id' => 37, 'city' => 'Hoyt'],
                ['state_id' => 37, 'city' => 'Stigler'],
                ['state_id' => 37, 'city' => 'Whitefield'],
                ['state_id' => 37, 'city' => 'Kinta'],
                ['state_id' => 37, 'city' => 'Keota'],
                ['state_id' => 37, 'city' => 'Lequire'],
                ['state_id' => 37, 'city' => 'Mccurtain'],
                ['state_id' => 37, 'city' => 'Calvin'],
                ['state_id' => 37, 'city' => 'Stuart'],
                ['state_id' => 37, 'city' => 'Atwood'],
                ['state_id' => 37, 'city' => 'Dustin'],
                ['state_id' => 37, 'city' => 'Holdenville'],
                ['state_id' => 37, 'city' => 'Lamar'],
                ['state_id' => 37, 'city' => 'Wetumka'],
                ['state_id' => 37, 'city' => 'Altus'],
                ['state_id' => 37, 'city' => 'Altus Afb'],
                ['state_id' => 37, 'city' => 'Blair'],
                ['state_id' => 37, 'city' => 'Duke'],
                ['state_id' => 37, 'city' => 'Eldorado'],
                ['state_id' => 37, 'city' => 'Elmer'],
                ['state_id' => 37, 'city' => 'Headrick'],
                ['state_id' => 37, 'city' => 'Martha'],
                ['state_id' => 37, 'city' => 'Olustee'],
                ['state_id' => 37, 'city' => 'Ringling'],
                ['state_id' => 37, 'city' => 'Addington'],
                ['state_id' => 37, 'city' => 'Hastings'],
                ['state_id' => 37, 'city' => 'Oscar'],
                ['state_id' => 37, 'city' => 'Ryan'],
                ['state_id' => 37, 'city' => 'Terral'],
                ['state_id' => 37, 'city' => 'Waurika'],
                ['state_id' => 37, 'city' => 'Coleman'],
                ['state_id' => 37, 'city' => 'Mannsville'],
                ['state_id' => 37, 'city' => 'Milburn'],
                ['state_id' => 37, 'city' => 'Ravia'],
                ['state_id' => 37, 'city' => 'Tishomingo'],
                ['state_id' => 37, 'city' => 'Wapanucka'],
                ['state_id' => 37, 'city' => 'Bromide'],
                ['state_id' => 37, 'city' => 'Connerville'],
                ['state_id' => 37, 'city' => 'Mill Creek'],
                ['state_id' => 37, 'city' => 'Ponca City'],
                ['state_id' => 37, 'city' => 'Blackwell'],
                ['state_id' => 37, 'city' => 'Braman'],
                ['state_id' => 37, 'city' => 'Kaw City'],
                ['state_id' => 37, 'city' => 'Nardin'],
                ['state_id' => 37, 'city' => 'Newkirk'],
                ['state_id' => 37, 'city' => 'Tonkawa'],
                ['state_id' => 37, 'city' => 'Cashion'],
                ['state_id' => 37, 'city' => 'Dover'],
                ['state_id' => 37, 'city' => 'Hennessey'],
                ['state_id' => 37, 'city' => 'Kingfisher'],
                ['state_id' => 37, 'city' => 'Loyal'],
                ['state_id' => 37, 'city' => 'Okarche'],
                ['state_id' => 37, 'city' => 'Omega'],
                ['state_id' => 37, 'city' => 'Gotebo'],
                ['state_id' => 37, 'city' => 'Mountain View'],
                ['state_id' => 37, 'city' => 'Mountain Park'],
                ['state_id' => 37, 'city' => 'Roosevelt'],
                ['state_id' => 37, 'city' => 'Snyder'],
                ['state_id' => 37, 'city' => 'Hobart'],
                ['state_id' => 37, 'city' => 'Lone Wolf'],
                ['state_id' => 37, 'city' => 'Gowen'],
                ['state_id' => 37, 'city' => 'Panola'],
                ['state_id' => 37, 'city' => 'Red Oak'],
                ['state_id' => 37, 'city' => 'Wilburton'],
                ['state_id' => 37, 'city' => 'Honobia'],
                ['state_id' => 37, 'city' => 'Talihina'],
                ['state_id' => 37, 'city' => 'Whitesboro'],
                ['state_id' => 37, 'city' => 'Arkoma'],
                ['state_id' => 37, 'city' => 'Pocola'],
                ['state_id' => 37, 'city' => 'Bokoshe'],
                ['state_id' => 37, 'city' => 'Cameron'],
                ['state_id' => 37, 'city' => 'Fanshawe'],
                ['state_id' => 37, 'city' => 'Heavener'],
                ['state_id' => 37, 'city' => 'Hodgen'],
                ['state_id' => 37, 'city' => 'Howe'],
                ['state_id' => 37, 'city' => 'Leflore'],
                ['state_id' => 37, 'city' => 'Monroe'],
                ['state_id' => 37, 'city' => 'Muse'],
                ['state_id' => 37, 'city' => 'Panama'],
                ['state_id' => 37, 'city' => 'Poteau'],
                ['state_id' => 37, 'city' => 'Shady Point'],
                ['state_id' => 37, 'city' => 'Spiro'],
                ['state_id' => 37, 'city' => 'Wister'],
                ['state_id' => 37, 'city' => 'Davenport'],
                ['state_id' => 37, 'city' => 'Stroud'],
                ['state_id' => 37, 'city' => 'Agra'],
                ['state_id' => 37, 'city' => 'Carney'],
                ['state_id' => 37, 'city' => 'Chandler'],
                ['state_id' => 37, 'city' => 'Meeker'],
                ['state_id' => 37, 'city' => 'Prague'],
                ['state_id' => 37, 'city' => 'Sparks'],
                ['state_id' => 37, 'city' => 'Tryon'],
                ['state_id' => 37, 'city' => 'Wellston'],
                ['state_id' => 37, 'city' => 'Coyle'],
                ['state_id' => 37, 'city' => 'Crescent'],
                ['state_id' => 37, 'city' => 'Guthrie'],
                ['state_id' => 37, 'city' => 'Langston'],
                ['state_id' => 37, 'city' => 'Marshall'],
                ['state_id' => 37, 'city' => 'Meridian'],
                ['state_id' => 37, 'city' => 'Mulhall'],
                ['state_id' => 37, 'city' => 'Orlando'],
                ['state_id' => 37, 'city' => 'Burneyville'],
                ['state_id' => 37, 'city' => 'Leon'],
                ['state_id' => 37, 'city' => 'Marietta'],
                ['state_id' => 37, 'city' => 'Overbrook'],
                ['state_id' => 37, 'city' => 'Thackerville'],
                ['state_id' => 37, 'city' => 'Blanchard'],
                ['state_id' => 37, 'city' => 'Dibble'],
                ['state_id' => 37, 'city' => 'Newcastle'],
                ['state_id' => 37, 'city' => 'Purcell'],
                ['state_id' => 37, 'city' => 'Washington'],
                ['state_id' => 37, 'city' => 'Wayne'],
                ['state_id' => 37, 'city' => 'Byars'],
                ['state_id' => 37, 'city' => 'Battiest'],
                ['state_id' => 37, 'city' => 'Bethel'],
                ['state_id' => 37, 'city' => 'Broken Bow'],
                ['state_id' => 37, 'city' => 'Eagletown'],
                ['state_id' => 37, 'city' => 'Garvin'],
                ['state_id' => 37, 'city' => 'Golden'],
                ['state_id' => 37, 'city' => 'Haworth'],
                ['state_id' => 37, 'city' => 'Idabel'],
                ['state_id' => 37, 'city' => 'Millerton'],
                ['state_id' => 37, 'city' => 'Pickens'],
                ['state_id' => 37, 'city' => 'Ringold'],
                ['state_id' => 37, 'city' => 'Rufe'],
                ['state_id' => 37, 'city' => 'Valliant'],
                ['state_id' => 37, 'city' => 'Wright City'],
                ['state_id' => 37, 'city' => 'Smithville'],
                ['state_id' => 37, 'city' => 'Watson'],
                ['state_id' => 37, 'city' => 'Checotah'],
                ['state_id' => 37, 'city' => 'Eufaula'],
                ['state_id' => 37, 'city' => 'Hitchita'],
                ['state_id' => 37, 'city' => 'Rentiesville'],
                ['state_id' => 37, 'city' => 'Stidham'],
                ['state_id' => 37, 'city' => 'Hanna'],
                ['state_id' => 37, 'city' => 'Ames'],
                ['state_id' => 37, 'city' => 'Cleo Springs'],
                ['state_id' => 37, 'city' => 'Fairview'],
                ['state_id' => 37, 'city' => 'Isabella'],
                ['state_id' => 37, 'city' => 'Meno'],
                ['state_id' => 37, 'city' => 'Ringwood'],
                ['state_id' => 37, 'city' => 'Chester'],
                ['state_id' => 37, 'city' => 'Kingston'],
                ['state_id' => 37, 'city' => 'Lebanon'],
                ['state_id' => 37, 'city' => 'Madill'],
                ['state_id' => 37, 'city' => 'Adair'],
                ['state_id' => 37, 'city' => 'Chouteau'],
                ['state_id' => 37, 'city' => 'Disney'],
                ['state_id' => 37, 'city' => 'Ketchum'],
                ['state_id' => 37, 'city' => 'Langley'],
                ['state_id' => 37, 'city' => 'Locust Grove'],
                ['state_id' => 37, 'city' => 'Pryor'],
                ['state_id' => 37, 'city' => 'Rose'],
                ['state_id' => 37, 'city' => 'Salina'],
                ['state_id' => 37, 'city' => 'Spavinaw'],
                ['state_id' => 37, 'city' => 'Strang'],
                ['state_id' => 37, 'city' => 'Davis'],
                ['state_id' => 37, 'city' => 'Dougherty'],
                ['state_id' => 37, 'city' => 'Sulphur'],
                ['state_id' => 37, 'city' => 'Muskogee'],
                ['state_id' => 37, 'city' => 'Boynton'],
                ['state_id' => 37, 'city' => 'Braggs'],
                ['state_id' => 37, 'city' => 'Council Hill'],
                ['state_id' => 37, 'city' => 'Fort Gibson'],
                ['state_id' => 37, 'city' => 'Haskell'],
                ['state_id' => 37, 'city' => 'Oktaha'],
                ['state_id' => 37, 'city' => 'Porum'],
                ['state_id' => 37, 'city' => 'Taft'],
                ['state_id' => 37, 'city' => 'Wainwright'],
                ['state_id' => 37, 'city' => 'Warner'],
                ['state_id' => 37, 'city' => 'Webbers Falls'],
                ['state_id' => 37, 'city' => 'Morrison'],
                ['state_id' => 37, 'city' => 'Perry'],
                ['state_id' => 37, 'city' => 'Lucien'],
                ['state_id' => 37, 'city' => 'Billings'],
                ['state_id' => 37, 'city' => 'Marland'],
                ['state_id' => 37, 'city' => 'Red Rock'],
                ['state_id' => 37, 'city' => 'Delaware'],
                ['state_id' => 37, 'city' => 'Lenapah'],
                ['state_id' => 37, 'city' => 'Nowata'],
                ['state_id' => 37, 'city' => 'S Coffeyville'],
                ['state_id' => 37, 'city' => 'Wann'],
                ['state_id' => 37, 'city' => 'Boley'],
                ['state_id' => 37, 'city' => 'Castle'],
                ['state_id' => 37, 'city' => 'Okemah'],
                ['state_id' => 37, 'city' => 'Paden'],
                ['state_id' => 37, 'city' => 'Weleetka'],
                ['state_id' => 37, 'city' => 'Edmond'],
                ['state_id' => 37, 'city' => 'Arcadia'],
                ['state_id' => 37, 'city' => 'Bethany'],
                ['state_id' => 37, 'city' => 'Choctaw'],
                ['state_id' => 37, 'city' => 'Harrah'],
                ['state_id' => 37, 'city' => 'Jones'],
                ['state_id' => 37, 'city' => 'Luther'],
                ['state_id' => 37, 'city' => 'Nicoma Park'],
                ['state_id' => 37, 'city' => 'Spencer'],
                ['state_id' => 37, 'city' => 'Wheatland'],
                ['state_id' => 37, 'city' => 'Newalla'],
                ['state_id' => 37, 'city' => 'Beggs'],
                ['state_id' => 37, 'city' => 'Dewar'],
                ['state_id' => 37, 'city' => 'Henryetta'],
                ['state_id' => 37, 'city' => 'Morris'],
                ['state_id' => 37, 'city' => 'Okmulgee'],
                ['state_id' => 37, 'city' => 'Preston'],
                ['state_id' => 37, 'city' => 'Schulter'],
                ['state_id' => 37, 'city' => 'Avant'],
                ['state_id' => 37, 'city' => 'Barnsdall'],
                ['state_id' => 37, 'city' => 'Hominy'],
                ['state_id' => 37, 'city' => 'Osage'],
                ['state_id' => 37, 'city' => 'Pawhuska'],
                ['state_id' => 37, 'city' => 'Prue'],
                ['state_id' => 37, 'city' => 'Skiatook'],
                ['state_id' => 37, 'city' => 'Wynona'],
                ['state_id' => 37, 'city' => 'Burbank'],
                ['state_id' => 37, 'city' => 'Fairfax'],
                ['state_id' => 37, 'city' => 'Shidler'],
                ['state_id' => 37, 'city' => 'Afton'],
                ['state_id' => 37, 'city' => 'Cardin'],
                ['state_id' => 37, 'city' => 'Commerce'],
                ['state_id' => 37, 'city' => 'Fairland'],
                ['state_id' => 37, 'city' => 'Miami'],
                ['state_id' => 37, 'city' => 'North Miami'],
                ['state_id' => 37, 'city' => 'Picher'],
                ['state_id' => 37, 'city' => 'Quapaw'],
                ['state_id' => 37, 'city' => 'Wyandotte'],
                ['state_id' => 37, 'city' => 'Cleveland'],
                ['state_id' => 37, 'city' => 'Hallett'],
                ['state_id' => 37, 'city' => 'Jennings'],
                ['state_id' => 37, 'city' => 'Maramec'],
                ['state_id' => 37, 'city' => 'Pawnee'],
                ['state_id' => 37, 'city' => 'Terlton'],
                ['state_id' => 37, 'city' => 'Ralston'],
                ['state_id' => 37, 'city' => 'Cushing'],
                ['state_id' => 37, 'city' => 'Glencoe'],
                ['state_id' => 37, 'city' => 'Perkins'],
                ['state_id' => 37, 'city' => 'Ripley'],
                ['state_id' => 37, 'city' => 'Stillwater'],
                ['state_id' => 37, 'city' => 'Yale'],
                ['state_id' => 37, 'city' => 'Canadian'],
                ['state_id' => 37, 'city' => 'Crowder'],
                ['state_id' => 37, 'city' => 'Indianola'],
                ['state_id' => 37, 'city' => 'Mcalester'],
                ['state_id' => 37, 'city' => 'Alderson'],
                ['state_id' => 37, 'city' => 'Blanco'],
                ['state_id' => 37, 'city' => 'Blocker'],
                ['state_id' => 37, 'city' => 'Haileyville'],
                ['state_id' => 37, 'city' => 'Hartshorne'],
                ['state_id' => 37, 'city' => 'Kiowa'],
                ['state_id' => 37, 'city' => 'Krebs'],
                ['state_id' => 37, 'city' => 'Pittsburg'],
                ['state_id' => 37, 'city' => 'Quinton'],
                ['state_id' => 37, 'city' => 'Savanna'],
                ['state_id' => 37, 'city' => 'Wardville'],
                ['state_id' => 37, 'city' => 'Ada'],
                ['state_id' => 37, 'city' => 'Allen'],
                ['state_id' => 37, 'city' => 'Fittstown'],
                ['state_id' => 37, 'city' => 'Fitzhugh'],
                ['state_id' => 37, 'city' => 'Francis'],
                ['state_id' => 37, 'city' => 'Roff'],
                ['state_id' => 37, 'city' => 'Stonewall'],
                ['state_id' => 37, 'city' => 'Shawnee'],
                ['state_id' => 37, 'city' => 'Asher'],
                ['state_id' => 37, 'city' => 'Earlsboro'],
                ['state_id' => 37, 'city' => 'Mcloud'],
                ['state_id' => 37, 'city' => 'Macomb'],
                ['state_id' => 37, 'city' => 'Maud'],
                ['state_id' => 37, 'city' => 'Saint Louis'],
                ['state_id' => 37, 'city' => 'Tecumseh'],
                ['state_id' => 37, 'city' => 'Wanette'],
                ['state_id' => 37, 'city' => 'Albion'],
                ['state_id' => 37, 'city' => 'Antlers'],
                ['state_id' => 37, 'city' => 'Clayton'],
                ['state_id' => 37, 'city' => 'Finley'],
                ['state_id' => 37, 'city' => 'Moyers'],
                ['state_id' => 37, 'city' => 'Nashoba'],
                ['state_id' => 37, 'city' => 'Rattan'],
                ['state_id' => 37, 'city' => 'Snow'],
                ['state_id' => 37, 'city' => 'Tuskahoma'],
                ['state_id' => 37, 'city' => 'Cheyenne'],
                ['state_id' => 37, 'city' => 'Crawford'],
                ['state_id' => 37, 'city' => 'Durham'],
                ['state_id' => 37, 'city' => 'Hammon'],
                ['state_id' => 37, 'city' => 'Reydon'],
                ['state_id' => 37, 'city' => 'Sweetwater'],
                ['state_id' => 37, 'city' => 'Catoosa'],
                ['state_id' => 37, 'city' => 'Chelsea'],
                ['state_id' => 37, 'city' => 'Claremore'],
                ['state_id' => 37, 'city' => 'Foyil'],
                ['state_id' => 37, 'city' => 'Inola'],
                ['state_id' => 37, 'city' => 'Oologah'],
                ['state_id' => 37, 'city' => 'Talala'],
                ['state_id' => 37, 'city' => 'Seminole'],
                ['state_id' => 37, 'city' => 'Bowlegs'],
                ['state_id' => 37, 'city' => 'Cromwell'],
                ['state_id' => 37, 'city' => 'Konawa'],
                ['state_id' => 37, 'city' => 'Sasakwa'],
                ['state_id' => 37, 'city' => 'Wewoka'],
                ['state_id' => 37, 'city' => 'Gore'],
                ['state_id' => 37, 'city' => 'Gans'],
                ['state_id' => 37, 'city' => 'Marble City'],
                ['state_id' => 37, 'city' => 'Moffett'],
                ['state_id' => 37, 'city' => 'Muldrow'],
                ['state_id' => 37, 'city' => 'Roland'],
                ['state_id' => 37, 'city' => 'Sallisaw'],
                ['state_id' => 37, 'city' => 'Vian'],
                ['state_id' => 37, 'city' => 'Marlow'],
                ['state_id' => 37, 'city' => 'Countyline'],
                ['state_id' => 37, 'city' => 'Foster'],
                ['state_id' => 37, 'city' => 'Loco'],
                ['state_id' => 37, 'city' => 'Velma'],
                ['state_id' => 37, 'city' => 'Comanche'],
                ['state_id' => 37, 'city' => 'Duncan'],
                ['state_id' => 37, 'city' => 'Adams'],
                ['state_id' => 37, 'city' => 'Goodwell'],
                ['state_id' => 37, 'city' => 'Guymon'],
                ['state_id' => 37, 'city' => 'Hardesty'],
                ['state_id' => 37, 'city' => 'Hooker'],
                ['state_id' => 37, 'city' => 'Texhoma'],
                ['state_id' => 37, 'city' => 'Tyrone'],
                ['state_id' => 37, 'city' => 'Davidson'],
                ['state_id' => 37, 'city' => 'Frederick'],
                ['state_id' => 37, 'city' => 'Grandfield'],
                ['state_id' => 37, 'city' => 'Hollister'],
                ['state_id' => 37, 'city' => 'Loveland'],
                ['state_id' => 37, 'city' => 'Manitou'],
                ['state_id' => 37, 'city' => 'Tipton'],
                ['state_id' => 37, 'city' => 'Bixby'],
                ['state_id' => 37, 'city' => 'Broken Arrow'],
                ['state_id' => 37, 'city' => 'Collinsville'],
                ['state_id' => 37, 'city' => 'Glenpool'],
                ['state_id' => 37, 'city' => 'Jenks'],
                ['state_id' => 37, 'city' => 'Leonard'],
                ['state_id' => 37, 'city' => 'Oakhurst'],
                ['state_id' => 37, 'city' => 'Owasso'],
                ['state_id' => 37, 'city' => 'Sand Springs'],
                ['state_id' => 37, 'city' => 'Sperry'],
                ['state_id' => 37, 'city' => 'Coweta'],
                ['state_id' => 37, 'city' => 'Okay'],
                ['state_id' => 37, 'city' => 'Porter'],
                ['state_id' => 37, 'city' => 'Redbird'],
                ['state_id' => 37, 'city' => 'Wagoner'],
                ['state_id' => 37, 'city' => 'Bartlesville'],
                ['state_id' => 37, 'city' => 'Copan'],
                ['state_id' => 37, 'city' => 'Dewey'],
                ['state_id' => 37, 'city' => 'Ochelata'],
                ['state_id' => 37, 'city' => 'Ramona'],
                ['state_id' => 37, 'city' => 'Vera'],
                ['state_id' => 37, 'city' => 'Colony'],
                ['state_id' => 37, 'city' => 'Corn'],
                ['state_id' => 37, 'city' => 'Bessie'],
                ['state_id' => 37, 'city' => 'Burns Flat'],
                ['state_id' => 37, 'city' => 'Canute'],
                ['state_id' => 37, 'city' => 'Cordell'],
                ['state_id' => 37, 'city' => 'Dill City'],
                ['state_id' => 37, 'city' => 'Foss'],
                ['state_id' => 37, 'city' => 'Rocky'],
                ['state_id' => 37, 'city' => 'Sentinel'],
                ['state_id' => 37, 'city' => 'Alva'],
                ['state_id' => 37, 'city' => 'Dacoma'],
                ['state_id' => 37, 'city' => 'Hopeton'],
                ['state_id' => 37, 'city' => 'Freedom'],
                ['state_id' => 37, 'city' => 'Waynoka'],
                ['state_id' => 37, 'city' => 'Woodward'],
                ['state_id' => 37, 'city' => 'Fort Supply'],
                ['state_id' => 37, 'city' => 'Mooreland'],
                ['state_id' => 37, 'city' => 'Mutual'],
                ['state_id' => 37, 'city' => 'Sharon', 'state_id' => 37]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
