<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State50TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of WI - Wisconsin.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 50, 'city' => 'Adams'],
                ['state_id' => 50, 'city' => 'Dellwood'],
                ['state_id' => 50, 'city' => 'Friendship'],
                ['state_id' => 50, 'city' => 'Grand Marsh'],
                ['state_id' => 50, 'city' => 'Arkdale'],
                ['state_id' => 50, 'city' => 'Butternut'],
                ['state_id' => 50, 'city' => 'Clam Lake'],
                ['state_id' => 50, 'city' => 'Glidden'],
                ['state_id' => 50, 'city' => 'Mellen'],
                ['state_id' => 50, 'city' => 'Ashland'],
                ['state_id' => 50, 'city' => 'High Bridge'],
                ['state_id' => 50, 'city' => 'La Pointe'],
                ['state_id' => 50, 'city' => 'Marengo'],
                ['state_id' => 50, 'city' => 'Odanah'],
                ['state_id' => 50, 'city' => 'Chetek'],
                ['state_id' => 50, 'city' => 'Dallas'],
                ['state_id' => 50, 'city' => 'Prairie Farm'],
                ['state_id' => 50, 'city' => 'Almena'],
                ['state_id' => 50, 'city' => 'Barron'],
                ['state_id' => 50, 'city' => 'Barronett'],
                ['state_id' => 50, 'city' => 'Brill'],
                ['state_id' => 50, 'city' => 'Cameron'],
                ['state_id' => 50, 'city' => 'Comstock'],
                ['state_id' => 50, 'city' => 'Cumberland'],
                ['state_id' => 50, 'city' => 'Haugen'],
                ['state_id' => 50, 'city' => 'Mikana'],
                ['state_id' => 50, 'city' => 'Rice Lake'],
                ['state_id' => 50, 'city' => 'Turtle Lake'],
                ['state_id' => 50, 'city' => 'Bayfield'],
                ['state_id' => 50, 'city' => 'Benoit'],
                ['state_id' => 50, 'city' => 'Cable'],
                ['state_id' => 50, 'city' => 'Cornucopia'],
                ['state_id' => 50, 'city' => 'Drummond'],
                ['state_id' => 50, 'city' => 'Grand View'],
                ['state_id' => 50, 'city' => 'Herbster'],
                ['state_id' => 50, 'city' => 'Iron River'],
                ['state_id' => 50, 'city' => 'Mason'],
                ['state_id' => 50, 'city' => 'Port Wing'],
                ['state_id' => 50, 'city' => 'Washburn'],
                ['state_id' => 50, 'city' => 'De Pere'],
                ['state_id' => 50, 'city' => 'Greenleaf'],
                ['state_id' => 50, 'city' => 'Pulaski'],
                ['state_id' => 50, 'city' => 'Suamico'],
                ['state_id' => 50, 'city' => 'Wrightstown'],
                ['state_id' => 50, 'city' => 'Denmark'],
                ['state_id' => 50, 'city' => 'New Franken'],
                ['state_id' => 50, 'city' => 'Green Bay'],
                ['state_id' => 50, 'city' => 'Alma'],
                ['state_id' => 50, 'city' => 'Cochrane'],
                ['state_id' => 50, 'city' => 'Fountain City'],
                ['state_id' => 50, 'city' => 'Gilmanton'],
                ['state_id' => 50, 'city' => 'Mondovi'],
                ['state_id' => 50, 'city' => 'Nelson'],
                ['state_id' => 50, 'city' => 'Danbury'],
                ['state_id' => 50, 'city' => 'Grantsburg'],
                ['state_id' => 50, 'city' => 'Hertel'],
                ['state_id' => 50, 'city' => 'Siren'],
                ['state_id' => 50, 'city' => 'Webster'],
                ['state_id' => 50, 'city' => 'Chilton'],
                ['state_id' => 50, 'city' => 'New Holstein'],
                ['state_id' => 50, 'city' => 'Stockbridge'],
                ['state_id' => 50, 'city' => 'Brillion'],
                ['state_id' => 50, 'city' => 'Forest Junction'],
                ['state_id' => 50, 'city' => 'Hilbert'],
                ['state_id' => 50, 'city' => 'Potter'],
                ['state_id' => 50, 'city' => 'Sherwood'],
                ['state_id' => 50, 'city' => 'Bloomer'],
                ['state_id' => 50, 'city' => 'Boyd'],
                ['state_id' => 50, 'city' => 'Cadott'],
                ['state_id' => 50, 'city' => 'Chippewa Falls'],
                ['state_id' => 50, 'city' => 'Cornell'],
                ['state_id' => 50, 'city' => 'Holcombe'],
                ['state_id' => 50, 'city' => 'Jim Falls'],
                ['state_id' => 50, 'city' => 'New Auburn'],
                ['state_id' => 50, 'city' => 'Stanley'],
                ['state_id' => 50, 'city' => 'Abbotsford'],
                ['state_id' => 50, 'city' => 'Chili'],
                ['state_id' => 50, 'city' => 'Colby'],
                ['state_id' => 50, 'city' => 'Curtiss'],
                ['state_id' => 50, 'city' => 'Dorchester'],
                ['state_id' => 50, 'city' => 'Granton'],
                ['state_id' => 50, 'city' => 'Greenwood'],
                ['state_id' => 50, 'city' => 'Loyal'],
                ['state_id' => 50, 'city' => 'Neillsville'],
                ['state_id' => 50, 'city' => 'Owen'],
                ['state_id' => 50, 'city' => 'Willard'],
                ['state_id' => 50, 'city' => 'Withee'],
                ['state_id' => 50, 'city' => 'Humbird'],
                ['state_id' => 50, 'city' => 'Thorp'],
                ['state_id' => 50, 'city' => 'Lodi'],
                ['state_id' => 50, 'city' => 'Portage'],
                ['state_id' => 50, 'city' => 'Arlington'],
                ['state_id' => 50, 'city' => 'Cambria'],
                ['state_id' => 50, 'city' => 'Columbus'],
                ['state_id' => 50, 'city' => 'Doylestown'],
                ['state_id' => 50, 'city' => 'Fall River'],
                ['state_id' => 50, 'city' => 'Friesland'],
                ['state_id' => 50, 'city' => 'Pardeeville'],
                ['state_id' => 50, 'city' => 'Poynette'],
                ['state_id' => 50, 'city' => 'Randolph'],
                ['state_id' => 50, 'city' => 'Rio'],
                ['state_id' => 50, 'city' => 'Wisconsin Dells'],
                ['state_id' => 50, 'city' => 'Wyocena'],
                ['state_id' => 50, 'city' => 'Prairie Du Chien'],
                ['state_id' => 50, 'city' => 'Wauzeka'],
                ['state_id' => 50, 'city' => 'Eastman'],
                ['state_id' => 50, 'city' => 'Ferryville'],
                ['state_id' => 50, 'city' => 'Gays Mills'],
                ['state_id' => 50, 'city' => 'Lynxville'],
                ['state_id' => 50, 'city' => 'Mount Sterling'],
                ['state_id' => 50, 'city' => 'Seneca'],
                ['state_id' => 50, 'city' => 'Soldiers Grove'],
                ['state_id' => 50, 'city' => 'Steuben'],
                ['state_id' => 50, 'city' => 'Belleville'],
                ['state_id' => 50, 'city' => 'Black Earth'],
                ['state_id' => 50, 'city' => 'Blue Mounds'],
                ['state_id' => 50, 'city' => 'Cambridge'],
                ['state_id' => 50, 'city' => 'Cottage Grove'],
                ['state_id' => 50, 'city' => 'Cross Plains'],
                ['state_id' => 50, 'city' => 'Dane'],
                ['state_id' => 50, 'city' => 'Deerfield'],
                ['state_id' => 50, 'city' => 'Deforest'],
                ['state_id' => 50, 'city' => 'Mc Farland'],
                ['state_id' => 50, 'city' => 'Marshall'],
                ['state_id' => 50, 'city' => 'Mazomanie'],
                ['state_id' => 50, 'city' => 'Middleton'],
                ['state_id' => 50, 'city' => 'Morrisonville'],
                ['state_id' => 50, 'city' => 'Mount Horeb'],
                ['state_id' => 50, 'city' => 'Oregon'],
                ['state_id' => 50, 'city' => 'Stoughton'],
                ['state_id' => 50, 'city' => 'Sun Prairie'],
                ['state_id' => 50, 'city' => 'Verona'],
                ['state_id' => 50, 'city' => 'Waunakee'],
                ['state_id' => 50, 'city' => 'Windsor'],
                ['state_id' => 50, 'city' => 'Madison'],
                ['state_id' => 50, 'city' => 'Ashippun'],
                ['state_id' => 50, 'city' => 'Brownsville'],
                ['state_id' => 50, 'city' => 'Clyman'],
                ['state_id' => 50, 'city' => 'Horicon'],
                ['state_id' => 50, 'city' => 'Hustisford'],
                ['state_id' => 50, 'city' => 'Iron Ridge'],
                ['state_id' => 50, 'city' => 'Juneau'],
                ['state_id' => 50, 'city' => 'Lebanon'],
                ['state_id' => 50, 'city' => 'Lomira'],
                ['state_id' => 50, 'city' => 'Mayville'],
                ['state_id' => 50, 'city' => 'Neosho'],
                ['state_id' => 50, 'city' => 'Rubicon'],
                ['state_id' => 50, 'city' => 'Theresa'],
                ['state_id' => 50, 'city' => 'Watertown'],
                ['state_id' => 50, 'city' => 'Woodland'],
                ['state_id' => 50, 'city' => 'Lowell'],
                ['state_id' => 50, 'city' => 'Reeseville'],
                ['state_id' => 50, 'city' => 'Beaver Dam'],
                ['state_id' => 50, 'city' => 'Burnett'],
                ['state_id' => 50, 'city' => 'Fox Lake'],
                ['state_id' => 50, 'city' => 'Waupun'],
                ['state_id' => 50, 'city' => 'Baileys Harbor'],
                ['state_id' => 50, 'city' => 'Brussels'],
                ['state_id' => 50, 'city' => 'Egg Harbor'],
                ['state_id' => 50, 'city' => 'Ellison Bay'],
                ['state_id' => 50, 'city' => 'Ephraim'],
                ['state_id' => 50, 'city' => 'Fish Creek'],
                ['state_id' => 50, 'city' => 'Forestville'],
                ['state_id' => 50, 'city' => 'Maplewood'],
                ['state_id' => 50, 'city' => 'Sister Bay'],
                ['state_id' => 50, 'city' => 'Sturgeon Bay'],
                ['state_id' => 50, 'city' => 'Washington Island'],
                ['state_id' => 50, 'city' => 'Brule'],
                ['state_id' => 50, 'city' => 'Foxboro'],
                ['state_id' => 50, 'city' => 'Gordon'],
                ['state_id' => 50, 'city' => 'Hawthorne'],
                ['state_id' => 50, 'city' => 'Lake Nebagamon'],
                ['state_id' => 50, 'city' => 'Maple'],
                ['state_id' => 50, 'city' => 'Poplar'],
                ['state_id' => 50, 'city' => 'Solon Springs'],
                ['state_id' => 50, 'city' => 'South Range'],
                ['state_id' => 50, 'city' => 'Superior'],
                ['state_id' => 50, 'city' => 'Wascott'],
                ['state_id' => 50, 'city' => 'Boyceville'],
                ['state_id' => 50, 'city' => 'Colfax'],
                ['state_id' => 50, 'city' => 'Downing'],
                ['state_id' => 50, 'city' => 'Downsville'],
                ['state_id' => 50, 'city' => 'Eau Galle'],
                ['state_id' => 50, 'city' => 'Elk Mound'],
                ['state_id' => 50, 'city' => 'Knapp'],
                ['state_id' => 50, 'city' => 'Menomonie'],
                ['state_id' => 50, 'city' => 'Ridgeland'],
                ['state_id' => 50, 'city' => 'Rock Falls'],
                ['state_id' => 50, 'city' => 'Sand Creek'],
                ['state_id' => 50, 'city' => 'Wheeler'],
                ['state_id' => 50, 'city' => 'Eau Claire'],
                ['state_id' => 50, 'city' => 'Altoona'],
                ['state_id' => 50, 'city' => 'Augusta'],
                ['state_id' => 50, 'city' => 'Fairchild'],
                ['state_id' => 50, 'city' => 'Fall Creek'],
                ['state_id' => 50, 'city' => 'Fence'],
                ['state_id' => 50, 'city' => 'Florence'],
                ['state_id' => 50, 'city' => 'Long Lake'],
                ['state_id' => 50, 'city' => 'Campbellsport'],
                ['state_id' => 50, 'city' => 'Eden'],
                ['state_id' => 50, 'city' => 'Malone'],
                ['state_id' => 50, 'city' => 'Mount Calvary'],
                ['state_id' => 50, 'city' => 'Oakfield'],
                ['state_id' => 50, 'city' => 'Saint Cloud'],
                ['state_id' => 50, 'city' => 'Brandon'],
                ['state_id' => 50, 'city' => 'Fairwater'],
                ['state_id' => 50, 'city' => 'Eldorado'],
                ['state_id' => 50, 'city' => 'Fond Du Lac'],
                ['state_id' => 50, 'city' => 'Ripon'],
                ['state_id' => 50, 'city' => 'Rosendale'],
                ['state_id' => 50, 'city' => 'Van Dyne'],
                ['state_id' => 50, 'city' => 'Armstrong Creek'],
                ['state_id' => 50, 'city' => 'Argonne'],
                ['state_id' => 50, 'city' => 'Crandon'],
                ['state_id' => 50, 'city' => 'Laona'],
                ['state_id' => 50, 'city' => 'Wabeno'],
                ['state_id' => 50, 'city' => 'Blue River'],
                ['state_id' => 50, 'city' => 'Livingston'],
                ['state_id' => 50, 'city' => 'Montfort'],
                ['state_id' => 50, 'city' => 'Muscoda'],
                ['state_id' => 50, 'city' => 'Bagley'],
                ['state_id' => 50, 'city' => 'Beetown'],
                ['state_id' => 50, 'city' => 'Bloomington'],
                ['state_id' => 50, 'city' => 'Boscobel'],
                ['state_id' => 50, 'city' => 'Cassville'],
                ['state_id' => 50, 'city' => 'Cuba City'],
                ['state_id' => 50, 'city' => 'Dickeyville'],
                ['state_id' => 50, 'city' => 'Fennimore'],
                ['state_id' => 50, 'city' => 'Glen Haven'],
                ['state_id' => 50, 'city' => 'Hazel Green'],
                ['state_id' => 50, 'city' => 'Kieler'],
                ['state_id' => 50, 'city' => 'Lancaster'],
                ['state_id' => 50, 'city' => 'Mount Hope'],
                ['state_id' => 50, 'city' => 'Patch Grove'],
                ['state_id' => 50, 'city' => 'Platteville'],
                ['state_id' => 50, 'city' => 'Potosi'],
                ['state_id' => 50, 'city' => 'Sinsinawa'],
                ['state_id' => 50, 'city' => 'Stitzer'],
                ['state_id' => 50, 'city' => 'Woodman'],
                ['state_id' => 50, 'city' => 'Albany'],
                ['state_id' => 50, 'city' => 'Brodhead'],
                ['state_id' => 50, 'city' => 'Brooklyn'],
                ['state_id' => 50, 'city' => 'Browntown'],
                ['state_id' => 50, 'city' => 'Juda'],
                ['state_id' => 50, 'city' => 'Monroe'],
                ['state_id' => 50, 'city' => 'Monticello'],
                ['state_id' => 50, 'city' => 'New Glarus'],
                ['state_id' => 50, 'city' => 'Dalton'],
                ['state_id' => 50, 'city' => 'Kingston'],
                ['state_id' => 50, 'city' => 'Markesan'],
                ['state_id' => 50, 'city' => 'Marquette'],
                ['state_id' => 50, 'city' => 'Berlin'],
                ['state_id' => 50, 'city' => 'Green Lake'],
                ['state_id' => 50, 'city' => 'Princeton'],
                ['state_id' => 50, 'city' => 'Arena'],
                ['state_id' => 50, 'city' => 'Avoca'],
                ['state_id' => 50, 'city' => 'Barneveld'],
                ['state_id' => 50, 'city' => 'Cobb'],
                ['state_id' => 50, 'city' => 'Dodgeville'],
                ['state_id' => 50, 'city' => 'Edmund'],
                ['state_id' => 50, 'city' => 'Highland'],
                ['state_id' => 50, 'city' => 'Hollandale'],
                ['state_id' => 50, 'city' => 'Linden'],
                ['state_id' => 50, 'city' => 'Mineral Point'],
                ['state_id' => 50, 'city' => 'Rewey'],
                ['state_id' => 50, 'city' => 'Ridgeway'],
                ['state_id' => 50, 'city' => 'Gile'],
                ['state_id' => 50, 'city' => 'Hurley'],
                ['state_id' => 50, 'city' => 'Iron Belt'],
                ['state_id' => 50, 'city' => 'Mercer'],
                ['state_id' => 50, 'city' => 'Montreal'],
                ['state_id' => 50, 'city' => 'Saxon'],
                ['state_id' => 50, 'city' => 'Upson'],
                ['state_id' => 50, 'city' => 'Alma Center'],
                ['state_id' => 50, 'city' => 'Black River Falls'],
                ['state_id' => 50, 'city' => 'Hixton'],
                ['state_id' => 50, 'city' => 'Melrose'],
                ['state_id' => 50, 'city' => 'Millston'],
                ['state_id' => 50, 'city' => 'Taylor'],
                ['state_id' => 50, 'city' => 'Merrillan'],
                ['state_id' => 50, 'city' => 'Ixonia'],
                ['state_id' => 50, 'city' => 'Johnson Creek'],
                ['state_id' => 50, 'city' => 'Helenville'],
                ['state_id' => 50, 'city' => 'Palmyra'],
                ['state_id' => 50, 'city' => 'Sullivan'],
                ['state_id' => 50, 'city' => 'Fort Atkinson'],
                ['state_id' => 50, 'city' => 'Jefferson'],
                ['state_id' => 50, 'city' => 'Lake Mills'],
                ['state_id' => 50, 'city' => 'Waterloo'],
                ['state_id' => 50, 'city' => 'Elroy'],
                ['state_id' => 50, 'city' => 'Lyndon Station'],
                ['state_id' => 50, 'city' => 'Mauston'],
                ['state_id' => 50, 'city' => 'New Lisbon'],
                ['state_id' => 50, 'city' => 'Union Center'],
                ['state_id' => 50, 'city' => 'Wonewoc'],
                ['state_id' => 50, 'city' => 'Camp Douglas'],
                ['state_id' => 50, 'city' => 'Hustler'],
                ['state_id' => 50, 'city' => 'Mather'],
                ['state_id' => 50, 'city' => 'Necedah'],
                ['state_id' => 50, 'city' => 'Bassett'],
                ['state_id' => 50, 'city' => 'Benet Lake'],
                ['state_id' => 50, 'city' => 'Bristol'],
                ['state_id' => 50, 'city' => 'Camp Lake'],
                ['state_id' => 50, 'city' => 'Kenosha'],
                ['state_id' => 50, 'city' => 'New Munster'],
                ['state_id' => 50, 'city' => 'Pleasant Prairie'],
                ['state_id' => 50, 'city' => 'Powers Lake'],
                ['state_id' => 50, 'city' => 'Salem'],
                ['state_id' => 50, 'city' => 'Silver Lake'],
                ['state_id' => 50, 'city' => 'Somers'],
                ['state_id' => 50, 'city' => 'Trevor'],
                ['state_id' => 50, 'city' => 'Twin Lakes'],
                ['state_id' => 50, 'city' => 'Wilmot'],
                ['state_id' => 50, 'city' => 'Woodworth'],
                ['state_id' => 50, 'city' => 'Algoma'],
                ['state_id' => 50, 'city' => 'Casco'],
                ['state_id' => 50, 'city' => 'Kewaunee'],
                ['state_id' => 50, 'city' => 'Luxemburg'],
                ['state_id' => 50, 'city' => 'La Crosse'],
                ['state_id' => 50, 'city' => 'Bangor'],
                ['state_id' => 50, 'city' => 'Holmen'],
                ['state_id' => 50, 'city' => 'Mindoro'],
                ['state_id' => 50, 'city' => 'Onalaska'],
                ['state_id' => 50, 'city' => 'Rockland'],
                ['state_id' => 50, 'city' => 'West Salem'],
                ['state_id' => 50, 'city' => 'Argyle'],
                ['state_id' => 50, 'city' => 'Belmont'],
                ['state_id' => 50, 'city' => 'Blanchardville'],
                ['state_id' => 50, 'city' => 'Darlington'],
                ['state_id' => 50, 'city' => 'Gratiot'],
                ['state_id' => 50, 'city' => 'Shullsburg'],
                ['state_id' => 50, 'city' => 'South Wayne'],
                ['state_id' => 50, 'city' => 'Woodford'],
                ['state_id' => 50, 'city' => 'Benton'],
                ['state_id' => 50, 'city' => 'Antigo'],
                ['state_id' => 50, 'city' => 'Bryant'],
                ['state_id' => 50, 'city' => 'Deerbrook'],
                ['state_id' => 50, 'city' => 'Elcho'],
                ['state_id' => 50, 'city' => 'Elton'],
                ['state_id' => 50, 'city' => 'Pearson'],
                ['state_id' => 50, 'city' => 'Phlox'],
                ['state_id' => 50, 'city' => 'Pickerel'],
                ['state_id' => 50, 'city' => 'Summit Lake'],
                ['state_id' => 50, 'city' => 'White Lake'],
                ['state_id' => 50, 'city' => 'Gleason'],
                ['state_id' => 50, 'city' => 'Irma'],
                ['state_id' => 50, 'city' => 'Merrill'],
                ['state_id' => 50, 'city' => 'Tomahawk'],
                ['state_id' => 50, 'city' => 'Heafford Junction'],
                ['state_id' => 50, 'city' => 'Cleveland'],
                ['state_id' => 50, 'city' => 'Kiel'],
                ['state_id' => 50, 'city' => 'Newton'],
                ['state_id' => 50, 'city' => 'Collins'],
                ['state_id' => 50, 'city' => 'Francis Creek'],
                ['state_id' => 50, 'city' => 'Kellnersville'],
                ['state_id' => 50, 'city' => 'Manitowoc'],
                ['state_id' => 50, 'city' => 'Maribel'],
                ['state_id' => 50, 'city' => 'Mishicot'],
                ['state_id' => 50, 'city' => 'Reedsville'],
                ['state_id' => 50, 'city' => 'Saint Nazianz'],
                ['state_id' => 50, 'city' => 'Tisch Mills'],
                ['state_id' => 50, 'city' => 'Two Rivers'],
                ['state_id' => 50, 'city' => 'Valders'],
                ['state_id' => 50, 'city' => 'Whitelaw'],
                ['state_id' => 50, 'city' => 'Wausau'],
                ['state_id' => 50, 'city' => 'Aniwa'],
                ['state_id' => 50, 'city' => 'Athens'],
                ['state_id' => 50, 'city' => 'Brokaw'],
                ['state_id' => 50, 'city' => 'Edgar'],
                ['state_id' => 50, 'city' => 'Eland'],
                ['state_id' => 50, 'city' => 'Elderon'],
                ['state_id' => 50, 'city' => 'Galloway'],
                ['state_id' => 50, 'city' => 'Hatley'],
                ['state_id' => 50, 'city' => 'Marathon'],
                ['state_id' => 50, 'city' => 'Mosinee'],
                ['state_id' => 50, 'city' => 'Ringle'],
                ['state_id' => 50, 'city' => 'Rothschild'],
                ['state_id' => 50, 'city' => 'Schofield'],
                ['state_id' => 50, 'city' => 'Spencer'],
                ['state_id' => 50, 'city' => 'Stratford'],
                ['state_id' => 50, 'city' => 'Unity'],
                ['state_id' => 50, 'city' => 'Amberg'],
                ['state_id' => 50, 'city' => 'Athelstane'],
                ['state_id' => 50, 'city' => 'Coleman'],
                ['state_id' => 50, 'city' => 'Crivitz'],
                ['state_id' => 50, 'city' => 'Dunbar'],
                ['state_id' => 50, 'city' => 'Goodman'],
                ['state_id' => 50, 'city' => 'Marinette'],
                ['state_id' => 50, 'city' => 'Niagara'],
                ['state_id' => 50, 'city' => 'Pembine'],
                ['state_id' => 50, 'city' => 'Peshtigo'],
                ['state_id' => 50, 'city' => 'Porterfield'],
                ['state_id' => 50, 'city' => 'Pound'],
                ['state_id' => 50, 'city' => 'Wausaukee'],
                ['state_id' => 50, 'city' => 'Briggsville'],
                ['state_id' => 50, 'city' => 'Endeavor'],
                ['state_id' => 50, 'city' => 'Montello'],
                ['state_id' => 50, 'city' => 'Oxford'],
                ['state_id' => 50, 'city' => 'Packwaukee'],
                ['state_id' => 50, 'city' => 'Westfield'],
                ['state_id' => 50, 'city' => 'Neshkoro'],
                ['state_id' => 50, 'city' => 'Keshena'],
                ['state_id' => 50, 'city' => 'Neopit'],
                ['state_id' => 50, 'city' => 'Cudahy'],
                ['state_id' => 50, 'city' => 'Greendale'],
                ['state_id' => 50, 'city' => 'Hales Corners'],
                ['state_id' => 50, 'city' => 'Franklin'],
                ['state_id' => 50, 'city' => 'Oak Creek'],
                ['state_id' => 50, 'city' => 'South Milwaukee'],
                ['state_id' => 50, 'city' => 'Milwaukee'],
                ['state_id' => 50, 'city' => 'Saint Francis'],
                ['state_id' => 50, 'city' => 'Cashton'],
                ['state_id' => 50, 'city' => 'Cataract'],
                ['state_id' => 50, 'city' => 'Kendall'],
                ['state_id' => 50, 'city' => 'Norwalk'],
                ['state_id' => 50, 'city' => 'Oakdale'],
                ['state_id' => 50, 'city' => 'Sparta'],
                ['state_id' => 50, 'city' => 'Tomah'],
                ['state_id' => 50, 'city' => 'Tunnel City'],
                ['state_id' => 50, 'city' => 'Warrens'],
                ['state_id' => 50, 'city' => 'Wilton'],
                ['state_id' => 50, 'city' => 'Abrams'],
                ['state_id' => 50, 'city' => 'Gillett'],
                ['state_id' => 50, 'city' => 'Lakewood'],
                ['state_id' => 50, 'city' => 'Lena'],
                ['state_id' => 50, 'city' => 'Little Suamico'],
                ['state_id' => 50, 'city' => 'Mountain'],
                ['state_id' => 50, 'city' => 'Oconto'],
                ['state_id' => 50, 'city' => 'Oconto Falls'],
                ['state_id' => 50, 'city' => 'Sobieski'],
                ['state_id' => 50, 'city' => 'Suring'],
                ['state_id' => 50, 'city' => 'Townsend'],
                ['state_id' => 50, 'city' => 'Pelican Lake'],
                ['state_id' => 50, 'city' => 'Rhinelander'],
                ['state_id' => 50, 'city' => 'Harshaw'],
                ['state_id' => 50, 'city' => 'Hazelhurst'],
                ['state_id' => 50, 'city' => 'Lake Tomahawk'],
                ['state_id' => 50, 'city' => 'Mc Naughton'],
                ['state_id' => 50, 'city' => 'Minocqua'],
                ['state_id' => 50, 'city' => 'Three Lakes'],
                ['state_id' => 50, 'city' => 'Tripoli'],
                ['state_id' => 50, 'city' => 'Woodruff'],
                ['state_id' => 50, 'city' => 'Black Creek'],
                ['state_id' => 50, 'city' => 'Combined Locks'],
                ['state_id' => 50, 'city' => 'Kaukauna'],
                ['state_id' => 50, 'city' => 'Freedom'],
                ['state_id' => 50, 'city' => 'Kimberly'],
                ['state_id' => 50, 'city' => 'Little Chute'],
                ['state_id' => 50, 'city' => 'Nichols'],
                ['state_id' => 50, 'city' => 'Oneida'],
                ['state_id' => 50, 'city' => 'Seymour'],
                ['state_id' => 50, 'city' => 'Shiocton'],
                ['state_id' => 50, 'city' => 'Appleton'],
                ['state_id' => 50, 'city' => 'Bear Creek'],
                ['state_id' => 50, 'city' => 'Dale'],
                ['state_id' => 50, 'city' => 'Greenville'],
                ['state_id' => 50, 'city' => 'Hortonville'],
                ['state_id' => 50, 'city' => 'Belgium'],
                ['state_id' => 50, 'city' => 'Cedarburg'],
                ['state_id' => 50, 'city' => 'Fredonia'],
                ['state_id' => 50, 'city' => 'Grafton'],
                ['state_id' => 50, 'city' => 'Port Washington'],
                ['state_id' => 50, 'city' => 'Saukville'],
                ['state_id' => 50, 'city' => 'Mequon'],
                ['state_id' => 50, 'city' => 'Arkansaw'],
                ['state_id' => 50, 'city' => 'Durand'],
                ['state_id' => 50, 'city' => 'Pepin'],
                ['state_id' => 50, 'city' => 'Stockholm'],
                ['state_id' => 50, 'city' => 'Beldenville'],
                ['state_id' => 50, 'city' => 'East Ellsworth'],
                ['state_id' => 50, 'city' => 'Ellsworth'],
                ['state_id' => 50, 'city' => 'Hager City'],
                ['state_id' => 50, 'city' => 'Prescott'],
                ['state_id' => 50, 'city' => 'River Falls'],
                ['state_id' => 50, 'city' => 'Bay City'],
                ['state_id' => 50, 'city' => 'Elmwood'],
                ['state_id' => 50, 'city' => 'Maiden Rock'],
                ['state_id' => 50, 'city' => 'Plum City'],
                ['state_id' => 50, 'city' => 'Spring Valley'],
                ['state_id' => 50, 'city' => 'Amery'],
                ['state_id' => 50, 'city' => 'Clayton'],
                ['state_id' => 50, 'city' => 'Clear Lake'],
                ['state_id' => 50, 'city' => 'Cushing'],
                ['state_id' => 50, 'city' => 'Dresser'],
                ['state_id' => 50, 'city' => 'Osceola'],
                ['state_id' => 50, 'city' => 'Saint Croix Falls'],
                ['state_id' => 50, 'city' => 'Star Prairie'],
                ['state_id' => 50, 'city' => 'Balsam Lake'],
                ['state_id' => 50, 'city' => 'Centuria'],
                ['state_id' => 50, 'city' => 'Frederic'],
                ['state_id' => 50, 'city' => 'Luck'],
                ['state_id' => 50, 'city' => 'Milltown'],
                ['state_id' => 50, 'city' => 'Amherst'],
                ['state_id' => 50, 'city' => 'Amherst Junction'],
                ['state_id' => 50, 'city' => 'Custer'],
                ['state_id' => 50, 'city' => 'Junction City'],
                ['state_id' => 50, 'city' => 'Nelsonville'],
                ['state_id' => 50, 'city' => 'Plover'],
                ['state_id' => 50, 'city' => 'Rosholt'],
                ['state_id' => 50, 'city' => 'Stevens Point'],
                ['state_id' => 50, 'city' => 'Almond'],
                ['state_id' => 50, 'city' => 'Bancroft'],
                ['state_id' => 50, 'city' => 'Ogema'],
                ['state_id' => 50, 'city' => 'Brantwood'],
                ['state_id' => 50, 'city' => 'Catawba'],
                ['state_id' => 50, 'city' => 'Fifield'],
                ['state_id' => 50, 'city' => 'Kennan'],
                ['state_id' => 50, 'city' => 'Park Falls'],
                ['state_id' => 50, 'city' => 'Phillips'],
                ['state_id' => 50, 'city' => 'Prentice'],
                ['state_id' => 50, 'city' => 'Burlington'],
                ['state_id' => 50, 'city' => 'Caledonia'],
                ['state_id' => 50, 'city' => 'Franksville'],
                ['state_id' => 50, 'city' => 'Kansasville'],
                ['state_id' => 50, 'city' => 'Rochester'],
                ['state_id' => 50, 'city' => 'Sturtevant'],
                ['state_id' => 50, 'city' => 'Union Grove'],
                ['state_id' => 50, 'city' => 'Waterford'],
                ['state_id' => 50, 'city' => 'Racine'],
                ['state_id' => 50, 'city' => 'Gotham'],
                ['state_id' => 50, 'city' => 'Lone Rock'],
                ['state_id' => 50, 'city' => 'Richland Center'],
                ['state_id' => 50, 'city' => 'Sextonville'],
                ['state_id' => 50, 'city' => 'Cazenovia'],
                ['state_id' => 50, 'city' => 'Afton'],
                ['state_id' => 50, 'city' => 'Avalon'],
                ['state_id' => 50, 'city' => 'Beloit'],
                ['state_id' => 50, 'city' => 'Clinton'],
                ['state_id' => 50, 'city' => 'Edgerton'],
                ['state_id' => 50, 'city' => 'Evansville'],
                ['state_id' => 50, 'city' => 'Footville'],
                ['state_id' => 50, 'city' => 'Hanover'],
                ['state_id' => 50, 'city' => 'Janesville'],
                ['state_id' => 50, 'city' => 'Milton'],
                ['state_id' => 50, 'city' => 'Orfordville'],
                ['state_id' => 50, 'city' => 'Glen Flora'],
                ['state_id' => 50, 'city' => 'Hawkins'],
                ['state_id' => 50, 'city' => 'Tony'],
                ['state_id' => 50, 'city' => 'Conrath'],
                ['state_id' => 50, 'city' => 'Sheldon'],
                ['state_id' => 50, 'city' => 'Bruce'],
                ['state_id' => 50, 'city' => 'Ladysmith'],
                ['state_id' => 50, 'city' => 'Weyerhaeuser'],
                ['state_id' => 50, 'city' => 'Baldwin'],
                ['state_id' => 50, 'city' => 'Deer Park'],
                ['state_id' => 50, 'city' => 'Glenwood City'],
                ['state_id' => 50, 'city' => 'Hammond'],
                ['state_id' => 50, 'city' => 'Hudson'],
                ['state_id' => 50, 'city' => 'New Richmond'],
                ['state_id' => 50, 'city' => 'Roberts'],
                ['state_id' => 50, 'city' => 'Somerset'],
                ['state_id' => 50, 'city' => 'Wilson'],
                ['state_id' => 50, 'city' => 'Woodville'],
                ['state_id' => 50, 'city' => 'Houlton'],
                ['state_id' => 50, 'city' => 'Merrimac'],
                ['state_id' => 50, 'city' => 'Plain'],
                ['state_id' => 50, 'city' => 'Prairie Du Sac'],
                ['state_id' => 50, 'city' => 'Sauk City'],
                ['state_id' => 50, 'city' => 'Spring Green'],
                ['state_id' => 50, 'city' => 'Baraboo'],
                ['state_id' => 50, 'city' => 'Hillpoint'],
                ['state_id' => 50, 'city' => 'Lake Delton'],
                ['state_id' => 50, 'city' => 'La Valle'],
                ['state_id' => 50, 'city' => 'Lime Ridge'],
                ['state_id' => 50, 'city' => 'Loganville'],
                ['state_id' => 50, 'city' => 'North Freedom'],
                ['state_id' => 50, 'city' => 'Reedsburg'],
                ['state_id' => 50, 'city' => 'Rock Springs'],
                ['state_id' => 50, 'city' => 'Couderay'],
                ['state_id' => 50, 'city' => 'Edgewater'],
                ['state_id' => 50, 'city' => 'Exeland'],
                ['state_id' => 50, 'city' => 'Hayward'],
                ['state_id' => 50, 'city' => 'Ojibwa'],
                ['state_id' => 50, 'city' => 'Radisson'],
                ['state_id' => 50, 'city' => 'Stone Lake'],
                ['state_id' => 50, 'city' => 'Winter'],
                ['state_id' => 50, 'city' => 'Bonduel'],
                ['state_id' => 50, 'city' => 'Cecil'],
                ['state_id' => 50, 'city' => 'Green Valley'],
                ['state_id' => 50, 'city' => 'Gresham'],
                ['state_id' => 50, 'city' => 'Krakow'],
                ['state_id' => 50, 'city' => 'Shawano'],
                ['state_id' => 50, 'city' => 'Zachow'],
                ['state_id' => 50, 'city' => 'Birnamwood'],
                ['state_id' => 50, 'city' => 'Bowler'],
                ['state_id' => 50, 'city' => 'Mattoon'],
                ['state_id' => 50, 'city' => 'Tigerton'],
                ['state_id' => 50, 'city' => 'Wittenberg'],
                ['state_id' => 50, 'city' => 'Caroline'],
                ['state_id' => 50, 'city' => 'Leopolis'],
                ['state_id' => 50, 'city' => 'Tilleda'],
                ['state_id' => 50, 'city' => 'Adell'],
                ['state_id' => 50, 'city' => 'Cascade'],
                ['state_id' => 50, 'city' => 'Cedar Grove'],
                ['state_id' => 50, 'city' => 'Elkhart Lake'],
                ['state_id' => 50, 'city' => 'Glenbeulah'],
                ['state_id' => 50, 'city' => 'Greenbush'],
                ['state_id' => 50, 'city' => 'Hingham'],
                ['state_id' => 50, 'city' => 'Kohler'],
                ['state_id' => 50, 'city' => 'Oostburg'],
                ['state_id' => 50, 'city' => 'Plymouth'],
                ['state_id' => 50, 'city' => 'Random Lake'],
                ['state_id' => 50, 'city' => 'Sheboygan'],
                ['state_id' => 50, 'city' => 'Sheboygan Falls'],
                ['state_id' => 50, 'city' => 'Waldo'],
                ['state_id' => 50, 'city' => 'Gilman'],
                ['state_id' => 50, 'city' => 'Jump River'],
                ['state_id' => 50, 'city' => 'Hannibal'],
                ['state_id' => 50, 'city' => 'Lublin'],
                ['state_id' => 50, 'city' => 'Medford'],
                ['state_id' => 50, 'city' => 'Rib Lake'],
                ['state_id' => 50, 'city' => 'Stetsonville'],
                ['state_id' => 50, 'city' => 'Westboro'],
                ['state_id' => 50, 'city' => 'Arcadia'],
                ['state_id' => 50, 'city' => 'Blair'],
                ['state_id' => 50, 'city' => 'Dodge'],
                ['state_id' => 50, 'city' => 'Ettrick'],
                ['state_id' => 50, 'city' => 'Galesville'],
                ['state_id' => 50, 'city' => 'Trempealeau'],
                ['state_id' => 50, 'city' => 'Eleva'],
                ['state_id' => 50, 'city' => 'Independence'],
                ['state_id' => 50, 'city' => 'Osseo'],
                ['state_id' => 50, 'city' => 'Pigeon Falls'],
                ['state_id' => 50, 'city' => 'Strum'],
                ['state_id' => 50, 'city' => 'Whitehall'],
                ['state_id' => 50, 'city' => 'Chaseburg'],
                ['state_id' => 50, 'city' => 'Coon Valley'],
                ['state_id' => 50, 'city' => 'De Soto'],
                ['state_id' => 50, 'city' => 'Genoa'],
                ['state_id' => 50, 'city' => 'Hillsboro'],
                ['state_id' => 50, 'city' => 'La Farge'],
                ['state_id' => 50, 'city' => 'Ontario'],
                ['state_id' => 50, 'city' => 'Readstown'],
                ['state_id' => 50, 'city' => 'Stoddard'],
                ['state_id' => 50, 'city' => 'Viola'],
                ['state_id' => 50, 'city' => 'Viroqua'],
                ['state_id' => 50, 'city' => 'Westby'],
                ['state_id' => 50, 'city' => 'Boulder Junction'],
                ['state_id' => 50, 'city' => 'Conover'],
                ['state_id' => 50, 'city' => 'Eagle River'],
                ['state_id' => 50, 'city' => 'Lac Du Flambeau'],
                ['state_id' => 50, 'city' => 'Land O Lakes'],
                ['state_id' => 50, 'city' => 'Manitowish Waters'],
                ['state_id' => 50, 'city' => 'Phelps'],
                ['state_id' => 50, 'city' => 'Presque Isle'],
                ['state_id' => 50, 'city' => 'Saint Germain'],
                ['state_id' => 50, 'city' => 'Sayner'],
                ['state_id' => 50, 'city' => 'Star Lake'],
                ['state_id' => 50, 'city' => 'Darien'],
                ['state_id' => 50, 'city' => 'Delavan'],
                ['state_id' => 50, 'city' => 'East Troy'],
                ['state_id' => 50, 'city' => 'Elkhorn'],
                ['state_id' => 50, 'city' => 'Fontana'],
                ['state_id' => 50, 'city' => 'Genoa City'],
                ['state_id' => 50, 'city' => 'Honey Creek'],
                ['state_id' => 50, 'city' => 'Lake Geneva'],
                ['state_id' => 50, 'city' => 'Lyons'],
                ['state_id' => 50, 'city' => 'Pell Lake'],
                ['state_id' => 50, 'city' => 'Springfield'],
                ['state_id' => 50, 'city' => 'Walworth'],
                ['state_id' => 50, 'city' => 'Whitewater'],
                ['state_id' => 50, 'city' => 'Williams Bay'],
                ['state_id' => 50, 'city' => 'Zenda'],
                ['state_id' => 50, 'city' => 'Sharon'],
                ['state_id' => 50, 'city' => 'Spooner'],
                ['state_id' => 50, 'city' => 'Birchwood'],
                ['state_id' => 50, 'city' => 'Minong'],
                ['state_id' => 50, 'city' => 'Sarona'],
                ['state_id' => 50, 'city' => 'Shell Lake'],
                ['state_id' => 50, 'city' => 'Springbrook'],
                ['state_id' => 50, 'city' => 'Trego'],
                ['state_id' => 50, 'city' => 'Allenton'],
                ['state_id' => 50, 'city' => 'Colgate'],
                ['state_id' => 50, 'city' => 'Germantown'],
                ['state_id' => 50, 'city' => 'Hartford'],
                ['state_id' => 50, 'city' => 'Hubertus'],
                ['state_id' => 50, 'city' => 'Jackson'],
                ['state_id' => 50, 'city' => 'Kewaskum'],
                ['state_id' => 50, 'city' => 'Newburg'],
                ['state_id' => 50, 'city' => 'Richfield'],
                ['state_id' => 50, 'city' => 'Slinger'],
                ['state_id' => 50, 'city' => 'West Bend'],
                ['state_id' => 50, 'city' => 'Brookfield'],
                ['state_id' => 50, 'city' => 'Butler'],
                ['state_id' => 50, 'city' => 'Delafield'],
                ['state_id' => 50, 'city' => 'Hartland'],
                ['state_id' => 50, 'city' => 'Lannon'],
                ['state_id' => 50, 'city' => 'Menomonee Falls'],
                ['state_id' => 50, 'city' => 'Merton'],
                ['state_id' => 50, 'city' => 'Nashotah'],
                ['state_id' => 50, 'city' => 'North Lake'],
                ['state_id' => 50, 'city' => 'Oconomowoc'],
                ['state_id' => 50, 'city' => 'Okauchee'],
                ['state_id' => 50, 'city' => 'Pewaukee'],
                ['state_id' => 50, 'city' => 'Sussex'],
                ['state_id' => 50, 'city' => 'Big Bend'],
                ['state_id' => 50, 'city' => 'Dousman'],
                ['state_id' => 50, 'city' => 'Eagle'],
                ['state_id' => 50, 'city' => 'Elm Grove'],
                ['state_id' => 50, 'city' => 'Genesee Depot'],
                ['state_id' => 50, 'city' => 'New Berlin'],
                ['state_id' => 50, 'city' => 'Mukwonago'],
                ['state_id' => 50, 'city' => 'Muskego'],
                ['state_id' => 50, 'city' => 'North Prairie'],
                ['state_id' => 50, 'city' => 'Wales'],
                ['state_id' => 50, 'city' => 'Waukesha'],
                ['state_id' => 50, 'city' => 'Big Falls'],
                ['state_id' => 50, 'city' => 'Clintonville'],
                ['state_id' => 50, 'city' => 'Embarrass'],
                ['state_id' => 50, 'city' => 'Fremont'],
                ['state_id' => 50, 'city' => 'Iola'],
                ['state_id' => 50, 'city' => 'King'],
                ['state_id' => 50, 'city' => 'Manawa'],
                ['state_id' => 50, 'city' => 'Marion'],
                ['state_id' => 50, 'city' => 'New London'],
                ['state_id' => 50, 'city' => 'Ogdensburg'],
                ['state_id' => 50, 'city' => 'Readfield'],
                ['state_id' => 50, 'city' => 'Scandinavia'],
                ['state_id' => 50, 'city' => 'Waupaca'],
                ['state_id' => 50, 'city' => 'Weyauwega'],
                ['state_id' => 50, 'city' => 'Coloma'],
                ['state_id' => 50, 'city' => 'Hancock'],
                ['state_id' => 50, 'city' => 'Pine River'],
                ['state_id' => 50, 'city' => 'Plainfield'],
                ['state_id' => 50, 'city' => 'Poy Sippi'],
                ['state_id' => 50, 'city' => 'Redgranite'],
                ['state_id' => 50, 'city' => 'Saxeville'],
                ['state_id' => 50, 'city' => 'Wautoma'],
                ['state_id' => 50, 'city' => 'Wild Rose'],
                ['state_id' => 50, 'city' => 'Oshkosh'],
                ['state_id' => 50, 'city' => 'Butte Des Morts'],
                ['state_id' => 50, 'city' => 'Eureka'],
                ['state_id' => 50, 'city' => 'Larsen'],
                ['state_id' => 50, 'city' => 'Menasha'],
                ['state_id' => 50, 'city' => 'Neenah'],
                ['state_id' => 50, 'city' => 'Omro'],
                ['state_id' => 50, 'city' => 'Pickett'],
                ['state_id' => 50, 'city' => 'Waukau'],
                ['state_id' => 50, 'city' => 'Winnebago'],
                ['state_id' => 50, 'city' => 'Winneconne'],
                ['state_id' => 50, 'city' => 'Marshfield'],
                ['state_id' => 50, 'city' => 'Arpin'],
                ['state_id' => 50, 'city' => 'Auburndale'],
                ['state_id' => 50, 'city' => 'Babcock'],
                ['state_id' => 50, 'city' => 'Blenker'],
                ['state_id' => 50, 'city' => 'Hewitt'],
                ['state_id' => 50, 'city' => 'Milladore'],
                ['state_id' => 50, 'city' => 'Nekoosa'],
                ['state_id' => 50, 'city' => 'Pittsville'],
                ['state_id' => 50, 'city' => 'Port Edwards'],
                ['state_id' => 50, 'city' => 'Rudolph'],
                ['state_id' => 50, 'city' => 'Vesper'],
                ['state_id' => 50, 'city' => 'Wisconsin Rapids', 'state_id' => 49]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
