<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State5TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of CA - California.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 5, 'city' => 'Alameda'],
                ['state_id' => 5, 'city' => 'Fremont'],
                ['state_id' => 5, 'city' => 'Hayward'],
                ['state_id' => 5, 'city' => 'Castro Valley'],
                ['state_id' => 5, 'city' => 'Livermore'],
                ['state_id' => 5, 'city' => 'Newark'],
                ['state_id' => 5, 'city' => 'Pleasanton'],
                ['state_id' => 5, 'city' => 'Dublin'],
                ['state_id' => 5, 'city' => 'San Leandro'],
                ['state_id' => 5, 'city' => 'San Lorenzo'],
                ['state_id' => 5, 'city' => 'Sunol'],
                ['state_id' => 5, 'city' => 'Union City'],
                ['state_id' => 5, 'city' => 'Oakland'],
                ['state_id' => 5, 'city' => 'Emeryville'],
                ['state_id' => 5, 'city' => 'Piedmont'],
                ['state_id' => 5, 'city' => 'Berkeley'],
                ['state_id' => 5, 'city' => 'Albany'],
                ['state_id' => 5, 'city' => 'Kirkwood'],
                ['state_id' => 5, 'city' => 'Markleeville'],
                ['state_id' => 5, 'city' => 'Amador City'],
                ['state_id' => 5, 'city' => 'Fiddletown'],
                ['state_id' => 5, 'city' => 'Ione'],
                ['state_id' => 5, 'city' => 'Jackson'],
                ['state_id' => 5, 'city' => 'Kit Carson'],
                ['state_id' => 5, 'city' => 'Martell'],
                ['state_id' => 5, 'city' => 'Pine Grove'],
                ['state_id' => 5, 'city' => 'Pioneer'],
                ['state_id' => 5, 'city' => 'Plymouth'],
                ['state_id' => 5, 'city' => 'River Pines'],
                ['state_id' => 5, 'city' => 'Sutter Creek'],
                ['state_id' => 5, 'city' => 'Volcano'],
                ['state_id' => 5, 'city' => 'Drytown'],
                ['state_id' => 5, 'city' => 'Bangor'],
                ['state_id' => 5, 'city' => 'Berry Creek'],
                ['state_id' => 5, 'city' => 'Biggs'],
                ['state_id' => 5, 'city' => 'Chico'],
                ['state_id' => 5, 'city' => 'Clipper Mills'],
                ['state_id' => 5, 'city' => 'Durham'],
                ['state_id' => 5, 'city' => 'Feather Falls'],
                ['state_id' => 5, 'city' => 'Forbestown'],
                ['state_id' => 5, 'city' => 'Forest Ranch'],
                ['state_id' => 5, 'city' => 'Gridley'],
                ['state_id' => 5, 'city' => 'Magalia'],
                ['state_id' => 5, 'city' => 'Nelson'],
                ['state_id' => 5, 'city' => 'Oroville'],
                ['state_id' => 5, 'city' => 'Paradise'],
                ['state_id' => 5, 'city' => 'Palermo'],
                ['state_id' => 5, 'city' => 'Richvale'],
                ['state_id' => 5, 'city' => 'Stirling City'],
                ['state_id' => 5, 'city' => 'Altaville'],
                ['state_id' => 5, 'city' => 'Angels Camp'],
                ['state_id' => 5, 'city' => 'Arnold'],
                ['state_id' => 5, 'city' => 'Avery'],
                ['state_id' => 5, 'city' => 'Burson'],
                ['state_id' => 5, 'city' => 'Campo Seco'],
                ['state_id' => 5, 'city' => 'Copperopolis'],
                ['state_id' => 5, 'city' => 'Douglas Flat'],
                ['state_id' => 5, 'city' => 'Glencoe'],
                ['state_id' => 5, 'city' => 'Hathaway Pines'],
                ['state_id' => 5, 'city' => 'Mokelumne Hill'],
                ['state_id' => 5, 'city' => 'Mountain Ranch'],
                ['state_id' => 5, 'city' => 'Murphys'],
                ['state_id' => 5, 'city' => 'Rail Road Flat'],
                ['state_id' => 5, 'city' => 'San Andreas'],
                ['state_id' => 5, 'city' => 'Vallecito'],
                ['state_id' => 5, 'city' => 'Valley Springs'],
                ['state_id' => 5, 'city' => 'Wallace'],
                ['state_id' => 5, 'city' => 'West Point'],
                ['state_id' => 5, 'city' => 'Wilseyville'],
                ['state_id' => 5, 'city' => 'Arbuckle'],
                ['state_id' => 5, 'city' => 'Colusa'],
                ['state_id' => 5, 'city' => 'Grimes'],
                ['state_id' => 5, 'city' => 'Maxwell'],
                ['state_id' => 5, 'city' => 'Princeton'],
                ['state_id' => 5, 'city' => 'Stonyford'],
                ['state_id' => 5, 'city' => 'Williams'],
                ['state_id' => 5, 'city' => 'Discovery Bay'],
                ['state_id' => 5, 'city' => 'Danville'],
                ['state_id' => 5, 'city' => 'Alamo'],
                ['state_id' => 5, 'city' => 'Antioch'],
                ['state_id' => 5, 'city' => 'Bethel Island'],
                ['state_id' => 5, 'city' => 'Brentwood'],
                ['state_id' => 5, 'city' => 'Byron'],
                ['state_id' => 5, 'city' => 'Canyon'],
                ['state_id' => 5, 'city' => 'Clayton'],
                ['state_id' => 5, 'city' => 'Concord'],
                ['state_id' => 5, 'city' => 'Pleasant Hill'],
                ['state_id' => 5, 'city' => 'Crockett'],
                ['state_id' => 5, 'city' => 'Diablo'],
                ['state_id' => 5, 'city' => 'El Cerrito'],
                ['state_id' => 5, 'city' => 'Hercules'],
                ['state_id' => 5, 'city' => 'Knightsen'],
                ['state_id' => 5, 'city' => 'Lafayette'],
                ['state_id' => 5, 'city' => 'Martinez'],
                ['state_id' => 5, 'city' => 'Moraga'],
                ['state_id' => 5, 'city' => 'Oakley'],
                ['state_id' => 5, 'city' => 'Orinda'],
                ['state_id' => 5, 'city' => 'Pinole'],
                ['state_id' => 5, 'city' => 'Pittsburg'],
                ['state_id' => 5, 'city' => 'Port Costa'],
                ['state_id' => 5, 'city' => 'Rodeo'],
                ['state_id' => 5, 'city' => 'San Ramon'],
                ['state_id' => 5, 'city' => 'Walnut Creek'],
                ['state_id' => 5, 'city' => 'Richmond'],
                ['state_id' => 5, 'city' => 'El Sobrante'],
                ['state_id' => 5, 'city' => 'San Pablo'],
                ['state_id' => 5, 'city' => 'Crescent City'],
                ['state_id' => 5, 'city' => 'Fort Dick'],
                ['state_id' => 5, 'city' => 'Gasquet'],
                ['state_id' => 5, 'city' => 'Klamath'],
                ['state_id' => 5, 'city' => 'Smith River'],
                ['state_id' => 5, 'city' => 'Coloma'],
                ['state_id' => 5, 'city' => 'Cool'],
                ['state_id' => 5, 'city' => 'Diamond Springs'],
                ['state_id' => 5, 'city' => 'El Dorado'],
                ['state_id' => 5, 'city' => 'Garden Valley'],
                ['state_id' => 5, 'city' => 'Georgetown'],
                ['state_id' => 5, 'city' => 'Greenwood'],
                ['state_id' => 5, 'city' => 'Grizzly Flats'],
                ['state_id' => 5, 'city' => 'Lotus'],
                ['state_id' => 5, 'city' => 'Mount Aukum'],
                ['state_id' => 5, 'city' => 'Pilot Hill'],
                ['state_id' => 5, 'city' => 'Placerville'],
                ['state_id' => 5, 'city' => 'Rescue'],
                ['state_id' => 5, 'city' => 'Shingle Springs'],
                ['state_id' => 5, 'city' => 'Somerset'],
                ['state_id' => 5, 'city' => 'Camino'],
                ['state_id' => 5, 'city' => 'Kyburz'],
                ['state_id' => 5, 'city' => 'Echo Lake'],
                ['state_id' => 5, 'city' => 'Pollock Pines'],
                ['state_id' => 5, 'city' => 'Twin Bridges'],
                ['state_id' => 5, 'city' => 'El Dorado Hills'],
                ['state_id' => 5, 'city' => 'Tahoma'],
                ['state_id' => 5, 'city' => 'South Lake Tahoe'],
                ['state_id' => 5, 'city' => 'Coalinga'],
                ['state_id' => 5, 'city' => 'Huron'],
                ['state_id' => 5, 'city' => 'Laton'],
                ['state_id' => 5, 'city' => 'Auberry'],
                ['state_id' => 5, 'city' => 'Big Creek'],
                ['state_id' => 5, 'city' => 'Biola'],
                ['state_id' => 5, 'city' => 'Burrel'],
                ['state_id' => 5, 'city' => 'Cantua Creek'],
                ['state_id' => 5, 'city' => 'Caruthers'],
                ['state_id' => 5, 'city' => 'Clovis'],
                ['state_id' => 5, 'city' => 'Del Rey'],
                ['state_id' => 5, 'city' => 'Dunlap'],
                ['state_id' => 5, 'city' => 'Firebaugh'],
                ['state_id' => 5, 'city' => 'Five Points'],
                ['state_id' => 5, 'city' => 'Fowler'],
                ['state_id' => 5, 'city' => 'Friant'],
                ['state_id' => 5, 'city' => 'Helm'],
                ['state_id' => 5, 'city' => 'Hume'],
                ['state_id' => 5, 'city' => 'Kerman'],
                ['state_id' => 5, 'city' => 'Kingsburg'],
                ['state_id' => 5, 'city' => 'Lakeshore'],
                ['state_id' => 5, 'city' => 'Mendota'],
                ['state_id' => 5, 'city' => 'Miramonte'],
                ['state_id' => 5, 'city' => 'Mono Hot Springs'],
                ['state_id' => 5, 'city' => 'Orange Cove'],
                ['state_id' => 5, 'city' => 'Parlier'],
                ['state_id' => 5, 'city' => 'Piedra'],
                ['state_id' => 5, 'city' => 'Fresno'],
                ['state_id' => 5, 'city' => 'Prather'],
                ['state_id' => 5, 'city' => 'Raisin City'],
                ['state_id' => 5, 'city' => 'Reedley'],
                ['state_id' => 5, 'city' => 'Riverdale'],
                ['state_id' => 5, 'city' => 'Sanger'],
                ['state_id' => 5, 'city' => 'San Joaquin'],
                ['state_id' => 5, 'city' => 'Selma'],
                ['state_id' => 5, 'city' => 'Shaver Lake'],
                ['state_id' => 5, 'city' => 'Tollhouse'],
                ['state_id' => 5, 'city' => 'Tranquillity'],
                ['state_id' => 5, 'city' => 'Squaw Valley'],
                ['state_id' => 5, 'city' => 'Artois'],
                ['state_id' => 5, 'city' => 'Butte City'],
                ['state_id' => 5, 'city' => 'Elk Creek'],
                ['state_id' => 5, 'city' => 'Glenn'],
                ['state_id' => 5, 'city' => 'Hamilton City'],
                ['state_id' => 5, 'city' => 'Orland'],
                ['state_id' => 5, 'city' => 'Willows'],
                ['state_id' => 5, 'city' => 'Eureka'],
                ['state_id' => 5, 'city' => 'Alderpoint'],
                ['state_id' => 5, 'city' => 'Blocksburg'],
                ['state_id' => 5, 'city' => 'Arcata'],
                ['state_id' => 5, 'city' => 'Mckinleyville'],
                ['state_id' => 5, 'city' => 'Bayside'],
                ['state_id' => 5, 'city' => 'Blue Lake'],
                ['state_id' => 5, 'city' => 'Bridgeville'],
                ['state_id' => 5, 'city' => 'Carlotta'],
                ['state_id' => 5, 'city' => 'Cutten'],
                ['state_id' => 5, 'city' => 'Ferndale'],
                ['state_id' => 5, 'city' => 'Fields Landing'],
                ['state_id' => 5, 'city' => 'Fortuna'],
                ['state_id' => 5, 'city' => 'Garberville'],
                ['state_id' => 5, 'city' => 'Honeydew'],
                ['state_id' => 5, 'city' => 'Hoopa'],
                ['state_id' => 5, 'city' => 'Hydesville'],
                ['state_id' => 5, 'city' => 'Kneeland'],
                ['state_id' => 5, 'city' => 'Korbel'],
                ['state_id' => 5, 'city' => 'Loleta'],
                ['state_id' => 5, 'city' => 'Miranda'],
                ['state_id' => 5, 'city' => 'Myers Flat'],
                ['state_id' => 5, 'city' => 'Orick'],
                ['state_id' => 5, 'city' => 'Orleans'],
                ['state_id' => 5, 'city' => 'Petrolia'],
                ['state_id' => 5, 'city' => 'Phillipsville'],
                ['state_id' => 5, 'city' => 'Redway'],
                ['state_id' => 5, 'city' => 'Rio Dell'],
                ['state_id' => 5, 'city' => 'Samoa'],
                ['state_id' => 5, 'city' => 'Scotia'],
                ['state_id' => 5, 'city' => 'Redcrest'],
                ['state_id' => 5, 'city' => 'Trinidad'],
                ['state_id' => 5, 'city' => 'Weott'],
                ['state_id' => 5, 'city' => 'Willow Creek'],
                ['state_id' => 5, 'city' => 'Whitethorn'],
                ['state_id' => 5, 'city' => 'Bard'],
                ['state_id' => 5, 'city' => 'Brawley'],
                ['state_id' => 5, 'city' => 'Calexico'],
                ['state_id' => 5, 'city' => 'Calipatria'],
                ['state_id' => 5, 'city' => 'El Centro'],
                ['state_id' => 5, 'city' => 'Heber'],
                ['state_id' => 5, 'city' => 'Holtville'],
                ['state_id' => 5, 'city' => 'Imperial'],
                ['state_id' => 5, 'city' => 'Niland'],
                ['state_id' => 5, 'city' => 'Ocotillo'],
                ['state_id' => 5, 'city' => 'Palo Verde'],
                ['state_id' => 5, 'city' => 'Seeley'],
                ['state_id' => 5, 'city' => 'Salton City'],
                ['state_id' => 5, 'city' => 'Westmorland'],
                ['state_id' => 5, 'city' => 'Winterhaven'],
                ['state_id' => 5, 'city' => 'Fontana'],
                ['state_id' => 5, 'city' => 'Death Valley'],
                ['state_id' => 5, 'city' => 'Shoshone'],
                ['state_id' => 5, 'city' => 'Tecopa'],
                ['state_id' => 5, 'city' => 'Big Pine'],
                ['state_id' => 5, 'city' => 'Bishop'],
                ['state_id' => 5, 'city' => 'Darwin'],
                ['state_id' => 5, 'city' => 'Independence'],
                ['state_id' => 5, 'city' => 'Keeler'],
                ['state_id' => 5, 'city' => 'Little Lake'],
                ['state_id' => 5, 'city' => 'Lone Pine'],
                ['state_id' => 5, 'city' => 'Olancha'],
                ['state_id' => 5, 'city' => 'Arvin'],
                ['state_id' => 5, 'city' => 'Bodfish'],
                ['state_id' => 5, 'city' => 'Buttonwillow'],
                ['state_id' => 5, 'city' => 'Delano'],
                ['state_id' => 5, 'city' => 'Edison'],
                ['state_id' => 5, 'city' => 'Pine Mountain Club'],
                ['state_id' => 5, 'city' => 'Fellows'],
                ['state_id' => 5, 'city' => 'Frazier Park'],
                ['state_id' => 5, 'city' => 'Glennville'],
                ['state_id' => 5, 'city' => 'Kernville'],
                ['state_id' => 5, 'city' => 'Lake Isabella'],
                ['state_id' => 5, 'city' => 'Lamont'],
                ['state_id' => 5, 'city' => 'Lebec'],
                ['state_id' => 5, 'city' => 'Lost Hills'],
                ['state_id' => 5, 'city' => 'Mc Farland'],
                ['state_id' => 5, 'city' => 'Mc Kittrick'],
                ['state_id' => 5, 'city' => 'Maricopa'],
                ['state_id' => 5, 'city' => 'Onyx'],
                ['state_id' => 5, 'city' => 'Shafter'],
                ['state_id' => 5, 'city' => 'Taft'],
                ['state_id' => 5, 'city' => 'Tupman'],
                ['state_id' => 5, 'city' => 'Wasco'],
                ['state_id' => 5, 'city' => 'Weldon'],
                ['state_id' => 5, 'city' => 'Wofford Heights'],
                ['state_id' => 5, 'city' => 'Woody'],
                ['state_id' => 5, 'city' => 'Bakersfield'],
                ['state_id' => 5, 'city' => 'Mojave'],
                ['state_id' => 5, 'city' => 'California City'],
                ['state_id' => 5, 'city' => 'Boron'],
                ['state_id' => 5, 'city' => 'Caliente'],
                ['state_id' => 5, 'city' => 'Cantil'],
                ['state_id' => 5, 'city' => 'Edwards'],
                ['state_id' => 5, 'city' => 'Inyokern'],
                ['state_id' => 5, 'city' => 'Johannesburg'],
                ['state_id' => 5, 'city' => 'Keene'],
                ['state_id' => 5, 'city' => 'Randsburg'],
                ['state_id' => 5, 'city' => 'Ridgecrest'],
                ['state_id' => 5, 'city' => 'Rosamond'],
                ['state_id' => 5, 'city' => 'Tehachapi'],
                ['state_id' => 5, 'city' => 'Armona'],
                ['state_id' => 5, 'city' => 'Avenal'],
                ['state_id' => 5, 'city' => 'Corcoran'],
                ['state_id' => 5, 'city' => 'Hanford'],
                ['state_id' => 5, 'city' => 'Kettleman City'],
                ['state_id' => 5, 'city' => 'Lemoore'],
                ['state_id' => 5, 'city' => 'Stratford'],
                ['state_id' => 5, 'city' => 'Clearlake'],
                ['state_id' => 5, 'city' => 'Clearlake Oaks'],
                ['state_id' => 5, 'city' => 'Clearlake Park'],
                ['state_id' => 5, 'city' => 'Cobb'],
                ['state_id' => 5, 'city' => 'Finley'],
                ['state_id' => 5, 'city' => 'Glenhaven'],
                ['state_id' => 5, 'city' => 'Kelseyville'],
                ['state_id' => 5, 'city' => 'Lakeport'],
                ['state_id' => 5, 'city' => 'Lower Lake'],
                ['state_id' => 5, 'city' => 'Lucerne'],
                ['state_id' => 5, 'city' => 'Middletown'],
                ['state_id' => 5, 'city' => 'Nice'],
                ['state_id' => 5, 'city' => 'Hidden Valley Lake'],
                ['state_id' => 5, 'city' => 'Upper Lake'],
                ['state_id' => 5, 'city' => 'Witter Springs'],
                ['state_id' => 5, 'city' => 'Bieber'],
                ['state_id' => 5, 'city' => 'Nubieber'],
                ['state_id' => 5, 'city' => 'Doyle'],
                ['state_id' => 5, 'city' => 'Herlong'],
                ['state_id' => 5, 'city' => 'Janesville'],
                ['state_id' => 5, 'city' => 'Litchfield'],
                ['state_id' => 5, 'city' => 'Madeline'],
                ['state_id' => 5, 'city' => 'Milford'],
                ['state_id' => 5, 'city' => 'Ravendale'],
                ['state_id' => 5, 'city' => 'Susanville'],
                ['state_id' => 5, 'city' => 'Standish'],
                ['state_id' => 5, 'city' => 'Termo'],
                ['state_id' => 5, 'city' => 'Wendel'],
                ['state_id' => 5, 'city' => 'Westwood'],
                ['state_id' => 5, 'city' => 'Los Angeles'],
                ['state_id' => 5, 'city' => 'West Hollywood'],
                ['state_id' => 5, 'city' => 'Dodgertown'],
                ['state_id' => 5, 'city' => 'Playa Vista'],
                ['state_id' => 5, 'city' => 'Bell Gardens'],
                ['state_id' => 5, 'city' => 'Bell'],
                ['state_id' => 5, 'city' => 'Beverly Hills'],
                ['state_id' => 5, 'city' => 'Compton'],
                ['state_id' => 5, 'city' => 'Culver City'],
                ['state_id' => 5, 'city' => 'Downey'],
                ['state_id' => 5, 'city' => 'El Segundo'],
                ['state_id' => 5, 'city' => 'Gardena'],
                ['state_id' => 5, 'city' => 'Hawthorne'],
                ['state_id' => 5, 'city' => 'Hermosa Beach'],
                ['state_id' => 5, 'city' => 'Huntington Park'],
                ['state_id' => 5, 'city' => 'Lawndale'],
                ['state_id' => 5, 'city' => 'Lynwood'],
                ['state_id' => 5, 'city' => 'Malibu'],
                ['state_id' => 5, 'city' => 'Manhattan Beach'],
                ['state_id' => 5, 'city' => 'Maywood'],
                ['state_id' => 5, 'city' => 'Pacific Palisades'],
                ['state_id' => 5, 'city' => 'Palos Verdes Peninsula'],
                ['state_id' => 5, 'city' => 'Rancho Palos Verdes'],
                ['state_id' => 5, 'city' => 'Redondo Beach'],
                ['state_id' => 5, 'city' => 'South Gate'],
                ['state_id' => 5, 'city' => 'Topanga'],
                ['state_id' => 5, 'city' => 'Venice'],
                ['state_id' => 5, 'city' => 'Marina Del Rey'],
                ['state_id' => 5, 'city' => 'Playa Del Rey'],
                ['state_id' => 5, 'city' => 'Inglewood'],
                ['state_id' => 5, 'city' => 'Santa Monica'],
                ['state_id' => 5, 'city' => 'Torrance'],
                ['state_id' => 5, 'city' => 'Whittier'],
                ['state_id' => 5, 'city' => 'La Mirada'],
                ['state_id' => 5, 'city' => 'Montebello'],
                ['state_id' => 5, 'city' => 'Norwalk'],
                ['state_id' => 5, 'city' => 'Pico Rivera'],
                ['state_id' => 5, 'city' => 'Santa Fe Springs'],
                ['state_id' => 5, 'city' => 'Artesia'],
                ['state_id' => 5, 'city' => 'Cerritos'],
                ['state_id' => 5, 'city' => 'Avalon'],
                ['state_id' => 5, 'city' => 'Bellflower'],
                ['state_id' => 5, 'city' => 'Harbor City'],
                ['state_id' => 5, 'city' => 'Lakewood'],
                ['state_id' => 5, 'city' => 'Hawaiian Gardens'],
                ['state_id' => 5, 'city' => 'Lomita'],
                ['state_id' => 5, 'city' => 'Paramount'],
                ['state_id' => 5, 'city' => 'San Pedro'],
                ['state_id' => 5, 'city' => 'Wilmington'],
                ['state_id' => 5, 'city' => 'Carson'],
                ['state_id' => 5, 'city' => 'Signal Hill'],
                ['state_id' => 5, 'city' => 'Long Beach'],
                ['state_id' => 5, 'city' => 'Altadena'],
                ['state_id' => 5, 'city' => 'Arcadia'],
                ['state_id' => 5, 'city' => 'Duarte'],
                ['state_id' => 5, 'city' => 'La Canada Flintridge'],
                ['state_id' => 5, 'city' => 'Monrovia'],
                ['state_id' => 5, 'city' => 'Montrose'],
                ['state_id' => 5, 'city' => 'Mount Wilson'],
                ['state_id' => 5, 'city' => 'Sierra Madre'],
                ['state_id' => 5, 'city' => 'South Pasadena'],
                ['state_id' => 5, 'city' => 'Sunland'],
                ['state_id' => 5, 'city' => 'Tujunga'],
                ['state_id' => 5, 'city' => 'Verdugo City'],
                ['state_id' => 5, 'city' => 'Pasadena'],
                ['state_id' => 5, 'city' => 'San Marino'],
                ['state_id' => 5, 'city' => 'Glendale'],
                ['state_id' => 5, 'city' => 'La Crescenta'],
                ['state_id' => 5, 'city' => 'Agoura Hills'],
                ['state_id' => 5, 'city' => 'Calabasas'],
                ['state_id' => 5, 'city' => 'Canoga Park'],
                ['state_id' => 5, 'city' => 'Winnetka'],
                ['state_id' => 5, 'city' => 'West Hills'],
                ['state_id' => 5, 'city' => 'Castaic'],
                ['state_id' => 5, 'city' => 'Chatsworth'],
                ['state_id' => 5, 'city' => 'Encino'],
                ['state_id' => 5, 'city' => 'Newhall'],
                ['state_id' => 5, 'city' => 'Northridge'],
                ['state_id' => 5, 'city' => 'Porter Ranch'],
                ['state_id' => 5, 'city' => 'Pacoima'],
                ['state_id' => 5, 'city' => 'Reseda'],
                ['state_id' => 5, 'city' => 'San Fernando'],
                ['state_id' => 5, 'city' => 'Sylmar'],
                ['state_id' => 5, 'city' => 'North Hills'],
                ['state_id' => 5, 'city' => 'Granada Hills'],
                ['state_id' => 5, 'city' => 'Mission Hills'],
                ['state_id' => 5, 'city' => 'Santa Clarita'],
                ['state_id' => 5, 'city' => 'Canyon Country'],
                ['state_id' => 5, 'city' => 'Sun Valley'],
                ['state_id' => 5, 'city' => 'Valencia'],
                ['state_id' => 5, 'city' => 'Tarzana'],
                ['state_id' => 5, 'city' => 'Woodland Hills'],
                ['state_id' => 5, 'city' => 'Stevenson Ranch'],
                ['state_id' => 5, 'city' => 'Van Nuys'],
                ['state_id' => 5, 'city' => 'Panorama City'],
                ['state_id' => 5, 'city' => 'Sherman Oaks'],
                ['state_id' => 5, 'city' => 'Burbank'],
                ['state_id' => 5, 'city' => 'North Hollywood'],
                ['state_id' => 5, 'city' => 'Studio City'],
                ['state_id' => 5, 'city' => 'Valley Village'],
                ['state_id' => 5, 'city' => 'Universal City'],
                ['state_id' => 5, 'city' => 'Toluca Lake'],
                ['state_id' => 5, 'city' => 'Azusa'],
                ['state_id' => 5, 'city' => 'Baldwin Park'],
                ['state_id' => 5, 'city' => 'Claremont'],
                ['state_id' => 5, 'city' => 'City Of Industry'],
                ['state_id' => 5, 'city' => 'Covina'],
                ['state_id' => 5, 'city' => 'El Monte'],
                ['state_id' => 5, 'city' => 'South El Monte'],
                ['state_id' => 5, 'city' => 'Glendora'],
                ['state_id' => 5, 'city' => 'La Puente'],
                ['state_id' => 5, 'city' => 'Hacienda Heights'],
                ['state_id' => 5, 'city' => 'Rowland Heights'],
                ['state_id' => 5, 'city' => 'La Verne'],
                ['state_id' => 5, 'city' => 'Monterey Park'],
                ['state_id' => 5, 'city' => 'Mt Baldy'],
                ['state_id' => 5, 'city' => 'Diamond Bar'],
                ['state_id' => 5, 'city' => 'Pomona'],
                ['state_id' => 5, 'city' => 'Rosemead'],
                ['state_id' => 5, 'city' => 'San Dimas'],
                ['state_id' => 5, 'city' => 'San Gabriel'],
                ['state_id' => 5, 'city' => 'Temple City'],
                ['state_id' => 5, 'city' => 'Walnut'],
                ['state_id' => 5, 'city' => 'West Covina'],
                ['state_id' => 5, 'city' => 'Alhambra'],
                ['state_id' => 5, 'city' => 'Acton'],
                ['state_id' => 5, 'city' => 'Lake Hughes'],
                ['state_id' => 5, 'city' => 'Lancaster'],
                ['state_id' => 5, 'city' => 'Littlerock'],
                ['state_id' => 5, 'city' => 'Llano'],
                ['state_id' => 5, 'city' => 'Palmdale'],
                ['state_id' => 5, 'city' => 'Pearblossom'],
                ['state_id' => 5, 'city' => 'Valyermo'],
                ['state_id' => 5, 'city' => 'Ahwahnee'],
                ['state_id' => 5, 'city' => 'Bass Lake'],
                ['state_id' => 5, 'city' => 'Chowchilla'],
                ['state_id' => 5, 'city' => 'Coarsegold'],
                ['state_id' => 5, 'city' => 'Madera'],
                ['state_id' => 5, 'city' => 'North Fork'],
                ['state_id' => 5, 'city' => 'Oakhurst'],
                ['state_id' => 5, 'city' => 'O Neals'],
                ['state_id' => 5, 'city' => 'Raymond'],
                ['state_id' => 5, 'city' => 'Wishon'],
                ['state_id' => 5, 'city' => 'San Rafael'],
                ['state_id' => 5, 'city' => 'Greenbrae'],
                ['state_id' => 5, 'city' => 'Kentfield'],
                ['state_id' => 5, 'city' => 'Belvedere Tiburon'],
                ['state_id' => 5, 'city' => 'Bolinas'],
                ['state_id' => 5, 'city' => 'Corte Madera'],
                ['state_id' => 5, 'city' => 'Dillon Beach'],
                ['state_id' => 5, 'city' => 'Fairfax'],
                ['state_id' => 5, 'city' => 'Forest Knolls'],
                ['state_id' => 5, 'city' => 'Inverness'],
                ['state_id' => 5, 'city' => 'Lagunitas'],
                ['state_id' => 5, 'city' => 'Larkspur'],
                ['state_id' => 5, 'city' => 'Marshall'],
                ['state_id' => 5, 'city' => 'Mill Valley'],
                ['state_id' => 5, 'city' => 'Novato'],
                ['state_id' => 5, 'city' => 'Nicasio'],
                ['state_id' => 5, 'city' => 'Olema'],
                ['state_id' => 5, 'city' => 'Point Reyes Station'],
                ['state_id' => 5, 'city' => 'Ross'],
                ['state_id' => 5, 'city' => 'San Anselmo'],
                ['state_id' => 5, 'city' => 'San Geronimo'],
                ['state_id' => 5, 'city' => 'San Quentin'],
                ['state_id' => 5, 'city' => 'Sausalito'],
                ['state_id' => 5, 'city' => 'Stinson Beach'],
                ['state_id' => 5, 'city' => 'Tomales'],
                ['state_id' => 5, 'city' => 'Woodacre'],
                ['state_id' => 5, 'city' => 'Fish Camp'],
                ['state_id' => 5, 'city' => 'Catheys Valley'],
                ['state_id' => 5, 'city' => 'Coulterville'],
                ['state_id' => 5, 'city' => 'El Portal'],
                ['state_id' => 5, 'city' => 'Hornitos'],
                ['state_id' => 5, 'city' => 'Mariposa'],
                ['state_id' => 5, 'city' => 'Midpines'],
                ['state_id' => 5, 'city' => 'Yosemite National Park'],
                ['state_id' => 5, 'city' => 'Albion'],
                ['state_id' => 5, 'city' => 'Boonville'],
                ['state_id' => 5, 'city' => 'Branscomb'],
                ['state_id' => 5, 'city' => 'Calpella'],
                ['state_id' => 5, 'city' => 'Caspar'],
                ['state_id' => 5, 'city' => 'Comptche'],
                ['state_id' => 5, 'city' => 'Covelo'],
                ['state_id' => 5, 'city' => 'Dos Rios'],
                ['state_id' => 5, 'city' => 'Elk'],
                ['state_id' => 5, 'city' => 'Fort Bragg'],
                ['state_id' => 5, 'city' => 'Gualala'],
                ['state_id' => 5, 'city' => 'Hopland'],
                ['state_id' => 5, 'city' => 'Laytonville'],
                ['state_id' => 5, 'city' => 'Little River'],
                ['state_id' => 5, 'city' => 'Manchester'],
                ['state_id' => 5, 'city' => 'Mendocino'],
                ['state_id' => 5, 'city' => 'Navarro'],
                ['state_id' => 5, 'city' => 'Philo'],
                ['state_id' => 5, 'city' => 'Point Arena'],
                ['state_id' => 5, 'city' => 'Potter Valley'],
                ['state_id' => 5, 'city' => 'Redwood Valley'],
                ['state_id' => 5, 'city' => 'Talmage'],
                ['state_id' => 5, 'city' => 'Ukiah'],
                ['state_id' => 5, 'city' => 'Westport'],
                ['state_id' => 5, 'city' => 'Willits'],
                ['state_id' => 5, 'city' => 'Yorkville'],
                ['state_id' => 5, 'city' => 'Leggett'],
                ['state_id' => 5, 'city' => 'Piercy'],
                ['state_id' => 5, 'city' => 'Dos Palos'],
                ['state_id' => 5, 'city' => 'Los Banos'],
                ['state_id' => 5, 'city' => 'Santa Rita Park'],
                ['state_id' => 5, 'city' => 'South Dos Palos'],
                ['state_id' => 5, 'city' => 'Atwater'],
                ['state_id' => 5, 'city' => 'Ballico'],
                ['state_id' => 5, 'city' => 'Cressey'],
                ['state_id' => 5, 'city' => 'Delhi'],
                ['state_id' => 5, 'city' => 'El Nido'],
                ['state_id' => 5, 'city' => 'Gustine'],
                ['state_id' => 5, 'city' => 'Hilmar'],
                ['state_id' => 5, 'city' => 'Le Grand'],
                ['state_id' => 5, 'city' => 'Livingston'],
                ['state_id' => 5, 'city' => 'Merced'],
                ['state_id' => 5, 'city' => 'Planada'],
                ['state_id' => 5, 'city' => 'Snelling'],
                ['state_id' => 5, 'city' => 'Stevinson'],
                ['state_id' => 5, 'city' => 'Winton'],
                ['state_id' => 5, 'city' => 'Adin'],
                ['state_id' => 5, 'city' => 'Canby'],
                ['state_id' => 5, 'city' => 'Lookout'],
                ['state_id' => 5, 'city' => 'Alturas'],
                ['state_id' => 5, 'city' => 'Cedarville'],
                ['state_id' => 5, 'city' => 'Davis Creek'],
                ['state_id' => 5, 'city' => 'Eagleville'],
                ['state_id' => 5, 'city' => 'Fort Bidwell'],
                ['state_id' => 5, 'city' => 'Lake City'],
                ['state_id' => 5, 'city' => 'Likely'],
                ['state_id' => 5, 'city' => 'Benton'],
                ['state_id' => 5, 'city' => 'Bridgeport'],
                ['state_id' => 5, 'city' => 'June Lake'],
                ['state_id' => 5, 'city' => 'Lee Vining'],
                ['state_id' => 5, 'city' => 'Mammoth Lakes'],
                ['state_id' => 5, 'city' => 'Coleville'],
                ['state_id' => 5, 'city' => 'Topaz'],
                ['state_id' => 5, 'city' => 'Bradley'],
                ['state_id' => 5, 'city' => 'San Ardo'],
                ['state_id' => 5, 'city' => 'Salinas'],
                ['state_id' => 5, 'city' => 'Big Sur'],
                ['state_id' => 5, 'city' => 'Carmel By The Sea'],
                ['state_id' => 5, 'city' => 'Carmel'],
                ['state_id' => 5, 'city' => 'Carmel Valley'],
                ['state_id' => 5, 'city' => 'Chualar'],
                ['state_id' => 5, 'city' => 'Gonzales'],
                ['state_id' => 5, 'city' => 'Greenfield'],
                ['state_id' => 5, 'city' => 'Jolon'],
                ['state_id' => 5, 'city' => 'King City'],
                ['state_id' => 5, 'city' => 'Lockwood'],
                ['state_id' => 5, 'city' => 'Marina'],
                ['state_id' => 5, 'city' => 'Monterey'],
                ['state_id' => 5, 'city' => 'Pacific Grove'],
                ['state_id' => 5, 'city' => 'Pebble Beach'],
                ['state_id' => 5, 'city' => 'San Lucas'],
                ['state_id' => 5, 'city' => 'Seaside'],
                ['state_id' => 5, 'city' => 'Soledad'],
                ['state_id' => 5, 'city' => 'Spreckels'],
                ['state_id' => 5, 'city' => 'Aromas'],
                ['state_id' => 5, 'city' => 'Castroville'],
                ['state_id' => 5, 'city' => 'Moss Landing'],
                ['state_id' => 5, 'city' => 'American Canyon'],
                ['state_id' => 5, 'city' => 'Angwin'],
                ['state_id' => 5, 'city' => 'Calistoga'],
                ['state_id' => 5, 'city' => 'Napa'],
                ['state_id' => 5, 'city' => 'Oakville'],
                ['state_id' => 5, 'city' => 'Pope Valley'],
                ['state_id' => 5, 'city' => 'Rutherford'],
                ['state_id' => 5, 'city' => 'Saint Helena'],
                ['state_id' => 5, 'city' => 'Deer Park'],
                ['state_id' => 5, 'city' => 'Yountville'],
                ['state_id' => 5, 'city' => 'Chicago Park'],
                ['state_id' => 5, 'city' => 'Norden'],
                ['state_id' => 5, 'city' => 'Soda Springs'],
                ['state_id' => 5, 'city' => 'Cedar Ridge'],
                ['state_id' => 5, 'city' => 'Grass Valley'],
                ['state_id' => 5, 'city' => 'Penn Valley'],
                ['state_id' => 5, 'city' => 'Nevada City'],
                ['state_id' => 5, 'city' => 'North San Juan'],
                ['state_id' => 5, 'city' => 'Rough And Ready'],
                ['state_id' => 5, 'city' => 'Smartsville'],
                ['state_id' => 5, 'city' => 'Washington'],
                ['state_id' => 5, 'city' => 'Floriston'],
                ['state_id' => 5, 'city' => 'Truckee'],
                ['state_id' => 5, 'city' => 'Buena Park'],
                ['state_id' => 5, 'city' => 'La Palma'],
                ['state_id' => 5, 'city' => 'Cypress'],
                ['state_id' => 5, 'city' => 'La Habra'],
                ['state_id' => 5, 'city' => 'Stanton'],
                ['state_id' => 5, 'city' => 'Los Alamitos'],
                ['state_id' => 5, 'city' => 'Seal Beach'],
                ['state_id' => 5, 'city' => 'Sunset Beach'],
                ['state_id' => 5, 'city' => 'Surfside'],
                ['state_id' => 5, 'city' => 'Irvine'],
                ['state_id' => 5, 'city' => 'Huntington Beach'],
                ['state_id' => 5, 'city' => 'Laguna Niguel'],
                ['state_id' => 5, 'city' => 'El Toro'],
                ['state_id' => 5, 'city' => 'Foothill Ranch'],
                ['state_id' => 5, 'city' => 'Capistrano Beach'],
                ['state_id' => 5, 'city' => 'Corona Del Mar'],
                ['state_id' => 5, 'city' => 'Costa Mesa'],
                ['state_id' => 5, 'city' => 'Dana Point'],
                ['state_id' => 5, 'city' => 'Lake Forest'],
                ['state_id' => 5, 'city' => 'Laguna Woods'],
                ['state_id' => 5, 'city' => 'East Irvine'],
                ['state_id' => 5, 'city' => 'Laguna Beach'],
                ['state_id' => 5, 'city' => 'Laguna Hills'],
                ['state_id' => 5, 'city' => 'Midway City'],
                ['state_id' => 5, 'city' => 'Aliso Viejo'],
                ['state_id' => 5, 'city' => 'Newport Coast'],
                ['state_id' => 5, 'city' => 'Newport Beach'],
                ['state_id' => 5, 'city' => 'San Clemente'],
                ['state_id' => 5, 'city' => 'San Juan Capistrano'],
                ['state_id' => 5, 'city' => 'Silverado'],
                ['state_id' => 5, 'city' => 'Trabuco Canyon'],
                ['state_id' => 5, 'city' => 'Westminster'],
                ['state_id' => 5, 'city' => 'Rancho Santa Margarita'],
                ['state_id' => 5, 'city' => 'Mission Viejo'],
                ['state_id' => 5, 'city' => 'Ladera Ranch'],
                ['state_id' => 5, 'city' => 'Santa Ana'],
                ['state_id' => 5, 'city' => 'Fountain Valley'],
                ['state_id' => 5, 'city' => 'Tustin'],
                ['state_id' => 5, 'city' => 'Anaheim'],
                ['state_id' => 5, 'city' => 'Atwood'],
                ['state_id' => 5, 'city' => 'Brea'],
                ['state_id' => 5, 'city' => 'Fullerton'],
                ['state_id' => 5, 'city' => 'Garden Grove'],
                ['state_id' => 5, 'city' => 'Orange'],
                ['state_id' => 5, 'city' => 'Villa Park'],
                ['state_id' => 5, 'city' => 'Placentia'],
                ['state_id' => 5, 'city' => 'Yorba Linda'],
                ['state_id' => 5, 'city' => 'Auburn'],
                ['state_id' => 5, 'city' => 'Foresthill'],
                ['state_id' => 5, 'city' => 'Lincoln'],
                ['state_id' => 5, 'city' => 'Loomis'],
                ['state_id' => 5, 'city' => 'Newcastle'],
                ['state_id' => 5, 'city' => 'Roseville'],
                ['state_id' => 5, 'city' => 'Penryn'],
                ['state_id' => 5, 'city' => 'Rocklin'],
                ['state_id' => 5, 'city' => 'Sheridan'],
                ['state_id' => 5, 'city' => 'Alta'],
                ['state_id' => 5, 'city' => 'Applegate'],
                ['state_id' => 5, 'city' => 'Colfax'],
                ['state_id' => 5, 'city' => 'Dutch Flat'],
                ['state_id' => 5, 'city' => 'Emigrant Gap'],
                ['state_id' => 5, 'city' => 'Gold Run'],
                ['state_id' => 5, 'city' => 'Meadow Vista'],
                ['state_id' => 5, 'city' => 'Weimar'],
                ['state_id' => 5, 'city' => 'Granite Bay'],
                ['state_id' => 5, 'city' => 'Carnelian Bay'],
                ['state_id' => 5, 'city' => 'Homewood'],
                ['state_id' => 5, 'city' => 'Kings Beach'],
                ['state_id' => 5, 'city' => 'Tahoe City'],
                ['state_id' => 5, 'city' => 'Olympic Valley'],
                ['state_id' => 5, 'city' => 'Tahoe Vista'],
                ['state_id' => 5, 'city' => 'Belden'],
                ['state_id' => 5, 'city' => 'Canyon Dam'],
                ['state_id' => 5, 'city' => 'Crescent Mills'],
                ['state_id' => 5, 'city' => 'Greenville'],
                ['state_id' => 5, 'city' => 'Meadow Valley'],
                ['state_id' => 5, 'city' => 'Quincy'],
                ['state_id' => 5, 'city' => 'Storrie'],
                ['state_id' => 5, 'city' => 'Taylorsville'],
                ['state_id' => 5, 'city' => 'Twain'],
                ['state_id' => 5, 'city' => 'Chester'],
                ['state_id' => 5, 'city' => 'Blairsden Graeagle'],
                ['state_id' => 5, 'city' => 'Chilcoot'],
                ['state_id' => 5, 'city' => 'Clio'],
                ['state_id' => 5, 'city' => 'Portola'],
                ['state_id' => 5, 'city' => 'Beckwourth'],
                ['state_id' => 5, 'city' => 'Vinton'],
                ['state_id' => 5, 'city' => 'Mira Loma'],
                ['state_id' => 5, 'city' => 'Indio'],
                ['state_id' => 5, 'city' => 'Indian Wells'],
                ['state_id' => 5, 'city' => 'Palm Desert'],
                ['state_id' => 5, 'city' => 'Banning'],
                ['state_id' => 5, 'city' => 'Beaumont'],
                ['state_id' => 5, 'city' => 'Blythe'],
                ['state_id' => 5, 'city' => 'Cabazon'],
                ['state_id' => 5, 'city' => 'Cathedral City'],
                ['state_id' => 5, 'city' => 'Coachella'],
                ['state_id' => 5, 'city' => 'Desert Center'],
                ['state_id' => 5, 'city' => 'Desert Hot Springs'],
                ['state_id' => 5, 'city' => 'La Quinta'],
                ['state_id' => 5, 'city' => 'Mecca'],
                ['state_id' => 5, 'city' => 'North Palm Springs'],
                ['state_id' => 5, 'city' => 'Palm Springs'],
                ['state_id' => 5, 'city' => 'Rancho Mirage'],
                ['state_id' => 5, 'city' => 'Thermal'],
                ['state_id' => 5, 'city' => 'Thousand Palms'],
                ['state_id' => 5, 'city' => 'Whitewater'],
                ['state_id' => 5, 'city' => 'Calimesa'],
                ['state_id' => 5, 'city' => 'Riverside'],
                ['state_id' => 5, 'city' => 'March Air Reserve Base'],
                ['state_id' => 5, 'city' => 'Lake Elsinore'],
                ['state_id' => 5, 'city' => 'Aguanga'],
                ['state_id' => 5, 'city' => 'Anza'],
                ['state_id' => 5, 'city' => 'Hemet'],
                ['state_id' => 5, 'city' => 'Homeland'],
                ['state_id' => 5, 'city' => 'Idyllwild'],
                ['state_id' => 5, 'city' => 'Moreno Valley'],
                ['state_id' => 5, 'city' => 'Mountain Center'],
                ['state_id' => 5, 'city' => 'Murrieta'],
                ['state_id' => 5, 'city' => 'Nuevo'],
                ['state_id' => 5, 'city' => 'Perris'],
                ['state_id' => 5, 'city' => 'San Jacinto'],
                ['state_id' => 5, 'city' => 'Menifee'],
                ['state_id' => 5, 'city' => 'Sun City'],
                ['state_id' => 5, 'city' => 'Quail Valley'],
                ['state_id' => 5, 'city' => 'Temecula'],
                ['state_id' => 5, 'city' => 'Wildomar'],
                ['state_id' => 5, 'city' => 'Winchester'],
                ['state_id' => 5, 'city' => 'Norco'],
                ['state_id' => 5, 'city' => 'Corona'],
                ['state_id' => 5, 'city' => 'Sacramento'],
                ['state_id' => 5, 'city' => 'Carmichael'],
                ['state_id' => 5, 'city' => 'Citrus Heights'],
                ['state_id' => 5, 'city' => 'Courtland'],
                ['state_id' => 5, 'city' => 'Elk Grove'],
                ['state_id' => 5, 'city' => 'Elverta'],
                ['state_id' => 5, 'city' => 'Fair Oaks'],
                ['state_id' => 5, 'city' => 'Folsom'],
                ['state_id' => 5, 'city' => 'Galt'],
                ['state_id' => 5, 'city' => 'Herald'],
                ['state_id' => 5, 'city' => 'Hood'],
                ['state_id' => 5, 'city' => 'Isleton'],
                ['state_id' => 5, 'city' => 'Mcclellan'],
                ['state_id' => 5, 'city' => 'Mather'],
                ['state_id' => 5, 'city' => 'North Highlands'],
                ['state_id' => 5, 'city' => 'Orangevale'],
                ['state_id' => 5, 'city' => 'Rancho Cordova'],
                ['state_id' => 5, 'city' => 'Represa'],
                ['state_id' => 5, 'city' => 'Rio Linda'],
                ['state_id' => 5, 'city' => 'Ryde'],
                ['state_id' => 5, 'city' => 'Sloughhouse'],
                ['state_id' => 5, 'city' => 'Walnut Grove'],
                ['state_id' => 5, 'city' => 'Wilton'],
                ['state_id' => 5, 'city' => 'Antelope'],
                ['state_id' => 5, 'city' => 'Hollister'],
                ['state_id' => 5, 'city' => 'Paicines'],
                ['state_id' => 5, 'city' => 'San Juan Bautista'],
                ['state_id' => 5, 'city' => 'Tres Pinos'],
                ['state_id' => 5, 'city' => 'Rancho Cucamonga'],
                ['state_id' => 5, 'city' => 'Chino'],
                ['state_id' => 5, 'city' => 'Chino Hills'],
                ['state_id' => 5, 'city' => 'Guasti'],
                ['state_id' => 5, 'city' => 'Ontario'],
                ['state_id' => 5, 'city' => 'Montclair'],
                ['state_id' => 5, 'city' => 'Upland'],
                ['state_id' => 5, 'city' => 'Earp'],
                ['state_id' => 5, 'city' => 'Joshua Tree'],
                ['state_id' => 5, 'city' => 'Morongo Valley'],
                ['state_id' => 5, 'city' => 'Parker Dam'],
                ['state_id' => 5, 'city' => 'Pioneertown'],
                ['state_id' => 5, 'city' => 'Twentynine Palms'],
                ['state_id' => 5, 'city' => 'Vidal'],
                ['state_id' => 5, 'city' => 'Yucca Valley'],
                ['state_id' => 5, 'city' => 'Landers'],
                ['state_id' => 5, 'city' => 'Adelanto'],
                ['state_id' => 5, 'city' => 'Amboy'],
                ['state_id' => 5, 'city' => 'Angelus Oaks'],
                ['state_id' => 5, 'city' => 'Apple Valley'],
                ['state_id' => 5, 'city' => 'Baker'],
                ['state_id' => 5, 'city' => 'Fort Irwin'],
                ['state_id' => 5, 'city' => 'Barstow'],
                ['state_id' => 5, 'city' => 'Grand Terrace'],
                ['state_id' => 5, 'city' => 'Big Bear City'],
                ['state_id' => 5, 'city' => 'Big Bear Lake'],
                ['state_id' => 5, 'city' => 'Bloomington'],
                ['state_id' => 5, 'city' => 'Blue Jay'],
                ['state_id' => 5, 'city' => 'Bryn Mawr'],
                ['state_id' => 5, 'city' => 'Cedar Glen'],
                ['state_id' => 5, 'city' => 'Cedarpines Park'],
                ['state_id' => 5, 'city' => 'Cima'],
                ['state_id' => 5, 'city' => 'Colton'],
                ['state_id' => 5, 'city' => 'Crestline'],
                ['state_id' => 5, 'city' => 'Daggett'],
                ['state_id' => 5, 'city' => 'Phelan'],
                ['state_id' => 5, 'city' => 'Essex'],
                ['state_id' => 5, 'city' => 'Fawnskin'],
                ['state_id' => 5, 'city' => 'Ludlow'],
                ['state_id' => 5, 'city' => 'Forest Falls'],
                ['state_id' => 5, 'city' => 'Hesperia'],
                ['state_id' => 5, 'city' => 'Green Valley Lake'],
                ['state_id' => 5, 'city' => 'Helendale'],
                ['state_id' => 5, 'city' => 'Highland'],
                ['state_id' => 5, 'city' => 'Hinkley'],
                ['state_id' => 5, 'city' => 'Loma Linda'],
                ['state_id' => 5, 'city' => 'Lake Arrowhead'],
                ['state_id' => 5, 'city' => 'Lucerne Valley'],
                ['state_id' => 5, 'city' => 'Lytle Creek'],
                ['state_id' => 5, 'city' => 'Mentone'],
                ['state_id' => 5, 'city' => 'Needles'],
                ['state_id' => 5, 'city' => 'Nipton'],
                ['state_id' => 5, 'city' => 'Newberry Springs'],
                ['state_id' => 5, 'city' => 'Mountain Pass'],
                ['state_id' => 5, 'city' => 'Oro Grande'],
                ['state_id' => 5, 'city' => 'Patton'],
                ['state_id' => 5, 'city' => 'Pinon Hills'],
                ['state_id' => 5, 'city' => 'Redlands'],
                ['state_id' => 5, 'city' => 'Rialto'],
                ['state_id' => 5, 'city' => 'Rimforest'],
                ['state_id' => 5, 'city' => 'Running Springs'],
                ['state_id' => 5, 'city' => 'Skyforest'],
                ['state_id' => 5, 'city' => 'Sugarloaf'],
                ['state_id' => 5, 'city' => 'Twin Peaks'],
                ['state_id' => 5, 'city' => 'Victorville'],
                ['state_id' => 5, 'city' => 'Wrightwood'],
                ['state_id' => 5, 'city' => 'Yermo'],
                ['state_id' => 5, 'city' => 'Yucaipa'],
                ['state_id' => 5, 'city' => 'San Bernardino'],
                ['state_id' => 5, 'city' => 'Red Mountain'],
                ['state_id' => 5, 'city' => 'Trona'],
                ['state_id' => 5, 'city' => 'Alpine'],
                ['state_id' => 5, 'city' => 'Bonita'],
                ['state_id' => 5, 'city' => 'Boulevard'],
                ['state_id' => 5, 'city' => 'Campo'],
                ['state_id' => 5, 'city' => 'Chula Vista'],
                ['state_id' => 5, 'city' => 'Descanso'],
                ['state_id' => 5, 'city' => 'Dulzura'],
                ['state_id' => 5, 'city' => 'Guatay'],
                ['state_id' => 5, 'city' => 'Imperial Beach'],
                ['state_id' => 5, 'city' => 'Jacumba'],
                ['state_id' => 5, 'city' => 'Jamul'],
                ['state_id' => 5, 'city' => 'La Mesa'],
                ['state_id' => 5, 'city' => 'Lemon Grove'],
                ['state_id' => 5, 'city' => 'Mount Laguna'],
                ['state_id' => 5, 'city' => 'National City'],
                ['state_id' => 5, 'city' => 'Pine Valley'],
                ['state_id' => 5, 'city' => 'Potrero'],
                ['state_id' => 5, 'city' => 'Spring Valley'],
                ['state_id' => 5, 'city' => 'Tecate'],
                ['state_id' => 5, 'city' => 'Bonsall'],
                ['state_id' => 5, 'city' => 'Borrego Springs'],
                ['state_id' => 5, 'city' => 'Cardiff By The Sea'],
                ['state_id' => 5, 'city' => 'Carlsbad'],
                ['state_id' => 5, 'city' => 'Del Mar'],
                ['state_id' => 5, 'city' => 'El Cajon'],
                ['state_id' => 5, 'city' => 'Encinitas'],
                ['state_id' => 5, 'city' => 'Escondido'],
                ['state_id' => 5, 'city' => 'Fallbrook'],
                ['state_id' => 5, 'city' => 'Julian'],
                ['state_id' => 5, 'city' => 'La Jolla'],
                ['state_id' => 5, 'city' => 'Lakeside'],
                ['state_id' => 5, 'city' => 'Oceanside'],
                ['state_id' => 5, 'city' => 'Camp Pendleton'],
                ['state_id' => 5, 'city' => 'Pala'],
                ['state_id' => 5, 'city' => 'Palomar Mountain'],
                ['state_id' => 5, 'city' => 'Pauma Valley'],
                ['state_id' => 5, 'city' => 'Poway'],
                ['state_id' => 5, 'city' => 'Ramona'],
                ['state_id' => 5, 'city' => 'Ranchita'],
                ['state_id' => 5, 'city' => 'Rancho Santa Fe'],
                ['state_id' => 5, 'city' => 'San Luis Rey'],
                ['state_id' => 5, 'city' => 'San Marcos'],
                ['state_id' => 5, 'city' => 'Santa Ysabel'],
                ['state_id' => 5, 'city' => 'Santee'],
                ['state_id' => 5, 'city' => 'Solana Beach'],
                ['state_id' => 5, 'city' => 'Vista'],
                ['state_id' => 5, 'city' => 'Valley Center'],
                ['state_id' => 5, 'city' => 'Warner Springs'],
                ['state_id' => 5, 'city' => 'San Diego'],
                ['state_id' => 5, 'city' => 'Coronado'],
                ['state_id' => 5, 'city' => 'San Ysidro'],
                ['state_id' => 5, 'city' => 'San Francisco'],
                ['state_id' => 5, 'city' => 'Stockton'],
                ['state_id' => 5, 'city' => 'Acampo'],
                ['state_id' => 5, 'city' => 'Clements'],
                ['state_id' => 5, 'city' => 'Farmington'],
                ['state_id' => 5, 'city' => 'French Camp'],
                ['state_id' => 5, 'city' => 'Holt'],
                ['state_id' => 5, 'city' => 'Linden'],
                ['state_id' => 5, 'city' => 'Lockeford'],
                ['state_id' => 5, 'city' => 'Lodi'],
                ['state_id' => 5, 'city' => 'Victor'],
                ['state_id' => 5, 'city' => 'Woodbridge'],
                ['state_id' => 5, 'city' => 'Tracy'],
                ['state_id' => 5, 'city' => 'Escalon'],
                ['state_id' => 5, 'city' => 'Lathrop'],
                ['state_id' => 5, 'city' => 'Manteca'],
                ['state_id' => 5, 'city' => 'Ripon'],
                ['state_id' => 5, 'city' => 'Vernalis'],
                ['state_id' => 5, 'city' => 'Thornton'],
                ['state_id' => 5, 'city' => 'San Luis Obispo'],
                ['state_id' => 5, 'city' => 'Los Osos'],
                ['state_id' => 5, 'city' => 'Arroyo Grande'],
                ['state_id' => 5, 'city' => 'Atascadero'],
                ['state_id' => 5, 'city' => 'Avila Beach'],
                ['state_id' => 5, 'city' => 'Cambria'],
                ['state_id' => 5, 'city' => 'Cayucos'],
                ['state_id' => 5, 'city' => 'Creston'],
                ['state_id' => 5, 'city' => 'Grover Beach'],
                ['state_id' => 5, 'city' => 'Harmony'],
                ['state_id' => 5, 'city' => 'Morro Bay'],
                ['state_id' => 5, 'city' => 'Nipomo'],
                ['state_id' => 5, 'city' => 'Oceano'],
                ['state_id' => 5, 'city' => 'Paso Robles'],
                ['state_id' => 5, 'city' => 'Pismo Beach'],
                ['state_id' => 5, 'city' => 'San Miguel'],
                ['state_id' => 5, 'city' => 'San Simeon'],
                ['state_id' => 5, 'city' => 'Santa Margarita'],
                ['state_id' => 5, 'city' => 'Shandon'],
                ['state_id' => 5, 'city' => 'Templeton'],
                ['state_id' => 5, 'city' => 'Belmont'],
                ['state_id' => 5, 'city' => 'Brisbane'],
                ['state_id' => 5, 'city' => 'Burlingame'],
                ['state_id' => 5, 'city' => 'Daly City'],
                ['state_id' => 5, 'city' => 'El Granada'],
                ['state_id' => 5, 'city' => 'Half Moon Bay'],
                ['state_id' => 5, 'city' => 'La Honda'],
                ['state_id' => 5, 'city' => 'Loma Mar'],
                ['state_id' => 5, 'city' => 'Menlo Park'],
                ['state_id' => 5, 'city' => 'Atherton'],
                ['state_id' => 5, 'city' => 'Portola Valley'],
                ['state_id' => 5, 'city' => 'Millbrae'],
                ['state_id' => 5, 'city' => 'Montara'],
                ['state_id' => 5, 'city' => 'Moss Beach'],
                ['state_id' => 5, 'city' => 'Pacifica'],
                ['state_id' => 5, 'city' => 'Pescadero'],
                ['state_id' => 5, 'city' => 'Redwood City'],
                ['state_id' => 5, 'city' => 'San Bruno'],
                ['state_id' => 5, 'city' => 'San Carlos'],
                ['state_id' => 5, 'city' => 'San Gregorio'],
                ['state_id' => 5, 'city' => 'South San Francisco'],
                ['state_id' => 5, 'city' => 'Palo Alto'],
                ['state_id' => 5, 'city' => 'San Mateo'],
                ['state_id' => 5, 'city' => 'Carpinteria'],
                ['state_id' => 5, 'city' => 'Summerland'],
                ['state_id' => 5, 'city' => 'Santa Barbara'],
                ['state_id' => 5, 'city' => 'Goleta'],
                ['state_id' => 5, 'city' => 'New Cuyama'],
                ['state_id' => 5, 'city' => 'Buellton'],
                ['state_id' => 5, 'city' => 'Casmalia'],
                ['state_id' => 5, 'city' => 'Guadalupe'],
                ['state_id' => 5, 'city' => 'Lompoc'],
                ['state_id' => 5, 'city' => 'Los Alamos'],
                ['state_id' => 5, 'city' => 'Los Olivos'],
                ['state_id' => 5, 'city' => 'Santa Maria'],
                ['state_id' => 5, 'city' => 'Santa Ynez'],
                ['state_id' => 5, 'city' => 'Solvang'],
                ['state_id' => 5, 'city' => 'Los Altos'],
                ['state_id' => 5, 'city' => 'Mountain View'],
                ['state_id' => 5, 'city' => 'Sunnyvale'],
                ['state_id' => 5, 'city' => 'Stanford'],
                ['state_id' => 5, 'city' => 'Alviso'],
                ['state_id' => 5, 'city' => 'Campbell'],
                ['state_id' => 5, 'city' => 'Coyote'],
                ['state_id' => 5, 'city' => 'Cupertino'],
                ['state_id' => 5, 'city' => 'Gilroy'],
                ['state_id' => 5, 'city' => 'Holy City'],
                ['state_id' => 5, 'city' => 'Los Gatos'],
                ['state_id' => 5, 'city' => 'Milpitas'],
                ['state_id' => 5, 'city' => 'Morgan Hill'],
                ['state_id' => 5, 'city' => 'New Almaden'],
                ['state_id' => 5, 'city' => 'Redwood Estates'],
                ['state_id' => 5, 'city' => 'San Martin'],
                ['state_id' => 5, 'city' => 'Santa Clara'],
                ['state_id' => 5, 'city' => 'Saratoga'],
                ['state_id' => 5, 'city' => 'San Jose'],
                ['state_id' => 5, 'city' => 'Mount Hamilton'],
                ['state_id' => 5, 'city' => 'Aptos'],
                ['state_id' => 5, 'city' => 'Ben Lomond'],
                ['state_id' => 5, 'city' => 'Boulder Creek'],
                ['state_id' => 5, 'city' => 'Brookdale'],
                ['state_id' => 5, 'city' => 'Capitola'],
                ['state_id' => 5, 'city' => 'Davenport'],
                ['state_id' => 5, 'city' => 'Felton'],
                ['state_id' => 5, 'city' => 'Freedom'],
                ['state_id' => 5, 'city' => 'Mount Hermon'],
                ['state_id' => 5, 'city' => 'Santa Cruz'],
                ['state_id' => 5, 'city' => 'Scotts Valley'],
                ['state_id' => 5, 'city' => 'Soquel'],
                ['state_id' => 5, 'city' => 'Watsonville'],
                ['state_id' => 5, 'city' => 'Redding'],
                ['state_id' => 5, 'city' => 'Anderson'],
                ['state_id' => 5, 'city' => 'Bella Vista'],
                ['state_id' => 5, 'city' => 'Big Bend'],
                ['state_id' => 5, 'city' => 'Burney'],
                ['state_id' => 5, 'city' => 'Cassel'],
                ['state_id' => 5, 'city' => 'Castella'],
                ['state_id' => 5, 'city' => 'Shasta Lake'],
                ['state_id' => 5, 'city' => 'Cottonwood'],
                ['state_id' => 5, 'city' => 'Fall River Mills'],
                ['state_id' => 5, 'city' => 'French Gulch'],
                ['state_id' => 5, 'city' => 'Hat Creek'],
                ['state_id' => 5, 'city' => 'Igo'],
                ['state_id' => 5, 'city' => 'Lakehead'],
                ['state_id' => 5, 'city' => 'Mcarthur'],
                ['state_id' => 5, 'city' => 'Millville'],
                ['state_id' => 5, 'city' => 'Montgomery Creek'],
                ['state_id' => 5, 'city' => 'Oak Run'],
                ['state_id' => 5, 'city' => 'Obrien'],
                ['state_id' => 5, 'city' => 'Old Station'],
                ['state_id' => 5, 'city' => 'Palo Cedro'],
                ['state_id' => 5, 'city' => 'Platina'],
                ['state_id' => 5, 'city' => 'Round Mountain'],
                ['state_id' => 5, 'city' => 'Shasta'],
                ['state_id' => 5, 'city' => 'Shingletown'],
                ['state_id' => 5, 'city' => 'Whiskeytown'],
                ['state_id' => 5, 'city' => 'Whitmore'],
                ['state_id' => 5, 'city' => 'Alleghany'],
                ['state_id' => 5, 'city' => 'Downieville'],
                ['state_id' => 5, 'city' => 'Goodyears Bar'],
                ['state_id' => 5, 'city' => 'Loyalton'],
                ['state_id' => 5, 'city' => 'Calpine'],
                ['state_id' => 5, 'city' => 'Sierra City'],
                ['state_id' => 5, 'city' => 'Sierraville'],
                ['state_id' => 5, 'city' => 'Somes Bar'],
                ['state_id' => 5, 'city' => 'Callahan'],
                ['state_id' => 5, 'city' => 'Dorris'],
                ['state_id' => 5, 'city' => 'Dunsmuir'],
                ['state_id' => 5, 'city' => 'Etna'],
                ['state_id' => 5, 'city' => 'Forks Of Salmon'],
                ['state_id' => 5, 'city' => 'Fort Jones'],
                ['state_id' => 5, 'city' => 'Gazelle'],
                ['state_id' => 5, 'city' => 'Greenview'],
                ['state_id' => 5, 'city' => 'Grenada'],
                ['state_id' => 5, 'city' => 'Happy Camp'],
                ['state_id' => 5, 'city' => 'Hornbrook'],
                ['state_id' => 5, 'city' => 'Klamath River'],
                ['state_id' => 5, 'city' => 'Mccloud'],
                ['state_id' => 5, 'city' => 'Macdoel'],
                ['state_id' => 5, 'city' => 'Montague'],
                ['state_id' => 5, 'city' => 'Mount Shasta'],
                ['state_id' => 5, 'city' => 'Scott Bar'],
                ['state_id' => 5, 'city' => 'Seiad Valley'],
                ['state_id' => 5, 'city' => 'Weed'],
                ['state_id' => 5, 'city' => 'Yreka'],
                ['state_id' => 5, 'city' => 'Tulelake'],
                ['state_id' => 5, 'city' => 'Benicia'],
                ['state_id' => 5, 'city' => 'Birds Landing'],
                ['state_id' => 5, 'city' => 'Fairfield'],
                ['state_id' => 5, 'city' => 'Travis Afb'],
                ['state_id' => 5, 'city' => 'Rio Vista'],
                ['state_id' => 5, 'city' => 'Suisun City'],
                ['state_id' => 5, 'city' => 'Vallejo'],
                ['state_id' => 5, 'city' => 'Dixon'],
                ['state_id' => 5, 'city' => 'Elmira'],
                ['state_id' => 5, 'city' => 'Vacaville'],
                ['state_id' => 5, 'city' => 'Bodega'],
                ['state_id' => 5, 'city' => 'Bodega Bay'],
                ['state_id' => 5, 'city' => 'Rohnert Park'],
                ['state_id' => 5, 'city' => 'Cotati'],
                ['state_id' => 5, 'city' => 'Penngrove'],
                ['state_id' => 5, 'city' => 'Petaluma'],
                ['state_id' => 5, 'city' => 'Valley Ford'],
                ['state_id' => 5, 'city' => 'Santa Rosa'],
                ['state_id' => 5, 'city' => 'Annapolis'],
                ['state_id' => 5, 'city' => 'Boyes Hot Springs'],
                ['state_id' => 5, 'city' => 'Camp Meeker'],
                ['state_id' => 5, 'city' => 'Cazadero'],
                ['state_id' => 5, 'city' => 'Cloverdale'],
                ['state_id' => 5, 'city' => 'Duncans Mills'],
                ['state_id' => 5, 'city' => 'Eldridge'],
                ['state_id' => 5, 'city' => 'El Verano'],
                ['state_id' => 5, 'city' => 'Forestville'],
                ['state_id' => 5, 'city' => 'Fulton'],
                ['state_id' => 5, 'city' => 'Geyserville'],
                ['state_id' => 5, 'city' => 'Glen Ellen'],
                ['state_id' => 5, 'city' => 'Graton'],
                ['state_id' => 5, 'city' => 'Guerneville'],
                ['state_id' => 5, 'city' => 'Healdsburg'],
                ['state_id' => 5, 'city' => 'Jenner'],
                ['state_id' => 5, 'city' => 'Kenwood'],
                ['state_id' => 5, 'city' => 'Monte Rio'],
                ['state_id' => 5, 'city' => 'Occidental'],
                ['state_id' => 5, 'city' => 'Rio Nido'],
                ['state_id' => 5, 'city' => 'Sebastopol'],
                ['state_id' => 5, 'city' => 'Sonoma'],
                ['state_id' => 5, 'city' => 'Stewarts Point'],
                ['state_id' => 5, 'city' => 'Villa Grande'],
                ['state_id' => 5, 'city' => 'Vineburg'],
                ['state_id' => 5, 'city' => 'Windsor'],
                ['state_id' => 5, 'city' => 'The Sea Ranch'],
                ['state_id' => 5, 'city' => 'Ceres'],
                ['state_id' => 5, 'city' => 'Crows Landing'],
                ['state_id' => 5, 'city' => 'Denair'],
                ['state_id' => 5, 'city' => 'Empire'],
                ['state_id' => 5, 'city' => 'Hickman'],
                ['state_id' => 5, 'city' => 'Hughson'],
                ['state_id' => 5, 'city' => 'Keyes'],
                ['state_id' => 5, 'city' => 'La Grange'],
                ['state_id' => 5, 'city' => 'Modesto'],
                ['state_id' => 5, 'city' => 'Newman'],
                ['state_id' => 5, 'city' => 'Oakdale'],
                ['state_id' => 5, 'city' => 'Patterson'],
                ['state_id' => 5, 'city' => 'Riverbank'],
                ['state_id' => 5, 'city' => 'Salida'],
                ['state_id' => 5, 'city' => 'Turlock'],
                ['state_id' => 5, 'city' => 'Waterford'],
                ['state_id' => 5, 'city' => 'Westley'],
                ['state_id' => 5, 'city' => 'Nicolaus'],
                ['state_id' => 5, 'city' => 'Pleasant Grove'],
                ['state_id' => 5, 'city' => 'Rio Oso'],
                ['state_id' => 5, 'city' => 'Robbins'],
                ['state_id' => 5, 'city' => 'Live Oak'],
                ['state_id' => 5, 'city' => 'Meridian'],
                ['state_id' => 5, 'city' => 'Sutter'],
                ['state_id' => 5, 'city' => 'Yuba City'],
                ['state_id' => 5, 'city' => 'Corning'],
                ['state_id' => 5, 'city' => 'Flournoy'],
                ['state_id' => 5, 'city' => 'Gerber'],
                ['state_id' => 5, 'city' => 'Los Molinos'],
                ['state_id' => 5, 'city' => 'Manton'],
                ['state_id' => 5, 'city' => 'Mill Creek'],
                ['state_id' => 5, 'city' => 'Mineral'],
                ['state_id' => 5, 'city' => 'Paskenta'],
                ['state_id' => 5, 'city' => 'Paynes Creek'],
                ['state_id' => 5, 'city' => 'Proberta'],
                ['state_id' => 5, 'city' => 'Red Bluff'],
                ['state_id' => 5, 'city' => 'Tehama'],
                ['state_id' => 5, 'city' => 'Vina'],
                ['state_id' => 5, 'city' => 'Burnt Ranch'],
                ['state_id' => 5, 'city' => 'Mad River'],
                ['state_id' => 5, 'city' => 'Salyer'],
                ['state_id' => 5, 'city' => 'Zenia'],
                ['state_id' => 5, 'city' => 'Big Bar'],
                ['state_id' => 5, 'city' => 'Douglas City'],
                ['state_id' => 5, 'city' => 'Hayfork'],
                ['state_id' => 5, 'city' => 'Hyampom'],
                ['state_id' => 5, 'city' => 'Junction City'],
                ['state_id' => 5, 'city' => 'Lewiston'],
                ['state_id' => 5, 'city' => 'Trinity Center'],
                ['state_id' => 5, 'city' => 'Weaverville'],
                ['state_id' => 5, 'city' => 'Alpaugh'],
                ['state_id' => 5, 'city' => 'California Hot Springs'],
                ['state_id' => 5, 'city' => 'Camp Nelson'],
                ['state_id' => 5, 'city' => 'Ducor'],
                ['state_id' => 5, 'city' => 'Earlimart'],
                ['state_id' => 5, 'city' => 'Exeter'],
                ['state_id' => 5, 'city' => 'Farmersville'],
                ['state_id' => 5, 'city' => 'Goshen'],
                ['state_id' => 5, 'city' => 'Ivanhoe'],
                ['state_id' => 5, 'city' => 'Kaweah'],
                ['state_id' => 5, 'city' => 'Lemon Cove'],
                ['state_id' => 5, 'city' => 'Lindsay'],
                ['state_id' => 5, 'city' => 'Pixley'],
                ['state_id' => 5, 'city' => 'Porterville'],
                ['state_id' => 5, 'city' => 'Posey'],
                ['state_id' => 5, 'city' => 'Richgrove'],
                ['state_id' => 5, 'city' => 'Sequoia National Park'],
                ['state_id' => 5, 'city' => 'Springville'],
                ['state_id' => 5, 'city' => 'Strathmore'],
                ['state_id' => 5, 'city' => 'Terra Bella'],
                ['state_id' => 5, 'city' => 'Three Rivers'],
                ['state_id' => 5, 'city' => 'Tipton'],
                ['state_id' => 5, 'city' => 'Tulare'],
                ['state_id' => 5, 'city' => 'Visalia'],
                ['state_id' => 5, 'city' => 'Waukena'],
                ['state_id' => 5, 'city' => 'Woodlake'],
                ['state_id' => 5, 'city' => 'Badger'],
                ['state_id' => 5, 'city' => 'Cutler'],
                ['state_id' => 5, 'city' => 'Dinuba'],
                ['state_id' => 5, 'city' => 'Kings Canyon National Pk'],
                ['state_id' => 5, 'city' => 'Orosi'],
                ['state_id' => 5, 'city' => 'Sultana'],
                ['state_id' => 5, 'city' => 'Yettem'],
                ['state_id' => 5, 'city' => 'Traver'],
                ['state_id' => 5, 'city' => 'Big Oak Flat'],
                ['state_id' => 5, 'city' => 'Chinese Camp'],
                ['state_id' => 5, 'city' => 'Columbia'],
                ['state_id' => 5, 'city' => 'Groveland'],
                ['state_id' => 5, 'city' => 'Jamestown'],
                ['state_id' => 5, 'city' => 'Long Barn'],
                ['state_id' => 5, 'city' => 'Mi Wuk Village'],
                ['state_id' => 5, 'city' => 'Moccasin'],
                ['state_id' => 5, 'city' => 'Pinecrest'],
                ['state_id' => 5, 'city' => 'Sonora'],
                ['state_id' => 5, 'city' => 'Soulsbyville'],
                ['state_id' => 5, 'city' => 'Standard'],
                ['state_id' => 5, 'city' => 'Strawberry'],
                ['state_id' => 5, 'city' => 'Tuolumne'],
                ['state_id' => 5, 'city' => 'Twain Harte'],
                ['state_id' => 5, 'city' => 'Newbury Park'],
                ['state_id' => 5, 'city' => 'Thousand Oaks'],
                ['state_id' => 5, 'city' => 'Westlake Village'],
                ['state_id' => 5, 'city' => 'Oak Park'],
                ['state_id' => 5, 'city' => 'Ventura'],
                ['state_id' => 5, 'city' => 'Camarillo'],
                ['state_id' => 5, 'city' => 'Fillmore'],
                ['state_id' => 5, 'city' => 'Moorpark'],
                ['state_id' => 5, 'city' => 'Oak View'],
                ['state_id' => 5, 'city' => 'Ojai'],
                ['state_id' => 5, 'city' => 'Oxnard'],
                ['state_id' => 5, 'city' => 'Piru'],
                ['state_id' => 5, 'city' => 'Port Hueneme'],
                ['state_id' => 5, 'city' => 'Point Mugu Nawc'],
                ['state_id' => 5, 'city' => 'Port Hueneme Cbc Base'],
                ['state_id' => 5, 'city' => 'Santa Paula'],
                ['state_id' => 5, 'city' => 'Simi Valley'],
                ['state_id' => 5, 'city' => 'Brandeis'],
                ['state_id' => 5, 'city' => 'Somis'],
                ['state_id' => 5, 'city' => 'West Sacramento'],
                ['state_id' => 5, 'city' => 'Brooks'],
                ['state_id' => 5, 'city' => 'Capay'],
                ['state_id' => 5, 'city' => 'Clarksburg'],
                ['state_id' => 5, 'city' => 'Davis'],
                ['state_id' => 5, 'city' => 'Esparto'],
                ['state_id' => 5, 'city' => 'Guinda'],
                ['state_id' => 5, 'city' => 'Knights Landing'],
                ['state_id' => 5, 'city' => 'Madison'],
                ['state_id' => 5, 'city' => 'Rumsey'],
                ['state_id' => 5, 'city' => 'Winters'],
                ['state_id' => 5, 'city' => 'Woodland'],
                ['state_id' => 5, 'city' => 'Yolo'],
                ['state_id' => 5, 'city' => 'Zamora'],
                ['state_id' => 5, 'city' => 'Dunnigan'],
                ['state_id' => 5, 'city' => 'Wheatland'],
                ['state_id' => 5, 'city' => 'Marysville'],
                ['state_id' => 5, 'city' => 'Beale Afb'],
                ['state_id' => 5, 'city' => 'Browns Valley'],
                ['state_id' => 5, 'city' => 'Brownsville'],
                ['state_id' => 5, 'city' => 'Camptonville'],
                ['state_id' => 5, 'city' => 'Challenge'],
                ['state_id' => 5, 'city' => 'Dobbins'],
                ['state_id' => 5, 'city' => 'Olivehurst'],
                ['state_id' => 5, 'city' => 'Oregon House'],
                ['state_id' => 5, 'city' => 'Rackerby'],
                ['state_id' => 5, 'city' => 'Strawberry Valley']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
