<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State30TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of NH - New Hampshire.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 30, 'city' => 'Barnstead'],
                ['state_id' => 30, 'city' => 'Belmont'],
                ['state_id' => 30, 'city' => 'Center Barnstead'],
                ['state_id' => 30, 'city' => 'Center Harbor'],
                ['state_id' => 30, 'city' => 'Gilmanton'],
                ['state_id' => 30, 'city' => 'Laconia'],
                ['state_id' => 30, 'city' => 'Gilford'],
                ['state_id' => 30, 'city' => 'Lochmere'],
                ['state_id' => 30, 'city' => 'Meredith'],
                ['state_id' => 30, 'city' => 'New Hampton'],
                ['state_id' => 30, 'city' => 'Sanbornton'],
                ['state_id' => 30, 'city' => 'Tilton'],
                ['state_id' => 30, 'city' => 'Winnisquam'],
                ['state_id' => 30, 'city' => 'Alton'],
                ['state_id' => 30, 'city' => 'Alton Bay'],
                ['state_id' => 30, 'city' => 'Gilmanton Iron Works'],
                ['state_id' => 30, 'city' => 'Center Sandwich'],
                ['state_id' => 30, 'city' => 'Moultonborough'],
                ['state_id' => 30, 'city' => 'North Sandwich'],
                ['state_id' => 30, 'city' => 'Bartlett'],
                ['state_id' => 30, 'city' => 'Center Conway'],
                ['state_id' => 30, 'city' => 'Center Ossipee'],
                ['state_id' => 30, 'city' => 'Center Tuftonboro'],
                ['state_id' => 30, 'city' => 'Chocorua'],
                ['state_id' => 30, 'city' => 'Conway'],
                ['state_id' => 30, 'city' => 'East Wakefield'],
                ['state_id' => 30, 'city' => 'Eaton Center'],
                ['state_id' => 30, 'city' => 'Freedom'],
                ['state_id' => 30, 'city' => 'Glen'],
                ['state_id' => 30, 'city' => 'Intervale'],
                ['state_id' => 30, 'city' => 'Jackson'],
                ['state_id' => 30, 'city' => 'Kearsarge'],
                ['state_id' => 30, 'city' => 'Madison'],
                ['state_id' => 30, 'city' => 'Melvin Village'],
                ['state_id' => 30, 'city' => 'Mirror Lake'],
                ['state_id' => 30, 'city' => 'North Conway'],
                ['state_id' => 30, 'city' => 'Lee'],
                ['state_id' => 30, 'city' => 'Ossipee'],
                ['state_id' => 30, 'city' => 'Sanbornville'],
                ['state_id' => 30, 'city' => 'Silver Lake'],
                ['state_id' => 30, 'city' => 'Effingham'],
                ['state_id' => 30, 'city' => 'South Tamworth'],
                ['state_id' => 30, 'city' => 'Tamworth'],
                ['state_id' => 30, 'city' => 'West Ossipee'],
                ['state_id' => 30, 'city' => 'Wolfeboro'],
                ['state_id' => 30, 'city' => 'Wolfeboro Falls'],
                ['state_id' => 30, 'city' => 'Wonalancet'],
                ['state_id' => 30, 'city' => 'Keene'],
                ['state_id' => 30, 'city' => 'Ashuelot'],
                ['state_id' => 30, 'city' => 'Chesterfield'],
                ['state_id' => 30, 'city' => 'Dublin'],
                ['state_id' => 30, 'city' => 'Sullivan'],
                ['state_id' => 30, 'city' => 'Swanzey'],
                ['state_id' => 30, 'city' => 'Fitzwilliam'],
                ['state_id' => 30, 'city' => 'Gilsum'],
                ['state_id' => 30, 'city' => 'Harrisville'],
                ['state_id' => 30, 'city' => 'Hinsdale'],
                ['state_id' => 30, 'city' => 'Jaffrey'],
                ['state_id' => 30, 'city' => 'Marlborough'],
                ['state_id' => 30, 'city' => 'Marlow'],
                ['state_id' => 30, 'city' => 'Nelson'],
                ['state_id' => 30, 'city' => 'Rindge'],
                ['state_id' => 30, 'city' => 'Spofford'],
                ['state_id' => 30, 'city' => 'Stoddard'],
                ['state_id' => 30, 'city' => 'Troy'],
                ['state_id' => 30, 'city' => 'West Chesterfield'],
                ['state_id' => 30, 'city' => 'Westmoreland'],
                ['state_id' => 30, 'city' => 'West Swanzey'],
                ['state_id' => 30, 'city' => 'Winchester'],
                ['state_id' => 30, 'city' => 'Alstead'],
                ['state_id' => 30, 'city' => 'Drewsville'],
                ['state_id' => 30, 'city' => 'Walpole'],
                ['state_id' => 30, 'city' => 'North Walpole'],
                ['state_id' => 30, 'city' => 'Berlin'],
                ['state_id' => 30, 'city' => 'Bretton Woods'],
                ['state_id' => 30, 'city' => 'Colebrook'],
                ['state_id' => 30, 'city' => 'Errol'],
                ['state_id' => 30, 'city' => 'Gorham'],
                ['state_id' => 30, 'city' => 'Groveton'],
                ['state_id' => 30, 'city' => 'Jefferson'],
                ['state_id' => 30, 'city' => 'Lancaster'],
                ['state_id' => 30, 'city' => 'Milan'],
                ['state_id' => 30, 'city' => 'Mount Washington'],
                ['state_id' => 30, 'city' => 'North Stratford'],
                ['state_id' => 30, 'city' => 'Pittsburg'],
                ['state_id' => 30, 'city' => 'Randolph'],
                ['state_id' => 30, 'city' => 'Twin Mountain'],
                ['state_id' => 30, 'city' => 'West Stewartstown'],
                ['state_id' => 30, 'city' => 'Whitefield'],
                ['state_id' => 30, 'city' => 'Waterville Valley'],
                ['state_id' => 30, 'city' => 'Ashland'],
                ['state_id' => 30, 'city' => 'Bristol'],
                ['state_id' => 30, 'city' => 'Campton'],
                ['state_id' => 30, 'city' => 'Glencliff'],
                ['state_id' => 30, 'city' => 'Grafton'],
                ['state_id' => 30, 'city' => 'Hebron'],
                ['state_id' => 30, 'city' => 'Holderness'],
                ['state_id' => 30, 'city' => 'Lincoln'],
                ['state_id' => 30, 'city' => 'Chichester'],
                ['state_id' => 30, 'city' => 'North Woodstock'],
                ['state_id' => 30, 'city' => 'Plymouth'],
                ['state_id' => 30, 'city' => 'Rumney'],
                ['state_id' => 30, 'city' => 'Warren'],
                ['state_id' => 30, 'city' => 'Wentworth'],
                ['state_id' => 30, 'city' => 'Thornton'],
                ['state_id' => 30, 'city' => 'Woodstock'],
                ['state_id' => 30, 'city' => 'Littleton'],
                ['state_id' => 30, 'city' => 'Bethlehem'],
                ['state_id' => 30, 'city' => 'Franconia'],
                ['state_id' => 30, 'city' => 'Lisbon'],
                ['state_id' => 30, 'city' => 'Sugar Hill'],
                ['state_id' => 30, 'city' => 'Bath'],
                ['state_id' => 30, 'city' => 'Canaan'],
                ['state_id' => 30, 'city' => 'Enfield'],
                ['state_id' => 30, 'city' => 'Enfield Center'],
                ['state_id' => 30, 'city' => 'Etna'],
                ['state_id' => 30, 'city' => 'Hanover'],
                ['state_id' => 30, 'city' => 'Lebanon'],
                ['state_id' => 30, 'city' => 'Haverhill'],
                ['state_id' => 30, 'city' => 'Lyme'],
                ['state_id' => 30, 'city' => 'Lyme Center'],
                ['state_id' => 30, 'city' => 'Monroe'],
                ['state_id' => 30, 'city' => 'North Haverhill'],
                ['state_id' => 30, 'city' => 'Orford'],
                ['state_id' => 30, 'city' => 'Piermont'],
                ['state_id' => 30, 'city' => 'Pike'],
                ['state_id' => 30, 'city' => 'West Lebanon'],
                ['state_id' => 30, 'city' => 'Woodsville'],
                ['state_id' => 30, 'city' => 'Amherst'],
                ['state_id' => 30, 'city' => 'Brookline'],
                ['state_id' => 30, 'city' => 'Francestown'],
                ['state_id' => 30, 'city' => 'Goffstown'],
                ['state_id' => 30, 'city' => 'Greenfield'],
                ['state_id' => 30, 'city' => 'Greenville'],
                ['state_id' => 30, 'city' => 'Hollis'],
                ['state_id' => 30, 'city' => 'Hudson'],
                ['state_id' => 30, 'city' => 'Litchfield'],
                ['state_id' => 30, 'city' => 'Merrimack'],
                ['state_id' => 30, 'city' => 'Milford'],
                ['state_id' => 30, 'city' => 'Mont Vernon'],
                ['state_id' => 30, 'city' => 'Nashua'],
                ['state_id' => 30, 'city' => 'New Boston'],
                ['state_id' => 30, 'city' => 'New Ipswich'],
                ['state_id' => 30, 'city' => 'Pelham'],
                ['state_id' => 30, 'city' => 'Lyndeborough'],
                ['state_id' => 30, 'city' => 'Temple'],
                ['state_id' => 30, 'city' => 'Wilton'],
                ['state_id' => 30, 'city' => 'Manchester'],
                ['state_id' => 30, 'city' => 'Bedford'],
                ['state_id' => 30, 'city' => 'Hillsborough'],
                ['state_id' => 30, 'city' => 'Weare'],
                ['state_id' => 30, 'city' => 'Antrim'],
                ['state_id' => 30, 'city' => 'Bennington'],
                ['state_id' => 30, 'city' => 'Hancock'],
                ['state_id' => 30, 'city' => 'Peterborough'],
                ['state_id' => 30, 'city' => 'West Peterborough'],
                ['state_id' => 30, 'city' => 'Dunbarton'],
                ['state_id' => 30, 'city' => 'Hooksett'],
                ['state_id' => 30, 'city' => 'Andover'],
                ['state_id' => 30, 'city' => 'Bradford'],
                ['state_id' => 30, 'city' => 'Canterbury'],
                ['state_id' => 30, 'city' => 'Contoocook'],
                ['state_id' => 30, 'city' => 'Danbury'],
                ['state_id' => 30, 'city' => 'East Andover'],
                ['state_id' => 30, 'city' => 'Elkins'],
                ['state_id' => 30, 'city' => 'Epsom'],
                ['state_id' => 30, 'city' => 'Franklin'],
                ['state_id' => 30, 'city' => 'Henniker'],
                ['state_id' => 30, 'city' => 'Hill'],
                ['state_id' => 30, 'city' => 'Newbury'],
                ['state_id' => 30, 'city' => 'New London'],
                ['state_id' => 30, 'city' => 'North Sutton'],
                ['state_id' => 30, 'city' => 'Pittsfield'],
                ['state_id' => 30, 'city' => 'Salisbury'],
                ['state_id' => 30, 'city' => 'South Newbury'],
                ['state_id' => 30, 'city' => 'South Sutton'],
                ['state_id' => 30, 'city' => 'Suncook'],
                ['state_id' => 30, 'city' => 'Warner'],
                ['state_id' => 30, 'city' => 'Wilmot'],
                ['state_id' => 30, 'city' => 'Concord'],
                ['state_id' => 30, 'city' => 'Bow'],
                ['state_id' => 30, 'city' => 'Loudon'],
                ['state_id' => 30, 'city' => 'Auburn'],
                ['state_id' => 30, 'city' => 'Candia'],
                ['state_id' => 30, 'city' => 'Chester'],
                ['state_id' => 30, 'city' => 'Deerfield'],
                ['state_id' => 30, 'city' => 'Derry'],
                ['state_id' => 30, 'city' => 'East Candia'],
                ['state_id' => 30, 'city' => 'East Derry'],
                ['state_id' => 30, 'city' => 'Epping'],
                ['state_id' => 30, 'city' => 'Fremont'],
                ['state_id' => 30, 'city' => 'Londonderry'],
                ['state_id' => 30, 'city' => 'North Salem'],
                ['state_id' => 30, 'city' => 'Raymond'],
                ['state_id' => 30, 'city' => 'Salem'],
                ['state_id' => 30, 'city' => 'Windham'],
                ['state_id' => 30, 'city' => 'Northwood'],
                ['state_id' => 30, 'city' => 'Nottingham'],
                ['state_id' => 30, 'city' => 'West Nottingham'],
                ['state_id' => 30, 'city' => 'Portsmouth'],
                ['state_id' => 30, 'city' => 'Atkinson'],
                ['state_id' => 30, 'city' => 'Danville'],
                ['state_id' => 30, 'city' => 'East Hampstead'],
                ['state_id' => 30, 'city' => 'East Kingston'],
                ['state_id' => 30, 'city' => 'Exeter'],
                ['state_id' => 30, 'city' => 'Greenland'],
                ['state_id' => 30, 'city' => 'Hampstead'],
                ['state_id' => 30, 'city' => 'Hampton'],
                ['state_id' => 30, 'city' => 'Hampton Falls'],
                ['state_id' => 30, 'city' => 'Kingston'],
                ['state_id' => 30, 'city' => 'New Castle'],
                ['state_id' => 30, 'city' => 'Newfields'],
                ['state_id' => 30, 'city' => 'Newmarket'],
                ['state_id' => 30, 'city' => 'Newton'],
                ['state_id' => 30, 'city' => 'Newton Junction'],
                ['state_id' => 30, 'city' => 'North Hampton'],
                ['state_id' => 30, 'city' => 'Plaistow'],
                ['state_id' => 30, 'city' => 'Rye'],
                ['state_id' => 30, 'city' => 'Rye Beach'],
                ['state_id' => 30, 'city' => 'Sandown'],
                ['state_id' => 30, 'city' => 'Seabrook'],
                ['state_id' => 30, 'city' => 'Stratham'],
                ['state_id' => 30, 'city' => 'Center Strafford'],
                ['state_id' => 30, 'city' => 'Dover'],
                ['state_id' => 30, 'city' => 'Madbury'],
                ['state_id' => 30, 'city' => 'Durham'],
                ['state_id' => 30, 'city' => 'Barrington'],
                ['state_id' => 30, 'city' => 'Farmington'],
                ['state_id' => 30, 'city' => 'Rochester'],
                ['state_id' => 30, 'city' => 'Milton'],
                ['state_id' => 30, 'city' => 'Milton Mills'],
                ['state_id' => 30, 'city' => 'New Durham'],
                ['state_id' => 30, 'city' => 'Rollinsford'],
                ['state_id' => 30, 'city' => 'Somersworth'],
                ['state_id' => 30, 'city' => 'Strafford'],
                ['state_id' => 30, 'city' => 'Union'],
                ['state_id' => 30, 'city' => 'Washington'],
                ['state_id' => 30, 'city' => 'Springfield'],
                ['state_id' => 30, 'city' => 'Acworth'],
                ['state_id' => 30, 'city' => 'Charlestown'],
                ['state_id' => 30, 'city' => 'Lempster'],
                ['state_id' => 30, 'city' => 'South Acworth'],
                ['state_id' => 30, 'city' => 'Claremont'],
                ['state_id' => 30, 'city' => 'Cornish'],
                ['state_id' => 30, 'city' => 'Cornish Flat'],
                ['state_id' => 30, 'city' => 'Georges Mills'],
                ['state_id' => 30, 'city' => 'Goshen'],
                ['state_id' => 30, 'city' => 'Grantham'],
                ['state_id' => 30, 'city' => 'Guild'],
                ['state_id' => 30, 'city' => 'Meriden'],
                ['state_id' => 30, 'city' => 'Newport'],
                ['state_id' => 30, 'city' => 'Plainfield'],
                ['state_id' => 30, 'city' => 'Sunapee']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
