<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State18TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of KY - Kentucky.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 18, 'city' => 'Breeding'],
                ['state_id' => 18, 'city' => 'Cane Valley'],
                ['state_id' => 18, 'city' => 'Columbia'],
                ['state_id' => 18, 'city' => 'Glens Fork'],
                ['state_id' => 18, 'city' => 'Gradyville'],
                ['state_id' => 18, 'city' => 'Knifley'],
                ['state_id' => 18, 'city' => 'Adolphus'],
                ['state_id' => 18, 'city' => 'Holland'],
                ['state_id' => 18, 'city' => 'Scottsville'],
                ['state_id' => 18, 'city' => 'Lawrenceburg'],
                ['state_id' => 18, 'city' => 'Bandana'],
                ['state_id' => 18, 'city' => 'Barlow'],
                ['state_id' => 18, 'city' => 'La Center'],
                ['state_id' => 18, 'city' => 'Lovelaceville'],
                ['state_id' => 18, 'city' => 'Wickliffe'],
                ['state_id' => 18, 'city' => 'Austin'],
                ['state_id' => 18, 'city' => 'Cave City'],
                ['state_id' => 18, 'city' => 'Eighty Eight'],
                ['state_id' => 18, 'city' => 'Etoile'],
                ['state_id' => 18, 'city' => 'Glasgow'],
                ['state_id' => 18, 'city' => 'Hiseville'],
                ['state_id' => 18, 'city' => 'Lucas'],
                ['state_id' => 18, 'city' => 'Park City'],
                ['state_id' => 18, 'city' => 'Olympia'],
                ['state_id' => 18, 'city' => 'Owingsville'],
                ['state_id' => 18, 'city' => 'Preston'],
                ['state_id' => 18, 'city' => 'Salt Lick'],
                ['state_id' => 18, 'city' => 'Sharpsburg'],
                ['state_id' => 18, 'city' => 'Calvin'],
                ['state_id' => 18, 'city' => 'Hulen'],
                ['state_id' => 18, 'city' => 'Miracle'],
                ['state_id' => 18, 'city' => 'Arjay'],
                ['state_id' => 18, 'city' => 'Beverly'],
                ['state_id' => 18, 'city' => 'Frakes'],
                ['state_id' => 18, 'city' => 'Ingram'],
                ['state_id' => 18, 'city' => 'Kettle Island'],
                ['state_id' => 18, 'city' => 'Middlesboro'],
                ['state_id' => 18, 'city' => 'Pineville'],
                ['state_id' => 18, 'city' => 'Stoney Fork'],
                ['state_id' => 18, 'city' => 'Burlington'],
                ['state_id' => 18, 'city' => 'Hebron'],
                ['state_id' => 18, 'city' => 'Florence'],
                ['state_id' => 18, 'city' => 'Petersburg'],
                ['state_id' => 18, 'city' => 'Union'],
                ['state_id' => 18, 'city' => 'Verona'],
                ['state_id' => 18, 'city' => 'Walton'],
                ['state_id' => 18, 'city' => 'Millersburg'],
                ['state_id' => 18, 'city' => 'North Middletown'],
                ['state_id' => 18, 'city' => 'Paris'],
                ['state_id' => 18, 'city' => 'Ashland'],
                ['state_id' => 18, 'city' => 'Catlettsburg'],
                ['state_id' => 18, 'city' => 'Rush'],
                ['state_id' => 18, 'city' => 'Danville'],
                ['state_id' => 18, 'city' => 'Junction City'],
                ['state_id' => 18, 'city' => 'Mitchellsburg'],
                ['state_id' => 18, 'city' => 'Parksville'],
                ['state_id' => 18, 'city' => 'Perryville'],
                ['state_id' => 18, 'city' => 'Augusta'],
                ['state_id' => 18, 'city' => 'Brooksville'],
                ['state_id' => 18, 'city' => 'Foster'],
                ['state_id' => 18, 'city' => 'Germantown'],
                ['state_id' => 18, 'city' => 'Milford'],
                ['state_id' => 18, 'city' => 'Bays'],
                ['state_id' => 18, 'city' => 'Clayhole'],
                ['state_id' => 18, 'city' => 'Jackson'],
                ['state_id' => 18, 'city' => 'Lost Creek'],
                ['state_id' => 18, 'city' => 'Rousseau'],
                ['state_id' => 18, 'city' => 'Vancleve'],
                ['state_id' => 18, 'city' => 'Whick'],
                ['state_id' => 18, 'city' => 'Cloverport'],
                ['state_id' => 18, 'city' => 'Custer'],
                ['state_id' => 18, 'city' => 'Garfield'],
                ['state_id' => 18, 'city' => 'Hardinsburg'],
                ['state_id' => 18, 'city' => 'Harned'],
                ['state_id' => 18, 'city' => 'Hudson'],
                ['state_id' => 18, 'city' => 'Irvington'],
                ['state_id' => 18, 'city' => 'Mc Daniels'],
                ['state_id' => 18, 'city' => 'Mc Quady'],
                ['state_id' => 18, 'city' => 'Stephensport'],
                ['state_id' => 18, 'city' => 'Union Star'],
                ['state_id' => 18, 'city' => 'Webster'],
                ['state_id' => 18, 'city' => 'Westview'],
                ['state_id' => 18, 'city' => 'Mount Washington'],
                ['state_id' => 18, 'city' => 'Brooks'],
                ['state_id' => 18, 'city' => 'Clermont'],
                ['state_id' => 18, 'city' => 'Hillview'],
                ['state_id' => 18, 'city' => 'Lebanon Junction'],
                ['state_id' => 18, 'city' => 'Shepherdsville'],
                ['state_id' => 18, 'city' => 'Aberdeen'],
                ['state_id' => 18, 'city' => 'Dunbar'],
                ['state_id' => 18, 'city' => 'Jetson'],
                ['state_id' => 18, 'city' => 'Morgantown'],
                ['state_id' => 18, 'city' => 'Rochester'],
                ['state_id' => 18, 'city' => 'Woodbury'],
                ['state_id' => 18, 'city' => 'Fredonia'],
                ['state_id' => 18, 'city' => 'Princeton'],
                ['state_id' => 18, 'city' => 'Almo'],
                ['state_id' => 18, 'city' => 'Dexter'],
                ['state_id' => 18, 'city' => 'Hazel'],
                ['state_id' => 18, 'city' => 'Kirksey'],
                ['state_id' => 18, 'city' => 'Murray'],
                ['state_id' => 18, 'city' => 'New Concord'],
                ['state_id' => 18, 'city' => 'Alexandria'],
                ['state_id' => 18, 'city' => 'California'],
                ['state_id' => 18, 'city' => 'Melbourne'],
                ['state_id' => 18, 'city' => 'Newport'],
                ['state_id' => 18, 'city' => 'Bellevue'],
                ['state_id' => 18, 'city' => 'Dayton'],
                ['state_id' => 18, 'city' => 'Fort Thomas'],
                ['state_id' => 18, 'city' => 'Silver Grove'],
                ['state_id' => 18, 'city' => 'Arlington'],
                ['state_id' => 18, 'city' => 'Bardwell'],
                ['state_id' => 18, 'city' => 'Cunningham'],
                ['state_id' => 18, 'city' => 'Milburn'],
                ['state_id' => 18, 'city' => 'Carrollton'],
                ['state_id' => 18, 'city' => 'Ghent'],
                ['state_id' => 18, 'city' => 'Sanders'],
                ['state_id' => 18, 'city' => 'Worthville'],
                ['state_id' => 18, 'city' => 'Carter'],
                ['state_id' => 18, 'city' => 'Denton'],
                ['state_id' => 18, 'city' => 'Grahn'],
                ['state_id' => 18, 'city' => 'Grayson'],
                ['state_id' => 18, 'city' => 'Hitchins'],
                ['state_id' => 18, 'city' => 'Olive Hill'],
                ['state_id' => 18, 'city' => 'Soldier'],
                ['state_id' => 18, 'city' => 'Willard'],
                ['state_id' => 18, 'city' => 'Bethelridge'],
                ['state_id' => 18, 'city' => 'Dunnville'],
                ['state_id' => 18, 'city' => 'Liberty'],
                ['state_id' => 18, 'city' => 'Middleburg'],
                ['state_id' => 18, 'city' => 'Windsor'],
                ['state_id' => 18, 'city' => 'Yosemite'],
                ['state_id' => 18, 'city' => 'Crofton'],
                ['state_id' => 18, 'city' => 'Fairview'],
                ['state_id' => 18, 'city' => 'Fort Campbell'],
                ['state_id' => 18, 'city' => 'Gracey'],
                ['state_id' => 18, 'city' => 'Herndon'],
                ['state_id' => 18, 'city' => 'Hopkinsville'],
                ['state_id' => 18, 'city' => 'La Fayette'],
                ['state_id' => 18, 'city' => 'Oak Grove'],
                ['state_id' => 18, 'city' => 'Pembroke'],
                ['state_id' => 18, 'city' => 'Winchester'],
                ['state_id' => 18, 'city' => 'Big Creek'],
                ['state_id' => 18, 'city' => 'Fall Rock'],
                ['state_id' => 18, 'city' => 'Garrard'],
                ['state_id' => 18, 'city' => 'Goose Rock'],
                ['state_id' => 18, 'city' => 'Hima'],
                ['state_id' => 18, 'city' => 'Manchester'],
                ['state_id' => 18, 'city' => 'Oneida'],
                ['state_id' => 18, 'city' => 'Sextons Creek'],
                ['state_id' => 18, 'city' => 'Albany'],
                ['state_id' => 18, 'city' => 'Alpha'],
                ['state_id' => 18, 'city' => 'Crayne'],
                ['state_id' => 18, 'city' => 'Dycusburg'],
                ['state_id' => 18, 'city' => 'Marion'],
                ['state_id' => 18, 'city' => 'Burkesville'],
                ['state_id' => 18, 'city' => 'Marrowbone'],
                ['state_id' => 18, 'city' => 'Owensboro'],
                ['state_id' => 18, 'city' => 'Curdsville'],
                ['state_id' => 18, 'city' => 'Maceo'],
                ['state_id' => 18, 'city' => 'Maple Mount'],
                ['state_id' => 18, 'city' => 'Philpot'],
                ['state_id' => 18, 'city' => 'Utica'],
                ['state_id' => 18, 'city' => 'West Louisville'],
                ['state_id' => 18, 'city' => 'Whitesville'],
                ['state_id' => 18, 'city' => 'Rocky Hill'],
                ['state_id' => 18, 'city' => 'Bee Spring'],
                ['state_id' => 18, 'city' => 'Brownsville'],
                ['state_id' => 18, 'city' => 'Mammoth Cave'],
                ['state_id' => 18, 'city' => 'Roundhill'],
                ['state_id' => 18, 'city' => 'Sweeden'],
                ['state_id' => 18, 'city' => 'Isonville'],
                ['state_id' => 18, 'city' => 'Sandy Hook'],
                ['state_id' => 18, 'city' => 'Irvine'],
                ['state_id' => 18, 'city' => 'Ravenna'],
                ['state_id' => 18, 'city' => 'Lexington'],
                ['state_id' => 18, 'city' => 'Elizaville'],
                ['state_id' => 18, 'city' => 'Ewing'],
                ['state_id' => 18, 'city' => 'Flemingsburg'],
                ['state_id' => 18, 'city' => 'Hillsboro'],
                ['state_id' => 18, 'city' => 'Muses Mills'],
                ['state_id' => 18, 'city' => 'Plummers Landing'],
                ['state_id' => 18, 'city' => 'Wallingford'],
                ['state_id' => 18, 'city' => 'Allen'],
                ['state_id' => 18, 'city' => 'Auxier'],
                ['state_id' => 18, 'city' => 'Banner'],
                ['state_id' => 18, 'city' => 'Beaver'],
                ['state_id' => 18, 'city' => 'Betsy Layne'],
                ['state_id' => 18, 'city' => 'Bevinsville'],
                ['state_id' => 18, 'city' => 'Blue River'],
                ['state_id' => 18, 'city' => 'Bypro'],
                ['state_id' => 18, 'city' => 'Dana'],
                ['state_id' => 18, 'city' => 'David'],
                ['state_id' => 18, 'city' => 'Drift'],
                ['state_id' => 18, 'city' => 'Dwale'],
                ['state_id' => 18, 'city' => 'Eastern'],
                ['state_id' => 18, 'city' => 'Garrett'],
                ['state_id' => 18, 'city' => 'Grethel'],
                ['state_id' => 18, 'city' => 'Harold'],
                ['state_id' => 18, 'city' => 'Hi Hat'],
                ['state_id' => 18, 'city' => 'Hueysville'],
                ['state_id' => 18, 'city' => 'Ivel'],
                ['state_id' => 18, 'city' => 'Lackey'],
                ['state_id' => 18, 'city' => 'Langley'],
                ['state_id' => 18, 'city' => 'Mc Dowell'],
                ['state_id' => 18, 'city' => 'Martin'],
                ['state_id' => 18, 'city' => 'Melvin'],
                ['state_id' => 18, 'city' => 'Minnie'],
                ['state_id' => 18, 'city' => 'Prestonsburg'],
                ['state_id' => 18, 'city' => 'Printer'],
                ['state_id' => 18, 'city' => 'Stanville'],
                ['state_id' => 18, 'city' => 'Teaberry'],
                ['state_id' => 18, 'city' => 'Tram'],
                ['state_id' => 18, 'city' => 'Wayland'],
                ['state_id' => 18, 'city' => 'Weeksbury'],
                ['state_id' => 18, 'city' => 'Wheelwright'],
                ['state_id' => 18, 'city' => 'Frankfort'],
                ['state_id' => 18, 'city' => 'Fulton'],
                ['state_id' => 18, 'city' => 'Hickman'],
                ['state_id' => 18, 'city' => 'Glencoe'],
                ['state_id' => 18, 'city' => 'Sparta'],
                ['state_id' => 18, 'city' => 'Warsaw'],
                ['state_id' => 18, 'city' => 'Bryantsville'],
                ['state_id' => 18, 'city' => 'Lancaster'],
                ['state_id' => 18, 'city' => 'Paint Lick'],
                ['state_id' => 18, 'city' => 'Corinth'],
                ['state_id' => 18, 'city' => 'Crittenden'],
                ['state_id' => 18, 'city' => 'Dry Ridge'],
                ['state_id' => 18, 'city' => 'Jonesville'],
                ['state_id' => 18, 'city' => 'Mason'],
                ['state_id' => 18, 'city' => 'Williamstown'],
                ['state_id' => 18, 'city' => 'Boaz'],
                ['state_id' => 18, 'city' => 'Fancy Farm'],
                ['state_id' => 18, 'city' => 'Farmington'],
                ['state_id' => 18, 'city' => 'Hickory'],
                ['state_id' => 18, 'city' => 'Lowes'],
                ['state_id' => 18, 'city' => 'Lynnville'],
                ['state_id' => 18, 'city' => 'Mayfield'],
                ['state_id' => 18, 'city' => 'Melber'],
                ['state_id' => 18, 'city' => 'Sedalia'],
                ['state_id' => 18, 'city' => 'Symsonia'],
                ['state_id' => 18, 'city' => 'Water Valley'],
                ['state_id' => 18, 'city' => 'Wingo'],
                ['state_id' => 18, 'city' => 'Falls Of Rough'],
                ['state_id' => 18, 'city' => 'Big Clifty'],
                ['state_id' => 18, 'city' => 'Caneyville'],
                ['state_id' => 18, 'city' => 'Clarkson'],
                ['state_id' => 18, 'city' => 'Leitchfield'],
                ['state_id' => 18, 'city' => 'Millwood'],
                ['state_id' => 18, 'city' => 'Greensburg'],
                ['state_id' => 18, 'city' => 'Summersville'],
                ['state_id' => 18, 'city' => 'Argillite'],
                ['state_id' => 18, 'city' => 'Flatwoods'],
                ['state_id' => 18, 'city' => 'Greenup'],
                ['state_id' => 18, 'city' => 'Russell'],
                ['state_id' => 18, 'city' => 'South Portsmouth'],
                ['state_id' => 18, 'city' => 'South Shore'],
                ['state_id' => 18, 'city' => 'Worthington'],
                ['state_id' => 18, 'city' => 'Hawesville'],
                ['state_id' => 18, 'city' => 'Lewisport'],
                ['state_id' => 18, 'city' => 'Pellville'],
                ['state_id' => 18, 'city' => 'Reynolds Station'],
                ['state_id' => 18, 'city' => 'Fort Knox'],
                ['state_id' => 18, 'city' => 'Radcliff'],
                ['state_id' => 18, 'city' => 'Rineyville'],
                ['state_id' => 18, 'city' => 'Vine Grove'],
                ['state_id' => 18, 'city' => 'West Point'],
                ['state_id' => 18, 'city' => 'Elizabethtown'],
                ['state_id' => 18, 'city' => 'Cecilia'],
                ['state_id' => 18, 'city' => 'Eastview'],
                ['state_id' => 18, 'city' => 'Glendale'],
                ['state_id' => 18, 'city' => 'Sonora'],
                ['state_id' => 18, 'city' => 'Upton'],
                ['state_id' => 18, 'city' => 'White Mills'],
                ['state_id' => 18, 'city' => 'Ages Brookside'],
                ['state_id' => 18, 'city' => 'Baxter'],
                ['state_id' => 18, 'city' => 'Benham'],
                ['state_id' => 18, 'city' => 'Big Laurel'],
                ['state_id' => 18, 'city' => 'Bledsoe'],
                ['state_id' => 18, 'city' => 'Cawood'],
                ['state_id' => 18, 'city' => 'Coalgood'],
                ['state_id' => 18, 'city' => 'Coldiron'],
                ['state_id' => 18, 'city' => 'Cranks'],
                ['state_id' => 18, 'city' => 'Cumberland'],
                ['state_id' => 18, 'city' => 'Dayhoit'],
                ['state_id' => 18, 'city' => 'Evarts'],
                ['state_id' => 18, 'city' => 'Grays Knob'],
                ['state_id' => 18, 'city' => 'Gulston'],
                ['state_id' => 18, 'city' => 'Harlan'],
                ['state_id' => 18, 'city' => 'Holmes Mill'],
                ['state_id' => 18, 'city' => 'Kenvir'],
                ['state_id' => 18, 'city' => 'Lejunior'],
                ['state_id' => 18, 'city' => 'Loyall'],
                ['state_id' => 18, 'city' => 'Lynch'],
                ['state_id' => 18, 'city' => 'Pathfork'],
                ['state_id' => 18, 'city' => 'Putney'],
                ['state_id' => 18, 'city' => 'Totz'],
                ['state_id' => 18, 'city' => 'Wallins Creek'],
                ['state_id' => 18, 'city' => 'Closplint'],
                ['state_id' => 18, 'city' => 'Mary Alice'],
                ['state_id' => 18, 'city' => 'Berry'],
                ['state_id' => 18, 'city' => 'Cynthiana'],
                ['state_id' => 18, 'city' => 'Bonnieville'],
                ['state_id' => 18, 'city' => 'Canmer'],
                ['state_id' => 18, 'city' => 'Cub Run'],
                ['state_id' => 18, 'city' => 'Hardyville'],
                ['state_id' => 18, 'city' => 'Horse Cave'],
                ['state_id' => 18, 'city' => 'Munfordville'],
                ['state_id' => 18, 'city' => 'Baskett'],
                ['state_id' => 18, 'city' => 'Corydon'],
                ['state_id' => 18, 'city' => 'Henderson'],
                ['state_id' => 18, 'city' => 'Reed'],
                ['state_id' => 18, 'city' => 'Robards'],
                ['state_id' => 18, 'city' => 'Smith Mills'],
                ['state_id' => 18, 'city' => 'Spottsville'],
                ['state_id' => 18, 'city' => 'Bethlehem'],
                ['state_id' => 18, 'city' => 'Campbellsburg'],
                ['state_id' => 18, 'city' => 'Eminence'],
                ['state_id' => 18, 'city' => 'Lockport'],
                ['state_id' => 18, 'city' => 'New Castle'],
                ['state_id' => 18, 'city' => 'Pendleton'],
                ['state_id' => 18, 'city' => 'Pleasureville'],
                ['state_id' => 18, 'city' => 'Port Royal'],
                ['state_id' => 18, 'city' => 'Smithfield'],
                ['state_id' => 18, 'city' => 'Sulphur'],
                ['state_id' => 18, 'city' => 'Turners Station'],
                ['state_id' => 18, 'city' => 'Clinton'],
                ['state_id' => 18, 'city' => 'Columbus'],
                ['state_id' => 18, 'city' => 'Dawson Springs'],
                ['state_id' => 18, 'city' => 'Earlington'],
                ['state_id' => 18, 'city' => 'Hanson'],
                ['state_id' => 18, 'city' => 'Madisonville'],
                ['state_id' => 18, 'city' => 'Manitou'],
                ['state_id' => 18, 'city' => 'Mortons Gap'],
                ['state_id' => 18, 'city' => 'Nebo'],
                ['state_id' => 18, 'city' => 'Nortonville'],
                ['state_id' => 18, 'city' => 'Saint Charles'],
                ['state_id' => 18, 'city' => 'White Plains'],
                ['state_id' => 18, 'city' => 'Annville'],
                ['state_id' => 18, 'city' => 'Gray Hawk'],
                ['state_id' => 18, 'city' => 'Mc Kee'],
                ['state_id' => 18, 'city' => 'Sandgap'],
                ['state_id' => 18, 'city' => 'Tyner'],
                ['state_id' => 18, 'city' => 'Waneta'],
                ['state_id' => 18, 'city' => 'Eastwood'],
                ['state_id' => 18, 'city' => 'Fisherville'],
                ['state_id' => 18, 'city' => 'Glenview'],
                ['state_id' => 18, 'city' => 'Harrods Creek'],
                ['state_id' => 18, 'city' => 'Masonic Home'],
                ['state_id' => 18, 'city' => 'Prospect'],
                ['state_id' => 18, 'city' => 'Fairdale'],
                ['state_id' => 18, 'city' => 'Louisville'],
                ['state_id' => 18, 'city' => 'Keene'],
                ['state_id' => 18, 'city' => 'Nicholasville'],
                ['state_id' => 18, 'city' => 'Wilmore'],
                ['state_id' => 18, 'city' => 'Boons Camp'],
                ['state_id' => 18, 'city' => 'East Point'],
                ['state_id' => 18, 'city' => 'Flatgap'],
                ['state_id' => 18, 'city' => 'Hagerhill'],
                ['state_id' => 18, 'city' => 'Keaton'],
                ['state_id' => 18, 'city' => 'Meally'],
                ['state_id' => 18, 'city' => 'Oil Springs'],
                ['state_id' => 18, 'city' => 'Paintsville'],
                ['state_id' => 18, 'city' => 'River'],
                ['state_id' => 18, 'city' => 'Sitka'],
                ['state_id' => 18, 'city' => 'Staffordsville'],
                ['state_id' => 18, 'city' => 'Stambaugh'],
                ['state_id' => 18, 'city' => 'Thelma'],
                ['state_id' => 18, 'city' => 'Tutor Key'],
                ['state_id' => 18, 'city' => 'Van Lear'],
                ['state_id' => 18, 'city' => 'West Van Lear'],
                ['state_id' => 18, 'city' => 'Williamsport'],
                ['state_id' => 18, 'city' => 'Wittensville'],
                ['state_id' => 18, 'city' => 'Covington'],
                ['state_id' => 18, 'city' => 'Latonia'],
                ['state_id' => 18, 'city' => 'Ft Mitchell'],
                ['state_id' => 18, 'city' => 'Erlanger'],
                ['state_id' => 18, 'city' => 'Independence'],
                ['state_id' => 18, 'city' => 'Kenton'],
                ['state_id' => 18, 'city' => 'Morning View'],
                ['state_id' => 18, 'city' => 'Carrie'],
                ['state_id' => 18, 'city' => 'Emmalena'],
                ['state_id' => 18, 'city' => 'Fisty'],
                ['state_id' => 18, 'city' => 'Sassafras'],
                ['state_id' => 18, 'city' => 'Vest'],
                ['state_id' => 18, 'city' => 'Garner'],
                ['state_id' => 18, 'city' => 'Hindman'],
                ['state_id' => 18, 'city' => 'Kite'],
                ['state_id' => 18, 'city' => 'Leburn'],
                ['state_id' => 18, 'city' => 'Littcarr'],
                ['state_id' => 18, 'city' => 'Mallie'],
                ['state_id' => 18, 'city' => 'Mousie'],
                ['state_id' => 18, 'city' => 'Pine Top'],
                ['state_id' => 18, 'city' => 'Pippa Passes'],
                ['state_id' => 18, 'city' => 'Redfox'],
                ['state_id' => 18, 'city' => 'Dema'],
                ['state_id' => 18, 'city' => 'Raven'],
                ['state_id' => 18, 'city' => 'Topmost'],
                ['state_id' => 18, 'city' => 'Gray'],
                ['state_id' => 18, 'city' => 'Woodbine'],
                ['state_id' => 18, 'city' => 'Artemus'],
                ['state_id' => 18, 'city' => 'Barbourville'],
                ['state_id' => 18, 'city' => 'Bimble'],
                ['state_id' => 18, 'city' => 'Bryants Store'],
                ['state_id' => 18, 'city' => 'Cannon'],
                ['state_id' => 18, 'city' => 'Dewitt'],
                ['state_id' => 18, 'city' => 'Flat Lick'],
                ['state_id' => 18, 'city' => 'Fourmile'],
                ['state_id' => 18, 'city' => 'Girdler'],
                ['state_id' => 18, 'city' => 'Green Road'],
                ['state_id' => 18, 'city' => 'Heidrick'],
                ['state_id' => 18, 'city' => 'Hinkle'],
                ['state_id' => 18, 'city' => 'Scalf'],
                ['state_id' => 18, 'city' => 'Trosper'],
                ['state_id' => 18, 'city' => 'Walker'],
                ['state_id' => 18, 'city' => 'Buffalo'],
                ['state_id' => 18, 'city' => 'Hodgenville'],
                ['state_id' => 18, 'city' => 'Magnolia'],
                ['state_id' => 18, 'city' => 'Mount Sherman'],
                ['state_id' => 18, 'city' => 'Bush'],
                ['state_id' => 18, 'city' => 'East Bernstadt'],
                ['state_id' => 18, 'city' => 'Keavy'],
                ['state_id' => 18, 'city' => 'Lily'],
                ['state_id' => 18, 'city' => 'London'],
                ['state_id' => 18, 'city' => 'Pittsburg'],
                ['state_id' => 18, 'city' => 'Blaine'],
                ['state_id' => 18, 'city' => 'Martha'],
                ['state_id' => 18, 'city' => 'Mazie'],
                ['state_id' => 18, 'city' => 'Webbville'],
                ['state_id' => 18, 'city' => 'Adams'],
                ['state_id' => 18, 'city' => 'Louisa'],
                ['state_id' => 18, 'city' => 'Lowmansville'],
                ['state_id' => 18, 'city' => 'Ulysses'],
                ['state_id' => 18, 'city' => 'Beattyville'],
                ['state_id' => 18, 'city' => 'Lone'],
                ['state_id' => 18, 'city' => 'Saint Helens'],
                ['state_id' => 18, 'city' => 'Zoe'],
                ['state_id' => 18, 'city' => 'Asher'],
                ['state_id' => 18, 'city' => 'Chappell'],
                ['state_id' => 18, 'city' => 'Essie'],
                ['state_id' => 18, 'city' => 'Helton'],
                ['state_id' => 18, 'city' => 'Hoskinston'],
                ['state_id' => 18, 'city' => 'Mozelle'],
                ['state_id' => 18, 'city' => 'Stinnett'],
                ['state_id' => 18, 'city' => 'Warbranch'],
                ['state_id' => 18, 'city' => 'Roark'],
                ['state_id' => 18, 'city' => 'Bear Branch'],
                ['state_id' => 18, 'city' => 'Hyden'],
                ['state_id' => 18, 'city' => 'Sizerock'],
                ['state_id' => 18, 'city' => 'Smilax'],
                ['state_id' => 18, 'city' => 'Thousandsticks'],
                ['state_id' => 18, 'city' => 'Wendover'],
                ['state_id' => 18, 'city' => 'Wooton'],
                ['state_id' => 18, 'city' => 'Yeaddiss'],
                ['state_id' => 18, 'city' => 'Eolia'],
                ['state_id' => 18, 'city' => 'Partridge'],
                ['state_id' => 18, 'city' => 'Burdine'],
                ['state_id' => 18, 'city' => 'Jenkins'],
                ['state_id' => 18, 'city' => 'Blackey'],
                ['state_id' => 18, 'city' => 'Cromona'],
                ['state_id' => 18, 'city' => 'Deane'],
                ['state_id' => 18, 'city' => 'Ermine'],
                ['state_id' => 18, 'city' => 'Gordon'],
                ['state_id' => 18, 'city' => 'Hallie'],
                ['state_id' => 18, 'city' => 'Isom'],
                ['state_id' => 18, 'city' => 'Jackhorn'],
                ['state_id' => 18, 'city' => 'Jeremiah'],
                ['state_id' => 18, 'city' => 'Letcher'],
                ['state_id' => 18, 'city' => 'Linefork'],
                ['state_id' => 18, 'city' => 'Mc Roberts'],
                ['state_id' => 18, 'city' => 'Mayking'],
                ['state_id' => 18, 'city' => 'Millstone'],
                ['state_id' => 18, 'city' => 'Neon'],
                ['state_id' => 18, 'city' => 'Premium'],
                ['state_id' => 18, 'city' => 'Roxana'],
                ['state_id' => 18, 'city' => 'Seco'],
                ['state_id' => 18, 'city' => 'Thornton'],
                ['state_id' => 18, 'city' => 'Whitesburg'],
                ['state_id' => 18, 'city' => 'Emerson'],
                ['state_id' => 18, 'city' => 'Garrison'],
                ['state_id' => 18, 'city' => 'Quincy'],
                ['state_id' => 18, 'city' => 'Vanceburg'],
                ['state_id' => 18, 'city' => 'Tollesboro'],
                ['state_id' => 18, 'city' => 'Crab Orchard'],
                ['state_id' => 18, 'city' => 'Hustonville'],
                ['state_id' => 18, 'city' => 'Kings Mountain'],
                ['state_id' => 18, 'city' => 'Mc Kinney'],
                ['state_id' => 18, 'city' => 'Stanford'],
                ['state_id' => 18, 'city' => 'Waynesburg'],
                ['state_id' => 18, 'city' => 'Burna'],
                ['state_id' => 18, 'city' => 'Grand Rivers'],
                ['state_id' => 18, 'city' => 'Hampton'],
                ['state_id' => 18, 'city' => 'Ledbetter'],
                ['state_id' => 18, 'city' => 'Salem'],
                ['state_id' => 18, 'city' => 'Smithland'],
                ['state_id' => 18, 'city' => 'Tiline'],
                ['state_id' => 18, 'city' => 'Adairville'],
                ['state_id' => 18, 'city' => 'Auburn'],
                ['state_id' => 18, 'city' => 'Lewisburg'],
                ['state_id' => 18, 'city' => 'Olmstead'],
                ['state_id' => 18, 'city' => 'Russellville'],
                ['state_id' => 18, 'city' => 'Eddyville'],
                ['state_id' => 18, 'city' => 'Kuttawa'],
                ['state_id' => 18, 'city' => 'Paducah'],
                ['state_id' => 18, 'city' => 'Kevil'],
                ['state_id' => 18, 'city' => 'West Paducah'],
                ['state_id' => 18, 'city' => 'Marshes Siding'],
                ['state_id' => 18, 'city' => 'Parkers Lake'],
                ['state_id' => 18, 'city' => 'Pine Knot'],
                ['state_id' => 18, 'city' => 'Revelo'],
                ['state_id' => 18, 'city' => 'Stearns'],
                ['state_id' => 18, 'city' => 'Strunk'],
                ['state_id' => 18, 'city' => 'Whitley City'],
                ['state_id' => 18, 'city' => 'Beech Grove'],
                ['state_id' => 18, 'city' => 'Calhoun'],
                ['state_id' => 18, 'city' => 'Island'],
                ['state_id' => 18, 'city' => 'Livermore'],
                ['state_id' => 18, 'city' => 'Rumsey'],
                ['state_id' => 18, 'city' => 'Sacramento'],
                ['state_id' => 18, 'city' => 'Waco'],
                ['state_id' => 18, 'city' => 'Berea'],
                ['state_id' => 18, 'city' => 'Bighill'],
                ['state_id' => 18, 'city' => 'Richmond'],
                ['state_id' => 18, 'city' => 'Falcon'],
                ['state_id' => 18, 'city' => 'Royalton'],
                ['state_id' => 18, 'city' => 'Salyersville'],
                ['state_id' => 18, 'city' => 'Gunlock'],
                ['state_id' => 18, 'city' => 'Bradfordsville'],
                ['state_id' => 18, 'city' => 'Lebanon'],
                ['state_id' => 18, 'city' => 'Loretto'],
                ['state_id' => 18, 'city' => 'Nerinx'],
                ['state_id' => 18, 'city' => 'Raywick'],
                ['state_id' => 18, 'city' => 'Saint Francis'],
                ['state_id' => 18, 'city' => 'Saint Mary'],
                ['state_id' => 18, 'city' => 'Gravel Switch'],
                ['state_id' => 18, 'city' => 'Benton'],
                ['state_id' => 18, 'city' => 'Calvert City'],
                ['state_id' => 18, 'city' => 'Gilbertsville'],
                ['state_id' => 18, 'city' => 'Hardin'],
                ['state_id' => 18, 'city' => 'Beauty'],
                ['state_id' => 18, 'city' => 'Debord'],
                ['state_id' => 18, 'city' => 'Inez'],
                ['state_id' => 18, 'city' => 'Lovely'],
                ['state_id' => 18, 'city' => 'Pilgrim'],
                ['state_id' => 18, 'city' => 'Tomahawk'],
                ['state_id' => 18, 'city' => 'Warfield'],
                ['state_id' => 18, 'city' => 'Dover'],
                ['state_id' => 18, 'city' => 'Mayslick'],
                ['state_id' => 18, 'city' => 'Maysville'],
                ['state_id' => 18, 'city' => 'Minerva'],
                ['state_id' => 18, 'city' => 'Washington'],
                ['state_id' => 18, 'city' => 'Battletown'],
                ['state_id' => 18, 'city' => 'Brandenburg'],
                ['state_id' => 18, 'city' => 'Ekron'],
                ['state_id' => 18, 'city' => 'Guston'],
                ['state_id' => 18, 'city' => 'Muldraugh'],
                ['state_id' => 18, 'city' => 'Payneville'],
                ['state_id' => 18, 'city' => 'Rhodelia'],
                ['state_id' => 18, 'city' => 'Denniston'],
                ['state_id' => 18, 'city' => 'Frenchburg'],
                ['state_id' => 18, 'city' => 'Means'],
                ['state_id' => 18, 'city' => 'Wellington'],
                ['state_id' => 18, 'city' => 'Burgin'],
                ['state_id' => 18, 'city' => 'Harrodsburg'],
                ['state_id' => 18, 'city' => 'Salvisa'],
                ['state_id' => 18, 'city' => 'Beaumont'],
                ['state_id' => 18, 'city' => 'Edmonton'],
                ['state_id' => 18, 'city' => 'Knob Lick'],
                ['state_id' => 18, 'city' => 'Summer Shade'],
                ['state_id' => 18, 'city' => 'Center'],
                ['state_id' => 18, 'city' => 'Fountain Run'],
                ['state_id' => 18, 'city' => 'Gamaliel'],
                ['state_id' => 18, 'city' => 'Hestand'],
                ['state_id' => 18, 'city' => 'Mount Hermon'],
                ['state_id' => 18, 'city' => 'Tompkinsville'],
                ['state_id' => 18, 'city' => 'Hope'],
                ['state_id' => 18, 'city' => 'Jeffersonville'],
                ['state_id' => 18, 'city' => 'Mount Sterling'],
                ['state_id' => 18, 'city' => 'Mize'],
                ['state_id' => 18, 'city' => 'Cannel City'],
                ['state_id' => 18, 'city' => 'Crockett'],
                ['state_id' => 18, 'city' => 'Elkfork'],
                ['state_id' => 18, 'city' => 'Ezel'],
                ['state_id' => 18, 'city' => 'Malone'],
                ['state_id' => 18, 'city' => 'West Liberty'],
                ['state_id' => 18, 'city' => 'Wrigley'],
                ['state_id' => 18, 'city' => 'Beech Creek'],
                ['state_id' => 18, 'city' => 'Beechmont'],
                ['state_id' => 18, 'city' => 'Belton'],
                ['state_id' => 18, 'city' => 'Bremen'],
                ['state_id' => 18, 'city' => 'Browder'],
                ['state_id' => 18, 'city' => 'Central City'],
                ['state_id' => 18, 'city' => 'Cleaton'],
                ['state_id' => 18, 'city' => 'Drakesboro'],
                ['state_id' => 18, 'city' => 'Dunmor'],
                ['state_id' => 18, 'city' => 'Graham'],
                ['state_id' => 18, 'city' => 'Greenville'],
                ['state_id' => 18, 'city' => 'Powderly'],
                ['state_id' => 18, 'city' => 'South Carrollton'],
                ['state_id' => 18, 'city' => 'Bardstown'],
                ['state_id' => 18, 'city' => 'Bloomfield'],
                ['state_id' => 18, 'city' => 'Chaplin'],
                ['state_id' => 18, 'city' => 'Coxs Creek'],
                ['state_id' => 18, 'city' => 'Fairfield'],
                ['state_id' => 18, 'city' => 'Nazareth'],
                ['state_id' => 18, 'city' => 'New Haven'],
                ['state_id' => 18, 'city' => 'New Hope'],
                ['state_id' => 18, 'city' => 'Boston'],
                ['state_id' => 18, 'city' => 'Carlisle'],
                ['state_id' => 18, 'city' => 'Moorefield'],
                ['state_id' => 18, 'city' => 'Beaver Dam'],
                ['state_id' => 18, 'city' => 'Centertown'],
                ['state_id' => 18, 'city' => 'Cromwell'],
                ['state_id' => 18, 'city' => 'Dundee'],
                ['state_id' => 18, 'city' => 'Fordsville'],
                ['state_id' => 18, 'city' => 'Hartford'],
                ['state_id' => 18, 'city' => 'Horse Branch'],
                ['state_id' => 18, 'city' => 'Mc Henry'],
                ['state_id' => 18, 'city' => 'Olaton'],
                ['state_id' => 18, 'city' => 'Rockport'],
                ['state_id' => 18, 'city' => 'Rosine'],
                ['state_id' => 18, 'city' => 'Buckner'],
                ['state_id' => 18, 'city' => 'Crestwood'],
                ['state_id' => 18, 'city' => 'Goshen'],
                ['state_id' => 18, 'city' => 'La Grange'],
                ['state_id' => 18, 'city' => 'Pewee Valley'],
                ['state_id' => 18, 'city' => 'Westport'],
                ['state_id' => 18, 'city' => 'New Liberty'],
                ['state_id' => 18, 'city' => 'Owenton'],
                ['state_id' => 18, 'city' => 'Perry Park'],
                ['state_id' => 18, 'city' => 'Booneville'],
                ['state_id' => 18, 'city' => 'Mistletoe'],
                ['state_id' => 18, 'city' => 'Ricetown'],
                ['state_id' => 18, 'city' => 'Vincent'],
                ['state_id' => 18, 'city' => 'Butler'],
                ['state_id' => 18, 'city' => 'De Mossville'],
                ['state_id' => 18, 'city' => 'Falmouth'],
                ['state_id' => 18, 'city' => 'Saul'],
                ['state_id' => 18, 'city' => 'Rowdy'],
                ['state_id' => 18, 'city' => 'Hazard'],
                ['state_id' => 18, 'city' => 'Ary'],
                ['state_id' => 18, 'city' => 'Avawam'],
                ['state_id' => 18, 'city' => 'Bonnyman'],
                ['state_id' => 18, 'city' => 'Buckhorn'],
                ['state_id' => 18, 'city' => 'Bulan'],
                ['state_id' => 18, 'city' => 'Busy'],
                ['state_id' => 18, 'city' => 'Chavies'],
                ['state_id' => 18, 'city' => 'Combs'],
                ['state_id' => 18, 'city' => 'Cornettsville'],
                ['state_id' => 18, 'city' => 'Delphia'],
                ['state_id' => 18, 'city' => 'Dice'],
                ['state_id' => 18, 'city' => 'Dwarf'],
                ['state_id' => 18, 'city' => 'Gays Creek'],
                ['state_id' => 18, 'city' => 'Happy'],
                ['state_id' => 18, 'city' => 'Jeff'],
                ['state_id' => 18, 'city' => 'Krypton'],
                ['state_id' => 18, 'city' => 'Scuddy'],
                ['state_id' => 18, 'city' => 'Slemp'],
                ['state_id' => 18, 'city' => 'Vicco'],
                ['state_id' => 18, 'city' => 'Viper'],
                ['state_id' => 18, 'city' => 'Yerkes'],
                ['state_id' => 18, 'city' => 'Pikeville'],
                ['state_id' => 18, 'city' => 'South Williamson'],
                ['state_id' => 18, 'city' => 'Ashcamp'],
                ['state_id' => 18, 'city' => 'Belcher'],
                ['state_id' => 18, 'city' => 'Belfry'],
                ['state_id' => 18, 'city' => 'Canada'],
                ['state_id' => 18, 'city' => 'Dorton'],
                ['state_id' => 18, 'city' => 'Elkhorn City'],
                ['state_id' => 18, 'city' => 'Fedscreek'],
                ['state_id' => 18, 'city' => 'Fords Branch'],
                ['state_id' => 18, 'city' => 'Forest Hills'],
                ['state_id' => 18, 'city' => 'Freeburn'],
                ['state_id' => 18, 'city' => 'Hardy'],
                ['state_id' => 18, 'city' => 'Hellier'],
                ['state_id' => 18, 'city' => 'Huddy'],
                ['state_id' => 18, 'city' => 'Jonancy'],
                ['state_id' => 18, 'city' => 'Kimper'],
                ['state_id' => 18, 'city' => 'Lick Creek'],
                ['state_id' => 18, 'city' => 'Lookout'],
                ['state_id' => 18, 'city' => 'Mc Andrews'],
                ['state_id' => 18, 'city' => 'Mc Carr'],
                ['state_id' => 18, 'city' => 'Majestic'],
                ['state_id' => 18, 'city' => 'Mouthcard'],
                ['state_id' => 18, 'city' => 'Myra'],
                ['state_id' => 18, 'city' => 'Phelps'],
                ['state_id' => 18, 'city' => 'Phyllis'],
                ['state_id' => 18, 'city' => 'Pinsonfork'],
                ['state_id' => 18, 'city' => 'Raccoon'],
                ['state_id' => 18, 'city' => 'Ransom'],
                ['state_id' => 18, 'city' => 'Regina'],
                ['state_id' => 18, 'city' => 'Robinson Creek'],
                ['state_id' => 18, 'city' => 'Rockhouse'],
                ['state_id' => 18, 'city' => 'Shelbiana'],
                ['state_id' => 18, 'city' => 'Shelby Gap'],
                ['state_id' => 18, 'city' => 'Sidney'],
                ['state_id' => 18, 'city' => 'Steele'],
                ['state_id' => 18, 'city' => 'Stone'],
                ['state_id' => 18, 'city' => 'Stopover'],
                ['state_id' => 18, 'city' => 'Varney'],
                ['state_id' => 18, 'city' => 'Virgie'],
                ['state_id' => 18, 'city' => 'Clay City'],
                ['state_id' => 18, 'city' => 'Slade'],
                ['state_id' => 18, 'city' => 'Stanton'],
                ['state_id' => 18, 'city' => 'Somerset'],
                ['state_id' => 18, 'city' => 'Bronston'],
                ['state_id' => 18, 'city' => 'Burnside'],
                ['state_id' => 18, 'city' => 'Ferguson'],
                ['state_id' => 18, 'city' => 'Nancy'],
                ['state_id' => 18, 'city' => 'Science Hill'],
                ['state_id' => 18, 'city' => 'Tateville'],
                ['state_id' => 18, 'city' => 'West Somerset'],
                ['state_id' => 18, 'city' => 'Eubank'],
                ['state_id' => 18, 'city' => 'Mount Olivet'],
                ['state_id' => 18, 'city' => 'Brodhead'],
                ['state_id' => 18, 'city' => 'Livingston'],
                ['state_id' => 18, 'city' => 'Mount Vernon'],
                ['state_id' => 18, 'city' => 'Orlando'],
                ['state_id' => 18, 'city' => 'Renfro Valley'],
                ['state_id' => 18, 'city' => 'Wildie'],
                ['state_id' => 18, 'city' => 'Clearfield'],
                ['state_id' => 18, 'city' => 'Elliottville'],
                ['state_id' => 18, 'city' => 'Farmers'],
                ['state_id' => 18, 'city' => 'Morehead'],
                ['state_id' => 18, 'city' => 'Jamestown'],
                ['state_id' => 18, 'city' => 'Russell Springs'],
                ['state_id' => 18, 'city' => 'Georgetown'],
                ['state_id' => 18, 'city' => 'Sadieville'],
                ['state_id' => 18, 'city' => 'Stamping Ground'],
                ['state_id' => 18, 'city' => 'Bagdad'],
                ['state_id' => 18, 'city' => 'Finchville'],
                ['state_id' => 18, 'city' => 'Shelbyville'],
                ['state_id' => 18, 'city' => 'Simpsonville'],
                ['state_id' => 18, 'city' => 'Waddy'],
                ['state_id' => 18, 'city' => 'Franklin'],
                ['state_id' => 18, 'city' => 'Mount Eden'],
                ['state_id' => 18, 'city' => 'Taylorsville'],
                ['state_id' => 18, 'city' => 'Campbellsville'],
                ['state_id' => 18, 'city' => 'Elk Horn'],
                ['state_id' => 18, 'city' => 'Mannsville'],
                ['state_id' => 18, 'city' => 'Allensville'],
                ['state_id' => 18, 'city' => 'Clifty'],
                ['state_id' => 18, 'city' => 'Elkton'],
                ['state_id' => 18, 'city' => 'Guthrie'],
                ['state_id' => 18, 'city' => 'Sharon Grove'],
                ['state_id' => 18, 'city' => 'Trenton'],
                ['state_id' => 18, 'city' => 'Cadiz'],
                ['state_id' => 18, 'city' => 'Cerulean'],
                ['state_id' => 18, 'city' => 'Bedford'],
                ['state_id' => 18, 'city' => 'Milton'],
                ['state_id' => 18, 'city' => 'Morganfield'],
                ['state_id' => 18, 'city' => 'Sturgis'],
                ['state_id' => 18, 'city' => 'Sullivan'],
                ['state_id' => 18, 'city' => 'Uniontown'],
                ['state_id' => 18, 'city' => 'Waverly'],
                ['state_id' => 18, 'city' => 'Bowling Green'],
                ['state_id' => 18, 'city' => 'Alvaton'],
                ['state_id' => 18, 'city' => 'Drake'],
                ['state_id' => 18, 'city' => 'Oakland'],
                ['state_id' => 18, 'city' => 'Woodburn'],
                ['state_id' => 18, 'city' => 'Smiths Grove'],
                ['state_id' => 18, 'city' => 'Rockfield'],
                ['state_id' => 18, 'city' => 'Mackville'],
                ['state_id' => 18, 'city' => 'Saint Catharine'],
                ['state_id' => 18, 'city' => 'Springfield'],
                ['state_id' => 18, 'city' => 'Willisburg'],
                ['state_id' => 18, 'city' => 'Monticello'],
                ['state_id' => 18, 'city' => 'Clay'],
                ['state_id' => 18, 'city' => 'Dixon'],
                ['state_id' => 18, 'city' => 'Poole'],
                ['state_id' => 18, 'city' => 'Providence'],
                ['state_id' => 18, 'city' => 'Sebree'],
                ['state_id' => 18, 'city' => 'Slaughters'],
                ['state_id' => 18, 'city' => 'Wheatcroft'],
                ['state_id' => 18, 'city' => 'Corbin'],
                ['state_id' => 18, 'city' => 'Emlyn'],
                ['state_id' => 18, 'city' => 'Rockholds'],
                ['state_id' => 18, 'city' => 'Siler'],
                ['state_id' => 18, 'city' => 'Williamsburg'],
                ['state_id' => 18, 'city' => 'Campton'],
                ['state_id' => 18, 'city' => 'Hazel Green'],
                ['state_id' => 18, 'city' => 'Pine Ridge'],
                ['state_id' => 18, 'city' => 'Rogers'],
                ['state_id' => 18, 'city' => 'Midway'],
                ['state_id' => 18, 'city' => 'Versailles']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
