<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State24TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MN - Minnesota.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 24, 'city' => 'Hill City'],
                ['state_id' => 24, 'city' => 'Jacobson'],
                ['state_id' => 24, 'city' => 'Mcgregor'],
                ['state_id' => 24, 'city' => 'Swatara'],
                ['state_id' => 24, 'city' => 'Tamarack'],
                ['state_id' => 24, 'city' => 'Mc Grath'],
                ['state_id' => 24, 'city' => 'Aitkin'],
                ['state_id' => 24, 'city' => 'Palisade'],
                ['state_id' => 24, 'city' => 'Bethel'],
                ['state_id' => 24, 'city' => 'Cedar'],
                ['state_id' => 24, 'city' => 'Circle Pines'],
                ['state_id' => 24, 'city' => 'Saint Francis'],
                ['state_id' => 24, 'city' => 'Anoka'],
                ['state_id' => 24, 'city' => 'Andover'],
                ['state_id' => 24, 'city' => 'Minneapolis'],
                ['state_id' => 24, 'city' => 'Detroit Lakes'],
                ['state_id' => 24, 'city' => 'Audubon'],
                ['state_id' => 24, 'city' => 'Callaway'],
                ['state_id' => 24, 'city' => 'Frazee'],
                ['state_id' => 24, 'city' => 'Lake Park'],
                ['state_id' => 24, 'city' => 'Ogema'],
                ['state_id' => 24, 'city' => 'Osage'],
                ['state_id' => 24, 'city' => 'Ponsford'],
                ['state_id' => 24, 'city' => 'Richwood'],
                ['state_id' => 24, 'city' => 'Rochert'],
                ['state_id' => 24, 'city' => 'White Earth'],
                ['state_id' => 24, 'city' => 'Wolf Lake'],
                ['state_id' => 24, 'city' => 'Bemidji'],
                ['state_id' => 24, 'city' => 'Blackduck'],
                ['state_id' => 24, 'city' => 'Hines'],
                ['state_id' => 24, 'city' => 'Kelliher'],
                ['state_id' => 24, 'city' => 'Pennington'],
                ['state_id' => 24, 'city' => 'Ponemah'],
                ['state_id' => 24, 'city' => 'Puposky'],
                ['state_id' => 24, 'city' => 'Redby'],
                ['state_id' => 24, 'city' => 'Redlake'],
                ['state_id' => 24, 'city' => 'Solway'],
                ['state_id' => 24, 'city' => 'Tenstrike'],
                ['state_id' => 24, 'city' => 'Waskish'],
                ['state_id' => 24, 'city' => 'Wilton'],
                ['state_id' => 24, 'city' => 'Foley'],
                ['state_id' => 24, 'city' => 'Gilman'],
                ['state_id' => 24, 'city' => 'Oak Park'],
                ['state_id' => 24, 'city' => 'Rice'],
                ['state_id' => 24, 'city' => 'Sauk Rapids'],
                ['state_id' => 24, 'city' => 'Barry'],
                ['state_id' => 24, 'city' => 'Beardsley'],
                ['state_id' => 24, 'city' => 'Clinton'],
                ['state_id' => 24, 'city' => 'Correll'],
                ['state_id' => 24, 'city' => 'Graceville'],
                ['state_id' => 24, 'city' => 'Odessa'],
                ['state_id' => 24, 'city' => 'Ortonville'],
                ['state_id' => 24, 'city' => 'Mankato'],
                ['state_id' => 24, 'city' => 'Amboy'],
                ['state_id' => 24, 'city' => 'Eagle Lake'],
                ['state_id' => 24, 'city' => 'Garden City'],
                ['state_id' => 24, 'city' => 'Good Thunder'],
                ['state_id' => 24, 'city' => 'Lake Crystal'],
                ['state_id' => 24, 'city' => 'Madison Lake'],
                ['state_id' => 24, 'city' => 'Mapleton'],
                ['state_id' => 24, 'city' => 'Pemberton'],
                ['state_id' => 24, 'city' => 'Saint Clair'],
                ['state_id' => 24, 'city' => 'Vernon Center'],
                ['state_id' => 24, 'city' => 'Comfrey'],
                ['state_id' => 24, 'city' => 'Essig'],
                ['state_id' => 24, 'city' => 'Hanska'],
                ['state_id' => 24, 'city' => 'New Ulm'],
                ['state_id' => 24, 'city' => 'Searles'],
                ['state_id' => 24, 'city' => 'Sleepy Eye'],
                ['state_id' => 24, 'city' => 'Springfield'],
                ['state_id' => 24, 'city' => 'Barnum'],
                ['state_id' => 24, 'city' => 'Carlton'],
                ['state_id' => 24, 'city' => 'Cloquet'],
                ['state_id' => 24, 'city' => 'Cromwell'],
                ['state_id' => 24, 'city' => 'Esko'],
                ['state_id' => 24, 'city' => 'Holyoke'],
                ['state_id' => 24, 'city' => 'Kettle River'],
                ['state_id' => 24, 'city' => 'Moose Lake'],
                ['state_id' => 24, 'city' => 'Sawyer'],
                ['state_id' => 24, 'city' => 'Wrenshall'],
                ['state_id' => 24, 'city' => 'Wright'],
                ['state_id' => 24, 'city' => 'Carver'],
                ['state_id' => 24, 'city' => 'Chanhassen'],
                ['state_id' => 24, 'city' => 'Chaska'],
                ['state_id' => 24, 'city' => 'Cologne'],
                ['state_id' => 24, 'city' => 'Hamburg'],
                ['state_id' => 24, 'city' => 'Mayer'],
                ['state_id' => 24, 'city' => 'New Germany'],
                ['state_id' => 24, 'city' => 'Norwood Young America'],
                ['state_id' => 24, 'city' => 'Norwood'],
                ['state_id' => 24, 'city' => 'Victoria'],
                ['state_id' => 24, 'city' => 'Waconia'],
                ['state_id' => 24, 'city' => 'Watertown'],
                ['state_id' => 24, 'city' => 'Young America'],
                ['state_id' => 24, 'city' => 'Ah Gwah Ching'],
                ['state_id' => 24, 'city' => 'Backus'],
                ['state_id' => 24, 'city' => 'Hackensack'],
                ['state_id' => 24, 'city' => 'Pillager'],
                ['state_id' => 24, 'city' => 'Pine River'],
                ['state_id' => 24, 'city' => 'Walker'],
                ['state_id' => 24, 'city' => 'Bena'],
                ['state_id' => 24, 'city' => 'Cass Lake'],
                ['state_id' => 24, 'city' => 'Federal Dam'],
                ['state_id' => 24, 'city' => 'Longville'],
                ['state_id' => 24, 'city' => 'Outing'],
                ['state_id' => 24, 'city' => 'Remer'],
                ['state_id' => 24, 'city' => 'Clara City'],
                ['state_id' => 24, 'city' => 'Maynard'],
                ['state_id' => 24, 'city' => 'Milan'],
                ['state_id' => 24, 'city' => 'Montevideo'],
                ['state_id' => 24, 'city' => 'Watson'],
                ['state_id' => 24, 'city' => 'Almelund'],
                ['state_id' => 24, 'city' => 'Center City'],
                ['state_id' => 24, 'city' => 'Chisago City'],
                ['state_id' => 24, 'city' => 'Harris'],
                ['state_id' => 24, 'city' => 'Lindstrom'],
                ['state_id' => 24, 'city' => 'North Branch'],
                ['state_id' => 24, 'city' => 'Rush City'],
                ['state_id' => 24, 'city' => 'Shafer'],
                ['state_id' => 24, 'city' => 'Stacy'],
                ['state_id' => 24, 'city' => 'Taylors Falls'],
                ['state_id' => 24, 'city' => 'Wyoming'],
                ['state_id' => 24, 'city' => 'Barnesville'],
                ['state_id' => 24, 'city' => 'Comstock'],
                ['state_id' => 24, 'city' => 'Dilworth'],
                ['state_id' => 24, 'city' => 'Felton'],
                ['state_id' => 24, 'city' => 'Georgetown'],
                ['state_id' => 24, 'city' => 'Glyndon'],
                ['state_id' => 24, 'city' => 'Hawley'],
                ['state_id' => 24, 'city' => 'Hitterdal'],
                ['state_id' => 24, 'city' => 'Moorhead'],
                ['state_id' => 24, 'city' => 'Sabin'],
                ['state_id' => 24, 'city' => 'Ulen'],
                ['state_id' => 24, 'city' => 'Bagley'],
                ['state_id' => 24, 'city' => 'Clearbrook'],
                ['state_id' => 24, 'city' => 'Gonvick'],
                ['state_id' => 24, 'city' => 'Leonard'],
                ['state_id' => 24, 'city' => 'Shevlin'],
                ['state_id' => 24, 'city' => 'Grand Marais'],
                ['state_id' => 24, 'city' => 'Grand Portage'],
                ['state_id' => 24, 'city' => 'Hovland'],
                ['state_id' => 24, 'city' => 'Lutsen'],
                ['state_id' => 24, 'city' => 'Schroeder'],
                ['state_id' => 24, 'city' => 'Tofte'],
                ['state_id' => 24, 'city' => 'Windom'],
                ['state_id' => 24, 'city' => 'Bingham Lake'],
                ['state_id' => 24, 'city' => 'Jeffers'],
                ['state_id' => 24, 'city' => 'Mountain Lake'],
                ['state_id' => 24, 'city' => 'Storden'],
                ['state_id' => 24, 'city' => 'Westbrook'],
                ['state_id' => 24, 'city' => 'Brainerd'],
                ['state_id' => 24, 'city' => 'Baxter'],
                ['state_id' => 24, 'city' => 'Crosby'],
                ['state_id' => 24, 'city' => 'Crosslake'],
                ['state_id' => 24, 'city' => 'Deerwood'],
                ['state_id' => 24, 'city' => 'Emily'],
                ['state_id' => 24, 'city' => 'Fifty Lakes'],
                ['state_id' => 24, 'city' => 'Fort Ripley'],
                ['state_id' => 24, 'city' => 'Garrison'],
                ['state_id' => 24, 'city' => 'Ironton'],
                ['state_id' => 24, 'city' => 'Jenkins'],
                ['state_id' => 24, 'city' => 'Lake Hubert'],
                ['state_id' => 24, 'city' => 'Merrifield'],
                ['state_id' => 24, 'city' => 'Nisswa'],
                ['state_id' => 24, 'city' => 'Pequot Lakes'],
                ['state_id' => 24, 'city' => 'Castle Rock'],
                ['state_id' => 24, 'city' => 'Farmington'],
                ['state_id' => 24, 'city' => 'Hampton'],
                ['state_id' => 24, 'city' => 'Hastings'],
                ['state_id' => 24, 'city' => 'Lakeville'],
                ['state_id' => 24, 'city' => 'Randolph'],
                ['state_id' => 24, 'city' => 'Rosemount'],
                ['state_id' => 24, 'city' => 'South Saint Paul'],
                ['state_id' => 24, 'city' => 'Inver Grove Heights'],
                ['state_id' => 24, 'city' => 'Vermillion'],
                ['state_id' => 24, 'city' => 'Saint Paul'],
                ['state_id' => 24, 'city' => 'Mendota'],
                ['state_id' => 24, 'city' => 'Burnsville'],
                ['state_id' => 24, 'city' => 'Claremont'],
                ['state_id' => 24, 'city' => 'Dodge Center'],
                ['state_id' => 24, 'city' => 'Hayfield'],
                ['state_id' => 24, 'city' => 'Kasson'],
                ['state_id' => 24, 'city' => 'Mantorville'],
                ['state_id' => 24, 'city' => 'West Concord'],
                ['state_id' => 24, 'city' => 'Alexandria'],
                ['state_id' => 24, 'city' => 'Brandon'],
                ['state_id' => 24, 'city' => 'Carlos'],
                ['state_id' => 24, 'city' => 'Evansville'],
                ['state_id' => 24, 'city' => 'Garfield'],
                ['state_id' => 24, 'city' => 'Holmes City'],
                ['state_id' => 24, 'city' => 'Kensington'],
                ['state_id' => 24, 'city' => 'Miltona'],
                ['state_id' => 24, 'city' => 'Nelson'],
                ['state_id' => 24, 'city' => 'Osakis'],
                ['state_id' => 24, 'city' => 'Blue Earth'],
                ['state_id' => 24, 'city' => 'Bricelyn'],
                ['state_id' => 24, 'city' => 'Delavan'],
                ['state_id' => 24, 'city' => 'Easton'],
                ['state_id' => 24, 'city' => 'Elmore'],
                ['state_id' => 24, 'city' => 'Frost'],
                ['state_id' => 24, 'city' => 'Huntley'],
                ['state_id' => 24, 'city' => 'Kiester'],
                ['state_id' => 24, 'city' => 'Minnesota Lake'],
                ['state_id' => 24, 'city' => 'Wells'],
                ['state_id' => 24, 'city' => 'Winnebago'],
                ['state_id' => 24, 'city' => 'Canton'],
                ['state_id' => 24, 'city' => 'Chatfield'],
                ['state_id' => 24, 'city' => 'Fountain'],
                ['state_id' => 24, 'city' => 'Harmony'],
                ['state_id' => 24, 'city' => 'Lanesboro'],
                ['state_id' => 24, 'city' => 'Mabel'],
                ['state_id' => 24, 'city' => 'Ostrander'],
                ['state_id' => 24, 'city' => 'Peterson'],
                ['state_id' => 24, 'city' => 'Preston'],
                ['state_id' => 24, 'city' => 'Rushford'],
                ['state_id' => 24, 'city' => 'Spring Valley'],
                ['state_id' => 24, 'city' => 'Wykoff'],
                ['state_id' => 24, 'city' => 'Albert Lea'],
                ['state_id' => 24, 'city' => 'Alden'],
                ['state_id' => 24, 'city' => 'Clarks Grove'],
                ['state_id' => 24, 'city' => 'Conger'],
                ['state_id' => 24, 'city' => 'Emmons'],
                ['state_id' => 24, 'city' => 'Freeborn'],
                ['state_id' => 24, 'city' => 'Geneva'],
                ['state_id' => 24, 'city' => 'Glenville'],
                ['state_id' => 24, 'city' => 'Hartland'],
                ['state_id' => 24, 'city' => 'Hayward'],
                ['state_id' => 24, 'city' => 'Hollandale'],
                ['state_id' => 24, 'city' => 'Twin Lakes'],
                ['state_id' => 24, 'city' => 'Cannon Falls'],
                ['state_id' => 24, 'city' => 'Dennison'],
                ['state_id' => 24, 'city' => 'Frontenac'],
                ['state_id' => 24, 'city' => 'Goodhue'],
                ['state_id' => 24, 'city' => 'Red Wing'],
                ['state_id' => 24, 'city' => 'Welch'],
                ['state_id' => 24, 'city' => 'Kenyon'],
                ['state_id' => 24, 'city' => 'Pine Island'],
                ['state_id' => 24, 'city' => 'Wanamingo'],
                ['state_id' => 24, 'city' => 'Zumbrota'],
                ['state_id' => 24, 'city' => 'Herman'],
                ['state_id' => 24, 'city' => 'Norcross'],
                ['state_id' => 24, 'city' => 'Ashby'],
                ['state_id' => 24, 'city' => 'Barrett'],
                ['state_id' => 24, 'city' => 'Hoffman'],
                ['state_id' => 24, 'city' => 'Elbow Lake'],
                ['state_id' => 24, 'city' => 'Wendell'],
                ['state_id' => 24, 'city' => 'Hopkins'],
                ['state_id' => 24, 'city' => 'Maple Grove'],
                ['state_id' => 24, 'city' => 'Champlin'],
                ['state_id' => 24, 'city' => 'Crystal Bay'],
                ['state_id' => 24, 'city' => 'Dayton'],
                ['state_id' => 24, 'city' => 'Excelsior'],
                ['state_id' => 24, 'city' => 'Hamel'],
                ['state_id' => 24, 'city' => 'Eden Prairie'],
                ['state_id' => 24, 'city' => 'Minnetonka'],
                ['state_id' => 24, 'city' => 'Maple Plain'],
                ['state_id' => 24, 'city' => 'Long Lake'],
                ['state_id' => 24, 'city' => 'Loretto'],
                ['state_id' => 24, 'city' => 'Minnetonka Beach'],
                ['state_id' => 24, 'city' => 'Mound'],
                ['state_id' => 24, 'city' => 'Osseo'],
                ['state_id' => 24, 'city' => 'Rogers'],
                ['state_id' => 24, 'city' => 'Saint Bonifacius'],
                ['state_id' => 24, 'city' => 'Spring Park'],
                ['state_id' => 24, 'city' => 'Wayzata'],
                ['state_id' => 24, 'city' => 'Navarre'],
                ['state_id' => 24, 'city' => 'Rockford'],
                ['state_id' => 24, 'city' => 'Howard Lake'],
                ['state_id' => 24, 'city' => 'Brownsville'],
                ['state_id' => 24, 'city' => 'Caledonia'],
                ['state_id' => 24, 'city' => 'Eitzen'],
                ['state_id' => 24, 'city' => 'Hokah'],
                ['state_id' => 24, 'city' => 'Houston'],
                ['state_id' => 24, 'city' => 'La Crescent'],
                ['state_id' => 24, 'city' => 'Spring Grove'],
                ['state_id' => 24, 'city' => 'Akeley'],
                ['state_id' => 24, 'city' => 'Benedict'],
                ['state_id' => 24, 'city' => 'Lake George'],
                ['state_id' => 24, 'city' => 'Laporte'],
                ['state_id' => 24, 'city' => 'Nevis'],
                ['state_id' => 24, 'city' => 'Park Rapids'],
                ['state_id' => 24, 'city' => 'Braham'],
                ['state_id' => 24, 'city' => 'Cambridge'],
                ['state_id' => 24, 'city' => 'Dalbo'],
                ['state_id' => 24, 'city' => 'Grandy'],
                ['state_id' => 24, 'city' => 'Isanti'],
                ['state_id' => 24, 'city' => 'Stanchfield'],
                ['state_id' => 24, 'city' => 'Bovey'],
                ['state_id' => 24, 'city' => 'Calumet'],
                ['state_id' => 24, 'city' => 'Cohasset'],
                ['state_id' => 24, 'city' => 'Coleraine'],
                ['state_id' => 24, 'city' => 'Grand Rapids'],
                ['state_id' => 24, 'city' => 'Goodland'],
                ['state_id' => 24, 'city' => 'Keewatin'],
                ['state_id' => 24, 'city' => 'Marble'],
                ['state_id' => 24, 'city' => 'Nashwauk'],
                ['state_id' => 24, 'city' => 'Pengilly'],
                ['state_id' => 24, 'city' => 'Swan River'],
                ['state_id' => 24, 'city' => 'Taconite'],
                ['state_id' => 24, 'city' => 'Warba'],
                ['state_id' => 24, 'city' => 'Bigfork'],
                ['state_id' => 24, 'city' => 'Bowstring'],
                ['state_id' => 24, 'city' => 'Deer River'],
                ['state_id' => 24, 'city' => 'Talmoon'],
                ['state_id' => 24, 'city' => 'Effie'],
                ['state_id' => 24, 'city' => 'Marcell'],
                ['state_id' => 24, 'city' => 'Max'],
                ['state_id' => 24, 'city' => 'Spring Lake'],
                ['state_id' => 24, 'city' => 'Squaw Lake'],
                ['state_id' => 24, 'city' => 'Wirt'],
                ['state_id' => 24, 'city' => 'Alpha'],
                ['state_id' => 24, 'city' => 'Heron Lake'],
                ['state_id' => 24, 'city' => 'Jackson'],
                ['state_id' => 24, 'city' => 'Lakefield'],
                ['state_id' => 24, 'city' => 'Okabena'],
                ['state_id' => 24, 'city' => 'Mora'],
                ['state_id' => 24, 'city' => 'Ogilvie'],
                ['state_id' => 24, 'city' => 'Willmar'],
                ['state_id' => 24, 'city' => 'Atwater'],
                ['state_id' => 24, 'city' => 'Blomkest'],
                ['state_id' => 24, 'city' => 'Kandiyohi'],
                ['state_id' => 24, 'city' => 'Lake Lillian'],
                ['state_id' => 24, 'city' => 'New London'],
                ['state_id' => 24, 'city' => 'Pennock'],
                ['state_id' => 24, 'city' => 'Prinsburg'],
                ['state_id' => 24, 'city' => 'Raymond'],
                ['state_id' => 24, 'city' => 'Spicer'],
                ['state_id' => 24, 'city' => 'Sunburg'],
                ['state_id' => 24, 'city' => 'Donaldson'],
                ['state_id' => 24, 'city' => 'Hallock'],
                ['state_id' => 24, 'city' => 'Halma'],
                ['state_id' => 24, 'city' => 'Humboldt'],
                ['state_id' => 24, 'city' => 'Karlstad'],
                ['state_id' => 24, 'city' => 'Kennedy'],
                ['state_id' => 24, 'city' => 'Lake Bronson'],
                ['state_id' => 24, 'city' => 'Lancaster'],
                ['state_id' => 24, 'city' => 'Noyes'],
                ['state_id' => 24, 'city' => 'Saint Vincent'],
                ['state_id' => 24, 'city' => 'Big Falls'],
                ['state_id' => 24, 'city' => 'Birchdale'],
                ['state_id' => 24, 'city' => 'International Falls'],
                ['state_id' => 24, 'city' => 'Littlefork'],
                ['state_id' => 24, 'city' => 'Loman'],
                ['state_id' => 24, 'city' => 'Margie'],
                ['state_id' => 24, 'city' => 'Mizpah'],
                ['state_id' => 24, 'city' => 'Northome'],
                ['state_id' => 24, 'city' => 'Ranier'],
                ['state_id' => 24, 'city' => 'Kabetogama'],
                ['state_id' => 24, 'city' => 'South International Falls'],
                ['state_id' => 24, 'city' => 'Bellingham'],
                ['state_id' => 24, 'city' => 'Boyd'],
                ['state_id' => 24, 'city' => 'Dawson'],
                ['state_id' => 24, 'city' => 'Madison'],
                ['state_id' => 24, 'city' => 'Marietta'],
                ['state_id' => 24, 'city' => 'Beaver Bay'],
                ['state_id' => 24, 'city' => 'Finland'],
                ['state_id' => 24, 'city' => 'Isabella'],
                ['state_id' => 24, 'city' => 'Knife River'],
                ['state_id' => 24, 'city' => 'Silver Bay'],
                ['state_id' => 24, 'city' => 'Two Harbors'],
                ['state_id' => 24, 'city' => 'Baudette'],
                ['state_id' => 24, 'city' => 'Williams'],
                ['state_id' => 24, 'city' => 'Angle Inlet'],
                ['state_id' => 24, 'city' => 'Oak Island'],
                ['state_id' => 24, 'city' => 'Cleveland'],
                ['state_id' => 24, 'city' => 'Elysian'],
                ['state_id' => 24, 'city' => 'Kasota'],
                ['state_id' => 24, 'city' => 'Kilkenny'],
                ['state_id' => 24, 'city' => 'Le Center'],
                ['state_id' => 24, 'city' => 'Le Sueur'],
                ['state_id' => 24, 'city' => 'Montgomery'],
                ['state_id' => 24, 'city' => 'New Prague'],
                ['state_id' => 24, 'city' => 'Waterville'],
                ['state_id' => 24, 'city' => 'Arco'],
                ['state_id' => 24, 'city' => 'Hendricks'],
                ['state_id' => 24, 'city' => 'Ivanhoe'],
                ['state_id' => 24, 'city' => 'Lake Benton'],
                ['state_id' => 24, 'city' => 'Tyler'],
                ['state_id' => 24, 'city' => 'Balaton'],
                ['state_id' => 24, 'city' => 'Garvin'],
                ['state_id' => 24, 'city' => 'Lynd'],
                ['state_id' => 24, 'city' => 'Russell'],
                ['state_id' => 24, 'city' => 'Tracy'],
                ['state_id' => 24, 'city' => 'Cottonwood'],
                ['state_id' => 24, 'city' => 'Ghent'],
                ['state_id' => 24, 'city' => 'Marshall'],
                ['state_id' => 24, 'city' => 'Minneota'],
                ['state_id' => 24, 'city' => 'Taunton'],
                ['state_id' => 24, 'city' => 'Brownton'],
                ['state_id' => 24, 'city' => 'Glencoe'],
                ['state_id' => 24, 'city' => 'Hutchinson'],
                ['state_id' => 24, 'city' => 'Lester Prairie'],
                ['state_id' => 24, 'city' => 'Plato'],
                ['state_id' => 24, 'city' => 'Silver Lake'],
                ['state_id' => 24, 'city' => 'Stewart'],
                ['state_id' => 24, 'city' => 'Winsted'],
                ['state_id' => 24, 'city' => 'Bejou'],
                ['state_id' => 24, 'city' => 'Mahnomen'],
                ['state_id' => 24, 'city' => 'Naytahwaush'],
                ['state_id' => 24, 'city' => 'Waubun'],
                ['state_id' => 24, 'city' => 'Alvarado'],
                ['state_id' => 24, 'city' => 'Argyle'],
                ['state_id' => 24, 'city' => 'Gatzke'],
                ['state_id' => 24, 'city' => 'Grygla'],
                ['state_id' => 24, 'city' => 'Middle River'],
                ['state_id' => 24, 'city' => 'Newfolden'],
                ['state_id' => 24, 'city' => 'Oslo'],
                ['state_id' => 24, 'city' => 'Stephen'],
                ['state_id' => 24, 'city' => 'Strandquist'],
                ['state_id' => 24, 'city' => 'Viking'],
                ['state_id' => 24, 'city' => 'Warren'],
                ['state_id' => 24, 'city' => 'Fairmont'],
                ['state_id' => 24, 'city' => 'Granada'],
                ['state_id' => 24, 'city' => 'Northrop'],
                ['state_id' => 24, 'city' => 'Truman'],
                ['state_id' => 24, 'city' => 'Ceylon'],
                ['state_id' => 24, 'city' => 'Dunnell'],
                ['state_id' => 24, 'city' => 'Ormsby'],
                ['state_id' => 24, 'city' => 'Sherburn'],
                ['state_id' => 24, 'city' => 'Trimont'],
                ['state_id' => 24, 'city' => 'Welcome'],
                ['state_id' => 24, 'city' => 'Darwin'],
                ['state_id' => 24, 'city' => 'Dassel'],
                ['state_id' => 24, 'city' => 'Eden Valley'],
                ['state_id' => 24, 'city' => 'Litchfield'],
                ['state_id' => 24, 'city' => 'Watkins'],
                ['state_id' => 24, 'city' => 'Cosmos'],
                ['state_id' => 24, 'city' => 'Grove City'],
                ['state_id' => 24, 'city' => 'Princeton'],
                ['state_id' => 24, 'city' => 'Bock'],
                ['state_id' => 24, 'city' => 'Foreston'],
                ['state_id' => 24, 'city' => 'Isle'],
                ['state_id' => 24, 'city' => 'Milaca'],
                ['state_id' => 24, 'city' => 'Onamia'],
                ['state_id' => 24, 'city' => 'Pease'],
                ['state_id' => 24, 'city' => 'Wahkon'],
                ['state_id' => 24, 'city' => 'Bowlus'],
                ['state_id' => 24, 'city' => 'Buckman'],
                ['state_id' => 24, 'city' => 'Flensburg'],
                ['state_id' => 24, 'city' => 'Hillman'],
                ['state_id' => 24, 'city' => 'Lastrup'],
                ['state_id' => 24, 'city' => 'Little Falls'],
                ['state_id' => 24, 'city' => 'Pierz'],
                ['state_id' => 24, 'city' => 'Royalton'],
                ['state_id' => 24, 'city' => 'Swanville'],
                ['state_id' => 24, 'city' => 'Upsala'],
                ['state_id' => 24, 'city' => 'Waite Park'],
                ['state_id' => 24, 'city' => 'Cushing'],
                ['state_id' => 24, 'city' => 'Motley'],
                ['state_id' => 24, 'city' => 'Randall'],
                ['state_id' => 24, 'city' => 'Adams'],
                ['state_id' => 24, 'city' => 'Austin'],
                ['state_id' => 24, 'city' => 'Brownsdale'],
                ['state_id' => 24, 'city' => 'Dexter'],
                ['state_id' => 24, 'city' => 'Elkton'],
                ['state_id' => 24, 'city' => 'Grand Meadow'],
                ['state_id' => 24, 'city' => 'Lansing'],
                ['state_id' => 24, 'city' => 'Le Roy'],
                ['state_id' => 24, 'city' => 'Lyle'],
                ['state_id' => 24, 'city' => 'Racine'],
                ['state_id' => 24, 'city' => 'Rose Creek'],
                ['state_id' => 24, 'city' => 'Sargeant'],
                ['state_id' => 24, 'city' => 'Taopi'],
                ['state_id' => 24, 'city' => 'Waltham'],
                ['state_id' => 24, 'city' => 'Avoca'],
                ['state_id' => 24, 'city' => 'Chandler'],
                ['state_id' => 24, 'city' => 'Currie'],
                ['state_id' => 24, 'city' => 'Dovray'],
                ['state_id' => 24, 'city' => 'Fulda'],
                ['state_id' => 24, 'city' => 'Iona'],
                ['state_id' => 24, 'city' => 'Lake Wilson'],
                ['state_id' => 24, 'city' => 'Slayton'],
                ['state_id' => 24, 'city' => 'Courtland'],
                ['state_id' => 24, 'city' => 'Lafayette'],
                ['state_id' => 24, 'city' => 'Nicollet'],
                ['state_id' => 24, 'city' => 'Saint Peter'],
                ['state_id' => 24, 'city' => 'Adrian'],
                ['state_id' => 24, 'city' => 'Bigelow'],
                ['state_id' => 24, 'city' => 'Brewster'],
                ['state_id' => 24, 'city' => 'Ellsworth'],
                ['state_id' => 24, 'city' => 'Leota'],
                ['state_id' => 24, 'city' => 'Lismore'],
                ['state_id' => 24, 'city' => 'Reading'],
                ['state_id' => 24, 'city' => 'Round Lake'],
                ['state_id' => 24, 'city' => 'Rushmore'],
                ['state_id' => 24, 'city' => 'Wilmont'],
                ['state_id' => 24, 'city' => 'Worthington'],
                ['state_id' => 24, 'city' => 'Ada'],
                ['state_id' => 24, 'city' => 'Borup'],
                ['state_id' => 24, 'city' => 'Flom'],
                ['state_id' => 24, 'city' => 'Gary'],
                ['state_id' => 24, 'city' => 'Halstad'],
                ['state_id' => 24, 'city' => 'Hendrum'],
                ['state_id' => 24, 'city' => 'Perley'],
                ['state_id' => 24, 'city' => 'Shelly'],
                ['state_id' => 24, 'city' => 'Twin Valley'],
                ['state_id' => 24, 'city' => 'Rochester'],
                ['state_id' => 24, 'city' => 'Byron'],
                ['state_id' => 24, 'city' => 'Dover'],
                ['state_id' => 24, 'city' => 'Eyota'],
                ['state_id' => 24, 'city' => 'Oronoco'],
                ['state_id' => 24, 'city' => 'Stewartville'],
                ['state_id' => 24, 'city' => 'Dalton'],
                ['state_id' => 24, 'city' => 'Parkers Prairie'],
                ['state_id' => 24, 'city' => 'Battle Lake'],
                ['state_id' => 24, 'city' => 'Bluffton'],
                ['state_id' => 24, 'city' => 'Clitherall'],
                ['state_id' => 24, 'city' => 'Deer Creek'],
                ['state_id' => 24, 'city' => 'Dent'],
                ['state_id' => 24, 'city' => 'Elizabeth'],
                ['state_id' => 24, 'city' => 'Erhard'],
                ['state_id' => 24, 'city' => 'Fergus Falls'],
                ['state_id' => 24, 'city' => 'Henning'],
                ['state_id' => 24, 'city' => 'New York Mills'],
                ['state_id' => 24, 'city' => 'Ottertail'],
                ['state_id' => 24, 'city' => 'Pelican Rapids'],
                ['state_id' => 24, 'city' => 'Perham'],
                ['state_id' => 24, 'city' => 'Richville'],
                ['state_id' => 24, 'city' => 'Underwood'],
                ['state_id' => 24, 'city' => 'Vergas'],
                ['state_id' => 24, 'city' => 'Vining'],
                ['state_id' => 24, 'city' => 'Thief River Falls'],
                ['state_id' => 24, 'city' => 'Goodridge'],
                ['state_id' => 24, 'city' => 'Saint Hilaire'],
                ['state_id' => 24, 'city' => 'Brook Park'],
                ['state_id' => 24, 'city' => 'Grasston'],
                ['state_id' => 24, 'city' => 'Henriette'],
                ['state_id' => 24, 'city' => 'Hinckley'],
                ['state_id' => 24, 'city' => 'Pine City'],
                ['state_id' => 24, 'city' => 'Rock Creek'],
                ['state_id' => 24, 'city' => 'Sandstone'],
                ['state_id' => 24, 'city' => 'Askov'],
                ['state_id' => 24, 'city' => 'Bruno'],
                ['state_id' => 24, 'city' => 'Finlayson'],
                ['state_id' => 24, 'city' => 'Kerrick'],
                ['state_id' => 24, 'city' => 'Sturgeon Lake'],
                ['state_id' => 24, 'city' => 'Willow River'],
                ['state_id' => 24, 'city' => 'Edgerton'],
                ['state_id' => 24, 'city' => 'Holland'],
                ['state_id' => 24, 'city' => 'Ihlen'],
                ['state_id' => 24, 'city' => 'Jasper'],
                ['state_id' => 24, 'city' => 'Pipestone'],
                ['state_id' => 24, 'city' => 'Ruthton'],
                ['state_id' => 24, 'city' => 'Woodstock'],
                ['state_id' => 24, 'city' => 'Beltrami'],
                ['state_id' => 24, 'city' => 'Climax'],
                ['state_id' => 24, 'city' => 'Erskine'],
                ['state_id' => 24, 'city' => 'Fertile'],
                ['state_id' => 24, 'city' => 'Fosston'],
                ['state_id' => 24, 'city' => 'Mcintosh'],
                ['state_id' => 24, 'city' => 'Nielsville'],
                ['state_id' => 24, 'city' => 'Winger'],
                ['state_id' => 24, 'city' => 'Gully'],
                ['state_id' => 24, 'city' => 'Lengby'],
                ['state_id' => 24, 'city' => 'Trail'],
                ['state_id' => 24, 'city' => 'Crookston'],
                ['state_id' => 24, 'city' => 'East Grand Forks'],
                ['state_id' => 24, 'city' => 'Euclid'],
                ['state_id' => 24, 'city' => 'Fisher'],
                ['state_id' => 24, 'city' => 'Mentor'],
                ['state_id' => 24, 'city' => 'Cyrus'],
                ['state_id' => 24, 'city' => 'Farwell'],
                ['state_id' => 24, 'city' => 'Glenwood'],
                ['state_id' => 24, 'city' => 'Lowry'],
                ['state_id' => 24, 'city' => 'Starbuck'],
                ['state_id' => 24, 'city' => 'Villard'],
                ['state_id' => 24, 'city' => 'Brooks'],
                ['state_id' => 24, 'city' => 'Oklee'],
                ['state_id' => 24, 'city' => 'Plummer'],
                ['state_id' => 24, 'city' => 'Red Lake Falls'],
                ['state_id' => 24, 'city' => 'Sanborn'],
                ['state_id' => 24, 'city' => 'Lamberton'],
                ['state_id' => 24, 'city' => 'Revere'],
                ['state_id' => 24, 'city' => 'Walnut Grove'],
                ['state_id' => 24, 'city' => 'Belview'],
                ['state_id' => 24, 'city' => 'Clements'],
                ['state_id' => 24, 'city' => 'Lucan'],
                ['state_id' => 24, 'city' => 'Milroy'],
                ['state_id' => 24, 'city' => 'Morgan'],
                ['state_id' => 24, 'city' => 'Redwood Falls'],
                ['state_id' => 24, 'city' => 'Seaforth'],
                ['state_id' => 24, 'city' => 'Vesta'],
                ['state_id' => 24, 'city' => 'Wabasso'],
                ['state_id' => 24, 'city' => 'Wanda'],
                ['state_id' => 24, 'city' => 'Bird Island'],
                ['state_id' => 24, 'city' => 'Buffalo Lake'],
                ['state_id' => 24, 'city' => 'Fairfax'],
                ['state_id' => 24, 'city' => 'Franklin'],
                ['state_id' => 24, 'city' => 'Hector'],
                ['state_id' => 24, 'city' => 'Danube'],
                ['state_id' => 24, 'city' => 'Morton'],
                ['state_id' => 24, 'city' => 'Olivia'],
                ['state_id' => 24, 'city' => 'Renville'],
                ['state_id' => 24, 'city' => 'Sacred Heart'],
                ['state_id' => 24, 'city' => 'Dundas'],
                ['state_id' => 24, 'city' => 'Faribault'],
                ['state_id' => 24, 'city' => 'Lonsdale'],
                ['state_id' => 24, 'city' => 'Morristown'],
                ['state_id' => 24, 'city' => 'Nerstrand'],
                ['state_id' => 24, 'city' => 'Northfield'],
                ['state_id' => 24, 'city' => 'Warsaw'],
                ['state_id' => 24, 'city' => 'Webster'],
                ['state_id' => 24, 'city' => 'Beaver Creek'],
                ['state_id' => 24, 'city' => 'Hardwick'],
                ['state_id' => 24, 'city' => 'Hills'],
                ['state_id' => 24, 'city' => 'Kanaranzi'],
                ['state_id' => 24, 'city' => 'Kenneth'],
                ['state_id' => 24, 'city' => 'Luverne'],
                ['state_id' => 24, 'city' => 'Magnolia'],
                ['state_id' => 24, 'city' => 'Steen'],
                ['state_id' => 24, 'city' => 'Roosevelt'],
                ['state_id' => 24, 'city' => 'Swift'],
                ['state_id' => 24, 'city' => 'Badger'],
                ['state_id' => 24, 'city' => 'Greenbush'],
                ['state_id' => 24, 'city' => 'Roseau'],
                ['state_id' => 24, 'city' => 'Salol'],
                ['state_id' => 24, 'city' => 'Strathcona'],
                ['state_id' => 24, 'city' => 'Wannaska'],
                ['state_id' => 24, 'city' => 'Warroad'],
                ['state_id' => 24, 'city' => 'Brimson'],
                ['state_id' => 24, 'city' => 'Alborn'],
                ['state_id' => 24, 'city' => 'Angora'],
                ['state_id' => 24, 'city' => 'Aurora'],
                ['state_id' => 24, 'city' => 'Babbitt'],
                ['state_id' => 24, 'city' => 'Biwabik'],
                ['state_id' => 24, 'city' => 'Britt'],
                ['state_id' => 24, 'city' => 'Brookston'],
                ['state_id' => 24, 'city' => 'Buhl'],
                ['state_id' => 24, 'city' => 'Canyon'],
                ['state_id' => 24, 'city' => 'Chisholm'],
                ['state_id' => 24, 'city' => 'Cook'],
                ['state_id' => 24, 'city' => 'Cotton'],
                ['state_id' => 24, 'city' => 'Crane Lake'],
                ['state_id' => 24, 'city' => 'Ely'],
                ['state_id' => 24, 'city' => 'Embarrass'],
                ['state_id' => 24, 'city' => 'Eveleth'],
                ['state_id' => 24, 'city' => 'Floodwood'],
                ['state_id' => 24, 'city' => 'Forbes'],
                ['state_id' => 24, 'city' => 'Gilbert'],
                ['state_id' => 24, 'city' => 'Hibbing'],
                ['state_id' => 24, 'city' => 'Hoyt Lakes'],
                ['state_id' => 24, 'city' => 'Iron'],
                ['state_id' => 24, 'city' => 'Kinney'],
                ['state_id' => 24, 'city' => 'Makinen'],
                ['state_id' => 24, 'city' => 'Meadowlands'],
                ['state_id' => 24, 'city' => 'Melrude'],
                ['state_id' => 24, 'city' => 'Mountain Iron'],
                ['state_id' => 24, 'city' => 'Orr'],
                ['state_id' => 24, 'city' => 'Nett Lake'],
                ['state_id' => 24, 'city' => 'Virginia'],
                ['state_id' => 24, 'city' => 'Saginaw'],
                ['state_id' => 24, 'city' => 'Side Lake'],
                ['state_id' => 24, 'city' => 'Soudan'],
                ['state_id' => 24, 'city' => 'Tower'],
                ['state_id' => 24, 'city' => 'Twig'],
                ['state_id' => 24, 'city' => 'Winton'],
                ['state_id' => 24, 'city' => 'Duluth'],
                ['state_id' => 24, 'city' => 'Elko New Market'],
                ['state_id' => 24, 'city' => 'Jordan'],
                ['state_id' => 24, 'city' => 'Prior Lake'],
                ['state_id' => 24, 'city' => 'Savage'],
                ['state_id' => 24, 'city' => 'Shakopee'],
                ['state_id' => 24, 'city' => 'Belle Plaine'],
                ['state_id' => 24, 'city' => 'Becker'],
                ['state_id' => 24, 'city' => 'Big Lake'],
                ['state_id' => 24, 'city' => 'Clear Lake'],
                ['state_id' => 24, 'city' => 'Elk River'],
                ['state_id' => 24, 'city' => 'Santiago'],
                ['state_id' => 24, 'city' => 'Zimmerman'],
                ['state_id' => 24, 'city' => 'Arlington'],
                ['state_id' => 24, 'city' => 'Gaylord'],
                ['state_id' => 24, 'city' => 'Gibbon'],
                ['state_id' => 24, 'city' => 'Green Isle'],
                ['state_id' => 24, 'city' => 'New Auburn'],
                ['state_id' => 24, 'city' => 'Winthrop'],
                ['state_id' => 24, 'city' => 'Henderson'],
                ['state_id' => 24, 'city' => 'Kimball'],
                ['state_id' => 24, 'city' => 'Saint Cloud'],
                ['state_id' => 24, 'city' => 'Albany'],
                ['state_id' => 24, 'city' => 'Avon'],
                ['state_id' => 24, 'city' => 'Belgrade'],
                ['state_id' => 24, 'city' => 'Brooten'],
                ['state_id' => 24, 'city' => 'Cold Spring'],
                ['state_id' => 24, 'city' => 'Collegeville'],
                ['state_id' => 24, 'city' => 'Elrosa'],
                ['state_id' => 24, 'city' => 'Freeport'],
                ['state_id' => 24, 'city' => 'Greenwald'],
                ['state_id' => 24, 'city' => 'Holdingford'],
                ['state_id' => 24, 'city' => 'Melrose'],
                ['state_id' => 24, 'city' => 'New Munich'],
                ['state_id' => 24, 'city' => 'Paynesville'],
                ['state_id' => 24, 'city' => 'Richmond'],
                ['state_id' => 24, 'city' => 'Rockville'],
                ['state_id' => 24, 'city' => 'Roscoe'],
                ['state_id' => 24, 'city' => 'Saint Joseph'],
                ['state_id' => 24, 'city' => 'Saint Stephen'],
                ['state_id' => 24, 'city' => 'Saint Martin'],
                ['state_id' => 24, 'city' => 'Sartell'],
                ['state_id' => 24, 'city' => 'Sauk Centre'],
                ['state_id' => 24, 'city' => 'Medford'],
                ['state_id' => 24, 'city' => 'Owatonna'],
                ['state_id' => 24, 'city' => 'Blooming Prairie'],
                ['state_id' => 24, 'city' => 'Ellendale'],
                ['state_id' => 24, 'city' => 'Hope'],
                ['state_id' => 24, 'city' => 'Alberta'],
                ['state_id' => 24, 'city' => 'Chokio'],
                ['state_id' => 24, 'city' => 'Donnelly'],
                ['state_id' => 24, 'city' => 'Hancock'],
                ['state_id' => 24, 'city' => 'Morris'],
                ['state_id' => 24, 'city' => 'Appleton'],
                ['state_id' => 24, 'city' => 'Benson'],
                ['state_id' => 24, 'city' => 'Clontarf'],
                ['state_id' => 24, 'city' => 'Danvers'],
                ['state_id' => 24, 'city' => 'Holloway'],
                ['state_id' => 24, 'city' => 'Kerkhoven'],
                ['state_id' => 24, 'city' => 'Murdock'],
                ['state_id' => 24, 'city' => 'Burtrum'],
                ['state_id' => 24, 'city' => 'Grey Eagle'],
                ['state_id' => 24, 'city' => 'Long Prairie'],
                ['state_id' => 24, 'city' => 'West Union'],
                ['state_id' => 24, 'city' => 'Bertha'],
                ['state_id' => 24, 'city' => 'Browerville'],
                ['state_id' => 24, 'city' => 'Clarissa'],
                ['state_id' => 24, 'city' => 'Eagle Bend'],
                ['state_id' => 24, 'city' => 'Hewitt'],
                ['state_id' => 24, 'city' => 'Staples'],
                ['state_id' => 24, 'city' => 'Browns Valley'],
                ['state_id' => 24, 'city' => 'Dumont'],
                ['state_id' => 24, 'city' => 'Wheaton'],
                ['state_id' => 24, 'city' => 'Tintah'],
                ['state_id' => 24, 'city' => 'Lake City'],
                ['state_id' => 24, 'city' => 'Elgin'],
                ['state_id' => 24, 'city' => 'Kellogg'],
                ['state_id' => 24, 'city' => 'Mazeppa'],
                ['state_id' => 24, 'city' => 'Millville'],
                ['state_id' => 24, 'city' => 'Plainview'],
                ['state_id' => 24, 'city' => 'Reads Landing'],
                ['state_id' => 24, 'city' => 'Wabasha'],
                ['state_id' => 24, 'city' => 'Zumbro Falls'],
                ['state_id' => 24, 'city' => 'Aldrich'],
                ['state_id' => 24, 'city' => 'Menahga'],
                ['state_id' => 24, 'city' => 'Sebeka'],
                ['state_id' => 24, 'city' => 'Verndale'],
                ['state_id' => 24, 'city' => 'Wadena'],
                ['state_id' => 24, 'city' => 'Janesville'],
                ['state_id' => 24, 'city' => 'New Richland'],
                ['state_id' => 24, 'city' => 'Waldorf'],
                ['state_id' => 24, 'city' => 'Waseca'],
                ['state_id' => 24, 'city' => 'Afton'],
                ['state_id' => 24, 'city' => 'Bayport'],
                ['state_id' => 24, 'city' => 'Cottage Grove'],
                ['state_id' => 24, 'city' => 'Forest Lake'],
                ['state_id' => 24, 'city' => 'Hugo'],
                ['state_id' => 24, 'city' => 'Lake Elmo'],
                ['state_id' => 24, 'city' => 'Lakeland'],
                ['state_id' => 24, 'city' => 'Marine On Saint Croix'],
                ['state_id' => 24, 'city' => 'Newport'],
                ['state_id' => 24, 'city' => 'Saint Paul Park'],
                ['state_id' => 24, 'city' => 'Scandia'],
                ['state_id' => 24, 'city' => 'Stillwater'],
                ['state_id' => 24, 'city' => 'Willernie'],
                ['state_id' => 24, 'city' => 'Darfur'],
                ['state_id' => 24, 'city' => 'La Salle'],
                ['state_id' => 24, 'city' => 'Lewisville'],
                ['state_id' => 24, 'city' => 'Madelia'],
                ['state_id' => 24, 'city' => 'Saint James'],
                ['state_id' => 24, 'city' => 'Butterfield'],
                ['state_id' => 24, 'city' => 'Odin'],
                ['state_id' => 24, 'city' => 'Breckenridge'],
                ['state_id' => 24, 'city' => 'Campbell'],
                ['state_id' => 24, 'city' => 'Foxhome'],
                ['state_id' => 24, 'city' => 'Kent'],
                ['state_id' => 24, 'city' => 'Nashua'],
                ['state_id' => 24, 'city' => 'Rothsay'],
                ['state_id' => 24, 'city' => 'Wolverton'],
                ['state_id' => 24, 'city' => 'Altura'],
                ['state_id' => 24, 'city' => 'Dakota'],
                ['state_id' => 24, 'city' => 'Homer'],
                ['state_id' => 24, 'city' => 'Lewiston'],
                ['state_id' => 24, 'city' => 'Minnesota City'],
                ['state_id' => 24, 'city' => 'Rollingstone'],
                ['state_id' => 24, 'city' => 'Saint Charles'],
                ['state_id' => 24, 'city' => 'Utica'],
                ['state_id' => 24, 'city' => 'Winona'],
                ['state_id' => 24, 'city' => 'Stockton'],
                ['state_id' => 24, 'city' => 'Albertville'],
                ['state_id' => 24, 'city' => 'Annandale'],
                ['state_id' => 24, 'city' => 'Buffalo'],
                ['state_id' => 24, 'city' => 'Clearwater'],
                ['state_id' => 24, 'city' => 'Cokato'],
                ['state_id' => 24, 'city' => 'Delano'],
                ['state_id' => 24, 'city' => 'Hanover'],
                ['state_id' => 24, 'city' => 'Maple Lake'],
                ['state_id' => 24, 'city' => 'Monticello'],
                ['state_id' => 24, 'city' => 'Montrose'],
                ['state_id' => 24, 'city' => 'Saint Michael'],
                ['state_id' => 24, 'city' => 'Silver Creek'],
                ['state_id' => 24, 'city' => 'South Haven'],
                ['state_id' => 24, 'city' => 'Waverly'],
                ['state_id' => 24, 'city' => 'Canby'],
                ['state_id' => 24, 'city' => 'Clarkfield'],
                ['state_id' => 24, 'city' => 'Echo'],
                ['state_id' => 24, 'city' => 'Granite Falls'],
                ['state_id' => 24, 'city' => 'Hanley Falls'],
                ['state_id' => 24, 'city' => 'Porter'],
                ['state_id' => 24, 'city' => 'Wood Lake']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
