<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State26TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of MO - Missouri.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 26, 'city' => 'Kirksville'],
                ['state_id' => 26, 'city' => 'Brashear'],
                ['state_id' => 26, 'city' => 'Gibbs'],
                ['state_id' => 26, 'city' => 'Greentop'],
                ['state_id' => 26, 'city' => 'Novinger'],
                ['state_id' => 26, 'city' => 'Amazonia'],
                ['state_id' => 26, 'city' => 'Bolckow'],
                ['state_id' => 26, 'city' => 'Cosby'],
                ['state_id' => 26, 'city' => 'Fillmore'],
                ['state_id' => 26, 'city' => 'Helena'],
                ['state_id' => 26, 'city' => 'Rea'],
                ['state_id' => 26, 'city' => 'Rosendale'],
                ['state_id' => 26, 'city' => 'Savannah'],
                ['state_id' => 26, 'city' => 'Saint Joseph'],
                ['state_id' => 26, 'city' => 'Fairfax'],
                ['state_id' => 26, 'city' => 'Rock Port'],
                ['state_id' => 26, 'city' => 'Tarkio'],
                ['state_id' => 26, 'city' => 'Watson'],
                ['state_id' => 26, 'city' => 'Westboro'],
                ['state_id' => 26, 'city' => 'Farber'],
                ['state_id' => 26, 'city' => 'Laddonia'],
                ['state_id' => 26, 'city' => 'Vandalia'],
                ['state_id' => 26, 'city' => 'Benton City'],
                ['state_id' => 26, 'city' => 'Martinsburg'],
                ['state_id' => 26, 'city' => 'Mexico'],
                ['state_id' => 26, 'city' => 'Rush Hill'],
                ['state_id' => 26, 'city' => 'Thompson'],
                ['state_id' => 26, 'city' => 'Wheaton'],
                ['state_id' => 26, 'city' => 'Butterfield'],
                ['state_id' => 26, 'city' => 'Cassville'],
                ['state_id' => 26, 'city' => 'Eagle Rock'],
                ['state_id' => 26, 'city' => 'Exeter'],
                ['state_id' => 26, 'city' => 'Golden'],
                ['state_id' => 26, 'city' => 'Monett'],
                ['state_id' => 26, 'city' => 'Purdy'],
                ['state_id' => 26, 'city' => 'Seligman'],
                ['state_id' => 26, 'city' => 'Shell Knob'],
                ['state_id' => 26, 'city' => 'Washburn'],
                ['state_id' => 26, 'city' => 'Golden City'],
                ['state_id' => 26, 'city' => 'Lamar'],
                ['state_id' => 26, 'city' => 'Liberal'],
                ['state_id' => 26, 'city' => 'Milford'],
                ['state_id' => 26, 'city' => 'Mindenmines'],
                ['state_id' => 26, 'city' => 'Adrian'],
                ['state_id' => 26, 'city' => 'Amoret'],
                ['state_id' => 26, 'city' => 'Amsterdam'],
                ['state_id' => 26, 'city' => 'Butler'],
                ['state_id' => 26, 'city' => 'Drexel'],
                ['state_id' => 26, 'city' => 'Foster'],
                ['state_id' => 26, 'city' => 'Hume'],
                ['state_id' => 26, 'city' => 'Rich Hill'],
                ['state_id' => 26, 'city' => 'Rockville'],
                ['state_id' => 26, 'city' => 'Cole Camp'],
                ['state_id' => 26, 'city' => 'Edwards'],
                ['state_id' => 26, 'city' => 'Ionia'],
                ['state_id' => 26, 'city' => 'Lincoln'],
                ['state_id' => 26, 'city' => 'Warsaw'],
                ['state_id' => 26, 'city' => 'Patton'],
                ['state_id' => 26, 'city' => 'Gipsy'],
                ['state_id' => 26, 'city' => 'Glenallen'],
                ['state_id' => 26, 'city' => 'Leopold'],
                ['state_id' => 26, 'city' => 'Marble Hill'],
                ['state_id' => 26, 'city' => 'Sedgewickville'],
                ['state_id' => 26, 'city' => 'Sturdivant'],
                ['state_id' => 26, 'city' => 'Zalma'],
                ['state_id' => 26, 'city' => 'Ashland'],
                ['state_id' => 26, 'city' => 'Hartsburg'],
                ['state_id' => 26, 'city' => 'Columbia'],
                ['state_id' => 26, 'city' => 'Centralia'],
                ['state_id' => 26, 'city' => 'Hallsville'],
                ['state_id' => 26, 'city' => 'Harrisburg'],
                ['state_id' => 26, 'city' => 'Rocheport'],
                ['state_id' => 26, 'city' => 'Sturgeon'],
                ['state_id' => 26, 'city' => 'Mid Missouri'],
                ['state_id' => 26, 'city' => 'Agency'],
                ['state_id' => 26, 'city' => 'De Kalb'],
                ['state_id' => 26, 'city' => 'Easton'],
                ['state_id' => 26, 'city' => 'Faucett'],
                ['state_id' => 26, 'city' => 'Rushville'],
                ['state_id' => 26, 'city' => 'Poplar Bluff'],
                ['state_id' => 26, 'city' => 'Broseley'],
                ['state_id' => 26, 'city' => 'Fagus'],
                ['state_id' => 26, 'city' => 'Fisk'],
                ['state_id' => 26, 'city' => 'Harviell'],
                ['state_id' => 26, 'city' => 'Neelyville'],
                ['state_id' => 26, 'city' => 'Qulin'],
                ['state_id' => 26, 'city' => 'Rombauer'],
                ['state_id' => 26, 'city' => 'Braymer'],
                ['state_id' => 26, 'city' => 'Breckenridge'],
                ['state_id' => 26, 'city' => 'Cowgill'],
                ['state_id' => 26, 'city' => 'Hamilton'],
                ['state_id' => 26, 'city' => 'Kidder'],
                ['state_id' => 26, 'city' => 'Kingston'],
                ['state_id' => 26, 'city' => 'Polo'],
                ['state_id' => 26, 'city' => 'Williamsburg'],
                ['state_id' => 26, 'city' => 'Holts Summit'],
                ['state_id' => 26, 'city' => 'Mokane'],
                ['state_id' => 26, 'city' => 'New Bloomfield'],
                ['state_id' => 26, 'city' => 'Portland'],
                ['state_id' => 26, 'city' => 'Steedman'],
                ['state_id' => 26, 'city' => 'Tebbetts'],
                ['state_id' => 26, 'city' => 'Auxvasse'],
                ['state_id' => 26, 'city' => 'Fulton'],
                ['state_id' => 26, 'city' => 'Kingdom City'],
                ['state_id' => 26, 'city' => 'Camdenton'],
                ['state_id' => 26, 'city' => 'Lake Ozark'],
                ['state_id' => 26, 'city' => 'Linn Creek'],
                ['state_id' => 26, 'city' => 'Osage Beach'],
                ['state_id' => 26, 'city' => 'Sunrise Beach'],
                ['state_id' => 26, 'city' => 'Climax Springs'],
                ['state_id' => 26, 'city' => 'Stoutland'],
                ['state_id' => 26, 'city' => 'Montreal'],
                ['state_id' => 26, 'city' => 'Macks Creek'],
                ['state_id' => 26, 'city' => 'Roach'],
                ['state_id' => 26, 'city' => 'Cape Girardeau'],
                ['state_id' => 26, 'city' => 'Burfordville'],
                ['state_id' => 26, 'city' => 'Daisy'],
                ['state_id' => 26, 'city' => 'Delta'],
                ['state_id' => 26, 'city' => 'Dutchtown'],
                ['state_id' => 26, 'city' => 'Friedheim'],
                ['state_id' => 26, 'city' => 'Gordonville'],
                ['state_id' => 26, 'city' => 'Jackson'],
                ['state_id' => 26, 'city' => 'Millersville'],
                ['state_id' => 26, 'city' => 'Oak Ridge'],
                ['state_id' => 26, 'city' => 'Old Appleton'],
                ['state_id' => 26, 'city' => 'Pocahontas'],
                ['state_id' => 26, 'city' => 'Whitewater'],
                ['state_id' => 26, 'city' => 'Bogard'],
                ['state_id' => 26, 'city' => 'Bosworth'],
                ['state_id' => 26, 'city' => 'Carrollton'],
                ['state_id' => 26, 'city' => 'De Witt'],
                ['state_id' => 26, 'city' => 'Hale'],
                ['state_id' => 26, 'city' => 'Norborne'],
                ['state_id' => 26, 'city' => 'Stet'],
                ['state_id' => 26, 'city' => 'Tina'],
                ['state_id' => 26, 'city' => 'Ellsinore'],
                ['state_id' => 26, 'city' => 'Fremont'],
                ['state_id' => 26, 'city' => 'Grandin'],
                ['state_id' => 26, 'city' => 'Van Buren'],
                ['state_id' => 26, 'city' => 'Belton'],
                ['state_id' => 26, 'city' => 'Peculiar'],
                ['state_id' => 26, 'city' => 'Pleasant Hill'],
                ['state_id' => 26, 'city' => 'Raymore'],
                ['state_id' => 26, 'city' => 'Strasburg'],
                ['state_id' => 26, 'city' => 'Harrisonville'],
                ['state_id' => 26, 'city' => 'Archie'],
                ['state_id' => 26, 'city' => 'Cleveland'],
                ['state_id' => 26, 'city' => 'Creighton'],
                ['state_id' => 26, 'city' => 'East Lynne'],
                ['state_id' => 26, 'city' => 'Freeman'],
                ['state_id' => 26, 'city' => 'Garden City'],
                ['state_id' => 26, 'city' => 'El Dorado Springs'],
                ['state_id' => 26, 'city' => 'Jerico Springs'],
                ['state_id' => 26, 'city' => 'Caplinger Mills'],
                ['state_id' => 26, 'city' => 'Stockton'],
                ['state_id' => 26, 'city' => 'Mendon'],
                ['state_id' => 26, 'city' => 'Rothville'],
                ['state_id' => 26, 'city' => 'Sumner'],
                ['state_id' => 26, 'city' => 'Brunswick'],
                ['state_id' => 26, 'city' => 'Dalton'],
                ['state_id' => 26, 'city' => 'Keytesville'],
                ['state_id' => 26, 'city' => 'Salisbury'],
                ['state_id' => 26, 'city' => 'Triplett'],
                ['state_id' => 26, 'city' => 'Billings'],
                ['state_id' => 26, 'city' => 'Bruner'],
                ['state_id' => 26, 'city' => 'Chadwick'],
                ['state_id' => 26, 'city' => 'Chestnutridge'],
                ['state_id' => 26, 'city' => 'Clever'],
                ['state_id' => 26, 'city' => 'Garrison'],
                ['state_id' => 26, 'city' => 'Highlandville'],
                ['state_id' => 26, 'city' => 'Nixa'],
                ['state_id' => 26, 'city' => 'Oldfield'],
                ['state_id' => 26, 'city' => 'Ozark'],
                ['state_id' => 26, 'city' => 'Sparta'],
                ['state_id' => 26, 'city' => 'Spokane'],
                ['state_id' => 26, 'city' => 'Alexandria'],
                ['state_id' => 26, 'city' => 'Kahoka'],
                ['state_id' => 26, 'city' => 'Luray'],
                ['state_id' => 26, 'city' => 'Revere'],
                ['state_id' => 26, 'city' => 'Saint Patrick'],
                ['state_id' => 26, 'city' => 'Wayland'],
                ['state_id' => 26, 'city' => 'Wyaconda'],
                ['state_id' => 26, 'city' => 'Excelsior Springs'],
                ['state_id' => 26, 'city' => 'Holt'],
                ['state_id' => 26, 'city' => 'Kearney'],
                ['state_id' => 26, 'city' => 'Liberty'],
                ['state_id' => 26, 'city' => 'Missouri City'],
                ['state_id' => 26, 'city' => 'Mosby'],
                ['state_id' => 26, 'city' => 'Smithville'],
                ['state_id' => 26, 'city' => 'Kansas City'],
                ['state_id' => 26, 'city' => 'Cameron'],
                ['state_id' => 26, 'city' => 'Gower'],
                ['state_id' => 26, 'city' => 'Lathrop'],
                ['state_id' => 26, 'city' => 'Plattsburg'],
                ['state_id' => 26, 'city' => 'Trimble'],
                ['state_id' => 26, 'city' => 'Turney'],
                ['state_id' => 26, 'city' => 'Centertown'],
                ['state_id' => 26, 'city' => 'Eugene'],
                ['state_id' => 26, 'city' => 'Henley'],
                ['state_id' => 26, 'city' => 'Lohman'],
                ['state_id' => 26, 'city' => 'Russellville'],
                ['state_id' => 26, 'city' => 'Saint Thomas'],
                ['state_id' => 26, 'city' => 'Jefferson City'],
                ['state_id' => 26, 'city' => 'Prairie Home'],
                ['state_id' => 26, 'city' => 'Boonville'],
                ['state_id' => 26, 'city' => 'Bunceton'],
                ['state_id' => 26, 'city' => 'Pilot Grove'],
                ['state_id' => 26, 'city' => 'Wooldridge'],
                ['state_id' => 26, 'city' => 'Blackwater'],
                ['state_id' => 26, 'city' => 'Otterville'],
                ['state_id' => 26, 'city' => 'Bourbon'],
                ['state_id' => 26, 'city' => 'Cherryville'],
                ['state_id' => 26, 'city' => 'Cook Sta'],
                ['state_id' => 26, 'city' => 'Cuba'],
                ['state_id' => 26, 'city' => 'Davisville'],
                ['state_id' => 26, 'city' => 'Leasburg'],
                ['state_id' => 26, 'city' => 'Steelville'],
                ['state_id' => 26, 'city' => 'Wesco'],
                ['state_id' => 26, 'city' => 'Arcola'],
                ['state_id' => 26, 'city' => 'Dadeville'],
                ['state_id' => 26, 'city' => 'Everton'],
                ['state_id' => 26, 'city' => 'Greenfield'],
                ['state_id' => 26, 'city' => 'Lockwood'],
                ['state_id' => 26, 'city' => 'South Greenfield'],
                ['state_id' => 26, 'city' => 'Long Lane'],
                ['state_id' => 26, 'city' => 'Buffalo'],
                ['state_id' => 26, 'city' => 'Louisburg'],
                ['state_id' => 26, 'city' => 'Tunas'],
                ['state_id' => 26, 'city' => 'Urbana'],
                ['state_id' => 26, 'city' => 'Windyville'],
                ['state_id' => 26, 'city' => 'Altamont'],
                ['state_id' => 26, 'city' => 'Coffey'],
                ['state_id' => 26, 'city' => 'Gallatin'],
                ['state_id' => 26, 'city' => 'Gilman City'],
                ['state_id' => 26, 'city' => 'Jameson'],
                ['state_id' => 26, 'city' => 'Jamesport'],
                ['state_id' => 26, 'city' => 'Lock Springs'],
                ['state_id' => 26, 'city' => 'Pattonsburg'],
                ['state_id' => 26, 'city' => 'Winston'],
                ['state_id' => 26, 'city' => 'Amity'],
                ['state_id' => 26, 'city' => 'Clarksdale'],
                ['state_id' => 26, 'city' => 'Maysville'],
                ['state_id' => 26, 'city' => 'Osborn'],
                ['state_id' => 26, 'city' => 'Stewartsville'],
                ['state_id' => 26, 'city' => 'Union Star'],
                ['state_id' => 26, 'city' => 'Weatherby'],
                ['state_id' => 26, 'city' => 'Boss'],
                ['state_id' => 26, 'city' => 'Jadwin'],
                ['state_id' => 26, 'city' => 'Lake Spring'],
                ['state_id' => 26, 'city' => 'Lenox'],
                ['state_id' => 26, 'city' => 'Salem'],
                ['state_id' => 26, 'city' => 'Ava'],
                ['state_id' => 26, 'city' => 'Drury'],
                ['state_id' => 26, 'city' => 'Squires'],
                ['state_id' => 26, 'city' => 'Vanzant'],
                ['state_id' => 26, 'city' => 'Arbyrd'],
                ['state_id' => 26, 'city' => 'Cardwell'],
                ['state_id' => 26, 'city' => 'Clarkton'],
                ['state_id' => 26, 'city' => 'Gibson'],
                ['state_id' => 26, 'city' => 'Holcomb'],
                ['state_id' => 26, 'city' => 'Hornersville'],
                ['state_id' => 26, 'city' => 'Kennett'],
                ['state_id' => 26, 'city' => 'Malden'],
                ['state_id' => 26, 'city' => 'Rives'],
                ['state_id' => 26, 'city' => 'Senath'],
                ['state_id' => 26, 'city' => 'Whiteoak'],
                ['state_id' => 26, 'city' => 'Campbell'],
                ['state_id' => 26, 'city' => 'Beaufort'],
                ['state_id' => 26, 'city' => 'Berger'],
                ['state_id' => 26, 'city' => 'Catawissa'],
                ['state_id' => 26, 'city' => 'Gerald'],
                ['state_id' => 26, 'city' => 'Gray Summit'],
                ['state_id' => 26, 'city' => 'Labadie'],
                ['state_id' => 26, 'city' => 'Leslie'],
                ['state_id' => 26, 'city' => 'Lonedell'],
                ['state_id' => 26, 'city' => 'Luebbering'],
                ['state_id' => 26, 'city' => 'New Haven'],
                ['state_id' => 26, 'city' => 'Pacific'],
                ['state_id' => 26, 'city' => 'Robertsville'],
                ['state_id' => 26, 'city' => 'Saint Albans'],
                ['state_id' => 26, 'city' => 'Saint Clair'],
                ['state_id' => 26, 'city' => 'Stanton'],
                ['state_id' => 26, 'city' => 'Sullivan'],
                ['state_id' => 26, 'city' => 'Union'],
                ['state_id' => 26, 'city' => 'Villa Ridge'],
                ['state_id' => 26, 'city' => 'Washington'],
                ['state_id' => 26, 'city' => 'Rosebud'],
                ['state_id' => 26, 'city' => 'Bland'],
                ['state_id' => 26, 'city' => 'Gasconade'],
                ['state_id' => 26, 'city' => 'Hermann'],
                ['state_id' => 26, 'city' => 'Morrison'],
                ['state_id' => 26, 'city' => 'Mount Sterling'],
                ['state_id' => 26, 'city' => 'Owensville'],
                ['state_id' => 26, 'city' => 'Albany'],
                ['state_id' => 26, 'city' => 'Darlington'],
                ['state_id' => 26, 'city' => 'Gentry'],
                ['state_id' => 26, 'city' => 'King City'],
                ['state_id' => 26, 'city' => 'Stanberry'],
                ['state_id' => 26, 'city' => 'Mc Fall'],
                ['state_id' => 26, 'city' => 'Ash Grove'],
                ['state_id' => 26, 'city' => 'Bois D Arc'],
                ['state_id' => 26, 'city' => 'Brookline'],
                ['state_id' => 26, 'city' => 'Fair Grove'],
                ['state_id' => 26, 'city' => 'Republic'],
                ['state_id' => 26, 'city' => 'Strafford'],
                ['state_id' => 26, 'city' => 'Turners'],
                ['state_id' => 26, 'city' => 'Walnut Grove'],
                ['state_id' => 26, 'city' => 'Willard'],
                ['state_id' => 26, 'city' => 'Springfield'],
                ['state_id' => 26, 'city' => 'Galt'],
                ['state_id' => 26, 'city' => 'Laredo'],
                ['state_id' => 26, 'city' => 'Spickard'],
                ['state_id' => 26, 'city' => 'Trenton'],
                ['state_id' => 26, 'city' => 'Bethany'],
                ['state_id' => 26, 'city' => 'Blythedale'],
                ['state_id' => 26, 'city' => 'Eagleville'],
                ['state_id' => 26, 'city' => 'Hatfield'],
                ['state_id' => 26, 'city' => 'Martinsville'],
                ['state_id' => 26, 'city' => 'New Hampton'],
                ['state_id' => 26, 'city' => 'Ridgeway'],
                ['state_id' => 26, 'city' => 'Cainsville'],
                ['state_id' => 26, 'city' => 'Blairstown'],
                ['state_id' => 26, 'city' => 'Clinton'],
                ['state_id' => 26, 'city' => 'Deepwater'],
                ['state_id' => 26, 'city' => 'Montrose'],
                ['state_id' => 26, 'city' => 'Urich'],
                ['state_id' => 26, 'city' => 'Calhoun'],
                ['state_id' => 26, 'city' => 'Windsor'],
                ['state_id' => 26, 'city' => 'Cross Timbers'],
                ['state_id' => 26, 'city' => 'Hermitage'],
                ['state_id' => 26, 'city' => 'Pittsburg'],
                ['state_id' => 26, 'city' => 'Preston'],
                ['state_id' => 26, 'city' => 'Quincy'],
                ['state_id' => 26, 'city' => 'Weaubleau'],
                ['state_id' => 26, 'city' => 'Wheatland'],
                ['state_id' => 26, 'city' => 'Craig'],
                ['state_id' => 26, 'city' => 'Forest City'],
                ['state_id' => 26, 'city' => 'Maitland'],
                ['state_id' => 26, 'city' => 'Mound City'],
                ['state_id' => 26, 'city' => 'Oregon'],
                ['state_id' => 26, 'city' => 'Armstrong'],
                ['state_id' => 26, 'city' => 'Fayette'],
                ['state_id' => 26, 'city' => 'Franklin'],
                ['state_id' => 26, 'city' => 'Glasgow'],
                ['state_id' => 26, 'city' => 'New Franklin'],
                ['state_id' => 26, 'city' => 'Mountain View'],
                ['state_id' => 26, 'city' => 'Caulfield'],
                ['state_id' => 26, 'city' => 'Brandsville'],
                ['state_id' => 26, 'city' => 'West Plains'],
                ['state_id' => 26, 'city' => 'Moody'],
                ['state_id' => 26, 'city' => 'Peace Valley'],
                ['state_id' => 26, 'city' => 'Pomona'],
                ['state_id' => 26, 'city' => 'Pottersville'],
                ['state_id' => 26, 'city' => 'Willow Springs'],
                ['state_id' => 26, 'city' => 'Annapolis'],
                ['state_id' => 26, 'city' => 'Arcadia'],
                ['state_id' => 26, 'city' => 'Belleview'],
                ['state_id' => 26, 'city' => 'Des Arc'],
                ['state_id' => 26, 'city' => 'Ironton'],
                ['state_id' => 26, 'city' => 'Middle Brook'],
                ['state_id' => 26, 'city' => 'Pilot Knob'],
                ['state_id' => 26, 'city' => 'Vulcan'],
                ['state_id' => 26, 'city' => 'Bixby'],
                ['state_id' => 26, 'city' => 'Viburnum'],
                ['state_id' => 26, 'city' => 'Lees Summit'],
                ['state_id' => 26, 'city' => 'Blue Springs'],
                ['state_id' => 26, 'city' => 'Buckner'],
                ['state_id' => 26, 'city' => 'Grain Valley'],
                ['state_id' => 26, 'city' => 'Grandview'],
                ['state_id' => 26, 'city' => 'Greenwood'],
                ['state_id' => 26, 'city' => 'Independence'],
                ['state_id' => 26, 'city' => 'Levasy'],
                ['state_id' => 26, 'city' => 'Lone Jack'],
                ['state_id' => 26, 'city' => 'Oak Grove'],
                ['state_id' => 26, 'city' => 'Sibley'],
                ['state_id' => 26, 'city' => 'Jasper'],
                ['state_id' => 26, 'city' => 'Joplin'],
                ['state_id' => 26, 'city' => 'Alba'],
                ['state_id' => 26, 'city' => 'Asbury'],
                ['state_id' => 26, 'city' => 'Avilla'],
                ['state_id' => 26, 'city' => 'Carl Junction'],
                ['state_id' => 26, 'city' => 'Carterville'],
                ['state_id' => 26, 'city' => 'Carthage'],
                ['state_id' => 26, 'city' => 'Duenweg'],
                ['state_id' => 26, 'city' => 'La Russell'],
                ['state_id' => 26, 'city' => 'Neck City'],
                ['state_id' => 26, 'city' => 'Oronogo'],
                ['state_id' => 26, 'city' => 'Purcell'],
                ['state_id' => 26, 'city' => 'Reeds'],
                ['state_id' => 26, 'city' => 'Sarcoxie'],
                ['state_id' => 26, 'city' => 'Webb City'],
                ['state_id' => 26, 'city' => 'Arnold'],
                ['state_id' => 26, 'city' => 'Barnhart'],
                ['state_id' => 26, 'city' => 'Cedar Hill'],
                ['state_id' => 26, 'city' => 'Crystal City'],
                ['state_id' => 26, 'city' => 'De Soto'],
                ['state_id' => 26, 'city' => 'Dittmer'],
                ['state_id' => 26, 'city' => 'Festus'],
                ['state_id' => 26, 'city' => 'Fletcher'],
                ['state_id' => 26, 'city' => 'Grubville'],
                ['state_id' => 26, 'city' => 'Hematite'],
                ['state_id' => 26, 'city' => 'Herculaneum'],
                ['state_id' => 26, 'city' => 'High Ridge'],
                ['state_id' => 26, 'city' => 'Hillsboro'],
                ['state_id' => 26, 'city' => 'House Springs'],
                ['state_id' => 26, 'city' => 'Imperial'],
                ['state_id' => 26, 'city' => 'Kimmswick'],
                ['state_id' => 26, 'city' => 'Liguori'],
                ['state_id' => 26, 'city' => 'Mapaville'],
                ['state_id' => 26, 'city' => 'Morse Mill'],
                ['state_id' => 26, 'city' => 'Pevely'],
                ['state_id' => 26, 'city' => 'Centerview'],
                ['state_id' => 26, 'city' => 'Holden'],
                ['state_id' => 26, 'city' => 'Kingsville'],
                ['state_id' => 26, 'city' => 'Warrensburg'],
                ['state_id' => 26, 'city' => 'Chilhowee'],
                ['state_id' => 26, 'city' => 'Leeton'],
                ['state_id' => 26, 'city' => 'Whiteman Air Force Base'],
                ['state_id' => 26, 'city' => 'Knob Noster'],
                ['state_id' => 26, 'city' => 'Knox City'],
                ['state_id' => 26, 'city' => 'Newark'],
                ['state_id' => 26, 'city' => 'Novelty'],
                ['state_id' => 26, 'city' => 'Plevna'],
                ['state_id' => 26, 'city' => 'Baring'],
                ['state_id' => 26, 'city' => 'Edina'],
                ['state_id' => 26, 'city' => 'Hurdland'],
                ['state_id' => 26, 'city' => 'Eldridge'],
                ['state_id' => 26, 'city' => 'Falcon'],
                ['state_id' => 26, 'city' => 'Lebanon'],
                ['state_id' => 26, 'city' => 'Lynchburg'],
                ['state_id' => 26, 'city' => 'Conway'],
                ['state_id' => 26, 'city' => 'Phillipsburg'],
                ['state_id' => 26, 'city' => 'Alma'],
                ['state_id' => 26, 'city' => 'Bates City'],
                ['state_id' => 26, 'city' => 'Concordia'],
                ['state_id' => 26, 'city' => 'Corder'],
                ['state_id' => 26, 'city' => 'Dover'],
                ['state_id' => 26, 'city' => 'Higginsville'],
                ['state_id' => 26, 'city' => 'Lexington'],
                ['state_id' => 26, 'city' => 'Mayview'],
                ['state_id' => 26, 'city' => 'Napoleon'],
                ['state_id' => 26, 'city' => 'Odessa'],
                ['state_id' => 26, 'city' => 'Waverly'],
                ['state_id' => 26, 'city' => 'Wellington'],
                ['state_id' => 26, 'city' => 'Emma'],
                ['state_id' => 26, 'city' => 'Aurora'],
                ['state_id' => 26, 'city' => 'Freistatt'],
                ['state_id' => 26, 'city' => 'Halltown'],
                ['state_id' => 26, 'city' => 'Marionville'],
                ['state_id' => 26, 'city' => 'Miller'],
                ['state_id' => 26, 'city' => 'Mount Vernon'],
                ['state_id' => 26, 'city' => 'Pierce City'],
                ['state_id' => 26, 'city' => 'Stotts City'],
                ['state_id' => 26, 'city' => 'Verona'],
                ['state_id' => 26, 'city' => 'Canton'],
                ['state_id' => 26, 'city' => 'Durham'],
                ['state_id' => 26, 'city' => 'Ewing'],
                ['state_id' => 26, 'city' => 'La Belle'],
                ['state_id' => 26, 'city' => 'La Grange'],
                ['state_id' => 26, 'city' => 'Lewistown'],
                ['state_id' => 26, 'city' => 'Monticello'],
                ['state_id' => 26, 'city' => 'Williamstown'],
                ['state_id' => 26, 'city' => 'Elsberry'],
                ['state_id' => 26, 'city' => 'Foley'],
                ['state_id' => 26, 'city' => 'Hawk Point'],
                ['state_id' => 26, 'city' => 'Moscow Mills'],
                ['state_id' => 26, 'city' => 'Old Monroe'],
                ['state_id' => 26, 'city' => 'Olney'],
                ['state_id' => 26, 'city' => 'Silex'],
                ['state_id' => 26, 'city' => 'Troy'],
                ['state_id' => 26, 'city' => 'Truxton'],
                ['state_id' => 26, 'city' => 'Whiteside'],
                ['state_id' => 26, 'city' => 'Winfield'],
                ['state_id' => 26, 'city' => 'New Boston'],
                ['state_id' => 26, 'city' => 'Brookfield'],
                ['state_id' => 26, 'city' => 'Browning'],
                ['state_id' => 26, 'city' => 'Bucklin'],
                ['state_id' => 26, 'city' => 'Laclede'],
                ['state_id' => 26, 'city' => 'Linneus'],
                ['state_id' => 26, 'city' => 'Marceline'],
                ['state_id' => 26, 'city' => 'Meadville'],
                ['state_id' => 26, 'city' => 'Purdin'],
                ['state_id' => 26, 'city' => 'Chillicothe'],
                ['state_id' => 26, 'city' => 'Chula'],
                ['state_id' => 26, 'city' => 'Dawn'],
                ['state_id' => 26, 'city' => 'Ludlow'],
                ['state_id' => 26, 'city' => 'Mooresville'],
                ['state_id' => 26, 'city' => 'Utica'],
                ['state_id' => 26, 'city' => 'Wheeling'],
                ['state_id' => 26, 'city' => 'Anderson'],
                ['state_id' => 26, 'city' => 'Goodman'],
                ['state_id' => 26, 'city' => 'Lanagan'],
                ['state_id' => 26, 'city' => 'Noel'],
                ['state_id' => 26, 'city' => 'Pineville'],
                ['state_id' => 26, 'city' => 'Rocky Comfort'],
                ['state_id' => 26, 'city' => 'South West City'],
                ['state_id' => 26, 'city' => 'Tiff City'],
                ['state_id' => 26, 'city' => 'Powell'],
                ['state_id' => 26, 'city' => 'Anabel'],
                ['state_id' => 26, 'city' => 'Atlanta'],
                ['state_id' => 26, 'city' => 'Bevier'],
                ['state_id' => 26, 'city' => 'Callao'],
                ['state_id' => 26, 'city' => 'Elmer'],
                ['state_id' => 26, 'city' => 'Ethel'],
                ['state_id' => 26, 'city' => 'La Plata'],
                ['state_id' => 26, 'city' => 'Macon'],
                ['state_id' => 26, 'city' => 'New Cambria'],
                ['state_id' => 26, 'city' => 'Excello'],
                ['state_id' => 26, 'city' => 'Fredericktown'],
                ['state_id' => 26, 'city' => 'Marquand'],
                ['state_id' => 26, 'city' => 'Belle'],
                ['state_id' => 26, 'city' => 'Brinktown'],
                ['state_id' => 26, 'city' => 'Vichy'],
                ['state_id' => 26, 'city' => 'Vienna'],
                ['state_id' => 26, 'city' => 'Hannibal'],
                ['state_id' => 26, 'city' => 'Maywood'],
                ['state_id' => 26, 'city' => 'Palmyra'],
                ['state_id' => 26, 'city' => 'Philadelphia'],
                ['state_id' => 26, 'city' => 'Taylor'],
                ['state_id' => 26, 'city' => 'Mercer'],
                ['state_id' => 26, 'city' => 'Princeton'],
                ['state_id' => 26, 'city' => 'Brumley'],
                ['state_id' => 26, 'city' => 'Eldon'],
                ['state_id' => 26, 'city' => 'Kaiser'],
                ['state_id' => 26, 'city' => 'Olean'],
                ['state_id' => 26, 'city' => 'Saint Elizabeth'],
                ['state_id' => 26, 'city' => 'Tuscumbia'],
                ['state_id' => 26, 'city' => 'Ulman'],
                ['state_id' => 26, 'city' => 'Iberia'],
                ['state_id' => 26, 'city' => 'Anniston'],
                ['state_id' => 26, 'city' => 'Bertrand'],
                ['state_id' => 26, 'city' => 'Charleston'],
                ['state_id' => 26, 'city' => 'East Prairie'],
                ['state_id' => 26, 'city' => 'Wolf Island'],
                ['state_id' => 26, 'city' => 'Wyatt'],
                ['state_id' => 26, 'city' => 'California'],
                ['state_id' => 26, 'city' => 'Clarksburg'],
                ['state_id' => 26, 'city' => 'Fortuna'],
                ['state_id' => 26, 'city' => 'High Point'],
                ['state_id' => 26, 'city' => 'Jamestown'],
                ['state_id' => 26, 'city' => 'Latham'],
                ['state_id' => 26, 'city' => 'Mc Girk'],
                ['state_id' => 26, 'city' => 'Tipton'],
                ['state_id' => 26, 'city' => 'Monroe City'],
                ['state_id' => 26, 'city' => 'Holliday'],
                ['state_id' => 26, 'city' => 'Madison'],
                ['state_id' => 26, 'city' => 'Paris'],
                ['state_id' => 26, 'city' => 'Santa Fe'],
                ['state_id' => 26, 'city' => 'Stoutsville'],
                ['state_id' => 26, 'city' => 'Bellflower'],
                ['state_id' => 26, 'city' => 'High Hill'],
                ['state_id' => 26, 'city' => 'Jonesburg'],
                ['state_id' => 26, 'city' => 'Middletown'],
                ['state_id' => 26, 'city' => 'Montgomery City'],
                ['state_id' => 26, 'city' => 'New Florence'],
                ['state_id' => 26, 'city' => 'Wellsville'],
                ['state_id' => 26, 'city' => 'Rhineland'],
                ['state_id' => 26, 'city' => 'Barnett'],
                ['state_id' => 26, 'city' => 'Gravois Mills'],
                ['state_id' => 26, 'city' => 'Laurie'],
                ['state_id' => 26, 'city' => 'Rocky Mount'],
                ['state_id' => 26, 'city' => 'Stover'],
                ['state_id' => 26, 'city' => 'Versailles'],
                ['state_id' => 26, 'city' => 'Florence'],
                ['state_id' => 26, 'city' => 'Syracuse'],
                ['state_id' => 26, 'city' => 'Canalou'],
                ['state_id' => 26, 'city' => 'Catron'],
                ['state_id' => 26, 'city' => 'Gideon'],
                ['state_id' => 26, 'city' => 'Kewanee'],
                ['state_id' => 26, 'city' => 'Lilbourn'],
                ['state_id' => 26, 'city' => 'Marston'],
                ['state_id' => 26, 'city' => 'Matthews'],
                ['state_id' => 26, 'city' => 'Morehouse'],
                ['state_id' => 26, 'city' => 'New Madrid'],
                ['state_id' => 26, 'city' => 'Parma'],
                ['state_id' => 26, 'city' => 'Portageville'],
                ['state_id' => 26, 'city' => 'Risco'],
                ['state_id' => 26, 'city' => 'Tallapoosa'],
                ['state_id' => 26, 'city' => 'Diamond'],
                ['state_id' => 26, 'city' => 'Fairview'],
                ['state_id' => 26, 'city' => 'Granby'],
                ['state_id' => 26, 'city' => 'Neosho'],
                ['state_id' => 26, 'city' => 'Newtonia'],
                ['state_id' => 26, 'city' => 'Racine'],
                ['state_id' => 26, 'city' => 'Saginaw'],
                ['state_id' => 26, 'city' => 'Seneca'],
                ['state_id' => 26, 'city' => 'Stark City'],
                ['state_id' => 26, 'city' => 'Stella'],
                ['state_id' => 26, 'city' => 'Wentworth'],
                ['state_id' => 26, 'city' => 'Barnard'],
                ['state_id' => 26, 'city' => 'Burlington Junction'],
                ['state_id' => 26, 'city' => 'Clearmont'],
                ['state_id' => 26, 'city' => 'Clyde'],
                ['state_id' => 26, 'city' => 'Conception'],
                ['state_id' => 26, 'city' => 'Conception Junction'],
                ['state_id' => 26, 'city' => 'Elmo'],
                ['state_id' => 26, 'city' => 'Graham'],
                ['state_id' => 26, 'city' => 'Guilford'],
                ['state_id' => 26, 'city' => 'Hopkins'],
                ['state_id' => 26, 'city' => 'Maryville'],
                ['state_id' => 26, 'city' => 'Parnell'],
                ['state_id' => 26, 'city' => 'Pickering'],
                ['state_id' => 26, 'city' => 'Ravenwood'],
                ['state_id' => 26, 'city' => 'Skidmore'],
                ['state_id' => 26, 'city' => 'Alton'],
                ['state_id' => 26, 'city' => 'Couch'],
                ['state_id' => 26, 'city' => 'Koshkonong'],
                ['state_id' => 26, 'city' => 'Myrtle'],
                ['state_id' => 26, 'city' => 'Thayer'],
                ['state_id' => 26, 'city' => 'Argyle'],
                ['state_id' => 26, 'city' => 'Bonnots Mill'],
                ['state_id' => 26, 'city' => 'Chamois'],
                ['state_id' => 26, 'city' => 'Freeburg'],
                ['state_id' => 26, 'city' => 'Koeltztown'],
                ['state_id' => 26, 'city' => 'Linn'],
                ['state_id' => 26, 'city' => 'Loose Creek'],
                ['state_id' => 26, 'city' => 'Meta'],
                ['state_id' => 26, 'city' => 'Westphalia'],
                ['state_id' => 26, 'city' => 'Bakersfield'],
                ['state_id' => 26, 'city' => 'Brixey'],
                ['state_id' => 26, 'city' => 'Dora'],
                ['state_id' => 26, 'city' => 'Gainesville'],
                ['state_id' => 26, 'city' => 'Hardenville'],
                ['state_id' => 26, 'city' => 'Isabella'],
                ['state_id' => 26, 'city' => 'Noble'],
                ['state_id' => 26, 'city' => 'Pontiac'],
                ['state_id' => 26, 'city' => 'Rockbridge'],
                ['state_id' => 26, 'city' => 'Tecumseh'],
                ['state_id' => 26, 'city' => 'Theodosia'],
                ['state_id' => 26, 'city' => 'Thornfield'],
                ['state_id' => 26, 'city' => 'Udall'],
                ['state_id' => 26, 'city' => 'Wasola'],
                ['state_id' => 26, 'city' => 'Zanoni'],
                ['state_id' => 26, 'city' => 'Braggadocio'],
                ['state_id' => 26, 'city' => 'Bragg City'],
                ['state_id' => 26, 'city' => 'Caruthersville'],
                ['state_id' => 26, 'city' => 'Cooter'],
                ['state_id' => 26, 'city' => 'Deering'],
                ['state_id' => 26, 'city' => 'Gobler'],
                ['state_id' => 26, 'city' => 'Hayti'],
                ['state_id' => 26, 'city' => 'Holland'],
                ['state_id' => 26, 'city' => 'Steele'],
                ['state_id' => 26, 'city' => 'Wardell'],
                ['state_id' => 26, 'city' => 'Altenburg'],
                ['state_id' => 26, 'city' => 'Brazeau'],
                ['state_id' => 26, 'city' => 'Farrar'],
                ['state_id' => 26, 'city' => 'Frohna'],
                ['state_id' => 26, 'city' => 'Perryville'],
                ['state_id' => 26, 'city' => 'Mc Bride'],
                ['state_id' => 26, 'city' => 'Uniontown'],
                ['state_id' => 26, 'city' => 'Sedalia'],
                ['state_id' => 26, 'city' => 'Green Ridge'],
                ['state_id' => 26, 'city' => 'Houstonia'],
                ['state_id' => 26, 'city' => 'Hughesville'],
                ['state_id' => 26, 'city' => 'La Monte'],
                ['state_id' => 26, 'city' => 'Mora'],
                ['state_id' => 26, 'city' => 'Smithton'],
                ['state_id' => 26, 'city' => 'Rolla'],
                ['state_id' => 26, 'city' => 'Beulah'],
                ['state_id' => 26, 'city' => 'Duke'],
                ['state_id' => 26, 'city' => 'Edgar Springs'],
                ['state_id' => 26, 'city' => 'Jerome'],
                ['state_id' => 26, 'city' => 'Newburg'],
                ['state_id' => 26, 'city' => 'Saint James'],
                ['state_id' => 26, 'city' => 'Annada'],
                ['state_id' => 26, 'city' => 'Bowling Green'],
                ['state_id' => 26, 'city' => 'Clarksville'],
                ['state_id' => 26, 'city' => 'Curryville'],
                ['state_id' => 26, 'city' => 'Eolia'],
                ['state_id' => 26, 'city' => 'Louisiana'],
                ['state_id' => 26, 'city' => 'Ashburn'],
                ['state_id' => 26, 'city' => 'Frankford'],
                ['state_id' => 26, 'city' => 'Camden Point'],
                ['state_id' => 26, 'city' => 'Farley'],
                ['state_id' => 26, 'city' => 'Platte City'],
                ['state_id' => 26, 'city' => 'Waldron'],
                ['state_id' => 26, 'city' => 'Weston'],
                ['state_id' => 26, 'city' => 'Riverside'],
                ['state_id' => 26, 'city' => 'Dearborn'],
                ['state_id' => 26, 'city' => 'Edgerton'],
                ['state_id' => 26, 'city' => 'Aldrich'],
                ['state_id' => 26, 'city' => 'Bolivar'],
                ['state_id' => 26, 'city' => 'Brighton'],
                ['state_id' => 26, 'city' => 'Dunnegan'],
                ['state_id' => 26, 'city' => 'Eudora'],
                ['state_id' => 26, 'city' => 'Fair Play'],
                ['state_id' => 26, 'city' => 'Flemington'],
                ['state_id' => 26, 'city' => 'Half Way'],
                ['state_id' => 26, 'city' => 'Humansville'],
                ['state_id' => 26, 'city' => 'Morrisville'],
                ['state_id' => 26, 'city' => 'Pleasant Hope'],
                ['state_id' => 26, 'city' => 'Polk'],
                ['state_id' => 26, 'city' => 'Crocker'],
                ['state_id' => 26, 'city' => 'Devils Elbow'],
                ['state_id' => 26, 'city' => 'Dixon'],
                ['state_id' => 26, 'city' => 'Fort Leonard Wood'],
                ['state_id' => 26, 'city' => 'Laquey'],
                ['state_id' => 26, 'city' => 'Richland'],
                ['state_id' => 26, 'city' => 'Waynesville'],
                ['state_id' => 26, 'city' => 'Saint Robert'],
                ['state_id' => 26, 'city' => 'Livonia'],
                ['state_id' => 26, 'city' => 'Unionville'],
                ['state_id' => 26, 'city' => 'Worthington'],
                ['state_id' => 26, 'city' => 'Lucerne'],
                ['state_id' => 26, 'city' => 'Powersville'],
                ['state_id' => 26, 'city' => 'Center'],
                ['state_id' => 26, 'city' => 'New London'],
                ['state_id' => 26, 'city' => 'Perry'],
                ['state_id' => 26, 'city' => 'Saverton'],
                ['state_id' => 26, 'city' => 'Cairo'],
                ['state_id' => 26, 'city' => 'Clark'],
                ['state_id' => 26, 'city' => 'Clifton Hill'],
                ['state_id' => 26, 'city' => 'Higbee'],
                ['state_id' => 26, 'city' => 'Huntsville'],
                ['state_id' => 26, 'city' => 'Jacksonville'],
                ['state_id' => 26, 'city' => 'Moberly'],
                ['state_id' => 26, 'city' => 'Renick'],
                ['state_id' => 26, 'city' => 'Camden'],
                ['state_id' => 26, 'city' => 'Hardin'],
                ['state_id' => 26, 'city' => 'Henrietta'],
                ['state_id' => 26, 'city' => 'Lawson'],
                ['state_id' => 26, 'city' => 'Orrick'],
                ['state_id' => 26, 'city' => 'Rayville'],
                ['state_id' => 26, 'city' => 'Richmond'],
                ['state_id' => 26, 'city' => 'Black'],
                ['state_id' => 26, 'city' => 'Bunker'],
                ['state_id' => 26, 'city' => 'Centerville'],
                ['state_id' => 26, 'city' => 'Ellington'],
                ['state_id' => 26, 'city' => 'Lesterville'],
                ['state_id' => 26, 'city' => 'Redford'],
                ['state_id' => 26, 'city' => 'Reynolds'],
                ['state_id' => 26, 'city' => 'Briar'],
                ['state_id' => 26, 'city' => 'Doniphan'],
                ['state_id' => 26, 'city' => 'Fairdealing'],
                ['state_id' => 26, 'city' => 'Gatewood'],
                ['state_id' => 26, 'city' => 'Naylor'],
                ['state_id' => 26, 'city' => 'Oxly'],
                ['state_id' => 26, 'city' => 'Saint Charles'],
                ['state_id' => 26, 'city' => 'Augusta'],
                ['state_id' => 26, 'city' => 'Cottleville'],
                ['state_id' => 26, 'city' => 'Defiance'],
                ['state_id' => 26, 'city' => 'Flinthill'],
                ['state_id' => 26, 'city' => 'Foristell'],
                ['state_id' => 26, 'city' => 'New Melle'],
                ['state_id' => 26, 'city' => 'O Fallon'],
                ['state_id' => 26, 'city' => 'Lake Saint Louis'],
                ['state_id' => 26, 'city' => 'Portage Des Sioux'],
                ['state_id' => 26, 'city' => 'Saint Peters'],
                ['state_id' => 26, 'city' => 'Wentzville'],
                ['state_id' => 26, 'city' => 'West Alton'],
                ['state_id' => 26, 'city' => 'Appleton City'],
                ['state_id' => 26, 'city' => 'Collins'],
                ['state_id' => 26, 'city' => 'Lowry City'],
                ['state_id' => 26, 'city' => 'Osceola'],
                ['state_id' => 26, 'city' => 'Roscoe'],
                ['state_id' => 26, 'city' => 'Bloomsdale'],
                ['state_id' => 26, 'city' => 'Sainte Genevieve'],
                ['state_id' => 26, 'city' => 'Saint Mary'],
                ['state_id' => 26, 'city' => 'French Village'],
                ['state_id' => 26, 'city' => 'Valles Mines'],
                ['state_id' => 26, 'city' => 'Park Hills'],
                ['state_id' => 26, 'city' => 'Bismarck'],
                ['state_id' => 26, 'city' => 'Blackwell'],
                ['state_id' => 26, 'city' => 'Bonne Terre'],
                ['state_id' => 26, 'city' => 'Doe Run'],
                ['state_id' => 26, 'city' => 'Farmington'],
                ['state_id' => 26, 'city' => 'Knob Lick'],
                ['state_id' => 26, 'city' => 'Leadwood'],
                ['state_id' => 26, 'city' => 'Chesterfield'],
                ['state_id' => 26, 'city' => 'Ballwin'],
                ['state_id' => 26, 'city' => 'Eureka'],
                ['state_id' => 26, 'city' => 'Fenton'],
                ['state_id' => 26, 'city' => 'Florissant'],
                ['state_id' => 26, 'city' => 'Glencoe'],
                ['state_id' => 26, 'city' => 'Grover'],
                ['state_id' => 26, 'city' => 'Hazelwood'],
                ['state_id' => 26, 'city' => 'Maryland Heights'],
                ['state_id' => 26, 'city' => 'Bridgeton'],
                ['state_id' => 26, 'city' => 'Earth City'],
                ['state_id' => 26, 'city' => 'Saint Ann'],
                ['state_id' => 26, 'city' => 'Valley Park'],
                ['state_id' => 26, 'city' => 'Saint Louis'],
                ['state_id' => 26, 'city' => 'Arrow Rock'],
                ['state_id' => 26, 'city' => 'Blackburn'],
                ['state_id' => 26, 'city' => 'Gilliam'],
                ['state_id' => 26, 'city' => 'Malta Bend'],
                ['state_id' => 26, 'city' => 'Marshall'],
                ['state_id' => 26, 'city' => 'Miami'],
                ['state_id' => 26, 'city' => 'Nelson'],
                ['state_id' => 26, 'city' => 'Slater'],
                ['state_id' => 26, 'city' => 'Sweet Springs'],
                ['state_id' => 26, 'city' => 'Coatsville'],
                ['state_id' => 26, 'city' => 'Downing'],
                ['state_id' => 26, 'city' => 'Glenwood'],
                ['state_id' => 26, 'city' => 'Lancaster'],
                ['state_id' => 26, 'city' => 'Queen City'],
                ['state_id' => 26, 'city' => 'Arbela'],
                ['state_id' => 26, 'city' => 'Granger'],
                ['state_id' => 26, 'city' => 'Gorin'],
                ['state_id' => 26, 'city' => 'Memphis'],
                ['state_id' => 26, 'city' => 'Rutledge'],
                ['state_id' => 26, 'city' => 'Benton'],
                ['state_id' => 26, 'city' => 'Chaffee'],
                ['state_id' => 26, 'city' => 'Commerce'],
                ['state_id' => 26, 'city' => 'Kelso'],
                ['state_id' => 26, 'city' => 'Morley'],
                ['state_id' => 26, 'city' => 'Oran'],
                ['state_id' => 26, 'city' => 'Perkins'],
                ['state_id' => 26, 'city' => 'Scott City'],
                ['state_id' => 26, 'city' => 'Vanduser'],
                ['state_id' => 26, 'city' => 'Sikeston'],
                ['state_id' => 26, 'city' => 'Blodgett'],
                ['state_id' => 26, 'city' => 'Birch Tree'],
                ['state_id' => 26, 'city' => 'Eminence'],
                ['state_id' => 26, 'city' => 'Montier'],
                ['state_id' => 26, 'city' => 'Winona'],
                ['state_id' => 26, 'city' => 'Bethel'],
                ['state_id' => 26, 'city' => 'Clarence'],
                ['state_id' => 26, 'city' => 'Emden'],
                ['state_id' => 26, 'city' => 'Hunnewell'],
                ['state_id' => 26, 'city' => 'Lentner'],
                ['state_id' => 26, 'city' => 'Leonard'],
                ['state_id' => 26, 'city' => 'Shelbina'],
                ['state_id' => 26, 'city' => 'Shelbyville'],
                ['state_id' => 26, 'city' => 'Advance'],
                ['state_id' => 26, 'city' => 'Bell City'],
                ['state_id' => 26, 'city' => 'Brownwood'],
                ['state_id' => 26, 'city' => 'Bernie'],
                ['state_id' => 26, 'city' => 'Bloomfield'],
                ['state_id' => 26, 'city' => 'Dexter'],
                ['state_id' => 26, 'city' => 'Essex'],
                ['state_id' => 26, 'city' => 'Grayridge'],
                ['state_id' => 26, 'city' => 'Dudley'],
                ['state_id' => 26, 'city' => 'Puxico'],
                ['state_id' => 26, 'city' => 'Blue Eye'],
                ['state_id' => 26, 'city' => 'Cape Fair'],
                ['state_id' => 26, 'city' => 'Crane'],
                ['state_id' => 26, 'city' => 'Galena'],
                ['state_id' => 26, 'city' => 'Hurley'],
                ['state_id' => 26, 'city' => 'Lampe'],
                ['state_id' => 26, 'city' => 'Kimberling City'],
                ['state_id' => 26, 'city' => 'Ponce De Leon'],
                ['state_id' => 26, 'city' => 'Reeds Spring'],
                ['state_id' => 26, 'city' => 'Green Castle'],
                ['state_id' => 26, 'city' => 'Green City'],
                ['state_id' => 26, 'city' => 'Milan'],
                ['state_id' => 26, 'city' => 'Pollock'],
                ['state_id' => 26, 'city' => 'Winigan'],
                ['state_id' => 26, 'city' => 'Harris'],
                ['state_id' => 26, 'city' => 'Humphreys'],
                ['state_id' => 26, 'city' => 'Newtown'],
                ['state_id' => 26, 'city' => 'Bradleyville'],
                ['state_id' => 26, 'city' => 'Branson'],
                ['state_id' => 26, 'city' => 'Cedarcreek'],
                ['state_id' => 26, 'city' => 'Forsyth'],
                ['state_id' => 26, 'city' => 'Hollister'],
                ['state_id' => 26, 'city' => 'Kirbyville'],
                ['state_id' => 26, 'city' => 'Kissee Mills'],
                ['state_id' => 26, 'city' => 'Point Lookout'],
                ['state_id' => 26, 'city' => 'Powersite'],
                ['state_id' => 26, 'city' => 'Protem'],
                ['state_id' => 26, 'city' => 'Ridgedale'],
                ['state_id' => 26, 'city' => 'Rockaway Beach'],
                ['state_id' => 26, 'city' => 'Rueter'],
                ['state_id' => 26, 'city' => 'Taneyville'],
                ['state_id' => 26, 'city' => 'Walnut Shade'],
                ['state_id' => 26, 'city' => 'Bucyrus'],
                ['state_id' => 26, 'city' => 'Elk Creek'],
                ['state_id' => 26, 'city' => 'Eunice'],
                ['state_id' => 26, 'city' => 'Hartshorn'],
                ['state_id' => 26, 'city' => 'Houston'],
                ['state_id' => 26, 'city' => 'Huggins'],
                ['state_id' => 26, 'city' => 'Licking'],
                ['state_id' => 26, 'city' => 'Plato'],
                ['state_id' => 26, 'city' => 'Raymondville'],
                ['state_id' => 26, 'city' => 'Roby'],
                ['state_id' => 26, 'city' => 'Solo'],
                ['state_id' => 26, 'city' => 'Success'],
                ['state_id' => 26, 'city' => 'Summersville'],
                ['state_id' => 26, 'city' => 'Yukon'],
                ['state_id' => 26, 'city' => 'Cabool'],
                ['state_id' => 26, 'city' => 'Bronaugh'],
                ['state_id' => 26, 'city' => 'Deerfield'],
                ['state_id' => 26, 'city' => 'Harwood'],
                ['state_id' => 26, 'city' => 'Metz'],
                ['state_id' => 26, 'city' => 'Milo'],
                ['state_id' => 26, 'city' => 'Moundville'],
                ['state_id' => 26, 'city' => 'Nevada'],
                ['state_id' => 26, 'city' => 'Richards'],
                ['state_id' => 26, 'city' => 'Schell City'],
                ['state_id' => 26, 'city' => 'Sheldon'],
                ['state_id' => 26, 'city' => 'Walker'],
                ['state_id' => 26, 'city' => 'Dutzow'],
                ['state_id' => 26, 'city' => 'Marthasville'],
                ['state_id' => 26, 'city' => 'Treloar'],
                ['state_id' => 26, 'city' => 'Truesdale'],
                ['state_id' => 26, 'city' => 'Warrenton'],
                ['state_id' => 26, 'city' => 'Wright City'],
                ['state_id' => 26, 'city' => 'Richwoods'],
                ['state_id' => 26, 'city' => 'Belgrade'],
                ['state_id' => 26, 'city' => 'Cadet'],
                ['state_id' => 26, 'city' => 'Caledonia'],
                ['state_id' => 26, 'city' => 'Irondale'],
                ['state_id' => 26, 'city' => 'Mineral Point'],
                ['state_id' => 26, 'city' => 'Potosi'],
                ['state_id' => 26, 'city' => 'Tiff'],
                ['state_id' => 26, 'city' => 'Cascade'],
                ['state_id' => 26, 'city' => 'Mc Gee'],
                ['state_id' => 26, 'city' => 'Clubb'],
                ['state_id' => 26, 'city' => 'Greenville'],
                ['state_id' => 26, 'city' => 'Lodi'],
                ['state_id' => 26, 'city' => 'Lowndes'],
                ['state_id' => 26, 'city' => 'Mill Spring'],
                ['state_id' => 26, 'city' => 'Patterson'],
                ['state_id' => 26, 'city' => 'Piedmont'],
                ['state_id' => 26, 'city' => 'Silva'],
                ['state_id' => 26, 'city' => 'Wappapello'],
                ['state_id' => 26, 'city' => 'Williamsville'],
                ['state_id' => 26, 'city' => 'Diggins'],
                ['state_id' => 26, 'city' => 'Elkland'],
                ['state_id' => 26, 'city' => 'Fordland'],
                ['state_id' => 26, 'city' => 'Marshfield'],
                ['state_id' => 26, 'city' => 'Niangua'],
                ['state_id' => 26, 'city' => 'Rogersville'],
                ['state_id' => 26, 'city' => 'Seymour'],
                ['state_id' => 26, 'city' => 'Allendale'],
                ['state_id' => 26, 'city' => 'Denver'],
                ['state_id' => 26, 'city' => 'Grant City'],
                ['state_id' => 26, 'city' => 'Sheridan'],
                ['state_id' => 26, 'city' => 'Worth'],
                ['state_id' => 26, 'city' => 'Graff'],
                ['state_id' => 26, 'city' => 'Grovespring'],
                ['state_id' => 26, 'city' => 'Hartville'],
                ['state_id' => 26, 'city' => 'Macomb'],
                ['state_id' => 26, 'city' => 'Mansfield'],
                ['state_id' => 26, 'city' => 'Mountain Grove'],
                ['state_id' => 26, 'city' => 'Norwood']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
