<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State46TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of VT - Vermont.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 46, 'city' => 'Bristol'],
                ['state_id' => 46, 'city' => 'Ferrisburgh'],
                ['state_id' => 46, 'city' => 'Monkton'],
                ['state_id' => 46, 'city' => 'New Haven'],
                ['state_id' => 46, 'city' => 'North Ferrisburgh'],
                ['state_id' => 46, 'city' => 'Starksboro'],
                ['state_id' => 46, 'city' => 'Vergennes'],
                ['state_id' => 46, 'city' => 'Roxbury'],
                ['state_id' => 46, 'city' => 'Bridport'],
                ['state_id' => 46, 'city' => 'East Middlebury'],
                ['state_id' => 46, 'city' => 'Granville'],
                ['state_id' => 46, 'city' => 'Hancock'],
                ['state_id' => 46, 'city' => 'Middlebury'],
                ['state_id' => 46, 'city' => 'Orwell'],
                ['state_id' => 46, 'city' => 'Ripton'],
                ['state_id' => 46, 'city' => 'Salisbury'],
                ['state_id' => 46, 'city' => 'Shoreham'],
                ['state_id' => 46, 'city' => 'Whiting'],
                ['state_id' => 46, 'city' => 'Peru'],
                ['state_id' => 46, 'city' => 'Bennington'],
                ['state_id' => 46, 'city' => 'Arlington'],
                ['state_id' => 46, 'city' => 'Dorset'],
                ['state_id' => 46, 'city' => 'East Arlington'],
                ['state_id' => 46, 'city' => 'East Dorset'],
                ['state_id' => 46, 'city' => 'Manchester'],
                ['state_id' => 46, 'city' => 'Manchester Center'],
                ['state_id' => 46, 'city' => 'North Bennington'],
                ['state_id' => 46, 'city' => 'North Pownal'],
                ['state_id' => 46, 'city' => 'Pownal'],
                ['state_id' => 46, 'city' => 'Shaftsbury'],
                ['state_id' => 46, 'city' => 'Bondville'],
                ['state_id' => 46, 'city' => 'Readsboro'],
                ['state_id' => 46, 'city' => 'Stamford'],
                ['state_id' => 46, 'city' => 'Rupert'],
                ['state_id' => 46, 'city' => 'West Rupert'],
                ['state_id' => 46, 'city' => 'East Ryegate'],
                ['state_id' => 46, 'city' => 'Groton'],
                ['state_id' => 46, 'city' => 'Mc Indoe Falls'],
                ['state_id' => 46, 'city' => 'South Ryegate'],
                ['state_id' => 46, 'city' => 'Saint Johnsbury'],
                ['state_id' => 46, 'city' => 'Barnet'],
                ['state_id' => 46, 'city' => 'Danville'],
                ['state_id' => 46, 'city' => 'East Burke'],
                ['state_id' => 46, 'city' => 'East Hardwick'],
                ['state_id' => 46, 'city' => 'East Saint Johnsbury'],
                ['state_id' => 46, 'city' => 'Hardwick'],
                ['state_id' => 46, 'city' => 'Lower Waterford'],
                ['state_id' => 46, 'city' => 'Lyndon'],
                ['state_id' => 46, 'city' => 'Lyndon Center'],
                ['state_id' => 46, 'city' => 'Lyndonville'],
                ['state_id' => 46, 'city' => 'Passumpsic'],
                ['state_id' => 46, 'city' => 'Peacham'],
                ['state_id' => 46, 'city' => 'Saint Johnsbury Center'],
                ['state_id' => 46, 'city' => 'Sheffield'],
                ['state_id' => 46, 'city' => 'Sutton'],
                ['state_id' => 46, 'city' => 'West Burke'],
                ['state_id' => 46, 'city' => 'West Danville'],
                ['state_id' => 46, 'city' => 'Burlington'],
                ['state_id' => 46, 'city' => 'South Burlington'],
                ['state_id' => 46, 'city' => 'Winooski'],
                ['state_id' => 46, 'city' => 'Colchester'],
                ['state_id' => 46, 'city' => 'Charlotte'],
                ['state_id' => 46, 'city' => 'Essex'],
                ['state_id' => 46, 'city' => 'Essex Junction'],
                ['state_id' => 46, 'city' => 'Hinesburg'],
                ['state_id' => 46, 'city' => 'Huntington'],
                ['state_id' => 46, 'city' => 'Jericho'],
                ['state_id' => 46, 'city' => 'Jonesville'],
                ['state_id' => 46, 'city' => 'Milton'],
                ['state_id' => 46, 'city' => 'Richmond'],
                ['state_id' => 46, 'city' => 'Shelburne'],
                ['state_id' => 46, 'city' => 'Underhill'],
                ['state_id' => 46, 'city' => 'Underhill Center'],
                ['state_id' => 46, 'city' => 'Westford'],
                ['state_id' => 46, 'city' => 'Williston'],
                ['state_id' => 46, 'city' => 'Concord'],
                ['state_id' => 46, 'city' => 'East Haven'],
                ['state_id' => 46, 'city' => 'Granby'],
                ['state_id' => 46, 'city' => 'Island Pond'],
                ['state_id' => 46, 'city' => 'North Concord'],
                ['state_id' => 46, 'city' => 'Averill'],
                ['state_id' => 46, 'city' => 'Beecher Falls'],
                ['state_id' => 46, 'city' => 'Canaan'],
                ['state_id' => 46, 'city' => 'Gilman'],
                ['state_id' => 46, 'city' => 'Guildhall'],
                ['state_id' => 46, 'city' => 'Lunenburg'],
                ['state_id' => 46, 'city' => 'Norton'],
                ['state_id' => 46, 'city' => 'Bakersfield'],
                ['state_id' => 46, 'city' => 'East Berkshire'],
                ['state_id' => 46, 'city' => 'East Fairfield'],
                ['state_id' => 46, 'city' => 'Enosburg Falls'],
                ['state_id' => 46, 'city' => 'Fairfax'],
                ['state_id' => 46, 'city' => 'Fairfield'],
                ['state_id' => 46, 'city' => 'Franklin'],
                ['state_id' => 46, 'city' => 'Highgate Center'],
                ['state_id' => 46, 'city' => 'Highgate Springs'],
                ['state_id' => 46, 'city' => 'Montgomery'],
                ['state_id' => 46, 'city' => 'Montgomery Center'],
                ['state_id' => 46, 'city' => 'Richford'],
                ['state_id' => 46, 'city' => 'Saint Albans'],
                ['state_id' => 46, 'city' => 'Saint Albans Bay'],
                ['state_id' => 46, 'city' => 'Sheldon'],
                ['state_id' => 46, 'city' => 'Sheldon Springs'],
                ['state_id' => 46, 'city' => 'Swanton'],
                ['state_id' => 46, 'city' => 'Alburgh'],
                ['state_id' => 46, 'city' => 'Grand Isle'],
                ['state_id' => 46, 'city' => 'Isle La Motte'],
                ['state_id' => 46, 'city' => 'North Hero'],
                ['state_id' => 46, 'city' => 'South Hero'],
                ['state_id' => 46, 'city' => 'Belvidere Center'],
                ['state_id' => 46, 'city' => 'Cambridge'],
                ['state_id' => 46, 'city' => 'Jeffersonville'],
                ['state_id' => 46, 'city' => 'Waterville'],
                ['state_id' => 46, 'city' => 'Eden'],
                ['state_id' => 46, 'city' => 'Eden Mills'],
                ['state_id' => 46, 'city' => 'Hyde Park'],
                ['state_id' => 46, 'city' => 'Johnson'],
                ['state_id' => 46, 'city' => 'Lake Elmore'],
                ['state_id' => 46, 'city' => 'Morrisville'],
                ['state_id' => 46, 'city' => 'Moscow'],
                ['state_id' => 46, 'city' => 'North Hyde Park'],
                ['state_id' => 46, 'city' => 'Stowe'],
                ['state_id' => 46, 'city' => 'Wolcott'],
                ['state_id' => 46, 'city' => 'Bradford'],
                ['state_id' => 46, 'city' => 'Brookfield'],
                ['state_id' => 46, 'city' => 'Chelsea'],
                ['state_id' => 46, 'city' => 'Corinth'],
                ['state_id' => 46, 'city' => 'East Corinth'],
                ['state_id' => 46, 'city' => 'East Randolph'],
                ['state_id' => 46, 'city' => 'East Thetford'],
                ['state_id' => 46, 'city' => 'Fairlee'],
                ['state_id' => 46, 'city' => 'Newbury'],
                ['state_id' => 46, 'city' => 'North Thetford'],
                ['state_id' => 46, 'city' => 'Post Mills'],
                ['state_id' => 46, 'city' => 'Randolph'],
                ['state_id' => 46, 'city' => 'Randolph Center'],
                ['state_id' => 46, 'city' => 'South Strafford'],
                ['state_id' => 46, 'city' => 'Strafford'],
                ['state_id' => 46, 'city' => 'Thetford'],
                ['state_id' => 46, 'city' => 'Thetford Center'],
                ['state_id' => 46, 'city' => 'Topsham'],
                ['state_id' => 46, 'city' => 'Tunbridge'],
                ['state_id' => 46, 'city' => 'Vershire'],
                ['state_id' => 46, 'city' => 'Wells River'],
                ['state_id' => 46, 'city' => 'West Fairlee'],
                ['state_id' => 46, 'city' => 'West Newbury'],
                ['state_id' => 46, 'city' => 'West Topsham'],
                ['state_id' => 46, 'city' => 'Washington'],
                ['state_id' => 46, 'city' => 'Williamstown'],
                ['state_id' => 46, 'city' => 'Albany'],
                ['state_id' => 46, 'city' => 'Barton'],
                ['state_id' => 46, 'city' => 'Beebe Plain'],
                ['state_id' => 46, 'city' => 'Coventry'],
                ['state_id' => 46, 'city' => 'Craftsbury'],
                ['state_id' => 46, 'city' => 'Craftsbury Common'],
                ['state_id' => 46, 'city' => 'Derby'],
                ['state_id' => 46, 'city' => 'Derby Line'],
                ['state_id' => 46, 'city' => 'East Charleston'],
                ['state_id' => 46, 'city' => 'Glover'],
                ['state_id' => 46, 'city' => 'Greensboro'],
                ['state_id' => 46, 'city' => 'Greensboro Bend'],
                ['state_id' => 46, 'city' => 'Irasburg'],
                ['state_id' => 46, 'city' => 'Lowell'],
                ['state_id' => 46, 'city' => 'Morgan'],
                ['state_id' => 46, 'city' => 'Newport'],
                ['state_id' => 46, 'city' => 'Newport Center'],
                ['state_id' => 46, 'city' => 'North Troy'],
                ['state_id' => 46, 'city' => 'Orleans'],
                ['state_id' => 46, 'city' => 'Troy'],
                ['state_id' => 46, 'city' => 'West Charleston'],
                ['state_id' => 46, 'city' => 'Westfield'],
                ['state_id' => 46, 'city' => 'Rutland'],
                ['state_id' => 46, 'city' => 'Belmont'],
                ['state_id' => 46, 'city' => 'Benson'],
                ['state_id' => 46, 'city' => 'Bomoseen'],
                ['state_id' => 46, 'city' => 'Brandon'],
                ['state_id' => 46, 'city' => 'Castleton'],
                ['state_id' => 46, 'city' => 'Center Rutland'],
                ['state_id' => 46, 'city' => 'Chittenden'],
                ['state_id' => 46, 'city' => 'Cuttingsville'],
                ['state_id' => 46, 'city' => 'Danby'],
                ['state_id' => 46, 'city' => 'East Poultney'],
                ['state_id' => 46, 'city' => 'East Wallingford'],
                ['state_id' => 46, 'city' => 'Fair Haven'],
                ['state_id' => 46, 'city' => 'Florence'],
                ['state_id' => 46, 'city' => 'Forest Dale'],
                ['state_id' => 46, 'city' => 'Hydeville'],
                ['state_id' => 46, 'city' => 'Killington'],
                ['state_id' => 46, 'city' => 'Middletown Springs'],
                ['state_id' => 46, 'city' => 'Mount Holly'],
                ['state_id' => 46, 'city' => 'North Clarendon'],
                ['state_id' => 46, 'city' => 'Pawlet'],
                ['state_id' => 46, 'city' => 'Pittsfield'],
                ['state_id' => 46, 'city' => 'Pittsford'],
                ['state_id' => 46, 'city' => 'Poultney'],
                ['state_id' => 46, 'city' => 'Proctor'],
                ['state_id' => 46, 'city' => 'Wallingford'],
                ['state_id' => 46, 'city' => 'Wells'],
                ['state_id' => 46, 'city' => 'West Pawlet'],
                ['state_id' => 46, 'city' => 'West Rutland'],
                ['state_id' => 46, 'city' => 'Montpelier'],
                ['state_id' => 46, 'city' => 'Adamant'],
                ['state_id' => 46, 'city' => 'Barre'],
                ['state_id' => 46, 'city' => 'Cabot'],
                ['state_id' => 46, 'city' => 'Calais'],
                ['state_id' => 46, 'city' => 'East Barre'],
                ['state_id' => 46, 'city' => 'East Calais'],
                ['state_id' => 46, 'city' => 'East Montpelier'],
                ['state_id' => 46, 'city' => 'Graniteville'],
                ['state_id' => 46, 'city' => 'Marshfield'],
                ['state_id' => 46, 'city' => 'Moretown'],
                ['state_id' => 46, 'city' => 'Northfield'],
                ['state_id' => 46, 'city' => 'Northfield Falls'],
                ['state_id' => 46, 'city' => 'North Montpelier'],
                ['state_id' => 46, 'city' => 'Plainfield'],
                ['state_id' => 46, 'city' => 'South Barre'],
                ['state_id' => 46, 'city' => 'Waterbury'],
                ['state_id' => 46, 'city' => 'Waitsfield'],
                ['state_id' => 46, 'city' => 'Warren'],
                ['state_id' => 46, 'city' => 'Waterbury Center'],
                ['state_id' => 46, 'city' => 'Websterville'],
                ['state_id' => 46, 'city' => 'Woodbury'],
                ['state_id' => 46, 'city' => 'Worcester'],
                ['state_id' => 46, 'city' => 'Bellows Falls'],
                ['state_id' => 46, 'city' => 'Cambridgeport'],
                ['state_id' => 46, 'city' => 'Grafton'],
                ['state_id' => 46, 'city' => 'Londonderry'],
                ['state_id' => 46, 'city' => 'Saxtons River'],
                ['state_id' => 46, 'city' => 'South Londonderry'],
                ['state_id' => 46, 'city' => 'Westminster'],
                ['state_id' => 46, 'city' => 'Westminster Station'],
                ['state_id' => 46, 'city' => 'Brattleboro'],
                ['state_id' => 46, 'city' => 'East Dover'],
                ['state_id' => 46, 'city' => 'Jacksonville'],
                ['state_id' => 46, 'city' => 'Jamaica'],
                ['state_id' => 46, 'city' => 'Marlboro'],
                ['state_id' => 46, 'city' => 'Newfane'],
                ['state_id' => 46, 'city' => 'Putney'],
                ['state_id' => 46, 'city' => 'South Newfane'],
                ['state_id' => 46, 'city' => 'Townshend'],
                ['state_id' => 46, 'city' => 'Vernon'],
                ['state_id' => 46, 'city' => 'Wardsboro'],
                ['state_id' => 46, 'city' => 'West Dover'],
                ['state_id' => 46, 'city' => 'West Dummerston'],
                ['state_id' => 46, 'city' => 'West Halifax'],
                ['state_id' => 46, 'city' => 'West Townshend'],
                ['state_id' => 46, 'city' => 'West Wardsboro'],
                ['state_id' => 46, 'city' => 'Whitingham'],
                ['state_id' => 46, 'city' => 'Williamsville'],
                ['state_id' => 46, 'city' => 'Wilmington'],
                ['state_id' => 46, 'city' => 'White River Junction'],
                ['state_id' => 46, 'city' => 'Ascutney'],
                ['state_id' => 46, 'city' => 'Barnard'],
                ['state_id' => 46, 'city' => 'Bethel'],
                ['state_id' => 46, 'city' => 'Bridgewater'],
                ['state_id' => 46, 'city' => 'Bridgewater Corners'],
                ['state_id' => 46, 'city' => 'Brownsville'],
                ['state_id' => 46, 'city' => 'Hartford'],
                ['state_id' => 46, 'city' => 'Hartland'],
                ['state_id' => 46, 'city' => 'Hartland Four Corners'],
                ['state_id' => 46, 'city' => 'North Hartland'],
                ['state_id' => 46, 'city' => 'North Pomfret'],
                ['state_id' => 46, 'city' => 'Norwich'],
                ['state_id' => 46, 'city' => 'Plymouth'],
                ['state_id' => 46, 'city' => 'Quechee'],
                ['state_id' => 46, 'city' => 'Reading'],
                ['state_id' => 46, 'city' => 'Sharon'],
                ['state_id' => 46, 'city' => 'South Pomfret'],
                ['state_id' => 46, 'city' => 'South Royalton'],
                ['state_id' => 46, 'city' => 'South Woodstock'],
                ['state_id' => 46, 'city' => 'Taftsville'],
                ['state_id' => 46, 'city' => 'West Hartford'],
                ['state_id' => 46, 'city' => 'Wilder'],
                ['state_id' => 46, 'city' => 'Windsor'],
                ['state_id' => 46, 'city' => 'Woodstock'],
                ['state_id' => 46, 'city' => 'Cavendish'],
                ['state_id' => 46, 'city' => 'Chester'],
                ['state_id' => 46, 'city' => 'Ludlow'],
                ['state_id' => 46, 'city' => 'North Springfield'],
                ['state_id' => 46, 'city' => 'Perkinsville'],
                ['state_id' => 46, 'city' => 'Proctorsville'],
                ['state_id' => 46, 'city' => 'Springfield'],
                ['state_id' => 46, 'city' => 'Weston'],
                ['state_id' => 46, 'city' => 'Gaysville'],
                ['state_id' => 46, 'city' => 'Rochester'],
                ['state_id' => 46, 'city' => 'Stockbridge'],
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
       }
    }
}
