<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State10TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of FL - Florida.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 10, 'city' => 'Gainesville'],
                ['state_id' => 10, 'city' => 'Alachua'],
                ['state_id' => 10, 'city' => 'Archer'],
                ['state_id' => 10, 'city' => 'Earleton'],
                ['state_id' => 10, 'city' => 'Evinston'],
                ['state_id' => 10, 'city' => 'Hawthorne'],
                ['state_id' => 10, 'city' => 'High Springs'],
                ['state_id' => 10, 'city' => 'Island Grove'],
                ['state_id' => 10, 'city' => 'La Crosse'],
                ['state_id' => 10, 'city' => 'Lochloosa'],
                ['state_id' => 10, 'city' => 'Micanopy'],
                ['state_id' => 10, 'city' => 'Newberry'],
                ['state_id' => 10, 'city' => 'Waldo'],
                ['state_id' => 10, 'city' => 'Glen Saint Mary'],
                ['state_id' => 10, 'city' => 'Macclenny'],
                ['state_id' => 10, 'city' => 'Olustee'],
                ['state_id' => 10, 'city' => 'Sanderson'],
                ['state_id' => 10, 'city' => 'Panama City'],
                ['state_id' => 10, 'city' => 'Panama City Beach'],
                ['state_id' => 10, 'city' => 'Mexico Beach'],
                ['state_id' => 10, 'city' => 'Fountain'],
                ['state_id' => 10, 'city' => 'Lynn Haven'],
                ['state_id' => 10, 'city' => 'Youngstown'],
                ['state_id' => 10, 'city' => 'Graham'],
                ['state_id' => 10, 'city' => 'Hampton'],
                ['state_id' => 10, 'city' => 'Lawtey'],
                ['state_id' => 10, 'city' => 'Starke'],
                ['state_id' => 10, 'city' => 'Brooker'],
                ['state_id' => 10, 'city' => 'Mims'],
                ['state_id' => 10, 'city' => 'Scottsmoor'],
                ['state_id' => 10, 'city' => 'Titusville'],
                ['state_id' => 10, 'city' => 'Orlando'],
                ['state_id' => 10, 'city' => 'Melbourne'],
                ['state_id' => 10, 'city' => 'Indialantic'],
                ['state_id' => 10, 'city' => 'Palm Bay'],
                ['state_id' => 10, 'city' => 'Cape Canaveral'],
                ['state_id' => 10, 'city' => 'Cocoa'],
                ['state_id' => 10, 'city' => 'Patrick Afb'],
                ['state_id' => 10, 'city' => 'Cocoa Beach'],
                ['state_id' => 10, 'city' => 'Satellite Beach'],
                ['state_id' => 10, 'city' => 'Grant'],
                ['state_id' => 10, 'city' => 'Malabar'],
                ['state_id' => 10, 'city' => 'Melbourne Beach'],
                ['state_id' => 10, 'city' => 'Merritt Island'],
                ['state_id' => 10, 'city' => 'Rockledge'],
                ['state_id' => 10, 'city' => 'Sharpes'],
                ['state_id' => 10, 'city' => 'Sebastian'],
                ['state_id' => 10, 'city' => 'Dania'],
                ['state_id' => 10, 'city' => 'Hallandale'],
                ['state_id' => 10, 'city' => 'Hollywood'],
                ['state_id' => 10, 'city' => 'Pembroke Pines'],
                ['state_id' => 10, 'city' => 'Pompano Beach'],
                ['state_id' => 10, 'city' => 'Coral Springs'],
                ['state_id' => 10, 'city' => 'Margate'],
                ['state_id' => 10, 'city' => 'Coconut Creek'],
                ['state_id' => 10, 'city' => 'Fort Lauderdale'],
                ['state_id' => 10, 'city' => 'Plantation'],
                ['state_id' => 10, 'city' => 'Deerfield Beach'],
                ['state_id' => 10, 'city' => 'Lehigh Acres'],
                ['state_id' => 10, 'city' => 'Altha'],
                ['state_id' => 10, 'city' => 'Blountstown'],
                ['state_id' => 10, 'city' => 'Clarksville'],
                ['state_id' => 10, 'city' => 'Wewahitchka'],
                ['state_id' => 10, 'city' => 'El Jobean'],
                ['state_id' => 10, 'city' => 'Murdock'],
                ['state_id' => 10, 'city' => 'Placida'],
                ['state_id' => 10, 'city' => 'Rotonda West'],
                ['state_id' => 10, 'city' => 'Port Charlotte'],
                ['state_id' => 10, 'city' => 'Punta Gorda'],
                ['state_id' => 10, 'city' => 'Crystal River'],
                ['state_id' => 10, 'city' => 'Dunnellon'],
                ['state_id' => 10, 'city' => 'Floral City'],
                ['state_id' => 10, 'city' => 'Hernando'],
                ['state_id' => 10, 'city' => 'Holder'],
                ['state_id' => 10, 'city' => 'Homosassa'],
                ['state_id' => 10, 'city' => 'Homosassa Springs'],
                ['state_id' => 10, 'city' => 'Inverness'],
                ['state_id' => 10, 'city' => 'Lecanto'],
                ['state_id' => 10, 'city' => 'Beverly Hills'],
                ['state_id' => 10, 'city' => 'Fleming Island'],
                ['state_id' => 10, 'city' => 'Doctors Inlet'],
                ['state_id' => 10, 'city' => 'Green Cove Springs'],
                ['state_id' => 10, 'city' => 'Middleburg'],
                ['state_id' => 10, 'city' => 'Orange Park'],
                ['state_id' => 10, 'city' => 'Penney Farms'],
                ['state_id' => 10, 'city' => 'Lake Geneva'],
                ['state_id' => 10, 'city' => 'Keystone Heights'],
                ['state_id' => 10, 'city' => 'Naples'],
                ['state_id' => 10, 'city' => 'Copeland'],
                ['state_id' => 10, 'city' => 'Chokoloskee'],
                ['state_id' => 10, 'city' => 'Everglades City'],
                ['state_id' => 10, 'city' => 'Goodland'],
                ['state_id' => 10, 'city' => 'Ochopee'],
                ['state_id' => 10, 'city' => 'Immokalee'],
                ['state_id' => 10, 'city' => 'Marco Island'],
                ['state_id' => 10, 'city' => 'Lake City'],
                ['state_id' => 10, 'city' => 'Fort White'],
                ['state_id' => 10, 'city' => 'Lulu'],
                ['state_id' => 10, 'city' => 'Arcadia'],
                ['state_id' => 10, 'city' => 'Fort Ogden'],
                ['state_id' => 10, 'city' => 'Nocatee'],
                ['state_id' => 10, 'city' => 'Cross City'],
                ['state_id' => 10, 'city' => 'Horseshoe Beach'],
                ['state_id' => 10, 'city' => 'Old Town'],
                ['state_id' => 10, 'city' => 'Suwannee'],
                ['state_id' => 10, 'city' => 'Jacksonville'],
                ['state_id' => 10, 'city' => 'Atlantic Beach'],
                ['state_id' => 10, 'city' => 'Jacksonville Beach'],
                ['state_id' => 10, 'city' => 'Neptune Beach'],
                ['state_id' => 10, 'city' => 'Pensacola'],
                ['state_id' => 10, 'city' => 'Cantonment'],
                ['state_id' => 10, 'city' => 'Century'],
                ['state_id' => 10, 'city' => 'Gonzalez'],
                ['state_id' => 10, 'city' => 'Mc David'],
                ['state_id' => 10, 'city' => 'Molino'],
                ['state_id' => 10, 'city' => 'Bunnell'],
                ['state_id' => 10, 'city' => 'Palm Coast'],
                ['state_id' => 10, 'city' => 'Flagler Beach'],
                ['state_id' => 10, 'city' => 'Tallahassee'],
                ['state_id' => 10, 'city' => 'Apalachicola'],
                ['state_id' => 10, 'city' => 'Carrabelle'],
                ['state_id' => 10, 'city' => 'Lanark Village'],
                ['state_id' => 10, 'city' => 'Eastpoint'],
                ['state_id' => 10, 'city' => 'Chattahoochee'],
                ['state_id' => 10, 'city' => 'Greensboro'],
                ['state_id' => 10, 'city' => 'Gretna'],
                ['state_id' => 10, 'city' => 'Havana'],
                ['state_id' => 10, 'city' => 'Midway'],
                ['state_id' => 10, 'city' => 'Quincy'],
                ['state_id' => 10, 'city' => 'Bell'],
                ['state_id' => 10, 'city' => 'Trenton'],
                ['state_id' => 10, 'city' => 'Moore Haven'],
                ['state_id' => 10, 'city' => 'Palmdale'],
                ['state_id' => 10, 'city' => 'Port Saint Joe'],
                ['state_id' => 10, 'city' => 'Jasper'],
                ['state_id' => 10, 'city' => 'Jennings'],
                ['state_id' => 10, 'city' => 'White Springs'],
                ['state_id' => 10, 'city' => 'Bowling Green'],
                ['state_id' => 10, 'city' => 'Ona'],
                ['state_id' => 10, 'city' => 'Wauchula'],
                ['state_id' => 10, 'city' => 'Zolfo Springs'],
                ['state_id' => 10, 'city' => 'Clewiston'],
                ['state_id' => 10, 'city' => 'Felda'],
                ['state_id' => 10, 'city' => 'Labelle'],
                ['state_id' => 10, 'city' => 'Brooksville'],
                ['state_id' => 10, 'city' => 'Spring Hill'],
                ['state_id' => 10, 'city' => 'Istachatta'],
                ['state_id' => 10, 'city' => 'Nobleton'],
                ['state_id' => 10, 'city' => 'Avon Park'],
                ['state_id' => 10, 'city' => 'Lake Placid'],
                ['state_id' => 10, 'city' => 'Lorida'],
                ['state_id' => 10, 'city' => 'Sebring'],
                ['state_id' => 10, 'city' => 'Venus'],
                ['state_id' => 10, 'city' => 'Balm'],
                ['state_id' => 10, 'city' => 'Brandon'],
                ['state_id' => 10, 'city' => 'Dover'],
                ['state_id' => 10, 'city' => 'Durant'],
                ['state_id' => 10, 'city' => 'Gibsonton'],
                ['state_id' => 10, 'city' => 'Lithia'],
                ['state_id' => 10, 'city' => 'Lutz'],
                ['state_id' => 10, 'city' => 'Mango'],
                ['state_id' => 10, 'city' => 'Odessa'],
                ['state_id' => 10, 'city' => 'Plant City'],
                ['state_id' => 10, 'city' => 'Riverview'],
                ['state_id' => 10, 'city' => 'Ruskin'],
                ['state_id' => 10, 'city' => 'Sun City Center'],
                ['state_id' => 10, 'city' => 'Apollo Beach'],
                ['state_id' => 10, 'city' => 'Seffner'],
                ['state_id' => 10, 'city' => 'Sun City'],
                ['state_id' => 10, 'city' => 'Sydney'],
                ['state_id' => 10, 'city' => 'Thonotosassa'],
                ['state_id' => 10, 'city' => 'Valrico'],
                ['state_id' => 10, 'city' => 'Wimauma'],
                ['state_id' => 10, 'city' => 'Tampa'],
                ['state_id' => 10, 'city' => 'Bonifay'],
                ['state_id' => 10, 'city' => 'Noma'],
                ['state_id' => 10, 'city' => 'Ponce De Leon'],
                ['state_id' => 10, 'city' => 'Westville'],
                ['state_id' => 10, 'city' => 'Fellsmere'],
                ['state_id' => 10, 'city' => 'Roseland'],
                ['state_id' => 10, 'city' => 'Vero Beach'],
                ['state_id' => 10, 'city' => 'Wabasso'],
                ['state_id' => 10, 'city' => 'Winter Beach'],
                ['state_id' => 10, 'city' => 'Alford'],
                ['state_id' => 10, 'city' => 'Bascom'],
                ['state_id' => 10, 'city' => 'Campbellton'],
                ['state_id' => 10, 'city' => 'Cottondale'],
                ['state_id' => 10, 'city' => 'Cypress'],
                ['state_id' => 10, 'city' => 'Graceville'],
                ['state_id' => 10, 'city' => 'Grand Ridge'],
                ['state_id' => 10, 'city' => 'Greenwood'],
                ['state_id' => 10, 'city' => 'Malone'],
                ['state_id' => 10, 'city' => 'Marianna'],
                ['state_id' => 10, 'city' => 'Sneads'],
                ['state_id' => 10, 'city' => 'Lamont'],
                ['state_id' => 10, 'city' => 'Lloyd'],
                ['state_id' => 10, 'city' => 'Monticello'],
                ['state_id' => 10, 'city' => 'Wacissa'],
                ['state_id' => 10, 'city' => 'Debary'],
                ['state_id' => 10, 'city' => 'Day'],
                ['state_id' => 10, 'city' => 'Mayo'],
                ['state_id' => 10, 'city' => 'Astor'],
                ['state_id' => 10, 'city' => 'Lady Lake'],
                ['state_id' => 10, 'city' => 'Altoona'],
                ['state_id' => 10, 'city' => 'Eustis'],
                ['state_id' => 10, 'city' => 'Grand Island'],
                ['state_id' => 10, 'city' => 'Mount Dora'],
                ['state_id' => 10, 'city' => 'Paisley'],
                ['state_id' => 10, 'city' => 'Sorrento'],
                ['state_id' => 10, 'city' => 'Tavares'],
                ['state_id' => 10, 'city' => 'Umatilla'],
                ['state_id' => 10, 'city' => 'Astatula'],
                ['state_id' => 10, 'city' => 'Clermont'],
                ['state_id' => 10, 'city' => 'Ferndale'],
                ['state_id' => 10, 'city' => 'Fruitland Park'],
                ['state_id' => 10, 'city' => 'Groveland'],
                ['state_id' => 10, 'city' => 'Howey In The Hills'],
                ['state_id' => 10, 'city' => 'Leesburg'],
                ['state_id' => 10, 'city' => 'Mascotte'],
                ['state_id' => 10, 'city' => 'Minneola'],
                ['state_id' => 10, 'city' => 'Montverde'],
                ['state_id' => 10, 'city' => 'Okahumpka'],
                ['state_id' => 10, 'city' => 'Yalaha'],
                ['state_id' => 10, 'city' => 'Fort Myers'],
                ['state_id' => 10, 'city' => 'North Fort Myers'],
                ['state_id' => 10, 'city' => 'Cape Coral'],
                ['state_id' => 10, 'city' => 'Alva'],
                ['state_id' => 10, 'city' => 'Boca Grande'],
                ['state_id' => 10, 'city' => 'Bokeelia'],
                ['state_id' => 10, 'city' => 'Captiva'],
                ['state_id' => 10, 'city' => 'Estero'],
                ['state_id' => 10, 'city' => 'Fort Myers Beach'],
                ['state_id' => 10, 'city' => 'Pineland'],
                ['state_id' => 10, 'city' => 'Saint James City'],
                ['state_id' => 10, 'city' => 'Sanibel'],
                ['state_id' => 10, 'city' => 'Bonita Springs'],
                ['state_id' => 10, 'city' => 'Woodville'],
                ['state_id' => 10, 'city' => 'Bronson'],
                ['state_id' => 10, 'city' => 'Cedar Key'],
                ['state_id' => 10, 'city' => 'Chiefland'],
                ['state_id' => 10, 'city' => 'Gulf Hammock'],
                ['state_id' => 10, 'city' => 'Morriston'],
                ['state_id' => 10, 'city' => 'Otter Creek'],
                ['state_id' => 10, 'city' => 'Williston'],
                ['state_id' => 10, 'city' => 'Inglis'],
                ['state_id' => 10, 'city' => 'Yankeetown'],
                ['state_id' => 10, 'city' => 'Bristol'],
                ['state_id' => 10, 'city' => 'Hosford'],
                ['state_id' => 10, 'city' => 'Sumatra'],
                ['state_id' => 10, 'city' => 'Telogia'],
                ['state_id' => 10, 'city' => 'Lee'],
                ['state_id' => 10, 'city' => 'Greenville'],
                ['state_id' => 10, 'city' => 'Madison'],
                ['state_id' => 10, 'city' => 'Pinetta'],
                ['state_id' => 10, 'city' => 'Bradenton'],
                ['state_id' => 10, 'city' => 'Cortez'],
                ['state_id' => 10, 'city' => 'Anna Maria'],
                ['state_id' => 10, 'city' => 'Bradenton Beach'],
                ['state_id' => 10, 'city' => 'Holmes Beach'],
                ['state_id' => 10, 'city' => 'Parrish'],
                ['state_id' => 10, 'city' => 'Palmetto'],
                ['state_id' => 10, 'city' => 'Ellenton'],
                ['state_id' => 10, 'city' => 'Longboat Key'],
                ['state_id' => 10, 'city' => 'Sarasota'],
                ['state_id' => 10, 'city' => 'Terra Ceia'],
                ['state_id' => 10, 'city' => 'Myakka City'],
                ['state_id' => 10, 'city' => 'Manasota'],
                ['state_id' => 10, 'city' => 'Oneco'],
                ['state_id' => 10, 'city' => 'Tallevast'],
                ['state_id' => 10, 'city' => 'Candler'],
                ['state_id' => 10, 'city' => 'Citra'],
                ['state_id' => 10, 'city' => 'Eastlake Weir'],
                ['state_id' => 10, 'city' => 'Fort Mc Coy'],
                ['state_id' => 10, 'city' => 'Ocklawaha'],
                ['state_id' => 10, 'city' => 'Orange Springs'],
                ['state_id' => 10, 'city' => 'Sparr'],
                ['state_id' => 10, 'city' => 'Weirsdale'],
                ['state_id' => 10, 'city' => 'Anthony'],
                ['state_id' => 10, 'city' => 'Fairfield'],
                ['state_id' => 10, 'city' => 'Lowell'],
                ['state_id' => 10, 'city' => 'Mc Intosh'],
                ['state_id' => 10, 'city' => 'Orange Lake'],
                ['state_id' => 10, 'city' => 'Reddick'],
                ['state_id' => 10, 'city' => 'Belleview'],
                ['state_id' => 10, 'city' => 'Ocala'],
                ['state_id' => 10, 'city' => 'Silver Springs'],
                ['state_id' => 10, 'city' => 'Summerfield'],
                ['state_id' => 10, 'city' => 'Hobe Sound'],
                ['state_id' => 10, 'city' => 'Indiantown'],
                ['state_id' => 10, 'city' => 'Jensen Beach'],
                ['state_id' => 10, 'city' => 'Palm City'],
                ['state_id' => 10, 'city' => 'Port Salerno'],
                ['state_id' => 10, 'city' => 'Stuart'],
                ['state_id' => 10, 'city' => 'Hialeah'],
                ['state_id' => 10, 'city' => 'Homestead'],
                ['state_id' => 10, 'city' => 'Opa Locka'],
                ['state_id' => 10, 'city' => 'Miami Gardens'],
                ['state_id' => 10, 'city' => 'Miami'],
                ['state_id' => 10, 'city' => 'Miami Beach'],
                ['state_id' => 10, 'city' => 'Coral Gables'],
                ['state_id' => 10, 'city' => 'Key Biscayne'],
                ['state_id' => 10, 'city' => 'North Miami Beach'],
                ['state_id' => 10, 'city' => 'Long Key'],
                ['state_id' => 10, 'city' => 'Islamorada'],
                ['state_id' => 10, 'city' => 'Key Largo'],
                ['state_id' => 10, 'city' => 'Key West'],
                ['state_id' => 10, 'city' => 'Summerland Key'],
                ['state_id' => 10, 'city' => 'Big Pine Key'],
                ['state_id' => 10, 'city' => 'Marathon'],
                ['state_id' => 10, 'city' => 'Key Colony Beach'],
                ['state_id' => 10, 'city' => 'Marathon Shores'],
                ['state_id' => 10, 'city' => 'Tavernier'],
                ['state_id' => 10, 'city' => 'Bryceville'],
                ['state_id' => 10, 'city' => 'Callahan'],
                ['state_id' => 10, 'city' => 'Fernandina Beach'],
                ['state_id' => 10, 'city' => 'Yulee'],
                ['state_id' => 10, 'city' => 'Hilliard'],
                ['state_id' => 10, 'city' => 'Baker'],
                ['state_id' => 10, 'city' => 'Crestview'],
                ['state_id' => 10, 'city' => 'Milligan'],
                ['state_id' => 10, 'city' => 'Destin'],
                ['state_id' => 10, 'city' => 'Eglin Afb'],
                ['state_id' => 10, 'city' => 'Hurlburt Field'],
                ['state_id' => 10, 'city' => 'Fort Walton Beach'],
                ['state_id' => 10, 'city' => 'Holt'],
                ['state_id' => 10, 'city' => 'Laurel Hill'],
                ['state_id' => 10, 'city' => 'Mary Esther'],
                ['state_id' => 10, 'city' => 'Niceville'],
                ['state_id' => 10, 'city' => 'Shalimar'],
                ['state_id' => 10, 'city' => 'Valparaiso'],
                ['state_id' => 10, 'city' => 'Okeechobee'],
                ['state_id' => 10, 'city' => 'Apopka'],
                ['state_id' => 10, 'city' => 'Christmas'],
                ['state_id' => 10, 'city' => 'Clarcona'],
                ['state_id' => 10, 'city' => 'Maitland'],
                ['state_id' => 10, 'city' => 'Plymouth'],
                ['state_id' => 10, 'city' => 'Tangerine'],
                ['state_id' => 10, 'city' => 'Winter Park'],
                ['state_id' => 10, 'city' => 'Zellwood'],
                ['state_id' => 10, 'city' => 'Gotha'],
                ['state_id' => 10, 'city' => 'Killarney'],
                ['state_id' => 10, 'city' => 'Oakland'],
                ['state_id' => 10, 'city' => 'Ocoee'],
                ['state_id' => 10, 'city' => 'Winter Garden'],
                ['state_id' => 10, 'city' => 'Windermere'],
                ['state_id' => 10, 'city' => 'Intercession City'],
                ['state_id' => 10, 'city' => 'Kenansville'],
                ['state_id' => 10, 'city' => 'Kissimmee'],
                ['state_id' => 10, 'city' => 'Saint Cloud'],
                ['state_id' => 10, 'city' => 'West Palm Beach'],
                ['state_id' => 10, 'city' => 'North Palm Beach'],
                ['state_id' => 10, 'city' => 'Palm Beach Gardens'],
                ['state_id' => 10, 'city' => 'Wellington'],
                ['state_id' => 10, 'city' => 'Royal Palm Beach'],
                ['state_id' => 10, 'city' => 'Boynton Beach'],
                ['state_id' => 10, 'city' => 'Boca Raton'],
                ['state_id' => 10, 'city' => 'Belle Glade'],
                ['state_id' => 10, 'city' => 'Canal Point'],
                ['state_id' => 10, 'city' => 'Delray Beach'],
                ['state_id' => 10, 'city' => 'Lake Worth'],
                ['state_id' => 10, 'city' => 'Greenacres'],
                ['state_id' => 10, 'city' => 'Jupiter'],
                ['state_id' => 10, 'city' => 'Lake Harbor'],
                ['state_id' => 10, 'city' => 'Loxahatchee'],
                ['state_id' => 10, 'city' => 'Pahokee'],
                ['state_id' => 10, 'city' => 'Palm Beach'],
                ['state_id' => 10, 'city' => 'South Bay'],
                ['state_id' => 10, 'city' => 'Dade City'],
                ['state_id' => 10, 'city' => 'Crystal Springs'],
                ['state_id' => 10, 'city' => 'Lacoochee'],
                ['state_id' => 10, 'city' => 'Zephyrhills'],
                ['state_id' => 10, 'city' => 'Wesley Chapel'],
                ['state_id' => 10, 'city' => 'Saint Leo'],
                ['state_id' => 10, 'city' => 'San Antonio'],
                ['state_id' => 10, 'city' => 'Trilby'],
                ['state_id' => 10, 'city' => 'Land O Lakes'],
                ['state_id' => 10, 'city' => 'New Port Richey'],
                ['state_id' => 10, 'city' => 'Hudson'],
                ['state_id' => 10, 'city' => 'Port Richey'],
                ['state_id' => 10, 'city' => 'Aripeka'],
                ['state_id' => 10, 'city' => 'Elfers'],
                ['state_id' => 10, 'city' => 'Holiday'],
                ['state_id' => 10, 'city' => 'Saint Petersburg'],
                ['state_id' => 10, 'city' => 'Bay Pines'],
                ['state_id' => 10, 'city' => 'Clearwater'],
                ['state_id' => 10, 'city' => 'Clearwater Beach'],
                ['state_id' => 10, 'city' => 'Largo'],
                ['state_id' => 10, 'city' => 'Seminole'],
                ['state_id' => 10, 'city' => 'Pinellas Park'],
                ['state_id' => 10, 'city' => 'Indian Rocks Beach'],
                ['state_id' => 10, 'city' => 'Belleair Beach'],
                ['state_id' => 10, 'city' => 'Ozona'],
                ['state_id' => 10, 'city' => 'Oldsmar'],
                ['state_id' => 10, 'city' => 'Crystal Beach'],
                ['state_id' => 10, 'city' => 'Palm Harbor'],
                ['state_id' => 10, 'city' => 'Tarpon Springs'],
                ['state_id' => 10, 'city' => 'Safety Harbor'],
                ['state_id' => 10, 'city' => 'Dunedin'],
                ['state_id' => 10, 'city' => 'Lakeland'],
                ['state_id' => 10, 'city' => 'Alturas'],
                ['state_id' => 10, 'city' => 'Auburndale'],
                ['state_id' => 10, 'city' => 'Babson Park'],
                ['state_id' => 10, 'city' => 'Bartow'],
                ['state_id' => 10, 'city' => 'Bradley'],
                ['state_id' => 10, 'city' => 'Davenport'],
                ['state_id' => 10, 'city' => 'Dundee'],
                ['state_id' => 10, 'city' => 'Eagle Lake'],
                ['state_id' => 10, 'city' => 'Eaton Park'],
                ['state_id' => 10, 'city' => 'Fort Meade'],
                ['state_id' => 10, 'city' => 'Frostproof'],
                ['state_id' => 10, 'city' => 'Haines City'],
                ['state_id' => 10, 'city' => 'Highland City'],
                ['state_id' => 10, 'city' => 'Homeland'],
                ['state_id' => 10, 'city' => 'Kathleen'],
                ['state_id' => 10, 'city' => 'Lake Alfred'],
                ['state_id' => 10, 'city' => 'Lake Hamilton'],
                ['state_id' => 10, 'city' => 'Lake Wales'],
                ['state_id' => 10, 'city' => 'Lakeshore'],
                ['state_id' => 10, 'city' => 'Indian Lake Estates'],
                ['state_id' => 10, 'city' => 'Nalcrest'],
                ['state_id' => 10, 'city' => 'Loughman'],
                ['state_id' => 10, 'city' => 'Mulberry'],
                ['state_id' => 10, 'city' => 'Nichols'],
                ['state_id' => 10, 'city' => 'River Ranch'],
                ['state_id' => 10, 'city' => 'Polk City'],
                ['state_id' => 10, 'city' => 'Waverly'],
                ['state_id' => 10, 'city' => 'Winter Haven'],
                ['state_id' => 10, 'city' => 'Bostwick'],
                ['state_id' => 10, 'city' => 'Crescent City'],
                ['state_id' => 10, 'city' => 'East Palatka'],
                ['state_id' => 10, 'city' => 'Grandin'],
                ['state_id' => 10, 'city' => 'Georgetown'],
                ['state_id' => 10, 'city' => 'Florahome'],
                ['state_id' => 10, 'city' => 'Hollister'],
                ['state_id' => 10, 'city' => 'Interlachen'],
                ['state_id' => 10, 'city' => 'Lake Como'],
                ['state_id' => 10, 'city' => 'Palatka'],
                ['state_id' => 10, 'city' => 'Pomona Park'],
                ['state_id' => 10, 'city' => 'Putnam Hall'],
                ['state_id' => 10, 'city' => 'San Mateo'],
                ['state_id' => 10, 'city' => 'Satsuma'],
                ['state_id' => 10, 'city' => 'Welaka'],
                ['state_id' => 10, 'city' => 'Melrose'],
                ['state_id' => 10, 'city' => 'Ponte Vedra Beach'],
                ['state_id' => 10, 'city' => 'Elkton'],
                ['state_id' => 10, 'city' => 'Saint Augustine'],
                ['state_id' => 10, 'city' => 'Ponte Vedra'],
                ['state_id' => 10, 'city' => 'Hastings'],
                ['state_id' => 10, 'city' => 'Saint Johns'],
                ['state_id' => 10, 'city' => 'Fort Pierce'],
                ['state_id' => 10, 'city' => 'Port Saint Lucie'],
                ['state_id' => 10, 'city' => 'Bagdad'],
                ['state_id' => 10, 'city' => 'Gulf Breeze'],
                ['state_id' => 10, 'city' => 'Jay'],
                ['state_id' => 10, 'city' => 'Navarre'],
                ['state_id' => 10, 'city' => 'Milton'],
                ['state_id' => 10, 'city' => 'Englewood'],
                ['state_id' => 10, 'city' => 'Osprey'],
                ['state_id' => 10, 'city' => 'Laurel'],
                ['state_id' => 10, 'city' => 'Nokomis'],
                ['state_id' => 10, 'city' => 'Venice'],
                ['state_id' => 10, 'city' => 'North Port'],
                ['state_id' => 10, 'city' => 'Altamonte Springs'],
                ['state_id' => 10, 'city' => 'Casselberry'],
                ['state_id' => 10, 'city' => 'Winter Springs'],
                ['state_id' => 10, 'city' => 'Geneva'],
                ['state_id' => 10, 'city' => 'Goldenrod'],
                ['state_id' => 10, 'city' => 'Lake Mary'],
                ['state_id' => 10, 'city' => 'Lake Monroe'],
                ['state_id' => 10, 'city' => 'Longwood'],
                ['state_id' => 10, 'city' => 'Oviedo'],
                ['state_id' => 10, 'city' => 'Sanford'],
                ['state_id' => 10, 'city' => 'Mid Florida'],
                ['state_id' => 10, 'city' => 'The Villages'],
                ['state_id' => 10, 'city' => 'Bushnell'],
                ['state_id' => 10, 'city' => 'Center Hill'],
                ['state_id' => 10, 'city' => 'Coleman'],
                ['state_id' => 10, 'city' => 'Lake Panasoffkee'],
                ['state_id' => 10, 'city' => 'Sumterville'],
                ['state_id' => 10, 'city' => 'Webster'],
                ['state_id' => 10, 'city' => 'Oxford'],
                ['state_id' => 10, 'city' => 'Wildwood'],
                ['state_id' => 10, 'city' => 'Branford'],
                ['state_id' => 10, 'city' => 'Live Oak'],
                ['state_id' => 10, 'city' => 'Mc Alpin'],
                ['state_id' => 10, 'city' => 'O Brien'],
                ['state_id' => 10, 'city' => 'Wellborn'],
                ['state_id' => 10, 'city' => 'Perry'],
                ['state_id' => 10, 'city' => 'Salem'],
                ['state_id' => 10, 'city' => 'Shady Grove'],
                ['state_id' => 10, 'city' => 'Steinhatchee'],
                ['state_id' => 10, 'city' => 'Raiford'],
                ['state_id' => 10, 'city' => 'Lake Butler'],
                ['state_id' => 10, 'city' => 'Worthington Springs'],
                ['state_id' => 10, 'city' => 'Barberville'],
                ['state_id' => 10, 'city' => 'Daytona Beach'],
                ['state_id' => 10, 'city' => 'Port Orange'],
                ['state_id' => 10, 'city' => 'De Leon Springs'],
                ['state_id' => 10, 'city' => 'Edgewater'],
                ['state_id' => 10, 'city' => 'New Smyrna Beach'],
                ['state_id' => 10, 'city' => 'Ormond Beach'],
                ['state_id' => 10, 'city' => 'Pierson'],
                ['state_id' => 10, 'city' => 'Seville'],
                ['state_id' => 10, 'city' => 'Cassadaga'],
                ['state_id' => 10, 'city' => 'Deland'],
                ['state_id' => 10, 'city' => 'Glenwood'],
                ['state_id' => 10, 'city' => 'Deltona'],
                ['state_id' => 10, 'city' => 'Lake Helen'],
                ['state_id' => 10, 'city' => 'Oak Hill'],
                ['state_id' => 10, 'city' => 'Orange City'],
                ['state_id' => 10, 'city' => 'Osteen'],
                ['state_id' => 10, 'city' => 'Crawfordville'],
                ['state_id' => 10, 'city' => 'Panacea'],
                ['state_id' => 10, 'city' => 'Saint Marks'],
                ['state_id' => 10, 'city' => 'Sopchoppy'],
                ['state_id' => 10, 'city' => 'Argyle'],
                ['state_id' => 10, 'city' => 'Defuniak Springs'],
                ['state_id' => 10, 'city' => 'Mossy Head'],
                ['state_id' => 10, 'city' => 'Freeport'],
                ['state_id' => 10, 'city' => 'Santa Rosa Beach'],
                ['state_id' => 10, 'city' => 'Rosemary Beach'],
                ['state_id' => 10, 'city' => 'Paxton'],
                ['state_id' => 10, 'city' => 'Miramar Beach'],
                ['state_id' => 10, 'city' => 'Caryville'],
                ['state_id' => 10, 'city' => 'Chipley'],
                ['state_id' => 10, 'city' => 'Ebro'],
                ['state_id' => 10, 'city' => 'Vernon'],
                ['state_id' => 10, 'city' => 'Wausau']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
