<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State43TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of TN - Tennessee.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 43, 'city' => 'Andersonville'],
                ['state_id' => 43, 'city' => 'Briceville'],
                ['state_id' => 43, 'city' => 'Clinton'],
                ['state_id' => 43, 'city' => 'Lake City'],
                ['state_id' => 43, 'city' => 'Norris'],
                ['state_id' => 43, 'city' => 'Oak Ridge'],
                ['state_id' => 43, 'city' => 'Bell Buckle'],
                ['state_id' => 43, 'city' => 'Shelbyville'],
                ['state_id' => 43, 'city' => 'Unionville'],
                ['state_id' => 43, 'city' => 'Wartrace'],
                ['state_id' => 43, 'city' => 'Normandy'],
                ['state_id' => 43, 'city' => 'Big Sandy'],
                ['state_id' => 43, 'city' => 'Camden'],
                ['state_id' => 43, 'city' => 'Eva'],
                ['state_id' => 43, 'city' => 'Holladay'],
                ['state_id' => 43, 'city' => 'Pikeville'],
                ['state_id' => 43, 'city' => 'Alcoa'],
                ['state_id' => 43, 'city' => 'Friendsville'],
                ['state_id' => 43, 'city' => 'Louisville'],
                ['state_id' => 43, 'city' => 'Maryville'],
                ['state_id' => 43, 'city' => 'Rockford'],
                ['state_id' => 43, 'city' => 'Tallassee'],
                ['state_id' => 43, 'city' => 'Townsend'],
                ['state_id' => 43, 'city' => 'Walland'],
                ['state_id' => 43, 'city' => 'Charleston'],
                ['state_id' => 43, 'city' => 'Cleveland'],
                ['state_id' => 43, 'city' => 'Mc Donald'],
                ['state_id' => 43, 'city' => 'Caryville'],
                ['state_id' => 43, 'city' => 'Duff'],
                ['state_id' => 43, 'city' => 'Jacksboro'],
                ['state_id' => 43, 'city' => 'Jellico'],
                ['state_id' => 43, 'city' => 'La Follette'],
                ['state_id' => 43, 'city' => 'Newcomb'],
                ['state_id' => 43, 'city' => 'Pioneer'],
                ['state_id' => 43, 'city' => 'Auburntown'],
                ['state_id' => 43, 'city' => 'Bradyville'],
                ['state_id' => 43, 'city' => 'Readyville'],
                ['state_id' => 43, 'city' => 'Woodbury'],
                ['state_id' => 43, 'city' => 'Mc Kenzie'],
                ['state_id' => 43, 'city' => 'Atwood'],
                ['state_id' => 43, 'city' => 'Mc Lemoresville'],
                ['state_id' => 43, 'city' => 'Trezevant'],
                ['state_id' => 43, 'city' => 'Bruceton'],
                ['state_id' => 43, 'city' => 'Buena Vista'],
                ['state_id' => 43, 'city' => 'Cedar Grove'],
                ['state_id' => 43, 'city' => 'Clarksburg'],
                ['state_id' => 43, 'city' => 'Hollow Rock'],
                ['state_id' => 43, 'city' => 'Huntingdon'],
                ['state_id' => 43, 'city' => 'Lavinia'],
                ['state_id' => 43, 'city' => 'Westport'],
                ['state_id' => 43, 'city' => 'Yuma'],
                ['state_id' => 43, 'city' => 'Elizabethton'],
                ['state_id' => 43, 'city' => 'Hampton'],
                ['state_id' => 43, 'city' => 'Milligan College'],
                ['state_id' => 43, 'city' => 'Roan Mountain'],
                ['state_id' => 43, 'city' => 'Watauga'],
                ['state_id' => 43, 'city' => 'Ashland City'],
                ['state_id' => 43, 'city' => 'Chapmansboro'],
                ['state_id' => 43, 'city' => 'Kingston Springs'],
                ['state_id' => 43, 'city' => 'Pegram'],
                ['state_id' => 43, 'city' => 'Pleasant View'],
                ['state_id' => 43, 'city' => 'Enville'],
                ['state_id' => 43, 'city' => 'Henderson'],
                ['state_id' => 43, 'city' => 'Jacks Creek'],
                ['state_id' => 43, 'city' => 'Luray'],
                ['state_id' => 43, 'city' => 'Arthur'],
                ['state_id' => 43, 'city' => 'Clairfield'],
                ['state_id' => 43, 'city' => 'Cumberland Gap'],
                ['state_id' => 43, 'city' => 'Eagan'],
                ['state_id' => 43, 'city' => 'Harrogate'],
                ['state_id' => 43, 'city' => 'Lone Mountain'],
                ['state_id' => 43, 'city' => 'New Tazewell'],
                ['state_id' => 43, 'city' => 'Pruden'],
                ['state_id' => 43, 'city' => 'Shawanee'],
                ['state_id' => 43, 'city' => 'Speedwell'],
                ['state_id' => 43, 'city' => 'Tazewell'],
                ['state_id' => 43, 'city' => 'Celina'],
                ['state_id' => 43, 'city' => 'Moss'],
                ['state_id' => 43, 'city' => 'Bybee'],
                ['state_id' => 43, 'city' => 'Cosby'],
                ['state_id' => 43, 'city' => 'Del Rio'],
                ['state_id' => 43, 'city' => 'Hartford'],
                ['state_id' => 43, 'city' => 'Newport'],
                ['state_id' => 43, 'city' => 'Parrottsville'],
                ['state_id' => 43, 'city' => 'Beechgrove'],
                ['state_id' => 43, 'city' => 'Hillsboro'],
                ['state_id' => 43, 'city' => 'Manchester'],
                ['state_id' => 43, 'city' => 'Summitville'],
                ['state_id' => 43, 'city' => 'Tullahoma'],
                ['state_id' => 43, 'city' => 'Arnold Afb'],
                ['state_id' => 43, 'city' => 'Alamo'],
                ['state_id' => 43, 'city' => 'Bells'],
                ['state_id' => 43, 'city' => 'Crockett Mills'],
                ['state_id' => 43, 'city' => 'Friendship'],
                ['state_id' => 43, 'city' => 'Maury City'],
                ['state_id' => 43, 'city' => 'Fruitvale'],
                ['state_id' => 43, 'city' => 'Gadsden'],
                ['state_id' => 43, 'city' => 'Crab Orchard'],
                ['state_id' => 43, 'city' => 'Crossville'],
                ['state_id' => 43, 'city' => 'Pleasant Hill'],
                ['state_id' => 43, 'city' => 'Antioch'],
                ['state_id' => 43, 'city' => 'Goodlettsville'],
                ['state_id' => 43, 'city' => 'Hermitage'],
                ['state_id' => 43, 'city' => 'Joelton'],
                ['state_id' => 43, 'city' => 'Madison'],
                ['state_id' => 43, 'city' => 'Old Hickory'],
                ['state_id' => 43, 'city' => 'Whites Creek'],
                ['state_id' => 43, 'city' => 'Nashville'],
                ['state_id' => 43, 'city' => 'Bath Springs'],
                ['state_id' => 43, 'city' => 'Decaturville'],
                ['state_id' => 43, 'city' => 'Parsons'],
                ['state_id' => 43, 'city' => 'Scotts Hill'],
                ['state_id' => 43, 'city' => 'Sugar Tree'],
                ['state_id' => 43, 'city' => 'Alexandria'],
                ['state_id' => 43, 'city' => 'Dowelltown'],
                ['state_id' => 43, 'city' => 'Liberty'],
                ['state_id' => 43, 'city' => 'Smithville'],
                ['state_id' => 43, 'city' => 'Burns'],
                ['state_id' => 43, 'city' => 'Charlotte'],
                ['state_id' => 43, 'city' => 'Cumberland Furnace'],
                ['state_id' => 43, 'city' => 'Dickson'],
                ['state_id' => 43, 'city' => 'Slayden'],
                ['state_id' => 43, 'city' => 'Vanleer'],
                ['state_id' => 43, 'city' => 'White Bluff'],
                ['state_id' => 43, 'city' => 'Bogota'],
                ['state_id' => 43, 'city' => 'Dyersburg'],
                ['state_id' => 43, 'city' => 'Finley'],
                ['state_id' => 43, 'city' => 'Lenox'],
                ['state_id' => 43, 'city' => 'Newbern'],
                ['state_id' => 43, 'city' => 'Tigrett'],
                ['state_id' => 43, 'city' => 'Trimble'],
                ['state_id' => 43, 'city' => 'Braden'],
                ['state_id' => 43, 'city' => 'Gallaway'],
                ['state_id' => 43, 'city' => 'Laconia'],
                ['state_id' => 43, 'city' => 'La Grange'],
                ['state_id' => 43, 'city' => 'Macon'],
                ['state_id' => 43, 'city' => 'Moscow'],
                ['state_id' => 43, 'city' => 'Oakland'],
                ['state_id' => 43, 'city' => 'Rossville'],
                ['state_id' => 43, 'city' => 'Somerville'],
                ['state_id' => 43, 'city' => 'Williston'],
                ['state_id' => 43, 'city' => 'Allardt'],
                ['state_id' => 43, 'city' => 'Clarkrange'],
                ['state_id' => 43, 'city' => 'Jamestown'],
                ['state_id' => 43, 'city' => 'Grimsley'],
                ['state_id' => 43, 'city' => 'Pall Mall'],
                ['state_id' => 43, 'city' => 'Wilder'],
                ['state_id' => 43, 'city' => 'Belvidere'],
                ['state_id' => 43, 'city' => 'Cowan'],
                ['state_id' => 43, 'city' => 'Decherd'],
                ['state_id' => 43, 'city' => 'Estill Springs'],
                ['state_id' => 43, 'city' => 'Huntland'],
                ['state_id' => 43, 'city' => 'Sewanee'],
                ['state_id' => 43, 'city' => 'Sherwood'],
                ['state_id' => 43, 'city' => 'Winchester'],
                ['state_id' => 43, 'city' => 'Kenton'],
                ['state_id' => 43, 'city' => 'Bradford'],
                ['state_id' => 43, 'city' => 'Dyer'],
                ['state_id' => 43, 'city' => 'Eaton'],
                ['state_id' => 43, 'city' => 'Gibson'],
                ['state_id' => 43, 'city' => 'Humboldt'],
                ['state_id' => 43, 'city' => 'Idlewild'],
                ['state_id' => 43, 'city' => 'Medina'],
                ['state_id' => 43, 'city' => 'Milan'],
                ['state_id' => 43, 'city' => 'Rutherford'],
                ['state_id' => 43, 'city' => 'Trenton'],
                ['state_id' => 43, 'city' => 'Yorkville'],
                ['state_id' => 43, 'city' => 'Ardmore'],
                ['state_id' => 43, 'city' => 'Elkton'],
                ['state_id' => 43, 'city' => 'Frankewing'],
                ['state_id' => 43, 'city' => 'Goodspring'],
                ['state_id' => 43, 'city' => 'Lynnville'],
                ['state_id' => 43, 'city' => 'Minor Hill'],
                ['state_id' => 43, 'city' => 'Prospect'],
                ['state_id' => 43, 'city' => 'Pulaski'],
                ['state_id' => 43, 'city' => 'Bean Station'],
                ['state_id' => 43, 'city' => 'Blaine'],
                ['state_id' => 43, 'city' => 'Powder Springs'],
                ['state_id' => 43, 'city' => 'Rutledge'],
                ['state_id' => 43, 'city' => 'Thorn Hill'],
                ['state_id' => 43, 'city' => 'Washburn'],
                ['state_id' => 43, 'city' => 'Afton'],
                ['state_id' => 43, 'city' => 'Chuckey'],
                ['state_id' => 43, 'city' => 'Greeneville'],
                ['state_id' => 43, 'city' => 'Midway'],
                ['state_id' => 43, 'city' => 'Mohawk'],
                ['state_id' => 43, 'city' => 'Mosheim'],
                ['state_id' => 43, 'city' => 'Altamont'],
                ['state_id' => 43, 'city' => 'Beersheba Springs'],
                ['state_id' => 43, 'city' => 'Coalmont'],
                ['state_id' => 43, 'city' => 'Gruetli Laager'],
                ['state_id' => 43, 'city' => 'Monteagle'],
                ['state_id' => 43, 'city' => 'Palmer'],
                ['state_id' => 43, 'city' => 'Pelham'],
                ['state_id' => 43, 'city' => 'Tracy City'],
                ['state_id' => 43, 'city' => 'Lowland'],
                ['state_id' => 43, 'city' => 'Morristown'],
                ['state_id' => 43, 'city' => 'Russellville'],
                ['state_id' => 43, 'city' => 'Talbott'],
                ['state_id' => 43, 'city' => 'Whitesburg'],
                ['state_id' => 43, 'city' => 'Apison'],
                ['state_id' => 43, 'city' => 'Bakewell'],
                ['state_id' => 43, 'city' => 'Birchwood'],
                ['state_id' => 43, 'city' => 'Collegedale'],
                ['state_id' => 43, 'city' => 'Harrison'],
                ['state_id' => 43, 'city' => 'Hixson'],
                ['state_id' => 43, 'city' => 'Lookout Mountain'],
                ['state_id' => 43, 'city' => 'Lupton City'],
                ['state_id' => 43, 'city' => 'Ooltewah'],
                ['state_id' => 43, 'city' => 'Sale Creek'],
                ['state_id' => 43, 'city' => 'Signal Mountain'],
                ['state_id' => 43, 'city' => 'Soddy Daisy'],
                ['state_id' => 43, 'city' => 'Chattanooga'],
                ['state_id' => 43, 'city' => 'Kyles Ford'],
                ['state_id' => 43, 'city' => 'Sneedville'],
                ['state_id' => 43, 'city' => 'Bolivar'],
                ['state_id' => 43, 'city' => 'Grand Junction'],
                ['state_id' => 43, 'city' => 'Hickory Valley'],
                ['state_id' => 43, 'city' => 'Hornsby'],
                ['state_id' => 43, 'city' => 'Middleton'],
                ['state_id' => 43, 'city' => 'Pocahontas'],
                ['state_id' => 43, 'city' => 'Saulsbury'],
                ['state_id' => 43, 'city' => 'Whiteville'],
                ['state_id' => 43, 'city' => 'Silerton'],
                ['state_id' => 43, 'city' => 'Toone'],
                ['state_id' => 43, 'city' => 'Counce'],
                ['state_id' => 43, 'city' => 'Crump'],
                ['state_id' => 43, 'city' => 'Morris Chapel'],
                ['state_id' => 43, 'city' => 'Pickwick Dam'],
                ['state_id' => 43, 'city' => 'Saltillo'],
                ['state_id' => 43, 'city' => 'Savannah'],
                ['state_id' => 43, 'city' => 'Shiloh'],
                ['state_id' => 43, 'city' => 'Olivehill'],
                ['state_id' => 43, 'city' => 'Church Hill'],
                ['state_id' => 43, 'city' => 'Mount Carmel'],
                ['state_id' => 43, 'city' => 'Bulls Gap'],
                ['state_id' => 43, 'city' => 'Eidson'],
                ['state_id' => 43, 'city' => 'Mooresburg'],
                ['state_id' => 43, 'city' => 'Rogersville'],
                ['state_id' => 43, 'city' => 'Surgoinsville'],
                ['state_id' => 43, 'city' => 'Brownsville'],
                ['state_id' => 43, 'city' => 'Stanton'],
                ['state_id' => 43, 'city' => 'Darden'],
                ['state_id' => 43, 'city' => 'Huron'],
                ['state_id' => 43, 'city' => 'Lexington'],
                ['state_id' => 43, 'city' => 'Reagan'],
                ['state_id' => 43, 'city' => 'Sardis'],
                ['state_id' => 43, 'city' => 'Wildersville'],
                ['state_id' => 43, 'city' => 'Buchanan'],
                ['state_id' => 43, 'city' => 'Como'],
                ['state_id' => 43, 'city' => 'Cottage Grove'],
                ['state_id' => 43, 'city' => 'Henry'],
                ['state_id' => 43, 'city' => 'Mansfield'],
                ['state_id' => 43, 'city' => 'Paris'],
                ['state_id' => 43, 'city' => 'Puryear'],
                ['state_id' => 43, 'city' => 'Springville'],
                ['state_id' => 43, 'city' => 'Bon Aqua'],
                ['state_id' => 43, 'city' => 'Centerville'],
                ['state_id' => 43, 'city' => 'Lyles'],
                ['state_id' => 43, 'city' => 'Nunnelly'],
                ['state_id' => 43, 'city' => 'Only'],
                ['state_id' => 43, 'city' => 'Duck River'],
                ['state_id' => 43, 'city' => 'Primm Springs'],
                ['state_id' => 43, 'city' => 'Erin'],
                ['state_id' => 43, 'city' => 'Stewart'],
                ['state_id' => 43, 'city' => 'Tennessee Ridge'],
                ['state_id' => 43, 'city' => 'Hurricane Mills'],
                ['state_id' => 43, 'city' => 'Mc Ewen'],
                ['state_id' => 43, 'city' => 'New Johnsonville'],
                ['state_id' => 43, 'city' => 'Waverly'],
                ['state_id' => 43, 'city' => 'Gainesboro'],
                ['state_id' => 43, 'city' => 'Granville'],
                ['state_id' => 43, 'city' => 'Whitleyville'],
                ['state_id' => 43, 'city' => 'Dandridge'],
                ['state_id' => 43, 'city' => 'Jefferson City'],
                ['state_id' => 43, 'city' => 'New Market'],
                ['state_id' => 43, 'city' => 'Strawberry Plains'],
                ['state_id' => 43, 'city' => 'White Pine'],
                ['state_id' => 43, 'city' => 'Butler'],
                ['state_id' => 43, 'city' => 'Laurel Bloomery'],
                ['state_id' => 43, 'city' => 'Mountain City'],
                ['state_id' => 43, 'city' => 'Shady Valley'],
                ['state_id' => 43, 'city' => 'Trade'],
                ['state_id' => 43, 'city' => 'Corryton'],
                ['state_id' => 43, 'city' => 'Heiskell'],
                ['state_id' => 43, 'city' => 'Mascot'],
                ['state_id' => 43, 'city' => 'Powell'],
                ['state_id' => 43, 'city' => 'Knoxville'],
                ['state_id' => 43, 'city' => 'Wynnburg'],
                ['state_id' => 43, 'city' => 'Tiptonville'],
                ['state_id' => 43, 'city' => 'Ridgely'],
                ['state_id' => 43, 'city' => 'Gates'],
                ['state_id' => 43, 'city' => 'Halls'],
                ['state_id' => 43, 'city' => 'Henning'],
                ['state_id' => 43, 'city' => 'Ripley'],
                ['state_id' => 43, 'city' => 'Ethridge'],
                ['state_id' => 43, 'city' => 'Five Points'],
                ['state_id' => 43, 'city' => 'Iron City'],
                ['state_id' => 43, 'city' => 'Lawrenceburg'],
                ['state_id' => 43, 'city' => 'Leoma'],
                ['state_id' => 43, 'city' => 'Loretto'],
                ['state_id' => 43, 'city' => 'Saint Joseph'],
                ['state_id' => 43, 'city' => 'Summertown'],
                ['state_id' => 43, 'city' => 'Westpoint'],
                ['state_id' => 43, 'city' => 'Hohenwald'],
                ['state_id' => 43, 'city' => 'Petersburg'],
                ['state_id' => 43, 'city' => 'Elora'],
                ['state_id' => 43, 'city' => 'Fayetteville'],
                ['state_id' => 43, 'city' => 'Flintville'],
                ['state_id' => 43, 'city' => 'Kelso'],
                ['state_id' => 43, 'city' => 'Mulberry'],
                ['state_id' => 43, 'city' => 'Dellrose'],
                ['state_id' => 43, 'city' => 'Taft'],
                ['state_id' => 43, 'city' => 'Greenback'],
                ['state_id' => 43, 'city' => 'Lenoir City'],
                ['state_id' => 43, 'city' => 'Loudon'],
                ['state_id' => 43, 'city' => 'Philadelphia'],
                ['state_id' => 43, 'city' => 'Athens'],
                ['state_id' => 43, 'city' => 'Calhoun'],
                ['state_id' => 43, 'city' => 'Englewood'],
                ['state_id' => 43, 'city' => 'Etowah'],
                ['state_id' => 43, 'city' => 'Riceville'],
                ['state_id' => 43, 'city' => 'Niota'],
                ['state_id' => 43, 'city' => 'Adamsville'],
                ['state_id' => 43, 'city' => 'Bethel Springs'],
                ['state_id' => 43, 'city' => 'Finger'],
                ['state_id' => 43, 'city' => 'Guys'],
                ['state_id' => 43, 'city' => 'Michie'],
                ['state_id' => 43, 'city' => 'Milledgeville'],
                ['state_id' => 43, 'city' => 'Ramer'],
                ['state_id' => 43, 'city' => 'Selmer'],
                ['state_id' => 43, 'city' => 'Stantonville'],
                ['state_id' => 43, 'city' => 'Chewalla'],
                ['state_id' => 43, 'city' => 'Lafayette'],
                ['state_id' => 43, 'city' => 'Red Boiling Springs'],
                ['state_id' => 43, 'city' => 'Jackson'],
                ['state_id' => 43, 'city' => 'Beech Bluff'],
                ['state_id' => 43, 'city' => 'Medon'],
                ['state_id' => 43, 'city' => 'Oakfield'],
                ['state_id' => 43, 'city' => 'Pinson'],
                ['state_id' => 43, 'city' => 'Spring Creek'],
                ['state_id' => 43, 'city' => 'Denmark'],
                ['state_id' => 43, 'city' => 'Mercer'],
                ['state_id' => 43, 'city' => 'Guild'],
                ['state_id' => 43, 'city' => 'Jasper'],
                ['state_id' => 43, 'city' => 'Sequatchie'],
                ['state_id' => 43, 'city' => 'South Pittsburg'],
                ['state_id' => 43, 'city' => 'Whiteside'],
                ['state_id' => 43, 'city' => 'Whitwell'],
                ['state_id' => 43, 'city' => 'Belfast'],
                ['state_id' => 43, 'city' => 'Chapel Hill'],
                ['state_id' => 43, 'city' => 'Cornersville'],
                ['state_id' => 43, 'city' => 'Lewisburg'],
                ['state_id' => 43, 'city' => 'Spring Hill'],
                ['state_id' => 43, 'city' => 'Columbia'],
                ['state_id' => 43, 'city' => 'Culleoka'],
                ['state_id' => 43, 'city' => 'Hampshire'],
                ['state_id' => 43, 'city' => 'Mount Pleasant'],
                ['state_id' => 43, 'city' => 'Santa Fe'],
                ['state_id' => 43, 'city' => 'Williamsport'],
                ['state_id' => 43, 'city' => 'Decatur'],
                ['state_id' => 43, 'city' => 'Georgetown'],
                ['state_id' => 43, 'city' => 'Ten Mile'],
                ['state_id' => 43, 'city' => 'Cokercreek'],
                ['state_id' => 43, 'city' => 'Madisonville'],
                ['state_id' => 43, 'city' => 'Tellico Plains'],
                ['state_id' => 43, 'city' => 'Sweetwater'],
                ['state_id' => 43, 'city' => 'Vonore'],
                ['state_id' => 43, 'city' => 'Clarksville'],
                ['state_id' => 43, 'city' => 'Cunningham'],
                ['state_id' => 43, 'city' => 'Palmyra'],
                ['state_id' => 43, 'city' => 'Southside'],
                ['state_id' => 43, 'city' => 'Woodlawn'],
                ['state_id' => 43, 'city' => 'Lynchburg'],
                ['state_id' => 43, 'city' => 'Coalfield'],
                ['state_id' => 43, 'city' => 'Deer Lodge'],
                ['state_id' => 43, 'city' => 'Rugby'],
                ['state_id' => 43, 'city' => 'Lancing'],
                ['state_id' => 43, 'city' => 'Oakdale'],
                ['state_id' => 43, 'city' => 'Oliver Springs'],
                ['state_id' => 43, 'city' => 'Petros'],
                ['state_id' => 43, 'city' => 'Sunbright'],
                ['state_id' => 43, 'city' => 'Wartburg'],
                ['state_id' => 43, 'city' => 'Hornbeak'],
                ['state_id' => 43, 'city' => 'Obion'],
                ['state_id' => 43, 'city' => 'Rives'],
                ['state_id' => 43, 'city' => 'Samburg'],
                ['state_id' => 43, 'city' => 'South Fulton'],
                ['state_id' => 43, 'city' => 'Troy'],
                ['state_id' => 43, 'city' => 'Union City'],
                ['state_id' => 43, 'city' => 'Woodland Mills'],
                ['state_id' => 43, 'city' => 'Allons'],
                ['state_id' => 43, 'city' => 'Allred'],
                ['state_id' => 43, 'city' => 'Alpine'],
                ['state_id' => 43, 'city' => 'Crawford'],
                ['state_id' => 43, 'city' => 'Hilham'],
                ['state_id' => 43, 'city' => 'Livingston'],
                ['state_id' => 43, 'city' => 'Monroe'],
                ['state_id' => 43, 'city' => 'Rickman'],
                ['state_id' => 43, 'city' => 'Linden'],
                ['state_id' => 43, 'city' => 'Lobelville'],
                ['state_id' => 43, 'city' => 'Byrdstown'],
                ['state_id' => 43, 'city' => 'Benton'],
                ['state_id' => 43, 'city' => 'Conasauga'],
                ['state_id' => 43, 'city' => 'Copperhill'],
                ['state_id' => 43, 'city' => 'Delano'],
                ['state_id' => 43, 'city' => 'Ducktown'],
                ['state_id' => 43, 'city' => 'Farner'],
                ['state_id' => 43, 'city' => 'Ocoee'],
                ['state_id' => 43, 'city' => 'Old Fort'],
                ['state_id' => 43, 'city' => 'Reliance'],
                ['state_id' => 43, 'city' => 'Turtletown'],
                ['state_id' => 43, 'city' => 'Cookeville'],
                ['state_id' => 43, 'city' => 'Baxter'],
                ['state_id' => 43, 'city' => 'Bloomington Springs'],
                ['state_id' => 43, 'city' => 'Buffalo Valley'],
                ['state_id' => 43, 'city' => 'Monterey'],
                ['state_id' => 43, 'city' => 'Silver Point'],
                ['state_id' => 43, 'city' => 'Dayton'],
                ['state_id' => 43, 'city' => 'Evensville'],
                ['state_id' => 43, 'city' => 'Grandview'],
                ['state_id' => 43, 'city' => 'Graysville'],
                ['state_id' => 43, 'city' => 'Spring City'],
                ['state_id' => 43, 'city' => 'Harriman'],
                ['state_id' => 43, 'city' => 'Kingston'],
                ['state_id' => 43, 'city' => 'Rockwood'],
                ['state_id' => 43, 'city' => 'Adams'],
                ['state_id' => 43, 'city' => 'Cedar Hill'],
                ['state_id' => 43, 'city' => 'Cross Plains'],
                ['state_id' => 43, 'city' => 'Greenbrier'],
                ['state_id' => 43, 'city' => 'Orlinda'],
                ['state_id' => 43, 'city' => 'Ridgetop'],
                ['state_id' => 43, 'city' => 'Springfield'],
                ['state_id' => 43, 'city' => 'White House'],
                ['state_id' => 43, 'city' => 'Christiana'],
                ['state_id' => 43, 'city' => 'Eagleville'],
                ['state_id' => 43, 'city' => 'Fosterville'],
                ['state_id' => 43, 'city' => 'Lascassas'],
                ['state_id' => 43, 'city' => 'La Vergne'],
                ['state_id' => 43, 'city' => 'Milton'],
                ['state_id' => 43, 'city' => 'Murfreesboro'],
                ['state_id' => 43, 'city' => 'Rockvale'],
                ['state_id' => 43, 'city' => 'Smyrna'],
                ['state_id' => 43, 'city' => 'Elgin'],
                ['state_id' => 43, 'city' => 'Helenwood'],
                ['state_id' => 43, 'city' => 'Huntsville'],
                ['state_id' => 43, 'city' => 'Oneida'],
                ['state_id' => 43, 'city' => 'Robbins'],
                ['state_id' => 43, 'city' => 'Winfield'],
                ['state_id' => 43, 'city' => 'Dunlap'],
                ['state_id' => 43, 'city' => 'Gatlinburg'],
                ['state_id' => 43, 'city' => 'Kodak'],
                ['state_id' => 43, 'city' => 'Sevierville'],
                ['state_id' => 43, 'city' => 'Pigeon Forge'],
                ['state_id' => 43, 'city' => 'Seymour'],
                ['state_id' => 43, 'city' => 'Memphis'],
                ['state_id' => 43, 'city' => 'Arlington'],
                ['state_id' => 43, 'city' => 'Brunswick'],
                ['state_id' => 43, 'city' => 'Cordova'],
                ['state_id' => 43, 'city' => 'Collierville'],
                ['state_id' => 43, 'city' => 'Eads'],
                ['state_id' => 43, 'city' => 'Ellendale'],
                ['state_id' => 43, 'city' => 'Millington'],
                ['state_id' => 43, 'city' => 'Germantown'],
                ['state_id' => 43, 'city' => 'Carthage'],
                ['state_id' => 43, 'city' => 'Dixon Springs'],
                ['state_id' => 43, 'city' => 'Pleasant Shade'],
                ['state_id' => 43, 'city' => 'Riddleton'],
                ['state_id' => 43, 'city' => 'Brush Creek'],
                ['state_id' => 43, 'city' => 'Chestnut Mound'],
                ['state_id' => 43, 'city' => 'Elmwood'],
                ['state_id' => 43, 'city' => 'Gordonsville'],
                ['state_id' => 43, 'city' => 'Hickman'],
                ['state_id' => 43, 'city' => 'Lancaster'],
                ['state_id' => 43, 'city' => 'Big Rock'],
                ['state_id' => 43, 'city' => 'Bumpus Mills'],
                ['state_id' => 43, 'city' => 'Cumberland City'],
                ['state_id' => 43, 'city' => 'Dover'],
                ['state_id' => 43, 'city' => 'Indian Mound'],
                ['state_id' => 43, 'city' => 'Blountville'],
                ['state_id' => 43, 'city' => 'Bluff City'],
                ['state_id' => 43, 'city' => 'Bristol'],
                ['state_id' => 43, 'city' => 'Kingsport'],
                ['state_id' => 43, 'city' => 'Piney Flats'],
                ['state_id' => 43, 'city' => 'Bethpage'],
                ['state_id' => 43, 'city' => 'Castalian Springs'],
                ['state_id' => 43, 'city' => 'Cottontown'],
                ['state_id' => 43, 'city' => 'Gallatin'],
                ['state_id' => 43, 'city' => 'Hendersonville'],
                ['state_id' => 43, 'city' => 'Mitchellville'],
                ['state_id' => 43, 'city' => 'Portland'],
                ['state_id' => 43, 'city' => 'Westmoreland'],
                ['state_id' => 43, 'city' => 'Atoka'],
                ['state_id' => 43, 'city' => 'Brighton'],
                ['state_id' => 43, 'city' => 'Burlison'],
                ['state_id' => 43, 'city' => 'Covington'],
                ['state_id' => 43, 'city' => 'Drummonds'],
                ['state_id' => 43, 'city' => 'Mason'],
                ['state_id' => 43, 'city' => 'Munford'],
                ['state_id' => 43, 'city' => 'Tipton'],
                ['state_id' => 43, 'city' => 'Hartsville'],
                ['state_id' => 43, 'city' => 'Erwin'],
                ['state_id' => 43, 'city' => 'Flag Pond'],
                ['state_id' => 43, 'city' => 'Unicoi'],
                ['state_id' => 43, 'city' => 'Luttrell'],
                ['state_id' => 43, 'city' => 'Maynardville'],
                ['state_id' => 43, 'city' => 'Sharps Chapel'],
                ['state_id' => 43, 'city' => 'Spencer'],
                ['state_id' => 43, 'city' => 'Mcminnville'],
                ['state_id' => 43, 'city' => 'Morrison'],
                ['state_id' => 43, 'city' => 'Smartt'],
                ['state_id' => 43, 'city' => 'Viola'],
                ['state_id' => 43, 'city' => 'Campaign'],
                ['state_id' => 43, 'city' => 'Rock Island'],
                ['state_id' => 43, 'city' => 'Johnson City'],
                ['state_id' => 43, 'city' => 'Fall Branch'],
                ['state_id' => 43, 'city' => 'Jonesborough'],
                ['state_id' => 43, 'city' => 'Limestone'],
                ['state_id' => 43, 'city' => 'Mountain Home'],
                ['state_id' => 43, 'city' => 'Telford'],
                ['state_id' => 43, 'city' => 'Clifton'],
                ['state_id' => 43, 'city' => 'Collinwood'],
                ['state_id' => 43, 'city' => 'Cypress Inn'],
                ['state_id' => 43, 'city' => 'Lutts'],
                ['state_id' => 43, 'city' => 'Waynesboro'],
                ['state_id' => 43, 'city' => 'Dresden'],
                ['state_id' => 43, 'city' => 'Dukedom'],
                ['state_id' => 43, 'city' => 'Gleason'],
                ['state_id' => 43, 'city' => 'Greenfield'],
                ['state_id' => 43, 'city' => 'Martin'],
                ['state_id' => 43, 'city' => 'Palmersville'],
                ['state_id' => 43, 'city' => 'Sharon'],
                ['state_id' => 43, 'city' => 'Doyle'],
                ['state_id' => 43, 'city' => 'Quebeck'],
                ['state_id' => 43, 'city' => 'Sparta'],
                ['state_id' => 43, 'city' => 'Walling'],
                ['state_id' => 43, 'city' => 'Arrington'],
                ['state_id' => 43, 'city' => 'Brentwood'],
                ['state_id' => 43, 'city' => 'College Grove'],
                ['state_id' => 43, 'city' => 'Fairview'],
                ['state_id' => 43, 'city' => 'Franklin'],
                ['state_id' => 43, 'city' => 'Nolensville'],
                ['state_id' => 43, 'city' => 'Thompsons Station'],
                ['state_id' => 43, 'city' => 'Gladeville'],
                ['state_id' => 43, 'city' => 'Lebanon'],
                ['state_id' => 43, 'city' => 'Mount Juliet'],
                ['state_id' => 43, 'city' => 'Norene'],
                ['state_id' => 43, 'city' => 'Watertown', 'state_id' => 43]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
