<?php
namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State19TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of LA - Louisiana.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 19, 'city' => 'Branch'],
                ['state_id' => 19, 'city' => 'Church Point'],
                ['state_id' => 19, 'city' => 'Crowley'],
                ['state_id' => 19, 'city' => 'Egan'],
                ['state_id' => 19, 'city' => 'Estherwood'],
                ['state_id' => 19, 'city' => 'Evangeline'],
                ['state_id' => 19, 'city' => 'Iota'],
                ['state_id' => 19, 'city' => 'Mermentau'],
                ['state_id' => 19, 'city' => 'Morse'],
                ['state_id' => 19, 'city' => 'Rayne'],
                ['state_id' => 19, 'city' => 'Elizabeth'],
                ['state_id' => 19, 'city' => 'Grant'],
                ['state_id' => 19, 'city' => 'Kinder'],
                ['state_id' => 19, 'city' => 'Leblanc'],
                ['state_id' => 19, 'city' => 'Mittie'],
                ['state_id' => 19, 'city' => 'Oberlin'],
                ['state_id' => 19, 'city' => 'Reeves'],
                ['state_id' => 19, 'city' => 'Oakdale'],
                ['state_id' => 19, 'city' => 'Donaldsonville'],
                ['state_id' => 19, 'city' => 'Gonzales'],
                ['state_id' => 19, 'city' => 'Brittany'],
                ['state_id' => 19, 'city' => 'Darrow'],
                ['state_id' => 19, 'city' => 'Duplessis'],
                ['state_id' => 19, 'city' => 'Geismar'],
                ['state_id' => 19, 'city' => 'Burnside'],
                ['state_id' => 19, 'city' => 'Prairieville'],
                ['state_id' => 19, 'city' => 'Saint Amant'],
                ['state_id' => 19, 'city' => 'Sorrento'],
                ['state_id' => 19, 'city' => 'Pierre Part'],
                ['state_id' => 19, 'city' => 'Belle Rose'],
                ['state_id' => 19, 'city' => 'Labadieville'],
                ['state_id' => 19, 'city' => 'Napoleonville'],
                ['state_id' => 19, 'city' => 'Paincourtville'],
                ['state_id' => 19, 'city' => 'Plattenville'],
                ['state_id' => 19, 'city' => 'Bordelonville'],
                ['state_id' => 19, 'city' => 'Bunkie'],
                ['state_id' => 19, 'city' => 'Center Point'],
                ['state_id' => 19, 'city' => 'Cottonport'],
                ['state_id' => 19, 'city' => 'Dupont'],
                ['state_id' => 19, 'city' => 'Effie'],
                ['state_id' => 19, 'city' => 'Evergreen'],
                ['state_id' => 19, 'city' => 'Hamburg'],
                ['state_id' => 19, 'city' => 'Hessmer'],
                ['state_id' => 19, 'city' => 'Mansura'],
                ['state_id' => 19, 'city' => 'Marksville'],
                ['state_id' => 19, 'city' => 'Moreauville'],
                ['state_id' => 19, 'city' => 'Plaucheville'],
                ['state_id' => 19, 'city' => 'Simmesport'],
                ['state_id' => 19, 'city' => 'Deridder'],
                ['state_id' => 19, 'city' => 'Dry Creek'],
                ['state_id' => 19, 'city' => 'Longville'],
                ['state_id' => 19, 'city' => 'Merryville'],
                ['state_id' => 19, 'city' => 'Ragley'],
                ['state_id' => 19, 'city' => 'Singer'],
                ['state_id' => 19, 'city' => 'Sugartown'],
                ['state_id' => 19, 'city' => 'Arcadia'],
                ['state_id' => 19, 'city' => 'Bienville'],
                ['state_id' => 19, 'city' => 'Castor'],
                ['state_id' => 19, 'city' => 'Gibsland'],
                ['state_id' => 19, 'city' => 'Jamestown'],
                ['state_id' => 19, 'city' => 'Ringgold'],
                ['state_id' => 19, 'city' => 'Saline'],
                ['state_id' => 19, 'city' => 'Taylor'],
                ['state_id' => 19, 'city' => 'Benton'],
                ['state_id' => 19, 'city' => 'Haughton'],
                ['state_id' => 19, 'city' => 'Elm Grove'],
                ['state_id' => 19, 'city' => 'Plain Dealing'],
                ['state_id' => 19, 'city' => 'Princeton'],
                ['state_id' => 19, 'city' => 'Barksdale Afb'],
                ['state_id' => 19, 'city' => 'Bossier City'],
                ['state_id' => 19, 'city' => 'Belcher'],
                ['state_id' => 19, 'city' => 'Bethany'],
                ['state_id' => 19, 'city' => 'Blanchard'],
                ['state_id' => 19, 'city' => 'Gilliam'],
                ['state_id' => 19, 'city' => 'Greenwood'],
                ['state_id' => 19, 'city' => 'Hosston'],
                ['state_id' => 19, 'city' => 'Ida'],
                ['state_id' => 19, 'city' => 'Keithville'],
                ['state_id' => 19, 'city' => 'Mooringsport'],
                ['state_id' => 19, 'city' => 'Oil City'],
                ['state_id' => 19, 'city' => 'Rodessa'],
                ['state_id' => 19, 'city' => 'Vivian'],
                ['state_id' => 19, 'city' => 'Shreveport'],
                ['state_id' => 19, 'city' => 'Lake Charles'],
                ['state_id' => 19, 'city' => 'Bell City'],
                ['state_id' => 19, 'city' => 'Dequincy'],
                ['state_id' => 19, 'city' => 'Hayes'],
                ['state_id' => 19, 'city' => 'Iowa'],
                ['state_id' => 19, 'city' => 'Starks'],
                ['state_id' => 19, 'city' => 'Sulphur'],
                ['state_id' => 19, 'city' => 'Vinton'],
                ['state_id' => 19, 'city' => 'Westlake'],
                ['state_id' => 19, 'city' => 'Clarks'],
                ['state_id' => 19, 'city' => 'Columbia'],
                ['state_id' => 19, 'city' => 'Grayson'],
                ['state_id' => 19, 'city' => 'Kelly'],
                ['state_id' => 19, 'city' => 'Cameron'],
                ['state_id' => 19, 'city' => 'Creole'],
                ['state_id' => 19, 'city' => 'Grand Chenier'],
                ['state_id' => 19, 'city' => 'Hackberry'],
                ['state_id' => 19, 'city' => 'Harrisonburg'],
                ['state_id' => 19, 'city' => 'Jonesville'],
                ['state_id' => 19, 'city' => 'Rhinehart'],
                ['state_id' => 19, 'city' => 'Sicily Island'],
                ['state_id' => 19, 'city' => 'Aimwell'],
                ['state_id' => 19, 'city' => 'Enterprise'],
                ['state_id' => 19, 'city' => 'Athens'],
                ['state_id' => 19, 'city' => 'Haynesville'],
                ['state_id' => 19, 'city' => 'Homer'],
                ['state_id' => 19, 'city' => 'Lisbon'],
                ['state_id' => 19, 'city' => 'Summerfield'],
                ['state_id' => 19, 'city' => 'Acme'],
                ['state_id' => 19, 'city' => 'Clayton'],
                ['state_id' => 19, 'city' => 'Ferriday'],
                ['state_id' => 19, 'city' => 'Monterey'],
                ['state_id' => 19, 'city' => 'Vidalia'],
                ['state_id' => 19, 'city' => 'Wildsville'],
                ['state_id' => 19, 'city' => 'Frierson'],
                ['state_id' => 19, 'city' => 'Gloster'],
                ['state_id' => 19, 'city' => 'Grand Cane'],
                ['state_id' => 19, 'city' => 'Keatchie'],
                ['state_id' => 19, 'city' => 'Logansport'],
                ['state_id' => 19, 'city' => 'Longstreet'],
                ['state_id' => 19, 'city' => 'Mansfield'],
                ['state_id' => 19, 'city' => 'Pelican'],
                ['state_id' => 19, 'city' => 'Stonewall'],
                ['state_id' => 19, 'city' => 'Baker'],
                ['state_id' => 19, 'city' => 'Greenwell Springs'],
                ['state_id' => 19, 'city' => 'Pride'],
                ['state_id' => 19, 'city' => 'Zachary'],
                ['state_id' => 19, 'city' => 'Baton Rouge'],
                ['state_id' => 19, 'city' => 'Lake Providence'],
                ['state_id' => 19, 'city' => 'Sondheimer'],
                ['state_id' => 19, 'city' => 'Transylvania'],
                ['state_id' => 19, 'city' => 'Clinton'],
                ['state_id' => 19, 'city' => 'Ethel'],
                ['state_id' => 19, 'city' => 'Jackson'],
                ['state_id' => 19, 'city' => 'Norwood'],
                ['state_id' => 19, 'city' => 'Slaughter'],
                ['state_id' => 19, 'city' => 'Wilson'],
                ['state_id' => 19, 'city' => 'Basile'],
                ['state_id' => 19, 'city' => 'Chataignier'],
                ['state_id' => 19, 'city' => 'Mamou'],
                ['state_id' => 19, 'city' => 'Pine Prairie'],
                ['state_id' => 19, 'city' => 'Reddell'],
                ['state_id' => 19, 'city' => 'Turkey Creek'],
                ['state_id' => 19, 'city' => 'Ville Platte'],
                ['state_id' => 19, 'city' => 'Saint Landry'],
                ['state_id' => 19, 'city' => 'Baskin'],
                ['state_id' => 19, 'city' => 'Crowville'],
                ['state_id' => 19, 'city' => 'Fort Necessity'],
                ['state_id' => 19, 'city' => 'Jigger'],
                ['state_id' => 19, 'city' => 'Winnsboro'],
                ['state_id' => 19, 'city' => 'Chase'],
                ['state_id' => 19, 'city' => 'Gilbert'],
                ['state_id' => 19, 'city' => 'Wisner'],
                ['state_id' => 19, 'city' => 'Bentley'],
                ['state_id' => 19, 'city' => 'Colfax'],
                ['state_id' => 19, 'city' => 'Dry Prong'],
                ['state_id' => 19, 'city' => 'Georgetown'],
                ['state_id' => 19, 'city' => 'Montgomery'],
                ['state_id' => 19, 'city' => 'Pollock'],
                ['state_id' => 19, 'city' => 'Avery Island'],
                ['state_id' => 19, 'city' => 'Jeanerette'],
                ['state_id' => 19, 'city' => 'Loreauville'],
                ['state_id' => 19, 'city' => 'New Iberia'],
                ['state_id' => 19, 'city' => 'Lydia'],
                ['state_id' => 19, 'city' => 'Carville'],
                ['state_id' => 19, 'city' => 'Grosse Tete'],
                ['state_id' => 19, 'city' => 'Maringouin'],
                ['state_id' => 19, 'city' => 'Plaquemine'],
                ['state_id' => 19, 'city' => 'Rosedale'],
                ['state_id' => 19, 'city' => 'Saint Gabriel'],
                ['state_id' => 19, 'city' => 'Sunshine'],
                ['state_id' => 19, 'city' => 'White Castle'],
                ['state_id' => 19, 'city' => 'Chatham'],
                ['state_id' => 19, 'city' => 'Eros'],
                ['state_id' => 19, 'city' => 'Hodge'],
                ['state_id' => 19, 'city' => 'Jonesboro'],
                ['state_id' => 19, 'city' => 'Quitman'],
                ['state_id' => 19, 'city' => 'Metairie'],
                ['state_id' => 19, 'city' => 'Barataria'],
                ['state_id' => 19, 'city' => 'Gretna'],
                ['state_id' => 19, 'city' => 'Harvey'],
                ['state_id' => 19, 'city' => 'Kenner'],
                ['state_id' => 19, 'city' => 'Lafitte'],
                ['state_id' => 19, 'city' => 'Marrero'],
                ['state_id' => 19, 'city' => 'Westwego'],
                ['state_id' => 19, 'city' => 'New Orleans'],
                ['state_id' => 19, 'city' => 'Grand Isle'],
                ['state_id' => 19, 'city' => 'Elton'],
                ['state_id' => 19, 'city' => 'Jennings'],
                ['state_id' => 19, 'city' => 'Lake Arthur'],
                ['state_id' => 19, 'city' => 'Roanoke'],
                ['state_id' => 19, 'city' => 'Welsh'],
                ['state_id' => 19, 'city' => 'Fenton'],
                ['state_id' => 19, 'city' => 'Lacassine'],
                ['state_id' => 19, 'city' => 'Lafayette'],
                ['state_id' => 19, 'city' => 'Broussard'],
                ['state_id' => 19, 'city' => 'Carencro'],
                ['state_id' => 19, 'city' => 'Duson'],
                ['state_id' => 19, 'city' => 'Milton'],
                ['state_id' => 19, 'city' => 'Scott'],
                ['state_id' => 19, 'city' => 'Youngsville'],
                ['state_id' => 19, 'city' => 'Thibodaux'],
                ['state_id' => 19, 'city' => 'Cut Off'],
                ['state_id' => 19, 'city' => 'Galliano'],
                ['state_id' => 19, 'city' => 'Gheens'],
                ['state_id' => 19, 'city' => 'Golden Meadow'],
                ['state_id' => 19, 'city' => 'Kraemer'],
                ['state_id' => 19, 'city' => 'Larose'],
                ['state_id' => 19, 'city' => 'Lockport'],
                ['state_id' => 19, 'city' => 'Mathews'],
                ['state_id' => 19, 'city' => 'Raceland'],
                ['state_id' => 19, 'city' => 'Jena'],
                ['state_id' => 19, 'city' => 'Trout'],
                ['state_id' => 19, 'city' => 'Olla'],
                ['state_id' => 19, 'city' => 'Tullos'],
                ['state_id' => 19, 'city' => 'Urania'],
                ['state_id' => 19, 'city' => 'Choudrant'],
                ['state_id' => 19, 'city' => 'Dubach'],
                ['state_id' => 19, 'city' => 'Grambling'],
                ['state_id' => 19, 'city' => 'Ruston'],
                ['state_id' => 19, 'city' => 'Simsboro'],
                ['state_id' => 19, 'city' => 'Maurepas'],
                ['state_id' => 19, 'city' => 'Springfield'],
                ['state_id' => 19, 'city' => 'Denham Springs'],
                ['state_id' => 19, 'city' => 'Albany'],
                ['state_id' => 19, 'city' => 'French Settlement'],
                ['state_id' => 19, 'city' => 'Holden'],
                ['state_id' => 19, 'city' => 'Livingston'],
                ['state_id' => 19, 'city' => 'Walker'],
                ['state_id' => 19, 'city' => 'Watson'],
                ['state_id' => 19, 'city' => 'Delta'],
                ['state_id' => 19, 'city' => 'Tallulah'],
                ['state_id' => 19, 'city' => 'Bastrop'],
                ['state_id' => 19, 'city' => 'Bonita'],
                ['state_id' => 19, 'city' => 'Collinston'],
                ['state_id' => 19, 'city' => 'Jones'],
                ['state_id' => 19, 'city' => 'Mer Rouge'],
                ['state_id' => 19, 'city' => 'Oak Ridge'],
                ['state_id' => 19, 'city' => 'Ashland'],
                ['state_id' => 19, 'city' => 'Goldonna'],
                ['state_id' => 19, 'city' => 'Powhatan'],
                ['state_id' => 19, 'city' => 'Campti'],
                ['state_id' => 19, 'city' => 'Clarence'],
                ['state_id' => 19, 'city' => 'Cloutierville'],
                ['state_id' => 19, 'city' => 'Flora'],
                ['state_id' => 19, 'city' => 'Gorum'],
                ['state_id' => 19, 'city' => 'Marthaville'],
                ['state_id' => 19, 'city' => 'Melrose'],
                ['state_id' => 19, 'city' => 'Mora'],
                ['state_id' => 19, 'city' => 'Natchez'],
                ['state_id' => 19, 'city' => 'Natchitoches'],
                ['state_id' => 19, 'city' => 'Provencal'],
                ['state_id' => 19, 'city' => 'Robeline'],
                ['state_id' => 19, 'city' => 'Monroe'],
                ['state_id' => 19, 'city' => 'Calhoun'],
                ['state_id' => 19, 'city' => 'Fairbanks'],
                ['state_id' => 19, 'city' => 'Sterlington'],
                ['state_id' => 19, 'city' => 'Swartz'],
                ['state_id' => 19, 'city' => 'West Monroe'],
                ['state_id' => 19, 'city' => 'Belle Chasse'],
                ['state_id' => 19, 'city' => 'Boothville'],
                ['state_id' => 19, 'city' => 'Braithwaite'],
                ['state_id' => 19, 'city' => 'Buras'],
                ['state_id' => 19, 'city' => 'Empire'],
                ['state_id' => 19, 'city' => 'Pilottown'],
                ['state_id' => 19, 'city' => 'Pointe A La Hache'],
                ['state_id' => 19, 'city' => 'Port Sulphur'],
                ['state_id' => 19, 'city' => 'Venice'],
                ['state_id' => 19, 'city' => 'Batchelor'],
                ['state_id' => 19, 'city' => 'Fordoche'],
                ['state_id' => 19, 'city' => 'Glynn'],
                ['state_id' => 19, 'city' => 'Innis'],
                ['state_id' => 19, 'city' => 'Jarreau'],
                ['state_id' => 19, 'city' => 'Lakeland'],
                ['state_id' => 19, 'city' => 'Lettsworth'],
                ['state_id' => 19, 'city' => 'Livonia'],
                ['state_id' => 19, 'city' => 'Lottie'],
                ['state_id' => 19, 'city' => 'Morganza'],
                ['state_id' => 19, 'city' => 'New Roads'],
                ['state_id' => 19, 'city' => 'Oscar'],
                ['state_id' => 19, 'city' => 'Rougon'],
                ['state_id' => 19, 'city' => 'Ventress'],
                ['state_id' => 19, 'city' => 'Alexandria'],
                ['state_id' => 19, 'city' => 'Cheneyville'],
                ['state_id' => 19, 'city' => 'Deville'],
                ['state_id' => 19, 'city' => 'Echo'],
                ['state_id' => 19, 'city' => 'Lecompte'],
                ['state_id' => 19, 'city' => 'Libuse'],
                ['state_id' => 19, 'city' => 'Pineville'],
                ['state_id' => 19, 'city' => 'Ruby'],
                ['state_id' => 19, 'city' => 'Ball'],
                ['state_id' => 19, 'city' => 'Boyce'],
                ['state_id' => 19, 'city' => 'Elmer'],
                ['state_id' => 19, 'city' => 'Flatwoods'],
                ['state_id' => 19, 'city' => 'Forest Hill'],
                ['state_id' => 19, 'city' => 'Gardner'],
                ['state_id' => 19, 'city' => 'Glenmora'],
                ['state_id' => 19, 'city' => 'Hineston'],
                ['state_id' => 19, 'city' => 'Lena'],
                ['state_id' => 19, 'city' => 'Longleaf'],
                ['state_id' => 19, 'city' => 'Otis'],
                ['state_id' => 19, 'city' => 'Sieper'],
                ['state_id' => 19, 'city' => 'Tioga'],
                ['state_id' => 19, 'city' => 'Woodworth'],
                ['state_id' => 19, 'city' => 'Coushatta'],
                ['state_id' => 19, 'city' => 'Hall Summit'],
                ['state_id' => 19, 'city' => 'Archibald'],
                ['state_id' => 19, 'city' => 'Delhi'],
                ['state_id' => 19, 'city' => 'Mangham'],
                ['state_id' => 19, 'city' => 'Rayville'],
                ['state_id' => 19, 'city' => 'Start'],
                ['state_id' => 19, 'city' => 'Pleasant Hill'],
                ['state_id' => 19, 'city' => 'Belmont'],
                ['state_id' => 19, 'city' => 'Converse'],
                ['state_id' => 19, 'city' => 'Fisher'],
                ['state_id' => 19, 'city' => 'Florien'],
                ['state_id' => 19, 'city' => 'Many'],
                ['state_id' => 19, 'city' => 'Negreet'],
                ['state_id' => 19, 'city' => 'Noble'],
                ['state_id' => 19, 'city' => 'Zwolle'],
                ['state_id' => 19, 'city' => 'Arabi'],
                ['state_id' => 19, 'city' => 'Chalmette'],
                ['state_id' => 19, 'city' => 'Meraux'],
                ['state_id' => 19, 'city' => 'Saint Bernard'],
                ['state_id' => 19, 'city' => 'Violet'],
                ['state_id' => 19, 'city' => 'Des Allemands'],
                ['state_id' => 19, 'city' => 'Ama'],
                ['state_id' => 19, 'city' => 'Boutte'],
                ['state_id' => 19, 'city' => 'Destrehan'],
                ['state_id' => 19, 'city' => 'Hahnville'],
                ['state_id' => 19, 'city' => 'Luling'],
                ['state_id' => 19, 'city' => 'New Sarpy'],
                ['state_id' => 19, 'city' => 'Norco'],
                ['state_id' => 19, 'city' => 'Paradis'],
                ['state_id' => 19, 'city' => 'Saint Rose'],
                ['state_id' => 19, 'city' => 'Greensburg'],
                ['state_id' => 19, 'city' => 'Pine Grove'],
                ['state_id' => 19, 'city' => 'Gramercy'],
                ['state_id' => 19, 'city' => 'Lutcher'],
                ['state_id' => 19, 'city' => 'Saint James'],
                ['state_id' => 19, 'city' => 'Vacherie'],
                ['state_id' => 19, 'city' => 'Convent'],
                ['state_id' => 19, 'city' => 'Hester'],
                ['state_id' => 19, 'city' => 'Paulina'],
                ['state_id' => 19, 'city' => 'Uncle Sam'],
                ['state_id' => 19, 'city' => 'Edgard'],
                ['state_id' => 19, 'city' => 'Garyville'],
                ['state_id' => 19, 'city' => 'La Place'],
                ['state_id' => 19, 'city' => 'Mount Airy'],
                ['state_id' => 19, 'city' => 'Reserve'],
                ['state_id' => 19, 'city' => 'Arnaudville'],
                ['state_id' => 19, 'city' => 'Eunice'],
                ['state_id' => 19, 'city' => 'Grand Coteau'],
                ['state_id' => 19, 'city' => 'Lawtell'],
                ['state_id' => 19, 'city' => 'Leonville'],
                ['state_id' => 19, 'city' => 'Opelousas'],
                ['state_id' => 19, 'city' => 'Port Barre'],
                ['state_id' => 19, 'city' => 'Sunset'],
                ['state_id' => 19, 'city' => 'Washington'],
                ['state_id' => 19, 'city' => 'Krotz Springs'],
                ['state_id' => 19, 'city' => 'Lebeau'],
                ['state_id' => 19, 'city' => 'Melville'],
                ['state_id' => 19, 'city' => 'Morrow'],
                ['state_id' => 19, 'city' => 'Palmetto'],
                ['state_id' => 19, 'city' => 'Breaux Bridge'],
                ['state_id' => 19, 'city' => 'Cade'],
                ['state_id' => 19, 'city' => 'Cecilia'],
                ['state_id' => 19, 'city' => 'Saint Martinville'],
                ['state_id' => 19, 'city' => 'Amelia'],
                ['state_id' => 19, 'city' => 'Berwick'],
                ['state_id' => 19, 'city' => 'Morgan City'],
                ['state_id' => 19, 'city' => 'Patterson'],
                ['state_id' => 19, 'city' => 'Baldwin'],
                ['state_id' => 19, 'city' => 'Centerville'],
                ['state_id' => 19, 'city' => 'Charenton'],
                ['state_id' => 19, 'city' => 'Franklin'],
                ['state_id' => 19, 'city' => 'Garden City'],
                ['state_id' => 19, 'city' => 'Abita Springs'],
                ['state_id' => 19, 'city' => 'Bush'],
                ['state_id' => 19, 'city' => 'Covington'],
                ['state_id' => 19, 'city' => 'Folsom'],
                ['state_id' => 19, 'city' => 'Lacombe'],
                ['state_id' => 19, 'city' => 'Madisonville'],
                ['state_id' => 19, 'city' => 'Mandeville'],
                ['state_id' => 19, 'city' => 'Pearl River'],
                ['state_id' => 19, 'city' => 'Saint Benedict'],
                ['state_id' => 19, 'city' => 'Slidell'],
                ['state_id' => 19, 'city' => 'Sun'],
                ['state_id' => 19, 'city' => 'Talisheek'],
                ['state_id' => 19, 'city' => 'Hammond'],
                ['state_id' => 19, 'city' => 'Akers'],
                ['state_id' => 19, 'city' => 'Amite'],
                ['state_id' => 19, 'city' => 'Fluker'],
                ['state_id' => 19, 'city' => 'Husser'],
                ['state_id' => 19, 'city' => 'Independence'],
                ['state_id' => 19, 'city' => 'Kentwood'],
                ['state_id' => 19, 'city' => 'Loranger'],
                ['state_id' => 19, 'city' => 'Natalbany'],
                ['state_id' => 19, 'city' => 'Ponchatoula'],
                ['state_id' => 19, 'city' => 'Robert'],
                ['state_id' => 19, 'city' => 'Roseland'],
                ['state_id' => 19, 'city' => 'Tangipahoa'],
                ['state_id' => 19, 'city' => 'Tickfaw'],
                ['state_id' => 19, 'city' => 'Newellton'],
                ['state_id' => 19, 'city' => 'Saint Joseph'],
                ['state_id' => 19, 'city' => 'Waterproof'],
                ['state_id' => 19, 'city' => 'Bourg'],
                ['state_id' => 19, 'city' => 'Chauvin'],
                ['state_id' => 19, 'city' => 'Donner'],
                ['state_id' => 19, 'city' => 'Dulac'],
                ['state_id' => 19, 'city' => 'Gibson'],
                ['state_id' => 19, 'city' => 'Gray'],
                ['state_id' => 19, 'city' => 'Houma'],
                ['state_id' => 19, 'city' => 'Montegut'],
                ['state_id' => 19, 'city' => 'Schriever'],
                ['state_id' => 19, 'city' => 'Theriot'],
                ['state_id' => 19, 'city' => 'Bernice'],
                ['state_id' => 19, 'city' => 'Downsville'],
                ['state_id' => 19, 'city' => 'Farmerville'],
                ['state_id' => 19, 'city' => 'Lillie'],
                ['state_id' => 19, 'city' => 'Marion'],
                ['state_id' => 19, 'city' => 'Spearsville'],
                ['state_id' => 19, 'city' => 'Abbeville'],
                ['state_id' => 19, 'city' => 'Delcambre'],
                ['state_id' => 19, 'city' => 'Erath'],
                ['state_id' => 19, 'city' => 'Gueydan'],
                ['state_id' => 19, 'city' => 'Kaplan'],
                ['state_id' => 19, 'city' => 'Maurice'],
                ['state_id' => 19, 'city' => 'Perry'],
                ['state_id' => 19, 'city' => 'Evans'],
                ['state_id' => 19, 'city' => 'Pitkin'],
                ['state_id' => 19, 'city' => 'Rosepine'],
                ['state_id' => 19, 'city' => 'Anacoco'],
                ['state_id' => 19, 'city' => 'Hornbeck'],
                ['state_id' => 19, 'city' => 'Kurthwood'],
                ['state_id' => 19, 'city' => 'Leesville'],
                ['state_id' => 19, 'city' => 'Fort Polk'],
                ['state_id' => 19, 'city' => 'New Llano'],
                ['state_id' => 19, 'city' => 'Simpson'],
                ['state_id' => 19, 'city' => 'Slagle'],
                ['state_id' => 19, 'city' => 'Angie'],
                ['state_id' => 19, 'city' => 'Bogalusa'],
                ['state_id' => 19, 'city' => 'Franklinton'],
                ['state_id' => 19, 'city' => 'Mount Hermon'],
                ['state_id' => 19, 'city' => 'Varnado'],
                ['state_id' => 19, 'city' => 'Cotton Valley'],
                ['state_id' => 19, 'city' => 'Cullen'],
                ['state_id' => 19, 'city' => 'Doyline'],
                ['state_id' => 19, 'city' => 'Dubberly'],
                ['state_id' => 19, 'city' => 'Heflin'],
                ['state_id' => 19, 'city' => 'Minden'],
                ['state_id' => 19, 'city' => 'Sarepta'],
                ['state_id' => 19, 'city' => 'Shongaloo'],
                ['state_id' => 19, 'city' => 'Sibley'],
                ['state_id' => 19, 'city' => 'Springhill'],
                ['state_id' => 19, 'city' => 'Addis'],
                ['state_id' => 19, 'city' => 'Brusly'],
                ['state_id' => 19, 'city' => 'Erwinville'],
                ['state_id' => 19, 'city' => 'Port Allen'],
                ['state_id' => 19, 'city' => 'Epps'],
                ['state_id' => 19, 'city' => 'Forest'],
                ['state_id' => 19, 'city' => 'Kilbourne'],
                ['state_id' => 19, 'city' => 'Oak Grove'],
                ['state_id' => 19, 'city' => 'Pioneer'],
                ['state_id' => 19, 'city' => 'Angola'],
                ['state_id' => 19, 'city' => 'Saint Francisville'],
                ['state_id' => 19, 'city' => 'Tunica'],
                ['state_id' => 19, 'city' => 'Wakefield'],
                ['state_id' => 19, 'city' => 'Weyanoke'],
                ['state_id' => 19, 'city' => 'Atlanta'],
                ['state_id' => 19, 'city' => 'Calvin'],
                ['state_id' => 19, 'city' => 'Dodson'],
                ['state_id' => 19, 'city' => 'Joyce'],
                ['state_id' => 19, 'city' => 'Saint Maurice'],
                ['state_id' => 19, 'city' => 'Sikes'],
                ['state_id' => 19, 'city' => 'Winnfield']
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
