<?php

namespace Database\Seeders\statecities;

use Illuminate\Database\Seeder;
use App\Models\City;
class State36TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Create Cities for the state of OH - Ohio.
        //If the table 'cities' exists, insert the data to the table.
        if (City::count() >= 0) {
            $cities = [
                ['state_id' => 36, 'city' => 'Bentonville'],
                ['state_id' => 36, 'city' => 'Manchester'],
                ['state_id' => 36, 'city' => 'Blue Creek'],
                ['state_id' => 36, 'city' => 'Cherry Fork'],
                ['state_id' => 36, 'city' => 'Lynx'],
                ['state_id' => 36, 'city' => 'Peebles'],
                ['state_id' => 36, 'city' => 'Seaman'],
                ['state_id' => 36, 'city' => 'West Union'],
                ['state_id' => 36, 'city' => 'Winchester'],
                ['state_id' => 36, 'city' => 'Lima'],
                ['state_id' => 36, 'city' => 'Beaverdam'],
                ['state_id' => 36, 'city' => 'Gomer'],
                ['state_id' => 36, 'city' => 'Bluffton'],
                ['state_id' => 36, 'city' => 'Cairo'],
                ['state_id' => 36, 'city' => 'Delphos'],
                ['state_id' => 36, 'city' => 'Harrod'],
                ['state_id' => 36, 'city' => 'Lafayette'],
                ['state_id' => 36, 'city' => 'Spencerville'],
                ['state_id' => 36, 'city' => 'Ashland'],
                ['state_id' => 36, 'city' => 'Hayesville'],
                ['state_id' => 36, 'city' => 'Jeromesville'],
                ['state_id' => 36, 'city' => 'Loudonville'],
                ['state_id' => 36, 'city' => 'Nankin'],
                ['state_id' => 36, 'city' => 'Nova'],
                ['state_id' => 36, 'city' => 'Perrysville'],
                ['state_id' => 36, 'city' => 'Polk'],
                ['state_id' => 36, 'city' => 'Savannah'],
                ['state_id' => 36, 'city' => 'Sullivan'],
                ['state_id' => 36, 'city' => 'Andover'],
                ['state_id' => 36, 'city' => 'Ashtabula'],
                ['state_id' => 36, 'city' => 'Austinburg'],
                ['state_id' => 36, 'city' => 'Conneaut'],
                ['state_id' => 36, 'city' => 'Dorset'],
                ['state_id' => 36, 'city' => 'Geneva'],
                ['state_id' => 36, 'city' => 'Jefferson'],
                ['state_id' => 36, 'city' => 'Kingsville'],
                ['state_id' => 36, 'city' => 'North Kingsville'],
                ['state_id' => 36, 'city' => 'Orwell'],
                ['state_id' => 36, 'city' => 'Pierpont'],
                ['state_id' => 36, 'city' => 'Rock Creek'],
                ['state_id' => 36, 'city' => 'Rome'],
                ['state_id' => 36, 'city' => 'Unionville'],
                ['state_id' => 36, 'city' => 'Williamsfield'],
                ['state_id' => 36, 'city' => 'Windsor'],
                ['state_id' => 36, 'city' => 'Athens'],
                ['state_id' => 36, 'city' => 'Albany'],
                ['state_id' => 36, 'city' => 'Amesville'],
                ['state_id' => 36, 'city' => 'Buchtel'],
                ['state_id' => 36, 'city' => 'Carbondale'],
                ['state_id' => 36, 'city' => 'Chauncey'],
                ['state_id' => 36, 'city' => 'Coolville'],
                ['state_id' => 36, 'city' => 'Glouster'],
                ['state_id' => 36, 'city' => 'Guysville'],
                ['state_id' => 36, 'city' => 'Hockingport'],
                ['state_id' => 36, 'city' => 'Jacksonville'],
                ['state_id' => 36, 'city' => 'Millfield'],
                ['state_id' => 36, 'city' => 'Nelsonville'],
                ['state_id' => 36, 'city' => 'New Marshfield'],
                ['state_id' => 36, 'city' => 'Shade'],
                ['state_id' => 36, 'city' => 'Sharpsburg'],
                ['state_id' => 36, 'city' => 'Stewart'],
                ['state_id' => 36, 'city' => 'The Plains'],
                ['state_id' => 36, 'city' => 'Trimble'],
                ['state_id' => 36, 'city' => 'Buckland'],
                ['state_id' => 36, 'city' => 'Minster'],
                ['state_id' => 36, 'city' => 'New Bremen'],
                ['state_id' => 36, 'city' => 'New Hampshire'],
                ['state_id' => 36, 'city' => 'New Knoxville'],
                ['state_id' => 36, 'city' => 'Saint Johns'],
                ['state_id' => 36, 'city' => 'Saint Marys'],
                ['state_id' => 36, 'city' => 'Uniopolis'],
                ['state_id' => 36, 'city' => 'Wapakoneta'],
                ['state_id' => 36, 'city' => 'Waynesfield'],
                ['state_id' => 36, 'city' => 'Barnesville'],
                ['state_id' => 36, 'city' => 'Belmont'],
                ['state_id' => 36, 'city' => 'Bethesda'],
                ['state_id' => 36, 'city' => 'Morristown'],
                ['state_id' => 36, 'city' => 'Alledonia'],
                ['state_id' => 36, 'city' => 'Barton'],
                ['state_id' => 36, 'city' => 'Bellaire'],
                ['state_id' => 36, 'city' => 'Blaine'],
                ['state_id' => 36, 'city' => 'Bridgeport'],
                ['state_id' => 36, 'city' => 'Colerain'],
                ['state_id' => 36, 'city' => 'Fairpoint'],
                ['state_id' => 36, 'city' => 'Glencoe'],
                ['state_id' => 36, 'city' => 'Jacobsburg'],
                ['state_id' => 36, 'city' => 'Lansing'],
                ['state_id' => 36, 'city' => 'Martins Ferry'],
                ['state_id' => 36, 'city' => 'Maynard'],
                ['state_id' => 36, 'city' => 'Neffs'],
                ['state_id' => 36, 'city' => 'Powhatan Point'],
                ['state_id' => 36, 'city' => 'Shadyside'],
                ['state_id' => 36, 'city' => 'Saint Clairsville'],
                ['state_id' => 36, 'city' => 'Lafferty'],
                ['state_id' => 36, 'city' => 'Warnock'],
                ['state_id' => 36, 'city' => 'Bannock'],
                ['state_id' => 36, 'city' => 'Flushing'],
                ['state_id' => 36, 'city' => 'Piedmont'],
                ['state_id' => 36, 'city' => 'Holloway'],
                ['state_id' => 36, 'city' => 'Aberdeen'],
                ['state_id' => 36, 'city' => 'Decatur'],
                ['state_id' => 36, 'city' => 'Fayetteville'],
                ['state_id' => 36, 'city' => 'Feesburg'],
                ['state_id' => 36, 'city' => 'Georgetown'],
                ['state_id' => 36, 'city' => 'Hamersville'],
                ['state_id' => 36, 'city' => 'Higginsport'],
                ['state_id' => 36, 'city' => 'Mount Orab'],
                ['state_id' => 36, 'city' => 'Ripley'],
                ['state_id' => 36, 'city' => 'Russellville'],
                ['state_id' => 36, 'city' => 'Sardinia'],
                ['state_id' => 36, 'city' => 'Cincinnati'],
                ['state_id' => 36, 'city' => 'College Corner'],
                ['state_id' => 36, 'city' => 'Collinsville'],
                ['state_id' => 36, 'city' => 'Hamilton'],
                ['state_id' => 36, 'city' => 'Fairfield'],
                ['state_id' => 36, 'city' => 'Middletown'],
                ['state_id' => 36, 'city' => 'Monroe'],
                ['state_id' => 36, 'city' => 'Okeana'],
                ['state_id' => 36, 'city' => 'Overpeck'],
                ['state_id' => 36, 'city' => 'Oxford'],
                ['state_id' => 36, 'city' => 'Ross'],
                ['state_id' => 36, 'city' => 'Seven Mile'],
                ['state_id' => 36, 'city' => 'Shandon'],
                ['state_id' => 36, 'city' => 'Somerville'],
                ['state_id' => 36, 'city' => 'Trenton'],
                ['state_id' => 36, 'city' => 'West Chester'],
                ['state_id' => 36, 'city' => 'Augusta'],
                ['state_id' => 36, 'city' => 'Carrollton'],
                ['state_id' => 36, 'city' => 'Dellroy'],
                ['state_id' => 36, 'city' => 'Leesville'],
                ['state_id' => 36, 'city' => 'Malvern'],
                ['state_id' => 36, 'city' => 'Mechanicstown'],
                ['state_id' => 36, 'city' => 'Sherrodsville'],
                ['state_id' => 36, 'city' => 'Cable'],
                ['state_id' => 36, 'city' => 'Mechanicsburg'],
                ['state_id' => 36, 'city' => 'Mingo'],
                ['state_id' => 36, 'city' => 'North Lewisburg'],
                ['state_id' => 36, 'city' => 'Rosewood'],
                ['state_id' => 36, 'city' => 'Saint Paris'],
                ['state_id' => 36, 'city' => 'Urbana'],
                ['state_id' => 36, 'city' => 'Westville'],
                ['state_id' => 36, 'city' => 'Woodstock'],
                ['state_id' => 36, 'city' => 'Christiansburg'],
                ['state_id' => 36, 'city' => 'Catawba'],
                ['state_id' => 36, 'city' => 'Donnelsville'],
                ['state_id' => 36, 'city' => 'Enon'],
                ['state_id' => 36, 'city' => 'Medway'],
                ['state_id' => 36, 'city' => 'New Carlisle'],
                ['state_id' => 36, 'city' => 'North Hampton'],
                ['state_id' => 36, 'city' => 'South Charleston'],
                ['state_id' => 36, 'city' => 'South Vienna'],
                ['state_id' => 36, 'city' => 'Tremont City'],
                ['state_id' => 36, 'city' => 'Springfield'],
                ['state_id' => 36, 'city' => 'Amelia'],
                ['state_id' => 36, 'city' => 'Batavia'],
                ['state_id' => 36, 'city' => 'Bethel'],
                ['state_id' => 36, 'city' => 'Chilo'],
                ['state_id' => 36, 'city' => 'Felicity'],
                ['state_id' => 36, 'city' => 'Goshen'],
                ['state_id' => 36, 'city' => 'Loveland'],
                ['state_id' => 36, 'city' => 'Miamiville'],
                ['state_id' => 36, 'city' => 'Milford'],
                ['state_id' => 36, 'city' => 'Moscow'],
                ['state_id' => 36, 'city' => 'Neville'],
                ['state_id' => 36, 'city' => 'New Richmond'],
                ['state_id' => 36, 'city' => 'Newtonsville'],
                ['state_id' => 36, 'city' => 'Owensville'],
                ['state_id' => 36, 'city' => 'Williamsburg'],
                ['state_id' => 36, 'city' => 'Blanchester'],
                ['state_id' => 36, 'city' => 'Clarksville'],
                ['state_id' => 36, 'city' => 'Cuba'],
                ['state_id' => 36, 'city' => 'Martinsville'],
                ['state_id' => 36, 'city' => 'Midland'],
                ['state_id' => 36, 'city' => 'New Vienna'],
                ['state_id' => 36, 'city' => 'Port William'],
                ['state_id' => 36, 'city' => 'Reesville'],
                ['state_id' => 36, 'city' => 'Sabina'],
                ['state_id' => 36, 'city' => 'Wilmington'],
                ['state_id' => 36, 'city' => 'East Liverpool'],
                ['state_id' => 36, 'city' => 'Salineville'],
                ['state_id' => 36, 'city' => 'Summitville'],
                ['state_id' => 36, 'city' => 'Wellsville'],
                ['state_id' => 36, 'city' => 'Columbiana'],
                ['state_id' => 36, 'city' => 'East Palestine'],
                ['state_id' => 36, 'city' => 'Elkton'],
                ['state_id' => 36, 'city' => 'Hanoverton'],
                ['state_id' => 36, 'city' => 'Kensington'],
                ['state_id' => 36, 'city' => 'Leetonia'],
                ['state_id' => 36, 'city' => 'Lisbon'],
                ['state_id' => 36, 'city' => 'Negley'],
                ['state_id' => 36, 'city' => 'New Waterford'],
                ['state_id' => 36, 'city' => 'Rogers'],
                ['state_id' => 36, 'city' => 'Salem'],
                ['state_id' => 36, 'city' => 'Washingtonville'],
                ['state_id' => 36, 'city' => 'West Point'],
                ['state_id' => 36, 'city' => 'Winona'],
                ['state_id' => 36, 'city' => 'East Rochester'],
                ['state_id' => 36, 'city' => 'Homeworth'],
                ['state_id' => 36, 'city' => 'North Georgetown'],
                ['state_id' => 36, 'city' => 'Bakersville'],
                ['state_id' => 36, 'city' => 'Blissfield'],
                ['state_id' => 36, 'city' => 'Conesville'],
                ['state_id' => 36, 'city' => 'Coshocton'],
                ['state_id' => 36, 'city' => 'Fresno'],
                ['state_id' => 36, 'city' => 'Keene'],
                ['state_id' => 36, 'city' => 'Plainfield'],
                ['state_id' => 36, 'city' => 'Walhonding'],
                ['state_id' => 36, 'city' => 'Warsaw'],
                ['state_id' => 36, 'city' => 'West Lafayette'],
                ['state_id' => 36, 'city' => 'Bucyrus'],
                ['state_id' => 36, 'city' => 'Chatfield'],
                ['state_id' => 36, 'city' => 'Crestline'],
                ['state_id' => 36, 'city' => 'Galion'],
                ['state_id' => 36, 'city' => 'New Washington'],
                ['state_id' => 36, 'city' => 'North Robinson'],
                ['state_id' => 36, 'city' => 'Oceola'],
                ['state_id' => 36, 'city' => 'Sulphur Springs'],
                ['state_id' => 36, 'city' => 'Tiro'],
                ['state_id' => 36, 'city' => 'Berea'],
                ['state_id' => 36, 'city' => 'Chagrin Falls'],
                ['state_id' => 36, 'city' => 'Gates Mills'],
                ['state_id' => 36, 'city' => 'North Olmsted'],
                ['state_id' => 36, 'city' => 'Cleveland'],
                ['state_id' => 36, 'city' => 'Lakewood'],
                ['state_id' => 36, 'city' => 'Rocky River'],
                ['state_id' => 36, 'city' => 'Euclid'],
                ['state_id' => 36, 'city' => 'Beachwood'],
                ['state_id' => 36, 'city' => 'Independence'],
                ['state_id' => 36, 'city' => 'North Royalton'],
                ['state_id' => 36, 'city' => 'Strongsville'],
                ['state_id' => 36, 'city' => 'Maple Heights'],
                ['state_id' => 36, 'city' => 'Olmsted Falls'],
                ['state_id' => 36, 'city' => 'Solon'],
                ['state_id' => 36, 'city' => 'Bay Village'],
                ['state_id' => 36, 'city' => 'Brecksville'],
                ['state_id' => 36, 'city' => 'Brookpark'],
                ['state_id' => 36, 'city' => 'Westlake'],
                ['state_id' => 36, 'city' => 'Bedford'],
                ['state_id' => 36, 'city' => 'Broadview Heights'],
                ['state_id' => 36, 'city' => 'Ansonia'],
                ['state_id' => 36, 'city' => 'Arcanum'],
                ['state_id' => 36, 'city' => 'Gettysburg'],
                ['state_id' => 36, 'city' => 'Greenville'],
                ['state_id' => 36, 'city' => 'Hollansburg'],
                ['state_id' => 36, 'city' => 'New Madison'],
                ['state_id' => 36, 'city' => 'New Weston'],
                ['state_id' => 36, 'city' => 'North Star'],
                ['state_id' => 36, 'city' => 'Osgood'],
                ['state_id' => 36, 'city' => 'Palestine'],
                ['state_id' => 36, 'city' => 'Pitsburg'],
                ['state_id' => 36, 'city' => 'Rossburg'],
                ['state_id' => 36, 'city' => 'Versailles'],
                ['state_id' => 36, 'city' => 'Yorkshire'],
                ['state_id' => 36, 'city' => 'Union City'],
                ['state_id' => 36, 'city' => 'Defiance'],
                ['state_id' => 36, 'city' => 'Evansport'],
                ['state_id' => 36, 'city' => 'Farmer'],
                ['state_id' => 36, 'city' => 'Hicksville'],
                ['state_id' => 36, 'city' => 'Jewell'],
                ['state_id' => 36, 'city' => 'Mark Center'],
                ['state_id' => 36, 'city' => 'Ney'],
                ['state_id' => 36, 'city' => 'Sherwood'],
                ['state_id' => 36, 'city' => 'Ashley'],
                ['state_id' => 36, 'city' => 'Delaware'],
                ['state_id' => 36, 'city' => 'Galena'],
                ['state_id' => 36, 'city' => 'Kilbourne'],
                ['state_id' => 36, 'city' => 'Lewis Center'],
                ['state_id' => 36, 'city' => 'Ostrander'],
                ['state_id' => 36, 'city' => 'Powell'],
                ['state_id' => 36, 'city' => 'Radnor'],
                ['state_id' => 36, 'city' => 'Sunbury'],
                ['state_id' => 36, 'city' => 'Westerville'],
                ['state_id' => 36, 'city' => 'Kelleys Island'],
                ['state_id' => 36, 'city' => 'Vermilion'],
                ['state_id' => 36, 'city' => 'Berlin Heights'],
                ['state_id' => 36, 'city' => 'Birmingham'],
                ['state_id' => 36, 'city' => 'Castalia'],
                ['state_id' => 36, 'city' => 'Huron'],
                ['state_id' => 36, 'city' => 'Milan'],
                ['state_id' => 36, 'city' => 'Sandusky'],
                ['state_id' => 36, 'city' => 'Millersport'],
                ['state_id' => 36, 'city' => 'Amanda'],
                ['state_id' => 36, 'city' => 'Baltimore'],
                ['state_id' => 36, 'city' => 'Bremen'],
                ['state_id' => 36, 'city' => 'Canal Winchester'],
                ['state_id' => 36, 'city' => 'Carroll'],
                ['state_id' => 36, 'city' => 'Lancaster'],
                ['state_id' => 36, 'city' => 'Lithopolis'],
                ['state_id' => 36, 'city' => 'Pickerington'],
                ['state_id' => 36, 'city' => 'Pleasantville'],
                ['state_id' => 36, 'city' => 'Rushville'],
                ['state_id' => 36, 'city' => 'Stoutsville'],
                ['state_id' => 36, 'city' => 'Sugar Grove'],
                ['state_id' => 36, 'city' => 'Thurston'],
                ['state_id' => 36, 'city' => 'Bloomingburg'],
                ['state_id' => 36, 'city' => 'Jeffersonville'],
                ['state_id' => 36, 'city' => 'Milledgeville'],
                ['state_id' => 36, 'city' => 'Washington Court House'],
                ['state_id' => 36, 'city' => 'Amlin'],
                ['state_id' => 36, 'city' => 'Blacklick'],
                ['state_id' => 36, 'city' => 'Dublin'],
                ['state_id' => 36, 'city' => 'Hilliard'],
                ['state_id' => 36, 'city' => 'New Albany'],
                ['state_id' => 36, 'city' => 'Reynoldsburg'],
                ['state_id' => 36, 'city' => 'Columbus'],
                ['state_id' => 36, 'city' => 'Brice'],
                ['state_id' => 36, 'city' => 'Galloway'],
                ['state_id' => 36, 'city' => 'Grove City'],
                ['state_id' => 36, 'city' => 'Groveport'],
                ['state_id' => 36, 'city' => 'Harrisburg'],
                ['state_id' => 36, 'city' => 'Lockbourne'],
                ['state_id' => 36, 'city' => 'Archbold'],
                ['state_id' => 36, 'city' => 'Delta'],
                ['state_id' => 36, 'city' => 'Fayette'],
                ['state_id' => 36, 'city' => 'Lyons'],
                ['state_id' => 36, 'city' => 'Metamora'],
                ['state_id' => 36, 'city' => 'Pettisville'],
                ['state_id' => 36, 'city' => 'Swanton'],
                ['state_id' => 36, 'city' => 'Wauseon'],
                ['state_id' => 36, 'city' => 'Bidwell'],
                ['state_id' => 36, 'city' => 'Cheshire'],
                ['state_id' => 36, 'city' => 'Crown City'],
                ['state_id' => 36, 'city' => 'Gallipolis'],
                ['state_id' => 36, 'city' => 'Kerr'],
                ['state_id' => 36, 'city' => 'Patriot'],
                ['state_id' => 36, 'city' => 'Rio Grande'],
                ['state_id' => 36, 'city' => 'Thurman'],
                ['state_id' => 36, 'city' => 'Vinton'],
                ['state_id' => 36, 'city' => 'Burton'],
                ['state_id' => 36, 'city' => 'Chardon'],
                ['state_id' => 36, 'city' => 'Chesterland'],
                ['state_id' => 36, 'city' => 'East Claridon'],
                ['state_id' => 36, 'city' => 'Huntsburg'],
                ['state_id' => 36, 'city' => 'Middlefield'],
                ['state_id' => 36, 'city' => 'Montville'],
                ['state_id' => 36, 'city' => 'Newbury'],
                ['state_id' => 36, 'city' => 'Novelty'],
                ['state_id' => 36, 'city' => 'Parkman'],
                ['state_id' => 36, 'city' => 'Thompson'],
                ['state_id' => 36, 'city' => 'Alpha'],
                ['state_id' => 36, 'city' => 'Bellbrook'],
                ['state_id' => 36, 'city' => 'Bowersville'],
                ['state_id' => 36, 'city' => 'Cedarville'],
                ['state_id' => 36, 'city' => 'Clifton'],
                ['state_id' => 36, 'city' => 'Fairborn'],
                ['state_id' => 36, 'city' => 'Jamestown'],
                ['state_id' => 36, 'city' => 'Spring Valley'],
                ['state_id' => 36, 'city' => 'Wilberforce'],
                ['state_id' => 36, 'city' => 'Xenia'],
                ['state_id' => 36, 'city' => 'Yellow Springs'],
                ['state_id' => 36, 'city' => 'Dayton'],
                ['state_id' => 36, 'city' => 'Buffalo'],
                ['state_id' => 36, 'city' => 'Byesville'],
                ['state_id' => 36, 'city' => 'Cambridge'],
                ['state_id' => 36, 'city' => 'Cumberland'],
                ['state_id' => 36, 'city' => 'Derwent'],
                ['state_id' => 36, 'city' => 'Fairview'],
                ['state_id' => 36, 'city' => 'Kimbolton'],
                ['state_id' => 36, 'city' => 'Kipling'],
                ['state_id' => 36, 'city' => 'Lore City'],
                ['state_id' => 36, 'city' => 'Old Washington'],
                ['state_id' => 36, 'city' => 'Pleasant City'],
                ['state_id' => 36, 'city' => 'Quaker City'],
                ['state_id' => 36, 'city' => 'Salesville'],
                ['state_id' => 36, 'city' => 'Senecaville'],
                ['state_id' => 36, 'city' => 'Addyston'],
                ['state_id' => 36, 'city' => 'Cleves'],
                ['state_id' => 36, 'city' => 'Harrison'],
                ['state_id' => 36, 'city' => 'Hooven'],
                ['state_id' => 36, 'city' => 'Miamitown'],
                ['state_id' => 36, 'city' => 'Mount Saint Joseph'],
                ['state_id' => 36, 'city' => 'North Bend'],
                ['state_id' => 36, 'city' => 'Camp Dennison'],
                ['state_id' => 36, 'city' => 'Terrace Park'],
                ['state_id' => 36, 'city' => 'Arcadia'],
                ['state_id' => 36, 'city' => 'Arlington'],
                ['state_id' => 36, 'city' => 'Benton Ridge'],
                ['state_id' => 36, 'city' => 'Findlay'],
                ['state_id' => 36, 'city' => 'Jenera'],
                ['state_id' => 36, 'city' => 'Mc Comb'],
                ['state_id' => 36, 'city' => 'Mount Blanchard'],
                ['state_id' => 36, 'city' => 'Mount Cory'],
                ['state_id' => 36, 'city' => 'Rawson'],
                ['state_id' => 36, 'city' => 'Van Buren'],
                ['state_id' => 36, 'city' => 'Vanlue'],
                ['state_id' => 36, 'city' => 'Williamstown'],
                ['state_id' => 36, 'city' => 'Kenton'],
                ['state_id' => 36, 'city' => 'Mount Victory'],
                ['state_id' => 36, 'city' => 'Ridgeway'],
                ['state_id' => 36, 'city' => 'Roundhead'],
                ['state_id' => 36, 'city' => 'Ada'],
                ['state_id' => 36, 'city' => 'Alger'],
                ['state_id' => 36, 'city' => 'Dola'],
                ['state_id' => 36, 'city' => 'Dunkirk'],
                ['state_id' => 36, 'city' => 'Forest'],
                ['state_id' => 36, 'city' => 'Mc Guffey'],
                ['state_id' => 36, 'city' => 'Cadiz'],
                ['state_id' => 36, 'city' => 'Freeport'],
                ['state_id' => 36, 'city' => 'Harrisville'],
                ['state_id' => 36, 'city' => 'Hopedale'],
                ['state_id' => 36, 'city' => 'New Athens'],
                ['state_id' => 36, 'city' => 'New Rumley'],
                ['state_id' => 36, 'city' => 'Jewett'],
                ['state_id' => 36, 'city' => 'Scio'],
                ['state_id' => 36, 'city' => 'Deersville'],
                ['state_id' => 36, 'city' => 'Bowerston'],
                ['state_id' => 36, 'city' => 'Tippecanoe'],
                ['state_id' => 36, 'city' => 'Colton'],
                ['state_id' => 36, 'city' => 'Deshler'],
                ['state_id' => 36, 'city' => 'Grelton'],
                ['state_id' => 36, 'city' => 'Hamler'],
                ['state_id' => 36, 'city' => 'Holgate'],
                ['state_id' => 36, 'city' => 'Liberty Center'],
                ['state_id' => 36, 'city' => 'Mc Clure'],
                ['state_id' => 36, 'city' => 'Malinta'],
                ['state_id' => 36, 'city' => 'Napoleon'],
                ['state_id' => 36, 'city' => 'New Bavaria'],
                ['state_id' => 36, 'city' => 'Okolona'],
                ['state_id' => 36, 'city' => 'Ridgeville Corners'],
                ['state_id' => 36, 'city' => 'Greenfield'],
                ['state_id' => 36, 'city' => 'Highland'],
                ['state_id' => 36, 'city' => 'Hillsboro'],
                ['state_id' => 36, 'city' => 'Leesburg'],
                ['state_id' => 36, 'city' => 'Lynchburg'],
                ['state_id' => 36, 'city' => 'Mowrystown'],
                ['state_id' => 36, 'city' => 'Sinking Spring'],
                ['state_id' => 36, 'city' => 'Carbon Hill'],
                ['state_id' => 36, 'city' => 'Haydenville'],
                ['state_id' => 36, 'city' => 'Laurelville'],
                ['state_id' => 36, 'city' => 'Logan'],
                ['state_id' => 36, 'city' => 'Murray City'],
                ['state_id' => 36, 'city' => 'Rockbridge'],
                ['state_id' => 36, 'city' => 'South Bloomingville'],
                ['state_id' => 36, 'city' => 'Union Furnace'],
                ['state_id' => 36, 'city' => 'Berlin'],
                ['state_id' => 36, 'city' => 'Big Prairie'],
                ['state_id' => 36, 'city' => 'Charm'],
                ['state_id' => 36, 'city' => 'Glenmont'],
                ['state_id' => 36, 'city' => 'Holmesville'],
                ['state_id' => 36, 'city' => 'Killbuck'],
                ['state_id' => 36, 'city' => 'Lakeville'],
                ['state_id' => 36, 'city' => 'Millersburg'],
                ['state_id' => 36, 'city' => 'Mount Hope'],
                ['state_id' => 36, 'city' => 'Nashville'],
                ['state_id' => 36, 'city' => 'Walnut Creek'],
                ['state_id' => 36, 'city' => 'Winesburg'],
                ['state_id' => 36, 'city' => 'Bellevue'],
                ['state_id' => 36, 'city' => 'Collins'],
                ['state_id' => 36, 'city' => 'Greenwich'],
                ['state_id' => 36, 'city' => 'Monroeville'],
                ['state_id' => 36, 'city' => 'New Haven'],
                ['state_id' => 36, 'city' => 'New London'],
                ['state_id' => 36, 'city' => 'North Fairfield'],
                ['state_id' => 36, 'city' => 'Norwalk'],
                ['state_id' => 36, 'city' => 'Willard'],
                ['state_id' => 36, 'city' => 'Wakeman'],
                ['state_id' => 36, 'city' => 'Coalton'],
                ['state_id' => 36, 'city' => 'Jackson'],
                ['state_id' => 36, 'city' => 'Oak Hill'],
                ['state_id' => 36, 'city' => 'Wellston'],
                ['state_id' => 36, 'city' => 'Adena'],
                ['state_id' => 36, 'city' => 'Amsterdam'],
                ['state_id' => 36, 'city' => 'Bergholz'],
                ['state_id' => 36, 'city' => 'Bloomingdale'],
                ['state_id' => 36, 'city' => 'Brilliant'],
                ['state_id' => 36, 'city' => 'Dillonvale'],
                ['state_id' => 36, 'city' => 'East Springfield'],
                ['state_id' => 36, 'city' => 'Empire'],
                ['state_id' => 36, 'city' => 'Hammondsville'],
                ['state_id' => 36, 'city' => 'Irondale'],
                ['state_id' => 36, 'city' => 'Mingo Junction'],
                ['state_id' => 36, 'city' => 'Mount Pleasant'],
                ['state_id' => 36, 'city' => 'Piney Fork'],
                ['state_id' => 36, 'city' => 'Rayland'],
                ['state_id' => 36, 'city' => 'Richmond'],
                ['state_id' => 36, 'city' => 'Smithfield'],
                ['state_id' => 36, 'city' => 'Steubenville'],
                ['state_id' => 36, 'city' => 'Stratton'],
                ['state_id' => 36, 'city' => 'Tiltonsville'],
                ['state_id' => 36, 'city' => 'Toronto'],
                ['state_id' => 36, 'city' => 'Wolf Run'],
                ['state_id' => 36, 'city' => 'Yorkville'],
                ['state_id' => 36, 'city' => 'Bladensburg'],
                ['state_id' => 36, 'city' => 'Brinkhaven'],
                ['state_id' => 36, 'city' => 'Centerburg'],
                ['state_id' => 36, 'city' => 'Danville'],
                ['state_id' => 36, 'city' => 'Fredericktown'],
                ['state_id' => 36, 'city' => 'Gambier'],
                ['state_id' => 36, 'city' => 'Howard'],
                ['state_id' => 36, 'city' => 'Martinsburg'],
                ['state_id' => 36, 'city' => 'Mount Liberty'],
                ['state_id' => 36, 'city' => 'Mount Vernon'],
                ['state_id' => 36, 'city' => 'Grand River'],
                ['state_id' => 36, 'city' => 'Madison'],
                ['state_id' => 36, 'city' => 'Mentor'],
                ['state_id' => 36, 'city' => 'Painesville'],
                ['state_id' => 36, 'city' => 'Perry'],
                ['state_id' => 36, 'city' => 'Wickliffe'],
                ['state_id' => 36, 'city' => 'Willoughby'],
                ['state_id' => 36, 'city' => 'Eastlake'],
                ['state_id' => 36, 'city' => 'Chesapeake'],
                ['state_id' => 36, 'city' => 'Ironton'],
                ['state_id' => 36, 'city' => 'Kitts Hill'],
                ['state_id' => 36, 'city' => 'Pedro'],
                ['state_id' => 36, 'city' => 'Proctorville'],
                ['state_id' => 36, 'city' => 'Rock Camp'],
                ['state_id' => 36, 'city' => 'Scottown'],
                ['state_id' => 36, 'city' => 'South Point'],
                ['state_id' => 36, 'city' => 'Waterloo'],
                ['state_id' => 36, 'city' => 'Willow Wood'],
                ['state_id' => 36, 'city' => 'Alexandria'],
                ['state_id' => 36, 'city' => 'Buckeye Lake'],
                ['state_id' => 36, 'city' => 'Croton'],
                ['state_id' => 36, 'city' => 'Etna'],
                ['state_id' => 36, 'city' => 'Granville'],
                ['state_id' => 36, 'city' => 'Hebron'],
                ['state_id' => 36, 'city' => 'Homer'],
                ['state_id' => 36, 'city' => 'Jacksontown'],
                ['state_id' => 36, 'city' => 'Johnstown'],
                ['state_id' => 36, 'city' => 'Kirkersville'],
                ['state_id' => 36, 'city' => 'Newark'],
                ['state_id' => 36, 'city' => 'Heath'],
                ['state_id' => 36, 'city' => 'Pataskala'],
                ['state_id' => 36, 'city' => 'Saint Louisville'],
                ['state_id' => 36, 'city' => 'Summit Station'],
                ['state_id' => 36, 'city' => 'Utica'],
                ['state_id' => 36, 'city' => 'Brownsville'],
                ['state_id' => 36, 'city' => 'Gratiot'],
                ['state_id' => 36, 'city' => 'Belle Center'],
                ['state_id' => 36, 'city' => 'Bellefontaine'],
                ['state_id' => 36, 'city' => 'De Graff'],
                ['state_id' => 36, 'city' => 'East Liberty'],
                ['state_id' => 36, 'city' => 'Huntsville'],
                ['state_id' => 36, 'city' => 'Lakeview'],
                ['state_id' => 36, 'city' => 'Lewistown'],
                ['state_id' => 36, 'city' => 'Middleburg'],
                ['state_id' => 36, 'city' => 'Quincy'],
                ['state_id' => 36, 'city' => 'Rushsylvania'],
                ['state_id' => 36, 'city' => 'Russells Point'],
                ['state_id' => 36, 'city' => 'West Liberty'],
                ['state_id' => 36, 'city' => 'West Mansfield'],
                ['state_id' => 36, 'city' => 'Zanesfield'],
                ['state_id' => 36, 'city' => 'Amherst'],
                ['state_id' => 36, 'city' => 'Avon'],
                ['state_id' => 36, 'city' => 'Avon Lake'],
                ['state_id' => 36, 'city' => 'Columbia Station'],
                ['state_id' => 36, 'city' => 'Elyria'],
                ['state_id' => 36, 'city' => 'North Ridgeville'],
                ['state_id' => 36, 'city' => 'Grafton'],
                ['state_id' => 36, 'city' => 'Kipton'],
                ['state_id' => 36, 'city' => 'Lagrange'],
                ['state_id' => 36, 'city' => 'Lorain'],
                ['state_id' => 36, 'city' => 'Sheffield Lake'],
                ['state_id' => 36, 'city' => 'Oberlin'],
                ['state_id' => 36, 'city' => 'Wellington'],
                ['state_id' => 36, 'city' => 'Harbor View'],
                ['state_id' => 36, 'city' => 'Berkey'],
                ['state_id' => 36, 'city' => 'Holland'],
                ['state_id' => 36, 'city' => 'Maumee'],
                ['state_id' => 36, 'city' => 'Monclova'],
                ['state_id' => 36, 'city' => 'Neapolis'],
                ['state_id' => 36, 'city' => 'Sylvania'],
                ['state_id' => 36, 'city' => 'Waterville'],
                ['state_id' => 36, 'city' => 'Whitehouse'],
                ['state_id' => 36, 'city' => 'Toledo'],
                ['state_id' => 36, 'city' => 'Oregon'],
                ['state_id' => 36, 'city' => 'Plain City'],
                ['state_id' => 36, 'city' => 'London'],
                ['state_id' => 36, 'city' => 'Mount Sterling'],
                ['state_id' => 36, 'city' => 'Sedalia'],
                ['state_id' => 36, 'city' => 'South Solon'],
                ['state_id' => 36, 'city' => 'West Jefferson'],
                ['state_id' => 36, 'city' => 'Berlin Center'],
                ['state_id' => 36, 'city' => 'Campbell'],
                ['state_id' => 36, 'city' => 'Canfield'],
                ['state_id' => 36, 'city' => 'Ellsworth'],
                ['state_id' => 36, 'city' => 'Greenford'],
                ['state_id' => 36, 'city' => 'Lake Milton'],
                ['state_id' => 36, 'city' => 'Lowellville'],
                ['state_id' => 36, 'city' => 'New Middletown'],
                ['state_id' => 36, 'city' => 'New Springfield'],
                ['state_id' => 36, 'city' => 'North Benton'],
                ['state_id' => 36, 'city' => 'North Jackson'],
                ['state_id' => 36, 'city' => 'North Lima'],
                ['state_id' => 36, 'city' => 'Petersburg'],
                ['state_id' => 36, 'city' => 'Struthers'],
                ['state_id' => 36, 'city' => 'Youngstown'],
                ['state_id' => 36, 'city' => 'Beloit'],
                ['state_id' => 36, 'city' => 'Damascus'],
                ['state_id' => 36, 'city' => 'Sebring'],
                ['state_id' => 36, 'city' => 'Marion'],
                ['state_id' => 36, 'city' => 'Caledonia'],
                ['state_id' => 36, 'city' => 'Green Camp'],
                ['state_id' => 36, 'city' => 'La Rue'],
                ['state_id' => 36, 'city' => 'Martel'],
                ['state_id' => 36, 'city' => 'Morral'],
                ['state_id' => 36, 'city' => 'New Bloomington'],
                ['state_id' => 36, 'city' => 'Prospect'],
                ['state_id' => 36, 'city' => 'Waldo'],
                ['state_id' => 36, 'city' => 'Brunswick'],
                ['state_id' => 36, 'city' => 'Chippewa Lake'],
                ['state_id' => 36, 'city' => 'Hinckley'],
                ['state_id' => 36, 'city' => 'Homerville'],
                ['state_id' => 36, 'city' => 'Westfield Center'],
                ['state_id' => 36, 'city' => 'Litchfield'],
                ['state_id' => 36, 'city' => 'Lodi'],
                ['state_id' => 36, 'city' => 'Medina'],
                ['state_id' => 36, 'city' => 'Seville'],
                ['state_id' => 36, 'city' => 'Sharon Center'],
                ['state_id' => 36, 'city' => 'Spencer'],
                ['state_id' => 36, 'city' => 'Valley City'],
                ['state_id' => 36, 'city' => 'Wadsworth'],
                ['state_id' => 36, 'city' => 'Chester'],
                ['state_id' => 36, 'city' => 'Langsville'],
                ['state_id' => 36, 'city' => 'Long Bottom'],
                ['state_id' => 36, 'city' => 'Middleport'],
                ['state_id' => 36, 'city' => 'Pomeroy'],
                ['state_id' => 36, 'city' => 'Portland'],
                ['state_id' => 36, 'city' => 'Racine'],
                ['state_id' => 36, 'city' => 'Reedsville'],
                ['state_id' => 36, 'city' => 'Rutland'],
                ['state_id' => 36, 'city' => 'Syracuse'],
                ['state_id' => 36, 'city' => 'Tuppers Plains'],
                ['state_id' => 36, 'city' => 'Burkettsville'],
                ['state_id' => 36, 'city' => 'Celina'],
                ['state_id' => 36, 'city' => 'Chickasaw'],
                ['state_id' => 36, 'city' => 'Coldwater'],
                ['state_id' => 36, 'city' => 'Fort Recovery'],
                ['state_id' => 36, 'city' => 'Maria Stein'],
                ['state_id' => 36, 'city' => 'Mendon'],
                ['state_id' => 36, 'city' => 'Montezuma'],
                ['state_id' => 36, 'city' => 'Rockford'],
                ['state_id' => 36, 'city' => 'Saint Henry'],
                ['state_id' => 36, 'city' => 'Bradford'],
                ['state_id' => 36, 'city' => 'Casstown'],
                ['state_id' => 36, 'city' => 'Conover'],
                ['state_id' => 36, 'city' => 'Covington'],
                ['state_id' => 36, 'city' => 'Fletcher'],
                ['state_id' => 36, 'city' => 'Laura'],
                ['state_id' => 36, 'city' => 'Ludlow Falls'],
                ['state_id' => 36, 'city' => 'Piqua'],
                ['state_id' => 36, 'city' => 'Pleasant Hill'],
                ['state_id' => 36, 'city' => 'Potsdam'],
                ['state_id' => 36, 'city' => 'Tipp City'],
                ['state_id' => 36, 'city' => 'Troy'],
                ['state_id' => 36, 'city' => 'West Milton'],
                ['state_id' => 36, 'city' => 'Beallsville'],
                ['state_id' => 36, 'city' => 'Jerusalem'],
                ['state_id' => 36, 'city' => 'Laings'],
                ['state_id' => 36, 'city' => 'Lewisville'],
                ['state_id' => 36, 'city' => 'Malaga'],
                ['state_id' => 36, 'city' => 'Stafford'],
                ['state_id' => 36, 'city' => 'Woodsfield'],
                ['state_id' => 36, 'city' => 'Cameron'],
                ['state_id' => 36, 'city' => 'Clarington'],
                ['state_id' => 36, 'city' => 'Hannibal'],
                ['state_id' => 36, 'city' => 'Sardis'],
                ['state_id' => 36, 'city' => 'Graysville'],
                ['state_id' => 36, 'city' => 'Brookville'],
                ['state_id' => 36, 'city' => 'Clayton'],
                ['state_id' => 36, 'city' => 'Englewood'],
                ['state_id' => 36, 'city' => 'Farmersville'],
                ['state_id' => 36, 'city' => 'Germantown'],
                ['state_id' => 36, 'city' => 'Miamisburg'],
                ['state_id' => 36, 'city' => 'New Lebanon'],
                ['state_id' => 36, 'city' => 'Phillipsburg'],
                ['state_id' => 36, 'city' => 'Vandalia'],
                ['state_id' => 36, 'city' => 'Chesterhill'],
                ['state_id' => 36, 'city' => 'Mcconnelsville'],
                ['state_id' => 36, 'city' => 'Malta'],
                ['state_id' => 36, 'city' => 'Stockport'],
                ['state_id' => 36, 'city' => 'Cardington'],
                ['state_id' => 36, 'city' => 'Chesterville'],
                ['state_id' => 36, 'city' => 'Edison'],
                ['state_id' => 36, 'city' => 'Fulton'],
                ['state_id' => 36, 'city' => 'Iberia'],
                ['state_id' => 36, 'city' => 'Marengo'],
                ['state_id' => 36, 'city' => 'Mount Gilead'],
                ['state_id' => 36, 'city' => 'Shauck'],
                ['state_id' => 36, 'city' => 'Sparta'],
                ['state_id' => 36, 'city' => 'Zanesville'],
                ['state_id' => 36, 'city' => 'Blue Rock'],
                ['state_id' => 36, 'city' => 'Chandlersville'],
                ['state_id' => 36, 'city' => 'Duncan Falls'],
                ['state_id' => 36, 'city' => 'East Fultonham'],
                ['state_id' => 36, 'city' => 'Fultonham'],
                ['state_id' => 36, 'city' => 'Hopewell'],
                ['state_id' => 36, 'city' => 'New Concord'],
                ['state_id' => 36, 'city' => 'Norwich'],
                ['state_id' => 36, 'city' => 'Philo'],
                ['state_id' => 36, 'city' => 'Roseville'],
                ['state_id' => 36, 'city' => 'White Cottage'],
                ['state_id' => 36, 'city' => 'Adamsville'],
                ['state_id' => 36, 'city' => 'Dresden'],
                ['state_id' => 36, 'city' => 'Frazeysburg'],
                ['state_id' => 36, 'city' => 'Nashport'],
                ['state_id' => 36, 'city' => 'Trinway'],
                ['state_id' => 36, 'city' => 'Ava'],
                ['state_id' => 36, 'city' => 'Belle Valley'],
                ['state_id' => 36, 'city' => 'Caldwell'],
                ['state_id' => 36, 'city' => 'Sarahsville'],
                ['state_id' => 36, 'city' => 'Summerfield'],
                ['state_id' => 36, 'city' => 'Dexter City'],
                ['state_id' => 36, 'city' => 'Clay Center'],
                ['state_id' => 36, 'city' => 'Curtice'],
                ['state_id' => 36, 'city' => 'Elmore'],
                ['state_id' => 36, 'city' => 'Genoa'],
                ['state_id' => 36, 'city' => 'Graytown'],
                ['state_id' => 36, 'city' => 'Gypsum'],
                ['state_id' => 36, 'city' => 'Isle Saint George'],
                ['state_id' => 36, 'city' => 'Lacarne'],
                ['state_id' => 36, 'city' => 'Lakeside Marblehead'],
                ['state_id' => 36, 'city' => 'Martin'],
                ['state_id' => 36, 'city' => 'Middle Bass'],
                ['state_id' => 36, 'city' => 'Oak Harbor'],
                ['state_id' => 36, 'city' => 'Port Clinton'],
                ['state_id' => 36, 'city' => 'Put In Bay'],
                ['state_id' => 36, 'city' => 'Rocky Ridge'],
                ['state_id' => 36, 'city' => 'Williston'],
                ['state_id' => 36, 'city' => 'Antwerp'],
                ['state_id' => 36, 'city' => 'Cecil'],
                ['state_id' => 36, 'city' => 'Grover Hill'],
                ['state_id' => 36, 'city' => 'Haviland'],
                ['state_id' => 36, 'city' => 'Latty'],
                ['state_id' => 36, 'city' => 'Melrose'],
                ['state_id' => 36, 'city' => 'Oakwood'],
                ['state_id' => 36, 'city' => 'Paulding'],
                ['state_id' => 36, 'city' => 'Payne'],
                ['state_id' => 36, 'city' => 'Thornville'],
                ['state_id' => 36, 'city' => 'Corning'],
                ['state_id' => 36, 'city' => 'Crooksville'],
                ['state_id' => 36, 'city' => 'Glenford'],
                ['state_id' => 36, 'city' => 'Junction City'],
                ['state_id' => 36, 'city' => 'Mount Perry'],
                ['state_id' => 36, 'city' => 'Moxahala'],
                ['state_id' => 36, 'city' => 'New Lexington'],
                ['state_id' => 36, 'city' => 'New Straitsville'],
                ['state_id' => 36, 'city' => 'Shawnee'],
                ['state_id' => 36, 'city' => 'Somerset'],
                ['state_id' => 36, 'city' => 'Ashville'],
                ['state_id' => 36, 'city' => 'Circleville'],
                ['state_id' => 36, 'city' => 'Commercial Point'],
                ['state_id' => 36, 'city' => 'Derby'],
                ['state_id' => 36, 'city' => 'New Holland'],
                ['state_id' => 36, 'city' => 'Orient'],
                ['state_id' => 36, 'city' => 'Tarlton'],
                ['state_id' => 36, 'city' => 'Williamsport'],
                ['state_id' => 36, 'city' => 'Beaver'],
                ['state_id' => 36, 'city' => 'Cynthiana'],
                ['state_id' => 36, 'city' => 'Jasper'],
                ['state_id' => 36, 'city' => 'Latham'],
                ['state_id' => 36, 'city' => 'Piketon'],
                ['state_id' => 36, 'city' => 'Stockdale'],
                ['state_id' => 36, 'city' => 'Wakefield'],
                ['state_id' => 36, 'city' => 'Waverly'],
                ['state_id' => 36, 'city' => 'Atwater'],
                ['state_id' => 36, 'city' => 'Aurora'],
                ['state_id' => 36, 'city' => 'Brady Lake'],
                ['state_id' => 36, 'city' => 'Garrettsville'],
                ['state_id' => 36, 'city' => 'Hiram'],
                ['state_id' => 36, 'city' => 'Kent'],
                ['state_id' => 36, 'city' => 'Streetsboro'],
                ['state_id' => 36, 'city' => 'Mantua'],
                ['state_id' => 36, 'city' => 'Randolph'],
                ['state_id' => 36, 'city' => 'Ravenna'],
                ['state_id' => 36, 'city' => 'Rootstown'],
                ['state_id' => 36, 'city' => 'Wayland'],
                ['state_id' => 36, 'city' => 'Windham'],
                ['state_id' => 36, 'city' => 'Deerfield'],
                ['state_id' => 36, 'city' => 'Diamond'],
                ['state_id' => 36, 'city' => 'West Elkton'],
                ['state_id' => 36, 'city' => 'Camden'],
                ['state_id' => 36, 'city' => 'Eaton'],
                ['state_id' => 36, 'city' => 'Eldorado'],
                ['state_id' => 36, 'city' => 'Gratis'],
                ['state_id' => 36, 'city' => 'Lewisburg'],
                ['state_id' => 36, 'city' => 'New Paris'],
                ['state_id' => 36, 'city' => 'Verona'],
                ['state_id' => 36, 'city' => 'West Alexandria'],
                ['state_id' => 36, 'city' => 'West Manchester'],
                ['state_id' => 36, 'city' => 'Belmore'],
                ['state_id' => 36, 'city' => 'Cloverdale'],
                ['state_id' => 36, 'city' => 'Columbus Grove'],
                ['state_id' => 36, 'city' => 'Continental'],
                ['state_id' => 36, 'city' => 'Dupont'],
                ['state_id' => 36, 'city' => 'Fort Jennings'],
                ['state_id' => 36, 'city' => 'Glandorf'],
                ['state_id' => 36, 'city' => 'Kalida'],
                ['state_id' => 36, 'city' => 'Leipsic'],
                ['state_id' => 36, 'city' => 'Miller City'],
                ['state_id' => 36, 'city' => 'Ottawa'],
                ['state_id' => 36, 'city' => 'Ottoville'],
                ['state_id' => 36, 'city' => 'Pandora'],
                ['state_id' => 36, 'city' => 'Vaughnsville'],
                ['state_id' => 36, 'city' => 'Bellville'],
                ['state_id' => 36, 'city' => 'Butler'],
                ['state_id' => 36, 'city' => 'Lucas'],
                ['state_id' => 36, 'city' => 'Ontario'],
                ['state_id' => 36, 'city' => 'Plymouth'],
                ['state_id' => 36, 'city' => 'Shelby'],
                ['state_id' => 36, 'city' => 'Shiloh'],
                ['state_id' => 36, 'city' => 'Mansfield'],
                ['state_id' => 36, 'city' => 'Adelphi'],
                ['state_id' => 36, 'city' => 'Clarksburg'],
                ['state_id' => 36, 'city' => 'Chillicothe'],
                ['state_id' => 36, 'city' => 'Bainbridge'],
                ['state_id' => 36, 'city' => 'Bourneville'],
                ['state_id' => 36, 'city' => 'Frankfort'],
                ['state_id' => 36, 'city' => 'Hallsville'],
                ['state_id' => 36, 'city' => 'Kingston'],
                ['state_id' => 36, 'city' => 'Londonderry'],
                ['state_id' => 36, 'city' => 'Richmond Dale'],
                ['state_id' => 36, 'city' => 'South Salem'],
                ['state_id' => 36, 'city' => 'Burgoon'],
                ['state_id' => 36, 'city' => 'Clyde'],
                ['state_id' => 36, 'city' => 'Fremont'],
                ['state_id' => 36, 'city' => 'Gibsonburg'],
                ['state_id' => 36, 'city' => 'Helena'],
                ['state_id' => 36, 'city' => 'Lindsey'],
                ['state_id' => 36, 'city' => 'Vickery'],
                ['state_id' => 36, 'city' => 'Woodville'],
                ['state_id' => 36, 'city' => 'Franklin Furnace'],
                ['state_id' => 36, 'city' => 'Friendship'],
                ['state_id' => 36, 'city' => 'Haverhill'],
                ['state_id' => 36, 'city' => 'Lucasville'],
                ['state_id' => 36, 'city' => 'Mc Dermott'],
                ['state_id' => 36, 'city' => 'Minford'],
                ['state_id' => 36, 'city' => 'Otway'],
                ['state_id' => 36, 'city' => 'Portsmouth'],
                ['state_id' => 36, 'city' => 'West Portsmouth'],
                ['state_id' => 36, 'city' => 'Rarden'],
                ['state_id' => 36, 'city' => 'Scioto Furnace'],
                ['state_id' => 36, 'city' => 'South Webster'],
                ['state_id' => 36, 'city' => 'Stout'],
                ['state_id' => 36, 'city' => 'Wheelersburg'],
                ['state_id' => 36, 'city' => 'Alvada'],
                ['state_id' => 36, 'city' => 'Attica'],
                ['state_id' => 36, 'city' => 'Bascom'],
                ['state_id' => 36, 'city' => 'Bettsville'],
                ['state_id' => 36, 'city' => 'Bloomville'],
                ['state_id' => 36, 'city' => 'Flat Rock'],
                ['state_id' => 36, 'city' => 'Fostoria'],
                ['state_id' => 36, 'city' => 'Green Springs'],
                ['state_id' => 36, 'city' => 'Kansas'],
                ['state_id' => 36, 'city' => 'Melmore'],
                ['state_id' => 36, 'city' => 'New Riegel'],
                ['state_id' => 36, 'city' => 'Old Fort'],
                ['state_id' => 36, 'city' => 'Republic'],
                ['state_id' => 36, 'city' => 'Tiffin'],
                ['state_id' => 36, 'city' => 'Anna'],
                ['state_id' => 36, 'city' => 'Botkins'],
                ['state_id' => 36, 'city' => 'Houston'],
                ['state_id' => 36, 'city' => 'Jackson Center'],
                ['state_id' => 36, 'city' => 'Kettlersville'],
                ['state_id' => 36, 'city' => 'Maplewood'],
                ['state_id' => 36, 'city' => 'Pemberton'],
                ['state_id' => 36, 'city' => 'Port Jefferson'],
                ['state_id' => 36, 'city' => 'Russia'],
                ['state_id' => 36, 'city' => 'Sidney'],
                ['state_id' => 36, 'city' => 'Fort Loramie'],
                ['state_id' => 36, 'city' => 'Alliance'],
                ['state_id' => 36, 'city' => 'Beach City'],
                ['state_id' => 36, 'city' => 'Brewster'],
                ['state_id' => 36, 'city' => 'Canal Fulton'],
                ['state_id' => 36, 'city' => 'East Sparta'],
                ['state_id' => 36, 'city' => 'Greentown'],
                ['state_id' => 36, 'city' => 'Hartville'],
                ['state_id' => 36, 'city' => 'Limaville'],
                ['state_id' => 36, 'city' => 'Louisville'],
                ['state_id' => 36, 'city' => 'Magnolia'],
                ['state_id' => 36, 'city' => 'Massillon'],
                ['state_id' => 36, 'city' => 'Maximo'],
                ['state_id' => 36, 'city' => 'Middlebranch'],
                ['state_id' => 36, 'city' => 'Minerva'],
                ['state_id' => 36, 'city' => 'Navarre'],
                ['state_id' => 36, 'city' => 'North Lawrence'],
                ['state_id' => 36, 'city' => 'Paris'],
                ['state_id' => 36, 'city' => 'Robertsville'],
                ['state_id' => 36, 'city' => 'Waynesburg'],
                ['state_id' => 36, 'city' => 'Wilmot'],
                ['state_id' => 36, 'city' => 'Canton'],
                ['state_id' => 36, 'city' => 'North Canton'],
                ['state_id' => 36, 'city' => 'East Canton'],
                ['state_id' => 36, 'city' => 'Macedonia'],
                ['state_id' => 36, 'city' => 'Northfield'],
                ['state_id' => 36, 'city' => 'Twinsburg'],
                ['state_id' => 36, 'city' => 'Barberton'],
                ['state_id' => 36, 'city' => 'Bath'],
                ['state_id' => 36, 'city' => 'Clinton'],
                ['state_id' => 36, 'city' => 'Cuyahoga Falls'],
                ['state_id' => 36, 'city' => 'Stow'],
                ['state_id' => 36, 'city' => 'Green'],
                ['state_id' => 36, 'city' => 'Hudson'],
                ['state_id' => 36, 'city' => 'Lakemore'],
                ['state_id' => 36, 'city' => 'Mogadore'],
                ['state_id' => 36, 'city' => 'Munroe Falls'],
                ['state_id' => 36, 'city' => 'Peninsula'],
                ['state_id' => 36, 'city' => 'Tallmadge'],
                ['state_id' => 36, 'city' => 'Richfield'],
                ['state_id' => 36, 'city' => 'Akron'],
                ['state_id' => 36, 'city' => 'Fairlawn'],
                ['state_id' => 36, 'city' => 'Uniontown'],
                ['state_id' => 36, 'city' => 'Bristolville'],
                ['state_id' => 36, 'city' => 'Brookfield'],
                ['state_id' => 36, 'city' => 'Burghill'],
                ['state_id' => 36, 'city' => 'Cortland'],
                ['state_id' => 36, 'city' => 'Farmdale'],
                ['state_id' => 36, 'city' => 'Fowler'],
                ['state_id' => 36, 'city' => 'Girard'],
                ['state_id' => 36, 'city' => 'Hartford'],
                ['state_id' => 36, 'city' => 'Hubbard'],
                ['state_id' => 36, 'city' => 'Kinsman'],
                ['state_id' => 36, 'city' => 'Leavittsburg'],
                ['state_id' => 36, 'city' => 'Mc Donald'],
                ['state_id' => 36, 'city' => 'Masury'],
                ['state_id' => 36, 'city' => 'Mesopotamia'],
                ['state_id' => 36, 'city' => 'Mineral Ridge'],
                ['state_id' => 36, 'city' => 'Newton Falls'],
                ['state_id' => 36, 'city' => 'Niles'],
                ['state_id' => 36, 'city' => 'North Bloomfield'],
                ['state_id' => 36, 'city' => 'Orangeville'],
                ['state_id' => 36, 'city' => 'Southington'],
                ['state_id' => 36, 'city' => 'Vienna'],
                ['state_id' => 36, 'city' => 'Warren'],
                ['state_id' => 36, 'city' => 'West Farmington'],
                ['state_id' => 36, 'city' => 'Baltic'],
                ['state_id' => 36, 'city' => 'Newcomerstown'],
                ['state_id' => 36, 'city' => 'Port Washington'],
                ['state_id' => 36, 'city' => 'Stone Creek'],
                ['state_id' => 36, 'city' => 'Bolivar'],
                ['state_id' => 36, 'city' => 'Dennison'],
                ['state_id' => 36, 'city' => 'Dover'],
                ['state_id' => 36, 'city' => 'Dundee'],
                ['state_id' => 36, 'city' => 'Gnadenhutten'],
                ['state_id' => 36, 'city' => 'Midvale'],
                ['state_id' => 36, 'city' => 'Mineral City'],
                ['state_id' => 36, 'city' => 'New Philadelphia'],
                ['state_id' => 36, 'city' => 'Sandyville'],
                ['state_id' => 36, 'city' => 'Somerdale'],
                ['state_id' => 36, 'city' => 'Stillwater'],
                ['state_id' => 36, 'city' => 'Strasburg'],
                ['state_id' => 36, 'city' => 'Sugarcreek'],
                ['state_id' => 36, 'city' => 'Tuscarawas'],
                ['state_id' => 36, 'city' => 'Uhrichsville'],
                ['state_id' => 36, 'city' => 'Zoar'],
                ['state_id' => 36, 'city' => 'Broadway'],
                ['state_id' => 36, 'city' => 'Irwin'],
                ['state_id' => 36, 'city' => 'Magnetic Springs'],
                ['state_id' => 36, 'city' => 'Marysville'],
                ['state_id' => 36, 'city' => 'Milford Center'],
                ['state_id' => 36, 'city' => 'Raymond'],
                ['state_id' => 36, 'city' => 'Unionville Center'],
                ['state_id' => 36, 'city' => 'Richwood'],
                ['state_id' => 36, 'city' => 'Convoy'],
                ['state_id' => 36, 'city' => 'Elgin'],
                ['state_id' => 36, 'city' => 'Middle Point'],
                ['state_id' => 36, 'city' => 'Ohio City'],
                ['state_id' => 36, 'city' => 'Scott'],
                ['state_id' => 36, 'city' => 'Van Wert'],
                ['state_id' => 36, 'city' => 'Venedocia'],
                ['state_id' => 36, 'city' => 'Willshire'],
                ['state_id' => 36, 'city' => 'Wren'],
                ['state_id' => 36, 'city' => 'Creola'],
                ['state_id' => 36, 'city' => 'Hamden'],
                ['state_id' => 36, 'city' => 'Mc Arthur'],
                ['state_id' => 36, 'city' => 'New Plymouth'],
                ['state_id' => 36, 'city' => 'Ray'],
                ['state_id' => 36, 'city' => 'Wilkesville'],
                ['state_id' => 36, 'city' => 'Zaleski'],
                ['state_id' => 36, 'city' => 'Franklin'],
                ['state_id' => 36, 'city' => 'Harveysburg'],
                ['state_id' => 36, 'city' => 'Kings Mills'],
                ['state_id' => 36, 'city' => 'Lebanon'],
                ['state_id' => 36, 'city' => 'Maineville'],
                ['state_id' => 36, 'city' => 'Mason'],
                ['state_id' => 36, 'city' => 'Oregonia'],
                ['state_id' => 36, 'city' => 'South Lebanon'],
                ['state_id' => 36, 'city' => 'Springboro'],
                ['state_id' => 36, 'city' => 'Waynesville'],
                ['state_id' => 36, 'city' => 'Morrow'],
                ['state_id' => 36, 'city' => 'Pleasant Plain'],
                ['state_id' => 36, 'city' => 'Barlow'],
                ['state_id' => 36, 'city' => 'Bartlett'],
                ['state_id' => 36, 'city' => 'Belpre'],
                ['state_id' => 36, 'city' => 'Beverly'],
                ['state_id' => 36, 'city' => 'Coal Run'],
                ['state_id' => 36, 'city' => 'Cutler'],
                ['state_id' => 36, 'city' => 'Fleming'],
                ['state_id' => 36, 'city' => 'Little Hocking'],
                ['state_id' => 36, 'city' => 'Lowell'],
                ['state_id' => 36, 'city' => 'Lower Salem'],
                ['state_id' => 36, 'city' => 'Macksburg'],
                ['state_id' => 36, 'city' => 'Marietta'],
                ['state_id' => 36, 'city' => 'New Matamoras'],
                ['state_id' => 36, 'city' => 'Newport'],
                ['state_id' => 36, 'city' => 'Reno'],
                ['state_id' => 36, 'city' => 'Vincent'],
                ['state_id' => 36, 'city' => 'Waterford'],
                ['state_id' => 36, 'city' => 'Watertown'],
                ['state_id' => 36, 'city' => 'Whipple'],
                ['state_id' => 36, 'city' => 'Wingett Run'],
                ['state_id' => 36, 'city' => 'Burbank'],
                ['state_id' => 36, 'city' => 'Creston'],
                ['state_id' => 36, 'city' => 'Doylestown'],
                ['state_id' => 36, 'city' => 'Rittman'],
                ['state_id' => 36, 'city' => 'Sterling'],
                ['state_id' => 36, 'city' => 'West Salem'],
                ['state_id' => 36, 'city' => 'Apple Creek'],
                ['state_id' => 36, 'city' => 'Dalton'],
                ['state_id' => 36, 'city' => 'Fredericksburg'],
                ['state_id' => 36, 'city' => 'Kidron'],
                ['state_id' => 36, 'city' => 'Marshallville'],
                ['state_id' => 36, 'city' => 'Mount Eaton'],
                ['state_id' => 36, 'city' => 'Orrville'],
                ['state_id' => 36, 'city' => 'Shreve'],
                ['state_id' => 36, 'city' => 'Smithville'],
                ['state_id' => 36, 'city' => 'Wooster'],
                ['state_id' => 36, 'city' => 'Alvordton'],
                ['state_id' => 36, 'city' => 'Blakeslee'],
                ['state_id' => 36, 'city' => 'Bryan'],
                ['state_id' => 36, 'city' => 'Edgerton'],
                ['state_id' => 36, 'city' => 'Edon'],
                ['state_id' => 36, 'city' => 'Kunkle'],
                ['state_id' => 36, 'city' => 'Montpelier'],
                ['state_id' => 36, 'city' => 'Pioneer'],
                ['state_id' => 36, 'city' => 'Stryker'],
                ['state_id' => 36, 'city' => 'West Unity'],
                ['state_id' => 36, 'city' => 'Bowling Green'],
                ['state_id' => 36, 'city' => 'Bradner'],
                ['state_id' => 36, 'city' => 'Cygnet'],
                ['state_id' => 36, 'city' => 'Dunbridge'],
                ['state_id' => 36, 'city' => 'Jerry City'],
                ['state_id' => 36, 'city' => 'Lemoyne'],
                ['state_id' => 36, 'city' => 'Luckey'],
                ['state_id' => 36, 'city' => 'Millbury'],
                ['state_id' => 36, 'city' => 'Pemberville'],
                ['state_id' => 36, 'city' => 'Portage'],
                ['state_id' => 36, 'city' => 'Risingsun'],
                ['state_id' => 36, 'city' => 'Rossford'],
                ['state_id' => 36, 'city' => 'Rudolph'],
                ['state_id' => 36, 'city' => 'Stony Ridge'],
                ['state_id' => 36, 'city' => 'Walbridge'],
                ['state_id' => 36, 'city' => 'Wayne'],
                ['state_id' => 36, 'city' => 'West Millgrove'],
                ['state_id' => 36, 'city' => 'Custar'],
                ['state_id' => 36, 'city' => 'Grand Rapids'],
                ['state_id' => 36, 'city' => 'Haskins'],
                ['state_id' => 36, 'city' => 'Hoytville'],
                ['state_id' => 36, 'city' => 'Milton Center'],
                ['state_id' => 36, 'city' => 'Perrysburg'],
                ['state_id' => 36, 'city' => 'Tontogany'],
                ['state_id' => 36, 'city' => 'Weston'],
                ['state_id' => 36, 'city' => 'Northwood'],
                ['state_id' => 36, 'city' => 'Bloomdale'],
                ['state_id' => 36, 'city' => 'North Baltimore'],
                ['state_id' => 36, 'city' => 'Carey'],
                ['state_id' => 36, 'city' => 'Harpster'],
                ['state_id' => 36, 'city' => 'Kirby'],
                ['state_id' => 36, 'city' => 'Upper Sandusky'],
                ['state_id' => 36, 'city' => 'Wharton'],
                ['state_id' => 36, 'city' => 'Mc Cutchenville'],
                ['state_id' => 36, 'city' => 'Nevada'],
                ['state_id' => 36, 'city' => 'Sycamore', 'state_id' => 36]
            ];
            foreach ($cities as $key => $city) {
                City::create($city);
            }
        }
    }
}
